# ALL_scores

## Install and clean

In [ ]:
# !pip install implicit
# !pip install lightfm-next
# !pip install catboost

In [ ]:
import json
import pandas as pd
import random
from tqdm import tqdm
from google.colab import drive
import matplotlib.pyplot as plt
from scipy.sparse import coo_matrix

SEED = 22
drive.mount('/content/drive')
import numpy as np
pd.options.display.max_rows = 50
pd.options.display.max_columns = 50
KS = (5, 10, 20, 50, 100)

Mounted at /content/drive

In [ ]:
csv_file_path = '/content/drive/MyDrive/final_yelp_PA_FL.parquet'
df = pd.read_parquet(csv_file_path)
df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,name,address,city,state,postal_code,latitude,longitude,stars_business,review_count,is_open,attributes,categories,hours,name_user,review_count_user,yelping_since,useful_user,funny_user,cool_user,elite,friends,fans,average_stars,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,checkin_count,compliment_count
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,19454,40.210196,-75.223639,3.0,169,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Friday': '7:30-15:0', 'Monday': '7:30-15:0',...",Melanie,33,2016-01-13 17:20:44,32,3,8,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",0,4.06,0,0,0,0,0,0,0,1,1,0,0,177.0,0.0
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18,Body Cycle Spinning Studio,"1923 Chestnut St, 2nd Fl",Philadelphia,PA,19119,39.952103,-75.172753,5.0,144,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Friday': '6:0-19:30', 'Monday': '6:30-20:30'...",Erin,10,2011-03-07 19:45:15,6,1,2,,"7uYgWwryg8KH33i1SLJUTQ, 0mGJMNL8o2AY4BT1d4TTDQ...",0,4.30,0,0,0,0,0,0,0,0,0,0,0,497.0,0.0
2,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,5.0,2,2,2,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,The N Crowd,111 S Independence Mall E,Philadelphia,PA,19106,39.949756,-75.148062,4.5,90,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Performing Arts, Arts & Entertainment, Nightli...","{'Friday': '19:15-21:15', 'Monday': '0:0-0:0',...",Mike,120,2010-08-16 19:59:54,48,17,31,,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",5,4.44,4,3,0,0,0,10,15,4,4,4,0,148.0,0.0
3,DyrAIuKl60j_X8Yrrv-kpg,mNsVyC9tQVYtzLOCbh2Piw,MWmXGQ98KbRo3vsS5nZhMA,5.0,1,0,0,I recently had dinner here with my wife over t...,2014-10-27 02:47:28,Anthony's at Paxon Hollow,850 Paxon Hollow Rd,Broomall,PA,19008,39.958108,-75.371118,3.5,32,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Event Planning & Services, Italian, Venues & E...","{'Friday': '12:0-21:0', 'Monday': None, 'Satur...",Michael,12,2014-07-20 22:56:07,43,6,2,,RKULSOrIvvYpDmtuYXEXzA,0,2.53,0,0,0,0,0,0,0,0,0,0,0,15.0,0.0
4,40thYphUgIfvJq17QCfTwA,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5.0,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24,Wawa,2544 W Main Street,Norristown,PA,19403,40.141292,-75.389286,3.5,8,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Food, Coffee & Tea, Gas Stations, Restaurants,...","{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa...",Kylhalil,14,2012-03-05 19:12:11,5,2,2,,"POmz_WtE-nowjX5H7s9NSA, PEYAcshPlYwY-YP-55Re4Q...",0,4.36,0,0,0,0,0,0,0,0,0,0,0,79.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673685,rtt1Ymczj-1Lb26JMsY2lA,M1cMsRL4L7IUr9RILDywEQ,vt_esoDw6HG5ClM12OPkMg,4.0,4,3,4,"5 stars for the Bonte waffle, 3 stars for this...",2009-03-03 20:59:10,Bonté Wafflerie & Café,130 S 17th St,Philadelphia,PA,19102,39.950510,-75.169205,3.5,115,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Coffee & Tea, Restaurants, Breakfast & Brunch,...","{'Friday': '6:30-18:0', 'Monday': '6:30-18:0',...",Matt,2227,2006-10-24 22:40:11,5681,1342,2430,"2008,2009,2010,2011,2012,2013,2014,2015,2016,2...","TLElemg3o3mlA4GGpupNiQ, REGjppkq2IkDLRQVmRj_Bg...",277,3.78,59,30,10,13,36,79,116,150,150,128,41,193.0,0.0
673686,5n_oSwXspiiSsZgNwjp48g,bJ5FtCtZX3ZZacz2_2PJjA,SOsjW1JARmtHUFtpFlp8rw,4.0,5,2,5,When I first heard that the Peace A Pizza (htt...,2017-02-23 19:11:04,Snap Custom Pizza - Center City,1504 Sansom St,Philadelphia,PA,19102,39.950297,-75.166156,4.0,271,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Pizza","{'Friday': '11:0-21:0', 'Monday': '11:0-21:0',...",Bill,1512,2007-07-13 04:00:59,8735,3041,6564,"2007,2008,2009,2010,2011,2012,2013,2014,2015,2...","01JtywQEvF7wIePoducP1w, NfU4RVEA_C-5a68YBZAcOQ...",287,4.17,453,34,17,19,57,272,517,630,630,213,49,296.0,0.0
673687,KlHxcAifUF5zDKpJCBrRsw,7ziWZULyiZv2TesYNMFf4g,qQO7ErS_RAN4Vs1uX0L55Q,4.0,1,0,0,"ice cream! ice cream sodas, sundaes!! \n\nwant...",2012-10-21 04:08:40,The Franklin Fountain,116 Market St,Philadelphia,PA,19106,39.949562,-75.142876,4.0,2062,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Ice Cream & Frozen Yogurt, Coffee & Tea, Food,...","{'Friday': '12:0-0:0', 'Monday': '12:0-0:0', '...",Linda,1786,2011-03-03 09:47:22,1500,599,1048,"2012,2013,2014,2015,2016,2017,2018,2019,20,20,...","FaxC5dWURnvs5IZjVg36hw, gf2eigNU0zlAN_u-QavLgw...",56,3.74,6,2,5,1,0,13,37,28,28,17,1,4894.0,1.0
673688,cACxcUY_AIsQKkpDRXuqnw,MCzlzlOw7IGbRAKVjJBPtg,fcGexL5VH5G2Xw0tRj9uOQ,3.0,1,1,0,This is a good pizza option - they deliver thr...,2018-03-13 13:54:48,Slice,1740 Sansom St,Philadelphia,PA,19103,39.950745,-75.170168,3.5,214,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Pizza","{'Friday': '10:0-3:0', 'Monday': '10:0-22:0', ...",Erin,263,2011-05-06 12:36:06,439,84,161,"2017,2018,2019,20,20,2021","URPUZR0LWdIW7c9uMmJJEw, UsZGD3uzMxwv0Klvs89fww...",10,3.71,1,0,1,0,0,7,6,6,6,7,0,481.0,1.0
673689,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10,Canoe Outpost-Little Manatee River,18001 S US Hwy 301,Wimauma,FL,33598,27.671976,-82.353671,4.5,30,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Hotels & Travel, Active Life, Boating, Rafting...","{'Friday': '9:0-17:0', 'Monday': '9:0-17:0', '...",Angela,41,2011-10-18 13:28:02,74,14,25,"20,20,2021","aFDTRdIPpnIam1VAG2TmRg, 3aoGw05z0vHBa7dYFfl1qw...",3,4.19,1,0,0,1,0,2,2,4,4,0,1,32.0,0.0

In [ ]:
if "is_open" not in df.columns:
    raise ValueError("No 'is_open' in df. Merge business meta first or add is_open to parquet.")

before = len(df)
df = df.copy()
df["is_open"] = pd.to_numeric(df["is_open"], errors="coerce").fillna(0).astype(int)
df = df[df["is_open"] == 1].copy()

print(f"is_open=1 filter: {before} -> {len(df)} rows | "
      f"users={df['user_id'].nunique()} | items={df['business_id'].nunique()}")

is_open=1 filter: 673690 -> 539694 rows | users=86675 | items=37899

In [ ]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix

SEED = 42
np.random.seed(SEED)

MIN_USER_INTERACTIONS = 5
MIN_ITEM_INTERACTIONS = 5
K_VAL  = 1
K_TEST = 1
assert MIN_USER_INTERACTIONS >= (K_TEST + K_VAL + 1), "иначе train_inner может стать пустым"

df0 = df.copy()
df0["date"] = pd.to_datetime(df0["date"], errors="coerce")
df0 = (df0
       .dropna(subset=["user_id", "business_id", "date"])
       .sort_values(["user_id", "date"])
)

user_cnt = df0.groupby("user_id")["business_id"].size()
eligible_users = user_cnt[user_cnt >= MIN_USER_INTERACTIONS].index
df_cf = df0[df0["user_id"].isin(eligible_users)].copy()

print("Users after filter:", df_cf["user_id"].nunique())
print("Total interactions:", len(df_cf))

Users after filter: 31794
Total interactions: 382074

In [ ]:
best_cb_vec_params =  {'lowercase': True, 'stop_words': 'english', 'norm': 'l2', 'sublinear_tf': True, 'ngram_range': (1, 1), 'max_df': 1.0, 'max_features': 300000, 'min_df': 5} # сохранить, чтобы дальше не затёрлось
best_itemknn_params = ('tfidf', 10, None, None)  # tuple вида (w, K_sim, K1, B)
best_bpr_params = (128, 0.01, 0.002, 200)  # (f, lr, reg, it)
best_als_params = (128, 0.01, 40, 40.0)  # (f, reg, it, alpha)
best_lfm_cf_params = ('warp', 64, 0.02, 0.0001, 0.0001, 30)  # (loss, c, lr, ia, ua, ep)

## Data split

In [ ]:

test_idx = df_cf.groupby("user_id").tail(K_TEST).index
test0_full  = df_cf.loc[test_idx].copy()
train0_full = df_cf.drop(test_idx).copy()


val_idx = train0_full.groupby("user_id").tail(K_VAL).index
val0_full        = train0_full.loc[val_idx].copy()
train_inner0_full = train0_full.drop(val_idx).copy()

print("train_inner0:", len(train_inner0_full), "val0:", len(val0_full), "test0:", len(test0_full))
print("min interactions per user in train_inner0:",
      int(train_inner0_full.groupby("user_id")["business_id"].size().min()))

train0 = train0_full[["user_id","business_id","date"]].copy()
test0 = test0_full[["user_id","business_id","date"]].copy()
val0 = val0_full[["user_id","business_id","date"]].copy()
train_inner0 = train_inner0_full[["user_id","business_id","date"]].copy()

train_inner0: 318486 val0: 31794 test0: 31794
min interactions per user in train_inner0: 3

In [ ]:
from scipy.sparse import coo_matrix

def build_split_objects_universe(train_df, eval_df, min_item_interactions=5):
    """
    - НЕ дропает cold-start из eval
    - item-space = eligible_items(train) U items(eval)
    - eval_f содержит флаги is_cold_item / is_warm_item_eligible
    """
    train_items_set = set(train_df["business_id"].unique())

    item_cnt = train_df.groupby("business_id")["user_id"].size()
    eligible_items = item_cnt[item_cnt >= min_item_interactions].index
    eligible_set = set(eligible_items)

    train_f = train_df[train_df["business_id"].isin(eligible_items)].copy()

    users = train_f["user_id"].unique()
    user2idx = {u:i for i,u in enumerate(users)}

    idx2biz = pd.Index(eligible_items).union(eval_df["business_id"].unique()).to_numpy()
    is_cold_by_i = np.array([b not in train_items_set for b in idx2biz], dtype=bool)
    n_cold_items = int(is_cold_by_i.sum())

    item2idx = {b:i for i,b in enumerate(idx2biz)}

    train_f["u"] = train_f["user_id"].map(user2idx).astype("int32")
    train_f["i"] = train_f["business_id"].map(item2idx).astype("int32")

    eval_f = eval_df.copy()
    eval_f["u"] = eval_f["user_id"].map(user2idx)
    eval_f["i"] = eval_f["business_id"].map(item2idx)

    before = len(eval_f)
    eval_f = eval_f.dropna(subset=["u","i"]).copy()
    eval_f["u"] = eval_f["u"].astype("int32")
    eval_f["i"] = eval_f["i"].astype("int32")
    dropped_unknown = before - len(eval_f)

    eval_f["is_cold_item"] = ~eval_f["business_id"].isin(train_items_set)
    eval_f["is_warm_item_eligible"] = eval_f["business_id"].isin(eligible_set)

    R = coo_matrix(
        (np.ones(len(train_f), dtype=np.float32),
         (train_f["u"].values, train_f["i"].values)),
        shape=(len(users), len(idx2biz))
    ).tocsr()

    user_train_items = train_f.groupby("u")["i"].apply(lambda x: set(x.tolist())).to_dict()
    all_items = np.arange(len(idx2biz), dtype=np.int32)

    pack = {
        "n_users": len(users),
        "n_items": len(idx2biz),
        "R": R,
        "train_f": train_f,
        "eval_f": eval_f,
        "eval_u": eval_f["u"].values,
        "eval_i": eval_f["i"].values,
        "user_train_items": user_train_items,
        "all_items": all_items,
        "eligible_items": eligible_items,
        "idx2biz": idx2biz,
        "dropped_unknown_eval": dropped_unknown,
        "is_cold_by_i": is_cold_by_i,
        "n_cold_items": n_cold_items,
    }
    return pack

def pack_stats(name, pack):
    ef = pack["eval_f"]
    print(f"{name}: n_users={pack['n_users']} n_items={pack['n_items']} eval={len(ef)} "
          f"| cold={int(ef['is_cold_item'].sum())} warm_eligible={int(ef['is_warm_item_eligible'].sum())} "
          f"| dropped_unknown_eval={pack.get('dropped_unknown_eval',0)}")

val_pack  = build_split_objects_universe(train_inner0, val0, min_item_interactions=MIN_ITEM_INTERACTIONS)
test_pack = build_split_objects_universe(train0,       test0, min_item_interactions=MIN_ITEM_INTERACTIONS)

pack_stats("VAL_CS",  val_pack)
pack_stats("TEST_CS", test_pack)

VAL_CS: n_users=31679 n_items=18765 eval=31679 | cold=1187 warm_eligible=25095 | dropped_unknown_eval=115
TEST_CS: n_users=31744 n_items=19942 eval=31744 | cold=1138 warm_eligible=24653 | dropped_unknown_eval=50

## Text agg

In [ ]:

def agg_item_text(train_full: pd.DataFrame, eligible_items: pd.Index) -> pd.Series:
    x = train_full[train_full["business_id"].isin(eligible_items)][["business_id","text"]].copy()
    x["text"] = x["text"].fillna("").astype(str)
    return x.groupby("business_id")["text"].apply(lambda s: " ".join(t for t in s.values if t))

# - для VAL: только train_inner0_full
# - для TEST: train0_full (train_inner + val)
item_text_val  = agg_item_text(train_inner0_full, val_pack["eligible_items"])
item_text_test = agg_item_text(train0_full,       test_pack["eligible_items"])

print("item_text_val items:",  item_text_val.shape[0])
print("item_text_test items:", item_text_test.shape[0])

item_text_val items: 13235
item_text_test items: 14281

In [ ]:

# Если дальше по ноутбуку у тебя где-то ожидается train_inner0 (как в LMROO пайплайне),
# то теперь в роли "inner-train" можно использовать global train0.
train_inner0 = train0

print(train0.shape, val0.shape, test0.shape)
print(train0["user_id"].nunique(), val0["user_id"].nunique(), test0["user_id"].nunique())

(350280, 3) (31794, 3) (31794, 3)
31794 31794 31794

## Metrics

In [ ]:
import numpy as np

def _ndcg_from_rank(rank: int) -> float:

    return 1.0 / np.log2(rank + 2)

def _ap_from_rank(rank: int) -> float:

    return 1.0 / (rank + 1)

def _extract_items(recs):
    """
    Нормализуем вывод recommend_fn:
    - если вернул np.array/list -> это items
    - если вернул (items, scores) -> берём items
    """
    if recs is None:
        return np.array([], dtype=np.int32)
    if isinstance(recs, tuple) and len(recs) >= 1:
        recs = recs[0]
    return np.asarray(recs, dtype=np.int32)

def evaluate_next_item(eval_u, eval_i, recommend_fn, ks=(5,10,20,50), name="model"):
    """
    Оценка next-item (по одному target на пользователя).
    ВАЖНО: ничего дополнительно из eval не выкидываем (в т.ч. если target item был seen ранее).
    """
    ks = tuple(sorted(ks))
    maxK = ks[-1]
    n = len(eval_u)
    if n == 0:
        print(f"[{name}] empty eval set")
        return {k: (0.0, 0.0, 0.0) for k in ks}

    rec = {k: 0.0 for k in ks}
    ndcg = {k: 0.0 for k in ks}
    mp = {k: 0.0 for k in ks}
    short_lists = 0

    for u, pos in zip(eval_u, eval_i):
        items = _extract_items(recommend_fn(int(u), int(maxK)))

        if len(items) < maxK:
            short_lists += 1


        rpos = None
        for r, it in enumerate(items):
            if int(it) == int(pos):
                rpos = r
                break

        for k in ks:
            if rpos is None or rpos >= k:
                continue
            rec[k] += 1.0
            ndcg[k] += _ndcg_from_rank(rpos)
            mp[k] += _ap_from_rank(rpos)

    out = {k: (rec[k]/n, ndcg[k]/n, mp[k]/n) for k in ks}
    print(f"[{name}] short rec lists: {short_lists}/{n} ({short_lists/n:.3f})")
    return out

import numpy as np

def _get_masks(pack):
    ef = pack["eval_f"]
    return {
        "ALL":  np.ones(len(ef), dtype=bool),
        "WARM": ef["is_warm_item_eligible"].values.astype(bool),
        "COLD": ef["is_cold_item"].values.astype(bool),
    }

def _unique_users(pack, mask):
    ef = pack["eval_f"]
    return np.unique(ef.loc[mask, "u"].values.astype(np.int32))

def catalog_coverage_at_k(pack, recommend_fn, mask, ks=(5,10,20,50)):
    """
    Coverage@K = |union of recommended items| / n_items
    """
    ks = tuple(sorted(ks))
    maxK = ks[-1]
    users = _unique_users(pack, mask)
    n_items = int(pack["n_items"])
    if users.size == 0 or n_items == 0:
        return {k: 0.0 for k in ks}

    unions = {k: set() for k in ks}

    for u in users:
        items = _extract_items(recommend_fn(int(u), int(maxK)))
        items = np.asarray(items, dtype=np.int32)
        for k in ks:
            unions[k].update(items[:k].tolist())

    return {k: (len(unions[k]) / n_items) for k in ks}

def novelty_at_k(pack, recommend_fn, mask, ks=(5,10,20,50), smoothing=1.0):
    """
    Novelty@K = avg_u avg_{i in topK(u)} -log2(p(i)),
    p(i) estimated from train popularity in pack["R"] with smoothing.
    """
    ks = tuple(sorted(ks))
    maxK = ks[-1]
    users = _unique_users(pack, mask)
    if users.size == 0:
        return {k: 0.0 for k in ks}

    pop = np.asarray(pack["R"].sum(axis=0)).ravel().astype(np.float64)
    denom = pop.sum() + smoothing * len(pop)
    p = (pop + smoothing) / denom
    invlogp = -np.log2(p)

    sums = {k: 0.0 for k in ks}
    cnts = {k: 0 for k in ks}

    for u in users:
        items = _extract_items(recommend_fn(int(u), int(maxK)))
        items = np.asarray(items, dtype=np.int32)

        for k in ks:
            topk = items[:k]
            if topk.size == 0:
                continue
            sums[k] += float(invlogp[topk].mean())
            cnts[k] += 1

    return {k: (sums[k] / cnts[k] if cnts[k] > 0 else 0.0) for k in ks}

def cold_share_at_k(pack, recommend_fn, mask, ks=(5,10,20,50)):
    """
    ColdShare@K = avg_u ( #cold in topK(u) / K )
    """
    ks = tuple(sorted(ks))
    maxK = ks[-1]
    users = _unique_users(pack, mask)
    if users.size == 0:
        return {k: 0.0 for k in ks}

    is_cold_by_i = pack["is_cold_by_i"].astype(bool)

    sums = {k: 0.0 for k in ks}
    cnts = {k: 0 for k in ks}

    for u in users:
        items = _extract_items(recommend_fn(int(u), int(maxK)))
        items = np.asarray(items, dtype=np.int32)

        for k in ks:
            topk = items[:k]
            if topk.size == 0:
                continue
            sums[k] += float(is_cold_by_i[topk].mean())
            cnts[k] += 1

    return {k: (sums[k] / cnts[k] if cnts[k] > 0 else 0.0) for k in ks}

def cold_coverage_at_k(pack, recommend_fn, mask, ks=(5,10,20,50)):
    """
    ColdCoverage@K = |union of recommended cold items| / n_cold_items_in_space
    """
    ks = tuple(sorted(ks))
    maxK = ks[-1]
    users = _unique_users(pack, mask)
    n_cold = int(pack.get("n_cold_items", 0))
    if users.size == 0 or n_cold == 0:
        return {k: 0.0 for k in ks}

    is_cold_by_i = pack["is_cold_by_i"].astype(bool)
    unions = {k: set() for k in ks}

    for u in users:
        items = _extract_items(recommend_fn(int(u), int(maxK)))
        items = np.asarray(items, dtype=np.int32)

        cold_items = items[is_cold_by_i[items]]
        for k in ks:
            unions[k].update(cold_items[:k].tolist())

    return {k: (len(unions[k]) / n_cold) for k in ks}

import numpy as np

def _get_masks(pack):
    ef = pack["eval_f"]
    return {
        "ALL":  np.ones(len(ef), dtype=bool),
        "WARM": ef["is_warm_item_eligible"].values.astype(bool),
        "COLD": ef["is_cold_item"].values.astype(bool),
    }

def evaluate_with_aux(pack, recommend_fn, mask, ks=(5,10,20,50), sample_n=None, seed=42):
    """
    За 1 проход по eval-инстансам считает:
      - Recall@K, NDCG@K, MAP@K (next-item, 1 positive на строку)
      - Coverage@K (catalog coverage)
      - Novelty@K (анти-популярность)
      - ColdShare@K (доля cold в топ-K)
      - ColdCoverage@K (покрытие cold-каталога)

    mask: bool-маска по строкам pack["eval_f"]
    sample_n: если задано, берём случайную подвыборку строк (ускорение)
    """
    ef = pack["eval_f"]
    ks = tuple(sorted(ks))
    maxK = ks[-1]

    idx = np.where(mask)[0]
    if idx.size == 0:
        out = {k: (0.0, 0.0, 0.0) for k in ks}
        aux = {
            "Coverage": {k: 0.0 for k in ks},
            "Novelty": {k: 0.0 for k in ks},
            "ColdShare": {k: 0.0 for k in ks},
            "ColdCoverage": {k: 0.0 for k in ks},
        }
        return out, aux

    if (sample_n is not None) and (idx.size > sample_n):
        rng = np.random.default_rng(seed)
        idx = rng.choice(idx, size=int(sample_n), replace=False)


    pop = np.asarray(pack["R"].sum(axis=0)).ravel().astype(np.float64)
    smoothing = 1.0
    denom = pop.sum() + smoothing * len(pop)
    p = (pop + smoothing) / denom
    invlogp = -np.log2(p)

    is_cold_by_i = pack["is_cold_by_i"].astype(bool)
    n_items = int(pack["n_items"])
    n_cold = int(pack.get("n_cold_items", is_cold_by_i.sum()))


    recall_sum = {k: 0.0 for k in ks}
    ndcg_sum   = {k: 0.0 for k in ks}
    map_sum    = {k: 0.0 for k in ks}
    denom_rows = float(idx.size)


    novelty_sum   = {k: 0.0 for k in ks}
    coldshare_sum = {k: 0.0 for k in ks}


    cov_masks     = {k: np.zeros(n_items, dtype=bool) for k in ks}
    coldcov_masks = {k: np.zeros(n_items, dtype=bool) for k in ks}

    for j in idx:
        u = int(ef.iloc[j]["u"])
        true_i = int(ef.iloc[j]["i"])

        rec_items = _extract_items(recommend_fn(u, int(maxK)))
        rec_items = np.asarray(rec_items, dtype=np.int32)
        if rec_items.size == 0:
            continue


        pos = np.where(rec_items == true_i)[0]
        rank = int(pos[0]) if pos.size > 0 else 10**9

        nov_vals  = invlogp[rec_items]
        cold_vals = is_cold_by_i[rec_items].astype(np.float64)

        nov_cum_mean  = np.cumsum(nov_vals)  / np.arange(1, rec_items.size + 1)
        cold_cum_mean = np.cumsum(cold_vals) / np.arange(1, rec_items.size + 1)

        for k in ks:
            kk = min(k, rec_items.size)
            hit = (rank < k)
            if hit:
                recall_sum[k] += 1.0
                ndcg_sum[k]   += 1.0 / np.log2(rank + 2.0)
                map_sum[k]    += 1.0 / (rank + 1.0)

            novelty_sum[k]   += float(nov_cum_mean[kk - 1])
            coldshare_sum[k] += float(cold_cum_mean[kk - 1])

            topk = rec_items[:kk]
            cov_masks[k][topk] = True

            cold_topk = topk[is_cold_by_i[topk]]
            if cold_topk.size > 0:
                coldcov_masks[k][cold_topk] = True

    out = {}
    for k in ks:
        out[k] = (
            recall_sum[k] / denom_rows,
            ndcg_sum[k]   / denom_rows,
            map_sum[k]    / denom_rows
        )

    aux = {
        "Coverage": {},
        "Novelty": {},
        "ColdShare": {},
        "ColdCoverage": {},
    }
    for k in ks:
        aux["Coverage"][k]     = float(cov_masks[k].sum() / n_items) if n_items > 0 else 0.0
        aux["Novelty"][k]      = float(novelty_sum[k] / denom_rows)
        aux["ColdShare"][k]    = float(coldshare_sum[k] / denom_rows)
        aux["ColdCoverage"][k] = float(coldcov_masks[k].sum() / n_cold) if n_cold > 0 else 0.0

    return out, aux


def print_metrics(name, out, ks=(5,10,20,50)):
    print(f"\n=== {name} ===")
    for k in ks:
        r, n, m = out[k]
        print(f"K={k:2d} | Recall@{k}: {r:.4f} | NDCG@{k}: {n:.4f} | MAP@{k}: {m:.4f}")

In [ ]:
import numpy as np

def evaluate_with_aux(pack, recommend_fn, mask, ks=(5,10,20,50), sample_n=None, seed=42):
    """
    За один проход считает:
      - Recall@K, NDCG@K, MAP@K (next-item, 1 позитив на строку)
      - Coverage@K, Novelty@K
      - ColdShare@K, ColdCoverage@K

    mask: булев массив по строкам pack["eval_f"]
    sample_n: если задано, то случайно берём sample_n строк (ускорение)
    """
    ef = pack["eval_f"]
    ks = tuple(sorted(ks))
    maxK = ks[-1]

    idx = np.where(mask)[0]
    if idx.size == 0:
        out = {k: (0.0, 0.0, 0.0) for k in ks}
        aux = { "Coverage": {k: 0.0 for k in ks},
                "Novelty": {k: 0.0 for k in ks},
                "ColdShare": {k: 0.0 for k in ks},
                "ColdCoverage": {k: 0.0 for k in ks} }
        return out, aux

    if (sample_n is not None) and (idx.size > sample_n):
        rng = np.random.default_rng(seed)
        idx = rng.choice(idx, size=int(sample_n), replace=False)


    pop = np.asarray(pack["R"].sum(axis=0)).ravel().astype(np.float64)
    smoothing = 1.0
    denom = pop.sum() + smoothing * len(pop)
    p = (pop + smoothing) / denom
    invlogp = -np.log2(p)  # larger => more novel

    is_cold_by_i = pack["is_cold_by_i"].astype(bool)
    n_items = int(pack["n_items"])
    n_cold = int(pack.get("n_cold_items", is_cold_by_i.sum()))


    recall_sum = {k: 0.0 for k in ks}
    ndcg_sum   = {k: 0.0 for k in ks}
    map_sum    = {k: 0.0 for k in ks}
    denom_rows = float(idx.size)


    novelty_sum   = {k: 0.0 for k in ks}
    coldshare_sum = {k: 0.0 for k in ks}

    cov_masks      = {k: np.zeros(n_items, dtype=bool) for k in ks}
    coldcov_masks  = {k: np.zeros(n_items, dtype=bool) for k in ks}  # marks cold items only

    for j in idx:
        u = int(ef.iloc[j]["u"])
        true_i = int(ef.iloc[j]["i"])

        rec_items = _extract_items(recommend_fn(u, int(maxK)))
        rec_items = np.asarray(rec_items, dtype=np.int32)
        if rec_items.size == 0:
            continue


        pos = np.where(rec_items == true_i)[0]
        rank = int(pos[0]) if pos.size > 0 else 10**9

        nov_vals  = invlogp[rec_items]
        cold_vals = is_cold_by_i[rec_items].astype(np.float64)

        nov_cum_mean  = np.cumsum(nov_vals)  / np.arange(1, rec_items.size + 1)
        cold_cum_mean = np.cumsum(cold_vals) / np.arange(1, rec_items.size + 1)

        for k in ks:
            kk = min(k, rec_items.size)
            # accuracy
            hit = (rank < k)
            if hit:
                recall_sum[k] += 1.0
                ndcg_sum[k]   += 1.0 / np.log2(rank + 2.0)
                map_sum[k]    += 1.0 / (rank + 1.0)

            # aux: novelty/coldshare
            novelty_sum[k]   += float(nov_cum_mean[kk - 1])
            coldshare_sum[k] += float(cold_cum_mean[kk - 1])

            # aux: coverage
            topk = rec_items[:kk]
            cov_masks[k][topk] = True

            # aux: cold coverage
            cold_topk = topk[is_cold_by_i[topk]]
            if cold_topk.size > 0:
                coldcov_masks[k][cold_topk] = True


    out = {}
    for k in ks:
        out[k] = (
            recall_sum[k] / denom_rows,
            ndcg_sum[k]   / denom_rows,
            map_sum[k]    / denom_rows
        )


    aux = {
        "Coverage": {},
        "Novelty": {},
        "ColdShare": {},
        "ColdCoverage": {}
    }
    for k in ks:
        aux["Coverage"][k]     = float(cov_masks[k].sum() / n_items) if n_items > 0 else 0.0
        aux["Novelty"][k]      = float(novelty_sum[k] / denom_rows)
        aux["ColdShare"][k]    = float(coldshare_sum[k] / denom_rows)
        aux["ColdCoverage"][k] = float(coldcov_masks[k].sum() / n_cold) if n_cold > 0 else 0.0

    return out, aux

## Feature engeneering

In [ ]:
# Берём статические поля бизнеса (это не даёт утечки)
need_item_cols = [c for c in ["business_id","categories","attributes","stars_business","review_count","is_open",'text']
                  if c in df_cf.columns]

items_meta = (df_cf[need_item_cols]
              .sort_values(["business_id"])
              .groupby("business_id", as_index=False)
              .first())

In [ ]:
import re, ast

_re_tok = re.compile(r"[^a-z0-9]+", re.IGNORECASE)

def _clean_token(s: str) -> str:
    s = str(s).strip().lower()
    s = s.replace("&", " and ")
    s = _re_tok.sub("_", s).strip("_")
    return s

def _cat_tokens(cat):
    if pd.isna(cat) or cat is None:
        return []
    parts = [p.strip() for p in str(cat).split(",") if p.strip()]
    return [f"cat_{_clean_token(p)}" for p in parts]

def _safe_literal_eval(x):
    if isinstance(x, dict):
        return x
    if pd.isna(x) or x is None:
        return {}
    s = str(x)
    # убираем префиксы u'...' / u"..."
    s = s.replace("u'", "'").replace('u"', '"')
    try:
        return ast.literal_eval(s)
    except Exception:
        return {}

def _norm_scalar(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    if isinstance(v, bool):
        return "true" if v else "false"
    s = str(v).strip()
    s = s.replace("u'", "'").replace('u"', '"')
    # снимем внешние кавычки типа "'loud'"
    if len(s) >= 2 and ((s[0] == s[-1] == "'") or (s[0] == s[-1] == '"')):
        s = s[1:-1].strip()
    return s if s else None

def _attr_tokens(attr):
    d = _safe_literal_eval(attr)
    out = []
    for k, v in (d or {}).items():
        if v is None:
            continue
        key = _clean_token(k)

        # вложенные dict часто лежат строкой -> распарсим ещё раз
        if isinstance(v, str) and v.strip().startswith("{") and v.strip().endswith("}"):
            v2 = _safe_literal_eval(v)
            if isinstance(v2, dict):
                v = v2

        if isinstance(v, dict):
            for kk, vv in v.items():
                vv = _norm_scalar(vv)
                if vv is None:
                    continue
                if str(vv).lower() in ("true", "false"):
                    if str(vv).lower() == "true":
                        out.append(f"attr_{key}_{_clean_token(kk)}")
                else:
                    out.append(f"attr_{key}_{_clean_token(kk)}_{_clean_token(vv)}")
        else:
            vv = _norm_scalar(v)
            if vv is None:
                continue
            if str(vv).lower() in ("true", "false"):
                if str(vv).lower() == "true":
                    out.append(f"attr_{key}")
            else:
                out.append(f"attr_{key}_{_clean_token(vv)}")
    return out

def build_item_docs_for_pack(pack, items_meta, item_text_series):
    """Build per-item documents in *exact* item-index order.

    Critical for cold-start eval: pack["n_items"] includes (eligible_train_items U eval_items).
    Therefore docs must be length == pack["n_items"] and aligned with item index i=0..n_items-1.

    Returns
    -------
    idx2biz : np.ndarray
        business_id for each internal item index i.
    docs : list[str]
        Document string for each item index.
    """
    # Prefer the canonical mapping created in build_split_objects_universe
    if "idx2biz" in pack:
        idx2biz = pack["idx2biz"]
    else:
        # Fallback (should not happen in this notebook)
        idx2biz = (pack["train_f"][["i", "business_id"]]
                   .drop_duplicates("i")
                   .sort_values("i")["business_id"].to_numpy())

    meta = items_meta.set_index("business_id")
    docs = []

    for b in idx2biz:
        row = meta.loc[b] if b in meta.index else None

        cats = _cat_tokens(row["categories"]) if row is not None and "categories" in meta.columns else []
        attrs = _attr_tokens(row["attributes"]) if row is not None and "attributes" in meta.columns else []

        # статические числовые/булевы поля бизнеса -> токены
        extra = []
        if row is not None:
            if "stars_business" in meta.columns and pd.notna(row.get("stars_business", np.nan)):
                sb = int(round(float(row["stars_business"]) * 10))
                extra.append(f"num_starsbiz_{sb}")
            if "review_count" in meta.columns and pd.notna(row.get("review_count", np.nan)):
                rc = int(row["review_count"])
                bin_rc = int(np.clip(np.floor(np.log10(rc + 1) * 10), 0, 50))
                extra.append(f"num_reviewcountbin_{bin_rc}")
            if "is_open" in meta.columns and pd.notna(row.get("is_open", np.nan)):
                extra.append("flag_open" if int(row["is_open"]) == 1 else "flag_closed")

        # тексты отзывов: только из train-пула -> без утечки
        rev = item_text_series.get(b, "")

        docs.append(" ".join(cats + attrs + extra)) # + " " + str(rev)

    # Safety: alignment guarantee
    assert len(docs) == int(pack["n_items"]), f"docs len {len(docs)} != n_items {pack['n_items']}"
    return idx2biz, docs


idx2biz_val,  item_docs_val  = build_item_docs_for_pack(val_pack,  items_meta, item_text_val)
idx2biz_test, item_docs_test = build_item_docs_for_pack(test_pack, items_meta, item_text_test)

print("VAL docs:", len(item_docs_val), "== n_items", val_pack["n_items"])
print("TEST docs:", len(item_docs_test), "== n_items", test_pack["n_items"])

VAL docs: 18765 == n_items 18765
TEST docs: 19942 == n_items 19942

In [ ]:
# Быстрый sanity-check по документам (без риска IndexError)
idx = min(10, len(item_docs_val) - 1)
print("Example idx:", idx)
print(item_docs_val[idx])

Example idx: 10
cat_beauty_and_spas cat_shopping cat_hair_salons cat_barbers attr_bikeparking attr_businessacceptscreditcards attr_businessparking_lot attr_restaurantspricerange2_1 num_starsbiz_35 num_reviewcountbin_11 flag_open

In [ ]:
def evaluate_pack_subsets(pack, recommend_fn, name, ks=KS):
    ef = pack["eval_f"]
    outs = {}

    def run(mask, split):
        u = ef.loc[mask, "u"].values
        i = ef.loc[mask, "i"].values
        print(f"\n[{name}/{split}] n={len(u)}")
        out = evaluate_next_item(u, i, recommend_fn, ks=ks, name=f"{name}/{split}")
        print_metrics(f"{name}/{split}", out, ks=ks)
        return out

    outs["ALL"]  = run(np.ones(len(ef), dtype=bool), "ALL")
    outs["WARM"] = run(ef["is_warm_item_eligible"].values, "WARM")
    outs["COLD"] = run(ef["is_cold_item"].values, "COLD")
    return outs

## SASREC

In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

from tqdm.auto import tqdm

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

device: cuda

In [ ]:

def build_user_sequences(pack, min_len=1):
    tf = pack["train_f"][["u","i","date"]].copy()
    tf["date"] = pd.to_datetime(tf["date"])
    tf = tf.sort_values(["u","date"])
    seqs = {}
    for u, g in tf.groupby("u", sort=False):
        seq = g["i"].astype(np.int32).to_numpy()
        if len(seq) >= min_len:
            seqs[int(u)] = seq
    return seqs

# Для обучения нужны seq длины >=2, для инференса достаточно >=1
val_seqs_infer  = build_user_sequences(val_pack,  min_len=1)
test_seqs_infer = build_user_sequences(test_pack, min_len=1)

val_seqs_train  = {u:s for u,s in val_seqs_infer.items()  if len(s) >= 2}
test_seqs_train = {u:s for u,s in test_seqs_infer.items() if len(s) >= 2}

# Диагностика: сколько eval-пользователей "терялись" бы без min_len=1
def missing_eval_users(pack, seqs_infer):
    eval_users = np.unique(pack["eval_f"]["u"].astype(np.int32).to_numpy())
    missing = np.sum([1 for u in eval_users if (int(u) not in seqs_infer) or (len(seqs_infer[int(u)]) == 0)])
    return len(eval_users), missing

n_eval, miss = missing_eval_users(val_pack, val_seqs_infer)
print("VAL eval users:", n_eval, "missing seq:", miss, "share:", miss/n_eval)

VAL eval users: 31679 missing seq: 0.0 share: 0.0

In [ ]:
def build_item_side_emb(item_docs, n_items, side_dim=64, min_df=2, max_features=200_000, seed=42):
    assert len(item_docs) == n_items, f"len(item_docs)={len(item_docs)} must equal n_items={n_items}"

    vec = TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 1),
        sublinear_tf=True,
        norm="l2",
        min_df=min_df,
        max_features=max_features,
    )
    X = vec.fit_transform(item_docs).astype(np.float32)

    svd = TruncatedSVD(n_components=int(side_dim), random_state=int(seed))
    Z = svd.fit_transform(X).astype(np.float32)  # (n_items, side_dim)

    # PAD row at 0, items shift +1
    Zpad = np.zeros((n_items + 1, side_dim), dtype=np.float32)
    Zpad[1:, :] = Z
    return Zpad

SIDE_DIM = 64
SIDE_MIN_DF = 2  # попробуйте 1 и 2 (для cold иногда 1 лучше)

val_item_side  = build_item_side_emb(item_docs_val,  val_pack["n_items"],  side_dim=SIDE_DIM, min_df=SIDE_MIN_DF, seed=SEED)
test_item_side = build_item_side_emb(item_docs_test, test_pack["n_items"], side_dim=SIDE_DIM, min_df=SIDE_MIN_DF, seed=SEED)

print(val_item_side.shape, test_item_side.shape)

(18766, 64) (19943, 64)

In [ ]:
class SASRec(nn.Module):
    def __init__(self, n_items, max_len=50, hidden=64, n_layers=2, n_heads=2, dropout=0.2,
                 side_dim=64, use_side=True):
        super().__init__()
        self.n_items = int(n_items)
        self.max_len = int(max_len)
        self.hidden = int(hidden)
        self.use_side = bool(use_side)

        self.item_emb = nn.Embedding(self.n_items + 1, self.hidden, padding_idx=0)  # 0=PAD
        self.pos_emb  = nn.Embedding(self.max_len, self.hidden)

        if self.use_side:
            self.side_proj = nn.Linear(int(side_dim), self.hidden, bias=False)

        self.dropout = nn.Dropout(float(dropout))
        self.norm = nn.LayerNorm(self.hidden)

        enc_layer = nn.TransformerEncoderLayer(
            d_model=self.hidden,
            nhead=int(n_heads),
            dim_feedforward=self.hidden * 4,
            dropout=float(dropout),
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=int(n_layers))

        # causal mask fixed (L,L)
        causal = torch.triu(torch.ones(self.max_len, self.max_len, dtype=torch.bool), diagonal=1)
        self.register_buffer("causal_mask", causal)

    def forward(self, seq, side_feats=None):
        """
        seq: (B, L=max_len) int64, 0=PAD, real item = i+1
        """
        B, L = seq.shape
        assert L == self.max_len

        pos = torch.arange(L, device=seq.device).unsqueeze(0).expand(B, L)
        x = self.item_emb(seq) + self.pos_emb(pos)

        if self.use_side:
            assert side_feats is not None
            x = x + self.side_proj(side_feats[seq])

        x = self.dropout(self.norm(x))

        pad_mask = (seq == 0)  # True where PAD
        h = self.encoder(x, mask=self.causal_mask, src_key_padding_mask=pad_mask)
        return h  # (B,L,H)

    def embed_items(self, item_ids_shifted, side_feats=None):
        """
        item_ids_shifted: (B,) or (B,n_neg) long, values in [0..n_items]
        returns embeddings with same leading dims and last dim H
        """
        e = self.item_emb(item_ids_shifted)
        if self.use_side:
            e = e + self.side_proj(side_feats[item_ids_shifted])
        return e

In [ ]:
class SASRecDataset(Dataset):
    def __init__(self, seqs_by_u, n_items, max_len=50, n_samples=200_000, seed=42,
                 neg_pool_items=None, n_neg=20):
        self.users = list(seqs_by_u.keys())
        self.seqs = seqs_by_u
        self.n_items = int(n_items)
        self.max_len = int(max_len)
        self.n_samples = int(n_samples)
        self.rng = np.random.default_rng(seed)

        self.n_neg = int(n_neg)
        if neg_pool_items is None:
            self.neg_pool = np.arange(self.n_items, dtype=np.int32)
        else:
            self.neg_pool = np.asarray(neg_pool_items, dtype=np.int32)

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        u = int(self.users[self.rng.integers(0, len(self.users))])
        seq = self.seqs[u]

        # choose t in [1 .. len(seq)-1], predict seq[t]
        t = int(self.rng.integers(1, len(seq)))
        pos = int(seq[t])

        hist = seq[:t]
        hist = hist[-self.max_len:]
        tokens = np.zeros(self.max_len, dtype=np.int64)
        tokens[-len(hist):] = (hist.astype(np.int64) + 1)  # shift +1

        # avoid sampling items from user's history + pos
        hist_set = set(hist.tolist())
        hist_set.add(pos)

        negs = np.empty(self.n_neg, dtype=np.int64)
        j = 0
        while j < self.n_neg:
            cand = int(self.neg_pool[self.rng.integers(0, len(self.neg_pool))])
            if cand not in hist_set:
                negs[j] = cand + 1  # shift +1
                j += 1

        return tokens, np.int64(pos + 1), negs

In [ ]:
def fit_sasrec(pack, seqs_train, seqs_infer, item_side_np,
               max_len=50, hidden=64, n_layers=2, n_heads=2, dropout=0.2,
               lr=1e-3, weight_decay=1e-4,
               batch_size=256, steps_per_epoch=1500, epochs=8,
               n_neg=20, n_neg_pool_from_train=True,
               maxK_cache=100, batch_users_eval=512):

    n_items = int(pack["n_items"])

    # neg pool = items that appear in train_f (warm pool)
    if n_neg_pool_from_train:
        train_item_ids = np.unique(pack["train_f"]["i"].astype(np.int32).to_numpy())
        neg_pool = train_item_ids
    else:
        neg_pool = np.arange(n_items, dtype=np.int32)

    ds = SASRecDataset(
        seqs_by_u=seqs_train,
        n_items=n_items,
        max_len=max_len,
        n_samples=steps_per_epoch * batch_size,
        seed=SEED,
        neg_pool_items=neg_pool,
        n_neg=n_neg,
    )
    dl = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=0,
                    pin_memory=(device.type == "cuda"))

    model = SASRec(
        n_items=n_items,
        max_len=max_len,
        hidden=hidden,
        n_layers=n_layers,
        n_heads=n_heads,
        dropout=dropout,
        side_dim=item_side_np.shape[1],
        use_side=True,
    ).to(device)

    side_feats = torch.from_numpy(item_side_np).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=float(lr), weight_decay=float(weight_decay))
    bce = nn.BCEWithLogitsLoss()

    for ep in range(1, epochs + 1):
        model.train()
        losses = []

        # "тихий" tqdm: без postfix каждый шаг, просто бар движется
        pbar = tqdm(
            total=steps_per_epoch,
            desc=f"SASRec epoch {ep}/{epochs}",
            leave=False,
            mininterval=1.0,      # обновлять UI не чаще раза в секунду
            smoothing=0.1,
            dynamic_ncols=True
        )

        it = 0
        for tokens, pos, negs in dl:
            tokens = tokens.to(device, non_blocking=True)          # (B,L)
            pos = pos.to(device, non_blocking=True)                # (B,)
            negs = torch.from_numpy(np.stack(negs)).to(device) if isinstance(negs, list) else negs.to(device, non_blocking=True)
            # negs: (B, n_neg) int64

            h = model(tokens, side_feats=side_feats)[:, -1, :]     # (B,H)

            # !!! ВАЖНО: получаем эмбеддинги ТОЛЬКО нужных pos/negs, без item_vecs на весь каталог
            pos_v = model.embed_items(pos, side_feats=side_feats)                   # (B,H)
            neg_v = model.embed_items(negs, side_feats=side_feats)                  # (B,n_neg,H)

            pos_logit = (h * pos_v).sum(dim=1)                                      # (B,)
            neg_logit = (h[:, None, :] * neg_v).sum(dim=2)                          # (B,n_neg)

            loss_pos = bce(pos_logit, torch.ones_like(pos_logit))
            loss_neg = bce(neg_logit.reshape(-1), torch.zeros_like(neg_logit).reshape(-1))
            loss = loss_pos + loss_neg

            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()

            losses.append(float(loss.item()))
            it += 1
            pbar.update(1)
            if it >= steps_per_epoch:
                break

        pbar.close()
        print(f"[SASRec] epoch {ep}/{epochs} loss={np.mean(losses):.4f}")

    # --- recommender (кэширует top-maxK для всех eval users пачками) ---
    model.eval()
    side_feats_t = torch.from_numpy(item_side_np).to(device)

    user_train_items = pack["user_train_items"]
    n_items = pack["n_items"]
    max_len = model.max_len

    cache = {}

    @torch.no_grad()
    def _precompute_for_users(users):
        users = [int(u) for u in users]
        item_vecs = model.embed_items(
            torch.arange(0, n_items + 1, device=device, dtype=torch.long),
            side_feats=side_feats_t
        )  # (n_items+1,H) one-time per precompute call
        item_vecs[0] = -1e9  # forbid PAD vector usage by score tricks (will also set score below)

        for s in range(0, len(users), batch_users_eval):
            ub = users[s:s + batch_users_eval]
            X = np.zeros((len(ub), max_len), dtype=np.int64)
            for j, u in enumerate(ub):
                seq = seqs_infer.get(u, None)
                if seq is None or len(seq) == 0:
                    continue
                hist = seq[-max_len:]
                X[j, -len(hist):] = (hist.astype(np.int64) + 1)

            X = torch.from_numpy(X).to(device)
            h = model(X, side_feats=side_feats_t)[:, -1, :]              # (B,H)

            scores = h @ item_vecs.T                                      # (B, n_items+1)
            scores[:, 0] = -1e9

            # filter seen
            for j, u in enumerate(ub):
                seen = user_train_items.get(u, None)
                if seen:
                    idx = torch.tensor([int(i)+1 for i in seen], device=device, dtype=torch.long)
                    scores[j, idx] = -1e9

            top = torch.topk(scores, k=min(maxK_cache, n_items), dim=1).indices.cpu().numpy()
            for j, u in enumerate(ub):
                items = top[j]
                items = items[items != 0] - 1
                cache[u] = items.astype(np.int32)

    def recommend_fn(u, K):
        u = int(u); K = int(K)
        if K <= 0:
            return np.array([], dtype=np.int32)

        if u not in cache:
            # лениво: предвычисляем для всех eval users (обычно быстрее, чем по одному)
            eval_users = np.unique(pack["eval_f"]["u"].astype(np.int32).to_numpy()).tolist()
            _precompute_for_users(eval_users)

        arr = cache.get(u, np.array([], dtype=np.int32))
        return arr[:K] if arr.size > K else arr

    return model, recommend_fn

In [ ]:
target_split = "ALL"   # можно "WARM" или "COLD"
target_k = 50

grid = [
    dict(max_len=50,  hidden=64,  n_heads=2, dropout=0.2, lr=1e-3),
    dict(max_len=50,  hidden=128, n_heads=4, dropout=0.2, lr=8e-4),
    dict(max_len=100, hidden=64,  n_heads=2, dropout=0.2, lr=8e-4),
    dict(max_len=100, hidden=128, n_heads=4, dropout=0.3, lr=5e-4),
]

best = {"score": -1, "cfg": None, "model": None, "rec": None}

for cfg in tqdm(grid, desc="SASRec hyperparam search", mininterval=1.0, dynamic_ncols=True):
    print("\n=== TRY:", cfg, "===")

    model, rec = fit_sasrec(
        val_pack,
        seqs_train=val_seqs_train,
        seqs_infer=val_seqs_infer,
        item_side_np=val_item_side,
        max_len=cfg["max_len"],
        hidden=cfg["hidden"],
        n_layers=2,
        n_heads=cfg["n_heads"],
        dropout=cfg["dropout"],
        lr=cfg["lr"],
        weight_decay=1e-4,
        batch_size=256,
        steps_per_epoch=1500,
        epochs=8,
        n_neg=20,
        maxK_cache=max(KS),
        batch_users_eval=512,
    )

    outs = evaluate_pack_subsets(val_pack, rec, "SASRec(VAL)", ks=KS)
    score = outs[target_split][target_k][0]  # Recall

    print(f"VAL target: split={target_split} K={target_k} Recall={score:.6f}")

    if score > best["score"]:
        best = {"score": score, "cfg": cfg, "model": model, "rec": rec}

print("\nBEST:", best["cfg"], "score=", best["score"])

SASRec hyperparam search:   0%|          | 0/4 [00:00<?, ?it/s]

=== TRY: {'max_len': 50, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.001} ===

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 1/8 loss=1.8842

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 2/8 loss=1.2496

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 3/8 loss=1.1502

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 4/8 loss=1.0598

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 5/8 loss=0.9474

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 6/8 loss=0.8416

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 7/8 loss=0.7830

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 8/8 loss=0.7444

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0033 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0061 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095
[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0000
K=10 | Recall@10: 0.0013 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0035 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0067 | NDCG@100: 0.0014 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target: split=ALL K=50 Recall=0.003346

=== TRY: {'max_len': 50, 'hidden': 128, 'n_heads': 4, 'dropout': 0.2, 'lr': 0.0008} ===

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 1/8 loss=2.7445

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 2/8 loss=1.4190

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 3/8 loss=1.2187

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 4/8 loss=1.0756

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 5/8 loss=0.9401

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 6/8 loss=0.8184

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 7/8 loss=0.7503

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 8/8 loss=0.7071

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0033 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0062 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095
[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0035 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0067 | NDCG@100: 0.0014 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0051 | NDCG@100: 0.0010 | MAP@100: 0.0002
VAL target: split=ALL K=50 Recall=0.003314

=== TRY: {'max_len': 100, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.0008} ===

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 1/8 loss=2.0114

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 2/8 loss=1.2840

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 3/8 loss=1.1858

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 4/8 loss=1.1137

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 5/8 loss=1.0402

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 6/8 loss=0.9440

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 7/8 loss=0.8544

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 8/8 loss=0.7965

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0032 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0057 | NDCG@100: 0.0012 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095
[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0013 | NDCG@20: 0.0004 | MAP@20: 0.0002
K=50 | Recall@50: 0.0033 | NDCG@50: 0.0008 | MAP@50: 0.0002
K=100 | Recall@100: 0.0062 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target: split=ALL K=50 Recall=0.003157

=== TRY: {'max_len': 100, 'hidden': 128, 'n_heads': 4, 'dropout': 0.3, 'lr': 0.0005} ===

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 1/8 loss=3.9998

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 2/8 loss=1.6945

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 3/8 loss=1.3848

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 4/8 loss=1.2486

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 5/8 loss=1.1559

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 6/8 loss=1.0763

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 7/8 loss=0.9996

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]

[SASRec] epoch 8/8 loss=0.9225

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0015 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0032 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0057 | NDCG@100: 0.0012 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095
[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0004 | MAP@20: 0.0002
K=50 | Recall@50: 0.0034 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0062 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0025 | NDCG@20: 0.0007 | MAP@20: 0.0002
K=50 | Recall@50: 0.0025 | NDCG@50: 0.0007 | MAP@50: 0.0002
K=100 | Recall@100: 0.0042 | NDCG@100: 0.0010 | MAP@100: 0.0003
VAL target: split=ALL K=50 Recall=0.003220

BEST: {'max_len': 50, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.001} score= 0.003346065216705073

In [ ]:
best_cfg = best["cfg"]

sas_model_test, sas_rec_test = fit_sasrec(
    test_pack,
    seqs_train=test_seqs_train,
    seqs_infer=test_seqs_infer,
    item_side_np=test_item_side,
    max_len=best_cfg["max_len"],
    hidden=best_cfg["hidden"],
    n_layers=2,
    n_heads=best_cfg["n_heads"],
    dropout=best_cfg["dropout"],
    lr=best_cfg["lr"],
    weight_decay=1e-4,
    batch_size=256,
    steps_per_epoch=2500,
    epochs=15,
    n_neg=20,
    maxK_cache=max(KS),
    batch_users_eval=512,
)

outs_sas = evaluate_pack_subsets(test_pack, sas_rec_test, "SASRec", ks=KS)
outs_sas

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 1/15 loss=1.6313

SASRec epoch 2/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 2/15 loss=1.1631

SASRec epoch 3/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 3/15 loss=1.0054

SASRec epoch 4/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 4/15 loss=0.8426

SASRec epoch 5/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 5/15 loss=0.7760

SASRec epoch 6/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 6/15 loss=0.7354

SASRec epoch 7/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 7/15 loss=0.7002

SASRec epoch 8/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 8/15 loss=0.6693

SASRec epoch 9/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 9/15 loss=0.6408

SASRec epoch 10/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 10/15 loss=0.6117

SASRec epoch 11/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 11/15 loss=0.5849

SASRec epoch 12/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 12/15 loss=0.5595

SASRec epoch 13/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 13/15 loss=0.5368

SASRec epoch 14/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 14/15 loss=0.5143

SASRec epoch 15/15:   0%|          | 0/2500 [00:00<?, ?it/s]

[SASRec] epoch 15/15 loss=0.4949

[SASRec/ALL] n=31744
[SASRec/ALL] short rec lists: 0/31744 (0.000)

=== SASRec/ALL ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0001 | MAP@5: 0.0000
K=10 | Recall@10: 0.0007 | NDCG@10: 0.0002 | MAP@10: 0.0001
K=20 | Recall@20: 0.0013 | NDCG@20: 0.0004 | MAP@20: 0.0001
K=50 | Recall@50: 0.0029 | NDCG@50: 0.0007 | MAP@50: 0.0002
K=100 | Recall@100: 0.0059 | NDCG@100: 0.0012 | MAP@100: 0.0002

[SASRec/WARM] n=24653
[SASRec/WARM] short rec lists: 0/24653 (0.000)

=== SASRec/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0007 | NDCG@10: 0.0002 | MAP@10: 0.0001
K=20 | Recall@20: 0.0013 | NDCG@20: 0.0004 | MAP@20: 0.0001
K=50 | Recall@50: 0.0032 | NDCG@50: 0.0007 | MAP@50: 0.0002
K=100 | Recall@100: 0.0064 | NDCG@100: 0.0012 | MAP@100: 0.0002

[SASRec/COLD] n=1138
[SASRec/COLD] short rec lists: 0/1138 (0.000)

=== SASRec/COLD ===
K= 5 | Recall@5: 0.0009 | NDCG@5: 0.0009 | MAP@5: 0.0009
K=10 | Recall@10: 0.0009 | NDCG@10: 0.0009 | MAP@10: 0.0009
K=20 | Recall@20: 0.0009 | NDCG@20: 0.0009 | MAP@20: 0.0009
K=50 | Recall@50: 0.0009 | NDCG@50: 0.0009 | MAP@50: 0.0009
K=100 | Recall@100: 0.0044 | NDCG@100: 0.0014 | MAP@100: 0.0009

{'ALL': {5: (9.450604838709677e-05,
   np.float64(5.5875302875160136e-05),
   4.410282258064516e-05),
  10: (0.0006615423387096774,
   np.float64(0.00023079839605359242),
   0.00011129462285586277),
  20: (0.0012600806451612903,
   np.float64(0.0003769998207130594),
   0.0001488154958516535),
  50: (0.0028666834677419355,
   np.float64(0.0006835768627662353),
   0.00019299798380820676),
  100: (0.005890877016129032,
   np.float64(0.0011702855589493034),
   0.00023477618927559952)},
 'WARM': {5: (8.112602928649658e-05,
   np.float64(3.1383832169272836e-05),
   1.6225205857299314e-05),
  10: (0.0007301342635784692,
   np.float64(0.00022865062117729618),
   9.018832184369847e-05),
  20: (0.0012980164685839452,
   np.float64(0.0003660673670741052),
   0.00012485163486322738),
  50: (0.003163915142173366,
   np.float64(0.0007212622418948422),
   0.00017571692813415078),
  100: (0.006408956313633229,
   np.float64(0.0012434274062375953),
   0.0002204793367010523)},
 'COLD': {5: (0.0008787346221441124,
   np.float64(0.0008787346221441124),
   0.0008787346221441124),
  10: (0.0008787346221441124,
   np.float64(0.0008787346221441124),
   0.0008787346221441124),
  20: (0.0008787346221441124,
   np.float64(0.0008787346221441124),
   0.0008787346221441124),
  50: (0.0008787346221441124,
   np.float64(0.0008787346221441124),
   0.0008787346221441124),
  100: (0.004393673110720563,
   np.float64(0.001440646951472807),
   0.000925924557308317)}}

In [ ]:
def evaluate_pack_subsets(pack, recommend_fn, name, ks=KS):
    ef = pack["eval_f"]
    outs = {}

    def run(mask, split):
        u = ef.loc[mask, "u"].values
        i = ef.loc[mask, "i"].values
        print(f"\n[{name}/{split}] n={len(u)}")
        out = evaluate_next_item(u, i, recommend_fn, ks=ks, name=f"{name}/{split}")
        print_metrics(f"{name}/{split}", out, ks=ks)
        return out

    outs["ALL"]  = run(np.ones(len(ef), dtype=bool), "ALL")
    outs["WARM"] = run(ef["is_warm_item_eligible"].values, "WARM")
    outs["COLD"] = run(ef["is_cold_item"].values, "COLD")
    return outs

In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

device: cuda

In [ ]:
def build_user_sequences(pack):
    tf = pack["train_f"][["u","i","date"]].copy()
    tf["date"] = pd.to_datetime(tf["date"])
    tf = tf.sort_values(["u","date"])

    seqs = {}
    for u, g in tf.groupby("u", sort=False):
        seq = g["i"].astype(np.int32).to_numpy()
        if len(seq) >= 2:
            seqs[int(u)] = seq
    return seqs

val_seqs  = build_user_sequences(val_pack)
test_seqs = build_user_sequences(test_pack)

print("val_seqs users:", len(val_seqs), "test_seqs users:", len(test_seqs))

val_seqs users: 30881 test_seqs users: 31486

In [ ]:
def build_item_side_emb(item_docs, n_items, side_dim=64, min_df=2, max_features=200_000, seed=42):
    assert len(item_docs) == n_items, f"len(item_docs)={len(item_docs)} must equal n_items={n_items}"

    vec = TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1,1),
        sublinear_tf=True,
        norm="l2",
        min_df=min_df,
        max_features=max_features,
    )
    X = vec.fit_transform(item_docs).astype(np.float32)

    svd = TruncatedSVD(n_components=int(side_dim), random_state=int(seed))
    Z = svd.fit_transform(X).astype(np.float32)  # (n_items, side_dim)

    # добавим padding row в начало: index 0 = PAD
    Zpad = np.zeros((n_items + 1, side_dim), dtype=np.float32)
    Zpad[1:, :] = Z
    return Zpad

# параметры side-emb (можете сравнить min_df=1 vs 2 именно для cold)
SIDE_DIM = 64
SIDE_MIN_DF = 2  # попробуйте 1 или 2

val_item_side  = build_item_side_emb(item_docs_val,  val_pack["n_items"],  side_dim=SIDE_DIM, min_df=SIDE_MIN_DF, seed=SEED)
test_item_side = build_item_side_emb(item_docs_test, test_pack["n_items"], side_dim=SIDE_DIM, min_df=SIDE_MIN_DF, seed=SEED)

print("val_item_side:", val_item_side.shape, "test_item_side:", test_item_side.shape)

val_item_side: (18766, 64) test_item_side: (19943, 64)

In [ ]:
class SASRec(nn.Module):
    def __init__(self, n_items, max_len=50, hidden=64, n_layers=2, n_heads=2, dropout=0.2,
                 side_dim=64, use_side=True):
        super().__init__()
        self.n_items = int(n_items)
        self.max_len = int(max_len)
        self.hidden = int(hidden)
        self.use_side = bool(use_side)

        # +1: PAD=0, items are shifted by +1
        self.item_emb = nn.Embedding(self.n_items + 1, self.hidden, padding_idx=0)
        self.pos_emb  = nn.Embedding(self.max_len, self.hidden)

        if self.use_side:
            self.side_proj = nn.Linear(int(side_dim), self.hidden, bias=False)

        self.dropout = nn.Dropout(dropout)
        self.norm = nn.LayerNorm(self.hidden)

        enc_layer = nn.TransformerEncoderLayer(
            d_model=self.hidden,
            nhead=int(n_heads),
            dim_feedforward=self.hidden * 4,
            dropout=float(dropout),
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=int(n_layers))

    def forward(self, seq, side_feats=None):
        """
        seq: (B, L) int64, values in [0..n_items] where 0=PAD, real item = i+1
        side_feats: (n_items+1, side_dim) float32 on device (optional)
        """
        B, L = seq.shape
        pos = torch.arange(L, device=seq.device).unsqueeze(0).expand(B, L)

        x = self.item_emb(seq) + self.pos_emb(pos)

        if self.use_side:
            assert side_feats is not None
            x = x + self.side_proj(side_feats[seq])  # gather side vectors for tokens

        x = self.dropout(self.norm(x))

        # causal mask (no looking ahead)
        # mask shape (L, L): True = masked
        causal = torch.triu(torch.ones(L, L, device=seq.device, dtype=torch.bool), diagonal=1)

        # key padding mask: True = PAD positions
        pad_mask = (seq == 0)

        h = self.encoder(x, mask=causal, src_key_padding_mask=pad_mask)
        return h  # (B,L,H)

    def item_vectors(self, side_feats=None):
        """
        Return item vectors for scoring: (n_items+1, H)
        """
        w = self.item_emb.weight  # (n_items+1,H)
        if self.use_side:
            assert side_feats is not None
            w = w + self.side_proj(side_feats)
        return w

In [ ]:
class SASRecDataset(Dataset):
    def __init__(self, seqs_by_u, n_items, max_len=50, n_samples=200_000, seed=42, neg_pool_items=None):
        self.users = list(seqs_by_u.keys())
        self.seqs = seqs_by_u
        self.n_items = int(n_items)
        self.max_len = int(max_len)
        self.n_samples = int(n_samples)
        self.rng = np.random.default_rng(seed)

        if neg_pool_items is None:
            self.neg_pool = np.arange(self.n_items, dtype=np.int32)
        else:
            self.neg_pool = np.asarray(neg_pool_items, dtype=np.int32)

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        # pick user
        u = int(self.users[self.rng.integers(0, len(self.users))])
        seq = self.seqs[u]
        # pick position t (predict seq[t] from history seq[:t])
        t = int(self.rng.integers(1, len(seq)))
        pos = int(seq[t])

        hist = seq[:t]
        # last max_len items
        hist = hist[-self.max_len:]
        # shift by +1, PAD=0
        tokens = np.zeros(self.max_len, dtype=np.int64)
        tokens[-len(hist):] = (hist.astype(np.int64) + 1)

        # negative sampling from train pool, avoid picking pos
        neg = pos
        while neg == pos:
            neg = int(self.neg_pool[self.rng.integers(0, len(self.neg_pool))])

        return tokens, np.int64(pos + 1), np.int64(neg + 1)  # shift +1

In [ ]:
@torch.no_grad()
def _encode_last(model, seq_batch, side_feats):
    h = model(seq_batch, side_feats=side_feats)   # (B,L,H)
    # берём последний НЕ-PAD токен: проще взять последний индекс (L-1), т.к. мы PAD слева
    last = h[:, -1, :]                            # (B,H)
    return last

def make_sasrec_recommender(pack, model, seqs_by_u, side_feats_np, maxK=50, batch_users=512):
    model.eval()
    side_feats = torch.from_numpy(side_feats_np).to(device)  # (n_items+1, side_dim)

    user_train_items = pack["user_train_items"]
    n_items = pack["n_items"]
    max_len = model.max_len

    cache = {}  # u -> np.int32[maxK]  (items in 0..n_items-1)

    # Предвычисление top-maxK для списка users (ускоряет ALL/WARM/COLD подряд)
    def _precompute(users):
        users = [int(u) for u in users]
        for s in range(0, len(users), batch_users):
            ub = users[s:s+batch_users]
            # build batch sequences
            X = np.zeros((len(ub), max_len), dtype=np.int64)
            for j, u in enumerate(ub):
                seq = seqs_by_u.get(u, None)
                if seq is None or len(seq) == 0:
                    continue
                hist = seq[-max_len:]
                X[j, -len(hist):] = (hist.astype(np.int64) + 1)

            X = torch.from_numpy(X).to(device)
            uvec = _encode_last(model, X, side_feats)            # (B,H)
            item_vecs = model.item_vectors(side_feats)           # (n_items+1,H)

            # scores for all items (including PAD=0)
            scores = (uvec @ item_vecs.T)                        # (B, n_items+1)
            scores[:, 0] = -1e9                                  # forbid PAD

            # filter seen
            for j, u in enumerate(ub):
                seen = user_train_items.get(u, None)
                if seen:
                    idx = torch.tensor([int(i)+1 for i in seen], device=device, dtype=torch.long)
                    scores[j, idx] = -1e9

            # topK in shifted space, then unshift back
            top = torch.topk(scores, k=min(maxK, n_items), dim=1).indices.cpu().numpy()  # (B,K) indices in [0..n_items]
            for j, u in enumerate(ub):
                # convert from shifted idx to item idx
                items = top[j]
                items = items[items != 0] - 1
                cache[u] = items.astype(np.int32)

    def recommend_fn(u, K):
        u = int(u); K = int(K)
        if K <= 0:
            return np.array([], dtype=np.int32)

        if u not in cache:
            # лениво предвычисляем сразу для всех eval users (ускоряет дальнейшие split-оценки)
            all_eval_users = np.unique(pack["eval_u"]).astype(np.int32).tolist()
            _precompute(all_eval_users)

        arr = cache.get(u, np.array([], dtype=np.int32))
        if arr.size <= K:
            return arr
        return arr[:K]

    return recommend_fn

In [ ]:
def fit_sasrec(pack, seqs_by_u, item_side_np,
               max_len=50, hidden=64, n_layers=2, n_heads=2, dropout=0.2,
               lr=1e-3, weight_decay=0.0, batch_size=256, steps_per_epoch=2000, epochs=10,
               n_neg_pool_from_train=True, maxK_cache=50):

    n_items = pack["n_items"]

    # neg pool = items that appear in train_f (eligible items)
    if n_neg_pool_from_train:
        train_item_ids = np.unique(pack["train_f"]["i"].astype(np.int32).to_numpy())
        neg_pool = train_item_ids
    else:
        neg_pool = np.arange(n_items, dtype=np.int32)

    ds = SASRecDataset(
        seqs_by_u=seqs_by_u,
        n_items=n_items,
        max_len=max_len,
        n_samples=steps_per_epoch * batch_size,
        seed=SEED,
        neg_pool_items=neg_pool,
    )
    dl = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=(device.type=="cuda"))

    model = SASRec(
        n_items=n_items,
        max_len=max_len,
        hidden=hidden,
        n_layers=n_layers,
        n_heads=n_heads,
        dropout=dropout,
        side_dim=item_side_np.shape[1],
        use_side=True,
    ).to(device)

    side_feats = torch.from_numpy(item_side_np).to(device)

    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    bce = nn.BCEWithLogitsLoss()

    model.train()
    for ep in range(1, epochs+1):
      losses = []
      model.train()

      pbar = tqdm(total=steps_per_epoch, desc=f"SASRec epoch {ep}/{epochs}", leave=False)
      it = 0

      for tokens, pos, neg in dl:
          tokens = tokens.to(device, non_blocking=True)
          pos = pos.to(device, non_blocking=True)
          neg = neg.to(device, non_blocking=True)

          h = model(tokens, side_feats=side_feats)[:, -1, :]  # (B,H)

          item_vecs = model.item_vectors(side_feats)  # (n_items+1,H)
          pos_v = item_vecs[pos]
          neg_v = item_vecs[neg]

          pos_logit = (h * pos_v).sum(dim=1)
          neg_logit = (h * neg_v).sum(dim=1)

          loss = bce(pos_logit, torch.ones_like(pos_logit)) + \
                bce(neg_logit, torch.zeros_like(neg_logit))

          opt.zero_grad(set_to_none=True)
          loss.backward()
          torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
          opt.step()

          l = float(loss.item())
          losses.append(l)

          it += 1
          pbar.update(1)
          if it % 50 == 0:
              pbar.set_postfix(loss=np.mean(losses[-50:]))
          if it >= steps_per_epoch:
              break

      pbar.close()
      print(f"[SASRec] epoch {ep}/{epochs} loss={np.mean(losses):.4f}")

    # recommender with cache
    rec_fn = make_sasrec_recommender(pack, model, seqs_by_u, item_side_np, maxK=maxK_cache)
    return model, rec_fn


# ---- hyperparam search on VAL ----
target_split = "ALL"   # можно "WARM" если цель — качество на warm
target_k = 50          # какую K оптимизируем

grid = [
    dict(max_len=50,  hidden=64,  n_heads=2, dropout=0.2, lr=1e-3),
    dict(max_len=50,  hidden=128, n_heads=4, dropout=0.2, lr=8e-4),
    dict(max_len=100, hidden=64,  n_heads=2, dropout=0.2, lr=8e-4),
    dict(max_len=100, hidden=128, n_heads=4, dropout=0.3, lr=5e-4),
]

best = {"score": -1, "cfg": None, "model": None, "rec": None}

for cfg in tqdm(grid, desc="SASRec hyperparam search"):
    print("\n=== TRY:", cfg, "===")
    model, rec = fit_sasrec(
        val_pack, val_seqs, val_item_side,
        max_len=cfg["max_len"],
        hidden=cfg["hidden"],
        n_layers=2,
        n_heads=cfg["n_heads"],
        dropout=cfg["dropout"],
        lr=cfg["lr"],
        weight_decay=1e-4,
        batch_size=256,
        steps_per_epoch=1500,   # ускорение тюнинга
        epochs=8,               # ускорение тюнинга
        maxK_cache=max(KS),
    )

    outs = evaluate_pack_subsets(val_pack, rec, "SASRec(VAL)", ks=KS)
    score = outs[target_split][target_k][0]  # Recall

    print(f"VAL target score: split={target_split} K={target_k} Recall={score:.6f}")

    if score > best["score"]:
        best = {"score": score, "cfg": cfg, "model": model, "rec": rec}

print("\nBEST:", best["cfg"], "score=", best["score"])

SASRec hyperparam search:   0%|          | 0/4 [00:00<?, ?it/s]

=== TRY: {'max_len': 50, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.001} ===

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 1/8:   0%|          | 1/1500 [00:02<52:36,  2.11s/it]
SASRec epoch 1/8:   0%|          | 5/1500 [00:02<08:30,  2.93it/s]
SASRec epoch 1/8:   1%|          | 9/1500 [00:02<04:13,  5.88it/s]
SASRec epoch 1/8:   1%|          | 13/1500 [00:02<02:42,  9.18it/s]
SASRec epoch 1/8:   1%|          | 17/1500 [00:02<01:54, 13.00it/s]
SASRec epoch 1/8:   1%|▏         | 21/1500 [00:02<01:28, 16.74it/s]
SASRec epoch 1/8:   2%|▏         | 26/1500 [00:02<01:07, 21.76it/s]
SASRec epoch 1/8:   2%|▏         | 30/1500 [00:02<00:58, 25.24it/s]
SASRec epoch 1/8:   2%|▏         | 34/1500 [00:03<00:51, 28.25it/s]
SASRec epoch 1/8:   3%|▎         | 39/1500 [00:03<00:45, 32.16it/s]
SASRec epoch 1/8:   3%|▎         | 45/1500 [00:03<00:37, 38.33it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:03<00:35, 40.45it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:03<00:35, 40.45it/s, loss=6.71]
SASRec epoch 1/8:   4%|▎         | 56/1500 [00:03<00:32, 44.21it/s, loss=6.71]
SASRec epoch 1/8:   4%|▍         | 62/1500 [00:03<00:30, 47.39it/s, loss=6.71]
SASRec epoch 1/8:   5%|▍         | 68/1500 [00:03<00:28, 49.74it/s, loss=6.71]
SASRec epoch 1/8:   5%|▍         | 74/1500 [00:03<00:27, 51.11it/s, loss=6.71]
SASRec epoch 1/8:   5%|▌         | 80/1500 [00:03<00:27, 52.38it/s, loss=6.71]
SASRec epoch 1/8:   6%|▌         | 86/1500 [00:04<00:26, 52.85it/s, loss=6.71]
SASRec epoch 1/8:   6%|▌         | 92/1500 [00:04<00:27, 51.00it/s, loss=6.71]
SASRec epoch 1/8:   7%|▋         | 98/1500 [00:04<00:28, 49.29it/s, loss=6.71]
SASRec epoch 1/8:   7%|▋         | 100/1500 [00:04<00:28, 49.29it/s, loss=4.92]
SASRec epoch 1/8:   7%|▋         | 103/1500 [00:04<00:28, 48.20it/s, loss=4.92]
SASRec epoch 1/8:   7%|▋         | 109/1500 [00:04<00:27, 50.40it/s, loss=4.92]
SASRec epoch 1/8:   8%|▊         | 115/1500 [00:04<00:26, 51.91it/s, loss=4.92]
SASRec epoch 1/8:   8%|▊         | 121/1500 [00:04<00:26, 52.74it/s, loss=4.92]
SASRec epoch 1/8:   8%|▊         | 127/1500 [00:04<00:25, 53.51it/s, loss=4.92]
SASRec epoch 1/8:   9%|▉         | 133/1500 [00:04<00:25, 54.20it/s, loss=4.92]
SASRec epoch 1/8:   9%|▉         | 139/1500 [00:05<00:24, 54.76it/s, loss=4.92]
SASRec epoch 1/8:  10%|▉         | 145/1500 [00:05<00:24, 55.15it/s, loss=4.92]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:05<00:24, 55.15it/s, loss=3.6]
SASRec epoch 1/8:  10%|█         | 151/1500 [00:05<00:24, 54.12it/s, loss=3.6]
SASRec epoch 1/8:  10%|█         | 157/1500 [00:05<00:25, 52.80it/s, loss=3.6]
SASRec epoch 1/8:  11%|█         | 163/1500 [00:05<00:24, 53.60it/s, loss=3.6]
SASRec epoch 1/8:  11%|█▏        | 169/1500 [00:05<00:24, 54.03it/s, loss=3.6]
SASRec epoch 1/8:  12%|█▏        | 175/1500 [00:05<00:24, 54.61it/s, loss=3.6]
SASRec epoch 1/8:  12%|█▏        | 181/1500 [00:05<00:24, 54.72it/s, loss=3.6]
SASRec epoch 1/8:  12%|█▏        | 187/1500 [00:05<00:24, 54.54it/s, loss=3.6]
SASRec epoch 1/8:  13%|█▎        | 193/1500 [00:06<00:23, 55.07it/s, loss=3.6]
SASRec epoch 1/8:  13%|█▎        | 199/1500 [00:06<00:23, 54.85it/s, loss=3.6]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:06<00:23, 54.85it/s, loss=2.85]
SASRec epoch 1/8:  14%|█▎        | 205/1500 [00:06<00:24, 53.84it/s, loss=2.85]
SASRec epoch 1/8:  14%|█▍        | 211/1500 [00:06<00:23, 54.41it/s, loss=2.85]
SASRec epoch 1/8:  14%|█▍        | 217/1500 [00:06<00:24, 52.50it/s, loss=2.85]
SASRec epoch 1/8:  15%|█▍        | 223/1500 [00:06<00:23, 53.37it/s, loss=2.85]
SASRec epoch 1/8:  15%|█▌        | 229/1500 [00:06<00:23, 54.12it/s, loss=2.85]
SASRec epoch 1/8:  16%|█▌        | 235/1500 [00:06<00:23, 54.69it/s, loss=2.85]
SASRec epoch 1/8:  16%|█▌        | 241/1500 [00:06<00:22, 55.00it/s, loss=2.85]
SASRec epoch 1/8:  16%|█▋        | 247/1500 [00:07<00:22, 55.47it/s, loss=2.85]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:07<00:22, 55.47it/s, loss=2.5]
SASRec epoch 1/8:  17%|█▋        | 253/1500 [00:07<00:23, 54.11it/s, loss=2.5]
SASRec epoch 1/8:  17%|█▋        | 259/1500 [00:07<00:22, 54.73it/s, loss=2.5]
SASRec epoch 1/8:  18%|█▊        | 265/1500 [00:07<00:22, 55.35it/s, loss=2.5]
SASRec epoch 1/8:  18%|█▊        | 271/1500 [00:07<00:22, 53.53it/s, loss=2.5]
SASRec epoch 1/8:  18%|█▊        | 277/1500 [00:07<00:22, 54.42it/s, loss=2.5]
SASRec epoch 1/8:  19%|█▉        | 283/1500 [00:07<00:22, 54.74it/s, loss=2.5]
SASRec epoch 1/8:  19%|█▉        | 289/1500 [00:07<00:22, 54.83it/s, loss=2.5]
SASRec epoch 1/8:  20%|█▉        | 295/1500 [00:07<00:21, 54.80it/s, loss=2.5]
SASRec epoch 1/8:  20%|██        | 300/1500 [00:07<00:21, 54.80it/s, loss=2.35]
SASRec epoch 1/8:  20%|██        | 301/1500 [00:08<00:22, 53.93it/s, loss=2.35]
SASRec epoch 1/8:  20%|██        | 307/1500 [00:08<00:21, 54.37it/s, loss=2.35]
SASRec epoch 1/8:  21%|██        | 313/1500 [00:08<00:21, 54.20it/s, loss=2.35]
SASRec epoch 1/8:  21%|██▏       | 319/1500 [00:08<00:21, 54.41it/s, loss=2.35]
SASRec epoch 1/8:  22%|██▏       | 325/1500 [00:08<00:21, 54.00it/s, loss=2.35]
SASRec epoch 1/8:  22%|██▏       | 331/1500 [00:08<00:22, 52.88it/s, loss=2.35]
SASRec epoch 1/8:  22%|██▏       | 337/1500 [00:08<00:21, 53.28it/s, loss=2.35]
SASRec epoch 1/8:  23%|██▎       | 343/1500 [00:08<00:21, 53.64it/s, loss=2.35]
SASRec epoch 1/8:  23%|██▎       | 349/1500 [00:08<00:21, 54.17it/s, loss=2.35]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:08<00:21, 54.17it/s, loss=2.24]
SASRec epoch 1/8:  24%|██▎       | 355/1500 [00:09<00:21, 53.95it/s, loss=2.24]
SASRec epoch 1/8:  24%|██▍       | 361/1500 [00:09<00:20, 54.47it/s, loss=2.24]
SASRec epoch 1/8:  24%|██▍       | 367/1500 [00:09<00:20, 54.14it/s, loss=2.24]
SASRec epoch 1/8:  25%|██▍       | 373/1500 [00:09<00:20, 54.14it/s, loss=2.24]
SASRec epoch 1/8:  25%|██▌       | 379/1500 [00:09<00:20, 54.47it/s, loss=2.24]
SASRec epoch 1/8:  26%|██▌       | 385/1500 [00:09<00:20, 53.33it/s, loss=2.24]
SASRec epoch 1/8:  26%|██▌       | 391/1500 [00:09<00:20, 53.69it/s, loss=2.24]
SASRec epoch 1/8:  26%|██▋       | 397/1500 [00:09<00:20, 54.40it/s, loss=2.24]
SASRec epoch 1/8:  27%|██▋       | 400/1500 [00:09<00:20, 54.40it/s, loss=2.11]
SASRec epoch 1/8:  27%|██▋       | 403/1500 [00:09<00:20, 53.68it/s, loss=2.11]
SASRec epoch 1/8:  27%|██▋       | 409/1500 [00:10<00:20, 53.69it/s, loss=2.11]
SASRec epoch 1/8:  28%|██▊       | 415/1500 [00:10<00:20, 53.96it/s, loss=2.11]
SASRec epoch 1/8:  28%|██▊       | 421/1500 [00:10<00:19, 54.15it/s, loss=2.11]
SASRec epoch 1/8:  28%|██▊       | 427/1500 [00:10<00:19, 54.05it/s, loss=2.11]
SASRec epoch 1/8:  29%|██▉       | 433/1500 [00:10<00:19, 54.50it/s, loss=2.11]
SASRec epoch 1/8:  29%|██▉       | 439/1500 [00:10<00:20, 52.99it/s, loss=2.11]
SASRec epoch 1/8:  30%|██▉       | 445/1500 [00:10<00:19, 53.40it/s, loss=2.11]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:10<00:19, 53.40it/s, loss=2.03]
SASRec epoch 1/8:  30%|███       | 451/1500 [00:10<00:20, 52.43it/s, loss=2.03]
SASRec epoch 1/8:  30%|███       | 457/1500 [00:10<00:19, 53.58it/s, loss=2.03]
SASRec epoch 1/8:  31%|███       | 463/1500 [00:11<00:19, 54.37it/s, loss=2.03]
SASRec epoch 1/8:  31%|███▏      | 469/1500 [00:11<00:18, 54.40it/s, loss=2.03]
SASRec epoch 1/8:  32%|███▏      | 475/1500 [00:11<00:18, 54.57it/s, loss=2.03]
SASRec epoch 1/8:  32%|███▏      | 481/1500 [00:11<00:18, 54.96it/s, loss=2.03]
SASRec epoch 1/8:  32%|███▏      | 487/1500 [00:11<00:18, 55.03it/s, loss=2.03]
SASRec epoch 1/8:  33%|███▎      | 493/1500 [00:11<00:18, 54.97it/s, loss=2.03]
SASRec epoch 1/8:  33%|███▎      | 499/1500 [00:11<00:18, 52.97it/s, loss=2.03]
SASRec epoch 1/8:  33%|███▎      | 500/1500 [00:11<00:18, 52.97it/s, loss=1.95]
SASRec epoch 1/8:  34%|███▎      | 505/1500 [00:11<00:18, 52.82it/s, loss=1.95]
SASRec epoch 1/8:  34%|███▍      | 511/1500 [00:11<00:18, 53.28it/s, loss=1.95]
SASRec epoch 1/8:  34%|███▍      | 517/1500 [00:12<00:18, 54.10it/s, loss=1.95]
SASRec epoch 1/8:  35%|███▍      | 523/1500 [00:12<00:18, 54.02it/s, loss=1.95]
SASRec epoch 1/8:  35%|███▌      | 529/1500 [00:12<00:17, 54.60it/s, loss=1.95]
SASRec epoch 1/8:  36%|███▌      | 535/1500 [00:12<00:17, 54.85it/s, loss=1.95]
SASRec epoch 1/8:  36%|███▌      | 541/1500 [00:12<00:17, 54.87it/s, loss=1.95]
SASRec epoch 1/8:  36%|███▋      | 547/1500 [00:12<00:17, 53.97it/s, loss=1.95]
SASRec epoch 1/8:  37%|███▋      | 550/1500 [00:12<00:17, 53.97it/s, loss=1.87]
SASRec epoch 1/8:  37%|███▋      | 553/1500 [00:12<00:18, 51.40it/s, loss=1.87]
SASRec epoch 1/8:  37%|███▋      | 559/1500 [00:12<00:17, 52.45it/s, loss=1.87]
SASRec epoch 1/8:  38%|███▊      | 565/1500 [00:12<00:17, 53.53it/s, loss=1.87]
SASRec epoch 1/8:  38%|███▊      | 571/1500 [00:13<00:17, 54.22it/s, loss=1.87]
SASRec epoch 1/8:  38%|███▊      | 577/1500 [00:13<00:17, 52.19it/s, loss=1.87]
SASRec epoch 1/8:  39%|███▉      | 583/1500 [00:13<00:19, 47.71it/s, loss=1.87]
SASRec epoch 1/8:  39%|███▉      | 588/1500 [00:13<00:19, 46.42it/s, loss=1.87]
SASRec epoch 1/8:  40%|███▉      | 593/1500 [00:13<00:19, 46.01it/s, loss=1.87]
SASRec epoch 1/8:  40%|███▉      | 598/1500 [00:13<00:20, 45.03it/s, loss=1.87]
SASRec epoch 1/8:  40%|████      | 600/1500 [00:13<00:19, 45.03it/s, loss=1.85]
SASRec epoch 1/8:  40%|████      | 603/1500 [00:13<00:20, 43.37it/s, loss=1.85]
SASRec epoch 1/8:  41%|████      | 608/1500 [00:13<00:20, 43.68it/s, loss=1.85]
SASRec epoch 1/8:  41%|████      | 613/1500 [00:13<00:20, 44.25it/s, loss=1.85]
SASRec epoch 1/8:  41%|████      | 618/1500 [00:14<00:19, 44.31it/s, loss=1.85]
SASRec epoch 1/8:  42%|████▏     | 623/1500 [00:14<00:19, 44.51it/s, loss=1.85]
SASRec epoch 1/8:  42%|████▏     | 628/1500 [00:14<00:19, 45.31it/s, loss=1.85]
SASRec epoch 1/8:  42%|████▏     | 633/1500 [00:14<00:19, 45.18it/s, loss=1.85]
SASRec epoch 1/8:  43%|████▎     | 638/1500 [00:14<00:18, 45.82it/s, loss=1.85]
SASRec epoch 1/8:  43%|████▎     | 643/1500 [00:14<00:18, 45.85it/s, loss=1.85]
SASRec epoch 1/8:  43%|████▎     | 648/1500 [00:14<00:18, 45.60it/s, loss=1.85]
SASRec epoch 1/8:  43%|████▎     | 650/1500 [00:14<00:18, 45.60it/s, loss=1.79]
SASRec epoch 1/8:  44%|████▎     | 653/1500 [00:14<00:20, 42.18it/s, loss=1.79]
SASRec epoch 1/8:  44%|████▍     | 658/1500 [00:15<00:19, 42.75it/s, loss=1.79]
SASRec epoch 1/8:  44%|████▍     | 663/1500 [00:15<00:19, 43.06it/s, loss=1.79]
SASRec epoch 1/8:  45%|████▍     | 668/1500 [00:15<00:19, 43.22it/s, loss=1.79]
SASRec epoch 1/8:  45%|████▍     | 673/1500 [00:15<00:19, 43.45it/s, loss=1.79]
SASRec epoch 1/8:  45%|████▌     | 678/1500 [00:15<00:19, 43.13it/s, loss=1.79]
SASRec epoch 1/8:  46%|████▌     | 683/1500 [00:15<00:19, 42.77it/s, loss=1.79]
SASRec epoch 1/8:  46%|████▌     | 688/1500 [00:15<00:19, 42.13it/s, loss=1.79]
SASRec epoch 1/8:  46%|████▌     | 693/1500 [00:15<00:19, 40.96it/s, loss=1.79]
SASRec epoch 1/8:  47%|████▋     | 698/1500 [00:15<00:20, 39.34it/s, loss=1.79]
SASRec epoch 1/8:  47%|████▋     | 700/1500 [00:16<00:20, 39.34it/s, loss=1.74]
SASRec epoch 1/8:  47%|████▋     | 702/1500 [00:16<00:21, 37.24it/s, loss=1.74]
SASRec epoch 1/8:  47%|████▋     | 706/1500 [00:16<00:21, 36.12it/s, loss=1.74]
SASRec epoch 1/8:  47%|████▋     | 710/1500 [00:16<00:21, 36.99it/s, loss=1.74]
SASRec epoch 1/8:  48%|████▊     | 715/1500 [00:16<00:20, 38.27it/s, loss=1.74]
SASRec epoch 1/8:  48%|████▊     | 719/1500 [00:16<00:20, 37.54it/s, loss=1.74]
SASRec epoch 1/8:  48%|████▊     | 723/1500 [00:16<00:20, 37.78it/s, loss=1.74]
SASRec epoch 1/8:  48%|████▊     | 727/1500 [00:16<00:20, 38.02it/s, loss=1.74]
SASRec epoch 1/8:  49%|████▊     | 731/1500 [00:16<00:20, 37.49it/s, loss=1.74]
SASRec epoch 1/8:  49%|████▉     | 736/1500 [00:16<00:19, 39.42it/s, loss=1.74]
SASRec epoch 1/8:  49%|████▉     | 742/1500 [00:17<00:17, 44.26it/s, loss=1.74]
SASRec epoch 1/8:  50%|████▉     | 748/1500 [00:17<00:15, 47.32it/s, loss=1.74]
SASRec epoch 1/8:  50%|█████     | 750/1500 [00:17<00:15, 47.32it/s, loss=1.71]
SASRec epoch 1/8:  50%|█████     | 753/1500 [00:17<00:15, 47.90it/s, loss=1.71]
SASRec epoch 1/8:  51%|█████     | 759/1500 [00:17<00:14, 49.71it/s, loss=1.71]
SASRec epoch 1/8:  51%|█████     | 765/1500 [00:17<00:14, 51.14it/s, loss=1.71]
SASRec epoch 1/8:  51%|█████▏    | 771/1500 [00:17<00:13, 52.23it/s, loss=1.71]
SASRec epoch 1/8:  52%|█████▏    | 777/1500 [00:17<00:13, 53.13it/s, loss=1.71]
SASRec epoch 1/8:  52%|█████▏    | 783/1500 [00:17<00:13, 53.48it/s, loss=1.71]
SASRec epoch 1/8:  53%|█████▎    | 789/1500 [00:17<00:13, 53.92it/s, loss=1.71]
SASRec epoch 1/8:  53%|█████▎    | 795/1500 [00:18<00:13, 52.91it/s, loss=1.71]
SASRec epoch 1/8:  53%|█████▎    | 800/1500 [00:18<00:13, 52.91it/s, loss=1.68]
SASRec epoch 1/8:  53%|█████▎    | 801/1500 [00:18<00:13, 52.06it/s, loss=1.68]
SASRec epoch 1/8:  54%|█████▍    | 807/1500 [00:18<00:12, 53.31it/s, loss=1.68]
SASRec epoch 1/8:  54%|█████▍    | 813/1500 [00:18<00:12, 53.98it/s, loss=1.68]
SASRec epoch 1/8:  55%|█████▍    | 819/1500 [00:18<00:12, 54.19it/s, loss=1.68]
SASRec epoch 1/8:  55%|█████▌    | 825/1500 [00:18<00:12, 54.81it/s, loss=1.68]
SASRec epoch 1/8:  55%|█████▌    | 831/1500 [00:18<00:12, 55.15it/s, loss=1.68]
SASRec epoch 1/8:  56%|█████▌    | 837/1500 [00:18<00:12, 55.03it/s, loss=1.68]
SASRec epoch 1/8:  56%|█████▌    | 843/1500 [00:18<00:11, 55.04it/s, loss=1.68]
SASRec epoch 1/8:  57%|█████▋    | 849/1500 [00:19<00:12, 53.50it/s, loss=1.68]
SASRec epoch 1/8:  57%|█████▋    | 850/1500 [00:19<00:12, 53.50it/s, loss=1.65]
SASRec epoch 1/8:  57%|█████▋    | 855/1500 [00:19<00:12, 52.13it/s, loss=1.65]
SASRec epoch 1/8:  57%|█████▋    | 861/1500 [00:19<00:12, 53.04it/s, loss=1.65]
SASRec epoch 1/8:  58%|█████▊    | 867/1500 [00:19<00:11, 53.48it/s, loss=1.65]
SASRec epoch 1/8:  58%|█████▊    | 873/1500 [00:19<00:11, 54.15it/s, loss=1.65]
SASRec epoch 1/8:  59%|█████▊    | 879/1500 [00:19<00:11, 54.57it/s, loss=1.65]
SASRec epoch 1/8:  59%|█████▉    | 885/1500 [00:19<00:11, 54.75it/s, loss=1.65]
SASRec epoch 1/8:  59%|█████▉    | 891/1500 [00:19<00:11, 54.66it/s, loss=1.65]
SASRec epoch 1/8:  60%|█████▉    | 897/1500 [00:19<00:11, 54.55it/s, loss=1.65]
SASRec epoch 1/8:  60%|██████    | 900/1500 [00:20<00:11, 54.55it/s, loss=1.62]
SASRec epoch 1/8:  60%|██████    | 903/1500 [00:20<00:11, 51.46it/s, loss=1.62]
SASRec epoch 1/8:  61%|██████    | 909/1500 [00:20<00:11, 52.20it/s, loss=1.62]
SASRec epoch 1/8:  61%|██████    | 915/1500 [00:20<00:10, 53.40it/s, loss=1.62]
SASRec epoch 1/8:  61%|██████▏   | 921/1500 [00:20<00:10, 53.89it/s, loss=1.62]
SASRec epoch 1/8:  62%|██████▏   | 927/1500 [00:20<00:10, 54.44it/s, loss=1.62]
SASRec epoch 1/8:  62%|██████▏   | 933/1500 [00:20<00:10, 54.70it/s, loss=1.62]
SASRec epoch 1/8:  63%|██████▎   | 939/1500 [00:20<00:10, 54.76it/s, loss=1.62]
SASRec epoch 1/8:  63%|██████▎   | 945/1500 [00:20<00:10, 54.99it/s, loss=1.62]
SASRec epoch 1/8:  63%|██████▎   | 950/1500 [00:20<00:10, 54.99it/s, loss=1.59]
SASRec epoch 1/8:  63%|██████▎   | 951/1500 [00:20<00:10, 53.55it/s, loss=1.59]
SASRec epoch 1/8:  64%|██████▍   | 957/1500 [00:21<00:09, 54.43it/s, loss=1.59]
SASRec epoch 1/8:  64%|██████▍   | 963/1500 [00:21<00:10, 52.78it/s, loss=1.59]
SASRec epoch 1/8:  65%|██████▍   | 969/1500 [00:21<00:09, 53.61it/s, loss=1.59]
SASRec epoch 1/8:  65%|██████▌   | 975/1500 [00:21<00:09, 54.37it/s, loss=1.59]
SASRec epoch 1/8:  65%|██████▌   | 981/1500 [00:21<00:09, 54.95it/s, loss=1.59]
SASRec epoch 1/8:  66%|██████▌   | 987/1500 [00:21<00:09, 55.12it/s, loss=1.59]
SASRec epoch 1/8:  66%|██████▌   | 993/1500 [00:21<00:09, 55.45it/s, loss=1.59]
SASRec epoch 1/8:  67%|██████▋   | 999/1500 [00:21<00:09, 55.36it/s, loss=1.59]
SASRec epoch 1/8:  67%|██████▋   | 1000/1500 [00:21<00:09, 55.36it/s, loss=1.56]
SASRec epoch 1/8:  67%|██████▋   | 1005/1500 [00:21<00:09, 53.84it/s, loss=1.56]
SASRec epoch 1/8:  67%|██████▋   | 1011/1500 [00:22<00:08, 54.45it/s, loss=1.56]
SASRec epoch 1/8:  68%|██████▊   | 1017/1500 [00:22<00:09, 52.60it/s, loss=1.56]
SASRec epoch 1/8:  68%|██████▊   | 1023/1500 [00:22<00:08, 53.52it/s, loss=1.56]
SASRec epoch 1/8:  69%|██████▊   | 1029/1500 [00:22<00:08, 54.00it/s, loss=1.56]
SASRec epoch 1/8:  69%|██████▉   | 1035/1500 [00:22<00:08, 54.52it/s, loss=1.56]
SASRec epoch 1/8:  69%|██████▉   | 1041/1500 [00:22<00:08, 54.62it/s, loss=1.56]
SASRec epoch 1/8:  70%|██████▉   | 1047/1500 [00:22<00:08, 54.67it/s, loss=1.56]
SASRec epoch 1/8:  70%|███████   | 1050/1500 [00:22<00:08, 54.67it/s, loss=1.55]
SASRec epoch 1/8:  70%|███████   | 1053/1500 [00:22<00:08, 53.88it/s, loss=1.55]
SASRec epoch 1/8:  71%|███████   | 1059/1500 [00:22<00:08, 54.08it/s, loss=1.55]
SASRec epoch 1/8:  71%|███████   | 1065/1500 [00:23<00:08, 54.10it/s, loss=1.55]
SASRec epoch 1/8:  71%|███████▏  | 1071/1500 [00:23<00:08, 53.25it/s, loss=1.55]
SASRec epoch 1/8:  72%|███████▏  | 1077/1500 [00:23<00:08, 52.87it/s, loss=1.55]
SASRec epoch 1/8:  72%|███████▏  | 1083/1500 [00:23<00:07, 53.79it/s, loss=1.55]
SASRec epoch 1/8:  73%|███████▎  | 1089/1500 [00:23<00:07, 54.24it/s, loss=1.55]
SASRec epoch 1/8:  73%|███████▎  | 1095/1500 [00:23<00:07, 54.57it/s, loss=1.55]
SASRec epoch 1/8:  73%|███████▎  | 1100/1500 [00:23<00:07, 54.57it/s, loss=1.53]
SASRec epoch 1/8:  73%|███████▎  | 1101/1500 [00:23<00:07, 53.76it/s, loss=1.53]
SASRec epoch 1/8:  74%|███████▍  | 1107/1500 [00:23<00:07, 54.29it/s, loss=1.53]
SASRec epoch 1/8:  74%|███████▍  | 1113/1500 [00:23<00:07, 54.34it/s, loss=1.53]
SASRec epoch 1/8:  75%|███████▍  | 1119/1500 [00:24<00:06, 54.51it/s, loss=1.53]
SASRec epoch 1/8:  75%|███████▌  | 1125/1500 [00:24<00:06, 54.19it/s, loss=1.53]
SASRec epoch 1/8:  75%|███████▌  | 1131/1500 [00:24<00:06, 52.72it/s, loss=1.53]
SASRec epoch 1/8:  76%|███████▌  | 1137/1500 [00:24<00:06, 53.71it/s, loss=1.53]
SASRec epoch 1/8:  76%|███████▌  | 1143/1500 [00:24<00:06, 54.21it/s, loss=1.53]
SASRec epoch 1/8:  77%|███████▋  | 1149/1500 [00:24<00:06, 54.63it/s, loss=1.53]
SASRec epoch 1/8:  77%|███████▋  | 1150/1500 [00:24<00:06, 54.63it/s, loss=1.52]
SASRec epoch 1/8:  77%|███████▋  | 1155/1500 [00:24<00:06, 53.71it/s, loss=1.52]
SASRec epoch 1/8:  77%|███████▋  | 1161/1500 [00:24<00:06, 53.51it/s, loss=1.52]
SASRec epoch 1/8:  78%|███████▊  | 1167/1500 [00:24<00:06, 53.63it/s, loss=1.52]
SASRec epoch 1/8:  78%|███████▊  | 1173/1500 [00:25<00:06, 54.25it/s, loss=1.52]
SASRec epoch 1/8:  79%|███████▊  | 1179/1500 [00:25<00:05, 54.03it/s, loss=1.52]
SASRec epoch 1/8:  79%|███████▉  | 1185/1500 [00:25<00:05, 52.83it/s, loss=1.52]
SASRec epoch 1/8:  79%|███████▉  | 1191/1500 [00:25<00:05, 53.68it/s, loss=1.52]
SASRec epoch 1/8:  80%|███████▉  | 1197/1500 [00:25<00:05, 54.34it/s, loss=1.52]
SASRec epoch 1/8:  80%|████████  | 1200/1500 [00:25<00:05, 54.34it/s, loss=1.49]
SASRec epoch 1/8:  80%|████████  | 1203/1500 [00:25<00:05, 53.47it/s, loss=1.49]
SASRec epoch 1/8:  81%|████████  | 1209/1500 [00:25<00:05, 54.13it/s, loss=1.49]
SASRec epoch 1/8:  81%|████████  | 1215/1500 [00:25<00:05, 54.28it/s, loss=1.49]
SASRec epoch 1/8:  81%|████████▏ | 1221/1500 [00:25<00:05, 54.40it/s, loss=1.49]
SASRec epoch 1/8:  82%|████████▏ | 1227/1500 [00:26<00:04, 54.84it/s, loss=1.49]
SASRec epoch 1/8:  82%|████████▏ | 1233/1500 [00:26<00:04, 54.97it/s, loss=1.49]
SASRec epoch 1/8:  83%|████████▎ | 1239/1500 [00:26<00:04, 55.35it/s, loss=1.49]
SASRec epoch 1/8:  83%|████████▎ | 1245/1500 [00:26<00:04, 53.11it/s, loss=1.49]
SASRec epoch 1/8:  83%|████████▎ | 1250/1500 [00:26<00:04, 53.11it/s, loss=1.48]
SASRec epoch 1/8:  83%|████████▎ | 1251/1500 [00:26<00:04, 52.23it/s, loss=1.48]
SASRec epoch 1/8:  84%|████████▍ | 1257/1500 [00:26<00:04, 53.34it/s, loss=1.48]
SASRec epoch 1/8:  84%|████████▍ | 1263/1500 [00:26<00:04, 54.32it/s, loss=1.48]
SASRec epoch 1/8:  85%|████████▍ | 1269/1500 [00:26<00:04, 54.23it/s, loss=1.48]
SASRec epoch 1/8:  85%|████████▌ | 1275/1500 [00:26<00:04, 50.66it/s, loss=1.48]

[SASRec] epoch 1/8 loss=2.1054

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 2/8:   0%|          | 6/1500 [00:00<00:28, 52.88it/s]
SASRec epoch 2/8:   1%|          | 12/1500 [00:00<00:27, 54.32it/s]
SASRec epoch 2/8:   1%|          | 18/1500 [00:00<00:26, 55.12it/s]
SASRec epoch 2/8:   2%|▏         | 24/1500 [00:00<00:26, 55.12it/s]
SASRec epoch 2/8:   2%|▏         | 30/1500 [00:00<00:26, 55.64it/s]
SASRec epoch 2/8:   2%|▏         | 36/1500 [00:00<00:26, 54.24it/s]
SASRec epoch 2/8:   3%|▎         | 42/1500 [00:00<00:26, 54.54it/s]
SASRec epoch 2/8:   3%|▎         | 48/1500 [00:00<00:26, 55.08it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:00<00:26, 55.08it/s, loss=1.42]
SASRec epoch 2/8:   4%|▎         | 54/1500 [00:00<00:27, 53.06it/s, loss=1.42]
SASRec epoch 2/8:   4%|▍         | 60/1500 [00:01<00:26, 53.85it/s, loss=1.42]
SASRec epoch 2/8:   4%|▍         | 66/1500 [00:01<00:26, 54.62it/s, loss=1.42]
SASRec epoch 2/8:   5%|▍         | 72/1500 [00:01<00:26, 54.72it/s, loss=1.42]
SASRec epoch 2/8:   5%|▌         | 78/1500 [00:01<00:25, 55.20it/s, loss=1.42]
SASRec epoch 2/8:   6%|▌         | 84/1500 [00:01<00:25, 55.09it/s, loss=1.42]
SASRec epoch 2/8:   6%|▌         | 90/1500 [00:01<00:26, 53.34it/s, loss=1.42]
SASRec epoch 2/8:   6%|▋         | 96/1500 [00:01<00:26, 53.94it/s, loss=1.42]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:01<00:25, 53.94it/s, loss=1.42]
SASRec epoch 2/8:   7%|▋         | 102/1500 [00:01<00:26, 52.78it/s, loss=1.42]
SASRec epoch 2/8:   7%|▋         | 108/1500 [00:01<00:26, 53.13it/s, loss=1.42]
SASRec epoch 2/8:   8%|▊         | 114/1500 [00:02<00:28, 48.71it/s, loss=1.42]
SASRec epoch 2/8:   8%|▊         | 120/1500 [00:02<00:27, 50.67it/s, loss=1.42]
SASRec epoch 2/8:   8%|▊         | 126/1500 [00:02<00:26, 52.07it/s, loss=1.42]
SASRec epoch 2/8:   9%|▉         | 132/1500 [00:02<00:25, 53.13it/s, loss=1.42]
SASRec epoch 2/8:   9%|▉         | 138/1500 [00:02<00:25, 53.54it/s, loss=1.42]
SASRec epoch 2/8:  10%|▉         | 144/1500 [00:02<00:25, 52.89it/s, loss=1.42]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:02<00:25, 53.56it/s, loss=1.42]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:02<00:25, 53.56it/s, loss=1.4]
SASRec epoch 2/8:  10%|█         | 156/1500 [00:02<00:25, 53.15it/s, loss=1.4]
SASRec epoch 2/8:  11%|█         | 162/1500 [00:03<00:24, 54.20it/s, loss=1.4]
SASRec epoch 2/8:  11%|█         | 168/1500 [00:03<00:24, 54.87it/s, loss=1.4]
SASRec epoch 2/8:  12%|█▏        | 174/1500 [00:03<00:24, 54.60it/s, loss=1.4]
SASRec epoch 2/8:  12%|█▏        | 180/1500 [00:03<00:24, 54.75it/s, loss=1.4]
SASRec epoch 2/8:  12%|█▏        | 186/1500 [00:03<00:23, 54.76it/s, loss=1.4]
SASRec epoch 2/8:  13%|█▎        | 192/1500 [00:03<00:23, 54.93it/s, loss=1.4]
SASRec epoch 2/8:  13%|█▎        | 198/1500 [00:03<00:23, 54.66it/s, loss=1.4]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:03<00:23, 54.66it/s, loss=1.39]
SASRec epoch 2/8:  14%|█▎        | 204/1500 [00:03<00:25, 51.45it/s, loss=1.39]
SASRec epoch 2/8:  14%|█▍        | 210/1500 [00:03<00:24, 52.53it/s, loss=1.39]
SASRec epoch 2/8:  14%|█▍        | 216/1500 [00:04<00:24, 53.06it/s, loss=1.39]
SASRec epoch 2/8:  15%|█▍        | 222/1500 [00:04<00:23, 53.76it/s, loss=1.39]
SASRec epoch 2/8:  15%|█▌        | 228/1500 [00:04<00:23, 54.47it/s, loss=1.39]
SASRec epoch 2/8:  16%|█▌        | 234/1500 [00:04<00:23, 54.75it/s, loss=1.39]
SASRec epoch 2/8:  16%|█▌        | 240/1500 [00:04<00:22, 55.04it/s, loss=1.39]
SASRec epoch 2/8:  16%|█▋        | 246/1500 [00:04<00:22, 55.39it/s, loss=1.39]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:04<00:22, 55.39it/s, loss=1.39]
SASRec epoch 2/8:  17%|█▋        | 252/1500 [00:04<00:23, 54.07it/s, loss=1.39]
SASRec epoch 2/8:  17%|█▋        | 258/1500 [00:04<00:23, 52.53it/s, loss=1.39]
SASRec epoch 2/8:  18%|█▊        | 264/1500 [00:04<00:23, 53.73it/s, loss=1.39]
SASRec epoch 2/8:  18%|█▊        | 270/1500 [00:05<00:22, 53.99it/s, loss=1.39]
SASRec epoch 2/8:  18%|█▊        | 276/1500 [00:05<00:22, 54.68it/s, loss=1.39]
SASRec epoch 2/8:  19%|█▉        | 282/1500 [00:05<00:22, 55.14it/s, loss=1.39]
SASRec epoch 2/8:  19%|█▉        | 288/1500 [00:05<00:21, 55.38it/s, loss=1.39]
SASRec epoch 2/8:  20%|█▉        | 294/1500 [00:05<00:21, 55.24it/s, loss=1.39]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:05<00:21, 55.20it/s, loss=1.39]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:05<00:21, 55.20it/s, loss=1.38]
SASRec epoch 2/8:  20%|██        | 306/1500 [00:05<00:22, 54.05it/s, loss=1.38]
SASRec epoch 2/8:  21%|██        | 312/1500 [00:05<00:22, 51.81it/s, loss=1.38]
SASRec epoch 2/8:  21%|██        | 318/1500 [00:05<00:22, 52.14it/s, loss=1.38]
SASRec epoch 2/8:  22%|██▏       | 324/1500 [00:06<00:22, 52.23it/s, loss=1.38]
SASRec epoch 2/8:  22%|██▏       | 330/1500 [00:06<00:22, 53.02it/s, loss=1.38]
SASRec epoch 2/8:  22%|██▏       | 336/1500 [00:06<00:21, 53.47it/s, loss=1.38]
SASRec epoch 2/8:  23%|██▎       | 342/1500 [00:06<00:21, 53.81it/s, loss=1.38]
SASRec epoch 2/8:  23%|██▎       | 348/1500 [00:06<00:21, 54.21it/s, loss=1.38]
SASRec epoch 2/8:  23%|██▎       | 350/1500 [00:06<00:21, 54.21it/s, loss=1.38]
SASRec epoch 2/8:  24%|██▎       | 354/1500 [00:06<00:21, 53.36it/s, loss=1.38]
SASRec epoch 2/8:  24%|██▍       | 360/1500 [00:06<00:21, 53.86it/s, loss=1.38]
SASRec epoch 2/8:  24%|██▍       | 366/1500 [00:06<00:21, 52.52it/s, loss=1.38]
SASRec epoch 2/8:  25%|██▍       | 372/1500 [00:06<00:22, 51.17it/s, loss=1.38]
SASRec epoch 2/8:  25%|██▌       | 378/1500 [00:07<00:21, 52.12it/s, loss=1.38]
SASRec epoch 2/8:  26%|██▌       | 384/1500 [00:07<00:21, 52.77it/s, loss=1.38]
SASRec epoch 2/8:  26%|██▌       | 390/1500 [00:07<00:20, 53.37it/s, loss=1.38]
SASRec epoch 2/8:  26%|██▋       | 396/1500 [00:07<00:20, 53.94it/s, loss=1.38]
SASRec epoch 2/8:  27%|██▋       | 400/1500 [00:07<00:20, 53.94it/s, loss=1.37]
SASRec epoch 2/8:  27%|██▋       | 402/1500 [00:07<00:20, 53.22it/s, loss=1.37]
SASRec epoch 2/8:  27%|██▋       | 408/1500 [00:07<00:20, 53.60it/s, loss=1.37]
SASRec epoch 2/8:  28%|██▊       | 414/1500 [00:07<00:19, 54.32it/s, loss=1.37]
SASRec epoch 2/8:  28%|██▊       | 420/1500 [00:07<00:19, 54.04it/s, loss=1.37]
SASRec epoch 2/8:  28%|██▊       | 426/1500 [00:07<00:20, 52.34it/s, loss=1.37]
SASRec epoch 2/8:  29%|██▉       | 432/1500 [00:08<00:20, 52.95it/s, loss=1.37]
SASRec epoch 2/8:  29%|██▉       | 438/1500 [00:08<00:20, 53.08it/s, loss=1.37]
SASRec epoch 2/8:  30%|██▉       | 444/1500 [00:08<00:19, 53.31it/s, loss=1.37]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:08<00:19, 53.56it/s, loss=1.37]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:08<00:19, 53.56it/s, loss=1.37]
SASRec epoch 2/8:  30%|███       | 456/1500 [00:08<00:19, 52.63it/s, loss=1.37]
SASRec epoch 2/8:  31%|███       | 462/1500 [00:08<00:21, 49.33it/s, loss=1.37]
SASRec epoch 2/8:  31%|███       | 467/1500 [00:08<00:22, 45.74it/s, loss=1.37]
SASRec epoch 2/8:  31%|███▏      | 472/1500 [00:08<00:23, 43.29it/s, loss=1.37]
SASRec epoch 2/8:  32%|███▏      | 477/1500 [00:09<00:24, 41.53it/s, loss=1.37]
SASRec epoch 2/8:  32%|███▏      | 482/1500 [00:09<00:24, 41.65it/s, loss=1.37]
SASRec epoch 2/8:  32%|███▏      | 487/1500 [00:09<00:24, 41.47it/s, loss=1.37]
SASRec epoch 2/8:  33%|███▎      | 492/1500 [00:09<00:24, 41.46it/s, loss=1.37]
SASRec epoch 2/8:  33%|███▎      | 497/1500 [00:09<00:24, 40.94it/s, loss=1.37]
SASRec epoch 2/8:  33%|███▎      | 500/1500 [00:09<00:24, 40.94it/s, loss=1.36]
SASRec epoch 2/8:  33%|███▎      | 502/1500 [00:09<00:24, 39.97it/s, loss=1.36]
SASRec epoch 2/8:  34%|███▍      | 507/1500 [00:09<00:24, 40.77it/s, loss=1.36]
SASRec epoch 2/8:  34%|███▍      | 512/1500 [00:09<00:23, 41.24it/s, loss=1.36]
SASRec epoch 2/8:  34%|███▍      | 517/1500 [00:10<00:24, 40.51it/s, loss=1.36]
SASRec epoch 2/8:  35%|███▍      | 522/1500 [00:10<00:23, 40.80it/s, loss=1.36]
SASRec epoch 2/8:  35%|███▌      | 527/1500 [00:10<00:24, 39.57it/s, loss=1.36]
SASRec epoch 2/8:  35%|███▌      | 532/1500 [00:10<00:23, 40.51it/s, loss=1.36]
SASRec epoch 2/8:  36%|███▌      | 537/1500 [00:10<00:23, 41.41it/s, loss=1.36]
SASRec epoch 2/8:  36%|███▌      | 542/1500 [00:10<00:22, 42.12it/s, loss=1.36]
SASRec epoch 2/8:  36%|███▋      | 547/1500 [00:10<00:22, 41.77it/s, loss=1.36]
SASRec epoch 2/8:  37%|███▋      | 550/1500 [00:10<00:22, 41.77it/s, loss=1.35]
SASRec epoch 2/8:  37%|███▋      | 552/1500 [00:10<00:22, 41.42it/s, loss=1.35]
SASRec epoch 2/8:  37%|███▋      | 557/1500 [00:10<00:22, 41.52it/s, loss=1.35]
SASRec epoch 2/8:  37%|███▋      | 562/1500 [00:11<00:22, 42.30it/s, loss=1.35]
SASRec epoch 2/8:  38%|███▊      | 567/1500 [00:11<00:22, 41.31it/s, loss=1.35]
SASRec epoch 2/8:  38%|███▊      | 572/1500 [00:11<00:22, 40.38it/s, loss=1.35]
SASRec epoch 2/8:  38%|███▊      | 577/1500 [00:11<00:22, 40.53it/s, loss=1.35]
SASRec epoch 2/8:  39%|███▉      | 582/1500 [00:11<00:23, 39.81it/s, loss=1.35]
SASRec epoch 2/8:  39%|███▉      | 586/1500 [00:11<00:23, 39.60it/s, loss=1.35]
SASRec epoch 2/8:  39%|███▉      | 591/1500 [00:11<00:22, 40.72it/s, loss=1.35]
SASRec epoch 2/8:  40%|███▉      | 596/1500 [00:11<00:23, 39.25it/s, loss=1.35]
SASRec epoch 2/8:  40%|████      | 600/1500 [00:12<00:22, 39.29it/s, loss=1.35]
SASRec epoch 2/8:  40%|████      | 600/1500 [00:12<00:22, 39.29it/s, loss=1.36]
SASRec epoch 2/8:  40%|████      | 604/1500 [00:12<00:23, 38.06it/s, loss=1.36]
SASRec epoch 2/8:  41%|████      | 608/1500 [00:12<00:24, 36.74it/s, loss=1.36]
SASRec epoch 2/8:  41%|████      | 613/1500 [00:12<00:22, 38.92it/s, loss=1.36]
SASRec epoch 2/8:  41%|████▏     | 619/1500 [00:12<00:20, 43.58it/s, loss=1.36]
SASRec epoch 2/8:  42%|████▏     | 625/1500 [00:12<00:18, 46.82it/s, loss=1.36]
SASRec epoch 2/8:  42%|████▏     | 630/1500 [00:12<00:18, 47.66it/s, loss=1.36]
SASRec epoch 2/8:  42%|████▏     | 636/1500 [00:12<00:17, 49.10it/s, loss=1.36]
SASRec epoch 2/8:  43%|████▎     | 642/1500 [00:12<00:17, 50.08it/s, loss=1.36]
SASRec epoch 2/8:  43%|████▎     | 648/1500 [00:13<00:16, 51.41it/s, loss=1.36]
SASRec epoch 2/8:  43%|████▎     | 650/1500 [00:13<00:16, 51.41it/s, loss=1.35]
SASRec epoch 2/8:  44%|████▎     | 654/1500 [00:13<00:16, 50.96it/s, loss=1.35]
SASRec epoch 2/8:  44%|████▍     | 660/1500 [00:13<00:16, 50.54it/s, loss=1.35]
SASRec epoch 2/8:  44%|████▍     | 666/1500 [00:13<00:16, 51.71it/s, loss=1.35]
SASRec epoch 2/8:  45%|████▍     | 672/1500 [00:13<00:15, 52.77it/s, loss=1.35]
SASRec epoch 2/8:  45%|████▌     | 678/1500 [00:13<00:15, 53.66it/s, loss=1.35]
SASRec epoch 2/8:  46%|████▌     | 684/1500 [00:13<00:14, 54.42it/s, loss=1.35]
SASRec epoch 2/8:  46%|████▌     | 690/1500 [00:13<00:14, 54.22it/s, loss=1.35]
SASRec epoch 2/8:  46%|████▋     | 696/1500 [00:13<00:14, 54.74it/s, loss=1.35]
SASRec epoch 2/8:  47%|████▋     | 700/1500 [00:14<00:14, 54.74it/s, loss=1.34]
SASRec epoch 2/8:  47%|████▋     | 702/1500 [00:14<00:14, 53.78it/s, loss=1.34]
SASRec epoch 2/8:  47%|████▋     | 708/1500 [00:14<00:14, 54.58it/s, loss=1.34]
SASRec epoch 2/8:  48%|████▊     | 714/1500 [00:14<00:14, 54.28it/s, loss=1.34]
SASRec epoch 2/8:  48%|████▊     | 720/1500 [00:14<00:14, 52.76it/s, loss=1.34]
SASRec epoch 2/8:  48%|████▊     | 726/1500 [00:14<00:14, 53.65it/s, loss=1.34]
SASRec epoch 2/8:  49%|████▉     | 732/1500 [00:14<00:14, 53.86it/s, loss=1.34]
SASRec epoch 2/8:  49%|████▉     | 738/1500 [00:14<00:14, 54.27it/s, loss=1.34]
SASRec epoch 2/8:  50%|████▉     | 744/1500 [00:14<00:13, 54.27it/s, loss=1.34]
SASRec epoch 2/8:  50%|█████     | 750/1500 [00:14<00:14, 53.56it/s, loss=1.34]
SASRec epoch 2/8:  50%|█████     | 750/1500 [00:14<00:14, 53.56it/s, loss=1.34]
SASRec epoch 2/8:  50%|█████     | 756/1500 [00:15<00:14, 52.70it/s, loss=1.34]
SASRec epoch 2/8:  51%|█████     | 762/1500 [00:15<00:14, 52.21it/s, loss=1.34]
SASRec epoch 2/8:  51%|█████     | 768/1500 [00:15<00:13, 52.98it/s, loss=1.34]
SASRec epoch 2/8:  52%|█████▏    | 774/1500 [00:15<00:14, 51.15it/s, loss=1.34]
SASRec epoch 2/8:  52%|█████▏    | 780/1500 [00:15<00:13, 52.05it/s, loss=1.34]
SASRec epoch 2/8:  52%|█████▏    | 786/1500 [00:15<00:13, 52.65it/s, loss=1.34]
SASRec epoch 2/8:  53%|█████▎    | 792/1500 [00:15<00:13, 52.96it/s, loss=1.34]
SASRec epoch 2/8:  53%|█████▎    | 798/1500 [00:15<00:13, 53.65it/s, loss=1.34]
SASRec epoch 2/8:  53%|█████▎    | 800/1500 [00:15<00:13, 53.65it/s, loss=1.33]
SASRec epoch 2/8:  54%|█████▎    | 804/1500 [00:16<00:13, 52.30it/s, loss=1.33]
SASRec epoch 2/8:  54%|█████▍    | 810/1500 [00:16<00:13, 52.79it/s, loss=1.33]
SASRec epoch 2/8:  54%|█████▍    | 816/1500 [00:16<00:12, 52.84it/s, loss=1.33]
SASRec epoch 2/8:  55%|█████▍    | 822/1500 [00:16<00:12, 53.35it/s, loss=1.33]
SASRec epoch 2/8:  55%|█████▌    | 828/1500 [00:16<00:13, 51.64it/s, loss=1.33]
SASRec epoch 2/8:  56%|█████▌    | 834/1500 [00:16<00:12, 52.67it/s, loss=1.33]
SASRec epoch 2/8:  56%|█████▌    | 840/1500 [00:16<00:12, 53.31it/s, loss=1.33]
SASRec epoch 2/8:  56%|█████▋    | 846/1500 [00:16<00:12, 53.43it/s, loss=1.33]
SASRec epoch 2/8:  57%|█████▋    | 850/1500 [00:16<00:12, 53.43it/s, loss=1.32]
SASRec epoch 2/8:  57%|█████▋    | 852/1500 [00:16<00:12, 52.58it/s, loss=1.32]
SASRec epoch 2/8:  57%|█████▋    | 858/1500 [00:17<00:12, 53.28it/s, loss=1.32]
SASRec epoch 2/8:  58%|█████▊    | 864/1500 [00:17<00:11, 53.85it/s, loss=1.32]
SASRec epoch 2/8:  58%|█████▊    | 870/1500 [00:17<00:11, 53.86it/s, loss=1.32]
SASRec epoch 2/8:  58%|█████▊    | 876/1500 [00:17<00:11, 54.35it/s, loss=1.32]
SASRec epoch 2/8:  59%|█████▉    | 882/1500 [00:17<00:11, 52.58it/s, loss=1.32]
SASRec epoch 2/8:  59%|█████▉    | 888/1500 [00:17<00:11, 53.02it/s, loss=1.32]
SASRec epoch 2/8:  60%|█████▉    | 894/1500 [00:17<00:11, 53.84it/s, loss=1.32]
SASRec epoch 2/8:  60%|██████    | 900/1500 [00:17<00:11, 53.94it/s, loss=1.32]
SASRec epoch 2/8:  60%|██████    | 900/1500 [00:17<00:11, 53.94it/s, loss=1.32]
SASRec epoch 2/8:  60%|██████    | 906/1500 [00:17<00:11, 53.32it/s, loss=1.32]
SASRec epoch 2/8:  61%|██████    | 912/1500 [00:18<00:10, 54.02it/s, loss=1.32]
SASRec epoch 2/8:  61%|██████    | 918/1500 [00:18<00:10, 54.33it/s, loss=1.32]
SASRec epoch 2/8:  62%|██████▏   | 924/1500 [00:18<00:10, 54.30it/s, loss=1.32]
SASRec epoch 2/8:  62%|██████▏   | 930/1500 [00:18<00:10, 54.66it/s, loss=1.32]
SASRec epoch 2/8:  62%|██████▏   | 936/1500 [00:18<00:10, 53.70it/s, loss=1.32]
SASRec epoch 2/8:  63%|██████▎   | 942/1500 [00:18<00:10, 52.78it/s, loss=1.32]
SASRec epoch 2/8:  63%|██████▎   | 948/1500 [00:18<00:10, 53.06it/s, loss=1.32]
SASRec epoch 2/8:  63%|██████▎   | 950/1500 [00:18<00:10, 53.06it/s, loss=1.3]
SASRec epoch 2/8:  64%|██████▎   | 954/1500 [00:18<00:10, 51.87it/s, loss=1.3]
SASRec epoch 2/8:  64%|██████▍   | 960/1500 [00:18<00:10, 52.41it/s, loss=1.3]
SASRec epoch 2/8:  64%|██████▍   | 966/1500 [00:19<00:10, 52.33it/s, loss=1.3]
SASRec epoch 2/8:  65%|██████▍   | 972/1500 [00:19<00:09, 52.83it/s, loss=1.3]
SASRec epoch 2/8:  65%|██████▌   | 978/1500 [00:19<00:09, 53.48it/s, loss=1.3]
SASRec epoch 2/8:  66%|██████▌   | 984/1500 [00:19<00:09, 53.63it/s, loss=1.3]
SASRec epoch 2/8:  66%|██████▌   | 990/1500 [00:19<00:09, 53.55it/s, loss=1.3]
SASRec epoch 2/8:  66%|██████▋   | 996/1500 [00:19<00:09, 52.16it/s, loss=1.3]
SASRec epoch 2/8:  67%|██████▋   | 1000/1500 [00:19<00:09, 52.16it/s, loss=1.31]
SASRec epoch 2/8:  67%|██████▋   | 1002/1500 [00:19<00:09, 51.66it/s, loss=1.31]
SASRec epoch 2/8:  67%|██████▋   | 1008/1500 [00:19<00:09, 52.14it/s, loss=1.31]
SASRec epoch 2/8:  68%|██████▊   | 1014/1500 [00:19<00:09, 51.79it/s, loss=1.31]
SASRec epoch 2/8:  68%|██████▊   | 1020/1500 [00:20<00:09, 52.21it/s, loss=1.31]
SASRec epoch 2/8:  68%|██████▊   | 1026/1500 [00:20<00:08, 52.77it/s, loss=1.31]
SASRec epoch 2/8:  69%|██████▉   | 1032/1500 [00:20<00:08, 52.67it/s, loss=1.31]
SASRec epoch 2/8:  69%|██████▉   | 1038/1500 [00:20<00:08, 53.19it/s, loss=1.31]
SASRec epoch 2/8:  70%|██████▉   | 1044/1500 [00:20<00:08, 53.70it/s, loss=1.31]
SASRec epoch 2/8:  70%|███████   | 1050/1500 [00:20<00:08, 51.73it/s, loss=1.31]
SASRec epoch 2/8:  70%|███████   | 1050/1500 [00:20<00:08, 51.73it/s, loss=1.32]
SASRec epoch 2/8:  70%|███████   | 1056/1500 [00:20<00:08, 51.77it/s, loss=1.32]
SASRec epoch 2/8:  71%|███████   | 1062/1500 [00:20<00:08, 52.76it/s, loss=1.32]
SASRec epoch 2/8:  71%|███████   | 1068/1500 [00:20<00:08, 52.79it/s, loss=1.32]
SASRec epoch 2/8:  72%|███████▏  | 1074/1500 [00:21<00:08, 52.73it/s, loss=1.32]
SASRec epoch 2/8:  72%|███████▏  | 1080/1500 [00:21<00:07, 53.20it/s, loss=1.32]
SASRec epoch 2/8:  72%|███████▏  | 1086/1500 [00:21<00:07, 53.78it/s, loss=1.32]
SASRec epoch 2/8:  73%|███████▎  | 1092/1500 [00:21<00:07, 53.86it/s, loss=1.32]
SASRec epoch 2/8:  73%|███████▎  | 1098/1500 [00:21<00:07, 54.10it/s, loss=1.32]
SASRec epoch 2/8:  73%|███████▎  | 1100/1500 [00:21<00:07, 54.10it/s, loss=1.29]
SASRec epoch 2/8:  74%|███████▎  | 1104/1500 [00:21<00:07, 50.49it/s, loss=1.29]
SASRec epoch 2/8:  74%|███████▍  | 1110/1500 [00:21<00:07, 51.26it/s, loss=1.29]
SASRec epoch 2/8:  74%|███████▍  | 1116/1500 [00:21<00:07, 51.48it/s, loss=1.29]
SASRec epoch 2/8:  75%|███████▍  | 1122/1500 [00:22<00:07, 52.47it/s, loss=1.29]
SASRec epoch 2/8:  75%|███████▌  | 1128/1500 [00:22<00:06, 53.35it/s, loss=1.29]
SASRec epoch 2/8:  76%|███████▌  | 1134/1500 [00:22<00:06, 53.64it/s, loss=1.29]
SASRec epoch 2/8:  76%|███████▌  | 1140/1500 [00:22<00:06, 53.67it/s, loss=1.29]
SASRec epoch 2/8:  76%|███████▋  | 1146/1500 [00:22<00:07, 48.36it/s, loss=1.29]
SASRec epoch 2/8:  77%|███████▋  | 1150/1500 [00:22<00:07, 48.36it/s, loss=1.31]
SASRec epoch 2/8:  77%|███████▋  | 1151/1500 [00:22<00:07, 44.06it/s, loss=1.31]
SASRec epoch 2/8:  77%|███████▋  | 1156/1500 [00:22<00:08, 42.62it/s, loss=1.31]
SASRec epoch 2/8:  77%|███████▋  | 1161/1500 [00:22<00:07, 42.66it/s, loss=1.31]
SASRec epoch 2/8:  78%|███████▊  | 1166/1500 [00:23<00:07, 43.00it/s, loss=1.31]
SASRec epoch 2/8:  78%|███████▊  | 1171/1500 [00:23<00:07, 42.51it/s, loss=1.31]
SASRec epoch 2/8:  78%|███████▊  | 1176/1500 [00:23<00:07, 42.16it/s, loss=1.31]
SASRec epoch 2/8:  79%|███████▊  | 1181/1500 [00:23<00:07, 42.33it/s, loss=1.31]
SASRec epoch 2/8:  79%|███████▉  | 1186/1500 [00:23<00:07, 41.76it/s, loss=1.31]
SASRec epoch 2/8:  79%|███████▉  | 1191/1500 [00:23<00:07, 42.05it/s, loss=1.31]
SASRec epoch 2/8:  80%|███████▉  | 1196/1500 [00:23<00:07, 42.60it/s, loss=1.31]
SASRec epoch 2/8:  80%|████████  | 1200/1500 [00:23<00:07, 42.60it/s, loss=1.3]
SASRec epoch 2/8:  80%|████████  | 1201/1500 [00:23<00:07, 41.36it/s, loss=1.3]
SASRec epoch 2/8:  80%|████████  | 1206/1500 [00:23<00:06, 42.31it/s, loss=1.3]
SASRec epoch 2/8:  81%|████████  | 1211/1500 [00:24<00:06, 43.26it/s, loss=1.3]
SASRec epoch 2/8:  81%|████████  | 1216/1500 [00:24<00:06, 42.91it/s, loss=1.3]
SASRec epoch 2/8:  81%|████████▏ | 1221/1500 [00:24<00:06, 43.80it/s, loss=1.3]
SASRec epoch 2/8:  82%|████████▏ | 1226/1500 [00:24<00:06, 44.05it/s, loss=1.3]
SASRec epoch 2/8:  82%|████████▏ | 1231/1500 [00:24<00:06, 44.60it/s, loss=1.3]
SASRec epoch 2/8:  82%|████████▏ | 1236/1500 [00:24<00:05, 44.87it/s, loss=1.3]
SASRec epoch 2/8:  83%|████████▎ | 1241/1500 [00:24<00:05, 45.32it/s, loss=1.3]
SASRec epoch 2/8:  83%|████████▎ | 1246/1500 [00:24<00:05, 45.06it/s, loss=1.3]
SASRec epoch 2/8:  83%|████████▎ | 1250/1500 [00:24<00:05, 45.06it/s, loss=1.3]
SASRec epoch 2/8:  83%|████████▎ | 1251/1500 [00:24<00:05, 42.99it/s, loss=1.3]
SASRec epoch 2/8:  84%|████████▎ | 1256/1500 [00:25<00:05, 43.10it/s, loss=1.3]
SASRec epoch 2/8:  84%|████████▍ | 1261/1500 [00:25<00:05, 43.12it/s, loss=1.3]
SASRec epoch 2/8:  84%|████████▍ | 1266/1500 [00:25<00:05, 41.26it/s, loss=1.3]
SASRec epoch 2/8:  85%|████████▍ | 1271/1500 [00:25<00:05, 40.42it/s, loss=1.3]
SASRec epoch 2/8:  85%|████████▌ | 1276/1500 [00:25<00:05, 39.24it/s, loss=1.3]
SASRec epoch 2/8:  85%|████████▌ | 1280/1500 [00:25<00:05, 38.40it/s, loss=1.3]
SASRec epoch 2/8:  86%|████████▌ | 1284/1500 [00:25<00:05, 38.52it/s, loss=1.3]

[SASRec] epoch 2/8 loss=1.3376

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 3/8:   0%|          | 6/1500 [00:00<00:28, 51.78it/s]
SASRec epoch 3/8:   1%|          | 12/1500 [00:00<00:28, 52.74it/s]
SASRec epoch 3/8:   1%|          | 18/1500 [00:00<00:27, 53.01it/s]
SASRec epoch 3/8:   2%|▏         | 24/1500 [00:00<00:27, 54.15it/s]
SASRec epoch 3/8:   2%|▏         | 30/1500 [00:00<00:27, 53.63it/s]
SASRec epoch 3/8:   2%|▏         | 36/1500 [00:00<00:26, 54.33it/s]
SASRec epoch 3/8:   3%|▎         | 42/1500 [00:00<00:26, 54.58it/s]
SASRec epoch 3/8:   3%|▎         | 48/1500 [00:00<00:26, 54.73it/s]
SASRec epoch 3/8:   3%|▎         | 50/1500 [00:00<00:26, 54.73it/s, loss=1.28]
SASRec epoch 3/8:   4%|▎         | 54/1500 [00:01<00:27, 52.92it/s, loss=1.28]
SASRec epoch 3/8:   4%|▍         | 60/1500 [00:01<00:26, 53.40it/s, loss=1.28]
SASRec epoch 3/8:   4%|▍         | 66/1500 [00:01<00:27, 51.52it/s, loss=1.28]
SASRec epoch 3/8:   5%|▍         | 72/1500 [00:01<00:27, 52.21it/s, loss=1.28]
SASRec epoch 3/8:   5%|▌         | 78/1500 [00:01<00:26, 53.02it/s, loss=1.28]
SASRec epoch 3/8:   6%|▌         | 84/1500 [00:01<00:26, 53.28it/s, loss=1.28]
SASRec epoch 3/8:   6%|▌         | 90/1500 [00:01<00:26, 53.68it/s, loss=1.28]
SASRec epoch 3/8:   6%|▋         | 96/1500 [00:01<00:26, 53.93it/s, loss=1.28]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:01<00:25, 53.93it/s, loss=1.27]
SASRec epoch 3/8:   7%|▋         | 102/1500 [00:01<00:26, 52.72it/s, loss=1.27]
SASRec epoch 3/8:   7%|▋         | 108/1500 [00:02<00:26, 53.50it/s, loss=1.27]
SASRec epoch 3/8:   8%|▊         | 114/1500 [00:02<00:25, 53.99it/s, loss=1.27]
SASRec epoch 3/8:   8%|▊         | 120/1500 [00:02<00:29, 46.49it/s, loss=1.27]
SASRec epoch 3/8:   8%|▊         | 126/1500 [00:02<00:28, 48.17it/s, loss=1.27]
SASRec epoch 3/8:   9%|▉         | 132/1500 [00:02<00:27, 49.30it/s, loss=1.27]
SASRec epoch 3/8:   9%|▉         | 138/1500 [00:02<00:26, 50.67it/s, loss=1.27]
SASRec epoch 3/8:  10%|▉         | 144/1500 [00:02<00:26, 51.39it/s, loss=1.27]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:02<00:26, 51.04it/s, loss=1.27]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:02<00:26, 51.04it/s, loss=1.26]
SASRec epoch 3/8:  10%|█         | 156/1500 [00:02<00:26, 50.44it/s, loss=1.26]
SASRec epoch 3/8:  11%|█         | 162/1500 [00:03<00:25, 51.55it/s, loss=1.26]
SASRec epoch 3/8:  11%|█         | 168/1500 [00:03<00:25, 52.28it/s, loss=1.26]
SASRec epoch 3/8:  12%|█▏        | 174/1500 [00:03<00:26, 50.98it/s, loss=1.26]
SASRec epoch 3/8:  12%|█▏        | 180/1500 [00:03<00:25, 52.13it/s, loss=1.26]
SASRec epoch 3/8:  12%|█▏        | 186/1500 [00:03<00:25, 52.51it/s, loss=1.26]
SASRec epoch 3/8:  13%|█▎        | 192/1500 [00:03<00:24, 53.04it/s, loss=1.26]
SASRec epoch 3/8:  13%|█▎        | 198/1500 [00:03<00:24, 53.32it/s, loss=1.26]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:03<00:24, 53.32it/s, loss=1.26]
SASRec epoch 3/8:  14%|█▎        | 204/1500 [00:03<00:25, 51.59it/s, loss=1.26]
SASRec epoch 3/8:  14%|█▍        | 210/1500 [00:04<00:24, 52.15it/s, loss=1.26]
SASRec epoch 3/8:  14%|█▍        | 216/1500 [00:04<00:24, 52.27it/s, loss=1.26]
SASRec epoch 3/8:  15%|█▍        | 222/1500 [00:04<00:24, 52.55it/s, loss=1.26]
SASRec epoch 3/8:  15%|█▌        | 228/1500 [00:04<00:24, 50.89it/s, loss=1.26]
SASRec epoch 3/8:  16%|█▌        | 234/1500 [00:04<00:24, 51.90it/s, loss=1.26]
SASRec epoch 3/8:  16%|█▌        | 240/1500 [00:04<00:24, 52.18it/s, loss=1.26]
SASRec epoch 3/8:  16%|█▋        | 246/1500 [00:04<00:23, 52.58it/s, loss=1.26]
SASRec epoch 3/8:  17%|█▋        | 250/1500 [00:04<00:23, 52.58it/s, loss=1.26]
SASRec epoch 3/8:  17%|█▋        | 252/1500 [00:04<00:24, 50.48it/s, loss=1.26]
SASRec epoch 3/8:  17%|█▋        | 258/1500 [00:04<00:24, 51.07it/s, loss=1.26]
SASRec epoch 3/8:  18%|█▊        | 264/1500 [00:05<00:23, 51.57it/s, loss=1.26]
SASRec epoch 3/8:  18%|█▊        | 270/1500 [00:05<00:23, 51.70it/s, loss=1.26]
SASRec epoch 3/8:  18%|█▊        | 276/1500 [00:05<00:23, 52.20it/s, loss=1.26]
SASRec epoch 3/8:  19%|█▉        | 282/1500 [00:05<00:23, 51.06it/s, loss=1.26]
SASRec epoch 3/8:  19%|█▉        | 288/1500 [00:05<00:23, 51.82it/s, loss=1.26]
SASRec epoch 3/8:  20%|█▉        | 294/1500 [00:05<00:22, 52.46it/s, loss=1.26]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:05<00:22, 52.93it/s, loss=1.26]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:05<00:22, 52.93it/s, loss=1.26]
SASRec epoch 3/8:  20%|██        | 306/1500 [00:05<00:23, 51.42it/s, loss=1.26]
SASRec epoch 3/8:  21%|██        | 312/1500 [00:05<00:22, 52.06it/s, loss=1.26]
SASRec epoch 3/8:  21%|██        | 318/1500 [00:06<00:22, 52.74it/s, loss=1.26]
SASRec epoch 3/8:  22%|██▏       | 324/1500 [00:06<00:21, 53.48it/s, loss=1.26]
SASRec epoch 3/8:  22%|██▏       | 330/1500 [00:06<00:22, 50.97it/s, loss=1.26]
SASRec epoch 3/8:  22%|██▏       | 336/1500 [00:06<00:25, 45.52it/s, loss=1.26]
SASRec epoch 3/8:  23%|██▎       | 341/1500 [00:06<00:26, 44.44it/s, loss=1.26]
SASRec epoch 3/8:  23%|██▎       | 346/1500 [00:06<00:26, 43.70it/s, loss=1.26]
SASRec epoch 3/8:  23%|██▎       | 350/1500 [00:06<00:26, 43.70it/s, loss=1.26]
SASRec epoch 3/8:  23%|██▎       | 351/1500 [00:06<00:27, 42.25it/s, loss=1.26]
SASRec epoch 3/8:  24%|██▎       | 356/1500 [00:07<00:27, 41.58it/s, loss=1.26]
SASRec epoch 3/8:  24%|██▍       | 361/1500 [00:07<00:27, 41.63it/s, loss=1.26]
SASRec epoch 3/8:  24%|██▍       | 366/1500 [00:07<00:27, 41.89it/s, loss=1.26]
SASRec epoch 3/8:  25%|██▍       | 371/1500 [00:07<00:26, 42.00it/s, loss=1.26]
SASRec epoch 3/8:  25%|██▌       | 376/1500 [00:07<00:28, 39.02it/s, loss=1.26]
SASRec epoch 3/8:  25%|██▌       | 381/1500 [00:07<00:27, 40.24it/s, loss=1.26]
SASRec epoch 3/8:  26%|██▌       | 386/1500 [00:07<00:27, 40.31it/s, loss=1.26]
SASRec epoch 3/8:  26%|██▌       | 391/1500 [00:07<00:26, 41.14it/s, loss=1.26]
SASRec epoch 3/8:  26%|██▋       | 396/1500 [00:07<00:26, 41.64it/s, loss=1.26]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:08<00:26, 41.64it/s, loss=1.25]
SASRec epoch 3/8:  27%|██▋       | 401/1500 [00:08<00:27, 40.47it/s, loss=1.25]
SASRec epoch 3/8:  27%|██▋       | 406/1500 [00:08<00:26, 41.10it/s, loss=1.25]
SASRec epoch 3/8:  27%|██▋       | 411/1500 [00:08<00:25, 42.23it/s, loss=1.25]
SASRec epoch 3/8:  28%|██▊       | 416/1500 [00:08<00:25, 42.98it/s, loss=1.25]
SASRec epoch 3/8:  28%|██▊       | 421/1500 [00:08<00:26, 41.24it/s, loss=1.25]
SASRec epoch 3/8:  28%|██▊       | 426/1500 [00:08<00:25, 42.15it/s, loss=1.25]
SASRec epoch 3/8:  29%|██▊       | 431/1500 [00:08<00:24, 42.81it/s, loss=1.25]
SASRec epoch 3/8:  29%|██▉       | 436/1500 [00:08<00:24, 43.53it/s, loss=1.25]
SASRec epoch 3/8:  29%|██▉       | 441/1500 [00:09<00:24, 44.01it/s, loss=1.25]
SASRec epoch 3/8:  30%|██▉       | 446/1500 [00:09<00:25, 42.00it/s, loss=1.25]
SASRec epoch 3/8:  30%|███       | 450/1500 [00:09<00:24, 42.00it/s, loss=1.25]
SASRec epoch 3/8:  30%|███       | 451/1500 [00:09<00:26, 40.30it/s, loss=1.25]
SASRec epoch 3/8:  30%|███       | 456/1500 [00:09<00:26, 39.51it/s, loss=1.25]
SASRec epoch 3/8:  31%|███       | 460/1500 [00:09<00:27, 38.07it/s, loss=1.25]
SASRec epoch 3/8:  31%|███       | 464/1500 [00:09<00:27, 37.33it/s, loss=1.25]
SASRec epoch 3/8:  31%|███       | 468/1500 [00:09<00:28, 35.64it/s, loss=1.25]
SASRec epoch 3/8:  31%|███▏      | 472/1500 [00:09<00:29, 35.34it/s, loss=1.25]
SASRec epoch 3/8:  32%|███▏      | 476/1500 [00:10<00:28, 35.64it/s, loss=1.25]
SASRec epoch 3/8:  32%|███▏      | 480/1500 [00:10<00:28, 35.38it/s, loss=1.25]
SASRec epoch 3/8:  32%|███▏      | 484/1500 [00:10<00:28, 36.10it/s, loss=1.25]
SASRec epoch 3/8:  33%|███▎      | 490/1500 [00:10<00:24, 41.34it/s, loss=1.25]
SASRec epoch 3/8:  33%|███▎      | 496/1500 [00:10<00:22, 45.21it/s, loss=1.25]
SASRec epoch 3/8:  33%|███▎      | 500/1500 [00:10<00:22, 45.21it/s, loss=1.24]
SASRec epoch 3/8:  33%|███▎      | 501/1500 [00:10<00:21, 46.48it/s, loss=1.24]
SASRec epoch 3/8:  34%|███▍      | 507/1500 [00:10<00:20, 49.25it/s, loss=1.24]
SASRec epoch 3/8:  34%|███▍      | 512/1500 [00:10<00:20, 48.86it/s, loss=1.24]
SASRec epoch 3/8:  35%|███▍      | 518/1500 [00:10<00:19, 50.31it/s, loss=1.24]
SASRec epoch 3/8:  35%|███▍      | 524/1500 [00:10<00:18, 51.53it/s, loss=1.24]
SASRec epoch 3/8:  35%|███▌      | 530/1500 [00:11<00:18, 52.51it/s, loss=1.24]
SASRec epoch 3/8:  36%|███▌      | 536/1500 [00:11<00:18, 52.94it/s, loss=1.24]
SASRec epoch 3/8:  36%|███▌      | 542/1500 [00:11<00:17, 53.43it/s, loss=1.24]
SASRec epoch 3/8:  37%|███▋      | 548/1500 [00:11<00:17, 53.76it/s, loss=1.24]
SASRec epoch 3/8:  37%|███▋      | 550/1500 [00:11<00:17, 53.76it/s, loss=1.25]
SASRec epoch 3/8:  37%|███▋      | 554/1500 [00:11<00:18, 52.41it/s, loss=1.25]
SASRec epoch 3/8:  37%|███▋      | 560/1500 [00:11<00:17, 52.86it/s, loss=1.25]
SASRec epoch 3/8:  38%|███▊      | 566/1500 [00:11<00:17, 52.22it/s, loss=1.25]
SASRec epoch 3/8:  38%|███▊      | 572/1500 [00:11<00:17, 51.63it/s, loss=1.25]
SASRec epoch 3/8:  39%|███▊      | 578/1500 [00:12<00:17, 52.29it/s, loss=1.25]
SASRec epoch 3/8:  39%|███▉      | 584/1500 [00:12<00:17, 53.09it/s, loss=1.25]
SASRec epoch 3/8:  39%|███▉      | 590/1500 [00:12<00:16, 53.85it/s, loss=1.25]
SASRec epoch 3/8:  40%|███▉      | 596/1500 [00:12<00:16, 54.22it/s, loss=1.25]
SASRec epoch 3/8:  40%|████      | 600/1500 [00:12<00:16, 54.22it/s, loss=1.24]
SASRec epoch 3/8:  40%|████      | 602/1500 [00:12<00:16, 53.04it/s, loss=1.24]
SASRec epoch 3/8:  41%|████      | 608/1500 [00:12<00:16, 53.29it/s, loss=1.24]
SASRec epoch 3/8:  41%|████      | 614/1500 [00:12<00:16, 53.52it/s, loss=1.24]
SASRec epoch 3/8:  41%|████▏     | 620/1500 [00:12<00:16, 53.44it/s, loss=1.24]
SASRec epoch 3/8:  42%|████▏     | 626/1500 [00:12<00:17, 50.40it/s, loss=1.24]
SASRec epoch 3/8:  42%|████▏     | 632/1500 [00:13<00:16, 51.33it/s, loss=1.24]
SASRec epoch 3/8:  43%|████▎     | 638/1500 [00:13<00:16, 51.90it/s, loss=1.24]
SASRec epoch 3/8:  43%|████▎     | 644/1500 [00:13<00:16, 52.61it/s, loss=1.24]
SASRec epoch 3/8:  43%|████▎     | 650/1500 [00:13<00:16, 52.38it/s, loss=1.24]
SASRec epoch 3/8:  43%|████▎     | 650/1500 [00:13<00:16, 52.38it/s, loss=1.23]
SASRec epoch 3/8:  44%|████▎     | 656/1500 [00:13<00:16, 51.75it/s, loss=1.23]
SASRec epoch 3/8:  44%|████▍     | 662/1500 [00:13<00:16, 52.07it/s, loss=1.23]
SASRec epoch 3/8:  45%|████▍     | 668/1500 [00:13<00:15, 52.07it/s, loss=1.23]
SASRec epoch 3/8:  45%|████▍     | 674/1500 [00:13<00:16, 51.61it/s, loss=1.23]
SASRec epoch 3/8:  45%|████▌     | 680/1500 [00:13<00:16, 49.92it/s, loss=1.23]
SASRec epoch 3/8:  46%|████▌     | 686/1500 [00:14<00:16, 50.58it/s, loss=1.23]
SASRec epoch 3/8:  46%|████▌     | 692/1500 [00:14<00:15, 51.50it/s, loss=1.23]
SASRec epoch 3/8:  47%|████▋     | 698/1500 [00:14<00:15, 51.73it/s, loss=1.23]
SASRec epoch 3/8:  47%|████▋     | 700/1500 [00:14<00:15, 51.73it/s, loss=1.22]
SASRec epoch 3/8:  47%|████▋     | 704/1500 [00:14<00:15, 50.94it/s, loss=1.22]
SASRec epoch 3/8:  47%|████▋     | 710/1500 [00:14<00:15, 51.77it/s, loss=1.22]
SASRec epoch 3/8:  48%|████▊     | 716/1500 [00:14<00:15, 51.81it/s, loss=1.22]
SASRec epoch 3/8:  48%|████▊     | 722/1500 [00:14<00:14, 52.29it/s, loss=1.22]
SASRec epoch 3/8:  49%|████▊     | 728/1500 [00:14<00:14, 52.54it/s, loss=1.22]
SASRec epoch 3/8:  49%|████▉     | 734/1500 [00:15<00:15, 50.36it/s, loss=1.22]
SASRec epoch 3/8:  49%|████▉     | 740/1500 [00:15<00:14, 51.18it/s, loss=1.22]
SASRec epoch 3/8:  50%|████▉     | 746/1500 [00:15<00:14, 52.24it/s, loss=1.22]
SASRec epoch 3/8:  50%|█████     | 750/1500 [00:15<00:14, 52.24it/s, loss=1.23]
SASRec epoch 3/8:  50%|█████     | 752/1500 [00:15<00:14, 51.71it/s, loss=1.23]
SASRec epoch 3/8:  51%|█████     | 758/1500 [00:15<00:14, 52.64it/s, loss=1.23]
SASRec epoch 3/8:  51%|█████     | 764/1500 [00:15<00:13, 53.08it/s, loss=1.23]
SASRec epoch 3/8:  51%|█████▏    | 770/1500 [00:15<00:13, 52.72it/s, loss=1.23]
SASRec epoch 3/8:  52%|█████▏    | 776/1500 [00:15<00:13, 52.70it/s, loss=1.23]
SASRec epoch 3/8:  52%|█████▏    | 782/1500 [00:15<00:13, 52.08it/s, loss=1.23]
SASRec epoch 3/8:  53%|█████▎    | 788/1500 [00:16<00:14, 50.07it/s, loss=1.23]
SASRec epoch 3/8:  53%|█████▎    | 794/1500 [00:16<00:13, 50.78it/s, loss=1.23]
SASRec epoch 3/8:  53%|█████▎    | 800/1500 [00:16<00:13, 51.64it/s, loss=1.23]
SASRec epoch 3/8:  53%|█████▎    | 800/1500 [00:16<00:13, 51.64it/s, loss=1.23]
SASRec epoch 3/8:  54%|█████▎    | 806/1500 [00:16<00:13, 51.09it/s, loss=1.23]
SASRec epoch 3/8:  54%|█████▍    | 812/1500 [00:16<00:13, 51.93it/s, loss=1.23]
SASRec epoch 3/8:  55%|█████▍    | 818/1500 [00:16<00:13, 52.32it/s, loss=1.23]
SASRec epoch 3/8:  55%|█████▍    | 824/1500 [00:16<00:12, 53.07it/s, loss=1.23]
SASRec epoch 3/8:  55%|█████▌    | 830/1500 [00:16<00:12, 52.70it/s, loss=1.23]
SASRec epoch 3/8:  56%|█████▌    | 836/1500 [00:16<00:12, 53.11it/s, loss=1.23]
SASRec epoch 3/8:  56%|█████▌    | 842/1500 [00:17<00:12, 51.09it/s, loss=1.23]
SASRec epoch 3/8:  57%|█████▋    | 848/1500 [00:17<00:12, 51.86it/s, loss=1.23]
SASRec epoch 3/8:  57%|█████▋    | 850/1500 [00:17<00:12, 51.86it/s, loss=1.23]
SASRec epoch 3/8:  57%|█████▋    | 854/1500 [00:17<00:12, 51.07it/s, loss=1.23]
SASRec epoch 3/8:  57%|█████▋    | 860/1500 [00:17<00:12, 52.04it/s, loss=1.23]
SASRec epoch 3/8:  58%|█████▊    | 866/1500 [00:17<00:12, 52.83it/s, loss=1.23]
SASRec epoch 3/8:  58%|█████▊    | 872/1500 [00:17<00:11, 53.07it/s, loss=1.23]
SASRec epoch 3/8:  59%|█████▊    | 878/1500 [00:17<00:11, 53.29it/s, loss=1.23]
SASRec epoch 3/8:  59%|█████▉    | 884/1500 [00:17<00:11, 52.72it/s, loss=1.23]
SASRec epoch 3/8:  59%|█████▉    | 890/1500 [00:17<00:11, 52.77it/s, loss=1.23]
SASRec epoch 3/8:  60%|█████▉    | 896/1500 [00:18<00:11, 51.28it/s, loss=1.23]
SASRec epoch 3/8:  60%|██████    | 900/1500 [00:18<00:11, 51.28it/s, loss=1.24]
SASRec epoch 3/8:  60%|██████    | 902/1500 [00:18<00:11, 51.04it/s, loss=1.24]
SASRec epoch 3/8:  61%|██████    | 908/1500 [00:18<00:11, 51.64it/s, loss=1.24]
SASRec epoch 3/8:  61%|██████    | 914/1500 [00:18<00:11, 52.00it/s, loss=1.24]
SASRec epoch 3/8:  61%|██████▏   | 920/1500 [00:18<00:11, 52.35it/s, loss=1.24]
SASRec epoch 3/8:  62%|██████▏   | 926/1500 [00:18<00:10, 52.70it/s, loss=1.24]
SASRec epoch 3/8:  62%|██████▏   | 932/1500 [00:18<00:10, 53.34it/s, loss=1.24]
SASRec epoch 3/8:  63%|██████▎   | 938/1500 [00:18<00:10, 52.78it/s, loss=1.24]
SASRec epoch 3/8:  63%|██████▎   | 944/1500 [00:19<00:10, 53.04it/s, loss=1.24]
SASRec epoch 3/8:  63%|██████▎   | 950/1500 [00:19<00:10, 51.16it/s, loss=1.24]
SASRec epoch 3/8:  63%|██████▎   | 950/1500 [00:19<00:10, 51.16it/s, loss=1.22]
SASRec epoch 3/8:  64%|██████▎   | 956/1500 [00:19<00:10, 51.44it/s, loss=1.22]
SASRec epoch 3/8:  64%|██████▍   | 962/1500 [00:19<00:10, 52.16it/s, loss=1.22]
SASRec epoch 3/8:  65%|██████▍   | 968/1500 [00:19<00:10, 53.03it/s, loss=1.22]
SASRec epoch 3/8:  65%|██████▍   | 974/1500 [00:19<00:09, 53.35it/s, loss=1.22]
SASRec epoch 3/8:  65%|██████▌   | 980/1500 [00:19<00:09, 53.70it/s, loss=1.22]
SASRec epoch 3/8:  66%|██████▌   | 986/1500 [00:19<00:09, 54.00it/s, loss=1.22]
SASRec epoch 3/8:  66%|██████▌   | 992/1500 [00:19<00:09, 53.39it/s, loss=1.22]
SASRec epoch 3/8:  67%|██████▋   | 998/1500 [00:20<00:09, 53.39it/s, loss=1.22]
SASRec epoch 3/8:  67%|██████▋   | 1000/1500 [00:20<00:09, 53.39it/s, loss=1.21]
SASRec epoch 3/8:  67%|██████▋   | 1004/1500 [00:20<00:09, 50.81it/s, loss=1.21]
SASRec epoch 3/8:  67%|██████▋   | 1010/1500 [00:20<00:10, 47.70it/s, loss=1.21]
SASRec epoch 3/8:  68%|██████▊   | 1015/1500 [00:20<00:10, 46.34it/s, loss=1.21]
SASRec epoch 3/8:  68%|██████▊   | 1020/1500 [00:20<00:10, 45.78it/s, loss=1.21]
SASRec epoch 3/8:  68%|██████▊   | 1025/1500 [00:20<00:10, 45.51it/s, loss=1.21]
SASRec epoch 3/8:  69%|██████▊   | 1030/1500 [00:20<00:10, 45.56it/s, loss=1.21]
SASRec epoch 3/8:  69%|██████▉   | 1035/1500 [00:20<00:10, 44.12it/s, loss=1.21]
SASRec epoch 3/8:  69%|██████▉   | 1040/1500 [00:21<00:10, 44.52it/s, loss=1.21]
SASRec epoch 3/8:  70%|██████▉   | 1045/1500 [00:21<00:10, 42.99it/s, loss=1.21]
SASRec epoch 3/8:  70%|███████   | 1050/1500 [00:21<00:10, 42.53it/s, loss=1.21]
SASRec epoch 3/8:  70%|███████   | 1050/1500 [00:21<00:10, 42.53it/s, loss=1.22]
SASRec epoch 3/8:  70%|███████   | 1055/1500 [00:21<00:10, 42.17it/s, loss=1.22]
SASRec epoch 3/8:  71%|███████   | 1060/1500 [00:21<00:10, 43.42it/s, loss=1.22]
SASRec epoch 3/8:  71%|███████   | 1065/1500 [00:21<00:09, 44.34it/s, loss=1.22]
SASRec epoch 3/8:  71%|███████▏  | 1070/1500 [00:21<00:09, 45.24it/s, loss=1.22]
SASRec epoch 3/8:  72%|███████▏  | 1075/1500 [00:21<00:09, 45.40it/s, loss=1.22]
SASRec epoch 3/8:  72%|███████▏  | 1080/1500 [00:21<00:09, 45.52it/s, loss=1.22]
SASRec epoch 3/8:  72%|███████▏  | 1085/1500 [00:22<00:09, 44.57it/s, loss=1.22]
SASRec epoch 3/8:  73%|███████▎  | 1090/1500 [00:22<00:09, 45.11it/s, loss=1.22]
SASRec epoch 3/8:  73%|███████▎  | 1095/1500 [00:22<00:09, 44.87it/s, loss=1.22]
SASRec epoch 3/8:  73%|███████▎  | 1100/1500 [00:22<00:09, 44.38it/s, loss=1.22]
SASRec epoch 3/8:  73%|███████▎  | 1100/1500 [00:22<00:09, 44.38it/s, loss=1.22]
SASRec epoch 3/8:  74%|███████▎  | 1105/1500 [00:22<00:08, 45.13it/s, loss=1.22]
SASRec epoch 3/8:  74%|███████▍  | 1110/1500 [00:22<00:08, 44.85it/s, loss=1.22]
SASRec epoch 3/8:  74%|███████▍  | 1115/1500 [00:22<00:08, 45.63it/s, loss=1.22]
SASRec epoch 3/8:  75%|███████▍  | 1120/1500 [00:22<00:08, 46.38it/s, loss=1.22]
SASRec epoch 3/8:  75%|███████▌  | 1125/1500 [00:22<00:08, 46.83it/s, loss=1.22]
SASRec epoch 3/8:  75%|███████▌  | 1130/1500 [00:23<00:08, 45.85it/s, loss=1.22]
SASRec epoch 3/8:  76%|███████▌  | 1135/1500 [00:23<00:08, 44.32it/s, loss=1.22]
SASRec epoch 3/8:  76%|███████▌  | 1140/1500 [00:23<00:08, 43.64it/s, loss=1.22]
SASRec epoch 3/8:  76%|███████▋  | 1145/1500 [00:23<00:08, 41.84it/s, loss=1.22]
SASRec epoch 3/8:  77%|███████▋  | 1150/1500 [00:23<00:08, 40.28it/s, loss=1.22]
SASRec epoch 3/8:  77%|███████▋  | 1150/1500 [00:23<00:08, 40.28it/s, loss=1.21]
SASRec epoch 3/8:  77%|███████▋  | 1155/1500 [00:23<00:08, 40.23it/s, loss=1.21]
SASRec epoch 3/8:  77%|███████▋  | 1160/1500 [00:23<00:08, 41.30it/s, loss=1.21]
SASRec epoch 3/8:  78%|███████▊  | 1165/1500 [00:23<00:08, 40.61it/s, loss=1.21]
SASRec epoch 3/8:  78%|███████▊  | 1170/1500 [00:24<00:08, 40.73it/s, loss=1.21]
SASRec epoch 3/8:  78%|███████▊  | 1175/1500 [00:24<00:08, 39.80it/s, loss=1.21]
SASRec epoch 3/8:  79%|███████▊  | 1180/1500 [00:24<00:07, 41.06it/s, loss=1.21]
SASRec epoch 3/8:  79%|███████▉  | 1186/1500 [00:24<00:06, 44.95it/s, loss=1.21]
SASRec epoch 3/8:  79%|███████▉  | 1192/1500 [00:24<00:06, 47.20it/s, loss=1.21]
SASRec epoch 3/8:  80%|███████▉  | 1198/1500 [00:24<00:06, 49.03it/s, loss=1.21]
SASRec epoch 3/8:  80%|████████  | 1200/1500 [00:24<00:06, 49.03it/s, loss=1.2]
SASRec epoch 3/8:  80%|████████  | 1203/1500 [00:24<00:06, 48.96it/s, loss=1.2]
SASRec epoch 3/8:  81%|████████  | 1209/1500 [00:24<00:05, 50.54it/s, loss=1.2]
SASRec epoch 3/8:  81%|████████  | 1215/1500 [00:24<00:05, 50.99it/s, loss=1.2]
SASRec epoch 3/8:  81%|████████▏ | 1221/1500 [00:25<00:05, 52.05it/s, loss=1.2]
SASRec epoch 3/8:  82%|████████▏ | 1227/1500 [00:25<00:05, 52.42it/s, loss=1.2]
SASRec epoch 3/8:  82%|████████▏ | 1233/1500 [00:25<00:05, 52.97it/s, loss=1.2]
SASRec epoch 3/8:  83%|████████▎ | 1239/1500 [00:25<00:04, 53.25it/s, loss=1.2]
SASRec epoch 3/8:  83%|████████▎ | 1245/1500 [00:25<00:04, 53.49it/s, loss=1.2]
SASRec epoch 3/8:  83%|████████▎ | 1250/1500 [00:25<00:04, 53.49it/s, loss=1.21]
SASRec epoch 3/8:  83%|████████▎ | 1251/1500 [00:25<00:04, 50.22it/s, loss=1.21]
SASRec epoch 3/8:  84%|████████▍ | 1257/1500 [00:25<00:04, 51.37it/s, loss=1.21]
SASRec epoch 3/8:  84%|████████▍ | 1263/1500 [00:25<00:04, 51.53it/s, loss=1.21]
SASRec epoch 3/8:  85%|████████▍ | 1269/1500 [00:25<00:04, 51.99it/s, loss=1.21]

[SASRec] epoch 3/8 loss=1.2306

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 4/8:   0%|          | 6/1500 [00:00<00:28, 53.21it/s]
SASRec epoch 4/8:   1%|          | 12/1500 [00:00<00:27, 54.81it/s]
SASRec epoch 4/8:   1%|          | 18/1500 [00:00<00:27, 54.04it/s]
SASRec epoch 4/8:   2%|▏         | 24/1500 [00:00<00:28, 52.31it/s]
SASRec epoch 4/8:   2%|▏         | 30/1500 [00:00<00:27, 53.03it/s]
SASRec epoch 4/8:   2%|▏         | 36/1500 [00:00<00:27, 53.51it/s]
SASRec epoch 4/8:   3%|▎         | 42/1500 [00:00<00:27, 53.55it/s]
SASRec epoch 4/8:   3%|▎         | 48/1500 [00:00<00:27, 53.21it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:00<00:27, 53.21it/s, loss=1.2]
SASRec epoch 4/8:   4%|▎         | 54/1500 [00:01<00:27, 52.27it/s, loss=1.2]
SASRec epoch 4/8:   4%|▍         | 60/1500 [00:01<00:27, 52.77it/s, loss=1.2]
SASRec epoch 4/8:   4%|▍         | 66/1500 [00:01<00:26, 53.58it/s, loss=1.2]
SASRec epoch 4/8:   5%|▍         | 72/1500 [00:01<00:26, 53.66it/s, loss=1.2]
SASRec epoch 4/8:   5%|▌         | 78/1500 [00:01<00:27, 52.09it/s, loss=1.2]
SASRec epoch 4/8:   6%|▌         | 84/1500 [00:01<00:27, 52.35it/s, loss=1.2]
SASRec epoch 4/8:   6%|▌         | 90/1500 [00:01<00:26, 52.76it/s, loss=1.2]
SASRec epoch 4/8:   6%|▋         | 96/1500 [00:01<00:26, 53.17it/s, loss=1.2]
SASRec epoch 4/8:   7%|▋         | 100/1500 [00:01<00:26, 53.17it/s, loss=1.17]
SASRec epoch 4/8:   7%|▋         | 102/1500 [00:01<00:27, 50.10it/s, loss=1.17]
SASRec epoch 4/8:   7%|▋         | 108/1500 [00:02<00:28, 49.34it/s, loss=1.17]
SASRec epoch 4/8:   8%|▊         | 114/1500 [00:02<00:27, 50.55it/s, loss=1.17]
SASRec epoch 4/8:   8%|▊         | 120/1500 [00:02<00:26, 51.50it/s, loss=1.17]
SASRec epoch 4/8:   8%|▊         | 126/1500 [00:02<00:26, 52.72it/s, loss=1.17]
SASRec epoch 4/8:   9%|▉         | 132/1500 [00:02<00:26, 52.07it/s, loss=1.17]
SASRec epoch 4/8:   9%|▉         | 138/1500 [00:02<00:25, 53.11it/s, loss=1.17]
SASRec epoch 4/8:  10%|▉         | 144/1500 [00:02<00:25, 53.25it/s, loss=1.17]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:02<00:25, 53.96it/s, loss=1.17]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:02<00:25, 53.96it/s, loss=1.19]
SASRec epoch 4/8:  10%|█         | 156/1500 [00:02<00:25, 53.36it/s, loss=1.19]
SASRec epoch 4/8:  11%|█         | 162/1500 [00:03<00:24, 53.64it/s, loss=1.19]
SASRec epoch 4/8:  11%|█         | 168/1500 [00:03<00:24, 53.95it/s, loss=1.19]
SASRec epoch 4/8:  12%|█▏        | 174/1500 [00:03<00:24, 54.20it/s, loss=1.19]
SASRec epoch 4/8:  12%|█▏        | 180/1500 [00:03<00:24, 54.45it/s, loss=1.19]
SASRec epoch 4/8:  12%|█▏        | 186/1500 [00:03<00:24, 52.94it/s, loss=1.19]
SASRec epoch 4/8:  13%|█▎        | 192/1500 [00:03<00:24, 53.39it/s, loss=1.19]
SASRec epoch 4/8:  13%|█▎        | 198/1500 [00:03<00:24, 53.72it/s, loss=1.19]
SASRec epoch 4/8:  13%|█▎        | 200/1500 [00:03<00:24, 53.72it/s, loss=1.17]
SASRec epoch 4/8:  14%|█▎        | 204/1500 [00:03<00:25, 50.69it/s, loss=1.17]
SASRec epoch 4/8:  14%|█▍        | 210/1500 [00:04<00:27, 46.51it/s, loss=1.17]
SASRec epoch 4/8:  14%|█▍        | 215/1500 [00:04<00:28, 45.06it/s, loss=1.17]
SASRec epoch 4/8:  15%|█▍        | 220/1500 [00:04<00:28, 44.95it/s, loss=1.17]
SASRec epoch 4/8:  15%|█▌        | 225/1500 [00:04<00:28, 44.25it/s, loss=1.17]
SASRec epoch 4/8:  15%|█▌        | 230/1500 [00:04<00:29, 43.60it/s, loss=1.17]
SASRec epoch 4/8:  16%|█▌        | 235/1500 [00:04<00:28, 43.66it/s, loss=1.17]
SASRec epoch 4/8:  16%|█▌        | 240/1500 [00:04<00:28, 44.51it/s, loss=1.17]
SASRec epoch 4/8:  16%|█▋        | 245/1500 [00:04<00:28, 44.50it/s, loss=1.17]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:04<00:27, 44.70it/s, loss=1.17]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:04<00:27, 44.70it/s, loss=1.17]
SASRec epoch 4/8:  17%|█▋        | 255/1500 [00:05<00:28, 42.94it/s, loss=1.17]
SASRec epoch 4/8:  17%|█▋        | 260/1500 [00:05<00:28, 43.86it/s, loss=1.17]
SASRec epoch 4/8:  18%|█▊        | 265/1500 [00:05<00:28, 43.96it/s, loss=1.17]
SASRec epoch 4/8:  18%|█▊        | 270/1500 [00:05<00:27, 43.97it/s, loss=1.17]
SASRec epoch 4/8:  18%|█▊        | 275/1500 [00:05<00:28, 42.63it/s, loss=1.17]
SASRec epoch 4/8:  19%|█▊        | 280/1500 [00:05<00:29, 40.87it/s, loss=1.17]
SASRec epoch 4/8:  19%|█▉        | 285/1500 [00:05<00:29, 40.92it/s, loss=1.17]
SASRec epoch 4/8:  19%|█▉        | 290/1500 [00:05<00:29, 41.54it/s, loss=1.17]
SASRec epoch 4/8:  20%|█▉        | 295/1500 [00:06<00:28, 42.63it/s, loss=1.17]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:06<00:27, 43.26it/s, loss=1.17]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:06<00:27, 43.26it/s, loss=1.17]
SASRec epoch 4/8:  20%|██        | 305/1500 [00:06<00:27, 44.24it/s, loss=1.17]
SASRec epoch 4/8:  21%|██        | 310/1500 [00:06<00:26, 45.26it/s, loss=1.17]
SASRec epoch 4/8:  21%|██        | 315/1500 [00:06<00:26, 44.84it/s, loss=1.17]
SASRec epoch 4/8:  21%|██▏       | 320/1500 [00:06<00:26, 44.69it/s, loss=1.17]
SASRec epoch 4/8:  22%|██▏       | 325/1500 [00:06<00:26, 43.80it/s, loss=1.17]
SASRec epoch 4/8:  22%|██▏       | 330/1500 [00:06<00:28, 40.72it/s, loss=1.17]
SASRec epoch 4/8:  22%|██▏       | 335/1500 [00:06<00:29, 39.27it/s, loss=1.17]
SASRec epoch 4/8:  23%|██▎       | 339/1500 [00:07<00:30, 38.26it/s, loss=1.17]
SASRec epoch 4/8:  23%|██▎       | 344/1500 [00:07<00:29, 39.30it/s, loss=1.17]
SASRec epoch 4/8:  23%|██▎       | 349/1500 [00:07<00:28, 40.56it/s, loss=1.17]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:07<00:28, 40.56it/s, loss=1.16]
SASRec epoch 4/8:  24%|██▎       | 354/1500 [00:07<00:30, 37.84it/s, loss=1.16]
SASRec epoch 4/8:  24%|██▍       | 358/1500 [00:07<00:30, 37.83it/s, loss=1.16]
SASRec epoch 4/8:  24%|██▍       | 362/1500 [00:07<00:30, 37.41it/s, loss=1.16]
SASRec epoch 4/8:  24%|██▍       | 366/1500 [00:07<00:30, 37.51it/s, loss=1.16]
SASRec epoch 4/8:  25%|██▍       | 370/1500 [00:08<00:49, 22.87it/s, loss=1.16]
SASRec epoch 4/8:  25%|██▍       | 373/1500 [00:08<00:59, 18.86it/s, loss=1.16]
SASRec epoch 4/8:  25%|██▌       | 376/1500 [00:08<01:03, 17.57it/s, loss=1.16]
SASRec epoch 4/8:  25%|██▌       | 380/1500 [00:08<00:53, 20.82it/s, loss=1.16]
SASRec epoch 4/8:  26%|██▌       | 386/1500 [00:08<00:40, 27.58it/s, loss=1.16]
SASRec epoch 4/8:  26%|██▌       | 391/1500 [00:08<00:34, 31.69it/s, loss=1.16]
SASRec epoch 4/8:  26%|██▋       | 397/1500 [00:09<00:29, 37.16it/s, loss=1.16]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:09<00:29, 37.16it/s, loss=1.17]
SASRec epoch 4/8:  27%|██▋       | 402/1500 [00:09<00:27, 39.85it/s, loss=1.17]
SASRec epoch 4/8:  27%|██▋       | 408/1500 [00:09<00:24, 43.81it/s, loss=1.17]
SASRec epoch 4/8:  28%|██▊       | 414/1500 [00:09<00:23, 46.79it/s, loss=1.17]
SASRec epoch 4/8:  28%|██▊       | 420/1500 [00:09<00:22, 48.50it/s, loss=1.17]
SASRec epoch 4/8:  28%|██▊       | 426/1500 [00:09<00:21, 49.78it/s, loss=1.17]
SASRec epoch 4/8:  29%|██▉       | 432/1500 [00:09<00:21, 50.80it/s, loss=1.17]
SASRec epoch 4/8:  29%|██▉       | 438/1500 [00:09<00:20, 51.51it/s, loss=1.17]
SASRec epoch 4/8:  30%|██▉       | 444/1500 [00:09<00:20, 51.08it/s, loss=1.17]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:10<00:20, 51.81it/s, loss=1.17]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:10<00:20, 51.81it/s, loss=1.16]
SASRec epoch 4/8:  30%|███       | 456/1500 [00:10<00:20, 51.16it/s, loss=1.16]
SASRec epoch 4/8:  31%|███       | 462/1500 [00:10<00:19, 52.09it/s, loss=1.16]
SASRec epoch 4/8:  31%|███       | 468/1500 [00:10<00:19, 52.88it/s, loss=1.16]
SASRec epoch 4/8:  32%|███▏      | 474/1500 [00:10<00:19, 52.73it/s, loss=1.16]
SASRec epoch 4/8:  32%|███▏      | 480/1500 [00:10<00:19, 53.12it/s, loss=1.16]
SASRec epoch 4/8:  32%|███▏      | 486/1500 [00:10<00:18, 53.56it/s, loss=1.16]
SASRec epoch 4/8:  33%|███▎      | 492/1500 [00:10<00:18, 53.56it/s, loss=1.16]
SASRec epoch 4/8:  33%|███▎      | 498/1500 [00:10<00:18, 53.79it/s, loss=1.16]
SASRec epoch 4/8:  33%|███▎      | 500/1500 [00:11<00:18, 53.79it/s, loss=1.17]
SASRec epoch 4/8:  34%|███▎      | 504/1500 [00:11<00:19, 50.23it/s, loss=1.17]
SASRec epoch 4/8:  34%|███▍      | 510/1500 [00:11<00:19, 51.03it/s, loss=1.17]
SASRec epoch 4/8:  34%|███▍      | 516/1500 [00:11<00:18, 51.86it/s, loss=1.17]
SASRec epoch 4/8:  35%|███▍      | 522/1500 [00:11<00:18, 51.99it/s, loss=1.17]
SASRec epoch 4/8:  35%|███▌      | 528/1500 [00:11<00:18, 52.20it/s, loss=1.17]
SASRec epoch 4/8:  36%|███▌      | 534/1500 [00:11<00:18, 52.47it/s, loss=1.17]
SASRec epoch 4/8:  36%|███▌      | 540/1500 [00:11<00:18, 52.67it/s, loss=1.17]
SASRec epoch 4/8:  36%|███▋      | 546/1500 [00:11<00:18, 52.68it/s, loss=1.17]
SASRec epoch 4/8:  37%|███▋      | 550/1500 [00:11<00:18, 52.68it/s, loss=1.15]
SASRec epoch 4/8:  37%|███▋      | 552/1500 [00:12<00:18, 51.72it/s, loss=1.15]
SASRec epoch 4/8:  37%|███▋      | 558/1500 [00:12<00:18, 50.26it/s, loss=1.15]
SASRec epoch 4/8:  38%|███▊      | 564/1500 [00:12<00:18, 51.17it/s, loss=1.15]
SASRec epoch 4/8:  38%|███▊      | 570/1500 [00:12<00:17, 51.78it/s, loss=1.15]
SASRec epoch 4/8:  38%|███▊      | 576/1500 [00:12<00:17, 52.85it/s, loss=1.15]
SASRec epoch 4/8:  39%|███▉      | 582/1500 [00:12<00:17, 53.25it/s, loss=1.15]
SASRec epoch 4/8:  39%|███▉      | 588/1500 [00:12<00:17, 53.64it/s, loss=1.15]
SASRec epoch 4/8:  40%|███▉      | 594/1500 [00:12<00:16, 53.92it/s, loss=1.15]
SASRec epoch 4/8:  40%|████      | 600/1500 [00:12<00:16, 54.05it/s, loss=1.15]
SASRec epoch 4/8:  40%|████      | 600/1500 [00:12<00:16, 54.05it/s, loss=1.16]
SASRec epoch 4/8:  40%|████      | 606/1500 [00:13<00:16, 53.53it/s, loss=1.16]
SASRec epoch 4/8:  41%|████      | 612/1500 [00:13<00:17, 51.96it/s, loss=1.16]
SASRec epoch 4/8:  41%|████      | 618/1500 [00:13<00:16, 52.57it/s, loss=1.16]
SASRec epoch 4/8:  42%|████▏     | 624/1500 [00:13<00:16, 53.00it/s, loss=1.16]
SASRec epoch 4/8:  42%|████▏     | 630/1500 [00:13<00:16, 53.05it/s, loss=1.16]
SASRec epoch 4/8:  42%|████▏     | 636/1500 [00:13<00:16, 52.90it/s, loss=1.16]
SASRec epoch 4/8:  43%|████▎     | 642/1500 [00:13<00:16, 53.29it/s, loss=1.16]
SASRec epoch 4/8:  43%|████▎     | 648/1500 [00:13<00:15, 53.74it/s, loss=1.16]
SASRec epoch 4/8:  43%|████▎     | 650/1500 [00:13<00:15, 53.74it/s, loss=1.16]
SASRec epoch 4/8:  44%|████▎     | 654/1500 [00:13<00:16, 52.51it/s, loss=1.16]
SASRec epoch 4/8:  44%|████▍     | 660/1500 [00:14<00:15, 52.78it/s, loss=1.16]
SASRec epoch 4/8:  44%|████▍     | 666/1500 [00:14<00:16, 51.84it/s, loss=1.16]
SASRec epoch 4/8:  45%|████▍     | 672/1500 [00:14<00:15, 52.41it/s, loss=1.16]
SASRec epoch 4/8:  45%|████▌     | 678/1500 [00:14<00:15, 52.98it/s, loss=1.16]
SASRec epoch 4/8:  46%|████▌     | 684/1500 [00:14<00:15, 53.24it/s, loss=1.16]
SASRec epoch 4/8:  46%|████▌     | 690/1500 [00:14<00:15, 53.77it/s, loss=1.16]
SASRec epoch 4/8:  46%|████▋     | 696/1500 [00:14<00:14, 53.96it/s, loss=1.16]
SASRec epoch 4/8:  47%|████▋     | 700/1500 [00:14<00:14, 53.96it/s, loss=1.15]
SASRec epoch 4/8:  47%|████▋     | 702/1500 [00:14<00:15, 52.43it/s, loss=1.15]
SASRec epoch 4/8:  47%|████▋     | 708/1500 [00:15<00:17, 44.91it/s, loss=1.15]
SASRec epoch 4/8:  48%|████▊     | 713/1500 [00:15<00:25, 30.36it/s, loss=1.15]
SASRec epoch 4/8:  48%|████▊     | 717/1500 [00:15<00:31, 25.24it/s, loss=1.15]
SASRec epoch 4/8:  48%|████▊     | 721/1500 [00:15<00:32, 23.77it/s, loss=1.15]
SASRec epoch 4/8:  48%|████▊     | 727/1500 [00:15<00:26, 29.35it/s, loss=1.15]
SASRec epoch 4/8:  49%|████▉     | 733/1500 [00:16<00:22, 34.52it/s, loss=1.15]
SASRec epoch 4/8:  49%|████▉     | 739/1500 [00:16<00:19, 38.91it/s, loss=1.15]
SASRec epoch 4/8:  50%|████▉     | 744/1500 [00:16<00:18, 40.84it/s, loss=1.15]
SASRec epoch 4/8:  50%|█████     | 750/1500 [00:16<00:16, 44.37it/s, loss=1.15]
SASRec epoch 4/8:  50%|█████     | 750/1500 [00:16<00:16, 44.37it/s, loss=1.16]
SASRec epoch 4/8:  50%|█████     | 755/1500 [00:16<00:16, 45.50it/s, loss=1.16]
SASRec epoch 4/8:  51%|█████     | 761/1500 [00:16<00:15, 47.61it/s, loss=1.16]
SASRec epoch 4/8:  51%|█████     | 767/1500 [00:16<00:14, 49.36it/s, loss=1.16]
SASRec epoch 4/8:  52%|█████▏    | 773/1500 [00:16<00:14, 51.06it/s, loss=1.16]
SASRec epoch 4/8:  52%|█████▏    | 779/1500 [00:16<00:13, 52.03it/s, loss=1.16]
SASRec epoch 4/8:  52%|█████▏    | 785/1500 [00:16<00:13, 52.10it/s, loss=1.16]
SASRec epoch 4/8:  53%|█████▎    | 791/1500 [00:17<00:13, 52.64it/s, loss=1.16]
SASRec epoch 4/8:  53%|█████▎    | 797/1500 [00:17<00:13, 53.07it/s, loss=1.16]
SASRec epoch 4/8:  53%|█████▎    | 800/1500 [00:17<00:13, 53.07it/s, loss=1.15]
SASRec epoch 4/8:  54%|█████▎    | 803/1500 [00:17<00:13, 50.50it/s, loss=1.15]
SASRec epoch 4/8:  54%|█████▍    | 809/1500 [00:17<00:13, 51.59it/s, loss=1.15]
SASRec epoch 4/8:  54%|█████▍    | 815/1500 [00:17<00:13, 52.29it/s, loss=1.15]
SASRec epoch 4/8:  55%|█████▍    | 821/1500 [00:17<00:12, 53.00it/s, loss=1.15]
SASRec epoch 4/8:  55%|█████▌    | 827/1500 [00:17<00:13, 51.66it/s, loss=1.15]
SASRec epoch 4/8:  56%|█████▌    | 833/1500 [00:17<00:14, 46.52it/s, loss=1.15]
SASRec epoch 4/8:  56%|█████▌    | 838/1500 [00:18<00:14, 46.42it/s, loss=1.15]
SASRec epoch 4/8:  56%|█████▌    | 843/1500 [00:18<00:14, 46.21it/s, loss=1.15]
SASRec epoch 4/8:  57%|█████▋    | 848/1500 [00:18<00:14, 46.00it/s, loss=1.15]
SASRec epoch 4/8:  57%|█████▋    | 850/1500 [00:18<00:14, 46.00it/s, loss=1.13]
SASRec epoch 4/8:  57%|█████▋    | 853/1500 [00:18<00:15, 42.55it/s, loss=1.13]
SASRec epoch 4/8:  57%|█████▋    | 858/1500 [00:18<00:14, 42.81it/s, loss=1.13]
SASRec epoch 4/8:  58%|█████▊    | 863/1500 [00:18<00:15, 42.39it/s, loss=1.13]
SASRec epoch 4/8:  58%|█████▊    | 868/1500 [00:18<00:15, 42.09it/s, loss=1.13]
SASRec epoch 4/8:  58%|█████▊    | 873/1500 [00:18<00:15, 41.32it/s, loss=1.13]
SASRec epoch 4/8:  59%|█████▊    | 878/1500 [00:19<00:14, 42.61it/s, loss=1.13]
SASRec epoch 4/8:  59%|█████▉    | 883/1500 [00:19<00:14, 43.70it/s, loss=1.13]
SASRec epoch 4/8:  59%|█████▉    | 888/1500 [00:19<00:13, 44.26it/s, loss=1.13]
SASRec epoch 4/8:  60%|█████▉    | 893/1500 [00:19<00:13, 44.89it/s, loss=1.13]
SASRec epoch 4/8:  60%|█████▉    | 898/1500 [00:19<00:13, 43.93it/s, loss=1.13]
SASRec epoch 4/8:  60%|██████    | 900/1500 [00:19<00:13, 43.93it/s, loss=1.14]
SASRec epoch 4/8:  60%|██████    | 903/1500 [00:19<00:14, 41.91it/s, loss=1.14]
SASRec epoch 4/8:  61%|██████    | 908/1500 [00:19<00:13, 42.41it/s, loss=1.14]
SASRec epoch 4/8:  61%|██████    | 913/1500 [00:19<00:13, 43.36it/s, loss=1.14]
SASRec epoch 4/8:  61%|██████    | 918/1500 [00:19<00:13, 43.23it/s, loss=1.14]
SASRec epoch 4/8:  62%|██████▏   | 923/1500 [00:20<00:13, 43.69it/s, loss=1.14]
SASRec epoch 4/8:  62%|██████▏   | 928/1500 [00:20<00:13, 43.83it/s, loss=1.14]
SASRec epoch 4/8:  62%|██████▏   | 933/1500 [00:20<00:12, 43.80it/s, loss=1.14]
SASRec epoch 4/8:  63%|██████▎   | 938/1500 [00:20<00:12, 44.18it/s, loss=1.14]
SASRec epoch 4/8:  63%|██████▎   | 943/1500 [00:20<00:12, 43.96it/s, loss=1.14]
SASRec epoch 4/8:  63%|██████▎   | 948/1500 [00:20<00:13, 41.90it/s, loss=1.14]
SASRec epoch 4/8:  63%|██████▎   | 950/1500 [00:20<00:13, 41.90it/s, loss=1.14]
SASRec epoch 4/8:  64%|██████▎   | 953/1500 [00:20<00:13, 39.78it/s, loss=1.14]
SASRec epoch 4/8:  64%|██████▍   | 958/1500 [00:20<00:13, 38.92it/s, loss=1.14]
SASRec epoch 4/8:  64%|██████▍   | 962/1500 [00:21<00:14, 38.22it/s, loss=1.14]
SASRec epoch 4/8:  64%|██████▍   | 966/1500 [00:21<00:14, 37.14it/s, loss=1.14]
SASRec epoch 4/8:  65%|██████▍   | 971/1500 [00:21<00:13, 38.64it/s, loss=1.14]
SASRec epoch 4/8:  65%|██████▌   | 975/1500 [00:21<00:13, 38.97it/s, loss=1.14]
SASRec epoch 4/8:  65%|██████▌   | 979/1500 [00:21<00:13, 38.54it/s, loss=1.14]
SASRec epoch 4/8:  66%|██████▌   | 983/1500 [00:21<00:13, 38.48it/s, loss=1.14]
SASRec epoch 4/8:  66%|██████▌   | 987/1500 [00:21<00:13, 37.40it/s, loss=1.14]
SASRec epoch 4/8:  66%|██████▌   | 991/1500 [00:21<00:13, 37.88it/s, loss=1.14]
SASRec epoch 4/8:  66%|██████▋   | 995/1500 [00:21<00:13, 38.05it/s, loss=1.14]
SASRec epoch 4/8:  67%|██████▋   | 1000/1500 [00:21<00:13, 38.05it/s, loss=1.14]
SASRec epoch 4/8:  67%|██████▋   | 1001/1500 [00:22<00:11, 41.96it/s, loss=1.14]
SASRec epoch 4/8:  67%|██████▋   | 1007/1500 [00:22<00:10, 45.64it/s, loss=1.14]
SASRec epoch 4/8:  68%|██████▊   | 1013/1500 [00:22<00:10, 48.29it/s, loss=1.14]
SASRec epoch 4/8:  68%|██████▊   | 1019/1500 [00:22<00:09, 49.94it/s, loss=1.14]
SASRec epoch 4/8:  68%|██████▊   | 1025/1500 [00:22<00:09, 50.62it/s, loss=1.14]
SASRec epoch 4/8:  69%|██████▊   | 1031/1500 [00:22<00:09, 51.79it/s, loss=1.14]
SASRec epoch 4/8:  69%|██████▉   | 1037/1500 [00:22<00:08, 52.57it/s, loss=1.14]
SASRec epoch 4/8:  70%|██████▉   | 1043/1500 [00:22<00:08, 51.74it/s, loss=1.14]
SASRec epoch 4/8:  70%|██████▉   | 1049/1500 [00:22<00:08, 52.12it/s, loss=1.14]
SASRec epoch 4/8:  70%|███████   | 1050/1500 [00:22<00:08, 52.12it/s, loss=1.14]
SASRec epoch 4/8:  70%|███████   | 1055/1500 [00:23<00:08, 51.32it/s, loss=1.14]
SASRec epoch 4/8:  71%|███████   | 1061/1500 [00:23<00:08, 52.06it/s, loss=1.14]
SASRec epoch 4/8:  71%|███████   | 1067/1500 [00:23<00:08, 52.76it/s, loss=1.14]
SASRec epoch 4/8:  72%|███████▏  | 1073/1500 [00:23<00:08, 52.90it/s, loss=1.14]
SASRec epoch 4/8:  72%|███████▏  | 1079/1500 [00:23<00:07, 53.38it/s, loss=1.14]
SASRec epoch 4/8:  72%|███████▏  | 1085/1500 [00:23<00:07, 53.09it/s, loss=1.14]
SASRec epoch 4/8:  73%|███████▎  | 1091/1500 [00:23<00:07, 53.06it/s, loss=1.14]
SASRec epoch 4/8:  73%|███████▎  | 1097/1500 [00:23<00:07, 52.31it/s, loss=1.14]
SASRec epoch 4/8:  73%|███████▎  | 1100/1500 [00:23<00:07, 52.31it/s, loss=1.14]
SASRec epoch 4/8:  74%|███████▎  | 1103/1500 [00:23<00:07, 51.12it/s, loss=1.14]
SASRec epoch 4/8:  74%|███████▍  | 1109/1500 [00:24<00:07, 51.61it/s, loss=1.14]
SASRec epoch 4/8:  74%|███████▍  | 1115/1500 [00:24<00:07, 51.81it/s, loss=1.14]
SASRec epoch 4/8:  75%|███████▍  | 1121/1500 [00:24<00:07, 51.89it/s, loss=1.14]
SASRec epoch 4/8:  75%|███████▌  | 1127/1500 [00:24<00:07, 52.33it/s, loss=1.14]
SASRec epoch 4/8:  76%|███████▌  | 1133/1500 [00:24<00:06, 52.53it/s, loss=1.14]
SASRec epoch 4/8:  76%|███████▌  | 1139/1500 [00:24<00:06, 52.97it/s, loss=1.14]
SASRec epoch 4/8:  76%|███████▋  | 1145/1500 [00:24<00:06, 53.57it/s, loss=1.14]
SASRec epoch 4/8:  77%|███████▋  | 1150/1500 [00:24<00:06, 53.57it/s, loss=1.13]
SASRec epoch 4/8:  77%|███████▋  | 1151/1500 [00:24<00:06, 50.99it/s, loss=1.13]
SASRec epoch 4/8:  77%|███████▋  | 1157/1500 [00:24<00:06, 52.21it/s, loss=1.13]
SASRec epoch 4/8:  78%|███████▊  | 1163/1500 [00:25<00:06, 53.01it/s, loss=1.13]
SASRec epoch 4/8:  78%|███████▊  | 1169/1500 [00:25<00:06, 53.63it/s, loss=1.13]
SASRec epoch 4/8:  78%|███████▊  | 1175/1500 [00:25<00:06, 53.99it/s, loss=1.13]
SASRec epoch 4/8:  79%|███████▊  | 1181/1500 [00:25<00:05, 54.17it/s, loss=1.13]
SASRec epoch 4/8:  79%|███████▉  | 1187/1500 [00:25<00:05, 54.24it/s, loss=1.13]
SASRec epoch 4/8:  80%|███████▉  | 1193/1500 [00:25<00:05, 54.21it/s, loss=1.13]
SASRec epoch 4/8:  80%|███████▉  | 1199/1500 [00:25<00:05, 54.51it/s, loss=1.13]
SASRec epoch 4/8:  80%|████████  | 1200/1500 [00:25<00:05, 54.51it/s, loss=1.13]
SASRec epoch 4/8:  80%|████████  | 1205/1500 [00:25<00:05, 51.90it/s, loss=1.13]
SASRec epoch 4/8:  81%|████████  | 1211/1500 [00:25<00:05, 52.29it/s, loss=1.13]
SASRec epoch 4/8:  81%|████████  | 1217/1500 [00:26<00:05, 52.97it/s, loss=1.13]
SASRec epoch 4/8:  82%|████████▏ | 1223/1500 [00:26<00:05, 53.05it/s, loss=1.13]
SASRec epoch 4/8:  82%|████████▏ | 1229/1500 [00:26<00:05, 53.15it/s, loss=1.13]
SASRec epoch 4/8:  82%|████████▏ | 1235/1500 [00:26<00:04, 53.18it/s, loss=1.13]
SASRec epoch 4/8:  83%|████████▎ | 1241/1500 [00:26<00:04, 52.55it/s, loss=1.13]
SASRec epoch 4/8:  83%|████████▎ | 1247/1500 [00:26<00:04, 52.76it/s, loss=1.13]
SASRec epoch 4/8:  83%|████████▎ | 1250/1500 [00:26<00:04, 52.76it/s, loss=1.13]
SASRec epoch 4/8:  84%|████████▎ | 1253/1500 [00:26<00:04, 51.54it/s, loss=1.13]

[SASRec] epoch 4/8 loss=1.1494

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 5/8:   0%|          | 6/1500 [00:00<00:28, 52.49it/s]
SASRec epoch 5/8:   1%|          | 12/1500 [00:00<00:27, 53.80it/s]
SASRec epoch 5/8:   1%|          | 18/1500 [00:00<00:27, 53.69it/s]
SASRec epoch 5/8:   2%|▏         | 24/1500 [00:00<00:30, 49.09it/s]
SASRec epoch 5/8:   2%|▏         | 29/1500 [00:00<00:33, 43.44it/s]
SASRec epoch 5/8:   2%|▏         | 34/1500 [00:00<00:36, 40.36it/s]
SASRec epoch 5/8:   3%|▎         | 39/1500 [00:00<00:35, 41.14it/s]
SASRec epoch 5/8:   3%|▎         | 44/1500 [00:00<00:34, 41.79it/s]
SASRec epoch 5/8:   3%|▎         | 49/1500 [00:01<00:34, 42.05it/s]
SASRec epoch 5/8:   3%|▎         | 50/1500 [00:01<00:34, 42.05it/s, loss=1.12]
SASRec epoch 5/8:   4%|▎         | 54/1500 [00:01<00:34, 41.90it/s, loss=1.12]
SASRec epoch 5/8:   4%|▍         | 59/1500 [00:01<00:33, 42.41it/s, loss=1.12]
SASRec epoch 5/8:   4%|▍         | 64/1500 [00:01<00:33, 43.32it/s, loss=1.12]
SASRec epoch 5/8:   5%|▍         | 69/1500 [00:01<00:32, 43.60it/s, loss=1.12]
SASRec epoch 5/8:   5%|▍         | 74/1500 [00:01<00:32, 44.05it/s, loss=1.12]
SASRec epoch 5/8:   5%|▌         | 79/1500 [00:01<00:32, 43.43it/s, loss=1.12]
SASRec epoch 5/8:   6%|▌         | 84/1500 [00:01<00:32, 43.03it/s, loss=1.12]
SASRec epoch 5/8:   6%|▌         | 89/1500 [00:02<00:31, 44.43it/s, loss=1.12]
SASRec epoch 5/8:   6%|▋         | 94/1500 [00:02<00:30, 45.39it/s, loss=1.12]
SASRec epoch 5/8:   7%|▋         | 99/1500 [00:02<00:30, 45.66it/s, loss=1.12]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:02<00:30, 45.66it/s, loss=1.11]
SASRec epoch 5/8:   7%|▋         | 104/1500 [00:02<00:31, 44.14it/s, loss=1.11]
SASRec epoch 5/8:   7%|▋         | 109/1500 [00:02<00:31, 43.96it/s, loss=1.11]
SASRec epoch 5/8:   8%|▊         | 114/1500 [00:02<00:31, 43.35it/s, loss=1.11]
SASRec epoch 5/8:   8%|▊         | 119/1500 [00:02<00:31, 43.52it/s, loss=1.11]
SASRec epoch 5/8:   8%|▊         | 124/1500 [00:02<00:31, 43.80it/s, loss=1.11]
SASRec epoch 5/8:   9%|▊         | 129/1500 [00:02<00:33, 40.54it/s, loss=1.11]
SASRec epoch 5/8:   9%|▉         | 134/1500 [00:03<00:33, 40.89it/s, loss=1.11]
SASRec epoch 5/8:   9%|▉         | 139/1500 [00:03<00:33, 41.03it/s, loss=1.11]
SASRec epoch 5/8:  10%|▉         | 144/1500 [00:03<00:32, 42.23it/s, loss=1.11]
SASRec epoch 5/8:  10%|▉         | 149/1500 [00:03<00:32, 41.92it/s, loss=1.11]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:03<00:32, 41.92it/s, loss=1.12]
SASRec epoch 5/8:  10%|█         | 154/1500 [00:03<00:32, 41.01it/s, loss=1.12]
SASRec epoch 5/8:  11%|█         | 159/1500 [00:03<00:33, 40.22it/s, loss=1.12]
SASRec epoch 5/8:  11%|█         | 164/1500 [00:03<00:33, 39.79it/s, loss=1.12]
SASRec epoch 5/8:  11%|█▏        | 169/1500 [00:03<00:33, 40.27it/s, loss=1.12]
SASRec epoch 5/8:  12%|█▏        | 174/1500 [00:04<00:35, 37.73it/s, loss=1.12]
SASRec epoch 5/8:  12%|█▏        | 178/1500 [00:04<00:35, 37.51it/s, loss=1.12]
SASRec epoch 5/8:  12%|█▏        | 182/1500 [00:04<00:35, 36.76it/s, loss=1.12]
SASRec epoch 5/8:  12%|█▏        | 186/1500 [00:04<00:36, 36.20it/s, loss=1.12]
SASRec epoch 5/8:  13%|█▎        | 190/1500 [00:04<00:36, 36.24it/s, loss=1.12]
SASRec epoch 5/8:  13%|█▎        | 196/1500 [00:04<00:31, 41.28it/s, loss=1.12]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:04<00:31, 41.28it/s, loss=1.11]
SASRec epoch 5/8:  13%|█▎        | 201/1500 [00:04<00:30, 43.04it/s, loss=1.11]
SASRec epoch 5/8:  14%|█▍        | 207/1500 [00:04<00:27, 46.35it/s, loss=1.11]
SASRec epoch 5/8:  14%|█▍        | 213/1500 [00:04<00:26, 47.83it/s, loss=1.11]
SASRec epoch 5/8:  15%|█▍        | 218/1500 [00:05<00:27, 46.71it/s, loss=1.11]
SASRec epoch 5/8:  15%|█▍        | 224/1500 [00:05<00:26, 48.22it/s, loss=1.11]
SASRec epoch 5/8:  15%|█▌        | 230/1500 [00:05<00:25, 49.80it/s, loss=1.11]
SASRec epoch 5/8:  16%|█▌        | 236/1500 [00:05<00:24, 50.88it/s, loss=1.11]
SASRec epoch 5/8:  16%|█▌        | 242/1500 [00:05<00:24, 51.36it/s, loss=1.11]
SASRec epoch 5/8:  17%|█▋        | 248/1500 [00:05<00:24, 51.97it/s, loss=1.11]
SASRec epoch 5/8:  17%|█▋        | 250/1500 [00:05<00:24, 51.97it/s, loss=1.11]
SASRec epoch 5/8:  17%|█▋        | 254/1500 [00:05<00:24, 51.27it/s, loss=1.11]
SASRec epoch 5/8:  17%|█▋        | 260/1500 [00:05<00:24, 51.66it/s, loss=1.11]
SASRec epoch 5/8:  18%|█▊        | 266/1500 [00:06<00:24, 51.32it/s, loss=1.11]
SASRec epoch 5/8:  18%|█▊        | 272/1500 [00:06<00:24, 50.41it/s, loss=1.11]
SASRec epoch 5/8:  19%|█▊        | 278/1500 [00:06<00:24, 50.72it/s, loss=1.11]
SASRec epoch 5/8:  19%|█▉        | 284/1500 [00:06<00:23, 51.28it/s, loss=1.11]
SASRec epoch 5/8:  19%|█▉        | 290/1500 [00:06<00:23, 52.03it/s, loss=1.11]
SASRec epoch 5/8:  20%|█▉        | 296/1500 [00:06<00:22, 52.73it/s, loss=1.11]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:06<00:22, 52.73it/s, loss=1.11]
SASRec epoch 5/8:  20%|██        | 302/1500 [00:06<00:23, 51.91it/s, loss=1.11]
SASRec epoch 5/8:  21%|██        | 308/1500 [00:06<00:22, 52.80it/s, loss=1.11]
SASRec epoch 5/8:  21%|██        | 314/1500 [00:06<00:22, 52.93it/s, loss=1.11]
SASRec epoch 5/8:  21%|██▏       | 320/1500 [00:07<00:22, 53.58it/s, loss=1.11]
SASRec epoch 5/8:  22%|██▏       | 326/1500 [00:07<00:22, 51.38it/s, loss=1.11]
SASRec epoch 5/8:  22%|██▏       | 332/1500 [00:07<00:22, 51.34it/s, loss=1.11]
SASRec epoch 5/8:  23%|██▎       | 338/1500 [00:07<00:22, 52.16it/s, loss=1.11]
SASRec epoch 5/8:  23%|██▎       | 344/1500 [00:07<00:21, 52.64it/s, loss=1.11]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:07<00:21, 53.10it/s, loss=1.11]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:07<00:21, 53.10it/s, loss=1.1]
SASRec epoch 5/8:  24%|██▎       | 356/1500 [00:07<00:21, 53.01it/s, loss=1.1]
SASRec epoch 5/8:  24%|██▍       | 362/1500 [00:07<00:21, 53.37it/s, loss=1.1]
SASRec epoch 5/8:  25%|██▍       | 368/1500 [00:07<00:21, 53.71it/s, loss=1.1]
SASRec epoch 5/8:  25%|██▍       | 374/1500 [00:08<00:21, 52.59it/s, loss=1.1]
SASRec epoch 5/8:  25%|██▌       | 380/1500 [00:08<00:21, 51.52it/s, loss=1.1]
SASRec epoch 5/8:  26%|██▌       | 386/1500 [00:08<00:21, 52.17it/s, loss=1.1]
SASRec epoch 5/8:  26%|██▌       | 392/1500 [00:08<00:20, 52.78it/s, loss=1.1]
SASRec epoch 5/8:  27%|██▋       | 398/1500 [00:08<00:20, 53.05it/s, loss=1.1]
SASRec epoch 5/8:  27%|██▋       | 400/1500 [00:08<00:20, 53.05it/s, loss=1.1]
SASRec epoch 5/8:  27%|██▋       | 404/1500 [00:08<00:21, 51.55it/s, loss=1.1]
SASRec epoch 5/8:  27%|██▋       | 410/1500 [00:08<00:20, 52.09it/s, loss=1.1]
SASRec epoch 5/8:  28%|██▊       | 416/1500 [00:08<00:20, 52.78it/s, loss=1.1]
SASRec epoch 5/8:  28%|██▊       | 422/1500 [00:08<00:20, 52.93it/s, loss=1.1]
SASRec epoch 5/8:  29%|██▊       | 428/1500 [00:09<00:20, 53.35it/s, loss=1.1]
SASRec epoch 5/8:  29%|██▉       | 434/1500 [00:09<00:20, 52.76it/s, loss=1.1]
SASRec epoch 5/8:  29%|██▉       | 440/1500 [00:09<00:19, 53.09it/s, loss=1.1]
SASRec epoch 5/8:  30%|██▉       | 446/1500 [00:09<00:19, 53.48it/s, loss=1.1]
SASRec epoch 5/8:  30%|███       | 450/1500 [00:09<00:19, 53.48it/s, loss=1.1]
SASRec epoch 5/8:  30%|███       | 452/1500 [00:09<00:20, 52.00it/s, loss=1.1]
SASRec epoch 5/8:  31%|███       | 458/1500 [00:09<00:19, 52.92it/s, loss=1.1]
SASRec epoch 5/8:  31%|███       | 464/1500 [00:09<00:19, 53.19it/s, loss=1.1]
SASRec epoch 5/8:  31%|███▏      | 470/1500 [00:09<00:19, 53.59it/s, loss=1.1]
SASRec epoch 5/8:  32%|███▏      | 476/1500 [00:10<00:19, 53.78it/s, loss=1.1]
SASRec epoch 5/8:  32%|███▏      | 482/1500 [00:10<00:19, 53.50it/s, loss=1.1]
SASRec epoch 5/8:  33%|███▎      | 488/1500 [00:10<00:19, 52.45it/s, loss=1.1]
SASRec epoch 5/8:  33%|███▎      | 494/1500 [00:10<00:18, 52.96it/s, loss=1.1]
SASRec epoch 5/8:  33%|███▎      | 500/1500 [00:10<00:18, 53.49it/s, loss=1.1]
SASRec epoch 5/8:  33%|███▎      | 500/1500 [00:10<00:18, 53.49it/s, loss=1.09]
SASRec epoch 5/8:  34%|███▎      | 506/1500 [00:10<00:18, 52.63it/s, loss=1.09]
SASRec epoch 5/8:  34%|███▍      | 512/1500 [00:10<00:18, 53.40it/s, loss=1.09]
SASRec epoch 5/8:  35%|███▍      | 518/1500 [00:10<00:18, 53.93it/s, loss=1.09]
SASRec epoch 5/8:  35%|███▍      | 524/1500 [00:10<00:18, 54.18it/s, loss=1.09]
SASRec epoch 5/8:  35%|███▌      | 530/1500 [00:11<00:17, 54.19it/s, loss=1.09]
SASRec epoch 5/8:  36%|███▌      | 536/1500 [00:11<00:17, 53.93it/s, loss=1.09]
SASRec epoch 5/8:  36%|███▌      | 542/1500 [00:11<00:17, 54.28it/s, loss=1.09]
SASRec epoch 5/8:  37%|███▋      | 548/1500 [00:11<00:18, 52.63it/s, loss=1.09]
SASRec epoch 5/8:  37%|███▋      | 550/1500 [00:11<00:18, 52.63it/s, loss=1.09]
SASRec epoch 5/8:  37%|███▋      | 554/1500 [00:11<00:18, 52.00it/s, loss=1.09]
SASRec epoch 5/8:  37%|███▋      | 560/1500 [00:11<00:17, 52.83it/s, loss=1.09]
SASRec epoch 5/8:  38%|███▊      | 566/1500 [00:11<00:17, 53.50it/s, loss=1.09]
SASRec epoch 5/8:  38%|███▊      | 572/1500 [00:11<00:17, 53.78it/s, loss=1.09]
SASRec epoch 5/8:  39%|███▊      | 578/1500 [00:11<00:17, 53.84it/s, loss=1.09]
SASRec epoch 5/8:  39%|███▉      | 584/1500 [00:12<00:17, 53.74it/s, loss=1.09]
SASRec epoch 5/8:  39%|███▉      | 590/1500 [00:12<00:16, 53.96it/s, loss=1.09]
SASRec epoch 5/8:  40%|███▉      | 596/1500 [00:12<00:16, 54.19it/s, loss=1.09]
SASRec epoch 5/8:  40%|████      | 600/1500 [00:12<00:16, 54.19it/s, loss=1.09]
SASRec epoch 5/8:  40%|████      | 602/1500 [00:12<00:17, 51.13it/s, loss=1.09]
SASRec epoch 5/8:  41%|████      | 608/1500 [00:12<00:17, 52.00it/s, loss=1.09]
SASRec epoch 5/8:  41%|████      | 614/1500 [00:12<00:16, 52.36it/s, loss=1.09]
SASRec epoch 5/8:  41%|████▏     | 620/1500 [00:12<00:16, 52.77it/s, loss=1.09]
SASRec epoch 5/8:  42%|████▏     | 626/1500 [00:12<00:16, 53.05it/s, loss=1.09]
SASRec epoch 5/8:  42%|████▏     | 632/1500 [00:12<00:16, 53.35it/s, loss=1.09]
SASRec epoch 5/8:  43%|████▎     | 638/1500 [00:13<00:16, 52.72it/s, loss=1.09]
SASRec epoch 5/8:  43%|████▎     | 644/1500 [00:13<00:16, 52.99it/s, loss=1.09]
SASRec epoch 5/8:  43%|████▎     | 650/1500 [00:13<00:16, 53.03it/s, loss=1.09]
SASRec epoch 5/8:  43%|████▎     | 650/1500 [00:13<00:16, 53.03it/s, loss=1.08]
SASRec epoch 5/8:  44%|████▎     | 656/1500 [00:13<00:16, 51.08it/s, loss=1.08]
SASRec epoch 5/8:  44%|████▍     | 662/1500 [00:13<00:16, 52.24it/s, loss=1.08]
SASRec epoch 5/8:  45%|████▍     | 668/1500 [00:13<00:15, 52.88it/s, loss=1.08]
SASRec epoch 5/8:  45%|████▍     | 674/1500 [00:13<00:15, 52.70it/s, loss=1.08]
SASRec epoch 5/8:  45%|████▌     | 680/1500 [00:13<00:15, 52.97it/s, loss=1.08]
SASRec epoch 5/8:  46%|████▌     | 686/1500 [00:13<00:15, 53.18it/s, loss=1.08]
SASRec epoch 5/8:  46%|████▌     | 692/1500 [00:14<00:15, 52.26it/s, loss=1.08]
SASRec epoch 5/8:  47%|████▋     | 698/1500 [00:14<00:15, 52.97it/s, loss=1.08]
SASRec epoch 5/8:  47%|████▋     | 700/1500 [00:14<00:15, 52.97it/s, loss=1.08]
SASRec epoch 5/8:  47%|████▋     | 704/1500 [00:14<00:15, 52.26it/s, loss=1.08]
SASRec epoch 5/8:  47%|████▋     | 710/1500 [00:14<00:15, 51.63it/s, loss=1.08]
SASRec epoch 5/8:  48%|████▊     | 716/1500 [00:14<00:15, 50.07it/s, loss=1.08]
SASRec epoch 5/8:  48%|████▊     | 722/1500 [00:14<00:16, 46.98it/s, loss=1.08]
SASRec epoch 5/8:  48%|████▊     | 727/1500 [00:14<00:16, 46.25it/s, loss=1.08]
SASRec epoch 5/8:  49%|████▉     | 732/1500 [00:14<00:17, 44.99it/s, loss=1.08]
SASRec epoch 5/8:  49%|████▉     | 737/1500 [00:15<00:17, 44.46it/s, loss=1.08]
SASRec epoch 5/8:  49%|████▉     | 742/1500 [00:15<00:17, 44.07it/s, loss=1.08]
SASRec epoch 5/8:  50%|████▉     | 747/1500 [00:15<00:17, 42.15it/s, loss=1.08]
SASRec epoch 5/8:  50%|█████     | 750/1500 [00:15<00:17, 42.15it/s, loss=1.08]
SASRec epoch 5/8:  50%|█████     | 752/1500 [00:15<00:18, 39.39it/s, loss=1.08]
SASRec epoch 5/8:  50%|█████     | 756/1500 [00:15<00:18, 39.24it/s, loss=1.08]
SASRec epoch 5/8:  51%|█████     | 761/1500 [00:15<00:18, 40.09it/s, loss=1.08]
SASRec epoch 5/8:  51%|█████     | 766/1500 [00:15<00:17, 41.43it/s, loss=1.08]
SASRec epoch 5/8:  51%|█████▏    | 771/1500 [00:15<00:17, 42.29it/s, loss=1.08]
SASRec epoch 5/8:  52%|█████▏    | 776/1500 [00:16<00:16, 42.99it/s, loss=1.08]
SASRec epoch 5/8:  52%|█████▏    | 781/1500 [00:16<00:16, 42.96it/s, loss=1.08]
SASRec epoch 5/8:  52%|█████▏    | 786/1500 [00:16<00:16, 43.26it/s, loss=1.08]
SASRec epoch 5/8:  53%|█████▎    | 791/1500 [00:16<00:16, 42.91it/s, loss=1.08]
SASRec epoch 5/8:  53%|█████▎    | 796/1500 [00:16<00:16, 42.55it/s, loss=1.08]
SASRec epoch 5/8:  53%|█████▎    | 800/1500 [00:16<00:16, 42.55it/s, loss=1.08]
SASRec epoch 5/8:  53%|█████▎    | 801/1500 [00:16<00:17, 40.97it/s, loss=1.08]
SASRec epoch 5/8:  54%|█████▎    | 806/1500 [00:16<00:16, 41.67it/s, loss=1.08]
SASRec epoch 5/8:  54%|█████▍    | 811/1500 [00:16<00:16, 43.04it/s, loss=1.08]
SASRec epoch 5/8:  54%|█████▍    | 816/1500 [00:16<00:15, 43.62it/s, loss=1.08]
SASRec epoch 5/8:  55%|█████▍    | 821/1500 [00:17<00:15, 43.51it/s, loss=1.08]
SASRec epoch 5/8:  55%|█████▌    | 826/1500 [00:17<00:15, 43.43it/s, loss=1.08]
SASRec epoch 5/8:  55%|█████▌    | 831/1500 [00:17<00:15, 43.01it/s, loss=1.08]
SASRec epoch 5/8:  56%|█████▌    | 836/1500 [00:17<00:15, 43.36it/s, loss=1.08]
SASRec epoch 5/8:  56%|█████▌    | 841/1500 [00:17<00:16, 40.58it/s, loss=1.08]
SASRec epoch 5/8:  56%|█████▋    | 846/1500 [00:17<00:17, 38.12it/s, loss=1.08]
SASRec epoch 5/8:  57%|█████▋    | 850/1500 [00:17<00:17, 37.45it/s, loss=1.08]
SASRec epoch 5/8:  57%|█████▋    | 850/1500 [00:17<00:17, 37.45it/s, loss=1.07]
SASRec epoch 5/8:  57%|█████▋    | 854/1500 [00:17<00:17, 36.48it/s, loss=1.07]
SASRec epoch 5/8:  57%|█████▋    | 858/1500 [00:18<00:17, 36.29it/s, loss=1.07]
SASRec epoch 5/8:  58%|█████▊    | 863/1500 [00:18<00:16, 38.21it/s, loss=1.07]
SASRec epoch 5/8:  58%|█████▊    | 867/1500 [00:18<00:16, 37.39it/s, loss=1.07]
SASRec epoch 5/8:  58%|█████▊    | 872/1500 [00:18<00:16, 38.73it/s, loss=1.07]
SASRec epoch 5/8:  58%|█████▊    | 876/1500 [00:18<00:16, 37.37it/s, loss=1.07]
SASRec epoch 5/8:  59%|█████▊    | 880/1500 [00:18<00:17, 35.92it/s, loss=1.07]
SASRec epoch 5/8:  59%|█████▉    | 884/1500 [00:18<00:17, 35.62it/s, loss=1.07]
SASRec epoch 5/8:  59%|█████▉    | 890/1500 [00:18<00:15, 40.44it/s, loss=1.07]
SASRec epoch 5/8:  60%|█████▉    | 896/1500 [00:18<00:13, 44.56it/s, loss=1.07]
SASRec epoch 5/8:  60%|██████    | 900/1500 [00:19<00:13, 44.56it/s, loss=1.08]
SASRec epoch 5/8:  60%|██████    | 901/1500 [00:19<00:13, 45.09it/s, loss=1.08]
SASRec epoch 5/8:  60%|██████    | 907/1500 [00:19<00:12, 47.71it/s, loss=1.08]
SASRec epoch 5/8:  61%|██████    | 913/1500 [00:19<00:11, 49.26it/s, loss=1.08]
SASRec epoch 5/8:  61%|██████▏   | 919/1500 [00:19<00:11, 50.72it/s, loss=1.08]
SASRec epoch 5/8:  62%|██████▏   | 925/1500 [00:19<00:11, 52.12it/s, loss=1.08]
SASRec epoch 5/8:  62%|██████▏   | 931/1500 [00:19<00:10, 52.80it/s, loss=1.08]
SASRec epoch 5/8:  62%|██████▏   | 937/1500 [00:19<00:10, 52.63it/s, loss=1.08]
SASRec epoch 5/8:  63%|██████▎   | 943/1500 [00:19<00:11, 50.62it/s, loss=1.08]
SASRec epoch 5/8:  63%|██████▎   | 949/1500 [00:20<00:11, 47.89it/s, loss=1.08]
SASRec epoch 5/8:  63%|██████▎   | 950/1500 [00:20<00:11, 47.89it/s, loss=1.07]
SASRec epoch 5/8:  64%|██████▎   | 954/1500 [00:20<00:12, 42.78it/s, loss=1.07]
SASRec epoch 5/8:  64%|██████▍   | 959/1500 [00:20<00:13, 40.83it/s, loss=1.07]
SASRec epoch 5/8:  64%|██████▍   | 964/1500 [00:20<00:13, 40.41it/s, loss=1.07]
SASRec epoch 5/8:  65%|██████▍   | 969/1500 [00:20<00:13, 39.54it/s, loss=1.07]
SASRec epoch 5/8:  65%|██████▍   | 974/1500 [00:20<00:12, 40.49it/s, loss=1.07]
SASRec epoch 5/8:  65%|██████▌   | 980/1500 [00:20<00:11, 43.70it/s, loss=1.07]
SASRec epoch 5/8:  66%|██████▌   | 985/1500 [00:20<00:11, 44.64it/s, loss=1.07]
SASRec epoch 5/8:  66%|██████▌   | 991/1500 [00:21<00:10, 47.36it/s, loss=1.07]
SASRec epoch 5/8:  66%|██████▋   | 997/1500 [00:21<00:10, 49.39it/s, loss=1.07]
SASRec epoch 5/8:  67%|██████▋   | 1000/1500 [00:21<00:10, 49.39it/s, loss=1.07]
SASRec epoch 5/8:  67%|██████▋   | 1002/1500 [00:21<00:10, 49.12it/s, loss=1.07]
SASRec epoch 5/8:  67%|██████▋   | 1008/1500 [00:21<00:09, 50.31it/s, loss=1.07]
SASRec epoch 5/8:  68%|██████▊   | 1014/1500 [00:21<00:09, 51.34it/s, loss=1.07]
SASRec epoch 5/8:  68%|██████▊   | 1020/1500 [00:21<00:09, 52.20it/s, loss=1.07]
SASRec epoch 5/8:  68%|██████▊   | 1026/1500 [00:21<00:09, 52.65it/s, loss=1.07]
SASRec epoch 5/8:  69%|██████▉   | 1032/1500 [00:21<00:08, 52.98it/s, loss=1.07]
SASRec epoch 5/8:  69%|██████▉   | 1038/1500 [00:21<00:08, 51.72it/s, loss=1.07]
SASRec epoch 5/8:  70%|██████▉   | 1044/1500 [00:22<00:08, 52.02it/s, loss=1.07]
SASRec epoch 5/8:  70%|███████   | 1050/1500 [00:22<00:08, 52.54it/s, loss=1.07]
SASRec epoch 5/8:  70%|███████   | 1050/1500 [00:22<00:08, 52.54it/s, loss=1.08]
SASRec epoch 5/8:  70%|███████   | 1056/1500 [00:22<00:08, 52.71it/s, loss=1.08]
SASRec epoch 5/8:  71%|███████   | 1062/1500 [00:22<00:08, 53.46it/s, loss=1.08]
SASRec epoch 5/8:  71%|███████   | 1068/1500 [00:22<00:07, 54.00it/s, loss=1.08]
SASRec epoch 5/8:  72%|███████▏  | 1074/1500 [00:22<00:07, 54.53it/s, loss=1.08]
SASRec epoch 5/8:  72%|███████▏  | 1080/1500 [00:22<00:07, 54.43it/s, loss=1.08]
SASRec epoch 5/8:  72%|███████▏  | 1086/1500 [00:22<00:07, 54.35it/s, loss=1.08]
SASRec epoch 5/8:  73%|███████▎  | 1092/1500 [00:22<00:07, 53.89it/s, loss=1.08]
SASRec epoch 5/8:  73%|███████▎  | 1098/1500 [00:23<00:07, 53.57it/s, loss=1.08]
SASRec epoch 5/8:  73%|███████▎  | 1100/1500 [00:23<00:07, 53.57it/s, loss=1.06]
SASRec epoch 5/8:  74%|███████▎  | 1104/1500 [00:23<00:07, 52.17it/s, loss=1.06]
SASRec epoch 5/8:  74%|███████▍  | 1110/1500 [00:23<00:07, 52.87it/s, loss=1.06]
SASRec epoch 5/8:  74%|███████▍  | 1116/1500 [00:23<00:07, 52.68it/s, loss=1.06]
SASRec epoch 5/8:  75%|███████▍  | 1122/1500 [00:23<00:07, 52.93it/s, loss=1.06]
SASRec epoch 5/8:  75%|███████▌  | 1128/1500 [00:23<00:07, 53.11it/s, loss=1.06]
SASRec epoch 5/8:  76%|███████▌  | 1134/1500 [00:23<00:06, 53.50it/s, loss=1.06]
SASRec epoch 5/8:  76%|███████▌  | 1140/1500 [00:23<00:06, 53.72it/s, loss=1.06]
SASRec epoch 5/8:  76%|███████▋  | 1146/1500 [00:23<00:06, 53.82it/s, loss=1.06]
SASRec epoch 5/8:  77%|███████▋  | 1150/1500 [00:24<00:06, 53.82it/s, loss=1.06]
SASRec epoch 5/8:  77%|███████▋  | 1152/1500 [00:24<00:06, 50.06it/s, loss=1.06]
SASRec epoch 5/8:  77%|███████▋  | 1158/1500 [00:24<00:06, 50.88it/s, loss=1.06]
SASRec epoch 5/8:  78%|███████▊  | 1164/1500 [00:24<00:06, 51.36it/s, loss=1.06]
SASRec epoch 5/8:  78%|███████▊  | 1170/1500 [00:24<00:06, 51.52it/s, loss=1.06]
SASRec epoch 5/8:  78%|███████▊  | 1176/1500 [00:24<00:06, 52.22it/s, loss=1.06]
SASRec epoch 5/8:  79%|███████▉  | 1182/1500 [00:24<00:06, 52.34it/s, loss=1.06]
SASRec epoch 5/8:  79%|███████▉  | 1188/1500 [00:24<00:06, 51.99it/s, loss=1.06]
SASRec epoch 5/8:  80%|███████▉  | 1194/1500 [00:24<00:05, 52.26it/s, loss=1.06]
SASRec epoch 5/8:  80%|████████  | 1200/1500 [00:24<00:05, 52.54it/s, loss=1.06]
SASRec epoch 5/8:  80%|████████  | 1200/1500 [00:24<00:05, 52.54it/s, loss=1.06]
SASRec epoch 5/8:  80%|████████  | 1206/1500 [00:25<00:05, 49.28it/s, loss=1.06]
SASRec epoch 5/8:  81%|████████  | 1212/1500 [00:25<00:05, 50.28it/s, loss=1.06]
SASRec epoch 5/8:  81%|████████  | 1218/1500 [00:25<00:05, 50.45it/s, loss=1.06]
SASRec epoch 5/8:  82%|████████▏ | 1224/1500 [00:25<00:05, 51.39it/s, loss=1.06]
SASRec epoch 5/8:  82%|████████▏ | 1230/1500 [00:25<00:05, 51.87it/s, loss=1.06]
SASRec epoch 5/8:  82%|████████▏ | 1236/1500 [00:25<00:04, 52.87it/s, loss=1.06]
SASRec epoch 5/8:  83%|████████▎ | 1242/1500 [00:25<00:04, 53.11it/s, loss=1.06]
SASRec epoch 5/8:  83%|████████▎ | 1248/1500 [00:25<00:04, 53.59it/s, loss=1.06]
SASRec epoch 5/8:  83%|████████▎ | 1250/1500 [00:25<00:04, 53.59it/s, loss=1.06]
SASRec epoch 5/8:  84%|████████▎ | 1254/1500 [00:26<00:04, 51.72it/s, loss=1.06]
SASRec epoch 5/8:  84%|████████▍ | 1260/1500 [00:26<00:04, 50.50it/s, loss=1.06]

[SASRec] epoch 5/8 loss=1.0813

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 6/8:   0%|          | 4/1500 [00:00<00:44, 33.83it/s]
SASRec epoch 6/8:   1%|          | 8/1500 [00:00<00:40, 36.71it/s]
SASRec epoch 6/8:   1%|          | 13/1500 [00:00<00:36, 40.61it/s]
SASRec epoch 6/8:   1%|          | 18/1500 [00:00<00:35, 41.61it/s]
SASRec epoch 6/8:   2%|▏         | 23/1500 [00:00<00:36, 40.61it/s]
SASRec epoch 6/8:   2%|▏         | 28/1500 [00:00<00:36, 40.08it/s]
SASRec epoch 6/8:   2%|▏         | 33/1500 [00:00<00:36, 40.36it/s]
SASRec epoch 6/8:   3%|▎         | 38/1500 [00:00<00:35, 40.86it/s]
SASRec epoch 6/8:   3%|▎         | 43/1500 [00:01<00:35, 41.57it/s]
SASRec epoch 6/8:   3%|▎         | 48/1500 [00:01<00:37, 39.00it/s]
SASRec epoch 6/8:   3%|▎         | 50/1500 [00:01<00:37, 39.00it/s, loss=1.05]
SASRec epoch 6/8:   3%|▎         | 52/1500 [00:01<00:38, 37.96it/s, loss=1.05]
SASRec epoch 6/8:   4%|▎         | 56/1500 [00:01<00:38, 37.57it/s, loss=1.05]
SASRec epoch 6/8:   4%|▍         | 60/1500 [00:01<00:38, 37.86it/s, loss=1.05]
SASRec epoch 6/8:   4%|▍         | 65/1500 [00:01<00:36, 39.41it/s, loss=1.05]
SASRec epoch 6/8:   5%|▍         | 71/1500 [00:01<00:32, 43.81it/s, loss=1.05]
SASRec epoch 6/8:   5%|▌         | 77/1500 [00:01<00:30, 47.16it/s, loss=1.05]
SASRec epoch 6/8:   6%|▌         | 83/1500 [00:01<00:28, 49.00it/s, loss=1.05]
SASRec epoch 6/8:   6%|▌         | 89/1500 [00:02<00:27, 50.68it/s, loss=1.05]
SASRec epoch 6/8:   6%|▋         | 95/1500 [00:02<00:27, 51.26it/s, loss=1.05]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:02<00:27, 51.26it/s, loss=1.05]
SASRec epoch 6/8:   7%|▋         | 101/1500 [00:02<00:28, 49.96it/s, loss=1.05]
SASRec epoch 6/8:   7%|▋         | 107/1500 [00:02<00:27, 50.59it/s, loss=1.05]
SASRec epoch 6/8:   8%|▊         | 113/1500 [00:02<00:26, 51.63it/s, loss=1.05]
SASRec epoch 6/8:   8%|▊         | 119/1500 [00:02<00:26, 51.76it/s, loss=1.05]
SASRec epoch 6/8:   8%|▊         | 125/1500 [00:02<00:26, 52.01it/s, loss=1.05]
SASRec epoch 6/8:   9%|▊         | 131/1500 [00:02<00:25, 52.82it/s, loss=1.05]
SASRec epoch 6/8:   9%|▉         | 137/1500 [00:03<00:25, 53.38it/s, loss=1.05]
SASRec epoch 6/8:  10%|▉         | 143/1500 [00:03<00:25, 53.66it/s, loss=1.05]
SASRec epoch 6/8:  10%|▉         | 149/1500 [00:03<00:25, 53.97it/s, loss=1.05]
SASRec epoch 6/8:  10%|█         | 150/1500 [00:03<00:25, 53.97it/s, loss=1.06]
SASRec epoch 6/8:  10%|█         | 155/1500 [00:03<00:26, 50.68it/s, loss=1.06]
SASRec epoch 6/8:  11%|█         | 161/1500 [00:03<00:25, 51.52it/s, loss=1.06]
SASRec epoch 6/8:  11%|█         | 167/1500 [00:03<00:25, 52.00it/s, loss=1.06]
SASRec epoch 6/8:  12%|█▏        | 173/1500 [00:03<00:25, 51.89it/s, loss=1.06]
SASRec epoch 6/8:  12%|█▏        | 179/1500 [00:03<00:25, 52.24it/s, loss=1.06]
SASRec epoch 6/8:  12%|█▏        | 185/1500 [00:03<00:24, 53.00it/s, loss=1.06]
SASRec epoch 6/8:  13%|█▎        | 191/1500 [00:04<00:24, 53.37it/s, loss=1.06]
SASRec epoch 6/8:  13%|█▎        | 197/1500 [00:04<00:24, 53.31it/s, loss=1.06]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:04<00:24, 53.31it/s, loss=1.03]
SASRec epoch 6/8:  14%|█▎        | 203/1500 [00:04<00:24, 51.99it/s, loss=1.03]
SASRec epoch 6/8:  14%|█▍        | 209/1500 [00:04<00:25, 50.74it/s, loss=1.03]
SASRec epoch 6/8:  14%|█▍        | 215/1500 [00:04<00:25, 50.97it/s, loss=1.03]
SASRec epoch 6/8:  15%|█▍        | 221/1500 [00:04<00:25, 50.56it/s, loss=1.03]
SASRec epoch 6/8:  15%|█▌        | 227/1500 [00:04<00:24, 51.04it/s, loss=1.03]
SASRec epoch 6/8:  16%|█▌        | 233/1500 [00:04<00:24, 51.33it/s, loss=1.03]
SASRec epoch 6/8:  16%|█▌        | 239/1500 [00:04<00:24, 51.41it/s, loss=1.03]
SASRec epoch 6/8:  16%|█▋        | 245/1500 [00:05<00:24, 51.90it/s, loss=1.03]
SASRec epoch 6/8:  17%|█▋        | 250/1500 [00:05<00:24, 51.90it/s, loss=1.04]
SASRec epoch 6/8:  17%|█▋        | 251/1500 [00:05<00:24, 51.14it/s, loss=1.04]
SASRec epoch 6/8:  17%|█▋        | 257/1500 [00:05<00:24, 51.51it/s, loss=1.04]
SASRec epoch 6/8:  18%|█▊        | 263/1500 [00:05<00:24, 49.94it/s, loss=1.04]
SASRec epoch 6/8:  18%|█▊        | 269/1500 [00:05<00:24, 50.64it/s, loss=1.04]
SASRec epoch 6/8:  18%|█▊        | 275/1500 [00:05<00:23, 51.36it/s, loss=1.04]
SASRec epoch 6/8:  19%|█▊        | 281/1500 [00:05<00:23, 51.79it/s, loss=1.04]
SASRec epoch 6/8:  19%|█▉        | 287/1500 [00:05<00:23, 52.05it/s, loss=1.04]
SASRec epoch 6/8:  20%|█▉        | 293/1500 [00:06<00:23, 51.83it/s, loss=1.04]
SASRec epoch 6/8:  20%|█▉        | 299/1500 [00:06<00:23, 52.18it/s, loss=1.04]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:06<00:22, 52.18it/s, loss=1.03]
SASRec epoch 6/8:  20%|██        | 305/1500 [00:06<00:23, 51.48it/s, loss=1.03]
SASRec epoch 6/8:  21%|██        | 311/1500 [00:06<00:22, 51.76it/s, loss=1.03]
SASRec epoch 6/8:  21%|██        | 317/1500 [00:06<00:23, 50.18it/s, loss=1.03]
SASRec epoch 6/8:  22%|██▏       | 323/1500 [00:06<00:23, 50.46it/s, loss=1.03]
SASRec epoch 6/8:  22%|██▏       | 329/1500 [00:06<00:22, 51.10it/s, loss=1.03]
SASRec epoch 6/8:  22%|██▏       | 335/1500 [00:06<00:22, 51.70it/s, loss=1.03]
SASRec epoch 6/8:  23%|██▎       | 341/1500 [00:06<00:22, 52.16it/s, loss=1.03]
SASRec epoch 6/8:  23%|██▎       | 347/1500 [00:07<00:21, 53.00it/s, loss=1.03]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:07<00:21, 53.00it/s, loss=1.03]
SASRec epoch 6/8:  24%|██▎       | 353/1500 [00:07<00:21, 52.38it/s, loss=1.03]
SASRec epoch 6/8:  24%|██▍       | 359/1500 [00:07<00:21, 52.41it/s, loss=1.03]
SASRec epoch 6/8:  24%|██▍       | 365/1500 [00:07<00:21, 52.73it/s, loss=1.03]
SASRec epoch 6/8:  25%|██▍       | 371/1500 [00:07<00:22, 50.22it/s, loss=1.03]
SASRec epoch 6/8:  25%|██▌       | 377/1500 [00:07<00:21, 51.28it/s, loss=1.03]
SASRec epoch 6/8:  26%|██▌       | 383/1500 [00:07<00:21, 51.65it/s, loss=1.03]
SASRec epoch 6/8:  26%|██▌       | 389/1500 [00:07<00:21, 52.17it/s, loss=1.03]
SASRec epoch 6/8:  26%|██▋       | 395/1500 [00:07<00:20, 52.64it/s, loss=1.03]
SASRec epoch 6/8:  27%|██▋       | 400/1500 [00:08<00:20, 52.64it/s, loss=1.03]
SASRec epoch 6/8:  27%|██▋       | 401/1500 [00:08<00:21, 51.40it/s, loss=1.03]
SASRec epoch 6/8:  27%|██▋       | 407/1500 [00:08<00:21, 51.93it/s, loss=1.03]
SASRec epoch 6/8:  28%|██▊       | 413/1500 [00:08<00:20, 52.11it/s, loss=1.03]
SASRec epoch 6/8:  28%|██▊       | 419/1500 [00:08<00:20, 52.94it/s, loss=1.03]
SASRec epoch 6/8:  28%|██▊       | 425/1500 [00:08<00:20, 51.53it/s, loss=1.03]
SASRec epoch 6/8:  29%|██▊       | 431/1500 [00:08<00:20, 51.98it/s, loss=1.03]
SASRec epoch 6/8:  29%|██▉       | 437/1500 [00:08<00:20, 52.43it/s, loss=1.03]
SASRec epoch 6/8:  30%|██▉       | 443/1500 [00:08<00:20, 52.59it/s, loss=1.03]
SASRec epoch 6/8:  30%|██▉       | 449/1500 [00:09<00:19, 52.60it/s, loss=1.03]
SASRec epoch 6/8:  30%|███       | 450/1500 [00:09<00:19, 52.60it/s, loss=1.01]
SASRec epoch 6/8:  30%|███       | 455/1500 [00:09<00:20, 51.34it/s, loss=1.01]
SASRec epoch 6/8:  31%|███       | 461/1500 [00:09<00:19, 52.38it/s, loss=1.01]
SASRec epoch 6/8:  31%|███       | 467/1500 [00:09<00:19, 52.73it/s, loss=1.01]
SASRec epoch 6/8:  32%|███▏      | 473/1500 [00:09<00:19, 52.62it/s, loss=1.01]
SASRec epoch 6/8:  32%|███▏      | 479/1500 [00:09<00:19, 51.27it/s, loss=1.01]
SASRec epoch 6/8:  32%|███▏      | 485/1500 [00:09<00:19, 51.59it/s, loss=1.01]
SASRec epoch 6/8:  33%|███▎      | 491/1500 [00:09<00:19, 52.27it/s, loss=1.01]
SASRec epoch 6/8:  33%|███▎      | 497/1500 [00:09<00:19, 52.79it/s, loss=1.01]
SASRec epoch 6/8:  33%|███▎      | 500/1500 [00:10<00:18, 52.79it/s, loss=1.03]
SASRec epoch 6/8:  34%|███▎      | 503/1500 [00:10<00:19, 51.40it/s, loss=1.03]
SASRec epoch 6/8:  34%|███▍      | 509/1500 [00:10<00:18, 52.40it/s, loss=1.03]
SASRec epoch 6/8:  34%|███▍      | 515/1500 [00:10<00:18, 53.22it/s, loss=1.03]
SASRec epoch 6/8:  35%|███▍      | 521/1500 [00:10<00:18, 53.78it/s, loss=1.03]
SASRec epoch 6/8:  35%|███▌      | 527/1500 [00:10<00:17, 54.07it/s, loss=1.03]
SASRec epoch 6/8:  36%|███▌      | 533/1500 [00:10<00:18, 52.77it/s, loss=1.03]
SASRec epoch 6/8:  36%|███▌      | 539/1500 [00:10<00:18, 52.36it/s, loss=1.03]
SASRec epoch 6/8:  36%|███▋      | 545/1500 [00:10<00:18, 52.39it/s, loss=1.03]
SASRec epoch 6/8:  37%|███▋      | 550/1500 [00:10<00:18, 52.39it/s, loss=1.02]
SASRec epoch 6/8:  37%|███▋      | 551/1500 [00:10<00:18, 50.55it/s, loss=1.02]
SASRec epoch 6/8:  37%|███▋      | 557/1500 [00:11<00:18, 50.83it/s, loss=1.02]
SASRec epoch 6/8:  38%|███▊      | 563/1500 [00:11<00:18, 51.58it/s, loss=1.02]
SASRec epoch 6/8:  38%|███▊      | 569/1500 [00:11<00:17, 52.07it/s, loss=1.02]
SASRec epoch 6/8:  38%|███▊      | 575/1500 [00:11<00:17, 52.75it/s, loss=1.02]
SASRec epoch 6/8:  39%|███▊      | 581/1500 [00:11<00:17, 52.64it/s, loss=1.02]
SASRec epoch 6/8:  39%|███▉      | 587/1500 [00:11<00:19, 47.29it/s, loss=1.02]
SASRec epoch 6/8:  39%|███▉      | 592/1500 [00:11<00:20, 44.73it/s, loss=1.02]
SASRec epoch 6/8:  40%|███▉      | 597/1500 [00:11<00:21, 42.28it/s, loss=1.02]
SASRec epoch 6/8:  40%|████      | 600/1500 [00:12<00:21, 42.28it/s, loss=1.02]
SASRec epoch 6/8:  40%|████      | 602/1500 [00:12<00:21, 41.16it/s, loss=1.02]
SASRec epoch 6/8:  40%|████      | 607/1500 [00:12<00:21, 41.26it/s, loss=1.02]
SASRec epoch 6/8:  41%|████      | 612/1500 [00:12<00:21, 40.86it/s, loss=1.02]
SASRec epoch 6/8:  41%|████      | 617/1500 [00:12<00:21, 41.54it/s, loss=1.02]
SASRec epoch 6/8:  41%|████▏     | 622/1500 [00:12<00:20, 41.92it/s, loss=1.02]
SASRec epoch 6/8:  42%|████▏     | 627/1500 [00:12<00:21, 40.43it/s, loss=1.02]
SASRec epoch 6/8:  42%|████▏     | 632/1500 [00:12<00:21, 41.18it/s, loss=1.02]
SASRec epoch 6/8:  42%|████▏     | 637/1500 [00:12<00:20, 42.80it/s, loss=1.02]
SASRec epoch 6/8:  43%|████▎     | 642/1500 [00:13<00:19, 43.81it/s, loss=1.02]
SASRec epoch 6/8:  43%|████▎     | 647/1500 [00:13<00:19, 44.37it/s, loss=1.02]
SASRec epoch 6/8:  43%|████▎     | 650/1500 [00:13<00:19, 44.37it/s, loss=1.02]
SASRec epoch 6/8:  43%|████▎     | 652/1500 [00:13<00:19, 44.42it/s, loss=1.02]
SASRec epoch 6/8:  44%|████▍     | 657/1500 [00:13<00:19, 44.06it/s, loss=1.02]
SASRec epoch 6/8:  44%|████▍     | 662/1500 [00:13<00:19, 43.82it/s, loss=1.02]
SASRec epoch 6/8:  44%|████▍     | 667/1500 [00:13<00:18, 44.23it/s, loss=1.02]
SASRec epoch 6/8:  45%|████▍     | 672/1500 [00:13<00:19, 42.61it/s, loss=1.02]
SASRec epoch 6/8:  45%|████▌     | 677/1500 [00:13<00:19, 41.74it/s, loss=1.02]
SASRec epoch 6/8:  45%|████▌     | 682/1500 [00:13<00:19, 42.10it/s, loss=1.02]
SASRec epoch 6/8:  46%|████▌     | 687/1500 [00:14<00:19, 42.20it/s, loss=1.02]
SASRec epoch 6/8:  46%|████▌     | 692/1500 [00:14<00:18, 42.74it/s, loss=1.02]
SASRec epoch 6/8:  46%|████▋     | 697/1500 [00:14<00:18, 43.03it/s, loss=1.02]
SASRec epoch 6/8:  47%|████▋     | 700/1500 [00:14<00:18, 43.03it/s, loss=1.02]
SASRec epoch 6/8:  47%|████▋     | 702/1500 [00:14<00:19, 40.43it/s, loss=1.02]
SASRec epoch 6/8:  47%|████▋     | 707/1500 [00:14<00:19, 39.76it/s, loss=1.02]
SASRec epoch 6/8:  47%|████▋     | 712/1500 [00:14<00:19, 39.85it/s, loss=1.02]
SASRec epoch 6/8:  48%|████▊     | 717/1500 [00:14<00:20, 37.89it/s, loss=1.02]
SASRec epoch 6/8:  48%|████▊     | 721/1500 [00:14<00:20, 37.14it/s, loss=1.02]
SASRec epoch 6/8:  48%|████▊     | 726/1500 [00:15<00:19, 38.88it/s, loss=1.02]
SASRec epoch 6/8:  49%|████▊     | 730/1500 [00:15<00:20, 37.62it/s, loss=1.02]
SASRec epoch 6/8:  49%|████▉     | 734/1500 [00:15<00:20, 37.33it/s, loss=1.02]
SASRec epoch 6/8:  49%|████▉     | 738/1500 [00:15<00:20, 37.99it/s, loss=1.02]
SASRec epoch 6/8:  49%|████▉     | 742/1500 [00:15<00:19, 38.36it/s, loss=1.02]
SASRec epoch 6/8:  50%|████▉     | 746/1500 [00:15<00:19, 38.42it/s, loss=1.02]
SASRec epoch 6/8:  50%|█████     | 750/1500 [00:15<00:19, 38.42it/s, loss=1.02]
SASRec epoch 6/8:  50%|█████     | 751/1500 [00:15<00:18, 40.07it/s, loss=1.02]
SASRec epoch 6/8:  50%|█████     | 757/1500 [00:15<00:16, 44.42it/s, loss=1.02]
SASRec epoch 6/8:  51%|█████     | 762/1500 [00:15<00:16, 44.66it/s, loss=1.02]
SASRec epoch 6/8:  51%|█████     | 768/1500 [00:16<00:15, 47.42it/s, loss=1.02]
SASRec epoch 6/8:  52%|█████▏    | 774/1500 [00:16<00:14, 49.47it/s, loss=1.02]
SASRec epoch 6/8:  52%|█████▏    | 780/1500 [00:16<00:14, 51.15it/s, loss=1.02]
SASRec epoch 6/8:  52%|█████▏    | 786/1500 [00:16<00:13, 52.26it/s, loss=1.02]
SASRec epoch 6/8:  53%|█████▎    | 792/1500 [00:16<00:13, 53.04it/s, loss=1.02]
SASRec epoch 6/8:  53%|█████▎    | 798/1500 [00:16<00:13, 53.04it/s, loss=1.02]
SASRec epoch 6/8:  53%|█████▎    | 800/1500 [00:16<00:13, 53.04it/s, loss=1.02]
SASRec epoch 6/8:  54%|█████▎    | 804/1500 [00:16<00:13, 52.16it/s, loss=1.02]
SASRec epoch 6/8:  54%|█████▍    | 810/1500 [00:16<00:13, 52.53it/s, loss=1.02]
SASRec epoch 6/8:  54%|█████▍    | 816/1500 [00:16<00:13, 51.13it/s, loss=1.02]
SASRec epoch 6/8:  55%|█████▍    | 822/1500 [00:17<00:13, 51.07it/s, loss=1.02]
SASRec epoch 6/8:  55%|█████▌    | 828/1500 [00:17<00:13, 51.32it/s, loss=1.02]
SASRec epoch 6/8:  56%|█████▌    | 834/1500 [00:17<00:12, 51.85it/s, loss=1.02]
SASRec epoch 6/8:  56%|█████▌    | 840/1500 [00:17<00:12, 52.44it/s, loss=1.02]
SASRec epoch 6/8:  56%|█████▋    | 846/1500 [00:17<00:12, 52.74it/s, loss=1.02]
SASRec epoch 6/8:  57%|█████▋    | 850/1500 [00:17<00:12, 52.74it/s, loss=1]
SASRec epoch 6/8:  57%|█████▋    | 852/1500 [00:17<00:12, 51.55it/s, loss=1]
SASRec epoch 6/8:  57%|█████▋    | 858/1500 [00:17<00:12, 51.31it/s, loss=1]
SASRec epoch 6/8:  58%|█████▊    | 864/1500 [00:17<00:12, 51.79it/s, loss=1]
SASRec epoch 6/8:  58%|█████▊    | 870/1500 [00:18<00:12, 49.98it/s, loss=1]
SASRec epoch 6/8:  58%|█████▊    | 876/1500 [00:18<00:12, 50.80it/s, loss=1]
SASRec epoch 6/8:  59%|█████▉    | 882/1500 [00:18<00:11, 51.71it/s, loss=1]
SASRec epoch 6/8:  59%|█████▉    | 888/1500 [00:18<00:11, 52.11it/s, loss=1]
SASRec epoch 6/8:  60%|█████▉    | 894/1500 [00:18<00:11, 53.03it/s, loss=1]
SASRec epoch 6/8:  60%|██████    | 900/1500 [00:18<00:11, 52.52it/s, loss=1]
SASRec epoch 6/8:  60%|██████    | 900/1500 [00:18<00:11, 52.52it/s, loss=1]
SASRec epoch 6/8:  60%|██████    | 906/1500 [00:18<00:11, 50.52it/s, loss=1]
SASRec epoch 6/8:  61%|██████    | 912/1500 [00:18<00:11, 51.08it/s, loss=1]
SASRec epoch 6/8:  61%|██████    | 918/1500 [00:18<00:11, 51.47it/s, loss=1]
SASRec epoch 6/8:  62%|██████▏   | 924/1500 [00:19<00:11, 50.32it/s, loss=1]
SASRec epoch 6/8:  62%|██████▏   | 930/1500 [00:19<00:11, 50.69it/s, loss=1]
SASRec epoch 6/8:  62%|██████▏   | 936/1500 [00:19<00:10, 51.54it/s, loss=1]
SASRec epoch 6/8:  63%|██████▎   | 942/1500 [00:19<00:10, 52.06it/s, loss=1]
SASRec epoch 6/8:  63%|██████▎   | 948/1500 [00:19<00:10, 51.96it/s, loss=1]
SASRec epoch 6/8:  63%|██████▎   | 950/1500 [00:19<00:10, 51.96it/s, loss=0.997]
SASRec epoch 6/8:  64%|██████▎   | 954/1500 [00:19<00:10, 51.16it/s, loss=0.997]
SASRec epoch 6/8:  64%|██████▍   | 960/1500 [00:19<00:10, 51.60it/s, loss=0.997]
SASRec epoch 6/8:  64%|██████▍   | 966/1500 [00:19<00:10, 51.49it/s, loss=0.997]
SASRec epoch 6/8:  65%|██████▍   | 972/1500 [00:20<00:10, 52.25it/s, loss=0.997]
SASRec epoch 6/8:  65%|██████▌   | 978/1500 [00:20<00:10, 50.62it/s, loss=0.997]
SASRec epoch 6/8:  66%|██████▌   | 984/1500 [00:20<00:10, 51.42it/s, loss=0.997]
SASRec epoch 6/8:  66%|██████▌   | 990/1500 [00:20<00:09, 51.83it/s, loss=0.997]
SASRec epoch 6/8:  66%|██████▋   | 996/1500 [00:20<00:09, 52.46it/s, loss=0.997]
SASRec epoch 6/8:  67%|██████▋   | 1000/1500 [00:20<00:09, 52.46it/s, loss=1]
SASRec epoch 6/8:  67%|██████▋   | 1002/1500 [00:20<00:09, 51.54it/s, loss=1]
SASRec epoch 6/8:  67%|██████▋   | 1008/1500 [00:20<00:09, 51.43it/s, loss=1]
SASRec epoch 6/8:  68%|██████▊   | 1014/1500 [00:20<00:09, 51.71it/s, loss=1]
SASRec epoch 6/8:  68%|██████▊   | 1020/1500 [00:20<00:09, 51.98it/s, loss=1]
SASRec epoch 6/8:  68%|██████▊   | 1026/1500 [00:21<00:09, 52.17it/s, loss=1]
SASRec epoch 6/8:  69%|██████▉   | 1032/1500 [00:21<00:09, 50.36it/s, loss=1]
SASRec epoch 6/8:  69%|██████▉   | 1038/1500 [00:21<00:09, 51.23it/s, loss=1]
SASRec epoch 6/8:  70%|██████▉   | 1044/1500 [00:21<00:08, 51.65it/s, loss=1]
SASRec epoch 6/8:  70%|███████   | 1050/1500 [00:21<00:08, 51.93it/s, loss=1]
SASRec epoch 6/8:  70%|███████   | 1050/1500 [00:21<00:08, 51.93it/s, loss=0.99]
SASRec epoch 6/8:  70%|███████   | 1056/1500 [00:21<00:08, 50.56it/s, loss=0.99]
SASRec epoch 6/8:  71%|███████   | 1062/1500 [00:21<00:08, 51.28it/s, loss=0.99]
SASRec epoch 6/8:  71%|███████   | 1068/1500 [00:21<00:08, 51.89it/s, loss=0.99]
SASRec epoch 6/8:  72%|███████▏  | 1074/1500 [00:21<00:08, 52.17it/s, loss=0.99]
SASRec epoch 6/8:  72%|███████▏  | 1080/1500 [00:22<00:08, 52.14it/s, loss=0.99]
SASRec epoch 6/8:  72%|███████▏  | 1086/1500 [00:22<00:08, 50.46it/s, loss=0.99]
SASRec epoch 6/8:  73%|███████▎  | 1092/1500 [00:22<00:07, 51.10it/s, loss=0.99]
SASRec epoch 6/8:  73%|███████▎  | 1098/1500 [00:22<00:07, 51.64it/s, loss=0.99]
SASRec epoch 6/8:  73%|███████▎  | 1100/1500 [00:22<00:07, 51.64it/s, loss=1]
SASRec epoch 6/8:  74%|███████▎  | 1104/1500 [00:22<00:07, 50.82it/s, loss=1]
SASRec epoch 6/8:  74%|███████▍  | 1110/1500 [00:22<00:07, 51.04it/s, loss=1]
SASRec epoch 6/8:  74%|███████▍  | 1116/1500 [00:22<00:07, 51.45it/s, loss=1]
SASRec epoch 6/8:  75%|███████▍  | 1122/1500 [00:22<00:07, 52.12it/s, loss=1]
SASRec epoch 6/8:  75%|███████▌  | 1128/1500 [00:23<00:07, 52.31it/s, loss=1]
SASRec epoch 6/8:  76%|███████▌  | 1134/1500 [00:23<00:06, 52.32it/s, loss=1]
SASRec epoch 6/8:  76%|███████▌  | 1140/1500 [00:23<00:07, 50.08it/s, loss=1]
SASRec epoch 6/8:  76%|███████▋  | 1146/1500 [00:23<00:07, 50.52it/s, loss=1]
SASRec epoch 6/8:  77%|███████▋  | 1150/1500 [00:23<00:06, 50.52it/s, loss=0.989]
SASRec epoch 6/8:  77%|███████▋  | 1152/1500 [00:23<00:07, 49.70it/s, loss=0.989]
SASRec epoch 6/8:  77%|███████▋  | 1157/1500 [00:23<00:06, 49.78it/s, loss=0.989]
SASRec epoch 6/8:  77%|███████▋  | 1162/1500 [00:23<00:06, 49.50it/s, loss=0.989]
SASRec epoch 6/8:  78%|███████▊  | 1168/1500 [00:23<00:06, 50.21it/s, loss=0.989]
SASRec epoch 6/8:  78%|███████▊  | 1174/1500 [00:23<00:06, 50.82it/s, loss=0.989]
SASRec epoch 6/8:  79%|███████▊  | 1180/1500 [00:24<00:06, 50.80it/s, loss=0.989]
SASRec epoch 6/8:  79%|███████▉  | 1186/1500 [00:24<00:06, 51.23it/s, loss=0.989]
SASRec epoch 6/8:  79%|███████▉  | 1192/1500 [00:24<00:06, 49.87it/s, loss=0.989]
SASRec epoch 6/8:  80%|███████▉  | 1198/1500 [00:24<00:05, 51.02it/s, loss=0.989]
SASRec epoch 6/8:  80%|████████  | 1200/1500 [00:24<00:05, 51.02it/s, loss=0.994]
SASRec epoch 6/8:  80%|████████  | 1204/1500 [00:24<00:05, 50.77it/s, loss=0.994]
SASRec epoch 6/8:  81%|████████  | 1210/1500 [00:24<00:05, 51.35it/s, loss=0.994]
SASRec epoch 6/8:  81%|████████  | 1216/1500 [00:24<00:05, 51.86it/s, loss=0.994]
SASRec epoch 6/8:  81%|████████▏ | 1222/1500 [00:24<00:05, 52.33it/s, loss=0.994]
SASRec epoch 6/8:  82%|████████▏ | 1228/1500 [00:25<00:05, 52.68it/s, loss=0.994]
SASRec epoch 6/8:  82%|████████▏ | 1234/1500 [00:25<00:05, 52.83it/s, loss=0.994]
SASRec epoch 6/8:  83%|████████▎ | 1240/1500 [00:25<00:04, 53.19it/s, loss=0.994]
SASRec epoch 6/8:  83%|████████▎ | 1246/1500 [00:25<00:04, 51.67it/s, loss=0.994]
SASRec epoch 6/8:  83%|████████▎ | 1250/1500 [00:25<00:04, 51.67it/s, loss=0.995]
SASRec epoch 6/8:  83%|████████▎ | 1252/1500 [00:25<00:04, 50.67it/s, loss=0.995]
SASRec epoch 6/8:  84%|████████▍ | 1258/1500 [00:25<00:04, 51.70it/s, loss=0.995]
SASRec epoch 6/8:  84%|████████▍ | 1264/1500 [00:25<00:04, 51.12it/s, loss=0.995]
SASRec epoch 6/8:  85%|████████▍ | 1270/1500 [00:25<00:04, 46.39it/s, loss=0.995]
SASRec epoch 6/8:  85%|████████▌ | 1275/1500 [00:25<00:04, 45.90it/s, loss=0.995]
SASRec epoch 6/8:  85%|████████▌ | 1280/1500 [00:26<00:04, 44.14it/s, loss=0.995]
SASRec epoch 6/8:  86%|████████▌ | 1285/1500 [00:26<00:04, 43.21it/s, loss=0.995]
SASRec epoch 6/8:  86%|████████▌ | 1290/1500 [00:26<00:05, 39.91it/s, loss=0.995]

[SASRec] epoch 6/8 loss=1.0102

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 7/8:   0%|          | 6/1500 [00:00<00:28, 52.74it/s]
SASRec epoch 7/8:   1%|          | 12/1500 [00:00<00:28, 52.89it/s]
SASRec epoch 7/8:   1%|          | 18/1500 [00:00<00:28, 52.51it/s]
SASRec epoch 7/8:   2%|▏         | 24/1500 [00:00<00:29, 50.58it/s]
SASRec epoch 7/8:   2%|▏         | 30/1500 [00:00<00:29, 50.20it/s]
SASRec epoch 7/8:   2%|▏         | 36/1500 [00:00<00:28, 50.85it/s]
SASRec epoch 7/8:   3%|▎         | 42/1500 [00:00<00:28, 50.73it/s]
SASRec epoch 7/8:   3%|▎         | 48/1500 [00:00<00:28, 51.54it/s]
SASRec epoch 7/8:   3%|▎         | 50/1500 [00:00<00:28, 51.54it/s, loss=0.973]
SASRec epoch 7/8:   4%|▎         | 54/1500 [00:01<00:28, 50.53it/s, loss=0.973]
SASRec epoch 7/8:   4%|▍         | 60/1500 [00:01<00:27, 51.46it/s, loss=0.973]
SASRec epoch 7/8:   4%|▍         | 66/1500 [00:01<00:27, 51.71it/s, loss=0.973]
SASRec epoch 7/8:   5%|▍         | 72/1500 [00:01<00:27, 51.25it/s, loss=0.973]
SASRec epoch 7/8:   5%|▌         | 78/1500 [00:01<00:28, 49.95it/s, loss=0.973]
SASRec epoch 7/8:   6%|▌         | 84/1500 [00:01<00:27, 50.77it/s, loss=0.973]
SASRec epoch 7/8:   6%|▌         | 90/1500 [00:01<00:27, 51.20it/s, loss=0.973]
SASRec epoch 7/8:   6%|▋         | 96/1500 [00:01<00:27, 51.81it/s, loss=0.973]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:01<00:27, 51.81it/s, loss=0.958]
SASRec epoch 7/8:   7%|▋         | 102/1500 [00:01<00:27, 50.64it/s, loss=0.958]
SASRec epoch 7/8:   7%|▋         | 108/1500 [00:02<00:26, 51.66it/s, loss=0.958]
SASRec epoch 7/8:   8%|▊         | 114/1500 [00:02<00:26, 51.87it/s, loss=0.958]
SASRec epoch 7/8:   8%|▊         | 120/1500 [00:02<00:27, 51.03it/s, loss=0.958]
SASRec epoch 7/8:   8%|▊         | 126/1500 [00:02<00:26, 51.43it/s, loss=0.958]
SASRec epoch 7/8:   9%|▉         | 132/1500 [00:02<00:27, 50.25it/s, loss=0.958]
SASRec epoch 7/8:   9%|▉         | 138/1500 [00:02<00:26, 50.99it/s, loss=0.958]
SASRec epoch 7/8:  10%|▉         | 144/1500 [00:02<00:26, 51.16it/s, loss=0.958]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:02<00:26, 51.72it/s, loss=0.958]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:02<00:26, 51.72it/s, loss=0.957]
SASRec epoch 7/8:  10%|█         | 156/1500 [00:03<00:26, 50.87it/s, loss=0.957]
SASRec epoch 7/8:  11%|█         | 162/1500 [00:03<00:26, 51.02it/s, loss=0.957]
SASRec epoch 7/8:  11%|█         | 168/1500 [00:03<00:26, 51.02it/s, loss=0.957]
SASRec epoch 7/8:  12%|█▏        | 174/1500 [00:03<00:26, 50.87it/s, loss=0.957]
SASRec epoch 7/8:  12%|█▏        | 180/1500 [00:03<00:25, 51.44it/s, loss=0.957]
SASRec epoch 7/8:  12%|█▏        | 186/1500 [00:03<00:26, 50.02it/s, loss=0.957]
SASRec epoch 7/8:  13%|█▎        | 192/1500 [00:03<00:25, 50.31it/s, loss=0.957]
SASRec epoch 7/8:  13%|█▎        | 198/1500 [00:03<00:25, 51.09it/s, loss=0.957]
SASRec epoch 7/8:  13%|█▎        | 200/1500 [00:03<00:25, 51.09it/s, loss=0.965]
SASRec epoch 7/8:  14%|█▎        | 204/1500 [00:04<00:25, 50.32it/s, loss=0.965]
SASRec epoch 7/8:  14%|█▍        | 210/1500 [00:04<00:27, 47.75it/s, loss=0.965]
SASRec epoch 7/8:  14%|█▍        | 215/1500 [00:04<00:45, 28.40it/s, loss=0.965]
SASRec epoch 7/8:  15%|█▍        | 219/1500 [00:04<00:59, 21.48it/s, loss=0.965]
SASRec epoch 7/8:  15%|█▍        | 223/1500 [00:04<00:53, 24.09it/s, loss=0.965]
SASRec epoch 7/8:  15%|█▌        | 229/1500 [00:05<00:42, 29.73it/s, loss=0.965]
SASRec epoch 7/8:  16%|█▌        | 235/1500 [00:05<00:36, 34.72it/s, loss=0.965]
SASRec epoch 7/8:  16%|█▌        | 241/1500 [00:05<00:32, 38.98it/s, loss=0.965]
SASRec epoch 7/8:  16%|█▋        | 247/1500 [00:05<00:29, 42.74it/s, loss=0.965]
SASRec epoch 7/8:  17%|█▋        | 250/1500 [00:05<00:29, 42.74it/s, loss=0.954]
SASRec epoch 7/8:  17%|█▋        | 252/1500 [00:05<00:28, 44.08it/s, loss=0.954]
SASRec epoch 7/8:  17%|█▋        | 258/1500 [00:05<00:26, 47.12it/s, loss=0.954]
SASRec epoch 7/8:  18%|█▊        | 264/1500 [00:05<00:26, 47.20it/s, loss=0.954]
SASRec epoch 7/8:  18%|█▊        | 270/1500 [00:05<00:25, 48.78it/s, loss=0.954]
SASRec epoch 7/8:  18%|█▊        | 276/1500 [00:05<00:24, 50.58it/s, loss=0.954]
SASRec epoch 7/8:  19%|█▉        | 282/1500 [00:06<00:23, 51.88it/s, loss=0.954]
SASRec epoch 7/8:  19%|█▉        | 288/1500 [00:06<00:23, 52.46it/s, loss=0.954]
SASRec epoch 7/8:  20%|█▉        | 294/1500 [00:06<00:22, 53.27it/s, loss=0.954]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:06<00:22, 53.00it/s, loss=0.954]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:06<00:22, 53.00it/s, loss=0.946]
SASRec epoch 7/8:  20%|██        | 306/1500 [00:06<00:22, 52.59it/s, loss=0.946]
SASRec epoch 7/8:  21%|██        | 312/1500 [00:06<00:22, 52.82it/s, loss=0.946]
SASRec epoch 7/8:  21%|██        | 318/1500 [00:06<00:23, 50.95it/s, loss=0.946]
SASRec epoch 7/8:  22%|██▏       | 324/1500 [00:06<00:22, 51.84it/s, loss=0.946]
SASRec epoch 7/8:  22%|██▏       | 330/1500 [00:06<00:22, 52.19it/s, loss=0.946]
SASRec epoch 7/8:  22%|██▏       | 336/1500 [00:07<00:22, 52.74it/s, loss=0.946]
SASRec epoch 7/8:  23%|██▎       | 342/1500 [00:07<00:21, 52.76it/s, loss=0.946]
SASRec epoch 7/8:  23%|██▎       | 348/1500 [00:07<00:21, 53.27it/s, loss=0.946]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:07<00:21, 53.27it/s, loss=0.947]
SASRec epoch 7/8:  24%|██▎       | 354/1500 [00:07<00:22, 51.88it/s, loss=0.947]
SASRec epoch 7/8:  24%|██▍       | 360/1500 [00:07<00:21, 52.33it/s, loss=0.947]
SASRec epoch 7/8:  24%|██▍       | 366/1500 [00:07<00:21, 52.65it/s, loss=0.947]
SASRec epoch 7/8:  25%|██▍       | 372/1500 [00:07<00:22, 50.61it/s, loss=0.947]
SASRec epoch 7/8:  25%|██▌       | 378/1500 [00:07<00:21, 51.60it/s, loss=0.947]
SASRec epoch 7/8:  26%|██▌       | 384/1500 [00:08<00:21, 52.60it/s, loss=0.947]
SASRec epoch 7/8:  26%|██▌       | 390/1500 [00:08<00:20, 52.91it/s, loss=0.947]
SASRec epoch 7/8:  26%|██▋       | 396/1500 [00:08<00:20, 53.06it/s, loss=0.947]
SASRec epoch 7/8:  27%|██▋       | 400/1500 [00:08<00:20, 53.06it/s, loss=0.945]
SASRec epoch 7/8:  27%|██▋       | 402/1500 [00:08<00:21, 51.26it/s, loss=0.945]
SASRec epoch 7/8:  27%|██▋       | 408/1500 [00:08<00:20, 52.32it/s, loss=0.945]
SASRec epoch 7/8:  28%|██▊       | 414/1500 [00:08<00:20, 52.81it/s, loss=0.945]
SASRec epoch 7/8:  28%|██▊       | 420/1500 [00:08<00:21, 49.24it/s, loss=0.945]
SASRec epoch 7/8:  28%|██▊       | 425/1500 [00:08<00:23, 45.17it/s, loss=0.945]
SASRec epoch 7/8:  29%|██▊       | 430/1500 [00:09<00:24, 43.32it/s, loss=0.945]
SASRec epoch 7/8:  29%|██▉       | 435/1500 [00:09<00:24, 43.41it/s, loss=0.945]
SASRec epoch 7/8:  29%|██▉       | 440/1500 [00:09<00:24, 43.51it/s, loss=0.945]
SASRec epoch 7/8:  30%|██▉       | 445/1500 [00:09<00:24, 42.93it/s, loss=0.945]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:09<00:24, 42.36it/s, loss=0.945]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:09<00:24, 42.36it/s, loss=0.947]
SASRec epoch 7/8:  30%|███       | 455/1500 [00:09<00:25, 41.36it/s, loss=0.947]
SASRec epoch 7/8:  31%|███       | 460/1500 [00:09<00:25, 41.46it/s, loss=0.947]
SASRec epoch 7/8:  31%|███       | 465/1500 [00:09<00:24, 41.59it/s, loss=0.947]
SASRec epoch 7/8:  31%|███▏      | 470/1500 [00:09<00:25, 41.14it/s, loss=0.947]
SASRec epoch 7/8:  32%|███▏      | 475/1500 [00:10<00:24, 41.45it/s, loss=0.947]
SASRec epoch 7/8:  32%|███▏      | 480/1500 [00:10<00:24, 42.45it/s, loss=0.947]
SASRec epoch 7/8:  32%|███▏      | 485/1500 [00:10<00:24, 41.94it/s, loss=0.947]
SASRec epoch 7/8:  33%|███▎      | 490/1500 [00:10<00:23, 42.69it/s, loss=0.947]
SASRec epoch 7/8:  33%|███▎      | 495/1500 [00:10<00:24, 41.69it/s, loss=0.947]
SASRec epoch 7/8:  33%|███▎      | 500/1500 [00:10<00:23, 42.13it/s, loss=0.947]
SASRec epoch 7/8:  33%|███▎      | 500/1500 [00:10<00:23, 42.13it/s, loss=0.936]
SASRec epoch 7/8:  34%|███▎      | 505/1500 [00:10<00:24, 41.25it/s, loss=0.936]
SASRec epoch 7/8:  34%|███▍      | 510/1500 [00:10<00:24, 41.24it/s, loss=0.936]
SASRec epoch 7/8:  34%|███▍      | 515/1500 [00:11<00:23, 42.07it/s, loss=0.936]
SASRec epoch 7/8:  35%|███▍      | 520/1500 [00:11<00:33, 29.13it/s, loss=0.936]
SASRec epoch 7/8:  35%|███▍      | 524/1500 [00:11<00:58, 16.72it/s, loss=0.936]
SASRec epoch 7/8:  35%|███▌      | 527/1500 [00:12<01:06, 14.60it/s, loss=0.936]
SASRec epoch 7/8:  35%|███▌      | 530/1500 [00:12<01:13, 13.21it/s, loss=0.936]
SASRec epoch 7/8:  36%|███▌      | 534/1500 [00:12<00:59, 16.34it/s, loss=0.936]
SASRec epoch 7/8:  36%|███▌      | 538/1500 [00:12<00:49, 19.42it/s, loss=0.936]
SASRec epoch 7/8:  36%|███▌      | 542/1500 [00:12<00:42, 22.33it/s, loss=0.936]
SASRec epoch 7/8:  36%|███▋      | 547/1500 [00:12<00:35, 26.51it/s, loss=0.936]
SASRec epoch 7/8:  37%|███▋      | 550/1500 [00:13<00:35, 26.51it/s, loss=0.934]
SASRec epoch 7/8:  37%|███▋      | 551/1500 [00:13<00:33, 28.41it/s, loss=0.934]
SASRec epoch 7/8:  37%|███▋      | 557/1500 [00:13<00:27, 34.68it/s, loss=0.934]
SASRec epoch 7/8:  37%|███▋      | 562/1500 [00:13<00:25, 37.29it/s, loss=0.934]
SASRec epoch 7/8:  38%|███▊      | 568/1500 [00:13<00:22, 41.33it/s, loss=0.934]
SASRec epoch 7/8:  38%|███▊      | 573/1500 [00:13<00:21, 43.54it/s, loss=0.934]
SASRec epoch 7/8:  39%|███▊      | 579/1500 [00:13<00:20, 45.83it/s, loss=0.934]
SASRec epoch 7/8:  39%|███▉      | 585/1500 [00:13<00:19, 47.79it/s, loss=0.934]
SASRec epoch 7/8:  39%|███▉      | 591/1500 [00:13<00:18, 48.95it/s, loss=0.934]
SASRec epoch 7/8:  40%|███▉      | 596/1500 [00:13<00:18, 49.23it/s, loss=0.934]
SASRec epoch 7/8:  40%|████      | 600/1500 [00:14<00:18, 49.23it/s, loss=0.929]
SASRec epoch 7/8:  40%|████      | 601/1500 [00:14<00:18, 48.58it/s, loss=0.929]
SASRec epoch 7/8:  40%|████      | 607/1500 [00:14<00:17, 50.03it/s, loss=0.929]
SASRec epoch 7/8:  41%|████      | 613/1500 [00:14<00:17, 50.11it/s, loss=0.929]
SASRec epoch 7/8:  41%|████▏     | 619/1500 [00:14<00:17, 49.60it/s, loss=0.929]
SASRec epoch 7/8:  42%|████▏     | 625/1500 [00:14<00:17, 50.22it/s, loss=0.929]
SASRec epoch 7/8:  42%|████▏     | 631/1500 [00:14<00:16, 51.14it/s, loss=0.929]
SASRec epoch 7/8:  42%|████▏     | 637/1500 [00:14<00:16, 51.80it/s, loss=0.929]
SASRec epoch 7/8:  43%|████▎     | 643/1500 [00:14<00:16, 51.96it/s, loss=0.929]
SASRec epoch 7/8:  43%|████▎     | 649/1500 [00:14<00:16, 52.22it/s, loss=0.929]
SASRec epoch 7/8:  43%|████▎     | 650/1500 [00:14<00:16, 52.22it/s, loss=0.933]
SASRec epoch 7/8:  44%|████▎     | 655/1500 [00:15<00:16, 51.16it/s, loss=0.933]
SASRec epoch 7/8:  44%|████▍     | 661/1500 [00:15<00:16, 51.79it/s, loss=0.933]
SASRec epoch 7/8:  44%|████▍     | 667/1500 [00:15<00:16, 50.20it/s, loss=0.933]
SASRec epoch 7/8:  45%|████▍     | 673/1500 [00:15<00:16, 50.27it/s, loss=0.933]
SASRec epoch 7/8:  45%|████▌     | 679/1500 [00:15<00:16, 50.70it/s, loss=0.933]
SASRec epoch 7/8:  46%|████▌     | 685/1500 [00:15<00:15, 51.33it/s, loss=0.933]
SASRec epoch 7/8:  46%|████▌     | 691/1500 [00:15<00:15, 51.30it/s, loss=0.933]
SASRec epoch 7/8:  46%|████▋     | 697/1500 [00:15<00:15, 51.58it/s, loss=0.933]
SASRec epoch 7/8:  47%|████▋     | 700/1500 [00:15<00:15, 51.58it/s, loss=0.923]
SASRec epoch 7/8:  47%|████▋     | 703/1500 [00:16<00:15, 50.48it/s, loss=0.923]
SASRec epoch 7/8:  47%|████▋     | 709/1500 [00:16<00:15, 51.20it/s, loss=0.923]
SASRec epoch 7/8:  48%|████▊     | 715/1500 [00:16<00:15, 51.20it/s, loss=0.923]
SASRec epoch 7/8:  48%|████▊     | 721/1500 [00:16<00:15, 50.24it/s, loss=0.923]
SASRec epoch 7/8:  48%|████▊     | 727/1500 [00:16<00:15, 50.73it/s, loss=0.923]
SASRec epoch 7/8:  49%|████▉     | 733/1500 [00:16<00:14, 51.25it/s, loss=0.923]
SASRec epoch 7/8:  49%|████▉     | 739/1500 [00:16<00:14, 51.66it/s, loss=0.923]
SASRec epoch 7/8:  50%|████▉     | 745/1500 [00:16<00:14, 51.87it/s, loss=0.923]
SASRec epoch 7/8:  50%|█████     | 750/1500 [00:16<00:14, 51.87it/s, loss=0.915]
SASRec epoch 7/8:  50%|█████     | 751/1500 [00:16<00:14, 51.07it/s, loss=0.915]
SASRec epoch 7/8:  50%|█████     | 757/1500 [00:17<00:14, 51.73it/s, loss=0.915]
SASRec epoch 7/8:  51%|█████     | 763/1500 [00:17<00:14, 52.22it/s, loss=0.915]
SASRec epoch 7/8:  51%|█████▏    | 769/1500 [00:17<00:13, 52.40it/s, loss=0.915]
SASRec epoch 7/8:  52%|█████▏    | 775/1500 [00:17<00:14, 50.82it/s, loss=0.915]
SASRec epoch 7/8:  52%|█████▏    | 781/1500 [00:17<00:13, 51.55it/s, loss=0.915]
SASRec epoch 7/8:  52%|█████▏    | 787/1500 [00:17<00:13, 52.10it/s, loss=0.915]
SASRec epoch 7/8:  53%|█████▎    | 793/1500 [00:17<00:13, 52.64it/s, loss=0.915]
SASRec epoch 7/8:  53%|█████▎    | 799/1500 [00:17<00:13, 52.80it/s, loss=0.915]
SASRec epoch 7/8:  53%|█████▎    | 800/1500 [00:17<00:13, 52.80it/s, loss=0.922]
SASRec epoch 7/8:  54%|█████▎    | 805/1500 [00:18<00:13, 51.17it/s, loss=0.922]
SASRec epoch 7/8:  54%|█████▍    | 811/1500 [00:18<00:13, 51.54it/s, loss=0.922]
SASRec epoch 7/8:  54%|█████▍    | 817/1500 [00:18<00:13, 51.82it/s, loss=0.922]
SASRec epoch 7/8:  55%|█████▍    | 823/1500 [00:18<00:13, 51.78it/s, loss=0.922]
SASRec epoch 7/8:  55%|█████▌    | 829/1500 [00:18<00:13, 50.43it/s, loss=0.922]
SASRec epoch 7/8:  56%|█████▌    | 835/1500 [00:18<00:13, 50.89it/s, loss=0.922]
SASRec epoch 7/8:  56%|█████▌    | 841/1500 [00:18<00:12, 52.02it/s, loss=0.922]
SASRec epoch 7/8:  56%|█████▋    | 847/1500 [00:18<00:12, 52.02it/s, loss=0.922]
SASRec epoch 7/8:  57%|█████▋    | 850/1500 [00:18<00:12, 52.02it/s, loss=0.932]
SASRec epoch 7/8:  57%|█████▋    | 853/1500 [00:18<00:12, 51.22it/s, loss=0.932]
SASRec epoch 7/8:  57%|█████▋    | 859/1500 [00:19<00:12, 51.88it/s, loss=0.932]
SASRec epoch 7/8:  58%|█████▊    | 865/1500 [00:19<00:12, 52.45it/s, loss=0.932]
SASRec epoch 7/8:  58%|█████▊    | 871/1500 [00:19<00:12, 51.80it/s, loss=0.932]
SASRec epoch 7/8:  58%|█████▊    | 877/1500 [00:19<00:11, 52.25it/s, loss=0.932]
SASRec epoch 7/8:  59%|█████▉    | 883/1500 [00:19<00:12, 50.29it/s, loss=0.932]
SASRec epoch 7/8:  59%|█████▉    | 889/1500 [00:19<00:11, 50.97it/s, loss=0.932]
SASRec epoch 7/8:  60%|█████▉    | 895/1500 [00:19<00:11, 52.19it/s, loss=0.932]
SASRec epoch 7/8:  60%|██████    | 900/1500 [00:19<00:11, 52.19it/s, loss=0.917]
SASRec epoch 7/8:  60%|██████    | 901/1500 [00:19<00:11, 51.27it/s, loss=0.917]
SASRec epoch 7/8:  60%|██████    | 907/1500 [00:19<00:11, 51.61it/s, loss=0.917]
SASRec epoch 7/8:  61%|██████    | 913/1500 [00:20<00:11, 51.81it/s, loss=0.917]
SASRec epoch 7/8:  61%|██████▏   | 919/1500 [00:20<00:11, 52.20it/s, loss=0.917]
SASRec epoch 7/8:  62%|██████▏   | 925/1500 [00:20<00:10, 52.38it/s, loss=0.917]
SASRec epoch 7/8:  62%|██████▏   | 931/1500 [00:20<00:10, 52.66it/s, loss=0.917]
SASRec epoch 7/8:  62%|██████▏   | 937/1500 [00:20<00:11, 50.97it/s, loss=0.917]
SASRec epoch 7/8:  63%|██████▎   | 943/1500 [00:20<00:10, 51.91it/s, loss=0.917]
SASRec epoch 7/8:  63%|██████▎   | 949/1500 [00:20<00:10, 52.89it/s, loss=0.917]
SASRec epoch 7/8:  63%|██████▎   | 950/1500 [00:20<00:10, 52.89it/s, loss=0.921]
SASRec epoch 7/8:  64%|██████▎   | 955/1500 [00:20<00:10, 51.75it/s, loss=0.921]
SASRec epoch 7/8:  64%|██████▍   | 961/1500 [00:21<00:10, 52.49it/s, loss=0.921]
SASRec epoch 7/8:  64%|██████▍   | 967/1500 [00:21<00:10, 52.88it/s, loss=0.921]
SASRec epoch 7/8:  65%|██████▍   | 973/1500 [00:21<00:09, 53.38it/s, loss=0.921]
SASRec epoch 7/8:  65%|██████▌   | 979/1500 [00:21<00:09, 53.41it/s, loss=0.921]
SASRec epoch 7/8:  66%|██████▌   | 985/1500 [00:21<00:09, 53.71it/s, loss=0.921]
SASRec epoch 7/8:  66%|██████▌   | 991/1500 [00:21<00:09, 52.17it/s, loss=0.921]
SASRec epoch 7/8:  66%|██████▋   | 997/1500 [00:21<00:09, 52.79it/s, loss=0.921]
SASRec epoch 7/8:  67%|██████▋   | 1000/1500 [00:21<00:09, 52.79it/s, loss=0.922]
SASRec epoch 7/8:  67%|██████▋   | 1003/1500 [00:21<00:09, 51.62it/s, loss=0.922]
SASRec epoch 7/8:  67%|██████▋   | 1009/1500 [00:21<00:09, 52.26it/s, loss=0.922]
SASRec epoch 7/8:  68%|██████▊   | 1015/1500 [00:22<00:09, 52.95it/s, loss=0.922]
SASRec epoch 7/8:  68%|██████▊   | 1021/1500 [00:22<00:09, 52.95it/s, loss=0.922]
SASRec epoch 7/8:  68%|██████▊   | 1027/1500 [00:22<00:08, 53.31it/s, loss=0.922]
SASRec epoch 7/8:  69%|██████▉   | 1033/1500 [00:22<00:08, 52.76it/s, loss=0.922]
SASRec epoch 7/8:  69%|██████▉   | 1039/1500 [00:22<00:08, 52.16it/s, loss=0.922]
SASRec epoch 7/8:  70%|██████▉   | 1045/1500 [00:22<00:08, 51.00it/s, loss=0.922]
SASRec epoch 7/8:  70%|███████   | 1050/1500 [00:22<00:08, 51.00it/s, loss=0.9]
SASRec epoch 7/8:  70%|███████   | 1051/1500 [00:22<00:08, 50.07it/s, loss=0.9]
SASRec epoch 7/8:  70%|███████   | 1057/1500 [00:22<00:08, 50.73it/s, loss=0.9]
SASRec epoch 7/8:  71%|███████   | 1063/1500 [00:22<00:08, 52.04it/s, loss=0.9]
SASRec epoch 7/8:  71%|███████▏  | 1069/1500 [00:23<00:08, 51.03it/s, loss=0.9]
SASRec epoch 7/8:  72%|███████▏  | 1075/1500 [00:23<00:08, 47.72it/s, loss=0.9]
SASRec epoch 7/8:  72%|███████▏  | 1080/1500 [00:23<00:09, 46.16it/s, loss=0.9]
SASRec epoch 7/8:  72%|███████▏  | 1085/1500 [00:23<00:09, 45.26it/s, loss=0.9]
SASRec epoch 7/8:  73%|███████▎  | 1090/1500 [00:23<00:09, 44.29it/s, loss=0.9]
SASRec epoch 7/8:  73%|███████▎  | 1095/1500 [00:23<00:09, 43.23it/s, loss=0.9]
SASRec epoch 7/8:  73%|███████▎  | 1100/1500 [00:23<00:09, 43.09it/s, loss=0.9]
SASRec epoch 7/8:  73%|███████▎  | 1100/1500 [00:23<00:09, 43.09it/s, loss=0.918]
SASRec epoch 7/8:  74%|███████▎  | 1105/1500 [00:23<00:09, 43.34it/s, loss=0.918]
SASRec epoch 7/8:  74%|███████▍  | 1110/1500 [00:24<00:08, 44.04it/s, loss=0.918]
SASRec epoch 7/8:  74%|███████▍  | 1115/1500 [00:24<00:08, 44.49it/s, loss=0.918]
SASRec epoch 7/8:  75%|███████▍  | 1120/1500 [00:24<00:08, 44.16it/s, loss=0.918]
SASRec epoch 7/8:  75%|███████▌  | 1125/1500 [00:24<00:08, 44.34it/s, loss=0.918]
SASRec epoch 7/8:  75%|███████▌  | 1130/1500 [00:24<00:08, 44.35it/s, loss=0.918]
SASRec epoch 7/8:  76%|███████▌  | 1135/1500 [00:24<00:08, 43.86it/s, loss=0.918]
SASRec epoch 7/8:  76%|███████▌  | 1140/1500 [00:24<00:08, 44.62it/s, loss=0.918]
SASRec epoch 7/8:  76%|███████▋  | 1145/1500 [00:24<00:08, 41.82it/s, loss=0.918]
SASRec epoch 7/8:  77%|███████▋  | 1150/1500 [00:24<00:08, 41.23it/s, loss=0.918]
SASRec epoch 7/8:  77%|███████▋  | 1150/1500 [00:24<00:08, 41.23it/s, loss=0.91]
SASRec epoch 7/8:  77%|███████▋  | 1155/1500 [00:25<00:08, 40.72it/s, loss=0.91]
SASRec epoch 7/8:  77%|███████▋  | 1160/1500 [00:25<00:08, 41.39it/s, loss=0.91]
SASRec epoch 7/8:  78%|███████▊  | 1165/1500 [00:25<00:08, 40.52it/s, loss=0.91]
SASRec epoch 7/8:  78%|███████▊  | 1170/1500 [00:25<00:07, 41.65it/s, loss=0.91]
SASRec epoch 7/8:  78%|███████▊  | 1175/1500 [00:25<00:07, 41.50it/s, loss=0.91]
SASRec epoch 7/8:  79%|███████▊  | 1180/1500 [00:25<00:07, 42.44it/s, loss=0.91]
SASRec epoch 7/8:  79%|███████▉  | 1185/1500 [00:25<00:07, 42.87it/s, loss=0.91]
SASRec epoch 7/8:  79%|███████▉  | 1190/1500 [00:25<00:07, 41.84it/s, loss=0.91]
SASRec epoch 7/8:  80%|███████▉  | 1195/1500 [00:26<00:07, 42.54it/s, loss=0.91]
SASRec epoch 7/8:  80%|████████  | 1200/1500 [00:26<00:07, 40.71it/s, loss=0.91]
SASRec epoch 7/8:  80%|████████  | 1200/1500 [00:26<00:07, 40.71it/s, loss=0.909]
SASRec epoch 7/8:  80%|████████  | 1205/1500 [00:26<00:07, 38.52it/s, loss=0.909]
SASRec epoch 7/8:  81%|████████  | 1209/1500 [00:26<00:07, 36.95it/s, loss=0.909]
SASRec epoch 7/8:  81%|████████  | 1213/1500 [00:26<00:07, 36.03it/s, loss=0.909]
SASRec epoch 7/8:  81%|████████  | 1217/1500 [00:26<00:08, 35.27it/s, loss=0.909]
SASRec epoch 7/8:  81%|████████▏ | 1221/1500 [00:26<00:08, 34.71it/s, loss=0.909]
SASRec epoch 7/8:  82%|████████▏ | 1225/1500 [00:26<00:07, 35.18it/s, loss=0.909]
SASRec epoch 7/8:  82%|████████▏ | 1229/1500 [00:27<00:07, 34.92it/s, loss=0.909]
SASRec epoch 7/8:  82%|████████▏ | 1233/1500 [00:27<00:07, 35.35it/s, loss=0.909]
SASRec epoch 7/8:  82%|████████▏ | 1237/1500 [00:27<00:07, 34.87it/s, loss=0.909]
SASRec epoch 7/8:  83%|████████▎ | 1241/1500 [00:27<00:07, 36.21it/s, loss=0.909]
SASRec epoch 7/8:  83%|████████▎ | 1247/1500 [00:27<00:06, 41.03it/s, loss=0.909]

[SASRec] epoch 7/8 loss=0.9254

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 8/8:   0%|          | 6/1500 [00:00<00:28, 51.93it/s]
SASRec epoch 8/8:   1%|          | 12/1500 [00:00<00:27, 53.17it/s]
SASRec epoch 8/8:   1%|          | 18/1500 [00:00<00:27, 53.95it/s]
SASRec epoch 8/8:   2%|▏         | 24/1500 [00:00<00:27, 53.66it/s]
SASRec epoch 8/8:   2%|▏         | 30/1500 [00:00<00:27, 53.88it/s]
SASRec epoch 8/8:   2%|▏         | 36/1500 [00:00<00:27, 54.06it/s]
SASRec epoch 8/8:   3%|▎         | 42/1500 [00:00<00:27, 53.83it/s]
SASRec epoch 8/8:   3%|▎         | 48/1500 [00:00<00:27, 52.31it/s]
SASRec epoch 8/8:   3%|▎         | 50/1500 [00:00<00:27, 52.31it/s, loss=0.89]
SASRec epoch 8/8:   4%|▎         | 54/1500 [00:01<00:28, 50.15it/s, loss=0.89]
SASRec epoch 8/8:   4%|▍         | 60/1500 [00:01<00:27, 51.47it/s, loss=0.89]
SASRec epoch 8/8:   4%|▍         | 66/1500 [00:01<00:27, 52.01it/s, loss=0.89]
SASRec epoch 8/8:   5%|▍         | 72/1500 [00:01<00:27, 52.70it/s, loss=0.89]
SASRec epoch 8/8:   5%|▌         | 78/1500 [00:01<00:26, 52.94it/s, loss=0.89]
SASRec epoch 8/8:   6%|▌         | 84/1500 [00:01<00:26, 53.12it/s, loss=0.89]
SASRec epoch 8/8:   6%|▌         | 90/1500 [00:01<00:26, 53.28it/s, loss=0.89]
SASRec epoch 8/8:   6%|▋         | 96/1500 [00:01<00:26, 53.35it/s, loss=0.89]
SASRec epoch 8/8:   7%|▋         | 100/1500 [00:01<00:26, 53.35it/s, loss=0.887]
SASRec epoch 8/8:   7%|▋         | 102/1500 [00:01<00:26, 52.03it/s, loss=0.887]
SASRec epoch 8/8:   7%|▋         | 108/1500 [00:02<00:27, 50.55it/s, loss=0.887]
SASRec epoch 8/8:   8%|▊         | 114/1500 [00:02<00:26, 51.42it/s, loss=0.887]
SASRec epoch 8/8:   8%|▊         | 120/1500 [00:02<00:26, 51.66it/s, loss=0.887]
SASRec epoch 8/8:   8%|▊         | 126/1500 [00:02<00:26, 52.24it/s, loss=0.887]
SASRec epoch 8/8:   9%|▉         | 132/1500 [00:02<00:26, 52.51it/s, loss=0.887]
SASRec epoch 8/8:   9%|▉         | 138/1500 [00:02<00:25, 52.44it/s, loss=0.887]
SASRec epoch 8/8:  10%|▉         | 144/1500 [00:02<00:25, 52.59it/s, loss=0.887]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:02<00:25, 52.87it/s, loss=0.887]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:02<00:25, 52.87it/s, loss=0.893]
SASRec epoch 8/8:  10%|█         | 156/1500 [00:02<00:26, 50.79it/s, loss=0.893]
SASRec epoch 8/8:  11%|█         | 162/1500 [00:03<00:26, 50.48it/s, loss=0.893]
SASRec epoch 8/8:  11%|█         | 168/1500 [00:03<00:26, 51.05it/s, loss=0.893]
SASRec epoch 8/8:  12%|█▏        | 174/1500 [00:03<00:25, 51.88it/s, loss=0.893]
SASRec epoch 8/8:  12%|█▏        | 180/1500 [00:03<00:25, 52.13it/s, loss=0.893]
SASRec epoch 8/8:  12%|█▏        | 186/1500 [00:03<00:25, 52.44it/s, loss=0.893]
SASRec epoch 8/8:  13%|█▎        | 192/1500 [00:03<00:24, 53.03it/s, loss=0.893]
SASRec epoch 8/8:  13%|█▎        | 198/1500 [00:03<00:24, 53.89it/s, loss=0.893]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:03<00:24, 53.89it/s, loss=0.879]
SASRec epoch 8/8:  14%|█▎        | 204/1500 [00:03<00:24, 51.90it/s, loss=0.879]
SASRec epoch 8/8:  14%|█▍        | 210/1500 [00:04<00:24, 52.80it/s, loss=0.879]
SASRec epoch 8/8:  14%|█▍        | 216/1500 [00:04<00:24, 51.77it/s, loss=0.879]
SASRec epoch 8/8:  15%|█▍        | 222/1500 [00:04<00:24, 52.04it/s, loss=0.879]
SASRec epoch 8/8:  15%|█▌        | 228/1500 [00:04<00:23, 53.12it/s, loss=0.879]
SASRec epoch 8/8:  16%|█▌        | 234/1500 [00:04<00:23, 53.69it/s, loss=0.879]
SASRec epoch 8/8:  16%|█▌        | 240/1500 [00:04<00:23, 53.77it/s, loss=0.879]
SASRec epoch 8/8:  16%|█▋        | 246/1500 [00:04<00:23, 53.91it/s, loss=0.879]
SASRec epoch 8/8:  17%|█▋        | 250/1500 [00:04<00:23, 53.91it/s, loss=0.888]
SASRec epoch 8/8:  17%|█▋        | 252/1500 [00:04<00:23, 52.19it/s, loss=0.888]
SASRec epoch 8/8:  17%|█▋        | 258/1500 [00:04<00:23, 52.92it/s, loss=0.888]
SASRec epoch 8/8:  18%|█▊        | 264/1500 [00:05<00:25, 48.49it/s, loss=0.888]
SASRec epoch 8/8:  18%|█▊        | 269/1500 [00:05<00:27, 44.52it/s, loss=0.888]
SASRec epoch 8/8:  18%|█▊        | 274/1500 [00:05<00:28, 43.20it/s, loss=0.888]
SASRec epoch 8/8:  19%|█▊        | 279/1500 [00:05<00:28, 42.69it/s, loss=0.888]
SASRec epoch 8/8:  19%|█▉        | 284/1500 [00:05<00:28, 42.97it/s, loss=0.888]
SASRec epoch 8/8:  19%|█▉        | 289/1500 [00:05<00:27, 43.33it/s, loss=0.888]
SASRec epoch 8/8:  20%|█▉        | 294/1500 [00:05<00:27, 43.50it/s, loss=0.888]
SASRec epoch 8/8:  20%|█▉        | 299/1500 [00:05<00:27, 43.50it/s, loss=0.888]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:05<00:27, 43.50it/s, loss=0.873]
SASRec epoch 8/8:  20%|██        | 304/1500 [00:06<00:27, 42.90it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 309/1500 [00:06<00:27, 42.96it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 314/1500 [00:06<00:30, 39.21it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 318/1500 [00:06<00:30, 38.88it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 323/1500 [00:06<00:29, 39.91it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 328/1500 [00:06<00:29, 40.13it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 333/1500 [00:06<00:28, 41.52it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 338/1500 [00:06<00:28, 40.72it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 343/1500 [00:07<00:29, 39.49it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 348/1500 [00:07<00:28, 40.60it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 350/1500 [00:07<00:28, 40.60it/s, loss=0.877]
SASRec epoch 8/8:  24%|██▎       | 353/1500 [00:07<00:28, 40.93it/s, loss=0.877]
SASRec epoch 8/8:  24%|██▍       | 358/1500 [00:07<00:29, 38.63it/s, loss=0.877]
SASRec epoch 8/8:  24%|██▍       | 363/1500 [00:07<00:28, 40.43it/s, loss=0.877]
SASRec epoch 8/8:  25%|██▍       | 368/1500 [00:07<00:27, 41.60it/s, loss=0.877]
SASRec epoch 8/8:  25%|██▍       | 373/1500 [00:07<00:26, 43.25it/s, loss=0.877]
SASRec epoch 8/8:  25%|██▌       | 378/1500 [00:07<00:25, 44.44it/s, loss=0.877]
SASRec epoch 8/8:  26%|██▌       | 383/1500 [00:07<00:24, 44.74it/s, loss=0.877]
SASRec epoch 8/8:  26%|██▌       | 388/1500 [00:08<00:25, 43.99it/s, loss=0.877]
SASRec epoch 8/8:  26%|██▌       | 393/1500 [00:08<00:25, 43.26it/s, loss=0.877]
SASRec epoch 8/8:  27%|██▋       | 398/1500 [00:08<00:28, 39.35it/s, loss=0.877]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:08<00:27, 39.35it/s, loss=0.867]
SASRec epoch 8/8:  27%|██▋       | 403/1500 [00:08<00:30, 36.32it/s, loss=0.867]
SASRec epoch 8/8:  27%|██▋       | 407/1500 [00:08<00:29, 36.85it/s, loss=0.867]
SASRec epoch 8/8:  27%|██▋       | 411/1500 [00:08<00:29, 36.68it/s, loss=0.867]
SASRec epoch 8/8:  28%|██▊       | 415/1500 [00:08<00:29, 37.26it/s, loss=0.867]
SASRec epoch 8/8:  28%|██▊       | 419/1500 [00:08<00:29, 36.55it/s, loss=0.867]
SASRec epoch 8/8:  28%|██▊       | 423/1500 [00:09<00:29, 36.55it/s, loss=0.867]
SASRec epoch 8/8:  28%|██▊       | 427/1500 [00:09<00:28, 37.44it/s, loss=0.867]
SASRec epoch 8/8:  29%|██▉       | 433/1500 [00:09<00:25, 42.52it/s, loss=0.867]
SASRec epoch 8/8:  29%|██▉       | 439/1500 [00:09<00:23, 45.50it/s, loss=0.867]
SASRec epoch 8/8:  30%|██▉       | 445/1500 [00:09<00:22, 47.51it/s, loss=0.867]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:09<00:22, 47.68it/s, loss=0.867]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:09<00:22, 47.68it/s, loss=0.864]
SASRec epoch 8/8:  30%|███       | 455/1500 [00:09<00:21, 47.73it/s, loss=0.864]
SASRec epoch 8/8:  31%|███       | 461/1500 [00:09<00:21, 49.26it/s, loss=0.864]
SASRec epoch 8/8:  31%|███       | 467/1500 [00:09<00:20, 50.07it/s, loss=0.864]
SASRec epoch 8/8:  32%|███▏      | 473/1500 [00:10<00:20, 50.99it/s, loss=0.864]
SASRec epoch 8/8:  32%|███▏      | 479/1500 [00:10<00:19, 52.01it/s, loss=0.864]
SASRec epoch 8/8:  32%|███▏      | 485/1500 [00:10<00:19, 52.80it/s, loss=0.864]
SASRec epoch 8/8:  33%|███▎      | 491/1500 [00:10<00:19, 52.79it/s, loss=0.864]
SASRec epoch 8/8:  33%|███▎      | 497/1500 [00:10<00:18, 52.99it/s, loss=0.864]
SASRec epoch 8/8:  33%|███▎      | 500/1500 [00:10<00:18, 52.99it/s, loss=0.868]
SASRec epoch 8/8:  34%|███▎      | 503/1500 [00:10<00:19, 50.24it/s, loss=0.868]
SASRec epoch 8/8:  34%|███▍      | 509/1500 [00:10<00:19, 51.32it/s, loss=0.868]
SASRec epoch 8/8:  34%|███▍      | 515/1500 [00:10<00:18, 52.33it/s, loss=0.868]
SASRec epoch 8/8:  35%|███▍      | 521/1500 [00:10<00:18, 52.82it/s, loss=0.868]
SASRec epoch 8/8:  35%|███▌      | 527/1500 [00:11<00:18, 53.43it/s, loss=0.868]
SASRec epoch 8/8:  36%|███▌      | 533/1500 [00:11<00:18, 53.44it/s, loss=0.868]
SASRec epoch 8/8:  36%|███▌      | 539/1500 [00:11<00:18, 53.35it/s, loss=0.868]
SASRec epoch 8/8:  36%|███▋      | 545/1500 [00:11<00:17, 53.24it/s, loss=0.868]
SASRec epoch 8/8:  37%|███▋      | 550/1500 [00:11<00:17, 53.24it/s, loss=0.868]
SASRec epoch 8/8:  37%|███▋      | 551/1500 [00:11<00:18, 51.53it/s, loss=0.868]
SASRec epoch 8/8:  37%|███▋      | 557/1500 [00:11<00:18, 50.93it/s, loss=0.868]
SASRec epoch 8/8:  38%|███▊      | 563/1500 [00:11<00:17, 52.12it/s, loss=0.868]
SASRec epoch 8/8:  38%|███▊      | 569/1500 [00:11<00:17, 52.41it/s, loss=0.868]
SASRec epoch 8/8:  38%|███▊      | 575/1500 [00:11<00:17, 52.29it/s, loss=0.868]
SASRec epoch 8/8:  39%|███▊      | 581/1500 [00:12<00:17, 53.05it/s, loss=0.868]
SASRec epoch 8/8:  39%|███▉      | 587/1500 [00:12<00:17, 53.53it/s, loss=0.868]
SASRec epoch 8/8:  40%|███▉      | 593/1500 [00:12<00:17, 53.25it/s, loss=0.868]
SASRec epoch 8/8:  40%|███▉      | 599/1500 [00:12<00:16, 53.25it/s, loss=0.868]
SASRec epoch 8/8:  40%|████      | 600/1500 [00:12<00:16, 53.25it/s, loss=0.857]
SASRec epoch 8/8:  40%|████      | 605/1500 [00:12<00:17, 51.97it/s, loss=0.857]
SASRec epoch 8/8:  41%|████      | 611/1500 [00:12<00:17, 51.06it/s, loss=0.857]
SASRec epoch 8/8:  41%|████      | 617/1500 [00:12<00:17, 51.49it/s, loss=0.857]
SASRec epoch 8/8:  42%|████▏     | 623/1500 [00:12<00:16, 52.24it/s, loss=0.857]
SASRec epoch 8/8:  42%|████▏     | 629/1500 [00:12<00:16, 52.76it/s, loss=0.857]
SASRec epoch 8/8:  42%|████▏     | 635/1500 [00:13<00:16, 52.85it/s, loss=0.857]
SASRec epoch 8/8:  43%|████▎     | 641/1500 [00:13<00:16, 53.51it/s, loss=0.857]
SASRec epoch 8/8:  43%|████▎     | 647/1500 [00:13<00:15, 53.58it/s, loss=0.857]
SASRec epoch 8/8:  43%|████▎     | 650/1500 [00:13<00:15, 53.58it/s, loss=0.851]
SASRec epoch 8/8:  44%|████▎     | 653/1500 [00:13<00:16, 52.73it/s, loss=0.851]
SASRec epoch 8/8:  44%|████▍     | 659/1500 [00:13<00:15, 52.95it/s, loss=0.851]
SASRec epoch 8/8:  44%|████▍     | 665/1500 [00:13<00:15, 52.23it/s, loss=0.851]
SASRec epoch 8/8:  45%|████▍     | 671/1500 [00:13<00:15, 52.90it/s, loss=0.851]
SASRec epoch 8/8:  45%|████▌     | 677/1500 [00:13<00:15, 53.10it/s, loss=0.851]
SASRec epoch 8/8:  46%|████▌     | 683/1500 [00:14<00:15, 53.09it/s, loss=0.851]
SASRec epoch 8/8:  46%|████▌     | 689/1500 [00:14<00:15, 53.19it/s, loss=0.851]
SASRec epoch 8/8:  46%|████▋     | 695/1500 [00:14<00:15, 53.09it/s, loss=0.851]
SASRec epoch 8/8:  47%|████▋     | 700/1500 [00:14<00:15, 53.09it/s, loss=0.875]
SASRec epoch 8/8:  47%|████▋     | 701/1500 [00:14<00:15, 51.83it/s, loss=0.875]
SASRec epoch 8/8:  47%|████▋     | 707/1500 [00:14<00:15, 52.29it/s, loss=0.875]
SASRec epoch 8/8:  48%|████▊     | 713/1500 [00:14<00:14, 52.52it/s, loss=0.875]
SASRec epoch 8/8:  48%|████▊     | 719/1500 [00:14<00:14, 52.91it/s, loss=0.875]
SASRec epoch 8/8:  48%|████▊     | 725/1500 [00:14<00:15, 51.55it/s, loss=0.875]
SASRec epoch 8/8:  49%|████▊     | 731/1500 [00:14<00:14, 52.16it/s, loss=0.875]
SASRec epoch 8/8:  49%|████▉     | 737/1500 [00:15<00:14, 52.97it/s, loss=0.875]
SASRec epoch 8/8:  50%|████▉     | 743/1500 [00:15<00:14, 53.65it/s, loss=0.875]
SASRec epoch 8/8:  50%|████▉     | 749/1500 [00:15<00:13, 53.93it/s, loss=0.875]
SASRec epoch 8/8:  50%|█████     | 750/1500 [00:15<00:13, 53.93it/s, loss=0.859]
SASRec epoch 8/8:  50%|█████     | 755/1500 [00:15<00:14, 53.03it/s, loss=0.859]
SASRec epoch 8/8:  51%|█████     | 761/1500 [00:15<00:13, 53.48it/s, loss=0.859]
SASRec epoch 8/8:  51%|█████     | 767/1500 [00:15<00:13, 53.54it/s, loss=0.859]
SASRec epoch 8/8:  52%|█████▏    | 773/1500 [00:15<00:13, 53.93it/s, loss=0.859]
SASRec epoch 8/8:  52%|█████▏    | 779/1500 [00:15<00:13, 52.35it/s, loss=0.859]
SASRec epoch 8/8:  52%|█████▏    | 785/1500 [00:15<00:13, 52.30it/s, loss=0.859]
SASRec epoch 8/8:  53%|█████▎    | 791/1500 [00:16<00:13, 52.57it/s, loss=0.859]
SASRec epoch 8/8:  53%|█████▎    | 797/1500 [00:16<00:13, 52.24it/s, loss=0.859]
SASRec epoch 8/8:  53%|█████▎    | 800/1500 [00:16<00:13, 52.24it/s, loss=0.859]
SASRec epoch 8/8:  54%|█████▎    | 803/1500 [00:16<00:13, 51.50it/s, loss=0.859]
SASRec epoch 8/8:  54%|█████▍    | 809/1500 [00:16<00:13, 51.92it/s, loss=0.859]
SASRec epoch 8/8:  54%|█████▍    | 815/1500 [00:16<00:13, 52.62it/s, loss=0.859]
SASRec epoch 8/8:  55%|█████▍    | 821/1500 [00:16<00:12, 52.93it/s, loss=0.859]
SASRec epoch 8/8:  55%|█████▌    | 827/1500 [00:16<00:12, 53.35it/s, loss=0.859]
SASRec epoch 8/8:  56%|█████▌    | 833/1500 [00:16<00:12, 51.56it/s, loss=0.859]
SASRec epoch 8/8:  56%|█████▌    | 839/1500 [00:16<00:12, 52.34it/s, loss=0.859]
SASRec epoch 8/8:  56%|█████▋    | 845/1500 [00:17<00:12, 52.91it/s, loss=0.859]
SASRec epoch 8/8:  57%|█████▋    | 850/1500 [00:17<00:12, 52.91it/s, loss=0.851]
SASRec epoch 8/8:  57%|█████▋    | 851/1500 [00:17<00:12, 52.27it/s, loss=0.851]
SASRec epoch 8/8:  57%|█████▋    | 857/1500 [00:17<00:12, 52.77it/s, loss=0.851]
SASRec epoch 8/8:  58%|█████▊    | 863/1500 [00:17<00:11, 53.21it/s, loss=0.851]
SASRec epoch 8/8:  58%|█████▊    | 869/1500 [00:17<00:11, 53.69it/s, loss=0.851]
SASRec epoch 8/8:  58%|█████▊    | 875/1500 [00:17<00:11, 53.48it/s, loss=0.851]
SASRec epoch 8/8:  59%|█████▊    | 881/1500 [00:17<00:11, 53.71it/s, loss=0.851]
SASRec epoch 8/8:  59%|█████▉    | 887/1500 [00:17<00:11, 51.43it/s, loss=0.851]
SASRec epoch 8/8:  60%|█████▉    | 893/1500 [00:17<00:11, 52.46it/s, loss=0.851]
SASRec epoch 8/8:  60%|█████▉    | 899/1500 [00:18<00:11, 52.87it/s, loss=0.851]
SASRec epoch 8/8:  60%|██████    | 900/1500 [00:18<00:11, 52.87it/s, loss=0.843]
SASRec epoch 8/8:  60%|██████    | 905/1500 [00:18<00:11, 51.39it/s, loss=0.843]
SASRec epoch 8/8:  61%|██████    | 911/1500 [00:18<00:11, 51.41it/s, loss=0.843]
SASRec epoch 8/8:  61%|██████    | 917/1500 [00:18<00:11, 51.70it/s, loss=0.843]
SASRec epoch 8/8:  62%|██████▏   | 923/1500 [00:18<00:11, 51.76it/s, loss=0.843]
SASRec epoch 8/8:  62%|██████▏   | 929/1500 [00:18<00:10, 52.24it/s, loss=0.843]
SASRec epoch 8/8:  62%|██████▏   | 935/1500 [00:18<00:10, 52.29it/s, loss=0.843]
SASRec epoch 8/8:  63%|██████▎   | 941/1500 [00:18<00:11, 50.25it/s, loss=0.843]
SASRec epoch 8/8:  63%|██████▎   | 947/1500 [00:19<00:10, 50.75it/s, loss=0.843]
SASRec epoch 8/8:  63%|██████▎   | 950/1500 [00:19<00:10, 50.75it/s, loss=0.85]
SASRec epoch 8/8:  64%|██████▎   | 953/1500 [00:19<00:12, 45.17it/s, loss=0.85]
SASRec epoch 8/8:  64%|██████▍   | 958/1500 [00:19<00:12, 42.58it/s, loss=0.85]
SASRec epoch 8/8:  64%|██████▍   | 963/1500 [00:19<00:12, 41.72it/s, loss=0.85]
SASRec epoch 8/8:  65%|██████▍   | 968/1500 [00:19<00:12, 41.65it/s, loss=0.85]
SASRec epoch 8/8:  65%|██████▍   | 973/1500 [00:19<00:13, 40.37it/s, loss=0.85]
SASRec epoch 8/8:  65%|██████▌   | 978/1500 [00:19<00:12, 41.25it/s, loss=0.85]
SASRec epoch 8/8:  66%|██████▌   | 983/1500 [00:19<00:12, 41.11it/s, loss=0.85]
SASRec epoch 8/8:  66%|██████▌   | 988/1500 [00:20<00:12, 40.11it/s, loss=0.85]
SASRec epoch 8/8:  66%|██████▌   | 993/1500 [00:20<00:12, 40.09it/s, loss=0.85]
SASRec epoch 8/8:  67%|██████▋   | 998/1500 [00:20<00:12, 40.39it/s, loss=0.85]
SASRec epoch 8/8:  67%|██████▋   | 1000/1500 [00:20<00:12, 40.39it/s, loss=0.853]
SASRec epoch 8/8:  67%|██████▋   | 1003/1500 [00:20<00:12, 38.84it/s, loss=0.853]
SASRec epoch 8/8:  67%|██████▋   | 1007/1500 [00:20<00:12, 38.98it/s, loss=0.853]
SASRec epoch 8/8:  67%|██████▋   | 1012/1500 [00:20<00:12, 40.14it/s, loss=0.853]
SASRec epoch 8/8:  68%|██████▊   | 1017/1500 [00:20<00:11, 40.29it/s, loss=0.853]
SASRec epoch 8/8:  68%|██████▊   | 1022/1500 [00:20<00:11, 40.48it/s, loss=0.853]
SASRec epoch 8/8:  68%|██████▊   | 1027/1500 [00:21<00:11, 40.23it/s, loss=0.853]
SASRec epoch 8/8:  69%|██████▉   | 1032/1500 [00:21<00:11, 41.30it/s, loss=0.853]
SASRec epoch 8/8:  69%|██████▉   | 1037/1500 [00:21<00:10, 42.59it/s, loss=0.853]
SASRec epoch 8/8:  69%|██████▉   | 1042/1500 [00:21<00:10, 42.91it/s, loss=0.853]
SASRec epoch 8/8:  70%|██████▉   | 1047/1500 [00:21<00:10, 43.73it/s, loss=0.853]
SASRec epoch 8/8:  70%|███████   | 1050/1500 [00:21<00:10, 43.73it/s, loss=0.843]
SASRec epoch 8/8:  70%|███████   | 1052/1500 [00:21<00:10, 43.39it/s, loss=0.843]
SASRec epoch 8/8:  70%|███████   | 1057/1500 [00:21<00:09, 44.38it/s, loss=0.843]
SASRec epoch 8/8:  71%|███████   | 1062/1500 [00:21<00:09, 44.64it/s, loss=0.843]
SASRec epoch 8/8:  71%|███████   | 1067/1500 [00:21<00:09, 45.23it/s, loss=0.843]
SASRec epoch 8/8:  71%|███████▏  | 1072/1500 [00:22<00:09, 45.89it/s, loss=0.843]
SASRec epoch 8/8:  72%|███████▏  | 1077/1500 [00:22<00:09, 43.83it/s, loss=0.843]
SASRec epoch 8/8:  72%|███████▏  | 1082/1500 [00:22<00:09, 43.12it/s, loss=0.843]
SASRec epoch 8/8:  72%|███████▏  | 1087/1500 [00:22<00:09, 42.02it/s, loss=0.843]
SASRec epoch 8/8:  73%|███████▎  | 1092/1500 [00:22<00:09, 41.06it/s, loss=0.843]
SASRec epoch 8/8:  73%|███████▎  | 1097/1500 [00:22<00:09, 40.35it/s, loss=0.843]
SASRec epoch 8/8:  73%|███████▎  | 1100/1500 [00:22<00:09, 40.35it/s, loss=0.849]
SASRec epoch 8/8:  73%|███████▎  | 1102/1500 [00:22<00:09, 41.10it/s, loss=0.849]
SASRec epoch 8/8:  74%|███████▍  | 1107/1500 [00:22<00:09, 40.06it/s, loss=0.849]
SASRec epoch 8/8:  74%|███████▍  | 1112/1500 [00:23<00:09, 39.51it/s, loss=0.849]
SASRec epoch 8/8:  74%|███████▍  | 1116/1500 [00:23<00:09, 39.25it/s, loss=0.849]
SASRec epoch 8/8:  75%|███████▍  | 1120/1500 [00:23<00:10, 37.11it/s, loss=0.849]
SASRec epoch 8/8:  75%|███████▍  | 1124/1500 [00:23<00:10, 36.73it/s, loss=0.849]
SASRec epoch 8/8:  75%|███████▌  | 1129/1500 [00:23<00:09, 39.43it/s, loss=0.849]
SASRec epoch 8/8:  76%|███████▌  | 1135/1500 [00:23<00:08, 43.43it/s, loss=0.849]
SASRec epoch 8/8:  76%|███████▌  | 1141/1500 [00:23<00:07, 46.73it/s, loss=0.849]
SASRec epoch 8/8:  76%|███████▋  | 1147/1500 [00:23<00:07, 48.97it/s, loss=0.849]
SASRec epoch 8/8:  77%|███████▋  | 1150/1500 [00:23<00:07, 48.97it/s, loss=0.845]
SASRec epoch 8/8:  77%|███████▋  | 1152/1500 [00:23<00:07, 47.76it/s, loss=0.845]
SASRec epoch 8/8:  77%|███████▋  | 1158/1500 [00:24<00:06, 49.77it/s, loss=0.845]
SASRec epoch 8/8:  78%|███████▊  | 1164/1500 [00:24<00:06, 51.05it/s, loss=0.845]
SASRec epoch 8/8:  78%|███████▊  | 1170/1500 [00:24<00:06, 49.96it/s, loss=0.845]
SASRec epoch 8/8:  78%|███████▊  | 1176/1500 [00:24<00:06, 51.00it/s, loss=0.845]
SASRec epoch 8/8:  79%|███████▉  | 1182/1500 [00:24<00:06, 52.03it/s, loss=0.845]
SASRec epoch 8/8:  79%|███████▉  | 1188/1500 [00:24<00:05, 52.67it/s, loss=0.845]
SASRec epoch 8/8:  80%|███████▉  | 1194/1500 [00:24<00:05, 53.35it/s, loss=0.845]
SASRec epoch 8/8:  80%|████████  | 1200/1500 [00:24<00:05, 53.93it/s, loss=0.845]
SASRec epoch 8/8:  80%|████████  | 1200/1500 [00:24<00:05, 53.93it/s, loss=0.85]
SASRec epoch 8/8:  80%|████████  | 1206/1500 [00:24<00:05, 52.63it/s, loss=0.85]
SASRec epoch 8/8:  81%|████████  | 1212/1500 [00:25<00:05, 53.33it/s, loss=0.85]
SASRec epoch 8/8:  81%|████████  | 1218/1500 [00:25<00:05, 53.67it/s, loss=0.85]
SASRec epoch 8/8:  82%|████████▏ | 1224/1500 [00:25<00:05, 53.35it/s, loss=0.85]
SASRec epoch 8/8:  82%|████████▏ | 1230/1500 [00:25<00:05, 52.32it/s, loss=0.85]
SASRec epoch 8/8:  82%|████████▏ | 1236/1500 [00:25<00:05, 52.42it/s, loss=0.85]
SASRec epoch 8/8:  83%|████████▎ | 1242/1500 [00:25<00:04, 52.66it/s, loss=0.85]
SASRec epoch 8/8:  83%|████████▎ | 1248/1500 [00:25<00:04, 53.19it/s, loss=0.85]
SASRec epoch 8/8:  83%|████████▎ | 1250/1500 [00:25<00:04, 53.19it/s, loss=0.845]

[SASRec] epoch 8/8 loss=0.8592

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0015 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0035 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0064 | NDCG@100: 0.0014 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095

SASRec hyperparam search:  25%|██▌       | 1/4 [04:23<13:10, 263.43s/it]/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0013 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0015 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0038 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0071 | NDCG@100: 0.0015 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target score: split=ALL K=50 Recall=0.003504

=== TRY: {'max_len': 50, 'hidden': 128, 'n_heads': 4, 'dropout': 0.2, 'lr': 0.0008} ===

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 1/8:   0%|          | 3/1500 [00:00<01:05, 23.00it/s]
SASRec epoch 1/8:   0%|          | 6/1500 [00:00<01:04, 23.34it/s]
SASRec epoch 1/8:   1%|          | 10/1500 [00:00<00:54, 27.53it/s]
SASRec epoch 1/8:   1%|          | 14/1500 [00:00<00:50, 29.52it/s]
SASRec epoch 1/8:   1%|          | 18/1500 [00:00<00:47, 30.88it/s]
SASRec epoch 1/8:   1%|▏         | 22/1500 [00:00<00:47, 31.16it/s]
SASRec epoch 1/8:   2%|▏         | 26/1500 [00:00<00:46, 31.68it/s]
SASRec epoch 1/8:   2%|▏         | 30/1500 [00:00<00:45, 32.04it/s]
SASRec epoch 1/8:   2%|▏         | 34/1500 [00:01<00:45, 32.42it/s]
SASRec epoch 1/8:   3%|▎         | 38/1500 [00:01<00:44, 32.90it/s]
SASRec epoch 1/8:   3%|▎         | 42/1500 [00:01<00:44, 32.92it/s]
SASRec epoch 1/8:   3%|▎         | 46/1500 [00:01<00:44, 32.96it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:01<00:43, 33.03it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:01<00:43, 33.03it/s, loss=9.89]
SASRec epoch 1/8:   4%|▎         | 54/1500 [00:01<00:44, 32.40it/s, loss=9.89]
SASRec epoch 1/8:   4%|▍         | 58/1500 [00:01<00:44, 32.14it/s, loss=9.89]
SASRec epoch 1/8:   4%|▍         | 62/1500 [00:01<00:43, 32.81it/s, loss=9.89]
SASRec epoch 1/8:   4%|▍         | 66/1500 [00:02<00:43, 33.21it/s, loss=9.89]
SASRec epoch 1/8:   5%|▍         | 70/1500 [00:02<00:42, 33.38it/s, loss=9.89]
SASRec epoch 1/8:   5%|▍         | 74/1500 [00:02<00:42, 33.50it/s, loss=9.89]
SASRec epoch 1/8:   5%|▌         | 78/1500 [00:02<00:42, 33.64it/s, loss=9.89]
SASRec epoch 1/8:   5%|▌         | 82/1500 [00:02<00:42, 33.76it/s, loss=9.89]
SASRec epoch 1/8:   6%|▌         | 86/1500 [00:02<00:41, 33.67it/s, loss=9.89]
SASRec epoch 1/8:   6%|▌         | 90/1500 [00:02<00:42, 33.46it/s, loss=9.89]
SASRec epoch 1/8:   6%|▋         | 94/1500 [00:02<00:42, 33.07it/s, loss=9.89]
SASRec epoch 1/8:   7%|▋         | 98/1500 [00:03<00:42, 33.15it/s, loss=9.89]
SASRec epoch 1/8:   7%|▋         | 100/1500 [00:03<00:42, 33.15it/s, loss=8.14]
SASRec epoch 1/8:   7%|▋         | 102/1500 [00:03<00:43, 32.24it/s, loss=8.14]
SASRec epoch 1/8:   7%|▋         | 106/1500 [00:03<00:42, 32.78it/s, loss=8.14]
SASRec epoch 1/8:   7%|▋         | 110/1500 [00:03<00:41, 33.11it/s, loss=8.14]
SASRec epoch 1/8:   8%|▊         | 114/1500 [00:03<00:41, 33.34it/s, loss=8.14]
SASRec epoch 1/8:   8%|▊         | 118/1500 [00:03<00:41, 33.17it/s, loss=8.14]
SASRec epoch 1/8:   8%|▊         | 122/1500 [00:03<00:41, 33.21it/s, loss=8.14]
SASRec epoch 1/8:   8%|▊         | 126/1500 [00:03<00:41, 32.97it/s, loss=8.14]
SASRec epoch 1/8:   9%|▊         | 130/1500 [00:04<00:41, 32.86it/s, loss=8.14]
SASRec epoch 1/8:   9%|▉         | 134/1500 [00:04<00:41, 32.98it/s, loss=8.14]
SASRec epoch 1/8:   9%|▉         | 138/1500 [00:04<00:41, 32.98it/s, loss=8.14]
SASRec epoch 1/8:   9%|▉         | 142/1500 [00:04<00:41, 33.12it/s, loss=8.14]
SASRec epoch 1/8:  10%|▉         | 146/1500 [00:04<00:40, 33.46it/s, loss=8.14]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:04<00:40, 33.19it/s, loss=8.14]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:04<00:40, 33.19it/s, loss=6.89]
SASRec epoch 1/8:  10%|█         | 154/1500 [00:04<00:41, 32.73it/s, loss=6.89]
SASRec epoch 1/8:  11%|█         | 158/1500 [00:04<00:41, 32.71it/s, loss=6.89]
SASRec epoch 1/8:  11%|█         | 162/1500 [00:04<00:41, 32.53it/s, loss=6.89]
SASRec epoch 1/8:  11%|█         | 166/1500 [00:05<00:40, 32.60it/s, loss=6.89]
SASRec epoch 1/8:  11%|█▏        | 170/1500 [00:05<00:41, 32.32it/s, loss=6.89]
SASRec epoch 1/8:  12%|█▏        | 174/1500 [00:05<00:40, 32.68it/s, loss=6.89]
SASRec epoch 1/8:  12%|█▏        | 178/1500 [00:05<00:40, 32.60it/s, loss=6.89]
SASRec epoch 1/8:  12%|█▏        | 182/1500 [00:05<00:40, 32.61it/s, loss=6.89]
SASRec epoch 1/8:  12%|█▏        | 186/1500 [00:05<00:40, 32.60it/s, loss=6.89]
SASRec epoch 1/8:  13%|█▎        | 190/1500 [00:05<00:39, 32.92it/s, loss=6.89]
SASRec epoch 1/8:  13%|█▎        | 194/1500 [00:05<00:39, 33.03it/s, loss=6.89]
SASRec epoch 1/8:  13%|█▎        | 198/1500 [00:06<00:39, 32.79it/s, loss=6.89]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:06<00:39, 32.79it/s, loss=5.79]
SASRec epoch 1/8:  13%|█▎        | 202/1500 [00:06<00:40, 32.30it/s, loss=5.79]
SASRec epoch 1/8:  14%|█▎        | 206/1500 [00:06<00:39, 32.43it/s, loss=5.79]
SASRec epoch 1/8:  14%|█▍        | 210/1500 [00:06<00:39, 32.53it/s, loss=5.79]
SASRec epoch 1/8:  14%|█▍        | 214/1500 [00:06<00:39, 32.74it/s, loss=5.79]
SASRec epoch 1/8:  15%|█▍        | 218/1500 [00:06<00:39, 32.63it/s, loss=5.79]
SASRec epoch 1/8:  15%|█▍        | 222/1500 [00:06<00:38, 32.99it/s, loss=5.79]
SASRec epoch 1/8:  15%|█▌        | 226/1500 [00:06<00:38, 33.12it/s, loss=5.79]
SASRec epoch 1/8:  15%|█▌        | 230/1500 [00:07<00:38, 32.80it/s, loss=5.79]
SASRec epoch 1/8:  16%|█▌        | 234/1500 [00:07<00:38, 32.87it/s, loss=5.79]
SASRec epoch 1/8:  16%|█▌        | 238/1500 [00:07<00:38, 32.87it/s, loss=5.79]
SASRec epoch 1/8:  16%|█▌        | 242/1500 [00:07<00:37, 33.25it/s, loss=5.79]
SASRec epoch 1/8:  16%|█▋        | 246/1500 [00:07<00:37, 33.48it/s, loss=5.79]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:07<00:37, 33.64it/s, loss=5.79]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:07<00:37, 33.64it/s, loss=4.99]
SASRec epoch 1/8:  17%|█▋        | 254/1500 [00:07<00:37, 33.31it/s, loss=4.99]
SASRec epoch 1/8:  17%|█▋        | 258/1500 [00:07<00:37, 33.40it/s, loss=4.99]
SASRec epoch 1/8:  17%|█▋        | 262/1500 [00:08<00:36, 33.68it/s, loss=4.99]
SASRec epoch 1/8:  18%|█▊        | 266/1500 [00:08<00:37, 33.33it/s, loss=4.99]
SASRec epoch 1/8:  18%|█▊        | 270/1500 [00:08<00:36, 33.66it/s, loss=4.99]
SASRec epoch 1/8:  18%|█▊        | 274/1500 [00:08<00:36, 33.62it/s, loss=4.99]
SASRec epoch 1/8:  19%|█▊        | 278/1500 [00:08<00:36, 33.70it/s, loss=4.99]
SASRec epoch 1/8:  19%|█▉        | 282/1500 [00:08<00:36, 33.64it/s, loss=4.99]
SASRec epoch 1/8:  19%|█▉        | 286/1500 [00:08<00:35, 33.73it/s, loss=4.99]
SASRec epoch 1/8:  19%|█▉        | 290/1500 [00:08<00:35, 33.78it/s, loss=4.99]
SASRec epoch 1/8:  20%|█▉        | 294/1500 [00:08<00:35, 33.79it/s, loss=4.99]
SASRec epoch 1/8:  20%|█▉        | 298/1500 [00:09<00:35, 33.77it/s, loss=4.99]
SASRec epoch 1/8:  20%|██        | 300/1500 [00:09<00:35, 33.77it/s, loss=4.27]
SASRec epoch 1/8:  20%|██        | 302/1500 [00:09<00:36, 32.87it/s, loss=4.27]
SASRec epoch 1/8:  20%|██        | 306/1500 [00:09<00:35, 33.32it/s, loss=4.27]
SASRec epoch 1/8:  21%|██        | 310/1500 [00:09<00:35, 33.21it/s, loss=4.27]
SASRec epoch 1/8:  21%|██        | 314/1500 [00:09<00:35, 33.11it/s, loss=4.27]
SASRec epoch 1/8:  21%|██        | 318/1500 [00:09<00:35, 33.16it/s, loss=4.27]
SASRec epoch 1/8:  21%|██▏       | 322/1500 [00:09<00:35, 33.19it/s, loss=4.27]
SASRec epoch 1/8:  22%|██▏       | 326/1500 [00:09<00:36, 31.73it/s, loss=4.27]
SASRec epoch 1/8:  22%|██▏       | 330/1500 [00:10<00:36, 31.67it/s, loss=4.27]
SASRec epoch 1/8:  22%|██▏       | 334/1500 [00:10<00:37, 30.96it/s, loss=4.27]
SASRec epoch 1/8:  23%|██▎       | 338/1500 [00:10<00:37, 30.89it/s, loss=4.27]
SASRec epoch 1/8:  23%|██▎       | 342/1500 [00:10<00:38, 30.15it/s, loss=4.27]
SASRec epoch 1/8:  23%|██▎       | 346/1500 [00:10<00:37, 30.47it/s, loss=4.27]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:10<00:37, 30.89it/s, loss=4.27]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:10<00:37, 30.89it/s, loss=3.84]
SASRec epoch 1/8:  24%|██▎       | 354/1500 [00:10<00:37, 30.55it/s, loss=3.84]
SASRec epoch 1/8:  24%|██▍       | 358/1500 [00:11<00:37, 30.78it/s, loss=3.84]
SASRec epoch 1/8:  24%|██▍       | 362/1500 [00:11<00:36, 31.04it/s, loss=3.84]
SASRec epoch 1/8:  24%|██▍       | 366/1500 [00:11<00:36, 31.09it/s, loss=3.84]
SASRec epoch 1/8:  25%|██▍       | 370/1500 [00:11<00:36, 31.10it/s, loss=3.84]
SASRec epoch 1/8:  25%|██▍       | 374/1500 [00:11<00:36, 31.22it/s, loss=3.84]
SASRec epoch 1/8:  25%|██▌       | 378/1500 [00:11<00:35, 31.33it/s, loss=3.84]
SASRec epoch 1/8:  25%|██▌       | 382/1500 [00:11<00:35, 31.30it/s, loss=3.84]
SASRec epoch 1/8:  26%|██▌       | 386/1500 [00:11<00:35, 31.05it/s, loss=3.84]
SASRec epoch 1/8:  26%|██▌       | 390/1500 [00:12<00:36, 30.68it/s, loss=3.84]
SASRec epoch 1/8:  26%|██▋       | 394/1500 [00:12<00:36, 30.69it/s, loss=3.84]
SASRec epoch 1/8:  27%|██▋       | 398/1500 [00:12<00:36, 30.46it/s, loss=3.84]
SASRec epoch 1/8:  27%|██▋       | 400/1500 [00:12<00:36, 30.46it/s, loss=3.52]
SASRec epoch 1/8:  27%|██▋       | 402/1500 [00:12<00:36, 29.88it/s, loss=3.52]
SASRec epoch 1/8:  27%|██▋       | 405/1500 [00:12<00:37, 29.25it/s, loss=3.52]
SASRec epoch 1/8:  27%|██▋       | 409/1500 [00:12<00:36, 29.73it/s, loss=3.52]
SASRec epoch 1/8:  27%|██▋       | 412/1500 [00:12<00:37, 29.32it/s, loss=3.52]
SASRec epoch 1/8:  28%|██▊       | 415/1500 [00:12<00:37, 28.98it/s, loss=3.52]
SASRec epoch 1/8:  28%|██▊       | 418/1500 [00:13<00:38, 28.39it/s, loss=3.52]
SASRec epoch 1/8:  28%|██▊       | 421/1500 [00:13<00:38, 28.27it/s, loss=3.52]
SASRec epoch 1/8:  28%|██▊       | 424/1500 [00:13<00:38, 27.96it/s, loss=3.52]
SASRec epoch 1/8:  28%|██▊       | 427/1500 [00:13<00:37, 28.49it/s, loss=3.52]
SASRec epoch 1/8:  29%|██▊       | 430/1500 [00:13<00:37, 28.84it/s, loss=3.52]
SASRec epoch 1/8:  29%|██▉       | 433/1500 [00:13<00:36, 28.91it/s, loss=3.52]
SASRec epoch 1/8:  29%|██▉       | 436/1500 [00:13<00:36, 29.14it/s, loss=3.52]
SASRec epoch 1/8:  29%|██▉       | 439/1500 [00:13<00:36, 29.25it/s, loss=3.52]
SASRec epoch 1/8:  30%|██▉       | 443/1500 [00:13<00:35, 29.72it/s, loss=3.52]
SASRec epoch 1/8:  30%|██▉       | 446/1500 [00:13<00:35, 29.77it/s, loss=3.52]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:14<00:34, 30.54it/s, loss=3.52]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:14<00:34, 30.54it/s, loss=3.32]
SASRec epoch 1/8:  30%|███       | 454/1500 [00:14<00:33, 30.86it/s, loss=3.32]
SASRec epoch 1/8:  31%|███       | 458/1500 [00:14<00:33, 31.52it/s, loss=3.32]
SASRec epoch 1/8:  31%|███       | 462/1500 [00:14<00:32, 31.84it/s, loss=3.32]
SASRec epoch 1/8:  31%|███       | 466/1500 [00:14<00:32, 32.19it/s, loss=3.32]
SASRec epoch 1/8:  31%|███▏      | 470/1500 [00:14<00:31, 32.19it/s, loss=3.32]
SASRec epoch 1/8:  32%|███▏      | 474/1500 [00:14<00:31, 32.33it/s, loss=3.32]
SASRec epoch 1/8:  32%|███▏      | 478/1500 [00:14<00:31, 32.44it/s, loss=3.32]
SASRec epoch 1/8:  32%|███▏      | 482/1500 [00:15<00:31, 32.38it/s, loss=3.32]
SASRec epoch 1/8:  32%|███▏      | 486/1500 [00:15<00:31, 32.34it/s, loss=3.32]
SASRec epoch 1/8:  33%|███▎      | 490/1500 [00:15<00:30, 32.63it/s, loss=3.32]
SASRec epoch 1/8:  33%|███▎      | 494/1500 [00:15<00:30, 32.78it/s, loss=3.32]
SASRec epoch 1/8:  33%|███▎      | 498/1500 [00:15<00:30, 32.94it/s, loss=3.32]
SASRec epoch 1/8:  33%|███▎      | 500/1500 [00:15<00:30, 32.94it/s, loss=3.14]
SASRec epoch 1/8:  33%|███▎      | 502/1500 [00:15<00:30, 32.44it/s, loss=3.14]
SASRec epoch 1/8:  34%|███▎      | 506/1500 [00:15<00:30, 32.24it/s, loss=3.14]
SASRec epoch 1/8:  34%|███▍      | 510/1500 [00:15<00:30, 32.60it/s, loss=3.14]
SASRec epoch 1/8:  34%|███▍      | 514/1500 [00:16<00:30, 32.78it/s, loss=3.14]
SASRec epoch 1/8:  35%|███▍      | 518/1500 [00:16<00:29, 32.93it/s, loss=3.14]
SASRec epoch 1/8:  35%|███▍      | 522/1500 [00:16<00:29, 33.02it/s, loss=3.14]
SASRec epoch 1/8:  35%|███▌      | 526/1500 [00:16<00:29, 33.02it/s, loss=3.14]
SASRec epoch 1/8:  35%|███▌      | 530/1500 [00:16<00:29, 33.11it/s, loss=3.14]
SASRec epoch 1/8:  36%|███▌      | 534/1500 [00:16<00:29, 33.02it/s, loss=3.14]
SASRec epoch 1/8:  36%|███▌      | 538/1500 [00:16<00:29, 32.77it/s, loss=3.14]
SASRec epoch 1/8:  36%|███▌      | 542/1500 [00:16<00:29, 32.80it/s, loss=3.14]
SASRec epoch 1/8:  36%|███▋      | 546/1500 [00:17<00:29, 32.78it/s, loss=3.14]
SASRec epoch 1/8:  37%|███▋      | 550/1500 [00:17<00:28, 32.92it/s, loss=3.14]
SASRec epoch 1/8:  37%|███▋      | 550/1500 [00:17<00:28, 32.92it/s, loss=3.03]
SASRec epoch 1/8:  37%|███▋      | 554/1500 [00:17<00:28, 32.76it/s, loss=3.03]
SASRec epoch 1/8:  37%|███▋      | 558/1500 [00:17<00:28, 32.63it/s, loss=3.03]
SASRec epoch 1/8:  37%|███▋      | 562/1500 [00:17<00:28, 32.93it/s, loss=3.03]
SASRec epoch 1/8:  38%|███▊      | 566/1500 [00:17<00:28, 33.00it/s, loss=3.03]
SASRec epoch 1/8:  38%|███▊      | 570/1500 [00:17<00:27, 33.28it/s, loss=3.03]
SASRec epoch 1/8:  38%|███▊      | 574/1500 [00:17<00:28, 32.92it/s, loss=3.03]
SASRec epoch 1/8:  39%|███▊      | 578/1500 [00:17<00:27, 33.13it/s, loss=3.03]
SASRec epoch 1/8:  39%|███▉      | 582/1500 [00:18<00:27, 33.37it/s, loss=3.03]
SASRec epoch 1/8:  39%|███▉      | 586/1500 [00:18<00:27, 33.53it/s, loss=3.03]
SASRec epoch 1/8:  39%|███▉      | 590/1500 [00:18<00:27, 33.67it/s, loss=3.03]
SASRec epoch 1/8:  40%|███▉      | 594/1500 [00:18<00:26, 33.61it/s, loss=3.03]
SASRec epoch 1/8:  40%|███▉      | 598/1500 [00:18<00:26, 33.62it/s, loss=3.03]
SASRec epoch 1/8:  40%|████      | 600/1500 [00:18<00:26, 33.62it/s, loss=2.89]
SASRec epoch 1/8:  40%|████      | 602/1500 [00:18<00:27, 32.61it/s, loss=2.89]
SASRec epoch 1/8:  40%|████      | 606/1500 [00:18<00:27, 32.35it/s, loss=2.89]
SASRec epoch 1/8:  41%|████      | 610/1500 [00:18<00:27, 32.63it/s, loss=2.89]
SASRec epoch 1/8:  41%|████      | 614/1500 [00:19<00:27, 32.79it/s, loss=2.89]
SASRec epoch 1/8:  41%|████      | 618/1500 [00:19<00:26, 32.85it/s, loss=2.89]
SASRec epoch 1/8:  41%|████▏     | 622/1500 [00:19<00:27, 31.63it/s, loss=2.89]
SASRec epoch 1/8:  42%|████▏     | 626/1500 [00:19<00:27, 32.06it/s, loss=2.89]
SASRec epoch 1/8:  42%|████▏     | 630/1500 [00:19<00:26, 32.64it/s, loss=2.89]
SASRec epoch 1/8:  42%|████▏     | 634/1500 [00:19<00:26, 32.59it/s, loss=2.89]
SASRec epoch 1/8:  43%|████▎     | 638/1500 [00:19<00:26, 32.93it/s, loss=2.89]
SASRec epoch 1/8:  43%|████▎     | 642/1500 [00:19<00:26, 32.53it/s, loss=2.89]
SASRec epoch 1/8:  43%|████▎     | 646/1500 [00:20<00:26, 32.83it/s, loss=2.89]
SASRec epoch 1/8:  43%|████▎     | 650/1500 [00:20<00:25, 32.84it/s, loss=2.89]
SASRec epoch 1/8:  43%|████▎     | 650/1500 [00:20<00:25, 32.84it/s, loss=2.75]
SASRec epoch 1/8:  44%|████▎     | 654/1500 [00:20<00:26, 32.30it/s, loss=2.75]
SASRec epoch 1/8:  44%|████▍     | 658/1500 [00:20<00:25, 32.55it/s, loss=2.75]
SASRec epoch 1/8:  44%|████▍     | 662/1500 [00:20<00:25, 32.91it/s, loss=2.75]
SASRec epoch 1/8:  44%|████▍     | 666/1500 [00:20<00:25, 32.84it/s, loss=2.75]
SASRec epoch 1/8:  45%|████▍     | 670/1500 [00:20<00:25, 32.86it/s, loss=2.75]
SASRec epoch 1/8:  45%|████▍     | 674/1500 [00:20<00:25, 32.50it/s, loss=2.75]
SASRec epoch 1/8:  45%|████▌     | 678/1500 [00:21<00:25, 32.83it/s, loss=2.75]
SASRec epoch 1/8:  45%|████▌     | 682/1500 [00:21<00:24, 32.88it/s, loss=2.75]
SASRec epoch 1/8:  46%|████▌     | 686/1500 [00:21<00:24, 32.90it/s, loss=2.75]
SASRec epoch 1/8:  46%|████▌     | 690/1500 [00:21<00:24, 32.95it/s, loss=2.75]
SASRec epoch 1/8:  46%|████▋     | 694/1500 [00:21<00:24, 33.16it/s, loss=2.75]
SASRec epoch 1/8:  47%|████▋     | 698/1500 [00:21<00:24, 33.26it/s, loss=2.75]
SASRec epoch 1/8:  47%|████▋     | 700/1500 [00:21<00:24, 33.26it/s, loss=2.62]
SASRec epoch 1/8:  47%|████▋     | 702/1500 [00:21<00:24, 32.92it/s, loss=2.62]
SASRec epoch 1/8:  47%|████▋     | 706/1500 [00:21<00:23, 33.30it/s, loss=2.62]
SASRec epoch 1/8:  47%|████▋     | 710/1500 [00:22<00:24, 32.89it/s, loss=2.62]
SASRec epoch 1/8:  48%|████▊     | 714/1500 [00:22<00:23, 32.92it/s, loss=2.62]
SASRec epoch 1/8:  48%|████▊     | 718/1500 [00:22<00:23, 33.22it/s, loss=2.62]
SASRec epoch 1/8:  48%|████▊     | 722/1500 [00:22<00:23, 33.43it/s, loss=2.62]
SASRec epoch 1/8:  48%|████▊     | 726/1500 [00:22<00:23, 33.30it/s, loss=2.62]
SASRec epoch 1/8:  49%|████▊     | 730/1500 [00:22<00:23, 33.05it/s, loss=2.62]
SASRec epoch 1/8:  49%|████▉     | 734/1500 [00:22<00:23, 33.30it/s, loss=2.62]
SASRec epoch 1/8:  49%|████▉     | 738/1500 [00:22<00:22, 33.36it/s, loss=2.62]
SASRec epoch 1/8:  49%|████▉     | 742/1500 [00:22<00:22, 33.47it/s, loss=2.62]
SASRec epoch 1/8:  50%|████▉     | 746/1500 [00:23<00:22, 33.14it/s, loss=2.62]
SASRec epoch 1/8:  50%|█████     | 750/1500 [00:23<00:22, 33.20it/s, loss=2.62]
SASRec epoch 1/8:  50%|█████     | 750/1500 [00:23<00:22, 33.20it/s, loss=2.52]
SASRec epoch 1/8:  50%|█████     | 754/1500 [00:23<00:22, 32.64it/s, loss=2.52]
SASRec epoch 1/8:  51%|█████     | 758/1500 [00:23<00:22, 32.85it/s, loss=2.52]
SASRec epoch 1/8:  51%|█████     | 762/1500 [00:23<00:22, 32.97it/s, loss=2.52]
SASRec epoch 1/8:  51%|█████     | 766/1500 [00:23<00:22, 32.96it/s, loss=2.52]
SASRec epoch 1/8:  51%|█████▏    | 770/1500 [00:23<00:22, 33.07it/s, loss=2.52]
SASRec epoch 1/8:  52%|█████▏    | 774/1500 [00:23<00:21, 33.11it/s, loss=2.52]
SASRec epoch 1/8:  52%|█████▏    | 778/1500 [00:24<00:22, 32.23it/s, loss=2.52]
SASRec epoch 1/8:  52%|█████▏    | 782/1500 [00:24<00:23, 30.91it/s, loss=2.52]
SASRec epoch 1/8:  52%|█████▏    | 786/1500 [00:24<00:23, 30.98it/s, loss=2.52]
SASRec epoch 1/8:  53%|█████▎    | 790/1500 [00:24<00:22, 30.90it/s, loss=2.52]
SASRec epoch 1/8:  53%|█████▎    | 794/1500 [00:24<00:22, 31.04it/s, loss=2.52]
SASRec epoch 1/8:  53%|█████▎    | 798/1500 [00:24<00:22, 31.18it/s, loss=2.52]
SASRec epoch 1/8:  53%|█████▎    | 800/1500 [00:24<00:22, 31.18it/s, loss=2.47]
SASRec epoch 1/8:  53%|█████▎    | 802/1500 [00:24<00:22, 30.97it/s, loss=2.47]
SASRec epoch 1/8:  54%|█████▎    | 806/1500 [00:24<00:22, 30.94it/s, loss=2.47]
SASRec epoch 1/8:  54%|█████▍    | 810/1500 [00:25<00:22, 30.75it/s, loss=2.47]
SASRec epoch 1/8:  54%|█████▍    | 814/1500 [00:25<00:22, 30.24it/s, loss=2.47]
SASRec epoch 1/8:  55%|█████▍    | 818/1500 [00:25<00:22, 29.93it/s, loss=2.47]
SASRec epoch 1/8:  55%|█████▍    | 821/1500 [00:25<00:22, 29.91it/s, loss=2.47]
SASRec epoch 1/8:  55%|█████▍    | 824/1500 [00:25<00:22, 29.89it/s, loss=2.47]
SASRec epoch 1/8:  55%|█████▌    | 828/1500 [00:25<00:22, 30.17it/s, loss=2.47]
SASRec epoch 1/8:  55%|█████▌    | 832/1500 [00:25<00:22, 29.82it/s, loss=2.47]
SASRec epoch 1/8:  56%|█████▌    | 835/1500 [00:25<00:22, 29.82it/s, loss=2.47]
SASRec epoch 1/8:  56%|█████▌    | 838/1500 [00:26<00:22, 29.50it/s, loss=2.47]
SASRec epoch 1/8:  56%|█████▌    | 842/1500 [00:26<00:22, 29.76it/s, loss=2.47]
SASRec epoch 1/8:  56%|█████▋    | 845/1500 [00:26<00:22, 29.25it/s, loss=2.47]
SASRec epoch 1/8:  57%|█████▋    | 848/1500 [00:26<00:22, 29.33it/s, loss=2.47]
SASRec epoch 1/8:  57%|█████▋    | 850/1500 [00:26<00:22, 29.33it/s, loss=2.42]
SASRec epoch 1/8:  57%|█████▋    | 851/1500 [00:26<00:22, 29.28it/s, loss=2.42]
SASRec epoch 1/8:  57%|█████▋    | 854/1500 [00:26<00:22, 29.16it/s, loss=2.42]
SASRec epoch 1/8:  57%|█████▋    | 857/1500 [00:26<00:22, 28.94it/s, loss=2.42]
SASRec epoch 1/8:  57%|█████▋    | 861/1500 [00:26<00:21, 29.56it/s, loss=2.42]
SASRec epoch 1/8:  58%|█████▊    | 865/1500 [00:26<00:21, 29.97it/s, loss=2.42]
SASRec epoch 1/8:  58%|█████▊    | 869/1500 [00:27<00:20, 30.18it/s, loss=2.42]
SASRec epoch 1/8:  58%|█████▊    | 873/1500 [00:27<00:20, 30.33it/s, loss=2.42]
SASRec epoch 1/8:  58%|█████▊    | 877/1500 [00:27<00:21, 29.56it/s, loss=2.42]
SASRec epoch 1/8:  59%|█████▊    | 880/1500 [00:27<00:21, 28.60it/s, loss=2.42]
SASRec epoch 1/8:  59%|█████▉    | 883/1500 [00:27<00:21, 28.53it/s, loss=2.42]
SASRec epoch 1/8:  59%|█████▉    | 886/1500 [00:27<00:21, 28.37it/s, loss=2.42]
SASRec epoch 1/8:  59%|█████▉    | 889/1500 [00:27<00:21, 28.00it/s, loss=2.42]
SASRec epoch 1/8:  59%|█████▉    | 892/1500 [00:27<00:22, 27.03it/s, loss=2.42]
SASRec epoch 1/8:  60%|█████▉    | 895/1500 [00:28<00:22, 27.47it/s, loss=2.42]
SASRec epoch 1/8:  60%|█████▉    | 898/1500 [00:28<00:22, 27.34it/s, loss=2.42]
SASRec epoch 1/8:  60%|██████    | 900/1500 [00:28<00:21, 27.34it/s, loss=2.36]
SASRec epoch 1/8:  60%|██████    | 901/1500 [00:28<00:22, 26.86it/s, loss=2.36]

[SASRec] epoch 1/8 loss=3.3195

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 2/8:   0%|          | 4/1500 [00:00<00:44, 33.98it/s]
SASRec epoch 2/8:   1%|          | 8/1500 [00:00<00:44, 33.55it/s]
SASRec epoch 2/8:   1%|          | 12/1500 [00:00<00:44, 33.14it/s]
SASRec epoch 2/8:   1%|          | 16/1500 [00:00<00:45, 32.64it/s]
SASRec epoch 2/8:   1%|▏         | 20/1500 [00:00<00:45, 32.60it/s]
SASRec epoch 2/8:   2%|▏         | 24/1500 [00:00<00:45, 32.72it/s]
SASRec epoch 2/8:   2%|▏         | 28/1500 [00:00<00:44, 32.96it/s]
SASRec epoch 2/8:   2%|▏         | 32/1500 [00:00<00:44, 33.29it/s]
SASRec epoch 2/8:   2%|▏         | 36/1500 [00:01<00:43, 33.44it/s]
SASRec epoch 2/8:   3%|▎         | 40/1500 [00:01<00:43, 33.61it/s]
SASRec epoch 2/8:   3%|▎         | 44/1500 [00:01<00:42, 33.89it/s]
SASRec epoch 2/8:   3%|▎         | 48/1500 [00:01<00:42, 33.97it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:01<00:42, 33.97it/s, loss=1.83]
SASRec epoch 2/8:   3%|▎         | 52/1500 [00:01<00:44, 32.42it/s, loss=1.83]
SASRec epoch 2/8:   4%|▎         | 56/1500 [00:01<00:44, 32.56it/s, loss=1.83]
SASRec epoch 2/8:   4%|▍         | 60/1500 [00:01<00:44, 32.51it/s, loss=1.83]
SASRec epoch 2/8:   4%|▍         | 64/1500 [00:01<00:43, 32.72it/s, loss=1.83]
SASRec epoch 2/8:   5%|▍         | 68/1500 [00:02<00:43, 32.74it/s, loss=1.83]
SASRec epoch 2/8:   5%|▍         | 72/1500 [00:02<00:43, 33.10it/s, loss=1.83]
SASRec epoch 2/8:   5%|▌         | 76/1500 [00:02<00:42, 33.21it/s, loss=1.83]
SASRec epoch 2/8:   5%|▌         | 80/1500 [00:02<00:44, 32.13it/s, loss=1.83]
SASRec epoch 2/8:   6%|▌         | 84/1500 [00:02<00:43, 32.18it/s, loss=1.83]
SASRec epoch 2/8:   6%|▌         | 88/1500 [00:02<00:44, 31.91it/s, loss=1.83]
SASRec epoch 2/8:   6%|▌         | 92/1500 [00:02<00:43, 32.17it/s, loss=1.83]
SASRec epoch 2/8:   6%|▋         | 96/1500 [00:02<00:43, 32.37it/s, loss=1.83]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:03<00:42, 32.57it/s, loss=1.83]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:03<00:42, 32.57it/s, loss=1.85]
SASRec epoch 2/8:   7%|▋         | 104/1500 [00:03<00:43, 32.03it/s, loss=1.85]
SASRec epoch 2/8:   7%|▋         | 108/1500 [00:03<00:43, 32.27it/s, loss=1.85]
SASRec epoch 2/8:   7%|▋         | 112/1500 [00:03<00:42, 32.56it/s, loss=1.85]
SASRec epoch 2/8:   8%|▊         | 116/1500 [00:03<00:42, 32.70it/s, loss=1.85]
SASRec epoch 2/8:   8%|▊         | 120/1500 [00:03<00:42, 32.28it/s, loss=1.85]
SASRec epoch 2/8:   8%|▊         | 124/1500 [00:03<00:42, 32.62it/s, loss=1.85]
SASRec epoch 2/8:   9%|▊         | 128/1500 [00:03<00:41, 32.86it/s, loss=1.85]
SASRec epoch 2/8:   9%|▉         | 132/1500 [00:04<00:41, 32.96it/s, loss=1.85]
SASRec epoch 2/8:   9%|▉         | 136/1500 [00:04<00:41, 33.08it/s, loss=1.85]
SASRec epoch 2/8:   9%|▉         | 140/1500 [00:04<00:41, 33.15it/s, loss=1.85]
SASRec epoch 2/8:  10%|▉         | 144/1500 [00:04<00:41, 32.94it/s, loss=1.85]
SASRec epoch 2/8:  10%|▉         | 148/1500 [00:04<00:40, 33.32it/s, loss=1.85]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:04<00:40, 33.32it/s, loss=1.83]
SASRec epoch 2/8:  10%|█         | 152/1500 [00:04<00:41, 32.18it/s, loss=1.83]
SASRec epoch 2/8:  10%|█         | 156/1500 [00:04<00:41, 32.77it/s, loss=1.83]
SASRec epoch 2/8:  11%|█         | 160/1500 [00:04<00:40, 33.06it/s, loss=1.83]
SASRec epoch 2/8:  11%|█         | 164/1500 [00:04<00:40, 33.39it/s, loss=1.83]
SASRec epoch 2/8:  11%|█         | 168/1500 [00:05<00:40, 33.20it/s, loss=1.83]
SASRec epoch 2/8:  11%|█▏        | 172/1500 [00:05<00:40, 32.97it/s, loss=1.83]
SASRec epoch 2/8:  12%|█▏        | 176/1500 [00:05<00:40, 32.97it/s, loss=1.83]
SASRec epoch 2/8:  12%|█▏        | 180/1500 [00:05<00:39, 33.18it/s, loss=1.83]
SASRec epoch 2/8:  12%|█▏        | 184/1500 [00:05<00:39, 33.33it/s, loss=1.83]
SASRec epoch 2/8:  13%|█▎        | 188/1500 [00:05<00:39, 33.01it/s, loss=1.83]
SASRec epoch 2/8:  13%|█▎        | 192/1500 [00:05<00:39, 33.35it/s, loss=1.83]
SASRec epoch 2/8:  13%|█▎        | 196/1500 [00:05<00:40, 32.14it/s, loss=1.83]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:06<00:41, 31.06it/s, loss=1.83]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:06<00:41, 31.06it/s, loss=1.79]
SASRec epoch 2/8:  14%|█▎        | 204/1500 [00:06<00:42, 30.15it/s, loss=1.79]
SASRec epoch 2/8:  14%|█▍        | 208/1500 [00:06<00:42, 30.11it/s, loss=1.79]
SASRec epoch 2/8:  14%|█▍        | 212/1500 [00:06<00:42, 30.02it/s, loss=1.79]
SASRec epoch 2/8:  14%|█▍        | 216/1500 [00:06<00:43, 29.77it/s, loss=1.79]
SASRec epoch 2/8:  15%|█▍        | 219/1500 [00:06<00:43, 29.25it/s, loss=1.79]
SASRec epoch 2/8:  15%|█▍        | 222/1500 [00:06<00:43, 29.15it/s, loss=1.79]
SASRec epoch 2/8:  15%|█▌        | 225/1500 [00:06<00:43, 29.26it/s, loss=1.79]
SASRec epoch 2/8:  15%|█▌        | 228/1500 [00:07<00:43, 29.31it/s, loss=1.79]
SASRec epoch 2/8:  15%|█▌        | 232/1500 [00:07<00:42, 29.80it/s, loss=1.79]
SASRec epoch 2/8:  16%|█▌        | 235/1500 [00:07<00:43, 29.39it/s, loss=1.79]
SASRec epoch 2/8:  16%|█▌        | 239/1500 [00:07<00:42, 29.86it/s, loss=1.79]
SASRec epoch 2/8:  16%|█▌        | 242/1500 [00:07<00:42, 29.76it/s, loss=1.79]
SASRec epoch 2/8:  16%|█▋        | 245/1500 [00:07<00:43, 29.17it/s, loss=1.79]
SASRec epoch 2/8:  17%|█▋        | 248/1500 [00:07<00:42, 29.16it/s, loss=1.79]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:07<00:42, 29.16it/s, loss=1.78]
SASRec epoch 2/8:  17%|█▋        | 251/1500 [00:07<00:43, 28.65it/s, loss=1.78]
SASRec epoch 2/8:  17%|█▋        | 255/1500 [00:07<00:42, 29.47it/s, loss=1.78]
SASRec epoch 2/8:  17%|█▋        | 259/1500 [00:08<00:41, 29.91it/s, loss=1.78]
SASRec epoch 2/8:  17%|█▋        | 262/1500 [00:08<00:41, 29.91it/s, loss=1.78]
SASRec epoch 2/8:  18%|█▊        | 266/1500 [00:08<00:40, 30.18it/s, loss=1.78]
SASRec epoch 2/8:  18%|█▊        | 270/1500 [00:08<00:40, 30.47it/s, loss=1.78]
SASRec epoch 2/8:  18%|█▊        | 274/1500 [00:08<00:40, 30.64it/s, loss=1.78]
SASRec epoch 2/8:  19%|█▊        | 278/1500 [00:08<00:39, 30.77it/s, loss=1.78]
SASRec epoch 2/8:  19%|█▉        | 282/1500 [00:08<00:39, 30.84it/s, loss=1.78]
SASRec epoch 2/8:  19%|█▉        | 286/1500 [00:09<00:40, 29.81it/s, loss=1.78]
SASRec epoch 2/8:  19%|█▉        | 289/1500 [00:09<00:40, 29.61it/s, loss=1.78]
SASRec epoch 2/8:  19%|█▉        | 292/1500 [00:09<00:41, 28.99it/s, loss=1.78]
SASRec epoch 2/8:  20%|█▉        | 295/1500 [00:09<00:42, 28.34it/s, loss=1.78]
SASRec epoch 2/8:  20%|█▉        | 298/1500 [00:09<00:41, 28.74it/s, loss=1.78]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:09<00:41, 28.74it/s, loss=1.75]
SASRec epoch 2/8:  20%|██        | 301/1500 [00:09<00:41, 28.76it/s, loss=1.75]
SASRec epoch 2/8:  20%|██        | 304/1500 [00:09<00:41, 29.09it/s, loss=1.75]
SASRec epoch 2/8:  20%|██        | 307/1500 [00:09<00:40, 29.32it/s, loss=1.75]
SASRec epoch 2/8:  21%|██        | 310/1500 [00:09<00:40, 29.46it/s, loss=1.75]
SASRec epoch 2/8:  21%|██        | 314/1500 [00:09<00:39, 29.70it/s, loss=1.75]
SASRec epoch 2/8:  21%|██        | 317/1500 [00:10<00:41, 28.26it/s, loss=1.75]
SASRec epoch 2/8:  21%|██▏       | 320/1500 [00:10<00:42, 27.77it/s, loss=1.75]
SASRec epoch 2/8:  22%|██▏       | 323/1500 [00:10<00:41, 28.18it/s, loss=1.75]
SASRec epoch 2/8:  22%|██▏       | 327/1500 [00:10<00:39, 29.58it/s, loss=1.75]
SASRec epoch 2/8:  22%|██▏       | 331/1500 [00:10<00:37, 30.81it/s, loss=1.75]
SASRec epoch 2/8:  22%|██▏       | 335/1500 [00:10<00:37, 31.36it/s, loss=1.75]
SASRec epoch 2/8:  23%|██▎       | 339/1500 [00:10<00:35, 32.31it/s, loss=1.75]
SASRec epoch 2/8:  23%|██▎       | 343/1500 [00:10<00:35, 32.90it/s, loss=1.75]
SASRec epoch 2/8:  23%|██▎       | 347/1500 [00:11<00:34, 33.13it/s, loss=1.75]
SASRec epoch 2/8:  23%|██▎       | 350/1500 [00:11<00:34, 33.13it/s, loss=1.78]
SASRec epoch 2/8:  23%|██▎       | 351/1500 [00:11<00:35, 32.29it/s, loss=1.78]
SASRec epoch 2/8:  24%|██▎       | 355/1500 [00:11<00:35, 32.67it/s, loss=1.78]
SASRec epoch 2/8:  24%|██▍       | 359/1500 [00:11<00:34, 32.96it/s, loss=1.78]
SASRec epoch 2/8:  24%|██▍       | 363/1500 [00:11<00:34, 33.02it/s, loss=1.78]
SASRec epoch 2/8:  24%|██▍       | 367/1500 [00:11<00:34, 32.95it/s, loss=1.78]
SASRec epoch 2/8:  25%|██▍       | 371/1500 [00:11<00:34, 32.92it/s, loss=1.78]
SASRec epoch 2/8:  25%|██▌       | 375/1500 [00:11<00:34, 32.86it/s, loss=1.78]
SASRec epoch 2/8:  25%|██▌       | 379/1500 [00:12<00:33, 32.99it/s, loss=1.78]
SASRec epoch 2/8:  26%|██▌       | 383/1500 [00:12<00:34, 32.71it/s, loss=1.78]
SASRec epoch 2/8:  26%|██▌       | 387/1500 [00:12<00:33, 32.74it/s, loss=1.78]
SASRec epoch 2/8:  26%|██▌       | 391/1500 [00:12<00:33, 32.77it/s, loss=1.78]
SASRec epoch 2/8:  26%|██▋       | 395/1500 [00:12<00:33, 33.20it/s, loss=1.78]
SASRec epoch 2/8:  27%|██▋       | 399/1500 [00:12<00:33, 33.10it/s, loss=1.78]
SASRec epoch 2/8:  27%|██▋       | 400/1500 [00:12<00:33, 33.10it/s, loss=1.73]
SASRec epoch 2/8:  27%|██▋       | 403/1500 [00:12<00:33, 32.86it/s, loss=1.73]
SASRec epoch 2/8:  27%|██▋       | 407/1500 [00:12<00:33, 33.12it/s, loss=1.73]
SASRec epoch 2/8:  27%|██▋       | 411/1500 [00:12<00:32, 33.16it/s, loss=1.73]
SASRec epoch 2/8:  28%|██▊       | 415/1500 [00:13<00:32, 33.29it/s, loss=1.73]
SASRec epoch 2/8:  28%|██▊       | 419/1500 [00:13<00:32, 33.14it/s, loss=1.73]
SASRec epoch 2/8:  28%|██▊       | 423/1500 [00:13<00:32, 33.34it/s, loss=1.73]
SASRec epoch 2/8:  28%|██▊       | 427/1500 [00:13<00:32, 33.43it/s, loss=1.73]
SASRec epoch 2/8:  29%|██▊       | 431/1500 [00:13<00:32, 33.40it/s, loss=1.73]
SASRec epoch 2/8:  29%|██▉       | 435/1500 [00:13<00:32, 32.86it/s, loss=1.73]
SASRec epoch 2/8:  29%|██▉       | 439/1500 [00:13<00:32, 32.88it/s, loss=1.73]
SASRec epoch 2/8:  30%|██▉       | 443/1500 [00:13<00:32, 32.89it/s, loss=1.73]
SASRec epoch 2/8:  30%|██▉       | 447/1500 [00:14<00:31, 33.11it/s, loss=1.73]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:14<00:31, 33.11it/s, loss=1.72]
SASRec epoch 2/8:  30%|███       | 451/1500 [00:14<00:32, 32.11it/s, loss=1.72]
SASRec epoch 2/8:  30%|███       | 455/1500 [00:14<00:32, 32.04it/s, loss=1.72]
SASRec epoch 2/8:  31%|███       | 459/1500 [00:14<00:32, 32.09it/s, loss=1.72]
SASRec epoch 2/8:  31%|███       | 463/1500 [00:14<00:32, 32.30it/s, loss=1.72]
SASRec epoch 2/8:  31%|███       | 467/1500 [00:14<00:31, 32.43it/s, loss=1.72]
SASRec epoch 2/8:  31%|███▏      | 471/1500 [00:14<00:31, 32.72it/s, loss=1.72]
SASRec epoch 2/8:  32%|███▏      | 475/1500 [00:14<00:31, 32.80it/s, loss=1.72]
SASRec epoch 2/8:  32%|███▏      | 479/1500 [00:15<00:31, 32.81it/s, loss=1.72]
SASRec epoch 2/8:  32%|███▏      | 483/1500 [00:15<00:30, 32.92it/s, loss=1.72]
SASRec epoch 2/8:  32%|███▏      | 487/1500 [00:15<00:30, 32.68it/s, loss=1.72]
SASRec epoch 2/8:  33%|███▎      | 491/1500 [00:15<00:30, 32.88it/s, loss=1.72]
SASRec epoch 2/8:  33%|███▎      | 495/1500 [00:15<00:30, 32.99it/s, loss=1.72]
SASRec epoch 2/8:  33%|███▎      | 499/1500 [00:15<00:30, 32.88it/s, loss=1.72]
SASRec epoch 2/8:  33%|███▎      | 500/1500 [00:15<00:30, 32.88it/s, loss=1.71]
SASRec epoch 2/8:  34%|███▎      | 503/1500 [00:15<00:30, 32.19it/s, loss=1.71]
SASRec epoch 2/8:  34%|███▍      | 507/1500 [00:15<00:30, 32.39it/s, loss=1.71]
SASRec epoch 2/8:  34%|███▍      | 511/1500 [00:16<00:30, 32.40it/s, loss=1.71]
SASRec epoch 2/8:  34%|███▍      | 515/1500 [00:16<00:30, 32.57it/s, loss=1.71]
SASRec epoch 2/8:  35%|███▍      | 519/1500 [00:16<00:29, 32.84it/s, loss=1.71]
SASRec epoch 2/8:  35%|███▍      | 523/1500 [00:16<00:30, 32.46it/s, loss=1.71]
SASRec epoch 2/8:  35%|███▌      | 527/1500 [00:16<00:29, 32.79it/s, loss=1.71]
SASRec epoch 2/8:  35%|███▌      | 531/1500 [00:16<00:29, 32.51it/s, loss=1.71]
SASRec epoch 2/8:  36%|███▌      | 535/1500 [00:16<00:29, 32.68it/s, loss=1.71]
SASRec epoch 2/8:  36%|███▌      | 539/1500 [00:16<00:29, 32.67it/s, loss=1.71]
SASRec epoch 2/8:  36%|███▌      | 543/1500 [00:17<00:29, 32.78it/s, loss=1.71]
SASRec epoch 2/8:  36%|███▋      | 547/1500 [00:17<00:28, 32.95it/s, loss=1.71]
SASRec epoch 2/8:  37%|███▋      | 550/1500 [00:17<00:28, 32.95it/s, loss=1.68]
SASRec epoch 2/8:  37%|███▋      | 551/1500 [00:17<00:29, 32.21it/s, loss=1.68]
SASRec epoch 2/8:  37%|███▋      | 555/1500 [00:17<00:29, 32.07it/s, loss=1.68]
SASRec epoch 2/8:  37%|███▋      | 559/1500 [00:17<00:29, 32.37it/s, loss=1.68]
SASRec epoch 2/8:  38%|███▊      | 563/1500 [00:17<00:28, 32.61it/s, loss=1.68]
SASRec epoch 2/8:  38%|███▊      | 567/1500 [00:17<00:28, 32.56it/s, loss=1.68]
SASRec epoch 2/8:  38%|███▊      | 571/1500 [00:17<00:28, 32.87it/s, loss=1.68]
SASRec epoch 2/8:  38%|███▊      | 575/1500 [00:17<00:28, 32.59it/s, loss=1.68]
SASRec epoch 2/8:  39%|███▊      | 579/1500 [00:18<00:28, 32.82it/s, loss=1.68]
SASRec epoch 2/8:  39%|███▉      | 583/1500 [00:18<00:27, 32.88it/s, loss=1.68]
SASRec epoch 2/8:  39%|███▉      | 587/1500 [00:18<00:27, 33.03it/s, loss=1.68]
SASRec epoch 2/8:  39%|███▉      | 591/1500 [00:18<00:27, 32.53it/s, loss=1.68]
SASRec epoch 2/8:  40%|███▉      | 595/1500 [00:18<00:27, 32.77it/s, loss=1.68]
SASRec epoch 2/8:  40%|███▉      | 599/1500 [00:18<00:27, 32.64it/s, loss=1.68]
SASRec epoch 2/8:  40%|████      | 600/1500 [00:18<00:27, 32.64it/s, loss=1.66]
SASRec epoch 2/8:  40%|████      | 603/1500 [00:18<00:27, 32.33it/s, loss=1.66]
SASRec epoch 2/8:  40%|████      | 607/1500 [00:18<00:27, 32.58it/s, loss=1.66]
SASRec epoch 2/8:  41%|████      | 611/1500 [00:19<00:27, 32.68it/s, loss=1.66]
SASRec epoch 2/8:  41%|████      | 615/1500 [00:19<00:27, 32.74it/s, loss=1.66]
SASRec epoch 2/8:  41%|████▏     | 619/1500 [00:19<00:27, 32.61it/s, loss=1.66]
SASRec epoch 2/8:  42%|████▏     | 623/1500 [00:19<00:27, 32.29it/s, loss=1.66]
SASRec epoch 2/8:  42%|████▏     | 627/1500 [00:19<00:26, 32.59it/s, loss=1.66]
SASRec epoch 2/8:  42%|████▏     | 631/1500 [00:19<00:26, 32.90it/s, loss=1.66]
SASRec epoch 2/8:  42%|████▏     | 635/1500 [00:19<00:26, 33.23it/s, loss=1.66]
SASRec epoch 2/8:  43%|████▎     | 639/1500 [00:19<00:25, 33.44it/s, loss=1.66]
SASRec epoch 2/8:  43%|████▎     | 643/1500 [00:20<00:25, 33.48it/s, loss=1.66]
SASRec epoch 2/8:  43%|████▎     | 647/1500 [00:20<00:25, 33.32it/s, loss=1.66]
SASRec epoch 2/8:  43%|████▎     | 650/1500 [00:20<00:25, 33.32it/s, loss=1.67]
SASRec epoch 2/8:  43%|████▎     | 651/1500 [00:20<00:26, 31.86it/s, loss=1.67]
SASRec epoch 2/8:  44%|████▎     | 655/1500 [00:20<00:27, 31.30it/s, loss=1.67]
SASRec epoch 2/8:  44%|████▍     | 659/1500 [00:20<00:27, 30.51it/s, loss=1.67]
SASRec epoch 2/8:  44%|████▍     | 663/1500 [00:20<00:28, 29.88it/s, loss=1.67]
SASRec epoch 2/8:  44%|████▍     | 667/1500 [00:20<00:27, 30.39it/s, loss=1.67]
SASRec epoch 2/8:  45%|████▍     | 671/1500 [00:20<00:27, 30.52it/s, loss=1.67]
SASRec epoch 2/8:  45%|████▌     | 675/1500 [00:21<00:27, 30.27it/s, loss=1.67]
SASRec epoch 2/8:  45%|████▌     | 679/1500 [00:21<00:27, 30.32it/s, loss=1.67]
SASRec epoch 2/8:  46%|████▌     | 683/1500 [00:21<00:26, 30.39it/s, loss=1.67]
SASRec epoch 2/8:  46%|████▌     | 687/1500 [00:21<00:26, 30.45it/s, loss=1.67]
SASRec epoch 2/8:  46%|████▌     | 691/1500 [00:21<00:26, 30.23it/s, loss=1.67]
SASRec epoch 2/8:  46%|████▋     | 695/1500 [00:21<00:26, 30.05it/s, loss=1.67]
SASRec epoch 2/8:  47%|████▋     | 699/1500 [00:21<00:26, 29.97it/s, loss=1.67]
SASRec epoch 2/8:  47%|████▋     | 700/1500 [00:21<00:26, 29.97it/s, loss=1.65]
SASRec epoch 2/8:  47%|████▋     | 703/1500 [00:22<00:26, 30.23it/s, loss=1.65]
SASRec epoch 2/8:  47%|████▋     | 707/1500 [00:22<00:25, 30.58it/s, loss=1.65]
SASRec epoch 2/8:  47%|████▋     | 711/1500 [00:22<00:26, 29.80it/s, loss=1.65]
SASRec epoch 2/8:  48%|████▊     | 714/1500 [00:22<00:26, 29.49it/s, loss=1.65]
SASRec epoch 2/8:  48%|████▊     | 717/1500 [00:22<00:26, 29.04it/s, loss=1.65]
SASRec epoch 2/8:  48%|████▊     | 720/1500 [00:22<00:26, 29.12it/s, loss=1.65]
SASRec epoch 2/8:  48%|████▊     | 723/1500 [00:22<00:27, 28.70it/s, loss=1.65]
SASRec epoch 2/8:  48%|████▊     | 727/1500 [00:22<00:26, 29.42it/s, loss=1.65]
SASRec epoch 2/8:  49%|████▊     | 731/1500 [00:23<00:25, 29.98it/s, loss=1.65]
SASRec epoch 2/8:  49%|████▉     | 734/1500 [00:23<00:25, 29.74it/s, loss=1.65]
SASRec epoch 2/8:  49%|████▉     | 738/1500 [00:23<00:25, 30.40it/s, loss=1.65]
SASRec epoch 2/8:  49%|████▉     | 742/1500 [00:23<00:24, 30.69it/s, loss=1.65]
SASRec epoch 2/8:  50%|████▉     | 746/1500 [00:23<00:25, 29.55it/s, loss=1.65]
SASRec epoch 2/8:  50%|█████     | 750/1500 [00:23<00:25, 29.84it/s, loss=1.65]
SASRec epoch 2/8:  50%|█████     | 750/1500 [00:23<00:25, 29.84it/s, loss=1.65]
SASRec epoch 2/8:  50%|█████     | 753/1500 [00:23<00:26, 28.22it/s, loss=1.65]
SASRec epoch 2/8:  50%|█████     | 756/1500 [00:23<00:26, 27.78it/s, loss=1.65]
SASRec epoch 2/8:  51%|█████     | 759/1500 [00:23<00:26, 28.02it/s, loss=1.65]
SASRec epoch 2/8:  51%|█████     | 762/1500 [00:24<00:26, 27.98it/s, loss=1.65]
SASRec epoch 2/8:  51%|█████     | 765/1500 [00:24<00:25, 28.31it/s, loss=1.65]
SASRec epoch 2/8:  51%|█████     | 768/1500 [00:24<00:25, 28.38it/s, loss=1.65]
SASRec epoch 2/8:  51%|█████▏    | 771/1500 [00:24<00:25, 28.50it/s, loss=1.65]
SASRec epoch 2/8:  52%|█████▏    | 774/1500 [00:24<00:25, 28.23it/s, loss=1.65]
SASRec epoch 2/8:  52%|█████▏    | 777/1500 [00:24<00:25, 28.67it/s, loss=1.65]
SASRec epoch 2/8:  52%|█████▏    | 781/1500 [00:24<00:23, 30.19it/s, loss=1.65]
SASRec epoch 2/8:  52%|█████▏    | 785/1500 [00:24<00:22, 31.39it/s, loss=1.65]
SASRec epoch 2/8:  53%|█████▎    | 789/1500 [00:24<00:22, 31.33it/s, loss=1.65]
SASRec epoch 2/8:  53%|█████▎    | 793/1500 [00:25<00:22, 31.83it/s, loss=1.65]
SASRec epoch 2/8:  53%|█████▎    | 797/1500 [00:25<00:21, 32.26it/s, loss=1.65]
SASRec epoch 2/8:  53%|█████▎    | 800/1500 [00:25<00:21, 32.26it/s, loss=1.62]
SASRec epoch 2/8:  53%|█████▎    | 801/1500 [00:25<00:21, 31.80it/s, loss=1.62]
SASRec epoch 2/8:  54%|█████▎    | 805/1500 [00:25<00:21, 32.28it/s, loss=1.62]
SASRec epoch 2/8:  54%|█████▍    | 809/1500 [00:25<00:21, 32.31it/s, loss=1.62]
SASRec epoch 2/8:  54%|█████▍    | 813/1500 [00:25<00:21, 32.65it/s, loss=1.62]
SASRec epoch 2/8:  54%|█████▍    | 817/1500 [00:25<00:20, 32.79it/s, loss=1.62]
SASRec epoch 2/8:  55%|█████▍    | 821/1500 [00:25<00:20, 32.61it/s, loss=1.62]
SASRec epoch 2/8:  55%|█████▌    | 825/1500 [00:26<00:20, 32.77it/s, loss=1.62]
SASRec epoch 2/8:  55%|█████▌    | 829/1500 [00:26<00:20, 33.02it/s, loss=1.62]
SASRec epoch 2/8:  56%|█████▌    | 833/1500 [00:26<00:20, 33.09it/s, loss=1.62]
SASRec epoch 2/8:  56%|█████▌    | 837/1500 [00:26<00:20, 33.04it/s, loss=1.62]
SASRec epoch 2/8:  56%|█████▌    | 841/1500 [00:26<00:20, 32.91it/s, loss=1.62]
SASRec epoch 2/8:  56%|█████▋    | 845/1500 [00:26<00:19, 32.85it/s, loss=1.62]
SASRec epoch 2/8:  57%|█████▋    | 849/1500 [00:26<00:19, 32.87it/s, loss=1.62]
SASRec epoch 2/8:  57%|█████▋    | 850/1500 [00:26<00:19, 32.87it/s, loss=1.62]
SASRec epoch 2/8:  57%|█████▋    | 853/1500 [00:26<00:20, 32.30it/s, loss=1.62]
SASRec epoch 2/8:  57%|█████▋    | 857/1500 [00:27<00:20, 31.71it/s, loss=1.62]
SASRec epoch 2/8:  57%|█████▋    | 861/1500 [00:27<00:19, 32.02it/s, loss=1.62]
SASRec epoch 2/8:  58%|█████▊    | 865/1500 [00:27<00:19, 32.27it/s, loss=1.62]
SASRec epoch 2/8:  58%|█████▊    | 869/1500 [00:27<00:19, 32.60it/s, loss=1.62]
SASRec epoch 2/8:  58%|█████▊    | 873/1500 [00:27<00:19, 32.73it/s, loss=1.62]
SASRec epoch 2/8:  58%|█████▊    | 877/1500 [00:27<00:19, 32.60it/s, loss=1.62]
SASRec epoch 2/8:  59%|█████▊    | 881/1500 [00:27<00:18, 32.71it/s, loss=1.62]
SASRec epoch 2/8:  59%|█████▉    | 885/1500 [00:27<00:18, 32.66it/s, loss=1.62]
SASRec epoch 2/8:  59%|█████▉    | 889/1500 [00:28<00:18, 32.53it/s, loss=1.62]
SASRec epoch 2/8:  60%|█████▉    | 893/1500 [00:28<00:18, 32.70it/s, loss=1.62]
SASRec epoch 2/8:  60%|█████▉    | 897/1500 [00:28<00:18, 32.85it/s, loss=1.62]
SASRec epoch 2/8:  60%|██████    | 900/1500 [00:28<00:18, 32.85it/s, loss=1.6]

[SASRec] epoch 2/8 loss=1.6468

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 3/8:   0%|          | 4/1500 [00:00<00:47, 31.78it/s]
SASRec epoch 3/8:   1%|          | 8/1500 [00:00<00:45, 32.76it/s]
SASRec epoch 3/8:   1%|          | 12/1500 [00:00<00:44, 33.40it/s]
SASRec epoch 3/8:   1%|          | 16/1500 [00:00<00:44, 33.39it/s]
SASRec epoch 3/8:   1%|▏         | 20/1500 [00:00<00:43, 33.70it/s]
SASRec epoch 3/8:   2%|▏         | 24/1500 [00:00<00:43, 33.59it/s]
SASRec epoch 3/8:   2%|▏         | 28/1500 [00:00<00:43, 33.63it/s]
SASRec epoch 3/8:   2%|▏         | 32/1500 [00:00<00:43, 33.46it/s]
SASRec epoch 3/8:   2%|▏         | 36/1500 [00:01<00:44, 33.10it/s]
SASRec epoch 3/8:   3%|▎         | 40/1500 [00:01<00:44, 33.14it/s]
SASRec epoch 3/8:   3%|▎         | 44/1500 [00:01<00:43, 33.50it/s]
SASRec epoch 3/8:   3%|▎         | 48/1500 [00:01<00:43, 33.44it/s]
SASRec epoch 3/8:   3%|▎         | 50/1500 [00:01<00:43, 33.44it/s, loss=1.49]
SASRec epoch 3/8:   3%|▎         | 52/1500 [00:01<00:44, 32.86it/s, loss=1.49]
SASRec epoch 3/8:   4%|▎         | 56/1500 [00:01<00:43, 33.18it/s, loss=1.49]
SASRec epoch 3/8:   4%|▍         | 60/1500 [00:01<00:43, 33.30it/s, loss=1.49]
SASRec epoch 3/8:   4%|▍         | 64/1500 [00:01<00:42, 33.46it/s, loss=1.49]
SASRec epoch 3/8:   5%|▍         | 68/1500 [00:02<00:43, 32.69it/s, loss=1.49]
SASRec epoch 3/8:   5%|▍         | 72/1500 [00:02<00:45, 31.40it/s, loss=1.49]
SASRec epoch 3/8:   5%|▌         | 76/1500 [00:02<00:45, 31.14it/s, loss=1.49]
SASRec epoch 3/8:   5%|▌         | 80/1500 [00:02<00:46, 30.78it/s, loss=1.49]
SASRec epoch 3/8:   6%|▌         | 84/1500 [00:02<00:46, 30.26it/s, loss=1.49]
SASRec epoch 3/8:   6%|▌         | 88/1500 [00:02<00:46, 30.51it/s, loss=1.49]
SASRec epoch 3/8:   6%|▌         | 92/1500 [00:02<00:46, 30.53it/s, loss=1.49]
SASRec epoch 3/8:   6%|▋         | 96/1500 [00:02<00:46, 30.43it/s, loss=1.49]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:03<00:46, 30.35it/s, loss=1.49]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:03<00:46, 30.35it/s, loss=1.48]
SASRec epoch 3/8:   7%|▋         | 104/1500 [00:03<00:47, 29.10it/s, loss=1.48]
SASRec epoch 3/8:   7%|▋         | 107/1500 [00:03<00:48, 28.98it/s, loss=1.48]
SASRec epoch 3/8:   7%|▋         | 110/1500 [00:03<00:47, 29.22it/s, loss=1.48]
SASRec epoch 3/8:   8%|▊         | 114/1500 [00:03<00:46, 29.77it/s, loss=1.48]
SASRec epoch 3/8:   8%|▊         | 118/1500 [00:03<00:45, 30.15it/s, loss=1.48]
SASRec epoch 3/8:   8%|▊         | 122/1500 [00:03<00:45, 30.41it/s, loss=1.48]
SASRec epoch 3/8:   8%|▊         | 126/1500 [00:03<00:45, 30.29it/s, loss=1.48]
SASRec epoch 3/8:   9%|▊         | 130/1500 [00:04<00:45, 30.36it/s, loss=1.48]
SASRec epoch 3/8:   9%|▉         | 134/1500 [00:04<00:44, 30.37it/s, loss=1.48]
SASRec epoch 3/8:   9%|▉         | 138/1500 [00:04<00:45, 30.22it/s, loss=1.48]
SASRec epoch 3/8:   9%|▉         | 142/1500 [00:04<00:44, 30.41it/s, loss=1.48]
SASRec epoch 3/8:  10%|▉         | 146/1500 [00:04<00:44, 30.55it/s, loss=1.48]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:04<00:44, 30.65it/s, loss=1.48]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:04<00:44, 30.65it/s, loss=1.47]
SASRec epoch 3/8:  10%|█         | 154/1500 [00:04<00:44, 30.36it/s, loss=1.47]
SASRec epoch 3/8:  11%|█         | 158/1500 [00:05<00:43, 30.51it/s, loss=1.47]
SASRec epoch 3/8:  11%|█         | 162/1500 [00:05<00:43, 30.57it/s, loss=1.47]
SASRec epoch 3/8:  11%|█         | 166/1500 [00:05<00:45, 29.55it/s, loss=1.47]
SASRec epoch 3/8:  11%|█▏        | 169/1500 [00:05<00:45, 29.19it/s, loss=1.47]
SASRec epoch 3/8:  11%|█▏        | 172/1500 [00:05<00:47, 28.13it/s, loss=1.47]
SASRec epoch 3/8:  12%|█▏        | 175/1500 [00:05<00:47, 27.90it/s, loss=1.47]
SASRec epoch 3/8:  12%|█▏        | 178/1500 [00:05<00:46, 28.33it/s, loss=1.47]
SASRec epoch 3/8:  12%|█▏        | 181/1500 [00:05<00:45, 28.69it/s, loss=1.47]
SASRec epoch 3/8:  12%|█▏        | 184/1500 [00:05<00:46, 28.51it/s, loss=1.47]
SASRec epoch 3/8:  12%|█▏        | 187/1500 [00:06<00:45, 28.83it/s, loss=1.47]
SASRec epoch 3/8:  13%|█▎        | 190/1500 [00:06<00:45, 28.99it/s, loss=1.47]
SASRec epoch 3/8:  13%|█▎        | 193/1500 [00:06<00:45, 28.62it/s, loss=1.47]
SASRec epoch 3/8:  13%|█▎        | 196/1500 [00:06<00:46, 27.93it/s, loss=1.47]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:06<00:44, 29.53it/s, loss=1.47]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:06<00:44, 29.53it/s, loss=1.47]
SASRec epoch 3/8:  14%|█▎        | 204/1500 [00:06<00:42, 30.37it/s, loss=1.47]
SASRec epoch 3/8:  14%|█▍        | 208/1500 [00:06<00:41, 31.19it/s, loss=1.47]
SASRec epoch 3/8:  14%|█▍        | 212/1500 [00:06<00:40, 31.79it/s, loss=1.47]
SASRec epoch 3/8:  14%|█▍        | 216/1500 [00:06<00:39, 32.27it/s, loss=1.47]
SASRec epoch 3/8:  15%|█▍        | 220/1500 [00:07<00:39, 32.71it/s, loss=1.47]
SASRec epoch 3/8:  15%|█▍        | 224/1500 [00:07<00:38, 32.87it/s, loss=1.47]
SASRec epoch 3/8:  15%|█▌        | 228/1500 [00:07<00:38, 33.23it/s, loss=1.47]
SASRec epoch 3/8:  15%|█▌        | 232/1500 [00:07<00:38, 32.77it/s, loss=1.47]
SASRec epoch 3/8:  16%|█▌        | 236/1500 [00:07<00:38, 33.00it/s, loss=1.47]
SASRec epoch 3/8:  16%|█▌        | 240/1500 [00:07<00:37, 33.40it/s, loss=1.47]
SASRec epoch 3/8:  16%|█▋        | 244/1500 [00:07<00:37, 33.27it/s, loss=1.47]
SASRec epoch 3/8:  17%|█▋        | 248/1500 [00:07<00:37, 33.46it/s, loss=1.47]
SASRec epoch 3/8:  17%|█▋        | 250/1500 [00:08<00:37, 33.46it/s, loss=1.46]
SASRec epoch 3/8:  17%|█▋        | 252/1500 [00:08<00:38, 32.68it/s, loss=1.46]
SASRec epoch 3/8:  17%|█▋        | 256/1500 [00:08<00:37, 33.10it/s, loss=1.46]
SASRec epoch 3/8:  17%|█▋        | 260/1500 [00:08<00:37, 33.14it/s, loss=1.46]
SASRec epoch 3/8:  18%|█▊        | 264/1500 [00:08<00:37, 33.03it/s, loss=1.46]
SASRec epoch 3/8:  18%|█▊        | 268/1500 [00:08<00:37, 32.78it/s, loss=1.46]
SASRec epoch 3/8:  18%|█▊        | 272/1500 [00:08<00:37, 32.69it/s, loss=1.46]
SASRec epoch 3/8:  18%|█▊        | 276/1500 [00:08<00:37, 32.84it/s, loss=1.46]
SASRec epoch 3/8:  19%|█▊        | 280/1500 [00:08<00:37, 32.83it/s, loss=1.46]
SASRec epoch 3/8:  19%|█▉        | 284/1500 [00:09<00:36, 33.18it/s, loss=1.46]
SASRec epoch 3/8:  19%|█▉        | 288/1500 [00:09<00:36, 33.33it/s, loss=1.46]
SASRec epoch 3/8:  19%|█▉        | 292/1500 [00:09<00:36, 33.41it/s, loss=1.46]
SASRec epoch 3/8:  20%|█▉        | 296/1500 [00:09<00:35, 33.49it/s, loss=1.46]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:09<00:35, 33.48it/s, loss=1.46]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:09<00:35, 33.48it/s, loss=1.45]
SASRec epoch 3/8:  20%|██        | 304/1500 [00:09<00:37, 32.31it/s, loss=1.45]
SASRec epoch 3/8:  21%|██        | 308/1500 [00:09<00:36, 32.67it/s, loss=1.45]
SASRec epoch 3/8:  21%|██        | 312/1500 [00:09<00:36, 32.78it/s, loss=1.45]
SASRec epoch 3/8:  21%|██        | 316/1500 [00:10<00:35, 32.96it/s, loss=1.45]
SASRec epoch 3/8:  21%|██▏       | 320/1500 [00:10<00:35, 33.04it/s, loss=1.45]
SASRec epoch 3/8:  22%|██▏       | 324/1500 [00:10<00:35, 33.01it/s, loss=1.45]
SASRec epoch 3/8:  22%|██▏       | 328/1500 [00:10<00:35, 33.08it/s, loss=1.45]
SASRec epoch 3/8:  22%|██▏       | 332/1500 [00:10<00:35, 33.03it/s, loss=1.45]
SASRec epoch 3/8:  22%|██▏       | 336/1500 [00:10<00:35, 32.64it/s, loss=1.45]
SASRec epoch 3/8:  23%|██▎       | 340/1500 [00:10<00:35, 32.65it/s, loss=1.45]
SASRec epoch 3/8:  23%|██▎       | 344/1500 [00:10<00:35, 32.60it/s, loss=1.45]
SASRec epoch 3/8:  23%|██▎       | 348/1500 [00:10<00:35, 32.60it/s, loss=1.45]
SASRec epoch 3/8:  23%|██▎       | 350/1500 [00:11<00:35, 32.60it/s, loss=1.46]
SASRec epoch 3/8:  23%|██▎       | 352/1500 [00:11<00:35, 32.10it/s, loss=1.46]
SASRec epoch 3/8:  24%|██▎       | 356/1500 [00:11<00:35, 32.37it/s, loss=1.46]
SASRec epoch 3/8:  24%|██▍       | 360/1500 [00:11<00:34, 32.63it/s, loss=1.46]
SASRec epoch 3/8:  24%|██▍       | 364/1500 [00:11<00:34, 32.49it/s, loss=1.46]
SASRec epoch 3/8:  25%|██▍       | 368/1500 [00:11<00:34, 32.75it/s, loss=1.46]
SASRec epoch 3/8:  25%|██▍       | 372/1500 [00:11<00:35, 31.97it/s, loss=1.46]
SASRec epoch 3/8:  25%|██▌       | 376/1500 [00:11<00:34, 32.58it/s, loss=1.46]
SASRec epoch 3/8:  25%|██▌       | 380/1500 [00:11<00:34, 32.70it/s, loss=1.46]
SASRec epoch 3/8:  26%|██▌       | 384/1500 [00:12<00:33, 33.02it/s, loss=1.46]
SASRec epoch 3/8:  26%|██▌       | 388/1500 [00:12<00:33, 33.25it/s, loss=1.46]
SASRec epoch 3/8:  26%|██▌       | 392/1500 [00:12<00:33, 33.44it/s, loss=1.46]
SASRec epoch 3/8:  26%|██▋       | 396/1500 [00:12<00:32, 33.54it/s, loss=1.46]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:12<00:32, 33.37it/s, loss=1.46]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:12<00:32, 33.37it/s, loss=1.44]
SASRec epoch 3/8:  27%|██▋       | 404/1500 [00:12<00:33, 32.68it/s, loss=1.44]
SASRec epoch 3/8:  27%|██▋       | 408/1500 [00:12<00:32, 33.17it/s, loss=1.44]
SASRec epoch 3/8:  27%|██▋       | 412/1500 [00:12<00:32, 33.06it/s, loss=1.44]
SASRec epoch 3/8:  28%|██▊       | 416/1500 [00:13<00:33, 32.81it/s, loss=1.44]
SASRec epoch 3/8:  28%|██▊       | 420/1500 [00:13<00:32, 32.98it/s, loss=1.44]
SASRec epoch 3/8:  28%|██▊       | 424/1500 [00:13<00:32, 33.04it/s, loss=1.44]
SASRec epoch 3/8:  29%|██▊       | 428/1500 [00:13<00:32, 33.10it/s, loss=1.44]
SASRec epoch 3/8:  29%|██▉       | 432/1500 [00:13<00:32, 33.27it/s, loss=1.44]
SASRec epoch 3/8:  29%|██▉       | 436/1500 [00:13<00:31, 33.48it/s, loss=1.44]
SASRec epoch 3/8:  29%|██▉       | 440/1500 [00:13<00:32, 32.69it/s, loss=1.44]
SASRec epoch 3/8:  30%|██▉       | 444/1500 [00:13<00:32, 32.63it/s, loss=1.44]
SASRec epoch 3/8:  30%|██▉       | 448/1500 [00:14<00:32, 32.73it/s, loss=1.44]
SASRec epoch 3/8:  30%|███       | 450/1500 [00:14<00:32, 32.73it/s, loss=1.43]
SASRec epoch 3/8:  30%|███       | 452/1500 [00:14<00:32, 32.10it/s, loss=1.43]
SASRec epoch 3/8:  30%|███       | 456/1500 [00:14<00:32, 32.43it/s, loss=1.43]
SASRec epoch 3/8:  31%|███       | 460/1500 [00:14<00:31, 32.65it/s, loss=1.43]
SASRec epoch 3/8:  31%|███       | 464/1500 [00:14<00:31, 32.45it/s, loss=1.43]
SASRec epoch 3/8:  31%|███       | 468/1500 [00:14<00:31, 32.56it/s, loss=1.43]
SASRec epoch 3/8:  31%|███▏      | 472/1500 [00:14<00:31, 32.36it/s, loss=1.43]
SASRec epoch 3/8:  32%|███▏      | 476/1500 [00:14<00:31, 32.65it/s, loss=1.43]
SASRec epoch 3/8:  32%|███▏      | 480/1500 [00:15<00:31, 32.77it/s, loss=1.43]
SASRec epoch 3/8:  32%|███▏      | 484/1500 [00:15<00:30, 33.05it/s, loss=1.43]
SASRec epoch 3/8:  33%|███▎      | 488/1500 [00:15<00:30, 32.94it/s, loss=1.43]
SASRec epoch 3/8:  33%|███▎      | 492/1500 [00:15<00:30, 33.14it/s, loss=1.43]
SASRec epoch 3/8:  33%|███▎      | 496/1500 [00:15<00:30, 33.27it/s, loss=1.43]
SASRec epoch 3/8:  33%|███▎      | 500/1500 [00:15<00:30, 32.67it/s, loss=1.43]
SASRec epoch 3/8:  33%|███▎      | 500/1500 [00:15<00:30, 32.67it/s, loss=1.42]
SASRec epoch 3/8:  34%|███▎      | 504/1500 [00:15<00:30, 32.51it/s, loss=1.42]
SASRec epoch 3/8:  34%|███▍      | 508/1500 [00:15<00:31, 31.73it/s, loss=1.42]
SASRec epoch 3/8:  34%|███▍      | 512/1500 [00:16<00:30, 31.94it/s, loss=1.42]
SASRec epoch 3/8:  34%|███▍      | 516/1500 [00:16<00:30, 32.12it/s, loss=1.42]
SASRec epoch 3/8:  35%|███▍      | 520/1500 [00:16<00:30, 32.48it/s, loss=1.42]
SASRec epoch 3/8:  35%|███▍      | 524/1500 [00:16<00:29, 32.76it/s, loss=1.42]
SASRec epoch 3/8:  35%|███▌      | 528/1500 [00:16<00:30, 31.45it/s, loss=1.42]
SASRec epoch 3/8:  35%|███▌      | 532/1500 [00:16<00:31, 30.38it/s, loss=1.42]
SASRec epoch 3/8:  36%|███▌      | 536/1500 [00:16<00:32, 29.51it/s, loss=1.42]
SASRec epoch 3/8:  36%|███▌      | 539/1500 [00:16<00:33, 28.76it/s, loss=1.42]
SASRec epoch 3/8:  36%|███▌      | 542/1500 [00:17<00:33, 28.45it/s, loss=1.42]
SASRec epoch 3/8:  36%|███▋      | 545/1500 [00:17<00:33, 28.59it/s, loss=1.42]
SASRec epoch 3/8:  37%|███▋      | 549/1500 [00:17<00:32, 29.25it/s, loss=1.42]
SASRec epoch 3/8:  37%|███▋      | 550/1500 [00:17<00:32, 29.25it/s, loss=1.42]
SASRec epoch 3/8:  37%|███▋      | 552/1500 [00:17<00:32, 29.24it/s, loss=1.42]
SASRec epoch 3/8:  37%|███▋      | 556/1500 [00:17<00:31, 29.61it/s, loss=1.42]
SASRec epoch 3/8:  37%|███▋      | 559/1500 [00:17<00:31, 29.60it/s, loss=1.42]
SASRec epoch 3/8:  38%|███▊      | 563/1500 [00:17<00:31, 29.99it/s, loss=1.42]
SASRec epoch 3/8:  38%|███▊      | 566/1500 [00:17<00:31, 29.60it/s, loss=1.42]
SASRec epoch 3/8:  38%|███▊      | 570/1500 [00:17<00:31, 29.53it/s, loss=1.42]
SASRec epoch 3/8:  38%|███▊      | 573/1500 [00:18<00:31, 29.22it/s, loss=1.42]
SASRec epoch 3/8:  38%|███▊      | 577/1500 [00:18<00:30, 29.95it/s, loss=1.42]
SASRec epoch 3/8:  39%|███▊      | 581/1500 [00:18<00:30, 30.44it/s, loss=1.42]
SASRec epoch 3/8:  39%|███▉      | 585/1500 [00:18<00:30, 29.63it/s, loss=1.42]
SASRec epoch 3/8:  39%|███▉      | 588/1500 [00:18<00:30, 29.49it/s, loss=1.42]
SASRec epoch 3/8:  39%|███▉      | 592/1500 [00:18<00:30, 29.91it/s, loss=1.42]
SASRec epoch 3/8:  40%|███▉      | 595/1500 [00:18<00:30, 29.87it/s, loss=1.42]
SASRec epoch 3/8:  40%|███▉      | 599/1500 [00:18<00:29, 30.18it/s, loss=1.42]
SASRec epoch 3/8:  40%|████      | 600/1500 [00:18<00:29, 30.18it/s, loss=1.42]
SASRec epoch 3/8:  40%|████      | 603/1500 [00:19<00:30, 29.45it/s, loss=1.42]
SASRec epoch 3/8:  40%|████      | 606/1500 [00:19<00:30, 29.51it/s, loss=1.42]
SASRec epoch 3/8:  41%|████      | 610/1500 [00:19<00:29, 29.96it/s, loss=1.42]
SASRec epoch 3/8:  41%|████      | 614/1500 [00:19<00:29, 30.22it/s, loss=1.42]
SASRec epoch 3/8:  41%|████      | 618/1500 [00:19<00:28, 30.56it/s, loss=1.42]
SASRec epoch 3/8:  41%|████▏     | 622/1500 [00:19<00:29, 29.91it/s, loss=1.42]
SASRec epoch 3/8:  42%|████▏     | 626/1500 [00:19<00:29, 29.96it/s, loss=1.42]
SASRec epoch 3/8:  42%|████▏     | 629/1500 [00:19<00:30, 28.83it/s, loss=1.42]
SASRec epoch 3/8:  42%|████▏     | 632/1500 [00:20<00:30, 28.04it/s, loss=1.42]
SASRec epoch 3/8:  42%|████▏     | 636/1500 [00:20<00:29, 28.85it/s, loss=1.42]
SASRec epoch 3/8:  43%|████▎     | 639/1500 [00:20<00:29, 28.88it/s, loss=1.42]
SASRec epoch 3/8:  43%|████▎     | 642/1500 [00:20<00:29, 28.65it/s, loss=1.42]
SASRec epoch 3/8:  43%|████▎     | 645/1500 [00:20<00:29, 28.63it/s, loss=1.42]
SASRec epoch 3/8:  43%|████▎     | 648/1500 [00:20<00:29, 28.59it/s, loss=1.42]
SASRec epoch 3/8:  43%|████▎     | 650/1500 [00:20<00:29, 28.59it/s, loss=1.41]
SASRec epoch 3/8:  43%|████▎     | 651/1500 [00:20<00:29, 28.36it/s, loss=1.41]
SASRec epoch 3/8:  44%|████▎     | 654/1500 [00:20<00:29, 28.50it/s, loss=1.41]
SASRec epoch 3/8:  44%|████▍     | 657/1500 [00:20<00:29, 28.70it/s, loss=1.41]
SASRec epoch 3/8:  44%|████▍     | 661/1500 [00:21<00:27, 30.36it/s, loss=1.41]
SASRec epoch 3/8:  44%|████▍     | 665/1500 [00:21<00:26, 31.38it/s, loss=1.41]
SASRec epoch 3/8:  45%|████▍     | 669/1500 [00:21<00:26, 31.54it/s, loss=1.41]
SASRec epoch 3/8:  45%|████▍     | 673/1500 [00:21<00:25, 31.98it/s, loss=1.41]
SASRec epoch 3/8:  45%|████▌     | 677/1500 [00:21<00:25, 32.37it/s, loss=1.41]
SASRec epoch 3/8:  45%|████▌     | 681/1500 [00:21<00:25, 32.59it/s, loss=1.41]
SASRec epoch 3/8:  46%|████▌     | 685/1500 [00:21<00:24, 32.83it/s, loss=1.41]
SASRec epoch 3/8:  46%|████▌     | 689/1500 [00:21<00:24, 32.88it/s, loss=1.41]
SASRec epoch 3/8:  46%|████▌     | 693/1500 [00:22<00:24, 32.87it/s, loss=1.41]
SASRec epoch 3/8:  46%|████▋     | 697/1500 [00:22<00:24, 32.98it/s, loss=1.41]
SASRec epoch 3/8:  47%|████▋     | 700/1500 [00:22<00:24, 32.98it/s, loss=1.38]
SASRec epoch 3/8:  47%|████▋     | 701/1500 [00:22<00:24, 32.32it/s, loss=1.38]
SASRec epoch 3/8:  47%|████▋     | 705/1500 [00:22<00:24, 32.34it/s, loss=1.38]
SASRec epoch 3/8:  47%|████▋     | 709/1500 [00:22<00:24, 32.38it/s, loss=1.38]
SASRec epoch 3/8:  48%|████▊     | 713/1500 [00:22<00:24, 32.60it/s, loss=1.38]
SASRec epoch 3/8:  48%|████▊     | 717/1500 [00:22<00:23, 32.77it/s, loss=1.38]
SASRec epoch 3/8:  48%|████▊     | 721/1500 [00:22<00:23, 33.02it/s, loss=1.38]
SASRec epoch 3/8:  48%|████▊     | 725/1500 [00:22<00:23, 33.38it/s, loss=1.38]
SASRec epoch 3/8:  49%|████▊     | 729/1500 [00:23<00:23, 33.35it/s, loss=1.38]
SASRec epoch 3/8:  49%|████▉     | 733/1500 [00:23<00:23, 33.21it/s, loss=1.38]
SASRec epoch 3/8:  49%|████▉     | 737/1500 [00:23<00:22, 33.39it/s, loss=1.38]
SASRec epoch 3/8:  49%|████▉     | 741/1500 [00:23<00:23, 32.88it/s, loss=1.38]
SASRec epoch 3/8:  50%|████▉     | 745/1500 [00:23<00:22, 33.10it/s, loss=1.38]
SASRec epoch 3/8:  50%|████▉     | 749/1500 [00:23<00:22, 33.16it/s, loss=1.38]
SASRec epoch 3/8:  50%|█████     | 750/1500 [00:23<00:22, 33.16it/s, loss=1.4]
SASRec epoch 3/8:  50%|█████     | 753/1500 [00:23<00:23, 32.41it/s, loss=1.4]
SASRec epoch 3/8:  50%|█████     | 757/1500 [00:23<00:22, 32.66it/s, loss=1.4]
SASRec epoch 3/8:  51%|█████     | 761/1500 [00:24<00:22, 32.78it/s, loss=1.4]
SASRec epoch 3/8:  51%|█████     | 765/1500 [00:24<00:22, 32.97it/s, loss=1.4]
SASRec epoch 3/8:  51%|█████▏    | 769/1500 [00:24<00:22, 32.96it/s, loss=1.4]
SASRec epoch 3/8:  52%|█████▏    | 773/1500 [00:24<00:22, 32.55it/s, loss=1.4]
SASRec epoch 3/8:  52%|█████▏    | 777/1500 [00:24<00:22, 32.76it/s, loss=1.4]
SASRec epoch 3/8:  52%|█████▏    | 781/1500 [00:24<00:21, 32.91it/s, loss=1.4]
SASRec epoch 3/8:  52%|█████▏    | 785/1500 [00:24<00:21, 33.10it/s, loss=1.4]
SASRec epoch 3/8:  53%|█████▎    | 789/1500 [00:24<00:21, 32.80it/s, loss=1.4]
SASRec epoch 3/8:  53%|█████▎    | 793/1500 [00:25<00:21, 33.15it/s, loss=1.4]
SASRec epoch 3/8:  53%|█████▎    | 797/1500 [00:25<00:21, 33.24it/s, loss=1.4]
SASRec epoch 3/8:  53%|█████▎    | 800/1500 [00:25<00:21, 33.24it/s, loss=1.38]
SASRec epoch 3/8:  53%|█████▎    | 801/1500 [00:25<00:21, 32.56it/s, loss=1.38]
SASRec epoch 3/8:  54%|█████▎    | 805/1500 [00:25<00:21, 32.98it/s, loss=1.38]
SASRec epoch 3/8:  54%|█████▍    | 809/1500 [00:25<00:21, 32.34it/s, loss=1.38]
SASRec epoch 3/8:  54%|█████▍    | 813/1500 [00:25<00:21, 32.50it/s, loss=1.38]
SASRec epoch 3/8:  54%|█████▍    | 817/1500 [00:25<00:20, 32.71it/s, loss=1.38]
SASRec epoch 3/8:  55%|█████▍    | 821/1500 [00:25<00:20, 32.56it/s, loss=1.38]
SASRec epoch 3/8:  55%|█████▌    | 825/1500 [00:26<00:20, 32.71it/s, loss=1.38]
SASRec epoch 3/8:  55%|█████▌    | 829/1500 [00:26<00:20, 32.81it/s, loss=1.38]
SASRec epoch 3/8:  56%|█████▌    | 833/1500 [00:26<00:20, 32.97it/s, loss=1.38]
SASRec epoch 3/8:  56%|█████▌    | 837/1500 [00:26<00:20, 32.94it/s, loss=1.38]
SASRec epoch 3/8:  56%|█████▌    | 841/1500 [00:26<00:20, 32.51it/s, loss=1.38]
SASRec epoch 3/8:  56%|█████▋    | 845/1500 [00:26<00:20, 32.55it/s, loss=1.38]
SASRec epoch 3/8:  57%|█████▋    | 849/1500 [00:26<00:19, 32.62it/s, loss=1.38]
SASRec epoch 3/8:  57%|█████▋    | 850/1500 [00:26<00:19, 32.62it/s, loss=1.39]
SASRec epoch 3/8:  57%|█████▋    | 853/1500 [00:26<00:20, 31.86it/s, loss=1.39]
SASRec epoch 3/8:  57%|█████▋    | 857/1500 [00:27<00:20, 32.07it/s, loss=1.39]
SASRec epoch 3/8:  57%|█████▋    | 861/1500 [00:27<00:19, 32.11it/s, loss=1.39]
SASRec epoch 3/8:  58%|█████▊    | 865/1500 [00:27<00:19, 32.32it/s, loss=1.39]
SASRec epoch 3/8:  58%|█████▊    | 869/1500 [00:27<00:19, 32.05it/s, loss=1.39]
SASRec epoch 3/8:  58%|█████▊    | 873/1500 [00:27<00:19, 31.80it/s, loss=1.39]
SASRec epoch 3/8:  58%|█████▊    | 877/1500 [00:27<00:19, 31.94it/s, loss=1.39]
SASRec epoch 3/8:  59%|█████▊    | 881/1500 [00:27<00:19, 32.29it/s, loss=1.39]
SASRec epoch 3/8:  59%|█████▉    | 885/1500 [00:27<00:18, 32.60it/s, loss=1.39]
SASRec epoch 3/8:  59%|█████▉    | 889/1500 [00:28<00:18, 32.55it/s, loss=1.39]
SASRec epoch 3/8:  60%|█████▉    | 893/1500 [00:28<00:18, 32.84it/s, loss=1.39]
SASRec epoch 3/8:  60%|█████▉    | 897/1500 [00:28<00:18, 32.89it/s, loss=1.39]
SASRec epoch 3/8:  60%|██████    | 900/1500 [00:28<00:18, 32.89it/s, loss=1.39]
SASRec epoch 3/8:  60%|██████    | 901/1500 [00:28<00:18, 32.28it/s, loss=1.39]

[SASRec] epoch 3/8 loss=1.3951

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 4/8:   0%|          | 3/1500 [00:00<00:51, 29.01it/s]
SASRec epoch 4/8:   0%|          | 6/1500 [00:00<00:50, 29.38it/s]
SASRec epoch 4/8:   1%|          | 10/1500 [00:00<00:49, 30.37it/s]
SASRec epoch 4/8:   1%|          | 14/1500 [00:00<00:49, 30.14it/s]
SASRec epoch 4/8:   1%|          | 18/1500 [00:00<00:48, 30.66it/s]
SASRec epoch 4/8:   1%|▏         | 22/1500 [00:00<00:47, 31.06it/s]
SASRec epoch 4/8:   2%|▏         | 26/1500 [00:00<00:47, 30.99it/s]
SASRec epoch 4/8:   2%|▏         | 30/1500 [00:00<00:46, 31.38it/s]
SASRec epoch 4/8:   2%|▏         | 34/1500 [00:01<00:46, 31.42it/s]
SASRec epoch 4/8:   3%|▎         | 38/1500 [00:01<00:47, 30.85it/s]
SASRec epoch 4/8:   3%|▎         | 42/1500 [00:01<00:46, 31.15it/s]
SASRec epoch 4/8:   3%|▎         | 46/1500 [00:01<00:47, 30.52it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:01<00:47, 30.60it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:01<00:47, 30.60it/s, loss=1.31]
SASRec epoch 4/8:   4%|▎         | 54/1500 [00:01<00:48, 29.86it/s, loss=1.31]
SASRec epoch 4/8:   4%|▍         | 57/1500 [00:01<00:50, 28.66it/s, loss=1.31]
SASRec epoch 4/8:   4%|▍         | 60/1500 [00:01<00:50, 28.55it/s, loss=1.31]
SASRec epoch 4/8:   4%|▍         | 64/1500 [00:02<00:49, 29.18it/s, loss=1.31]
SASRec epoch 4/8:   4%|▍         | 67/1500 [00:02<00:50, 28.27it/s, loss=1.31]
SASRec epoch 4/8:   5%|▍         | 70/1500 [00:02<00:51, 27.91it/s, loss=1.31]
SASRec epoch 4/8:   5%|▍         | 73/1500 [00:02<00:50, 28.23it/s, loss=1.31]
SASRec epoch 4/8:   5%|▌         | 76/1500 [00:02<00:51, 27.75it/s, loss=1.31]
SASRec epoch 4/8:   5%|▌         | 79/1500 [00:02<00:51, 27.45it/s, loss=1.31]
SASRec epoch 4/8:   5%|▌         | 82/1500 [00:02<00:50, 27.92it/s, loss=1.31]
SASRec epoch 4/8:   6%|▌         | 86/1500 [00:02<00:47, 29.48it/s, loss=1.31]
SASRec epoch 4/8:   6%|▌         | 90/1500 [00:03<00:45, 30.67it/s, loss=1.31]
SASRec epoch 4/8:   6%|▋         | 94/1500 [00:03<00:44, 31.53it/s, loss=1.31]
SASRec epoch 4/8:   7%|▋         | 98/1500 [00:03<00:43, 31.97it/s, loss=1.31]
SASRec epoch 4/8:   7%|▋         | 100/1500 [00:03<00:43, 31.97it/s, loss=1.28]
SASRec epoch 4/8:   7%|▋         | 102/1500 [00:03<00:44, 31.51it/s, loss=1.28]
SASRec epoch 4/8:   7%|▋         | 106/1500 [00:03<00:43, 31.79it/s, loss=1.28]
SASRec epoch 4/8:   7%|▋         | 110/1500 [00:03<00:43, 31.80it/s, loss=1.28]
SASRec epoch 4/8:   8%|▊         | 114/1500 [00:03<00:43, 32.13it/s, loss=1.28]
SASRec epoch 4/8:   8%|▊         | 118/1500 [00:03<00:42, 32.31it/s, loss=1.28]
SASRec epoch 4/8:   8%|▊         | 122/1500 [00:04<00:42, 32.38it/s, loss=1.28]
SASRec epoch 4/8:   8%|▊         | 126/1500 [00:04<00:42, 32.52it/s, loss=1.28]
SASRec epoch 4/8:   9%|▊         | 130/1500 [00:04<00:42, 32.61it/s, loss=1.28]
SASRec epoch 4/8:   9%|▉         | 134/1500 [00:04<00:41, 32.83it/s, loss=1.28]
SASRec epoch 4/8:   9%|▉         | 138/1500 [00:04<00:41, 32.88it/s, loss=1.28]
SASRec epoch 4/8:   9%|▉         | 142/1500 [00:04<00:41, 32.55it/s, loss=1.28]
SASRec epoch 4/8:  10%|▉         | 146/1500 [00:04<00:41, 32.82it/s, loss=1.28]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:04<00:41, 32.90it/s, loss=1.28]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:04<00:41, 32.90it/s, loss=1.3]
SASRec epoch 4/8:  10%|█         | 154/1500 [00:04<00:41, 32.13it/s, loss=1.3]
SASRec epoch 4/8:  11%|█         | 158/1500 [00:05<00:41, 32.29it/s, loss=1.3]
SASRec epoch 4/8:  11%|█         | 162/1500 [00:05<00:41, 32.57it/s, loss=1.3]
SASRec epoch 4/8:  11%|█         | 166/1500 [00:05<00:40, 32.71it/s, loss=1.3]
SASRec epoch 4/8:  11%|█▏        | 170/1500 [00:05<00:40, 32.81it/s, loss=1.3]
SASRec epoch 4/8:  12%|█▏        | 174/1500 [00:05<00:40, 32.59it/s, loss=1.3]
SASRec epoch 4/8:  12%|█▏        | 178/1500 [00:05<00:41, 31.82it/s, loss=1.3]
SASRec epoch 4/8:  12%|█▏        | 182/1500 [00:05<00:40, 32.18it/s, loss=1.3]
SASRec epoch 4/8:  12%|█▏        | 186/1500 [00:05<00:40, 32.52it/s, loss=1.3]
SASRec epoch 4/8:  13%|█▎        | 190/1500 [00:06<00:39, 32.93it/s, loss=1.3]
SASRec epoch 4/8:  13%|█▎        | 194/1500 [00:06<00:39, 33.20it/s, loss=1.3]
SASRec epoch 4/8:  13%|█▎        | 198/1500 [00:06<00:38, 33.44it/s, loss=1.3]
SASRec epoch 4/8:  13%|█▎        | 200/1500 [00:06<00:38, 33.44it/s, loss=1.28]
SASRec epoch 4/8:  13%|█▎        | 202/1500 [00:06<00:39, 32.91it/s, loss=1.28]
SASRec epoch 4/8:  14%|█▎        | 206/1500 [00:06<00:39, 32.79it/s, loss=1.28]
SASRec epoch 4/8:  14%|█▍        | 210/1500 [00:06<00:39, 32.88it/s, loss=1.28]
SASRec epoch 4/8:  14%|█▍        | 214/1500 [00:06<00:39, 32.55it/s, loss=1.28]
SASRec epoch 4/8:  15%|█▍        | 218/1500 [00:06<00:39, 32.63it/s, loss=1.28]
SASRec epoch 4/8:  15%|█▍        | 222/1500 [00:07<00:38, 32.79it/s, loss=1.28]
SASRec epoch 4/8:  15%|█▌        | 226/1500 [00:07<00:38, 32.76it/s, loss=1.28]
SASRec epoch 4/8:  15%|█▌        | 230/1500 [00:07<00:38, 32.91it/s, loss=1.28]
SASRec epoch 4/8:  16%|█▌        | 234/1500 [00:07<00:38, 33.03it/s, loss=1.28]
SASRec epoch 4/8:  16%|█▌        | 238/1500 [00:07<00:38, 33.08it/s, loss=1.28]
SASRec epoch 4/8:  16%|█▌        | 242/1500 [00:07<00:37, 33.21it/s, loss=1.28]
SASRec epoch 4/8:  16%|█▋        | 246/1500 [00:07<00:38, 32.68it/s, loss=1.28]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:07<00:38, 32.75it/s, loss=1.28]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:07<00:38, 32.75it/s, loss=1.28]
SASRec epoch 4/8:  17%|█▋        | 254/1500 [00:08<00:38, 32.36it/s, loss=1.28]
SASRec epoch 4/8:  17%|█▋        | 258/1500 [00:08<00:38, 32.58it/s, loss=1.28]
SASRec epoch 4/8:  17%|█▋        | 262/1500 [00:08<00:37, 33.00it/s, loss=1.28]
SASRec epoch 4/8:  18%|█▊        | 266/1500 [00:08<00:37, 33.28it/s, loss=1.28]
SASRec epoch 4/8:  18%|█▊        | 270/1500 [00:08<00:36, 33.38it/s, loss=1.28]
SASRec epoch 4/8:  18%|█▊        | 274/1500 [00:08<00:36, 33.47it/s, loss=1.28]
SASRec epoch 4/8:  19%|█▊        | 278/1500 [00:08<00:36, 33.64it/s, loss=1.28]
SASRec epoch 4/8:  19%|█▉        | 282/1500 [00:08<00:36, 33.06it/s, loss=1.28]
SASRec epoch 4/8:  19%|█▉        | 286/1500 [00:09<00:36, 33.25it/s, loss=1.28]
SASRec epoch 4/8:  19%|█▉        | 290/1500 [00:09<00:36, 33.35it/s, loss=1.28]
SASRec epoch 4/8:  20%|█▉        | 294/1500 [00:09<00:36, 33.38it/s, loss=1.28]
SASRec epoch 4/8:  20%|█▉        | 298/1500 [00:09<00:36, 33.34it/s, loss=1.28]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:09<00:35, 33.34it/s, loss=1.27]
SASRec epoch 4/8:  20%|██        | 302/1500 [00:09<00:36, 32.75it/s, loss=1.27]
SASRec epoch 4/8:  20%|██        | 306/1500 [00:09<00:36, 32.95it/s, loss=1.27]
SASRec epoch 4/8:  21%|██        | 310/1500 [00:09<00:35, 33.21it/s, loss=1.27]
SASRec epoch 4/8:  21%|██        | 314/1500 [00:09<00:36, 32.92it/s, loss=1.27]
SASRec epoch 4/8:  21%|██        | 318/1500 [00:09<00:35, 32.98it/s, loss=1.27]
SASRec epoch 4/8:  21%|██▏       | 322/1500 [00:10<00:35, 32.98it/s, loss=1.27]
SASRec epoch 4/8:  22%|██▏       | 326/1500 [00:10<00:35, 33.19it/s, loss=1.27]
SASRec epoch 4/8:  22%|██▏       | 330/1500 [00:10<00:35, 33.38it/s, loss=1.27]
SASRec epoch 4/8:  22%|██▏       | 334/1500 [00:10<00:34, 33.38it/s, loss=1.27]
SASRec epoch 4/8:  23%|██▎       | 338/1500 [00:10<00:34, 33.26it/s, loss=1.27]
SASRec epoch 4/8:  23%|██▎       | 342/1500 [00:10<00:34, 33.26it/s, loss=1.27]
SASRec epoch 4/8:  23%|██▎       | 346/1500 [00:10<00:34, 33.18it/s, loss=1.27]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:10<00:35, 32.64it/s, loss=1.27]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:10<00:35, 32.64it/s, loss=1.28]
SASRec epoch 4/8:  24%|██▎       | 354/1500 [00:11<00:35, 32.32it/s, loss=1.28]
SASRec epoch 4/8:  24%|██▍       | 358/1500 [00:11<00:35, 32.52it/s, loss=1.28]
SASRec epoch 4/8:  24%|██▍       | 362/1500 [00:11<00:34, 32.63it/s, loss=1.28]
SASRec epoch 4/8:  24%|██▍       | 366/1500 [00:11<00:34, 32.84it/s, loss=1.28]
SASRec epoch 4/8:  25%|██▍       | 370/1500 [00:11<00:34, 33.06it/s, loss=1.28]
SASRec epoch 4/8:  25%|██▍       | 374/1500 [00:11<00:33, 33.36it/s, loss=1.28]
SASRec epoch 4/8:  25%|██▌       | 378/1500 [00:11<00:33, 33.54it/s, loss=1.28]
SASRec epoch 4/8:  25%|██▌       | 382/1500 [00:11<00:33, 33.33it/s, loss=1.28]
SASRec epoch 4/8:  26%|██▌       | 386/1500 [00:12<00:33, 32.89it/s, loss=1.28]
SASRec epoch 4/8:  26%|██▌       | 390/1500 [00:12<00:33, 32.75it/s, loss=1.28]
SASRec epoch 4/8:  26%|██▋       | 394/1500 [00:12<00:33, 33.11it/s, loss=1.28]
SASRec epoch 4/8:  27%|██▋       | 398/1500 [00:12<00:33, 33.35it/s, loss=1.28]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:12<00:32, 33.35it/s, loss=1.28]
SASRec epoch 4/8:  27%|██▋       | 402/1500 [00:12<00:33, 32.76it/s, loss=1.28]
SASRec epoch 4/8:  27%|██▋       | 406/1500 [00:12<00:32, 33.15it/s, loss=1.28]
SASRec epoch 4/8:  27%|██▋       | 410/1500 [00:12<00:32, 33.52it/s, loss=1.28]
SASRec epoch 4/8:  28%|██▊       | 414/1500 [00:12<00:34, 31.93it/s, loss=1.28]
SASRec epoch 4/8:  28%|██▊       | 418/1500 [00:13<00:35, 30.81it/s, loss=1.28]
SASRec epoch 4/8:  28%|██▊       | 422/1500 [00:13<00:35, 30.23it/s, loss=1.28]
SASRec epoch 4/8:  28%|██▊       | 426/1500 [00:13<00:35, 30.28it/s, loss=1.28]
SASRec epoch 4/8:  29%|██▊       | 430/1500 [00:13<00:35, 30.33it/s, loss=1.28]
SASRec epoch 4/8:  29%|██▉       | 434/1500 [00:13<00:34, 30.51it/s, loss=1.28]
SASRec epoch 4/8:  29%|██▉       | 438/1500 [00:13<00:34, 30.66it/s, loss=1.28]
SASRec epoch 4/8:  29%|██▉       | 442/1500 [00:13<00:34, 30.77it/s, loss=1.28]
SASRec epoch 4/8:  30%|██▉       | 446/1500 [00:13<00:34, 30.90it/s, loss=1.28]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:14<00:34, 30.36it/s, loss=1.28]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:14<00:34, 30.36it/s, loss=1.26]
SASRec epoch 4/8:  30%|███       | 454/1500 [00:14<00:36, 28.94it/s, loss=1.26]
SASRec epoch 4/8:  30%|███       | 457/1500 [00:14<00:36, 28.66it/s, loss=1.26]
SASRec epoch 4/8:  31%|███       | 461/1500 [00:14<00:35, 29.30it/s, loss=1.26]
SASRec epoch 4/8:  31%|███       | 465/1500 [00:14<00:34, 30.00it/s, loss=1.26]
SASRec epoch 4/8:  31%|███▏      | 469/1500 [00:14<00:33, 30.54it/s, loss=1.26]
SASRec epoch 4/8:  32%|███▏      | 473/1500 [00:14<00:34, 30.20it/s, loss=1.26]
SASRec epoch 4/8:  32%|███▏      | 477/1500 [00:14<00:34, 29.97it/s, loss=1.26]
SASRec epoch 4/8:  32%|███▏      | 481/1500 [00:15<00:34, 29.53it/s, loss=1.26]
SASRec epoch 4/8:  32%|███▏      | 484/1500 [00:15<00:35, 28.44it/s, loss=1.26]
SASRec epoch 4/8:  32%|███▏      | 487/1500 [00:15<00:35, 28.81it/s, loss=1.26]
SASRec epoch 4/8:  33%|███▎      | 491/1500 [00:15<00:34, 29.55it/s, loss=1.26]
SASRec epoch 4/8:  33%|███▎      | 495/1500 [00:15<00:33, 29.93it/s, loss=1.26]
SASRec epoch 4/8:  33%|███▎      | 499/1500 [00:15<00:32, 30.34it/s, loss=1.26]
SASRec epoch 4/8:  33%|███▎      | 500/1500 [00:15<00:32, 30.34it/s, loss=1.26]
SASRec epoch 4/8:  34%|███▎      | 503/1500 [00:15<00:32, 30.32it/s, loss=1.26]
SASRec epoch 4/8:  34%|███▍      | 507/1500 [00:16<00:32, 30.18it/s, loss=1.26]
SASRec epoch 4/8:  34%|███▍      | 511/1500 [00:16<00:33, 29.49it/s, loss=1.26]
SASRec epoch 4/8:  34%|███▍      | 514/1500 [00:16<00:33, 29.24it/s, loss=1.26]
SASRec epoch 4/8:  34%|███▍      | 517/1500 [00:16<00:34, 28.41it/s, loss=1.26]
SASRec epoch 4/8:  35%|███▍      | 521/1500 [00:16<00:33, 29.08it/s, loss=1.26]
SASRec epoch 4/8:  35%|███▍      | 524/1500 [00:16<00:34, 28.69it/s, loss=1.26]
SASRec epoch 4/8:  35%|███▌      | 528/1500 [00:16<00:33, 29.39it/s, loss=1.26]
SASRec epoch 4/8:  35%|███▌      | 531/1500 [00:16<00:33, 29.26it/s, loss=1.26]
SASRec epoch 4/8:  36%|███▌      | 534/1500 [00:16<00:33, 29.23it/s, loss=1.26]
SASRec epoch 4/8:  36%|███▌      | 537/1500 [00:17<00:33, 28.89it/s, loss=1.26]
SASRec epoch 4/8:  36%|███▌      | 540/1500 [00:17<00:34, 28.12it/s, loss=1.26]
SASRec epoch 4/8:  36%|███▋      | 544/1500 [00:17<00:32, 29.27it/s, loss=1.26]
SASRec epoch 4/8:  37%|███▋      | 548/1500 [00:17<00:31, 30.16it/s, loss=1.26]
SASRec epoch 4/8:  37%|███▋      | 550/1500 [00:17<00:31, 30.16it/s, loss=1.25]
SASRec epoch 4/8:  37%|███▋      | 552/1500 [00:17<00:30, 30.71it/s, loss=1.25]
SASRec epoch 4/8:  37%|███▋      | 556/1500 [00:17<00:29, 31.71it/s, loss=1.25]
SASRec epoch 4/8:  37%|███▋      | 560/1500 [00:17<00:29, 32.36it/s, loss=1.25]
SASRec epoch 4/8:  38%|███▊      | 564/1500 [00:17<00:28, 32.58it/s, loss=1.25]
SASRec epoch 4/8:  38%|███▊      | 568/1500 [00:18<00:28, 32.70it/s, loss=1.25]
SASRec epoch 4/8:  38%|███▊      | 572/1500 [00:18<00:28, 32.65it/s, loss=1.25]
SASRec epoch 4/8:  38%|███▊      | 576/1500 [00:18<00:28, 32.54it/s, loss=1.25]
SASRec epoch 4/8:  39%|███▊      | 580/1500 [00:18<00:28, 32.49it/s, loss=1.25]
SASRec epoch 4/8:  39%|███▉      | 584/1500 [00:18<00:27, 33.02it/s, loss=1.25]
SASRec epoch 4/8:  39%|███▉      | 588/1500 [00:18<00:27, 32.99it/s, loss=1.25]
SASRec epoch 4/8:  39%|███▉      | 592/1500 [00:18<00:27, 33.05it/s, loss=1.25]
SASRec epoch 4/8:  40%|███▉      | 596/1500 [00:18<00:27, 33.19it/s, loss=1.25]
SASRec epoch 4/8:  40%|████      | 600/1500 [00:18<00:27, 33.26it/s, loss=1.25]
SASRec epoch 4/8:  40%|████      | 600/1500 [00:18<00:27, 33.26it/s, loss=1.25]
SASRec epoch 4/8:  40%|████      | 604/1500 [00:19<00:27, 32.58it/s, loss=1.25]
SASRec epoch 4/8:  41%|████      | 608/1500 [00:19<00:27, 32.78it/s, loss=1.25]
SASRec epoch 4/8:  41%|████      | 612/1500 [00:19<00:26, 33.03it/s, loss=1.25]
SASRec epoch 4/8:  41%|████      | 616/1500 [00:19<00:26, 33.03it/s, loss=1.25]
SASRec epoch 4/8:  41%|████▏     | 620/1500 [00:19<00:26, 33.35it/s, loss=1.25]
SASRec epoch 4/8:  42%|████▏     | 624/1500 [00:19<00:26, 33.48it/s, loss=1.25]
SASRec epoch 4/8:  42%|████▏     | 628/1500 [00:19<00:26, 33.38it/s, loss=1.25]
SASRec epoch 4/8:  42%|████▏     | 632/1500 [00:19<00:25, 33.42it/s, loss=1.25]
SASRec epoch 4/8:  42%|████▏     | 636/1500 [00:20<00:26, 33.09it/s, loss=1.25]
SASRec epoch 4/8:  43%|████▎     | 640/1500 [00:20<00:26, 32.98it/s, loss=1.25]
SASRec epoch 4/8:  43%|████▎     | 644/1500 [00:20<00:25, 33.12it/s, loss=1.25]
SASRec epoch 4/8:  43%|████▎     | 648/1500 [00:20<00:25, 33.20it/s, loss=1.25]
SASRec epoch 4/8:  43%|████▎     | 650/1500 [00:20<00:25, 33.20it/s, loss=1.26]
SASRec epoch 4/8:  43%|████▎     | 652/1500 [00:20<00:26, 31.82it/s, loss=1.26]
SASRec epoch 4/8:  44%|████▎     | 656/1500 [00:20<00:26, 32.21it/s, loss=1.26]
SASRec epoch 4/8:  44%|████▍     | 660/1500 [00:20<00:25, 32.51it/s, loss=1.26]
SASRec epoch 4/8:  44%|████▍     | 664/1500 [00:20<00:25, 32.81it/s, loss=1.26]
SASRec epoch 4/8:  45%|████▍     | 668/1500 [00:21<00:25, 32.97it/s, loss=1.26]
SASRec epoch 4/8:  45%|████▍     | 672/1500 [00:21<00:25, 32.92it/s, loss=1.26]
SASRec epoch 4/8:  45%|████▌     | 676/1500 [00:21<00:24, 33.14it/s, loss=1.26]
SASRec epoch 4/8:  45%|████▌     | 680/1500 [00:21<00:24, 33.21it/s, loss=1.26]
SASRec epoch 4/8:  46%|████▌     | 684/1500 [00:21<00:24, 32.90it/s, loss=1.26]
SASRec epoch 4/8:  46%|████▌     | 688/1500 [00:21<00:24, 33.06it/s, loss=1.26]
SASRec epoch 4/8:  46%|████▌     | 692/1500 [00:21<00:24, 33.27it/s, loss=1.26]
SASRec epoch 4/8:  46%|████▋     | 696/1500 [00:21<00:24, 33.11it/s, loss=1.26]
SASRec epoch 4/8:  47%|████▋     | 700/1500 [00:22<00:24, 33.25it/s, loss=1.26]
SASRec epoch 4/8:  47%|████▋     | 700/1500 [00:22<00:24, 33.25it/s, loss=1.24]
SASRec epoch 4/8:  47%|████▋     | 704/1500 [00:22<00:24, 32.09it/s, loss=1.24]
SASRec epoch 4/8:  47%|████▋     | 708/1500 [00:22<00:24, 32.35it/s, loss=1.24]
SASRec epoch 4/8:  47%|████▋     | 712/1500 [00:22<00:24, 32.66it/s, loss=1.24]
SASRec epoch 4/8:  48%|████▊     | 716/1500 [00:22<00:23, 32.83it/s, loss=1.24]
SASRec epoch 4/8:  48%|████▊     | 720/1500 [00:22<00:24, 32.50it/s, loss=1.24]
SASRec epoch 4/8:  48%|████▊     | 724/1500 [00:22<00:23, 32.87it/s, loss=1.24]
SASRec epoch 4/8:  49%|████▊     | 728/1500 [00:22<00:23, 32.94it/s, loss=1.24]
SASRec epoch 4/8:  49%|████▉     | 732/1500 [00:22<00:23, 33.24it/s, loss=1.24]
SASRec epoch 4/8:  49%|████▉     | 736/1500 [00:23<00:22, 33.27it/s, loss=1.24]
SASRec epoch 4/8:  49%|████▉     | 740/1500 [00:23<00:22, 33.34it/s, loss=1.24]
SASRec epoch 4/8:  50%|████▉     | 744/1500 [00:23<00:22, 33.40it/s, loss=1.24]
SASRec epoch 4/8:  50%|████▉     | 748/1500 [00:23<00:22, 33.42it/s, loss=1.24]
SASRec epoch 4/8:  50%|█████     | 750/1500 [00:23<00:22, 33.42it/s, loss=1.24]
SASRec epoch 4/8:  50%|█████     | 752/1500 [00:23<00:22, 32.74it/s, loss=1.24]
SASRec epoch 4/8:  50%|█████     | 756/1500 [00:23<00:22, 32.71it/s, loss=1.24]
SASRec epoch 4/8:  51%|█████     | 760/1500 [00:23<00:22, 32.96it/s, loss=1.24]
SASRec epoch 4/8:  51%|█████     | 764/1500 [00:23<00:22, 33.17it/s, loss=1.24]
SASRec epoch 4/8:  51%|█████     | 768/1500 [00:24<00:22, 33.10it/s, loss=1.24]
SASRec epoch 4/8:  51%|█████▏    | 772/1500 [00:24<00:21, 33.17it/s, loss=1.24]
SASRec epoch 4/8:  52%|█████▏    | 776/1500 [00:24<00:22, 32.89it/s, loss=1.24]
SASRec epoch 4/8:  52%|█████▏    | 780/1500 [00:24<00:21, 33.12it/s, loss=1.24]
SASRec epoch 4/8:  52%|█████▏    | 784/1500 [00:24<00:21, 33.12it/s, loss=1.24]
SASRec epoch 4/8:  53%|█████▎    | 788/1500 [00:24<00:21, 33.03it/s, loss=1.24]
SASRec epoch 4/8:  53%|█████▎    | 792/1500 [00:24<00:21, 33.21it/s, loss=1.24]
SASRec epoch 4/8:  53%|█████▎    | 796/1500 [00:24<00:21, 33.37it/s, loss=1.24]
SASRec epoch 4/8:  53%|█████▎    | 800/1500 [00:25<00:20, 33.75it/s, loss=1.24]
SASRec epoch 4/8:  53%|█████▎    | 800/1500 [00:25<00:20, 33.75it/s, loss=1.22]
SASRec epoch 4/8:  54%|█████▎    | 804/1500 [00:25<00:21, 32.81it/s, loss=1.22]
SASRec epoch 4/8:  54%|█████▍    | 808/1500 [00:25<00:20, 32.95it/s, loss=1.22]
SASRec epoch 4/8:  54%|█████▍    | 812/1500 [00:25<00:20, 33.17it/s, loss=1.22]
SASRec epoch 4/8:  54%|█████▍    | 816/1500 [00:25<00:20, 33.27it/s, loss=1.22]
SASRec epoch 4/8:  55%|█████▍    | 820/1500 [00:25<00:20, 33.33it/s, loss=1.22]
SASRec epoch 4/8:  55%|█████▍    | 824/1500 [00:25<00:20, 32.44it/s, loss=1.22]
SASRec epoch 4/8:  55%|█████▌    | 828/1500 [00:25<00:20, 32.50it/s, loss=1.22]
SASRec epoch 4/8:  55%|█████▌    | 832/1500 [00:26<00:20, 32.66it/s, loss=1.22]
SASRec epoch 4/8:  56%|█████▌    | 836/1500 [00:26<00:20, 32.86it/s, loss=1.22]
SASRec epoch 4/8:  56%|█████▌    | 840/1500 [00:26<00:20, 32.98it/s, loss=1.22]
SASRec epoch 4/8:  56%|█████▋    | 844/1500 [00:26<00:19, 33.06it/s, loss=1.22]
SASRec epoch 4/8:  57%|█████▋    | 848/1500 [00:26<00:19, 33.20it/s, loss=1.22]
SASRec epoch 4/8:  57%|█████▋    | 850/1500 [00:26<00:19, 33.20it/s, loss=1.23]
SASRec epoch 4/8:  57%|█████▋    | 852/1500 [00:26<00:19, 32.51it/s, loss=1.23]
SASRec epoch 4/8:  57%|█████▋    | 856/1500 [00:26<00:19, 32.48it/s, loss=1.23]
SASRec epoch 4/8:  57%|█████▋    | 860/1500 [00:26<00:19, 32.83it/s, loss=1.23]
SASRec epoch 4/8:  58%|█████▊    | 864/1500 [00:26<00:19, 32.96it/s, loss=1.23]
SASRec epoch 4/8:  58%|█████▊    | 868/1500 [00:27<00:19, 32.95it/s, loss=1.23]
SASRec epoch 4/8:  58%|█████▊    | 872/1500 [00:27<00:19, 32.86it/s, loss=1.23]
SASRec epoch 4/8:  58%|█████▊    | 876/1500 [00:27<00:20, 30.99it/s, loss=1.23]
SASRec epoch 4/8:  59%|█████▊    | 880/1500 [00:27<00:20, 30.62it/s, loss=1.23]
SASRec epoch 4/8:  59%|█████▉    | 884/1500 [00:27<00:20, 30.50it/s, loss=1.23]
SASRec epoch 4/8:  59%|█████▉    | 888/1500 [00:27<00:21, 28.70it/s, loss=1.23]
SASRec epoch 4/8:  59%|█████▉    | 891/1500 [00:27<00:22, 27.32it/s, loss=1.23]
SASRec epoch 4/8:  60%|█████▉    | 894/1500 [00:28<00:22, 27.24it/s, loss=1.23]
SASRec epoch 4/8:  60%|█████▉    | 897/1500 [00:28<00:21, 27.70it/s, loss=1.23]
SASRec epoch 4/8:  60%|██████    | 900/1500 [00:28<00:21, 28.17it/s, loss=1.23]
SASRec epoch 4/8:  60%|██████    | 900/1500 [00:28<00:21, 28.17it/s, loss=1.22]
SASRec epoch 4/8:  60%|██████    | 903/1500 [00:28<00:21, 28.31it/s, loss=1.22]
SASRec epoch 4/8:  60%|██████    | 907/1500 [00:28<00:20, 28.94it/s, loss=1.22]

[SASRec] epoch 4/8 loss=1.2356

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 5/8:   0%|          | 4/1500 [00:00<00:46, 32.01it/s]
SASRec epoch 5/8:   1%|          | 8/1500 [00:00<00:46, 32.38it/s]
SASRec epoch 5/8:   1%|          | 12/1500 [00:00<00:45, 32.48it/s]
SASRec epoch 5/8:   1%|          | 16/1500 [00:00<00:45, 32.93it/s]
SASRec epoch 5/8:   1%|▏         | 20/1500 [00:00<00:44, 33.33it/s]
SASRec epoch 5/8:   2%|▏         | 24/1500 [00:00<00:44, 33.28it/s]
SASRec epoch 5/8:   2%|▏         | 28/1500 [00:00<00:44, 32.93it/s]
SASRec epoch 5/8:   2%|▏         | 32/1500 [00:00<00:44, 33.13it/s]
SASRec epoch 5/8:   2%|▏         | 36/1500 [00:01<00:44, 33.16it/s]
SASRec epoch 5/8:   3%|▎         | 40/1500 [00:01<00:43, 33.18it/s]
SASRec epoch 5/8:   3%|▎         | 44/1500 [00:01<00:43, 33.15it/s]
SASRec epoch 5/8:   3%|▎         | 48/1500 [00:01<00:43, 33.19it/s]
SASRec epoch 5/8:   3%|▎         | 50/1500 [00:01<00:43, 33.19it/s, loss=1.18]
SASRec epoch 5/8:   3%|▎         | 52/1500 [00:01<00:44, 32.57it/s, loss=1.18]
SASRec epoch 5/8:   4%|▎         | 56/1500 [00:01<00:43, 32.86it/s, loss=1.18]
SASRec epoch 5/8:   4%|▍         | 60/1500 [00:01<00:44, 32.58it/s, loss=1.18]
SASRec epoch 5/8:   4%|▍         | 64/1500 [00:01<00:43, 32.89it/s, loss=1.18]
SASRec epoch 5/8:   5%|▍         | 68/1500 [00:02<00:43, 33.01it/s, loss=1.18]
SASRec epoch 5/8:   5%|▍         | 72/1500 [00:02<00:43, 33.05it/s, loss=1.18]
SASRec epoch 5/8:   5%|▌         | 76/1500 [00:02<00:43, 33.11it/s, loss=1.18]
SASRec epoch 5/8:   5%|▌         | 80/1500 [00:02<00:42, 33.35it/s, loss=1.18]
SASRec epoch 5/8:   6%|▌         | 84/1500 [00:02<00:42, 33.39it/s, loss=1.18]
SASRec epoch 5/8:   6%|▌         | 88/1500 [00:02<00:42, 33.18it/s, loss=1.18]
SASRec epoch 5/8:   6%|▌         | 92/1500 [00:02<00:42, 33.36it/s, loss=1.18]
SASRec epoch 5/8:   6%|▋         | 96/1500 [00:02<00:42, 33.30it/s, loss=1.18]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:03<00:42, 33.27it/s, loss=1.18]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:03<00:42, 33.27it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 104/1500 [00:03<00:42, 32.85it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 108/1500 [00:03<00:42, 32.61it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 112/1500 [00:03<00:42, 32.97it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 116/1500 [00:03<00:41, 33.09it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 120/1500 [00:03<00:41, 33.07it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 124/1500 [00:03<00:41, 33.12it/s, loss=1.16]
SASRec epoch 5/8:   9%|▊         | 128/1500 [00:03<00:41, 33.23it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 132/1500 [00:04<00:41, 32.68it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 136/1500 [00:04<00:41, 32.68it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 140/1500 [00:04<00:41, 32.67it/s, loss=1.16]
SASRec epoch 5/8:  10%|▉         | 144/1500 [00:04<00:41, 32.66it/s, loss=1.16]
SASRec epoch 5/8:  10%|▉         | 148/1500 [00:04<00:41, 32.72it/s, loss=1.16]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:04<00:41, 32.72it/s, loss=1.17]
SASRec epoch 5/8:  10%|█         | 152/1500 [00:04<00:41, 32.22it/s, loss=1.17]
SASRec epoch 5/8:  10%|█         | 156/1500 [00:04<00:41, 32.28it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 160/1500 [00:04<00:41, 32.40it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 164/1500 [00:04<00:41, 32.25it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 168/1500 [00:05<00:41, 32.37it/s, loss=1.17]
SASRec epoch 5/8:  11%|█▏        | 172/1500 [00:05<00:40, 32.69it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 176/1500 [00:05<00:40, 32.90it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 180/1500 [00:05<00:40, 32.91it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 184/1500 [00:05<00:39, 32.97it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 188/1500 [00:05<00:39, 32.92it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 192/1500 [00:05<00:39, 33.23it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 196/1500 [00:05<00:39, 33.10it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:06<00:40, 32.20it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:06<00:40, 32.20it/s, loss=1.17]
SASRec epoch 5/8:  14%|█▎        | 204/1500 [00:06<00:40, 32.00it/s, loss=1.17]
SASRec epoch 5/8:  14%|█▍        | 208/1500 [00:06<00:40, 32.21it/s, loss=1.17]
SASRec epoch 5/8:  14%|█▍        | 212/1500 [00:06<00:39, 32.48it/s, loss=1.17]
SASRec epoch 5/8:  14%|█▍        | 216/1500 [00:06<00:39, 32.51it/s, loss=1.17]
SASRec epoch 5/8:  15%|█▍        | 220/1500 [00:06<00:39, 32.74it/s, loss=1.17]
SASRec epoch 5/8:  15%|█▍        | 224/1500 [00:06<00:38, 33.00it/s, loss=1.17]
SASRec epoch 5/8:  15%|█▌        | 228/1500 [00:06<00:38, 32.95it/s, loss=1.17]
SASRec epoch 5/8:  15%|█▌        | 232/1500 [00:07<00:38, 32.63it/s, loss=1.17]
SASRec epoch 5/8:  16%|█▌        | 236/1500 [00:07<00:38, 32.89it/s, loss=1.17]
SASRec epoch 5/8:  16%|█▌        | 240/1500 [00:07<00:38, 33.05it/s, loss=1.17]
SASRec epoch 5/8:  16%|█▋        | 244/1500 [00:07<00:37, 33.22it/s, loss=1.17]
SASRec epoch 5/8:  17%|█▋        | 248/1500 [00:07<00:37, 33.02it/s, loss=1.17]
SASRec epoch 5/8:  17%|█▋        | 250/1500 [00:07<00:37, 33.02it/s, loss=1.16]
SASRec epoch 5/8:  17%|█▋        | 252/1500 [00:07<00:38, 32.17it/s, loss=1.16]
SASRec epoch 5/8:  17%|█▋        | 256/1500 [00:07<00:38, 32.29it/s, loss=1.16]
SASRec epoch 5/8:  17%|█▋        | 260/1500 [00:07<00:38, 32.39it/s, loss=1.16]
SASRec epoch 5/8:  18%|█▊        | 264/1500 [00:08<00:38, 32.51it/s, loss=1.16]
SASRec epoch 5/8:  18%|█▊        | 268/1500 [00:08<00:38, 32.37it/s, loss=1.16]
SASRec epoch 5/8:  18%|█▊        | 272/1500 [00:08<00:37, 32.69it/s, loss=1.16]
SASRec epoch 5/8:  18%|█▊        | 276/1500 [00:08<00:37, 32.81it/s, loss=1.16]
SASRec epoch 5/8:  19%|█▊        | 280/1500 [00:08<00:37, 32.91it/s, loss=1.16]
SASRec epoch 5/8:  19%|█▉        | 284/1500 [00:08<00:36, 33.08it/s, loss=1.16]
SASRec epoch 5/8:  19%|█▉        | 288/1500 [00:08<00:36, 32.89it/s, loss=1.16]
SASRec epoch 5/8:  19%|█▉        | 292/1500 [00:08<00:36, 32.96it/s, loss=1.16]
SASRec epoch 5/8:  20%|█▉        | 296/1500 [00:09<00:36, 33.10it/s, loss=1.16]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:09<00:36, 32.87it/s, loss=1.16]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:09<00:36, 32.87it/s, loss=1.15]
SASRec epoch 5/8:  20%|██        | 304/1500 [00:09<00:36, 32.54it/s, loss=1.15]
SASRec epoch 5/8:  21%|██        | 308/1500 [00:09<00:36, 32.79it/s, loss=1.15]
SASRec epoch 5/8:  21%|██        | 312/1500 [00:09<00:37, 32.03it/s, loss=1.15]
SASRec epoch 5/8:  21%|██        | 316/1500 [00:09<00:38, 30.79it/s, loss=1.15]
SASRec epoch 5/8:  21%|██▏       | 320/1500 [00:09<00:39, 30.01it/s, loss=1.15]
SASRec epoch 5/8:  22%|██▏       | 324/1500 [00:09<00:40, 29.27it/s, loss=1.15]
SASRec epoch 5/8:  22%|██▏       | 327/1500 [00:10<00:40, 28.93it/s, loss=1.15]
SASRec epoch 5/8:  22%|██▏       | 330/1500 [00:10<00:40, 28.55it/s, loss=1.15]
SASRec epoch 5/8:  22%|██▏       | 333/1500 [00:10<00:41, 28.19it/s, loss=1.15]
SASRec epoch 5/8:  22%|██▏       | 337/1500 [00:10<00:39, 29.33it/s, loss=1.15]
SASRec epoch 5/8:  23%|██▎       | 341/1500 [00:10<00:38, 29.98it/s, loss=1.15]
SASRec epoch 5/8:  23%|██▎       | 345/1500 [00:10<00:38, 30.21it/s, loss=1.15]
SASRec epoch 5/8:  23%|██▎       | 349/1500 [00:10<00:37, 30.40it/s, loss=1.15]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:10<00:37, 30.40it/s, loss=1.16]
SASRec epoch 5/8:  24%|██▎       | 353/1500 [00:10<00:37, 30.60it/s, loss=1.16]
SASRec epoch 5/8:  24%|██▍       | 357/1500 [00:11<00:37, 30.54it/s, loss=1.16]
SASRec epoch 5/8:  24%|██▍       | 361/1500 [00:11<00:36, 30.83it/s, loss=1.16]
SASRec epoch 5/8:  24%|██▍       | 365/1500 [00:11<00:37, 30.21it/s, loss=1.16]
SASRec epoch 5/8:  25%|██▍       | 369/1500 [00:11<00:38, 29.48it/s, loss=1.16]
SASRec epoch 5/8:  25%|██▍       | 372/1500 [00:11<00:38, 29.17it/s, loss=1.16]
SASRec epoch 5/8:  25%|██▌       | 376/1500 [00:11<00:37, 29.59it/s, loss=1.16]
SASRec epoch 5/8:  25%|██▌       | 379/1500 [00:11<00:38, 29.27it/s, loss=1.16]
SASRec epoch 5/8:  25%|██▌       | 382/1500 [00:11<00:38, 28.84it/s, loss=1.16]
SASRec epoch 5/8:  26%|██▌       | 385/1500 [00:12<00:39, 28.05it/s, loss=1.16]
SASRec epoch 5/8:  26%|██▌       | 389/1500 [00:12<00:38, 28.95it/s, loss=1.16]
SASRec epoch 5/8:  26%|██▌       | 393/1500 [00:12<00:37, 29.65it/s, loss=1.16]
SASRec epoch 5/8:  26%|██▋       | 397/1500 [00:12<00:36, 30.06it/s, loss=1.16]
SASRec epoch 5/8:  27%|██▋       | 400/1500 [00:12<00:36, 30.06it/s, loss=1.14]
SASRec epoch 5/8:  27%|██▋       | 401/1500 [00:12<00:36, 30.01it/s, loss=1.14]
SASRec epoch 5/8:  27%|██▋       | 405/1500 [00:12<00:35, 30.44it/s, loss=1.14]
SASRec epoch 5/8:  27%|██▋       | 409/1500 [00:12<00:36, 30.22it/s, loss=1.14]
SASRec epoch 5/8:  28%|██▊       | 413/1500 [00:12<00:36, 29.55it/s, loss=1.14]
SASRec epoch 5/8:  28%|██▊       | 416/1500 [00:13<00:37, 28.94it/s, loss=1.14]
SASRec epoch 5/8:  28%|██▊       | 419/1500 [00:13<00:37, 29.04it/s, loss=1.14]
SASRec epoch 5/8:  28%|██▊       | 422/1500 [00:13<00:38, 28.15it/s, loss=1.14]
SASRec epoch 5/8:  28%|██▊       | 425/1500 [00:13<00:38, 28.07it/s, loss=1.14]
SASRec epoch 5/8:  29%|██▊       | 428/1500 [00:13<00:37, 28.53it/s, loss=1.14]
SASRec epoch 5/8:  29%|██▊       | 431/1500 [00:13<00:38, 27.94it/s, loss=1.14]
SASRec epoch 5/8:  29%|██▉       | 434/1500 [00:13<00:38, 27.79it/s, loss=1.14]
SASRec epoch 5/8:  29%|██▉       | 437/1500 [00:13<00:38, 27.74it/s, loss=1.14]
SASRec epoch 5/8:  29%|██▉       | 440/1500 [00:13<00:38, 27.44it/s, loss=1.14]
SASRec epoch 5/8:  30%|██▉       | 443/1500 [00:14<00:37, 27.84it/s, loss=1.14]
SASRec epoch 5/8:  30%|██▉       | 447/1500 [00:14<00:35, 29.44it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 450/1500 [00:14<00:35, 29.44it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 451/1500 [00:14<00:35, 29.71it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 455/1500 [00:14<00:33, 30.89it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 459/1500 [00:14<00:33, 31.54it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 463/1500 [00:14<00:32, 31.51it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 467/1500 [00:14<00:32, 31.80it/s, loss=1.14]
SASRec epoch 5/8:  31%|███▏      | 471/1500 [00:14<00:32, 32.12it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 475/1500 [00:15<00:31, 32.32it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 479/1500 [00:15<00:31, 32.48it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 483/1500 [00:15<00:30, 32.85it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 487/1500 [00:15<00:30, 33.09it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 491/1500 [00:15<00:30, 33.08it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 495/1500 [00:15<00:30, 32.83it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 499/1500 [00:15<00:30, 32.67it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 500/1500 [00:15<00:30, 32.67it/s, loss=1.13]
SASRec epoch 5/8:  34%|███▎      | 503/1500 [00:15<00:31, 32.00it/s, loss=1.13]
SASRec epoch 5/8:  34%|███▍      | 507/1500 [00:15<00:30, 32.12it/s, loss=1.13]
SASRec epoch 5/8:  34%|███▍      | 511/1500 [00:16<00:30, 32.47it/s, loss=1.13]
SASRec epoch 5/8:  34%|███▍      | 515/1500 [00:16<00:30, 32.43it/s, loss=1.13]
SASRec epoch 5/8:  35%|███▍      | 519/1500 [00:16<00:30, 32.68it/s, loss=1.13]
SASRec epoch 5/8:  35%|███▍      | 523/1500 [00:16<00:29, 32.69it/s, loss=1.13]
SASRec epoch 5/8:  35%|███▌      | 527/1500 [00:16<00:29, 32.73it/s, loss=1.13]
SASRec epoch 5/8:  35%|███▌      | 531/1500 [00:16<00:29, 32.49it/s, loss=1.13]
SASRec epoch 5/8:  36%|███▌      | 535/1500 [00:16<00:29, 32.57it/s, loss=1.13]
SASRec epoch 5/8:  36%|███▌      | 539/1500 [00:16<00:29, 32.56it/s, loss=1.13]
SASRec epoch 5/8:  36%|███▌      | 543/1500 [00:17<00:29, 32.75it/s, loss=1.13]
SASRec epoch 5/8:  36%|███▋      | 547/1500 [00:17<00:29, 32.80it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 550/1500 [00:17<00:28, 32.80it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 551/1500 [00:17<00:29, 32.02it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 555/1500 [00:17<00:29, 32.33it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 559/1500 [00:17<00:28, 32.55it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 563/1500 [00:17<00:29, 32.28it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 567/1500 [00:17<00:28, 32.51it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 571/1500 [00:17<00:28, 32.74it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 575/1500 [00:18<00:28, 32.95it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▊      | 579/1500 [00:18<00:27, 32.93it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 583/1500 [00:18<00:27, 32.94it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 587/1500 [00:18<00:27, 32.76it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 591/1500 [00:18<00:27, 32.69it/s, loss=1.13]
SASRec epoch 5/8:  40%|███▉      | 595/1500 [00:18<00:27, 32.78it/s, loss=1.13]
SASRec epoch 5/8:  40%|███▉      | 599/1500 [00:18<00:27, 32.40it/s, loss=1.13]
SASRec epoch 5/8:  40%|████      | 600/1500 [00:18<00:27, 32.40it/s, loss=1.14]
SASRec epoch 5/8:  40%|████      | 603/1500 [00:18<00:27, 32.05it/s, loss=1.14]
SASRec epoch 5/8:  40%|████      | 607/1500 [00:19<00:27, 32.33it/s, loss=1.14]
SASRec epoch 5/8:  41%|████      | 611/1500 [00:19<00:27, 32.49it/s, loss=1.14]
SASRec epoch 5/8:  41%|████      | 615/1500 [00:19<00:26, 33.04it/s, loss=1.14]
SASRec epoch 5/8:  41%|████▏     | 619/1500 [00:19<00:26, 33.22it/s, loss=1.14]
SASRec epoch 5/8:  42%|████▏     | 623/1500 [00:19<00:26, 33.34it/s, loss=1.14]
SASRec epoch 5/8:  42%|████▏     | 627/1500 [00:19<00:26, 33.45it/s, loss=1.14]
SASRec epoch 5/8:  42%|████▏     | 631/1500 [00:19<00:26, 33.31it/s, loss=1.14]
SASRec epoch 5/8:  42%|████▏     | 635/1500 [00:19<00:26, 32.78it/s, loss=1.14]
SASRec epoch 5/8:  43%|████▎     | 639/1500 [00:20<00:26, 32.81it/s, loss=1.14]
SASRec epoch 5/8:  43%|████▎     | 643/1500 [00:20<00:26, 32.73it/s, loss=1.14]
SASRec epoch 5/8:  43%|████▎     | 647/1500 [00:20<00:25, 32.93it/s, loss=1.14]
SASRec epoch 5/8:  43%|████▎     | 650/1500 [00:20<00:25, 32.93it/s, loss=1.12]
SASRec epoch 5/8:  43%|████▎     | 651/1500 [00:20<00:26, 32.24it/s, loss=1.12]
SASRec epoch 5/8:  44%|████▎     | 655/1500 [00:20<00:25, 32.79it/s, loss=1.12]
SASRec epoch 5/8:  44%|████▍     | 659/1500 [00:20<00:25, 33.20it/s, loss=1.12]
SASRec epoch 5/8:  44%|████▍     | 663/1500 [00:20<00:25, 33.20it/s, loss=1.12]
SASRec epoch 5/8:  44%|████▍     | 667/1500 [00:20<00:25, 32.83it/s, loss=1.12]
SASRec epoch 5/8:  45%|████▍     | 671/1500 [00:21<00:25, 32.96it/s, loss=1.12]
SASRec epoch 5/8:  45%|████▌     | 675/1500 [00:21<00:24, 33.05it/s, loss=1.12]
SASRec epoch 5/8:  45%|████▌     | 679/1500 [00:21<00:24, 33.29it/s, loss=1.12]
SASRec epoch 5/8:  46%|████▌     | 683/1500 [00:21<00:24, 33.35it/s, loss=1.12]
SASRec epoch 5/8:  46%|████▌     | 687/1500 [00:21<00:24, 33.57it/s, loss=1.12]
SASRec epoch 5/8:  46%|████▌     | 691/1500 [00:21<00:24, 33.65it/s, loss=1.12]
SASRec epoch 5/8:  46%|████▋     | 695/1500 [00:21<00:24, 33.47it/s, loss=1.12]
SASRec epoch 5/8:  47%|████▋     | 699/1500 [00:21<00:24, 33.29it/s, loss=1.12]
SASRec epoch 5/8:  47%|████▋     | 700/1500 [00:21<00:24, 33.29it/s, loss=1.12]
SASRec epoch 5/8:  47%|████▋     | 703/1500 [00:21<00:24, 32.07it/s, loss=1.12]
SASRec epoch 5/8:  47%|████▋     | 707/1500 [00:22<00:24, 32.40it/s, loss=1.12]
SASRec epoch 5/8:  47%|████▋     | 711/1500 [00:22<00:24, 32.67it/s, loss=1.12]
SASRec epoch 5/8:  48%|████▊     | 715/1500 [00:22<00:23, 32.86it/s, loss=1.12]
SASRec epoch 5/8:  48%|████▊     | 719/1500 [00:22<00:23, 32.98it/s, loss=1.12]
SASRec epoch 5/8:  48%|████▊     | 723/1500 [00:22<00:23, 33.31it/s, loss=1.12]
SASRec epoch 5/8:  48%|████▊     | 727/1500 [00:22<00:23, 33.37it/s, loss=1.12]
SASRec epoch 5/8:  49%|████▊     | 731/1500 [00:22<00:23, 33.22it/s, loss=1.12]
SASRec epoch 5/8:  49%|████▉     | 735/1500 [00:22<00:22, 33.45it/s, loss=1.12]
SASRec epoch 5/8:  49%|████▉     | 739/1500 [00:23<00:23, 33.03it/s, loss=1.12]
SASRec epoch 5/8:  50%|████▉     | 743/1500 [00:23<00:22, 33.00it/s, loss=1.12]
SASRec epoch 5/8:  50%|████▉     | 747/1500 [00:23<00:22, 33.28it/s, loss=1.12]
SASRec epoch 5/8:  50%|█████     | 750/1500 [00:23<00:22, 33.28it/s, loss=1.13]
SASRec epoch 5/8:  50%|█████     | 751/1500 [00:23<00:23, 32.24it/s, loss=1.13]
SASRec epoch 5/8:  50%|█████     | 755/1500 [00:23<00:22, 32.67it/s, loss=1.13]
SASRec epoch 5/8:  51%|█████     | 759/1500 [00:23<00:22, 32.77it/s, loss=1.13]
SASRec epoch 5/8:  51%|█████     | 763/1500 [00:23<00:22, 32.74it/s, loss=1.13]
SASRec epoch 5/8:  51%|█████     | 767/1500 [00:23<00:22, 32.76it/s, loss=1.13]
SASRec epoch 5/8:  51%|█████▏    | 771/1500 [00:24<00:22, 32.42it/s, loss=1.13]
SASRec epoch 5/8:  52%|█████▏    | 775/1500 [00:24<00:23, 31.04it/s, loss=1.13]
SASRec epoch 5/8:  52%|█████▏    | 779/1500 [00:24<00:23, 30.60it/s, loss=1.13]
SASRec epoch 5/8:  52%|█████▏    | 783/1500 [00:24<00:23, 30.10it/s, loss=1.13]
SASRec epoch 5/8:  52%|█████▏    | 787/1500 [00:24<00:23, 30.28it/s, loss=1.13]
SASRec epoch 5/8:  53%|█████▎    | 791/1500 [00:24<00:23, 30.08it/s, loss=1.13]
SASRec epoch 5/8:  53%|█████▎    | 795/1500 [00:24<00:24, 29.22it/s, loss=1.13]
SASRec epoch 5/8:  53%|█████▎    | 799/1500 [00:24<00:23, 29.87it/s, loss=1.13]
SASRec epoch 5/8:  53%|█████▎    | 800/1500 [00:25<00:23, 29.87it/s, loss=1.12]
SASRec epoch 5/8:  53%|█████▎    | 802/1500 [00:25<00:23, 29.39it/s, loss=1.12]
SASRec epoch 5/8:  54%|█████▎    | 806/1500 [00:25<00:23, 29.96it/s, loss=1.12]
SASRec epoch 5/8:  54%|█████▍    | 810/1500 [00:25<00:22, 30.20it/s, loss=1.12]
SASRec epoch 5/8:  54%|█████▍    | 814/1500 [00:25<00:22, 30.44it/s, loss=1.12]
SASRec epoch 5/8:  55%|█████▍    | 818/1500 [00:25<00:22, 30.81it/s, loss=1.12]
SASRec epoch 5/8:  55%|█████▍    | 822/1500 [00:25<00:21, 31.20it/s, loss=1.12]
SASRec epoch 5/8:  55%|█████▌    | 826/1500 [00:25<00:21, 31.53it/s, loss=1.12]
SASRec epoch 5/8:  55%|█████▌    | 830/1500 [00:25<00:21, 31.71it/s, loss=1.12]
SASRec epoch 5/8:  56%|█████▌    | 834/1500 [00:26<00:21, 31.60it/s, loss=1.12]
SASRec epoch 5/8:  56%|█████▌    | 838/1500 [00:26<00:21, 30.60it/s, loss=1.12]
SASRec epoch 5/8:  56%|█████▌    | 842/1500 [00:26<00:21, 30.27it/s, loss=1.12]
SASRec epoch 5/8:  56%|█████▋    | 846/1500 [00:26<00:21, 30.46it/s, loss=1.12]
SASRec epoch 5/8:  57%|█████▋    | 850/1500 [00:26<00:21, 30.32it/s, loss=1.12]
SASRec epoch 5/8:  57%|█████▋    | 850/1500 [00:26<00:21, 30.32it/s, loss=1.11]
SASRec epoch 5/8:  57%|█████▋    | 854/1500 [00:26<00:22, 28.83it/s, loss=1.11]
SASRec epoch 5/8:  57%|█████▋    | 857/1500 [00:26<00:22, 28.76it/s, loss=1.11]
SASRec epoch 5/8:  57%|█████▋    | 861/1500 [00:27<00:21, 29.35it/s, loss=1.11]
SASRec epoch 5/8:  58%|█████▊    | 865/1500 [00:27<00:21, 29.88it/s, loss=1.11]
SASRec epoch 5/8:  58%|█████▊    | 868/1500 [00:27<00:21, 29.38it/s, loss=1.11]
SASRec epoch 5/8:  58%|█████▊    | 871/1500 [00:27<00:21, 29.32it/s, loss=1.11]
SASRec epoch 5/8:  58%|█████▊    | 874/1500 [00:27<00:21, 28.94it/s, loss=1.11]
SASRec epoch 5/8:  58%|█████▊    | 877/1500 [00:27<00:21, 28.97it/s, loss=1.11]
SASRec epoch 5/8:  59%|█████▊    | 880/1500 [00:27<00:21, 28.28it/s, loss=1.11]
SASRec epoch 5/8:  59%|█████▉    | 883/1500 [00:27<00:22, 27.88it/s, loss=1.11]
SASRec epoch 5/8:  59%|█████▉    | 886/1500 [00:27<00:22, 27.25it/s, loss=1.11]
SASRec epoch 5/8:  59%|█████▉    | 890/1500 [00:28<00:21, 28.36it/s, loss=1.11]
SASRec epoch 5/8:  60%|█████▉    | 893/1500 [00:28<00:21, 28.30it/s, loss=1.11]
SASRec epoch 5/8:  60%|█████▉    | 896/1500 [00:28<00:21, 28.58it/s, loss=1.11]
SASRec epoch 5/8:  60%|██████    | 900/1500 [00:28<00:20, 28.91it/s, loss=1.11]
SASRec epoch 5/8:  60%|██████    | 900/1500 [00:28<00:20, 28.91it/s, loss=1.12]
SASRec epoch 5/8:  60%|██████    | 903/1500 [00:28<00:20, 28.48it/s, loss=1.12]

[SASRec] epoch 5/8 loss=1.1217

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 6/8:   0%|          | 4/1500 [00:00<00:46, 32.09it/s]
SASRec epoch 6/8:   1%|          | 8/1500 [00:00<00:45, 32.64it/s]
SASRec epoch 6/8:   1%|          | 12/1500 [00:00<00:45, 32.35it/s]
SASRec epoch 6/8:   1%|          | 16/1500 [00:00<00:45, 32.49it/s]
SASRec epoch 6/8:   1%|▏         | 20/1500 [00:00<00:44, 32.90it/s]
SASRec epoch 6/8:   2%|▏         | 24/1500 [00:00<00:44, 32.97it/s]
SASRec epoch 6/8:   2%|▏         | 28/1500 [00:00<00:44, 32.96it/s]
SASRec epoch 6/8:   2%|▏         | 32/1500 [00:00<00:44, 33.16it/s]
SASRec epoch 6/8:   2%|▏         | 36/1500 [00:01<00:43, 33.54it/s]
SASRec epoch 6/8:   3%|▎         | 40/1500 [00:01<00:43, 33.63it/s]
SASRec epoch 6/8:   3%|▎         | 44/1500 [00:01<00:43, 33.81it/s]
SASRec epoch 6/8:   3%|▎         | 48/1500 [00:01<00:44, 32.73it/s]
SASRec epoch 6/8:   3%|▎         | 50/1500 [00:01<00:44, 32.73it/s, loss=1.07]
SASRec epoch 6/8:   3%|▎         | 52/1500 [00:01<00:44, 32.44it/s, loss=1.07]
SASRec epoch 6/8:   4%|▎         | 56/1500 [00:01<00:44, 32.77it/s, loss=1.07]
SASRec epoch 6/8:   4%|▍         | 60/1500 [00:01<00:43, 33.02it/s, loss=1.07]
SASRec epoch 6/8:   4%|▍         | 64/1500 [00:01<00:43, 33.38it/s, loss=1.07]
SASRec epoch 6/8:   5%|▍         | 68/1500 [00:02<00:42, 33.50it/s, loss=1.07]
SASRec epoch 6/8:   5%|▍         | 72/1500 [00:02<00:42, 33.46it/s, loss=1.07]
SASRec epoch 6/8:   5%|▌         | 76/1500 [00:02<00:42, 33.54it/s, loss=1.07]
SASRec epoch 6/8:   5%|▌         | 80/1500 [00:02<00:42, 33.08it/s, loss=1.07]
SASRec epoch 6/8:   6%|▌         | 84/1500 [00:02<00:42, 33.05it/s, loss=1.07]
SASRec epoch 6/8:   6%|▌         | 88/1500 [00:02<00:42, 33.08it/s, loss=1.07]
SASRec epoch 6/8:   6%|▌         | 92/1500 [00:02<00:42, 32.97it/s, loss=1.07]
SASRec epoch 6/8:   6%|▋         | 96/1500 [00:02<00:42, 33.19it/s, loss=1.07]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:03<00:42, 33.03it/s, loss=1.07]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:03<00:42, 33.03it/s, loss=1.07]
SASRec epoch 6/8:   7%|▋         | 104/1500 [00:03<00:42, 32.58it/s, loss=1.07]
SASRec epoch 6/8:   7%|▋         | 108/1500 [00:03<00:42, 32.66it/s, loss=1.07]
SASRec epoch 6/8:   7%|▋         | 112/1500 [00:03<00:42, 32.65it/s, loss=1.07]
SASRec epoch 6/8:   8%|▊         | 116/1500 [00:03<00:43, 32.11it/s, loss=1.07]
SASRec epoch 6/8:   8%|▊         | 120/1500 [00:03<00:43, 32.01it/s, loss=1.07]
SASRec epoch 6/8:   8%|▊         | 124/1500 [00:03<00:42, 32.35it/s, loss=1.07]
SASRec epoch 6/8:   9%|▊         | 128/1500 [00:03<00:42, 32.54it/s, loss=1.07]
SASRec epoch 6/8:   9%|▉         | 132/1500 [00:04<00:41, 32.60it/s, loss=1.07]
SASRec epoch 6/8:   9%|▉         | 136/1500 [00:04<00:41, 32.75it/s, loss=1.07]
SASRec epoch 6/8:   9%|▉         | 140/1500 [00:04<00:41, 32.83it/s, loss=1.07]
SASRec epoch 6/8:  10%|▉         | 144/1500 [00:04<00:41, 33.01it/s, loss=1.07]
SASRec epoch 6/8:  10%|▉         | 148/1500 [00:04<00:41, 32.45it/s, loss=1.07]
SASRec epoch 6/8:  10%|█         | 150/1500 [00:04<00:41, 32.45it/s, loss=1.08]
SASRec epoch 6/8:  10%|█         | 152/1500 [00:04<00:42, 31.79it/s, loss=1.08]
SASRec epoch 6/8:  10%|█         | 156/1500 [00:04<00:42, 31.80it/s, loss=1.08]
SASRec epoch 6/8:  11%|█         | 160/1500 [00:04<00:41, 32.15it/s, loss=1.08]
SASRec epoch 6/8:  11%|█         | 164/1500 [00:05<00:41, 32.49it/s, loss=1.08]
SASRec epoch 6/8:  11%|█         | 168/1500 [00:05<00:40, 32.71it/s, loss=1.08]
SASRec epoch 6/8:  11%|█▏        | 172/1500 [00:05<00:40, 33.02it/s, loss=1.08]
SASRec epoch 6/8:  12%|█▏        | 176/1500 [00:05<00:39, 33.24it/s, loss=1.08]
SASRec epoch 6/8:  12%|█▏        | 180/1500 [00:05<00:39, 33.23it/s, loss=1.08]
SASRec epoch 6/8:  12%|█▏        | 184/1500 [00:05<00:40, 32.58it/s, loss=1.08]
SASRec epoch 6/8:  13%|█▎        | 188/1500 [00:05<00:39, 32.82it/s, loss=1.08]
SASRec epoch 6/8:  13%|█▎        | 192/1500 [00:05<00:39, 33.09it/s, loss=1.08]
SASRec epoch 6/8:  13%|█▎        | 196/1500 [00:05<00:39, 33.18it/s, loss=1.08]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:06<00:39, 33.04it/s, loss=1.08]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:06<00:39, 33.04it/s, loss=1.06]
SASRec epoch 6/8:  14%|█▎        | 204/1500 [00:06<00:39, 32.44it/s, loss=1.06]
SASRec epoch 6/8:  14%|█▍        | 208/1500 [00:06<00:39, 32.71it/s, loss=1.06]
SASRec epoch 6/8:  14%|█▍        | 212/1500 [00:06<00:39, 32.85it/s, loss=1.06]
SASRec epoch 6/8:  14%|█▍        | 216/1500 [00:06<00:40, 31.54it/s, loss=1.06]
SASRec epoch 6/8:  15%|█▍        | 220/1500 [00:06<00:42, 30.46it/s, loss=1.06]
SASRec epoch 6/8:  15%|█▍        | 224/1500 [00:06<00:42, 30.35it/s, loss=1.06]
SASRec epoch 6/8:  15%|█▌        | 228/1500 [00:07<00:42, 30.13it/s, loss=1.06]
SASRec epoch 6/8:  15%|█▌        | 232/1500 [00:07<00:41, 30.34it/s, loss=1.06]
SASRec epoch 6/8:  16%|█▌        | 236/1500 [00:07<00:41, 30.11it/s, loss=1.06]
SASRec epoch 6/8:  16%|█▌        | 240/1500 [00:07<00:41, 30.31it/s, loss=1.06]
SASRec epoch 6/8:  16%|█▋        | 244/1500 [00:07<00:40, 30.74it/s, loss=1.06]
SASRec epoch 6/8:  17%|█▋        | 248/1500 [00:07<00:40, 30.85it/s, loss=1.06]
SASRec epoch 6/8:  17%|█▋        | 250/1500 [00:07<00:40, 30.85it/s, loss=1.06]
SASRec epoch 6/8:  17%|█▋        | 252/1500 [00:07<00:41, 30.40it/s, loss=1.06]
SASRec epoch 6/8:  17%|█▋        | 256/1500 [00:07<00:40, 30.67it/s, loss=1.06]
SASRec epoch 6/8:  17%|█▋        | 260/1500 [00:08<00:40, 30.92it/s, loss=1.06]
SASRec epoch 6/8:  18%|█▊        | 264/1500 [00:08<00:39, 30.94it/s, loss=1.06]
SASRec epoch 6/8:  18%|█▊        | 268/1500 [00:08<00:39, 31.30it/s, loss=1.06]
SASRec epoch 6/8:  18%|█▊        | 272/1500 [00:08<00:39, 30.97it/s, loss=1.06]
SASRec epoch 6/8:  18%|█▊        | 276/1500 [00:08<00:39, 30.69it/s, loss=1.06]
SASRec epoch 6/8:  19%|█▊        | 280/1500 [00:08<00:39, 30.76it/s, loss=1.06]
SASRec epoch 6/8:  19%|█▉        | 284/1500 [00:08<00:39, 30.67it/s, loss=1.06]
SASRec epoch 6/8:  19%|█▉        | 288/1500 [00:08<00:39, 30.64it/s, loss=1.06]
SASRec epoch 6/8:  19%|█▉        | 292/1500 [00:09<00:38, 31.15it/s, loss=1.06]
SASRec epoch 6/8:  20%|█▉        | 296/1500 [00:09<00:38, 31.35it/s, loss=1.06]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:09<00:38, 31.37it/s, loss=1.06]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:09<00:38, 31.37it/s, loss=1.06]
SASRec epoch 6/8:  20%|██        | 304/1500 [00:09<00:38, 30.69it/s, loss=1.06]
SASRec epoch 6/8:  21%|██        | 308/1500 [00:09<00:38, 30.87it/s, loss=1.06]
SASRec epoch 6/8:  21%|██        | 312/1500 [00:09<00:38, 30.99it/s, loss=1.06]
SASRec epoch 6/8:  21%|██        | 316/1500 [00:09<00:37, 31.30it/s, loss=1.06]
SASRec epoch 6/8:  21%|██▏       | 320/1500 [00:09<00:38, 30.51it/s, loss=1.06]
SASRec epoch 6/8:  22%|██▏       | 324/1500 [00:10<00:38, 30.60it/s, loss=1.06]
SASRec epoch 6/8:  22%|██▏       | 328/1500 [00:10<00:38, 30.20it/s, loss=1.06]
SASRec epoch 6/8:  22%|██▏       | 332/1500 [00:10<00:39, 29.89it/s, loss=1.06]
SASRec epoch 6/8:  22%|██▏       | 335/1500 [00:10<00:39, 29.32it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 338/1500 [00:10<00:40, 28.61it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 341/1500 [00:10<00:41, 28.09it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 344/1500 [00:10<00:40, 28.54it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 347/1500 [00:10<00:41, 28.06it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:11<00:41, 27.70it/s, loss=1.06]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:11<00:41, 27.70it/s, loss=1.05]
SASRec epoch 6/8:  24%|██▎       | 353/1500 [00:11<00:42, 26.76it/s, loss=1.05]
SASRec epoch 6/8:  24%|██▍       | 357/1500 [00:11<00:39, 28.79it/s, loss=1.05]
SASRec epoch 6/8:  24%|██▍       | 361/1500 [00:11<00:37, 30.12it/s, loss=1.05]
SASRec epoch 6/8:  24%|██▍       | 365/1500 [00:11<00:36, 30.91it/s, loss=1.05]
SASRec epoch 6/8:  25%|██▍       | 369/1500 [00:11<00:35, 31.79it/s, loss=1.05]
SASRec epoch 6/8:  25%|██▍       | 373/1500 [00:11<00:35, 32.16it/s, loss=1.05]
SASRec epoch 6/8:  25%|██▌       | 377/1500 [00:11<00:34, 32.54it/s, loss=1.05]
SASRec epoch 6/8:  25%|██▌       | 381/1500 [00:12<00:34, 32.57it/s, loss=1.05]
SASRec epoch 6/8:  26%|██▌       | 385/1500 [00:12<00:34, 32.39it/s, loss=1.05]
SASRec epoch 6/8:  26%|██▌       | 389/1500 [00:12<00:34, 32.32it/s, loss=1.05]
SASRec epoch 6/8:  26%|██▌       | 393/1500 [00:12<00:34, 32.37it/s, loss=1.05]
SASRec epoch 6/8:  26%|██▋       | 397/1500 [00:12<00:33, 32.79it/s, loss=1.05]
SASRec epoch 6/8:  27%|██▋       | 400/1500 [00:12<00:33, 32.79it/s, loss=1.05]
SASRec epoch 6/8:  27%|██▋       | 401/1500 [00:12<00:34, 32.14it/s, loss=1.05]
SASRec epoch 6/8:  27%|██▋       | 405/1500 [00:12<00:33, 32.66it/s, loss=1.05]
SASRec epoch 6/8:  27%|██▋       | 409/1500 [00:12<00:33, 32.97it/s, loss=1.05]
SASRec epoch 6/8:  28%|██▊       | 413/1500 [00:12<00:33, 32.78it/s, loss=1.05]
SASRec epoch 6/8:  28%|██▊       | 417/1500 [00:13<00:33, 32.59it/s, loss=1.05]
SASRec epoch 6/8:  28%|██▊       | 421/1500 [00:13<00:32, 32.78it/s, loss=1.05]
SASRec epoch 6/8:  28%|██▊       | 425/1500 [00:13<00:32, 32.98it/s, loss=1.05]
SASRec epoch 6/8:  29%|██▊       | 429/1500 [00:13<00:32, 33.18it/s, loss=1.05]
SASRec epoch 6/8:  29%|██▉       | 433/1500 [00:13<00:32, 33.06it/s, loss=1.05]
SASRec epoch 6/8:  29%|██▉       | 437/1500 [00:13<00:31, 33.32it/s, loss=1.05]
SASRec epoch 6/8:  29%|██▉       | 441/1500 [00:13<00:31, 33.58it/s, loss=1.05]
SASRec epoch 6/8:  30%|██▉       | 445/1500 [00:13<00:31, 33.30it/s, loss=1.05]
SASRec epoch 6/8:  30%|██▉       | 449/1500 [00:14<00:31, 33.19it/s, loss=1.05]
SASRec epoch 6/8:  30%|███       | 450/1500 [00:14<00:31, 33.19it/s, loss=1.05]
SASRec epoch 6/8:  30%|███       | 453/1500 [00:14<00:32, 31.84it/s, loss=1.05]
SASRec epoch 6/8:  30%|███       | 457/1500 [00:14<00:32, 32.14it/s, loss=1.05]
SASRec epoch 6/8:  31%|███       | 461/1500 [00:14<00:31, 32.54it/s, loss=1.05]
SASRec epoch 6/8:  31%|███       | 465/1500 [00:14<00:31, 32.58it/s, loss=1.05]
SASRec epoch 6/8:  31%|███▏      | 469/1500 [00:14<00:31, 32.87it/s, loss=1.05]
SASRec epoch 6/8:  32%|███▏      | 473/1500 [00:14<00:31, 32.95it/s, loss=1.05]
SASRec epoch 6/8:  32%|███▏      | 477/1500 [00:14<00:30, 33.05it/s, loss=1.05]
SASRec epoch 6/8:  32%|███▏      | 481/1500 [00:15<00:30, 33.00it/s, loss=1.05]
SASRec epoch 6/8:  32%|███▏      | 485/1500 [00:15<00:30, 32.96it/s, loss=1.05]
SASRec epoch 6/8:  33%|███▎      | 489/1500 [00:15<00:31, 32.00it/s, loss=1.05]
SASRec epoch 6/8:  33%|███▎      | 493/1500 [00:15<00:31, 32.28it/s, loss=1.05]
SASRec epoch 6/8:  33%|███▎      | 497/1500 [00:15<00:31, 32.17it/s, loss=1.05]
SASRec epoch 6/8:  33%|███▎      | 500/1500 [00:15<00:31, 32.17it/s, loss=1.04]
SASRec epoch 6/8:  33%|███▎      | 501/1500 [00:15<00:31, 31.39it/s, loss=1.04]
SASRec epoch 6/8:  34%|███▎      | 505/1500 [00:15<00:31, 31.98it/s, loss=1.04]
SASRec epoch 6/8:  34%|███▍      | 509/1500 [00:15<00:30, 32.32it/s, loss=1.04]
SASRec epoch 6/8:  34%|███▍      | 513/1500 [00:16<00:30, 32.68it/s, loss=1.04]
SASRec epoch 6/8:  34%|███▍      | 517/1500 [00:16<00:30, 32.54it/s, loss=1.04]
SASRec epoch 6/8:  35%|███▍      | 521/1500 [00:16<00:30, 32.07it/s, loss=1.04]
SASRec epoch 6/8:  35%|███▌      | 525/1500 [00:16<00:30, 32.38it/s, loss=1.04]
SASRec epoch 6/8:  35%|███▌      | 529/1500 [00:16<00:30, 32.32it/s, loss=1.04]
SASRec epoch 6/8:  36%|███▌      | 533/1500 [00:16<00:29, 32.53it/s, loss=1.04]
SASRec epoch 6/8:  36%|███▌      | 537/1500 [00:16<00:29, 32.61it/s, loss=1.04]
SASRec epoch 6/8:  36%|███▌      | 541/1500 [00:16<00:29, 32.70it/s, loss=1.04]
SASRec epoch 6/8:  36%|███▋      | 545/1500 [00:17<00:29, 32.66it/s, loss=1.04]
SASRec epoch 6/8:  37%|███▋      | 549/1500 [00:17<00:29, 32.70it/s, loss=1.04]
SASRec epoch 6/8:  37%|███▋      | 550/1500 [00:17<00:29, 32.70it/s, loss=1.05]
SASRec epoch 6/8:  37%|███▋      | 553/1500 [00:17<00:29, 32.20it/s, loss=1.05]
SASRec epoch 6/8:  37%|███▋      | 557/1500 [00:17<00:29, 31.99it/s, loss=1.05]
SASRec epoch 6/8:  37%|███▋      | 561/1500 [00:17<00:28, 32.47it/s, loss=1.05]
SASRec epoch 6/8:  38%|███▊      | 565/1500 [00:17<00:28, 32.43it/s, loss=1.05]
SASRec epoch 6/8:  38%|███▊      | 569/1500 [00:17<00:28, 32.63it/s, loss=1.05]
SASRec epoch 6/8:  38%|███▊      | 573/1500 [00:17<00:28, 32.77it/s, loss=1.05]
SASRec epoch 6/8:  38%|███▊      | 577/1500 [00:18<00:28, 32.94it/s, loss=1.05]
SASRec epoch 6/8:  39%|███▊      | 581/1500 [00:18<00:27, 33.07it/s, loss=1.05]
SASRec epoch 6/8:  39%|███▉      | 585/1500 [00:18<00:27, 33.27it/s, loss=1.05]
SASRec epoch 6/8:  39%|███▉      | 589/1500 [00:18<00:27, 33.42it/s, loss=1.05]
SASRec epoch 6/8:  40%|███▉      | 593/1500 [00:18<00:27, 33.30it/s, loss=1.05]
SASRec epoch 6/8:  40%|███▉      | 597/1500 [00:18<00:27, 33.26it/s, loss=1.05]
SASRec epoch 6/8:  40%|████      | 600/1500 [00:18<00:27, 33.26it/s, loss=1.04]
SASRec epoch 6/8:  40%|████      | 601/1500 [00:18<00:27, 32.60it/s, loss=1.04]
SASRec epoch 6/8:  40%|████      | 605/1500 [00:18<00:27, 32.82it/s, loss=1.04]
SASRec epoch 6/8:  41%|████      | 609/1500 [00:18<00:27, 32.96it/s, loss=1.04]
SASRec epoch 6/8:  41%|████      | 613/1500 [00:19<00:26, 33.29it/s, loss=1.04]
SASRec epoch 6/8:  41%|████      | 617/1500 [00:19<00:26, 33.48it/s, loss=1.04]
SASRec epoch 6/8:  41%|████▏     | 621/1500 [00:19<00:26, 33.59it/s, loss=1.04]
SASRec epoch 6/8:  42%|████▏     | 625/1500 [00:19<00:26, 32.98it/s, loss=1.04]
SASRec epoch 6/8:  42%|████▏     | 629/1500 [00:19<00:26, 32.95it/s, loss=1.04]
SASRec epoch 6/8:  42%|████▏     | 633/1500 [00:19<00:26, 33.32it/s, loss=1.04]
SASRec epoch 6/8:  42%|████▏     | 637/1500 [00:19<00:25, 33.33it/s, loss=1.04]
SASRec epoch 6/8:  43%|████▎     | 641/1500 [00:19<00:25, 33.12it/s, loss=1.04]
SASRec epoch 6/8:  43%|████▎     | 645/1500 [00:20<00:25, 33.18it/s, loss=1.04]
SASRec epoch 6/8:  43%|████▎     | 649/1500 [00:20<00:25, 33.13it/s, loss=1.04]
SASRec epoch 6/8:  43%|████▎     | 650/1500 [00:20<00:25, 33.13it/s, loss=1.04]
SASRec epoch 6/8:  44%|████▎     | 653/1500 [00:20<00:26, 32.37it/s, loss=1.04]
SASRec epoch 6/8:  44%|████▍     | 657/1500 [00:20<00:25, 32.50it/s, loss=1.04]
SASRec epoch 6/8:  44%|████▍     | 661/1500 [00:20<00:26, 31.81it/s, loss=1.04]
SASRec epoch 6/8:  44%|████▍     | 665/1500 [00:20<00:25, 32.49it/s, loss=1.04]
SASRec epoch 6/8:  45%|████▍     | 669/1500 [00:20<00:25, 32.80it/s, loss=1.04]
SASRec epoch 6/8:  45%|████▍     | 673/1500 [00:20<00:25, 32.91it/s, loss=1.04]
SASRec epoch 6/8:  45%|████▌     | 677/1500 [00:21<00:24, 33.07it/s, loss=1.04]
SASRec epoch 6/8:  45%|████▌     | 681/1500 [00:21<00:24, 32.97it/s, loss=1.04]
SASRec epoch 6/8:  46%|████▌     | 685/1500 [00:21<00:25, 31.66it/s, loss=1.04]
SASRec epoch 6/8:  46%|████▌     | 689/1500 [00:21<00:26, 31.12it/s, loss=1.04]
SASRec epoch 6/8:  46%|████▌     | 693/1500 [00:21<00:26, 30.27it/s, loss=1.04]
SASRec epoch 6/8:  46%|████▋     | 697/1500 [00:21<00:26, 30.01it/s, loss=1.04]
SASRec epoch 6/8:  47%|████▋     | 700/1500 [00:21<00:26, 30.01it/s, loss=1.04]
SASRec epoch 6/8:  47%|████▋     | 701/1500 [00:21<00:26, 29.67it/s, loss=1.04]
SASRec epoch 6/8:  47%|████▋     | 704/1500 [00:21<00:26, 29.49it/s, loss=1.04]
SASRec epoch 6/8:  47%|████▋     | 708/1500 [00:22<00:26, 29.83it/s, loss=1.04]
SASRec epoch 6/8:  47%|████▋     | 712/1500 [00:22<00:26, 30.10it/s, loss=1.04]
SASRec epoch 6/8:  48%|████▊     | 716/1500 [00:22<00:26, 30.00it/s, loss=1.04]
SASRec epoch 6/8:  48%|████▊     | 720/1500 [00:22<00:25, 30.12it/s, loss=1.04]
SASRec epoch 6/8:  48%|████▊     | 724/1500 [00:22<00:25, 29.89it/s, loss=1.04]
SASRec epoch 6/8:  48%|████▊     | 727/1500 [00:22<00:25, 29.74it/s, loss=1.04]
SASRec epoch 6/8:  49%|████▊     | 730/1500 [00:22<00:26, 29.54it/s, loss=1.04]
SASRec epoch 6/8:  49%|████▉     | 733/1500 [00:22<00:26, 29.41it/s, loss=1.04]
SASRec epoch 6/8:  49%|████▉     | 736/1500 [00:23<00:26, 28.67it/s, loss=1.04]
SASRec epoch 6/8:  49%|████▉     | 739/1500 [00:23<00:26, 28.33it/s, loss=1.04]
SASRec epoch 6/8:  49%|████▉     | 742/1500 [00:23<00:26, 28.20it/s, loss=1.04]
SASRec epoch 6/8:  50%|████▉     | 746/1500 [00:23<00:25, 29.10it/s, loss=1.04]
SASRec epoch 6/8:  50%|████▉     | 749/1500 [00:23<00:25, 29.25it/s, loss=1.04]
SASRec epoch 6/8:  50%|█████     | 750/1500 [00:23<00:25, 29.25it/s, loss=1.04]
SASRec epoch 6/8:  50%|█████     | 752/1500 [00:23<00:25, 29.34it/s, loss=1.04]
SASRec epoch 6/8:  50%|█████     | 756/1500 [00:23<00:24, 30.15it/s, loss=1.04]
SASRec epoch 6/8:  51%|█████     | 760/1500 [00:23<00:24, 29.81it/s, loss=1.04]
SASRec epoch 6/8:  51%|█████     | 763/1500 [00:23<00:24, 29.72it/s, loss=1.04]
SASRec epoch 6/8:  51%|█████     | 766/1500 [00:24<00:24, 29.71it/s, loss=1.04]
SASRec epoch 6/8:  51%|█████▏    | 769/1500 [00:24<00:24, 29.55it/s, loss=1.04]
SASRec epoch 6/8:  52%|█████▏    | 773/1500 [00:24<00:24, 30.00it/s, loss=1.04]
SASRec epoch 6/8:  52%|█████▏    | 777/1500 [00:24<00:23, 30.34it/s, loss=1.04]
SASRec epoch 6/8:  52%|█████▏    | 781/1500 [00:24<00:23, 30.56it/s, loss=1.04]
SASRec epoch 6/8:  52%|█████▏    | 785/1500 [00:24<00:23, 30.08it/s, loss=1.04]
SASRec epoch 6/8:  53%|█████▎    | 789/1500 [00:24<00:23, 29.90it/s, loss=1.04]
SASRec epoch 6/8:  53%|█████▎    | 792/1500 [00:24<00:24, 28.39it/s, loss=1.04]
SASRec epoch 6/8:  53%|█████▎    | 795/1500 [00:25<00:24, 28.61it/s, loss=1.04]
SASRec epoch 6/8:  53%|█████▎    | 798/1500 [00:25<00:24, 28.52it/s, loss=1.04]
SASRec epoch 6/8:  53%|█████▎    | 800/1500 [00:25<00:24, 28.52it/s, loss=1.03]
SASRec epoch 6/8:  53%|█████▎    | 801/1500 [00:25<00:26, 26.71it/s, loss=1.03]
SASRec epoch 6/8:  54%|█████▎    | 804/1500 [00:25<00:25, 26.80it/s, loss=1.03]
SASRec epoch 6/8:  54%|█████▍    | 807/1500 [00:25<00:26, 26.44it/s, loss=1.03]
SASRec epoch 6/8:  54%|█████▍    | 810/1500 [00:25<00:26, 26.43it/s, loss=1.03]
SASRec epoch 6/8:  54%|█████▍    | 813/1500 [00:25<00:26, 26.21it/s, loss=1.03]
SASRec epoch 6/8:  54%|█████▍    | 816/1500 [00:25<00:26, 25.40it/s, loss=1.03]
SASRec epoch 6/8:  55%|█████▍    | 819/1500 [00:25<00:26, 25.70it/s, loss=1.03]
SASRec epoch 6/8:  55%|█████▍    | 823/1500 [00:26<00:24, 27.91it/s, loss=1.03]
SASRec epoch 6/8:  55%|█████▌    | 827/1500 [00:26<00:22, 29.27it/s, loss=1.03]
SASRec epoch 6/8:  55%|█████▌    | 831/1500 [00:26<00:22, 29.96it/s, loss=1.03]
SASRec epoch 6/8:  56%|█████▌    | 834/1500 [00:26<00:22, 29.88it/s, loss=1.03]
SASRec epoch 6/8:  56%|█████▌    | 838/1500 [00:26<00:21, 30.74it/s, loss=1.03]
SASRec epoch 6/8:  56%|█████▌    | 842/1500 [00:26<00:21, 31.00it/s, loss=1.03]
SASRec epoch 6/8:  56%|█████▋    | 846/1500 [00:26<00:20, 31.54it/s, loss=1.03]
SASRec epoch 6/8:  57%|█████▋    | 850/1500 [00:26<00:20, 31.91it/s, loss=1.03]
SASRec epoch 6/8:  57%|█████▋    | 850/1500 [00:26<00:20, 31.91it/s, loss=1.02]
SASRec epoch 6/8:  57%|█████▋    | 854/1500 [00:27<00:20, 30.80it/s, loss=1.02]
SASRec epoch 6/8:  57%|█████▋    | 858/1500 [00:27<00:20, 31.47it/s, loss=1.02]
SASRec epoch 6/8:  57%|█████▋    | 862/1500 [00:27<00:20, 31.73it/s, loss=1.02]
SASRec epoch 6/8:  58%|█████▊    | 866/1500 [00:27<00:19, 31.90it/s, loss=1.02]
SASRec epoch 6/8:  58%|█████▊    | 870/1500 [00:27<00:19, 32.00it/s, loss=1.02]
SASRec epoch 6/8:  58%|█████▊    | 874/1500 [00:27<00:19, 32.11it/s, loss=1.02]
SASRec epoch 6/8:  59%|█████▊    | 878/1500 [00:27<00:19, 32.31it/s, loss=1.02]
SASRec epoch 6/8:  59%|█████▉    | 882/1500 [00:27<00:18, 32.56it/s, loss=1.02]
SASRec epoch 6/8:  59%|█████▉    | 886/1500 [00:28<00:18, 32.36it/s, loss=1.02]
SASRec epoch 6/8:  59%|█████▉    | 890/1500 [00:28<00:19, 31.75it/s, loss=1.02]
SASRec epoch 6/8:  60%|█████▉    | 894/1500 [00:28<00:19, 30.92it/s, loss=1.02]
SASRec epoch 6/8:  60%|█████▉    | 898/1500 [00:28<00:19, 30.95it/s, loss=1.02]
SASRec epoch 6/8:  60%|██████    | 900/1500 [00:28<00:19, 30.95it/s, loss=1.03]
SASRec epoch 6/8:  60%|██████    | 902/1500 [00:28<00:19, 30.16it/s, loss=1.03]

[SASRec] epoch 6/8 loss=1.0331

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 7/8:   0%|          | 4/1500 [00:00<00:46, 32.14it/s]
SASRec epoch 7/8:   1%|          | 8/1500 [00:00<00:45, 32.74it/s]
SASRec epoch 7/8:   1%|          | 12/1500 [00:00<00:45, 32.85it/s]
SASRec epoch 7/8:   1%|          | 16/1500 [00:00<00:45, 32.73it/s]
SASRec epoch 7/8:   1%|▏         | 20/1500 [00:00<00:45, 32.56it/s]
SASRec epoch 7/8:   2%|▏         | 24/1500 [00:00<00:45, 32.23it/s]
SASRec epoch 7/8:   2%|▏         | 28/1500 [00:00<00:45, 32.32it/s]
SASRec epoch 7/8:   2%|▏         | 32/1500 [00:00<00:45, 32.34it/s]
SASRec epoch 7/8:   2%|▏         | 36/1500 [00:01<00:45, 32.16it/s]
SASRec epoch 7/8:   3%|▎         | 40/1500 [00:01<00:44, 32.52it/s]
SASRec epoch 7/8:   3%|▎         | 44/1500 [00:01<00:44, 32.45it/s]
SASRec epoch 7/8:   3%|▎         | 48/1500 [00:01<00:44, 32.65it/s]
SASRec epoch 7/8:   3%|▎         | 50/1500 [00:01<00:44, 32.65it/s, loss=0.99]
SASRec epoch 7/8:   3%|▎         | 52/1500 [00:01<00:45, 32.06it/s, loss=0.99]
SASRec epoch 7/8:   4%|▎         | 56/1500 [00:01<00:45, 31.75it/s, loss=0.99]
SASRec epoch 7/8:   4%|▍         | 60/1500 [00:01<00:44, 32.06it/s, loss=0.99]
SASRec epoch 7/8:   4%|▍         | 64/1500 [00:01<00:44, 32.19it/s, loss=0.99]
SASRec epoch 7/8:   5%|▍         | 68/1500 [00:02<00:44, 32.41it/s, loss=0.99]
SASRec epoch 7/8:   5%|▍         | 72/1500 [00:02<00:43, 32.80it/s, loss=0.99]
SASRec epoch 7/8:   5%|▌         | 76/1500 [00:02<00:42, 33.13it/s, loss=0.99]
SASRec epoch 7/8:   5%|▌         | 80/1500 [00:02<00:42, 33.27it/s, loss=0.99]
SASRec epoch 7/8:   6%|▌         | 84/1500 [00:02<00:42, 33.48it/s, loss=0.99]
SASRec epoch 7/8:   6%|▌         | 88/1500 [00:02<00:42, 33.54it/s, loss=0.99]
SASRec epoch 7/8:   6%|▌         | 92/1500 [00:02<00:42, 33.09it/s, loss=0.99]
SASRec epoch 7/8:   6%|▋         | 96/1500 [00:02<00:42, 33.01it/s, loss=0.99]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:03<00:42, 32.89it/s, loss=0.99]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:03<00:42, 32.89it/s, loss=0.973]
SASRec epoch 7/8:   7%|▋         | 104/1500 [00:03<00:43, 32.18it/s, loss=0.973]
SASRec epoch 7/8:   7%|▋         | 108/1500 [00:03<00:42, 32.45it/s, loss=0.973]
SASRec epoch 7/8:   7%|▋         | 112/1500 [00:03<00:42, 32.81it/s, loss=0.973]
SASRec epoch 7/8:   8%|▊         | 116/1500 [00:03<00:42, 32.90it/s, loss=0.973]
SASRec epoch 7/8:   8%|▊         | 120/1500 [00:03<00:42, 32.19it/s, loss=0.973]
SASRec epoch 7/8:   8%|▊         | 124/1500 [00:03<00:43, 31.30it/s, loss=0.973]
SASRec epoch 7/8:   9%|▊         | 128/1500 [00:03<00:44, 30.80it/s, loss=0.973]
SASRec epoch 7/8:   9%|▉         | 132/1500 [00:04<00:45, 30.38it/s, loss=0.973]
SASRec epoch 7/8:   9%|▉         | 136/1500 [00:04<00:44, 30.49it/s, loss=0.973]
SASRec epoch 7/8:   9%|▉         | 140/1500 [00:04<00:44, 30.41it/s, loss=0.973]
SASRec epoch 7/8:  10%|▉         | 144/1500 [00:04<00:44, 30.51it/s, loss=0.973]
SASRec epoch 7/8:  10%|▉         | 148/1500 [00:04<00:44, 30.25it/s, loss=0.973]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:04<00:44, 30.25it/s, loss=0.984]
SASRec epoch 7/8:  10%|█         | 152/1500 [00:04<00:44, 29.97it/s, loss=0.984]
SASRec epoch 7/8:  10%|█         | 155/1500 [00:04<00:44, 29.96it/s, loss=0.984]
SASRec epoch 7/8:  11%|█         | 158/1500 [00:04<00:45, 29.33it/s, loss=0.984]
SASRec epoch 7/8:  11%|█         | 161/1500 [00:05<00:45, 29.50it/s, loss=0.984]
SASRec epoch 7/8:  11%|█         | 165/1500 [00:05<00:44, 30.14it/s, loss=0.984]
SASRec epoch 7/8:  11%|█▏        | 169/1500 [00:05<00:43, 30.79it/s, loss=0.984]
SASRec epoch 7/8:  12%|█▏        | 173/1500 [00:05<00:42, 31.09it/s, loss=0.984]
SASRec epoch 7/8:  12%|█▏        | 177/1500 [00:05<00:42, 31.42it/s, loss=0.984]
SASRec epoch 7/8:  12%|█▏        | 181/1500 [00:05<00:41, 31.52it/s, loss=0.984]
SASRec epoch 7/8:  12%|█▏        | 185/1500 [00:05<00:41, 31.51it/s, loss=0.984]
SASRec epoch 7/8:  13%|█▎        | 189/1500 [00:05<00:44, 29.71it/s, loss=0.984]
SASRec epoch 7/8:  13%|█▎        | 192/1500 [00:06<00:45, 28.46it/s, loss=0.984]
SASRec epoch 7/8:  13%|█▎        | 195/1500 [00:06<00:45, 28.48it/s, loss=0.984]
SASRec epoch 7/8:  13%|█▎        | 198/1500 [00:06<00:45, 28.39it/s, loss=0.984]
SASRec epoch 7/8:  13%|█▎        | 200/1500 [00:06<00:45, 28.39it/s, loss=0.979]
SASRec epoch 7/8:  13%|█▎        | 201/1500 [00:06<00:46, 27.71it/s, loss=0.979]
SASRec epoch 7/8:  14%|█▎        | 204/1500 [00:06<00:46, 28.04it/s, loss=0.979]
SASRec epoch 7/8:  14%|█▍        | 207/1500 [00:06<00:46, 27.96it/s, loss=0.979]
SASRec epoch 7/8:  14%|█▍        | 211/1500 [00:06<00:44, 28.96it/s, loss=0.979]
SASRec epoch 7/8:  14%|█▍        | 215/1500 [00:06<00:43, 29.58it/s, loss=0.979]
SASRec epoch 7/8:  15%|█▍        | 219/1500 [00:07<00:43, 29.70it/s, loss=0.979]
SASRec epoch 7/8:  15%|█▍        | 222/1500 [00:07<00:44, 28.46it/s, loss=0.979]
SASRec epoch 7/8:  15%|█▌        | 225/1500 [00:07<00:45, 27.78it/s, loss=0.979]
SASRec epoch 7/8:  15%|█▌        | 228/1500 [00:07<00:47, 26.69it/s, loss=0.979]
SASRec epoch 7/8:  15%|█▌        | 231/1500 [00:07<00:47, 26.87it/s, loss=0.979]
SASRec epoch 7/8:  16%|█▌        | 234/1500 [00:07<00:46, 27.48it/s, loss=0.979]
SASRec epoch 7/8:  16%|█▌        | 237/1500 [00:07<00:46, 27.38it/s, loss=0.979]
SASRec epoch 7/8:  16%|█▌        | 240/1500 [00:07<00:45, 27.69it/s, loss=0.979]
SASRec epoch 7/8:  16%|█▌        | 243/1500 [00:07<00:46, 27.32it/s, loss=0.979]
SASRec epoch 7/8:  16%|█▋        | 246/1500 [00:08<00:46, 27.11it/s, loss=0.979]
SASRec epoch 7/8:  17%|█▋        | 249/1500 [00:08<00:45, 27.21it/s, loss=0.979]
SASRec epoch 7/8:  17%|█▋        | 250/1500 [00:08<00:45, 27.21it/s, loss=0.989]
SASRec epoch 7/8:  17%|█▋        | 252/1500 [00:08<00:47, 26.38it/s, loss=0.989]
SASRec epoch 7/8:  17%|█▋        | 255/1500 [00:08<00:45, 27.20it/s, loss=0.989]
SASRec epoch 7/8:  17%|█▋        | 258/1500 [00:08<00:45, 27.46it/s, loss=0.989]
SASRec epoch 7/8:  17%|█▋        | 262/1500 [00:08<00:42, 29.13it/s, loss=0.989]
SASRec epoch 7/8:  18%|█▊        | 266/1500 [00:08<00:40, 30.31it/s, loss=0.989]
SASRec epoch 7/8:  18%|█▊        | 270/1500 [00:08<00:39, 31.22it/s, loss=0.989]
SASRec epoch 7/8:  18%|█▊        | 274/1500 [00:08<00:39, 31.36it/s, loss=0.989]
SASRec epoch 7/8:  19%|█▊        | 278/1500 [00:09<00:38, 31.74it/s, loss=0.989]
SASRec epoch 7/8:  19%|█▉        | 282/1500 [00:09<00:37, 32.20it/s, loss=0.989]
SASRec epoch 7/8:  19%|█▉        | 286/1500 [00:09<00:37, 32.06it/s, loss=0.989]
SASRec epoch 7/8:  19%|█▉        | 290/1500 [00:09<00:37, 32.41it/s, loss=0.989]
SASRec epoch 7/8:  20%|█▉        | 294/1500 [00:09<00:36, 32.99it/s, loss=0.989]
SASRec epoch 7/8:  20%|█▉        | 298/1500 [00:09<00:36, 33.30it/s, loss=0.989]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:09<00:36, 33.30it/s, loss=0.971]
SASRec epoch 7/8:  20%|██        | 302/1500 [00:09<00:37, 32.29it/s, loss=0.971]
SASRec epoch 7/8:  20%|██        | 306/1500 [00:09<00:36, 32.66it/s, loss=0.971]
SASRec epoch 7/8:  21%|██        | 310/1500 [00:10<00:36, 32.73it/s, loss=0.971]
SASRec epoch 7/8:  21%|██        | 314/1500 [00:10<00:35, 33.09it/s, loss=0.971]
SASRec epoch 7/8:  21%|██        | 318/1500 [00:10<00:35, 33.02it/s, loss=0.971]
SASRec epoch 7/8:  21%|██▏       | 322/1500 [00:10<00:36, 32.26it/s, loss=0.971]
SASRec epoch 7/8:  22%|██▏       | 326/1500 [00:10<00:36, 32.54it/s, loss=0.971]
SASRec epoch 7/8:  22%|██▏       | 330/1500 [00:10<00:35, 32.60it/s, loss=0.971]
SASRec epoch 7/8:  22%|██▏       | 334/1500 [00:10<00:35, 32.83it/s, loss=0.971]
SASRec epoch 7/8:  23%|██▎       | 338/1500 [00:10<00:35, 33.02it/s, loss=0.971]
SASRec epoch 7/8:  23%|██▎       | 342/1500 [00:11<00:35, 32.83it/s, loss=0.971]
SASRec epoch 7/8:  23%|██▎       | 346/1500 [00:11<00:35, 32.95it/s, loss=0.971]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:11<00:34, 33.17it/s, loss=0.971]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:11<00:34, 33.17it/s, loss=0.97]
SASRec epoch 7/8:  24%|██▎       | 354/1500 [00:11<00:35, 32.29it/s, loss=0.97]
SASRec epoch 7/8:  24%|██▍       | 358/1500 [00:11<00:34, 32.65it/s, loss=0.97]
SASRec epoch 7/8:  24%|██▍       | 362/1500 [00:11<00:34, 32.82it/s, loss=0.97]
SASRec epoch 7/8:  24%|██▍       | 366/1500 [00:11<00:34, 32.67it/s, loss=0.97]
SASRec epoch 7/8:  25%|██▍       | 370/1500 [00:11<00:34, 32.83it/s, loss=0.97]
SASRec epoch 7/8:  25%|██▍       | 374/1500 [00:12<00:34, 32.74it/s, loss=0.97]
SASRec epoch 7/8:  25%|██▌       | 378/1500 [00:12<00:34, 32.61it/s, loss=0.97]
SASRec epoch 7/8:  25%|██▌       | 382/1500 [00:12<00:34, 32.57it/s, loss=0.97]
SASRec epoch 7/8:  26%|██▌       | 386/1500 [00:12<00:34, 32.63it/s, loss=0.97]
SASRec epoch 7/8:  26%|██▌       | 390/1500 [00:12<00:34, 31.72it/s, loss=0.97]
SASRec epoch 7/8:  26%|██▋       | 394/1500 [00:12<00:34, 31.86it/s, loss=0.97]
SASRec epoch 7/8:  27%|██▋       | 398/1500 [00:12<00:34, 32.18it/s, loss=0.97]
SASRec epoch 7/8:  27%|██▋       | 400/1500 [00:12<00:34, 32.18it/s, loss=0.962]
SASRec epoch 7/8:  27%|██▋       | 402/1500 [00:12<00:34, 31.57it/s, loss=0.962]
SASRec epoch 7/8:  27%|██▋       | 406/1500 [00:13<00:34, 31.82it/s, loss=0.962]
SASRec epoch 7/8:  27%|██▋       | 410/1500 [00:13<00:33, 32.33it/s, loss=0.962]
SASRec epoch 7/8:  28%|██▊       | 414/1500 [00:13<00:33, 32.69it/s, loss=0.962]
SASRec epoch 7/8:  28%|██▊       | 418/1500 [00:13<00:32, 32.88it/s, loss=0.962]
SASRec epoch 7/8:  28%|██▊       | 422/1500 [00:13<00:32, 32.78it/s, loss=0.962]
SASRec epoch 7/8:  28%|██▊       | 426/1500 [00:13<00:32, 32.97it/s, loss=0.962]
SASRec epoch 7/8:  29%|██▊       | 430/1500 [00:13<00:32, 33.17it/s, loss=0.962]
SASRec epoch 7/8:  29%|██▉       | 434/1500 [00:13<00:32, 33.11it/s, loss=0.962]
SASRec epoch 7/8:  29%|██▉       | 438/1500 [00:13<00:32, 33.03it/s, loss=0.962]
SASRec epoch 7/8:  29%|██▉       | 442/1500 [00:14<00:32, 32.74it/s, loss=0.962]
SASRec epoch 7/8:  30%|██▉       | 446/1500 [00:14<00:32, 32.90it/s, loss=0.962]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:14<00:31, 33.07it/s, loss=0.962]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:14<00:31, 33.07it/s, loss=0.955]
SASRec epoch 7/8:  30%|███       | 454/1500 [00:14<00:32, 32.45it/s, loss=0.955]
SASRec epoch 7/8:  31%|███       | 458/1500 [00:14<00:32, 31.70it/s, loss=0.955]
SASRec epoch 7/8:  31%|███       | 462/1500 [00:14<00:32, 31.93it/s, loss=0.955]
SASRec epoch 7/8:  31%|███       | 466/1500 [00:14<00:31, 32.47it/s, loss=0.955]
SASRec epoch 7/8:  31%|███▏      | 470/1500 [00:14<00:31, 32.46it/s, loss=0.955]
SASRec epoch 7/8:  32%|███▏      | 474/1500 [00:15<00:31, 32.67it/s, loss=0.955]
SASRec epoch 7/8:  32%|███▏      | 478/1500 [00:15<00:31, 32.70it/s, loss=0.955]
SASRec epoch 7/8:  32%|███▏      | 482/1500 [00:15<00:31, 32.82it/s, loss=0.955]
SASRec epoch 7/8:  32%|███▏      | 486/1500 [00:15<00:30, 33.03it/s, loss=0.955]
SASRec epoch 7/8:  33%|███▎      | 490/1500 [00:15<00:30, 32.75it/s, loss=0.955]
SASRec epoch 7/8:  33%|███▎      | 494/1500 [00:15<00:30, 33.04it/s, loss=0.955]
SASRec epoch 7/8:  33%|███▎      | 498/1500 [00:15<00:30, 33.01it/s, loss=0.955]
SASRec epoch 7/8:  33%|███▎      | 500/1500 [00:15<00:30, 33.01it/s, loss=0.956]
SASRec epoch 7/8:  33%|███▎      | 502/1500 [00:15<00:31, 32.02it/s, loss=0.956]
SASRec epoch 7/8:  34%|███▎      | 506/1500 [00:16<00:30, 32.14it/s, loss=0.956]
SASRec epoch 7/8:  34%|███▍      | 510/1500 [00:16<00:30, 32.36it/s, loss=0.956]
SASRec epoch 7/8:  34%|███▍      | 514/1500 [00:16<00:30, 32.38it/s, loss=0.956]
SASRec epoch 7/8:  35%|███▍      | 518/1500 [00:16<00:30, 32.51it/s, loss=0.956]
SASRec epoch 7/8:  35%|███▍      | 522/1500 [00:16<00:30, 32.18it/s, loss=0.956]
SASRec epoch 7/8:  35%|███▌      | 526/1500 [00:16<00:30, 32.06it/s, loss=0.956]
SASRec epoch 7/8:  35%|███▌      | 530/1500 [00:16<00:30, 32.21it/s, loss=0.956]
SASRec epoch 7/8:  36%|███▌      | 534/1500 [00:16<00:29, 32.40it/s, loss=0.956]
SASRec epoch 7/8:  36%|███▌      | 538/1500 [00:17<00:29, 32.47it/s, loss=0.956]
SASRec epoch 7/8:  36%|███▌      | 542/1500 [00:17<00:29, 32.58it/s, loss=0.956]
SASRec epoch 7/8:  36%|███▋      | 546/1500 [00:17<00:29, 32.55it/s, loss=0.956]
SASRec epoch 7/8:  37%|███▋      | 550/1500 [00:17<00:29, 32.52it/s, loss=0.956]
SASRec epoch 7/8:  37%|███▋      | 550/1500 [00:17<00:29, 32.52it/s, loss=0.947]
SASRec epoch 7/8:  37%|███▋      | 554/1500 [00:17<00:29, 32.10it/s, loss=0.947]
SASRec epoch 7/8:  37%|███▋      | 558/1500 [00:17<00:29, 31.78it/s, loss=0.947]
SASRec epoch 7/8:  37%|███▋      | 562/1500 [00:17<00:29, 32.13it/s, loss=0.947]
SASRec epoch 7/8:  38%|███▊      | 566/1500 [00:17<00:28, 32.36it/s, loss=0.947]
SASRec epoch 7/8:  38%|███▊      | 570/1500 [00:18<00:28, 32.41it/s, loss=0.947]
SASRec epoch 7/8:  38%|███▊      | 574/1500 [00:18<00:28, 32.38it/s, loss=0.947]
SASRec epoch 7/8:  39%|███▊      | 578/1500 [00:18<00:28, 32.56it/s, loss=0.947]
SASRec epoch 7/8:  39%|███▉      | 582/1500 [00:18<00:28, 32.50it/s, loss=0.947]
SASRec epoch 7/8:  39%|███▉      | 586/1500 [00:18<00:28, 32.35it/s, loss=0.947]
SASRec epoch 7/8:  39%|███▉      | 590/1500 [00:18<00:30, 29.48it/s, loss=0.947]
SASRec epoch 7/8:  40%|███▉      | 593/1500 [00:18<00:31, 29.12it/s, loss=0.947]
SASRec epoch 7/8:  40%|███▉      | 596/1500 [00:18<00:31, 28.88it/s, loss=0.947]
SASRec epoch 7/8:  40%|███▉      | 599/1500 [00:19<00:31, 28.96it/s, loss=0.947]
SASRec epoch 7/8:  40%|████      | 600/1500 [00:19<00:31, 28.96it/s, loss=0.951]
SASRec epoch 7/8:  40%|████      | 602/1500 [00:19<00:31, 28.58it/s, loss=0.951]
SASRec epoch 7/8:  40%|████      | 605/1500 [00:19<00:31, 28.76it/s, loss=0.951]
SASRec epoch 7/8:  41%|████      | 608/1500 [00:19<00:30, 28.83it/s, loss=0.951]
SASRec epoch 7/8:  41%|████      | 612/1500 [00:19<00:30, 29.37it/s, loss=0.951]
SASRec epoch 7/8:  41%|████      | 616/1500 [00:19<00:29, 29.90it/s, loss=0.951]
SASRec epoch 7/8:  41%|████▏     | 620/1500 [00:19<00:29, 29.95it/s, loss=0.951]
SASRec epoch 7/8:  42%|████▏     | 623/1500 [00:19<00:29, 29.52it/s, loss=0.951]
SASRec epoch 7/8:  42%|████▏     | 627/1500 [00:19<00:29, 29.87it/s, loss=0.951]
SASRec epoch 7/8:  42%|████▏     | 630/1500 [00:20<00:29, 29.65it/s, loss=0.951]
SASRec epoch 7/8:  42%|████▏     | 633/1500 [00:20<00:29, 29.45it/s, loss=0.951]
SASRec epoch 7/8:  42%|████▏     | 636/1500 [00:20<00:29, 29.12it/s, loss=0.951]
SASRec epoch 7/8:  43%|████▎     | 639/1500 [00:20<00:29, 28.96it/s, loss=0.951]
SASRec epoch 7/8:  43%|████▎     | 642/1500 [00:20<00:30, 28.46it/s, loss=0.951]
SASRec epoch 7/8:  43%|████▎     | 646/1500 [00:20<00:29, 29.39it/s, loss=0.951]
SASRec epoch 7/8:  43%|████▎     | 650/1500 [00:20<00:28, 30.04it/s, loss=0.951]
SASRec epoch 7/8:  43%|████▎     | 650/1500 [00:20<00:28, 30.04it/s, loss=0.943]
SASRec epoch 7/8:  44%|████▎     | 653/1500 [00:20<00:28, 29.46it/s, loss=0.943]
SASRec epoch 7/8:  44%|████▎     | 656/1500 [00:20<00:29, 29.08it/s, loss=0.943]
SASRec epoch 7/8:  44%|████▍     | 659/1500 [00:21<00:28, 29.32it/s, loss=0.943]
SASRec epoch 7/8:  44%|████▍     | 663/1500 [00:21<00:28, 29.75it/s, loss=0.943]
SASRec epoch 7/8:  44%|████▍     | 667/1500 [00:21<00:27, 30.09it/s, loss=0.943]
SASRec epoch 7/8:  45%|████▍     | 671/1500 [00:21<00:27, 30.34it/s, loss=0.943]
SASRec epoch 7/8:  45%|████▌     | 675/1500 [00:21<00:27, 30.49it/s, loss=0.943]
SASRec epoch 7/8:  45%|████▌     | 679/1500 [00:21<00:27, 30.05it/s, loss=0.943]
SASRec epoch 7/8:  46%|████▌     | 683/1500 [00:21<00:27, 29.44it/s, loss=0.943]
SASRec epoch 7/8:  46%|████▌     | 687/1500 [00:22<00:27, 29.64it/s, loss=0.943]
SASRec epoch 7/8:  46%|████▌     | 690/1500 [00:22<00:27, 29.31it/s, loss=0.943]
SASRec epoch 7/8:  46%|████▌     | 693/1500 [00:22<00:27, 29.29it/s, loss=0.943]
SASRec epoch 7/8:  46%|████▋     | 696/1500 [00:22<00:28, 28.55it/s, loss=0.943]
SASRec epoch 7/8:  47%|████▋     | 699/1500 [00:22<00:28, 28.31it/s, loss=0.943]
SASRec epoch 7/8:  47%|████▋     | 700/1500 [00:22<00:28, 28.31it/s, loss=0.927]
SASRec epoch 7/8:  47%|████▋     | 702/1500 [00:22<00:28, 27.97it/s, loss=0.927]
SASRec epoch 7/8:  47%|████▋     | 705/1500 [00:22<00:28, 27.44it/s, loss=0.927]
SASRec epoch 7/8:  47%|████▋     | 709/1500 [00:22<00:27, 28.43it/s, loss=0.927]
SASRec epoch 7/8:  47%|████▋     | 712/1500 [00:22<00:27, 28.38it/s, loss=0.927]
SASRec epoch 7/8:  48%|████▊     | 715/1500 [00:23<00:28, 27.36it/s, loss=0.927]
SASRec epoch 7/8:  48%|████▊     | 718/1500 [00:23<00:28, 27.59it/s, loss=0.927]
SASRec epoch 7/8:  48%|████▊     | 721/1500 [00:23<00:28, 27.28it/s, loss=0.927]
SASRec epoch 7/8:  48%|████▊     | 724/1500 [00:23<00:28, 27.36it/s, loss=0.927]
SASRec epoch 7/8:  48%|████▊     | 727/1500 [00:23<00:28, 27.38it/s, loss=0.927]
SASRec epoch 7/8:  49%|████▊     | 730/1500 [00:23<00:27, 27.75it/s, loss=0.927]
SASRec epoch 7/8:  49%|████▉     | 733/1500 [00:23<00:27, 28.33it/s, loss=0.927]
SASRec epoch 7/8:  49%|████▉     | 737/1500 [00:23<00:25, 30.03it/s, loss=0.927]
SASRec epoch 7/8:  49%|████▉     | 741/1500 [00:23<00:24, 30.99it/s, loss=0.927]
SASRec epoch 7/8:  50%|████▉     | 745/1500 [00:24<00:23, 31.57it/s, loss=0.927]
SASRec epoch 7/8:  50%|████▉     | 749/1500 [00:24<00:23, 31.75it/s, loss=0.927]
SASRec epoch 7/8:  50%|█████     | 750/1500 [00:24<00:23, 31.75it/s, loss=0.93]
SASRec epoch 7/8:  50%|█████     | 753/1500 [00:24<00:24, 30.99it/s, loss=0.93]
SASRec epoch 7/8:  50%|█████     | 757/1500 [00:24<00:23, 31.46it/s, loss=0.93]
SASRec epoch 7/8:  51%|█████     | 761/1500 [00:24<00:23, 31.51it/s, loss=0.93]
SASRec epoch 7/8:  51%|█████     | 765/1500 [00:24<00:22, 31.98it/s, loss=0.93]
SASRec epoch 7/8:  51%|█████▏    | 769/1500 [00:24<00:22, 32.22it/s, loss=0.93]
SASRec epoch 7/8:  52%|█████▏    | 773/1500 [00:24<00:22, 32.39it/s, loss=0.93]
SASRec epoch 7/8:  52%|█████▏    | 777/1500 [00:25<00:22, 32.24it/s, loss=0.93]
SASRec epoch 7/8:  52%|█████▏    | 781/1500 [00:25<00:22, 32.31it/s, loss=0.93]
SASRec epoch 7/8:  52%|█████▏    | 785/1500 [00:25<00:22, 32.39it/s, loss=0.93]
SASRec epoch 7/8:  53%|█████▎    | 789/1500 [00:25<00:22, 31.44it/s, loss=0.93]
SASRec epoch 7/8:  53%|█████▎    | 793/1500 [00:25<00:22, 31.63it/s, loss=0.93]
SASRec epoch 7/8:  53%|█████▎    | 797/1500 [00:25<00:21, 31.97it/s, loss=0.93]
SASRec epoch 7/8:  53%|█████▎    | 800/1500 [00:25<00:21, 31.97it/s, loss=0.944]
SASRec epoch 7/8:  53%|█████▎    | 801/1500 [00:25<00:22, 31.41it/s, loss=0.944]
SASRec epoch 7/8:  54%|█████▎    | 805/1500 [00:25<00:21, 31.83it/s, loss=0.944]
SASRec epoch 7/8:  54%|█████▍    | 809/1500 [00:26<00:21, 31.84it/s, loss=0.944]
SASRec epoch 7/8:  54%|█████▍    | 813/1500 [00:26<00:21, 32.29it/s, loss=0.944]
SASRec epoch 7/8:  54%|█████▍    | 817/1500 [00:26<00:21, 32.38it/s, loss=0.944]
SASRec epoch 7/8:  55%|█████▍    | 821/1500 [00:26<00:21, 32.13it/s, loss=0.944]
SASRec epoch 7/8:  55%|█████▌    | 825/1500 [00:26<00:20, 32.20it/s, loss=0.944]
SASRec epoch 7/8:  55%|█████▌    | 829/1500 [00:26<00:20, 32.21it/s, loss=0.944]
SASRec epoch 7/8:  56%|█████▌    | 833/1500 [00:26<00:20, 32.36it/s, loss=0.944]
SASRec epoch 7/8:  56%|█████▌    | 837/1500 [00:26<00:20, 32.37it/s, loss=0.944]
SASRec epoch 7/8:  56%|█████▌    | 841/1500 [00:27<00:20, 32.07it/s, loss=0.944]
SASRec epoch 7/8:  56%|█████▋    | 845/1500 [00:27<00:20, 32.03it/s, loss=0.944]
SASRec epoch 7/8:  57%|█████▋    | 849/1500 [00:27<00:20, 32.07it/s, loss=0.944]
SASRec epoch 7/8:  57%|█████▋    | 850/1500 [00:27<00:20, 32.07it/s, loss=0.952]
SASRec epoch 7/8:  57%|█████▋    | 853/1500 [00:27<00:20, 31.27it/s, loss=0.952]
SASRec epoch 7/8:  57%|█████▋    | 857/1500 [00:27<00:20, 31.69it/s, loss=0.952]
SASRec epoch 7/8:  57%|█████▋    | 861/1500 [00:27<00:19, 32.16it/s, loss=0.952]
SASRec epoch 7/8:  58%|█████▊    | 865/1500 [00:27<00:19, 32.49it/s, loss=0.952]
SASRec epoch 7/8:  58%|█████▊    | 869/1500 [00:27<00:19, 32.73it/s, loss=0.952]
SASRec epoch 7/8:  58%|█████▊    | 873/1500 [00:28<00:19, 32.69it/s, loss=0.952]

[SASRec] epoch 7/8 loss=0.9399

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 8/8:   0%|          | 4/1500 [00:00<00:48, 31.10it/s]
SASRec epoch 8/8:   1%|          | 8/1500 [00:00<00:46, 31.93it/s]
SASRec epoch 8/8:   1%|          | 12/1500 [00:00<00:46, 32.03it/s]
SASRec epoch 8/8:   1%|          | 16/1500 [00:00<00:46, 32.18it/s]
SASRec epoch 8/8:   1%|▏         | 20/1500 [00:00<00:46, 31.83it/s]
SASRec epoch 8/8:   2%|▏         | 24/1500 [00:00<00:45, 32.27it/s]
SASRec epoch 8/8:   2%|▏         | 28/1500 [00:00<00:46, 31.75it/s]
SASRec epoch 8/8:   2%|▏         | 32/1500 [00:01<00:48, 30.37it/s]
SASRec epoch 8/8:   2%|▏         | 36/1500 [00:01<00:48, 29.92it/s]
SASRec epoch 8/8:   3%|▎         | 40/1500 [00:01<00:49, 29.41it/s]
SASRec epoch 8/8:   3%|▎         | 43/1500 [00:01<00:50, 28.67it/s]
SASRec epoch 8/8:   3%|▎         | 46/1500 [00:01<00:50, 28.95it/s]
SASRec epoch 8/8:   3%|▎         | 49/1500 [00:01<00:49, 29.12it/s]
SASRec epoch 8/8:   3%|▎         | 50/1500 [00:01<00:49, 29.12it/s, loss=0.899]
SASRec epoch 8/8:   3%|▎         | 52/1500 [00:01<00:50, 28.74it/s, loss=0.899]
SASRec epoch 8/8:   4%|▎         | 55/1500 [00:01<00:49, 28.94it/s, loss=0.899]
SASRec epoch 8/8:   4%|▍         | 59/1500 [00:01<00:49, 29.26it/s, loss=0.899]
SASRec epoch 8/8:   4%|▍         | 62/1500 [00:02<00:48, 29.37it/s, loss=0.899]
SASRec epoch 8/8:   4%|▍         | 66/1500 [00:02<00:48, 29.58it/s, loss=0.899]
SASRec epoch 8/8:   5%|▍         | 70/1500 [00:02<00:47, 29.94it/s, loss=0.899]
SASRec epoch 8/8:   5%|▍         | 73/1500 [00:02<00:48, 29.48it/s, loss=0.899]
SASRec epoch 8/8:   5%|▌         | 76/1500 [00:02<00:48, 29.28it/s, loss=0.899]
SASRec epoch 8/8:   5%|▌         | 79/1500 [00:02<00:49, 28.82it/s, loss=0.899]
SASRec epoch 8/8:   5%|▌         | 82/1500 [00:02<00:48, 29.10it/s, loss=0.899]
SASRec epoch 8/8:   6%|▌         | 86/1500 [00:02<00:47, 29.67it/s, loss=0.899]
SASRec epoch 8/8:   6%|▌         | 89/1500 [00:02<00:47, 29.50it/s, loss=0.899]
SASRec epoch 8/8:   6%|▌         | 93/1500 [00:03<00:46, 30.16it/s, loss=0.899]
SASRec epoch 8/8:   6%|▋         | 97/1500 [00:03<00:47, 29.66it/s, loss=0.899]
SASRec epoch 8/8:   7%|▋         | 100/1500 [00:03<00:47, 29.66it/s, loss=0.895]
SASRec epoch 8/8:   7%|▋         | 101/1500 [00:03<00:46, 29.84it/s, loss=0.895]
SASRec epoch 8/8:   7%|▋         | 105/1500 [00:03<00:46, 30.14it/s, loss=0.895]
SASRec epoch 8/8:   7%|▋         | 109/1500 [00:03<00:45, 30.42it/s, loss=0.895]
SASRec epoch 8/8:   8%|▊         | 113/1500 [00:03<00:45, 30.69it/s, loss=0.895]
SASRec epoch 8/8:   8%|▊         | 117/1500 [00:03<00:44, 30.77it/s, loss=0.895]
SASRec epoch 8/8:   8%|▊         | 121/1500 [00:04<00:45, 30.57it/s, loss=0.895]
SASRec epoch 8/8:   8%|▊         | 125/1500 [00:04<00:44, 30.66it/s, loss=0.895]
SASRec epoch 8/8:   9%|▊         | 129/1500 [00:04<00:44, 30.78it/s, loss=0.895]
SASRec epoch 8/8:   9%|▉         | 133/1500 [00:04<00:44, 30.78it/s, loss=0.895]
SASRec epoch 8/8:   9%|▉         | 137/1500 [00:04<00:44, 30.91it/s, loss=0.895]
SASRec epoch 8/8:   9%|▉         | 141/1500 [00:04<00:43, 31.09it/s, loss=0.895]
SASRec epoch 8/8:  10%|▉         | 145/1500 [00:04<00:43, 30.80it/s, loss=0.895]
SASRec epoch 8/8:  10%|▉         | 149/1500 [00:04<00:44, 30.52it/s, loss=0.895]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:04<00:44, 30.52it/s, loss=0.897]
SASRec epoch 8/8:  10%|█         | 153/1500 [00:05<00:45, 29.41it/s, loss=0.897]
SASRec epoch 8/8:  10%|█         | 156/1500 [00:05<00:47, 28.33it/s, loss=0.897]
SASRec epoch 8/8:  11%|█         | 159/1500 [00:05<00:47, 28.22it/s, loss=0.897]
SASRec epoch 8/8:  11%|█         | 162/1500 [00:05<00:46, 28.60it/s, loss=0.897]
SASRec epoch 8/8:  11%|█         | 165/1500 [00:05<00:46, 28.56it/s, loss=0.897]
SASRec epoch 8/8:  11%|█         | 168/1500 [00:05<00:47, 28.33it/s, loss=0.897]
SASRec epoch 8/8:  11%|█▏        | 171/1500 [00:05<00:46, 28.39it/s, loss=0.897]
SASRec epoch 8/8:  12%|█▏        | 174/1500 [00:05<00:46, 28.41it/s, loss=0.897]
SASRec epoch 8/8:  12%|█▏        | 177/1500 [00:05<00:46, 28.55it/s, loss=0.897]
SASRec epoch 8/8:  12%|█▏        | 180/1500 [00:06<00:49, 26.76it/s, loss=0.897]
SASRec epoch 8/8:  12%|█▏        | 184/1500 [00:06<00:46, 28.41it/s, loss=0.897]
SASRec epoch 8/8:  13%|█▎        | 188/1500 [00:06<00:44, 29.73it/s, loss=0.897]
SASRec epoch 8/8:  13%|█▎        | 192/1500 [00:06<00:42, 30.74it/s, loss=0.897]
SASRec epoch 8/8:  13%|█▎        | 196/1500 [00:06<00:41, 31.31it/s, loss=0.897]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:06<00:40, 31.77it/s, loss=0.897]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:06<00:40, 31.77it/s, loss=0.886]
SASRec epoch 8/8:  14%|█▎        | 204/1500 [00:06<00:41, 31.43it/s, loss=0.886]
SASRec epoch 8/8:  14%|█▍        | 208/1500 [00:06<00:40, 31.68it/s, loss=0.886]
SASRec epoch 8/8:  14%|█▍        | 212/1500 [00:07<00:40, 31.81it/s, loss=0.886]
SASRec epoch 8/8:  14%|█▍        | 216/1500 [00:07<00:40, 31.83it/s, loss=0.886]
SASRec epoch 8/8:  15%|█▍        | 220/1500 [00:07<00:40, 31.76it/s, loss=0.886]
SASRec epoch 8/8:  15%|█▍        | 224/1500 [00:07<00:39, 32.45it/s, loss=0.886]
SASRec epoch 8/8:  15%|█▌        | 228/1500 [00:07<00:38, 32.83it/s, loss=0.886]
SASRec epoch 8/8:  15%|█▌        | 232/1500 [00:07<00:38, 32.99it/s, loss=0.886]
SASRec epoch 8/8:  16%|█▌        | 236/1500 [00:07<00:38, 33.12it/s, loss=0.886]
SASRec epoch 8/8:  16%|█▌        | 240/1500 [00:07<00:38, 33.16it/s, loss=0.886]
SASRec epoch 8/8:  16%|█▋        | 244/1500 [00:08<00:37, 33.15it/s, loss=0.886]
SASRec epoch 8/8:  17%|█▋        | 248/1500 [00:08<00:37, 33.38it/s, loss=0.886]
SASRec epoch 8/8:  17%|█▋        | 250/1500 [00:08<00:37, 33.38it/s, loss=0.887]
SASRec epoch 8/8:  17%|█▋        | 252/1500 [00:08<00:38, 32.35it/s, loss=0.887]
SASRec epoch 8/8:  17%|█▋        | 256/1500 [00:08<00:38, 32.68it/s, loss=0.887]
SASRec epoch 8/8:  17%|█▋        | 260/1500 [00:08<00:37, 33.00it/s, loss=0.887]
SASRec epoch 8/8:  18%|█▊        | 264/1500 [00:08<00:37, 33.20it/s, loss=0.887]
SASRec epoch 8/8:  18%|█▊        | 268/1500 [00:08<00:36, 33.39it/s, loss=0.887]
SASRec epoch 8/8:  18%|█▊        | 272/1500 [00:08<00:36, 33.61it/s, loss=0.887]
SASRec epoch 8/8:  18%|█▊        | 276/1500 [00:08<00:36, 33.26it/s, loss=0.887]
SASRec epoch 8/8:  19%|█▊        | 280/1500 [00:09<00:36, 33.16it/s, loss=0.887]
SASRec epoch 8/8:  19%|█▉        | 284/1500 [00:09<00:36, 33.24it/s, loss=0.887]
SASRec epoch 8/8:  19%|█▉        | 288/1500 [00:09<00:37, 32.73it/s, loss=0.887]
SASRec epoch 8/8:  19%|█▉        | 292/1500 [00:09<00:36, 33.06it/s, loss=0.887]
SASRec epoch 8/8:  20%|█▉        | 296/1500 [00:09<00:36, 33.00it/s, loss=0.887]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:09<00:36, 32.93it/s, loss=0.887]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:09<00:36, 32.93it/s, loss=0.873]
SASRec epoch 8/8:  20%|██        | 304/1500 [00:09<00:36, 32.58it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 308/1500 [00:09<00:36, 32.72it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 312/1500 [00:10<00:36, 32.99it/s, loss=0.873]
SASRec epoch 8/8:  21%|██        | 316/1500 [00:10<00:35, 32.94it/s, loss=0.873]
SASRec epoch 8/8:  21%|██▏       | 320/1500 [00:10<00:35, 33.06it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 324/1500 [00:10<00:35, 32.97it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 328/1500 [00:10<00:35, 32.80it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 332/1500 [00:10<00:35, 32.69it/s, loss=0.873]
SASRec epoch 8/8:  22%|██▏       | 336/1500 [00:10<00:35, 32.98it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 340/1500 [00:10<00:35, 32.47it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 344/1500 [00:11<00:35, 32.18it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 348/1500 [00:11<00:35, 32.35it/s, loss=0.873]
SASRec epoch 8/8:  23%|██▎       | 350/1500 [00:11<00:35, 32.35it/s, loss=0.887]
SASRec epoch 8/8:  23%|██▎       | 352/1500 [00:11<00:36, 31.71it/s, loss=0.887]
SASRec epoch 8/8:  24%|██▎       | 356/1500 [00:11<00:36, 31.38it/s, loss=0.887]
SASRec epoch 8/8:  24%|██▍       | 360/1500 [00:11<00:36, 31.59it/s, loss=0.887]
SASRec epoch 8/8:  24%|██▍       | 364/1500 [00:11<00:35, 31.97it/s, loss=0.887]
SASRec epoch 8/8:  25%|██▍       | 368/1500 [00:11<00:34, 32.39it/s, loss=0.887]
SASRec epoch 8/8:  25%|██▍       | 372/1500 [00:11<00:34, 32.65it/s, loss=0.887]
SASRec epoch 8/8:  25%|██▌       | 376/1500 [00:12<00:34, 32.54it/s, loss=0.887]
SASRec epoch 8/8:  25%|██▌       | 380/1500 [00:12<00:34, 32.62it/s, loss=0.887]
SASRec epoch 8/8:  26%|██▌       | 384/1500 [00:12<00:34, 32.63it/s, loss=0.887]
SASRec epoch 8/8:  26%|██▌       | 388/1500 [00:12<00:34, 32.17it/s, loss=0.887]
SASRec epoch 8/8:  26%|██▌       | 392/1500 [00:12<00:34, 32.46it/s, loss=0.887]
SASRec epoch 8/8:  26%|██▋       | 396/1500 [00:12<00:34, 32.36it/s, loss=0.887]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:12<00:33, 32.64it/s, loss=0.887]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:12<00:33, 32.64it/s, loss=0.873]
SASRec epoch 8/8:  27%|██▋       | 404/1500 [00:12<00:34, 32.12it/s, loss=0.873]
SASRec epoch 8/8:  27%|██▋       | 408/1500 [00:13<00:33, 32.17it/s, loss=0.873]
SASRec epoch 8/8:  27%|██▋       | 412/1500 [00:13<00:33, 32.21it/s, loss=0.873]
SASRec epoch 8/8:  28%|██▊       | 416/1500 [00:13<00:33, 32.31it/s, loss=0.873]
SASRec epoch 8/8:  28%|██▊       | 420/1500 [00:13<00:33, 32.56it/s, loss=0.873]
SASRec epoch 8/8:  28%|██▊       | 424/1500 [00:13<00:33, 32.12it/s, loss=0.873]
SASRec epoch 8/8:  29%|██▊       | 428/1500 [00:13<00:33, 32.46it/s, loss=0.873]
SASRec epoch 8/8:  29%|██▉       | 432/1500 [00:13<00:32, 32.61it/s, loss=0.873]
SASRec epoch 8/8:  29%|██▉       | 436/1500 [00:13<00:32, 32.74it/s, loss=0.873]
SASRec epoch 8/8:  29%|██▉       | 440/1500 [00:14<00:32, 32.42it/s, loss=0.873]
SASRec epoch 8/8:  30%|██▉       | 444/1500 [00:14<00:32, 32.63it/s, loss=0.873]
SASRec epoch 8/8:  30%|██▉       | 448/1500 [00:14<00:32, 32.49it/s, loss=0.873]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:14<00:32, 32.49it/s, loss=0.874]
SASRec epoch 8/8:  30%|███       | 452/1500 [00:14<00:32, 32.05it/s, loss=0.874]
SASRec epoch 8/8:  30%|███       | 456/1500 [00:14<00:33, 31.58it/s, loss=0.874]
SASRec epoch 8/8:  31%|███       | 460/1500 [00:14<00:32, 31.85it/s, loss=0.874]
SASRec epoch 8/8:  31%|███       | 464/1500 [00:14<00:32, 32.12it/s, loss=0.874]
SASRec epoch 8/8:  31%|███       | 468/1500 [00:14<00:31, 32.48it/s, loss=0.874]
SASRec epoch 8/8:  31%|███▏      | 472/1500 [00:15<00:31, 32.46it/s, loss=0.874]
SASRec epoch 8/8:  32%|███▏      | 476/1500 [00:15<00:31, 32.68it/s, loss=0.874]
SASRec epoch 8/8:  32%|███▏      | 480/1500 [00:15<00:31, 32.80it/s, loss=0.874]
SASRec epoch 8/8:  32%|███▏      | 484/1500 [00:15<00:31, 32.66it/s, loss=0.874]
SASRec epoch 8/8:  33%|███▎      | 488/1500 [00:15<00:30, 32.68it/s, loss=0.874]
SASRec epoch 8/8:  33%|███▎      | 492/1500 [00:15<00:31, 31.86it/s, loss=0.874]
SASRec epoch 8/8:  33%|███▎      | 496/1500 [00:15<00:31, 32.08it/s, loss=0.874]
SASRec epoch 8/8:  33%|███▎      | 500/1500 [00:15<00:31, 32.18it/s, loss=0.874]
SASRec epoch 8/8:  33%|███▎      | 500/1500 [00:15<00:31, 32.18it/s, loss=0.876]
SASRec epoch 8/8:  34%|███▎      | 504/1500 [00:16<00:31, 31.52it/s, loss=0.876]
SASRec epoch 8/8:  34%|███▍      | 508/1500 [00:16<00:32, 30.74it/s, loss=0.876]
SASRec epoch 8/8:  34%|███▍      | 512/1500 [00:16<00:32, 30.02it/s, loss=0.876]
SASRec epoch 8/8:  34%|███▍      | 516/1500 [00:16<00:32, 30.09it/s, loss=0.876]
SASRec epoch 8/8:  35%|███▍      | 520/1500 [00:16<00:33, 29.43it/s, loss=0.876]
SASRec epoch 8/8:  35%|███▍      | 523/1500 [00:16<00:33, 29.13it/s, loss=0.876]
SASRec epoch 8/8:  35%|███▌      | 526/1500 [00:16<00:33, 28.78it/s, loss=0.876]
SASRec epoch 8/8:  35%|███▌      | 529/1500 [00:16<00:33, 29.01it/s, loss=0.876]
SASRec epoch 8/8:  35%|███▌      | 532/1500 [00:17<00:33, 29.13it/s, loss=0.876]
SASRec epoch 8/8:  36%|███▌      | 535/1500 [00:17<00:32, 29.35it/s, loss=0.876]
SASRec epoch 8/8:  36%|███▌      | 538/1500 [00:17<00:32, 29.49it/s, loss=0.876]
SASRec epoch 8/8:  36%|███▌      | 541/1500 [00:17<00:32, 29.40it/s, loss=0.876]
SASRec epoch 8/8:  36%|███▋      | 545/1500 [00:17<00:32, 29.69it/s, loss=0.876]
SASRec epoch 8/8:  37%|███▋      | 549/1500 [00:17<00:31, 29.91it/s, loss=0.876]
SASRec epoch 8/8:  37%|███▋      | 550/1500 [00:17<00:31, 29.91it/s, loss=0.867]
SASRec epoch 8/8:  37%|███▋      | 552/1500 [00:17<00:31, 29.82it/s, loss=0.867]
SASRec epoch 8/8:  37%|███▋      | 556/1500 [00:17<00:31, 29.88it/s, loss=0.867]
SASRec epoch 8/8:  37%|███▋      | 559/1500 [00:17<00:31, 29.63it/s, loss=0.867]
SASRec epoch 8/8:  38%|███▊      | 563/1500 [00:18<00:31, 29.99it/s, loss=0.867]
SASRec epoch 8/8:  38%|███▊      | 567/1500 [00:18<00:30, 30.30it/s, loss=0.867]
SASRec epoch 8/8:  38%|███▊      | 571/1500 [00:18<00:30, 30.56it/s, loss=0.867]
SASRec epoch 8/8:  38%|███▊      | 575/1500 [00:18<00:30, 30.71it/s, loss=0.867]
SASRec epoch 8/8:  39%|███▊      | 579/1500 [00:18<00:31, 29.41it/s, loss=0.867]
SASRec epoch 8/8:  39%|███▉      | 582/1500 [00:18<00:31, 29.47it/s, loss=0.867]
SASRec epoch 8/8:  39%|███▉      | 585/1500 [00:18<00:31, 29.14it/s, loss=0.867]
SASRec epoch 8/8:  39%|███▉      | 588/1500 [00:18<00:31, 28.95it/s, loss=0.867]
SASRec epoch 8/8:  39%|███▉      | 591/1500 [00:18<00:31, 28.55it/s, loss=0.867]
SASRec epoch 8/8:  40%|███▉      | 594/1500 [00:19<00:31, 28.69it/s, loss=0.867]
SASRec epoch 8/8:  40%|███▉      | 597/1500 [00:19<00:31, 28.44it/s, loss=0.867]
SASRec epoch 8/8:  40%|████      | 600/1500 [00:19<00:31, 28.44it/s, loss=0.851]
SASRec epoch 8/8:  40%|████      | 601/1500 [00:19<00:31, 28.73it/s, loss=0.851]
SASRec epoch 8/8:  40%|████      | 605/1500 [00:19<00:30, 29.58it/s, loss=0.851]
SASRec epoch 8/8:  41%|████      | 609/1500 [00:19<00:29, 29.85it/s, loss=0.851]
SASRec epoch 8/8:  41%|████      | 613/1500 [00:19<00:29, 30.01it/s, loss=0.851]
SASRec epoch 8/8:  41%|████      | 616/1500 [00:19<00:29, 29.92it/s, loss=0.851]
SASRec epoch 8/8:  41%|████▏     | 619/1500 [00:19<00:29, 29.48it/s, loss=0.851]
SASRec epoch 8/8:  41%|████▏     | 622/1500 [00:20<00:31, 27.90it/s, loss=0.851]
SASRec epoch 8/8:  42%|████▏     | 625/1500 [00:20<00:31, 27.88it/s, loss=0.851]
SASRec epoch 8/8:  42%|████▏     | 628/1500 [00:20<00:32, 26.73it/s, loss=0.851]
SASRec epoch 8/8:  42%|████▏     | 631/1500 [00:20<00:32, 26.91it/s, loss=0.851]
SASRec epoch 8/8:  42%|████▏     | 635/1500 [00:20<00:30, 28.14it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 638/1500 [00:20<00:30, 28.33it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 641/1500 [00:20<00:30, 28.63it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 644/1500 [00:20<00:30, 28.43it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 647/1500 [00:20<00:29, 28.68it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 650/1500 [00:21<00:30, 27.61it/s, loss=0.851]
SASRec epoch 8/8:  43%|████▎     | 650/1500 [00:21<00:30, 27.61it/s, loss=0.854]
SASRec epoch 8/8:  44%|████▎     | 653/1500 [00:21<00:31, 27.13it/s, loss=0.854]
SASRec epoch 8/8:  44%|████▎     | 656/1500 [00:21<00:30, 27.48it/s, loss=0.854]
SASRec epoch 8/8:  44%|████▍     | 659/1500 [00:21<00:30, 28.03it/s, loss=0.854]
SASRec epoch 8/8:  44%|████▍     | 663/1500 [00:21<00:28, 29.43it/s, loss=0.854]
SASRec epoch 8/8:  44%|████▍     | 667/1500 [00:21<00:27, 30.54it/s, loss=0.854]
SASRec epoch 8/8:  45%|████▍     | 671/1500 [00:21<00:26, 30.80it/s, loss=0.854]
SASRec epoch 8/8:  45%|████▌     | 675/1500 [00:21<00:26, 31.18it/s, loss=0.854]
SASRec epoch 8/8:  45%|████▌     | 679/1500 [00:22<00:26, 31.49it/s, loss=0.854]
SASRec epoch 8/8:  46%|████▌     | 683/1500 [00:22<00:25, 31.90it/s, loss=0.854]
SASRec epoch 8/8:  46%|████▌     | 687/1500 [00:22<00:25, 31.70it/s, loss=0.854]
SASRec epoch 8/8:  46%|████▌     | 691/1500 [00:22<00:25, 31.78it/s, loss=0.854]
SASRec epoch 8/8:  46%|████▋     | 695/1500 [00:22<00:24, 32.23it/s, loss=0.854]
SASRec epoch 8/8:  47%|████▋     | 699/1500 [00:22<00:24, 32.21it/s, loss=0.854]
SASRec epoch 8/8:  47%|████▋     | 700/1500 [00:22<00:24, 32.21it/s, loss=0.869]
SASRec epoch 8/8:  47%|████▋     | 703/1500 [00:22<00:25, 31.70it/s, loss=0.869]
SASRec epoch 8/8:  47%|████▋     | 707/1500 [00:22<00:25, 31.61it/s, loss=0.869]
SASRec epoch 8/8:  47%|████▋     | 711/1500 [00:23<00:24, 31.87it/s, loss=0.869]
SASRec epoch 8/8:  48%|████▊     | 715/1500 [00:23<00:24, 31.94it/s, loss=0.869]
SASRec epoch 8/8:  48%|████▊     | 719/1500 [00:23<00:24, 31.39it/s, loss=0.869]
SASRec epoch 8/8:  48%|████▊     | 723/1500 [00:23<00:24, 31.54it/s, loss=0.869]
SASRec epoch 8/8:  48%|████▊     | 727/1500 [00:23<00:24, 31.71it/s, loss=0.869]
SASRec epoch 8/8:  49%|████▊     | 731/1500 [00:23<00:24, 31.62it/s, loss=0.869]
SASRec epoch 8/8:  49%|████▉     | 735/1500 [00:23<00:23, 31.94it/s, loss=0.869]
SASRec epoch 8/8:  49%|████▉     | 739/1500 [00:23<00:23, 31.99it/s, loss=0.869]
SASRec epoch 8/8:  50%|████▉     | 743/1500 [00:24<00:23, 32.13it/s, loss=0.869]
SASRec epoch 8/8:  50%|████▉     | 747/1500 [00:24<00:23, 32.18it/s, loss=0.869]
SASRec epoch 8/8:  50%|█████     | 750/1500 [00:24<00:23, 32.18it/s, loss=0.857]
SASRec epoch 8/8:  50%|█████     | 751/1500 [00:24<00:24, 30.90it/s, loss=0.857]
SASRec epoch 8/8:  50%|█████     | 755/1500 [00:24<00:24, 30.81it/s, loss=0.857]
SASRec epoch 8/8:  51%|█████     | 759/1500 [00:24<00:23, 31.25it/s, loss=0.857]
SASRec epoch 8/8:  51%|█████     | 763/1500 [00:24<00:23, 31.50it/s, loss=0.857]
SASRec epoch 8/8:  51%|█████     | 767/1500 [00:24<00:23, 31.73it/s, loss=0.857]
SASRec epoch 8/8:  51%|█████▏    | 771/1500 [00:24<00:22, 31.90it/s, loss=0.857]
SASRec epoch 8/8:  52%|█████▏    | 775/1500 [00:25<00:22, 31.92it/s, loss=0.857]
SASRec epoch 8/8:  52%|█████▏    | 779/1500 [00:25<00:22, 32.05it/s, loss=0.857]
SASRec epoch 8/8:  52%|█████▏    | 783/1500 [00:25<00:22, 32.17it/s, loss=0.857]
SASRec epoch 8/8:  52%|█████▏    | 787/1500 [00:25<00:22, 31.49it/s, loss=0.857]
SASRec epoch 8/8:  53%|█████▎    | 791/1500 [00:25<00:22, 31.78it/s, loss=0.857]
SASRec epoch 8/8:  53%|█████▎    | 795/1500 [00:25<00:22, 31.75it/s, loss=0.857]
SASRec epoch 8/8:  53%|█████▎    | 799/1500 [00:25<00:21, 32.04it/s, loss=0.857]
SASRec epoch 8/8:  53%|█████▎    | 800/1500 [00:25<00:21, 32.04it/s, loss=0.863]
SASRec epoch 8/8:  54%|█████▎    | 803/1500 [00:25<00:22, 31.32it/s, loss=0.863]
SASRec epoch 8/8:  54%|█████▍    | 807/1500 [00:26<00:21, 31.55it/s, loss=0.863]
SASRec epoch 8/8:  54%|█████▍    | 811/1500 [00:26<00:21, 31.82it/s, loss=0.863]
SASRec epoch 8/8:  54%|█████▍    | 815/1500 [00:26<00:21, 32.04it/s, loss=0.863]
SASRec epoch 8/8:  55%|█████▍    | 819/1500 [00:26<00:21, 31.37it/s, loss=0.863]
SASRec epoch 8/8:  55%|█████▍    | 823/1500 [00:26<00:21, 31.59it/s, loss=0.863]
SASRec epoch 8/8:  55%|█████▌    | 827/1500 [00:26<00:21, 31.87it/s, loss=0.863]
SASRec epoch 8/8:  55%|█████▌    | 831/1500 [00:26<00:20, 31.87it/s, loss=0.863]
SASRec epoch 8/8:  56%|█████▌    | 835/1500 [00:26<00:20, 32.25it/s, loss=0.863]
SASRec epoch 8/8:  56%|█████▌    | 839/1500 [00:27<00:20, 32.18it/s, loss=0.863]
SASRec epoch 8/8:  56%|█████▌    | 843/1500 [00:27<00:20, 32.34it/s, loss=0.863]
SASRec epoch 8/8:  56%|█████▋    | 847/1500 [00:27<00:20, 32.43it/s, loss=0.863]
SASRec epoch 8/8:  57%|█████▋    | 850/1500 [00:27<00:20, 32.43it/s, loss=0.855]
SASRec epoch 8/8:  57%|█████▋    | 851/1500 [00:27<00:20, 31.38it/s, loss=0.855]
SASRec epoch 8/8:  57%|█████▋    | 855/1500 [00:27<00:20, 31.20it/s, loss=0.855]
SASRec epoch 8/8:  57%|█████▋    | 859/1500 [00:27<00:20, 31.21it/s, loss=0.855]
SASRec epoch 8/8:  58%|█████▊    | 863/1500 [00:27<00:20, 31.48it/s, loss=0.855]
SASRec epoch 8/8:  58%|█████▊    | 867/1500 [00:27<00:20, 31.59it/s, loss=0.855]
SASRec epoch 8/8:  58%|█████▊    | 871/1500 [00:28<00:19, 31.57it/s, loss=0.855]
SASRec epoch 8/8:  58%|█████▊    | 875/1500 [00:28<00:19, 31.82it/s, loss=0.855]

[SASRec] epoch 8/8 loss=0.8586

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0005 | MAP@10: 0.0003
K=20 | Recall@20: 0.0015 | NDCG@20: 0.0006 | MAP@20: 0.0003
K=50 | Recall@50: 0.0034 | NDCG@50: 0.0009 | MAP@50: 0.0003
K=100 | Recall@100: 0.0063 | NDCG@100: 0.0014 | MAP@100: 0.0004

[SASRec(VAL)/WARM] n=25095

SASRec hyperparam search:  50%|█████     | 2/4 [10:49<11:11, 335.81s/it]/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0014 | NDCG@10: 0.0005 | MAP@10: 0.0003
K=20 | Recall@20: 0.0016 | NDCG@20: 0.0005 | MAP@20: 0.0003
K=50 | Recall@50: 0.0037 | NDCG@50: 0.0010 | MAP@50: 0.0003
K=100 | Recall@100: 0.0069 | NDCG@100: 0.0015 | MAP@100: 0.0004

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target score: split=ALL K=50 Recall=0.003441

=== TRY: {'max_len': 100, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.0008} ===

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 1/8:   0%|          | 3/1500 [00:00<01:11, 20.99it/s]
SASRec epoch 1/8:   0%|          | 6/1500 [00:00<01:08, 21.67it/s]
SASRec epoch 1/8:   1%|          | 9/1500 [00:00<01:01, 24.26it/s]
SASRec epoch 1/8:   1%|          | 12/1500 [00:00<00:56, 26.14it/s]
SASRec epoch 1/8:   1%|          | 15/1500 [00:00<00:55, 26.88it/s]
SASRec epoch 1/8:   1%|          | 18/1500 [00:00<00:53, 27.50it/s]
SASRec epoch 1/8:   1%|▏         | 22/1500 [00:00<00:51, 28.91it/s]
SASRec epoch 1/8:   2%|▏         | 26/1500 [00:00<00:49, 29.61it/s]
SASRec epoch 1/8:   2%|▏         | 29/1500 [00:01<00:49, 29.64it/s]
SASRec epoch 1/8:   2%|▏         | 32/1500 [00:01<00:49, 29.67it/s]
SASRec epoch 1/8:   2%|▏         | 35/1500 [00:01<00:49, 29.58it/s]
SASRec epoch 1/8:   3%|▎         | 38/1500 [00:01<00:49, 29.53it/s]
SASRec epoch 1/8:   3%|▎         | 42/1500 [00:01<00:48, 29.96it/s]
SASRec epoch 1/8:   3%|▎         | 45/1500 [00:01<00:49, 29.51it/s]
SASRec epoch 1/8:   3%|▎         | 49/1500 [00:01<00:48, 29.99it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:01<00:48, 29.99it/s, loss=7.14]
SASRec epoch 1/8:   3%|▎         | 52/1500 [00:01<00:49, 29.18it/s, loss=7.14]
SASRec epoch 1/8:   4%|▎         | 56/1500 [00:01<00:48, 29.88it/s, loss=7.14]
SASRec epoch 1/8:   4%|▍         | 59/1500 [00:02<00:48, 29.81it/s, loss=7.14]
SASRec epoch 1/8:   4%|▍         | 62/1500 [00:02<00:48, 29.79it/s, loss=7.14]
SASRec epoch 1/8:   4%|▍         | 65/1500 [00:02<00:48, 29.65it/s, loss=7.14]
SASRec epoch 1/8:   5%|▍         | 68/1500 [00:02<00:48, 29.61it/s, loss=7.14]
SASRec epoch 1/8:   5%|▍         | 72/1500 [00:02<00:47, 29.95it/s, loss=7.14]
SASRec epoch 1/8:   5%|▌         | 75/1500 [00:02<00:48, 29.57it/s, loss=7.14]
SASRec epoch 1/8:   5%|▌         | 78/1500 [00:02<00:48, 29.55it/s, loss=7.14]
SASRec epoch 1/8:   5%|▌         | 81/1500 [00:02<00:47, 29.60it/s, loss=7.14]
SASRec epoch 1/8:   6%|▌         | 84/1500 [00:02<00:47, 29.68it/s, loss=7.14]
SASRec epoch 1/8:   6%|▌         | 88/1500 [00:03<00:47, 30.01it/s, loss=7.14]
SASRec epoch 1/8:   6%|▌         | 91/1500 [00:03<00:47, 29.85it/s, loss=7.14]
SASRec epoch 1/8:   6%|▋         | 95/1500 [00:03<00:46, 30.11it/s, loss=7.14]
SASRec epoch 1/8:   7%|▋         | 99/1500 [00:03<00:46, 30.37it/s, loss=7.14]
SASRec epoch 1/8:   7%|▋         | 100/1500 [00:03<00:46, 30.37it/s, loss=5.38]
SASRec epoch 1/8:   7%|▋         | 103/1500 [00:03<00:46, 29.79it/s, loss=5.38]
SASRec epoch 1/8:   7%|▋         | 106/1500 [00:03<00:47, 29.48it/s, loss=5.38]
SASRec epoch 1/8:   7%|▋         | 109/1500 [00:03<00:47, 29.48it/s, loss=5.38]
SASRec epoch 1/8:   8%|▊         | 113/1500 [00:03<00:46, 30.03it/s, loss=5.38]
SASRec epoch 1/8:   8%|▊         | 116/1500 [00:03<00:46, 29.84it/s, loss=5.38]
SASRec epoch 1/8:   8%|▊         | 120/1500 [00:04<00:45, 30.10it/s, loss=5.38]
SASRec epoch 1/8:   8%|▊         | 124/1500 [00:04<00:45, 30.02it/s, loss=5.38]
SASRec epoch 1/8:   9%|▊         | 128/1500 [00:04<00:45, 30.28it/s, loss=5.38]
SASRec epoch 1/8:   9%|▉         | 132/1500 [00:04<00:45, 30.16it/s, loss=5.38]
SASRec epoch 1/8:   9%|▉         | 136/1500 [00:04<00:45, 30.19it/s, loss=5.38]
SASRec epoch 1/8:   9%|▉         | 140/1500 [00:04<00:46, 29.55it/s, loss=5.38]
SASRec epoch 1/8:  10%|▉         | 144/1500 [00:04<00:45, 29.88it/s, loss=5.38]
SASRec epoch 1/8:  10%|▉         | 148/1500 [00:05<00:44, 30.14it/s, loss=5.38]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:05<00:44, 30.14it/s, loss=4.25]
SASRec epoch 1/8:  10%|█         | 152/1500 [00:05<00:45, 29.34it/s, loss=4.25]
SASRec epoch 1/8:  10%|█         | 155/1500 [00:05<00:45, 29.45it/s, loss=4.25]
SASRec epoch 1/8:  11%|█         | 158/1500 [00:05<00:45, 29.38it/s, loss=4.25]
SASRec epoch 1/8:  11%|█         | 161/1500 [00:05<00:45, 29.46it/s, loss=4.25]
SASRec epoch 1/8:  11%|█         | 164/1500 [00:05<00:45, 29.49it/s, loss=4.25]
SASRec epoch 1/8:  11%|█         | 167/1500 [00:05<00:45, 29.46it/s, loss=4.25]
SASRec epoch 1/8:  11%|█▏        | 170/1500 [00:05<00:45, 29.06it/s, loss=4.25]
SASRec epoch 1/8:  12%|█▏        | 174/1500 [00:05<00:44, 29.73it/s, loss=4.25]
SASRec epoch 1/8:  12%|█▏        | 177/1500 [00:06<00:44, 29.79it/s, loss=4.25]
SASRec epoch 1/8:  12%|█▏        | 181/1500 [00:06<00:43, 30.10it/s, loss=4.25]
SASRec epoch 1/8:  12%|█▏        | 185/1500 [00:06<00:43, 30.01it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 188/1500 [00:06<00:43, 29.89it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 191/1500 [00:06<00:45, 28.95it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 194/1500 [00:06<00:46, 27.79it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 197/1500 [00:06<00:47, 27.20it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:06<00:49, 26.53it/s, loss=4.25]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:06<00:49, 26.53it/s, loss=3.3]
SASRec epoch 1/8:  14%|█▎        | 203/1500 [00:06<00:50, 25.71it/s, loss=3.3]
SASRec epoch 1/8:  14%|█▎        | 206/1500 [00:07<00:51, 25.21it/s, loss=3.3]
SASRec epoch 1/8:  14%|█▍        | 209/1500 [00:07<00:50, 25.80it/s, loss=3.3]
SASRec epoch 1/8:  14%|█▍        | 212/1500 [00:07<00:48, 26.46it/s, loss=3.3]
SASRec epoch 1/8:  14%|█▍        | 215/1500 [00:07<00:47, 27.06it/s, loss=3.3]
SASRec epoch 1/8:  15%|█▍        | 218/1500 [00:07<00:46, 27.44it/s, loss=3.3]
SASRec epoch 1/8:  15%|█▍        | 221/1500 [00:07<00:46, 27.74it/s, loss=3.3]
SASRec epoch 1/8:  15%|█▍        | 224/1500 [00:07<00:45, 28.01it/s, loss=3.3]
SASRec epoch 1/8:  15%|█▌        | 227/1500 [00:07<00:44, 28.32it/s, loss=3.3]
SASRec epoch 1/8:  15%|█▌        | 230/1500 [00:07<00:46, 27.53it/s, loss=3.3]
SASRec epoch 1/8:  16%|█▌        | 233/1500 [00:08<00:45, 27.97it/s, loss=3.3]
SASRec epoch 1/8:  16%|█▌        | 236/1500 [00:08<00:44, 28.13it/s, loss=3.3]
SASRec epoch 1/8:  16%|█▌        | 239/1500 [00:08<00:45, 27.74it/s, loss=3.3]
SASRec epoch 1/8:  16%|█▌        | 242/1500 [00:08<00:45, 27.35it/s, loss=3.3]
SASRec epoch 1/8:  16%|█▋        | 245/1500 [00:08<00:47, 26.69it/s, loss=3.3]
SASRec epoch 1/8:  17%|█▋        | 248/1500 [00:08<00:46, 27.22it/s, loss=3.3]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:08<00:45, 27.22it/s, loss=2.73]
SASRec epoch 1/8:  17%|█▋        | 251/1500 [00:08<00:45, 27.24it/s, loss=2.73]
SASRec epoch 1/8:  17%|█▋        | 254/1500 [00:08<00:45, 27.15it/s, loss=2.73]
SASRec epoch 1/8:  17%|█▋        | 257/1500 [00:08<00:47, 26.32it/s, loss=2.73]
SASRec epoch 1/8:  17%|█▋        | 260/1500 [00:09<00:47, 26.19it/s, loss=2.73]
SASRec epoch 1/8:  18%|█▊        | 263/1500 [00:09<00:46, 26.86it/s, loss=2.73]
SASRec epoch 1/8:  18%|█▊        | 266/1500 [00:09<00:45, 27.21it/s, loss=2.73]
SASRec epoch 1/8:  18%|█▊        | 269/1500 [00:09<00:44, 27.58it/s, loss=2.73]
SASRec epoch 1/8:  18%|█▊        | 272/1500 [00:09<00:44, 27.88it/s, loss=2.73]
SASRec epoch 1/8:  18%|█▊        | 275/1500 [00:09<00:43, 27.99it/s, loss=2.73]
SASRec epoch 1/8:  19%|█▊        | 278/1500 [00:09<00:47, 25.85it/s, loss=2.73]
SASRec epoch 1/8:  19%|█▊        | 281/1500 [00:09<00:45, 26.69it/s, loss=2.73]
SASRec epoch 1/8:  19%|█▉        | 284/1500 [00:09<00:44, 27.33it/s, loss=2.73]
SASRec epoch 1/8:  19%|█▉        | 287/1500 [00:10<00:43, 27.63it/s, loss=2.73]
SASRec epoch 1/8:  19%|█▉        | 290/1500 [00:10<00:44, 27.50it/s, loss=2.73]
SASRec epoch 1/8:  20%|█▉        | 293/1500 [00:10<00:43, 27.59it/s, loss=2.73]
SASRec epoch 1/8:  20%|█▉        | 296/1500 [00:10<00:43, 27.53it/s, loss=2.73]
SASRec epoch 1/8:  20%|█▉        | 299/1500 [00:10<00:44, 26.80it/s, loss=2.73]
SASRec epoch 1/8:  20%|██        | 300/1500 [00:10<00:44, 26.80it/s, loss=2.5]
SASRec epoch 1/8:  20%|██        | 302/1500 [00:10<00:45, 26.34it/s, loss=2.5]
SASRec epoch 1/8:  20%|██        | 305/1500 [00:10<00:45, 26.22it/s, loss=2.5]
SASRec epoch 1/8:  21%|██        | 308/1500 [00:10<00:45, 26.17it/s, loss=2.5]
SASRec epoch 1/8:  21%|██        | 311/1500 [00:10<00:46, 25.50it/s, loss=2.5]
SASRec epoch 1/8:  21%|██        | 314/1500 [00:11<00:47, 24.86it/s, loss=2.5]
SASRec epoch 1/8:  21%|██        | 317/1500 [00:11<00:47, 25.08it/s, loss=2.5]
SASRec epoch 1/8:  21%|██▏       | 320/1500 [00:11<00:47, 24.62it/s, loss=2.5]
SASRec epoch 1/8:  22%|██▏       | 323/1500 [00:11<00:47, 24.91it/s, loss=2.5]
SASRec epoch 1/8:  22%|██▏       | 326/1500 [00:11<00:46, 25.24it/s, loss=2.5]
SASRec epoch 1/8:  22%|██▏       | 329/1500 [00:11<00:47, 24.70it/s, loss=2.5]
SASRec epoch 1/8:  22%|██▏       | 332/1500 [00:11<00:45, 25.96it/s, loss=2.5]
SASRec epoch 1/8:  22%|██▏       | 336/1500 [00:11<00:42, 27.65it/s, loss=2.5]
SASRec epoch 1/8:  23%|██▎       | 339/1500 [00:12<00:41, 28.22it/s, loss=2.5]
SASRec epoch 1/8:  23%|██▎       | 342/1500 [00:12<00:40, 28.45it/s, loss=2.5]
SASRec epoch 1/8:  23%|██▎       | 345/1500 [00:12<00:40, 28.86it/s, loss=2.5]
SASRec epoch 1/8:  23%|██▎       | 348/1500 [00:12<00:40, 28.49it/s, loss=2.5]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:12<00:40, 28.49it/s, loss=2.31]
SASRec epoch 1/8:  23%|██▎       | 351/1500 [00:12<00:40, 28.24it/s, loss=2.31]
SASRec epoch 1/8:  24%|██▎       | 354/1500 [00:12<00:39, 28.73it/s, loss=2.31]
SASRec epoch 1/8:  24%|██▍       | 357/1500 [00:12<00:39, 28.79it/s, loss=2.31]
SASRec epoch 1/8:  24%|██▍       | 360/1500 [00:12<00:39, 28.95it/s, loss=2.31]
SASRec epoch 1/8:  24%|██▍       | 363/1500 [00:12<00:39, 29.12it/s, loss=2.31]
SASRec epoch 1/8:  24%|██▍       | 367/1500 [00:13<00:38, 29.68it/s, loss=2.31]
SASRec epoch 1/8:  25%|██▍       | 370/1500 [00:13<00:38, 29.48it/s, loss=2.31]
SASRec epoch 1/8:  25%|██▍       | 373/1500 [00:13<00:38, 29.59it/s, loss=2.31]
SASRec epoch 1/8:  25%|██▌       | 376/1500 [00:13<00:38, 29.58it/s, loss=2.31]
SASRec epoch 1/8:  25%|██▌       | 379/1500 [00:13<00:39, 28.69it/s, loss=2.31]
SASRec epoch 1/8:  25%|██▌       | 382/1500 [00:13<00:38, 29.03it/s, loss=2.31]
SASRec epoch 1/8:  26%|██▌       | 385/1500 [00:13<00:38, 29.30it/s, loss=2.31]
SASRec epoch 1/8:  26%|██▌       | 388/1500 [00:13<00:37, 29.43it/s, loss=2.31]
SASRec epoch 1/8:  26%|██▌       | 391/1500 [00:13<00:37, 29.44it/s, loss=2.31]
SASRec epoch 1/8:  26%|██▋       | 394/1500 [00:13<00:37, 29.46it/s, loss=2.31]
SASRec epoch 1/8:  27%|██▋       | 398/1500 [00:14<00:36, 29.90it/s, loss=2.31]
SASRec epoch 1/8:  27%|██▋       | 400/1500 [00:14<00:36, 29.90it/s, loss=2.2]
SASRec epoch 1/8:  27%|██▋       | 401/1500 [00:14<00:37, 28.98it/s, loss=2.2]
SASRec epoch 1/8:  27%|██▋       | 404/1500 [00:14<00:37, 29.04it/s, loss=2.2]
SASRec epoch 1/8:  27%|██▋       | 407/1500 [00:14<00:37, 29.00it/s, loss=2.2]
SASRec epoch 1/8:  27%|██▋       | 410/1500 [00:14<00:38, 28.30it/s, loss=2.2]
SASRec epoch 1/8:  28%|██▊       | 413/1500 [00:14<00:38, 28.50it/s, loss=2.2]
SASRec epoch 1/8:  28%|██▊       | 417/1500 [00:14<00:37, 29.24it/s, loss=2.2]
SASRec epoch 1/8:  28%|██▊       | 420/1500 [00:14<00:36, 29.23it/s, loss=2.2]
SASRec epoch 1/8:  28%|██▊       | 424/1500 [00:14<00:36, 29.71it/s, loss=2.2]
SASRec epoch 1/8:  28%|██▊       | 427/1500 [00:15<00:36, 29.52it/s, loss=2.2]
SASRec epoch 1/8:  29%|██▊       | 431/1500 [00:15<00:35, 29.89it/s, loss=2.2]
SASRec epoch 1/8:  29%|██▉       | 434/1500 [00:15<00:35, 29.75it/s, loss=2.2]
SASRec epoch 1/8:  29%|██▉       | 437/1500 [00:15<00:35, 29.69it/s, loss=2.2]
SASRec epoch 1/8:  29%|██▉       | 440/1500 [00:15<00:36, 29.24it/s, loss=2.2]
SASRec epoch 1/8:  30%|██▉       | 443/1500 [00:15<00:36, 29.28it/s, loss=2.2]
SASRec epoch 1/8:  30%|██▉       | 446/1500 [00:15<00:35, 29.31it/s, loss=2.2]
SASRec epoch 1/8:  30%|██▉       | 449/1500 [00:15<00:35, 29.35it/s, loss=2.2]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:15<00:35, 29.35it/s, loss=2.13]
SASRec epoch 1/8:  30%|███       | 452/1500 [00:15<00:36, 28.62it/s, loss=2.13]
SASRec epoch 1/8:  30%|███       | 455/1500 [00:16<00:36, 29.00it/s, loss=2.13]
SASRec epoch 1/8:  31%|███       | 458/1500 [00:16<00:35, 29.10it/s, loss=2.13]
SASRec epoch 1/8:  31%|███       | 461/1500 [00:16<00:36, 28.79it/s, loss=2.13]
SASRec epoch 1/8:  31%|███       | 465/1500 [00:16<00:35, 29.48it/s, loss=2.13]
SASRec epoch 1/8:  31%|███       | 468/1500 [00:16<00:35, 29.48it/s, loss=2.13]
SASRec epoch 1/8:  31%|███▏      | 471/1500 [00:16<00:36, 28.53it/s, loss=2.13]
SASRec epoch 1/8:  32%|███▏      | 474/1500 [00:16<00:35, 28.93it/s, loss=2.13]
SASRec epoch 1/8:  32%|███▏      | 477/1500 [00:16<00:35, 29.05it/s, loss=2.13]
SASRec epoch 1/8:  32%|███▏      | 480/1500 [00:16<00:35, 29.12it/s, loss=2.13]
SASRec epoch 1/8:  32%|███▏      | 483/1500 [00:16<00:34, 29.25it/s, loss=2.13]
SASRec epoch 1/8:  32%|███▏      | 486/1500 [00:17<00:34, 29.26it/s, loss=2.13]
SASRec epoch 1/8:  33%|███▎      | 489/1500 [00:17<00:35, 28.86it/s, loss=2.13]
SASRec epoch 1/8:  33%|███▎      | 492/1500 [00:17<00:34, 29.16it/s, loss=2.13]
SASRec epoch 1/8:  33%|███▎      | 495/1500 [00:17<00:34, 29.34it/s, loss=2.13]
SASRec epoch 1/8:  33%|███▎      | 498/1500 [00:17<00:34, 29.47it/s, loss=2.13]
SASRec epoch 1/8:  33%|███▎      | 500/1500 [00:17<00:33, 29.47it/s, loss=2.06]
SASRec epoch 1/8:  33%|███▎      | 501/1500 [00:17<00:35, 28.28it/s, loss=2.06]
SASRec epoch 1/8:  34%|███▎      | 504/1500 [00:17<00:34, 28.73it/s, loss=2.06]
SASRec epoch 1/8:  34%|███▍      | 507/1500 [00:17<00:34, 28.98it/s, loss=2.06]
SASRec epoch 1/8:  34%|███▍      | 510/1500 [00:17<00:33, 29.16it/s, loss=2.06]
SASRec epoch 1/8:  34%|███▍      | 514/1500 [00:18<00:33, 29.74it/s, loss=2.06]
SASRec epoch 1/8:  34%|███▍      | 517/1500 [00:18<00:33, 29.72it/s, loss=2.06]
SASRec epoch 1/8:  35%|███▍      | 520/1500 [00:18<00:33, 29.51it/s, loss=2.06]
SASRec epoch 1/8:  35%|███▍      | 523/1500 [00:18<00:33, 29.54it/s, loss=2.06]
SASRec epoch 1/8:  35%|███▌      | 526/1500 [00:18<00:33, 29.35it/s, loss=2.06]
SASRec epoch 1/8:  35%|███▌      | 529/1500 [00:18<00:32, 29.53it/s, loss=2.06]
SASRec epoch 1/8:  35%|███▌      | 532/1500 [00:18<00:33, 29.03it/s, loss=2.06]
SASRec epoch 1/8:  36%|███▌      | 536/1500 [00:18<00:32, 29.65it/s, loss=2.06]
SASRec epoch 1/8:  36%|███▌      | 539/1500 [00:18<00:32, 29.61it/s, loss=2.06]
SASRec epoch 1/8:  36%|███▌      | 543/1500 [00:19<00:31, 30.04it/s, loss=2.06]
SASRec epoch 1/8:  36%|███▋      | 546/1500 [00:19<00:32, 29.76it/s, loss=2.06]
SASRec epoch 1/8:  37%|███▋      | 550/1500 [00:19<00:31, 30.03it/s, loss=2.06]
SASRec epoch 1/8:  37%|███▋      | 550/1500 [00:19<00:31, 30.03it/s, loss=2]
SASRec epoch 1/8:  37%|███▋      | 553/1500 [00:19<00:32, 29.16it/s, loss=2]
SASRec epoch 1/8:  37%|███▋      | 556/1500 [00:19<00:32, 29.19it/s, loss=2]
SASRec epoch 1/8:  37%|███▋      | 559/1500 [00:19<00:32, 29.34it/s, loss=2]
SASRec epoch 1/8:  37%|███▋      | 562/1500 [00:19<00:32, 28.92it/s, loss=2]
SASRec epoch 1/8:  38%|███▊      | 566/1500 [00:19<00:31, 29.53it/s, loss=2]
SASRec epoch 1/8:  38%|███▊      | 570/1500 [00:19<00:31, 29.99it/s, loss=2]
SASRec epoch 1/8:  38%|███▊      | 573/1500 [00:20<00:31, 29.85it/s, loss=2]
SASRec epoch 1/8:  38%|███▊      | 577/1500 [00:20<00:30, 30.19it/s, loss=2]
SASRec epoch 1/8:  39%|███▊      | 581/1500 [00:20<00:30, 30.06it/s, loss=2]
SASRec epoch 1/8:  39%|███▉      | 585/1500 [00:20<00:30, 30.11it/s, loss=2]
SASRec epoch 1/8:  39%|███▉      | 589/1500 [00:20<00:30, 30.02it/s, loss=2]
SASRec epoch 1/8:  39%|███▉      | 592/1500 [00:20<00:30, 29.83it/s, loss=2]
SASRec epoch 1/8:  40%|███▉      | 595/1500 [00:20<00:31, 28.51it/s, loss=2]
SASRec epoch 1/8:  40%|███▉      | 598/1500 [00:20<00:31, 28.86it/s, loss=2]
SASRec epoch 1/8:  40%|████      | 600/1500 [00:20<00:31, 28.86it/s, loss=1.92]
SASRec epoch 1/8:  40%|████      | 601/1500 [00:20<00:31, 28.41it/s, loss=1.92]
SASRec epoch 1/8:  40%|████      | 604/1500 [00:21<00:31, 28.74it/s, loss=1.92]
SASRec epoch 1/8:  40%|████      | 607/1500 [00:21<00:30, 28.93it/s, loss=1.92]
SASRec epoch 1/8:  41%|████      | 610/1500 [00:21<00:30, 28.95it/s, loss=1.92]
SASRec epoch 1/8:  41%|████      | 613/1500 [00:21<00:30, 29.03it/s, loss=1.92]
SASRec epoch 1/8:  41%|████      | 616/1500 [00:21<00:30, 29.19it/s, loss=1.92]
SASRec epoch 1/8:  41%|████▏     | 619/1500 [00:21<00:30, 29.06it/s, loss=1.92]
SASRec epoch 1/8:  41%|████▏     | 622/1500 [00:21<00:30, 29.22it/s, loss=1.92]
SASRec epoch 1/8:  42%|████▏     | 625/1500 [00:21<00:31, 27.71it/s, loss=1.92]
SASRec epoch 1/8:  42%|████▏     | 628/1500 [00:21<00:31, 27.38it/s, loss=1.92]
SASRec epoch 1/8:  42%|████▏     | 631/1500 [00:22<00:32, 26.58it/s, loss=1.92]
SASRec epoch 1/8:  42%|████▏     | 634/1500 [00:22<00:32, 26.74it/s, loss=1.92]
SASRec epoch 1/8:  42%|████▏     | 637/1500 [00:22<00:31, 27.10it/s, loss=1.92]
SASRec epoch 1/8:  43%|████▎     | 640/1500 [00:22<00:31, 27.49it/s, loss=1.92]
SASRec epoch 1/8:  43%|████▎     | 643/1500 [00:22<00:30, 27.87it/s, loss=1.92]
SASRec epoch 1/8:  43%|████▎     | 646/1500 [00:22<00:30, 28.09it/s, loss=1.92]
SASRec epoch 1/8:  43%|████▎     | 649/1500 [00:22<00:30, 28.30it/s, loss=1.92]
SASRec epoch 1/8:  43%|████▎     | 650/1500 [00:22<00:30, 28.30it/s, loss=1.87]
SASRec epoch 1/8:  43%|████▎     | 652/1500 [00:22<00:30, 27.97it/s, loss=1.87]
SASRec epoch 1/8:  44%|████▎     | 655/1500 [00:22<00:30, 27.42it/s, loss=1.87]
SASRec epoch 1/8:  44%|████▍     | 658/1500 [00:23<00:30, 27.74it/s, loss=1.87]
SASRec epoch 1/8:  44%|████▍     | 661/1500 [00:23<00:29, 28.16it/s, loss=1.87]
SASRec epoch 1/8:  44%|████▍     | 664/1500 [00:23<00:29, 28.57it/s, loss=1.87]
SASRec epoch 1/8:  44%|████▍     | 667/1500 [00:23<00:29, 28.64it/s, loss=1.87]
SASRec epoch 1/8:  45%|████▍     | 670/1500 [00:23<00:29, 28.59it/s, loss=1.87]
SASRec epoch 1/8:  45%|████▍     | 673/1500 [00:23<00:28, 28.78it/s, loss=1.87]
SASRec epoch 1/8:  45%|████▌     | 676/1500 [00:23<00:28, 28.90it/s, loss=1.87]
SASRec epoch 1/8:  45%|████▌     | 679/1500 [00:23<00:28, 28.93it/s, loss=1.87]
SASRec epoch 1/8:  45%|████▌     | 682/1500 [00:23<00:28, 28.89it/s, loss=1.87]
SASRec epoch 1/8:  46%|████▌     | 685/1500 [00:23<00:28, 28.52it/s, loss=1.87]
SASRec epoch 1/8:  46%|████▌     | 688/1500 [00:24<00:29, 27.83it/s, loss=1.87]
SASRec epoch 1/8:  46%|████▌     | 691/1500 [00:24<00:28, 27.96it/s, loss=1.87]
SASRec epoch 1/8:  46%|████▋     | 694/1500 [00:24<00:29, 27.76it/s, loss=1.87]
SASRec epoch 1/8:  46%|████▋     | 697/1500 [00:24<00:30, 26.35it/s, loss=1.87]
SASRec epoch 1/8:  47%|████▋     | 700/1500 [00:24<00:29, 27.13it/s, loss=1.87]
SASRec epoch 1/8:  47%|████▋     | 700/1500 [00:24<00:29, 27.13it/s, loss=1.83]
SASRec epoch 1/8:  47%|████▋     | 703/1500 [00:24<00:29, 27.26it/s, loss=1.83]
SASRec epoch 1/8:  47%|████▋     | 706/1500 [00:24<00:28, 27.64it/s, loss=1.83]
SASRec epoch 1/8:  47%|████▋     | 709/1500 [00:24<00:28, 27.92it/s, loss=1.83]
SASRec epoch 1/8:  47%|████▋     | 712/1500 [00:24<00:27, 28.16it/s, loss=1.83]
SASRec epoch 1/8:  48%|████▊     | 715/1500 [00:25<00:27, 28.32it/s, loss=1.83]
SASRec epoch 1/8:  48%|████▊     | 718/1500 [00:25<00:28, 27.65it/s, loss=1.83]
SASRec epoch 1/8:  48%|████▊     | 721/1500 [00:25<00:28, 27.58it/s, loss=1.83]
SASRec epoch 1/8:  48%|████▊     | 724/1500 [00:25<00:27, 27.85it/s, loss=1.83]
SASRec epoch 1/8:  48%|████▊     | 727/1500 [00:25<00:27, 27.77it/s, loss=1.83]
SASRec epoch 1/8:  49%|████▊     | 730/1500 [00:25<00:27, 27.99it/s, loss=1.83]
SASRec epoch 1/8:  49%|████▉     | 733/1500 [00:25<00:27, 28.17it/s, loss=1.83]
SASRec epoch 1/8:  49%|████▉     | 736/1500 [00:25<00:26, 28.33it/s, loss=1.83]
SASRec epoch 1/8:  49%|████▉     | 739/1500 [00:25<00:26, 28.41it/s, loss=1.83]
SASRec epoch 1/8:  49%|████▉     | 742/1500 [00:26<00:26, 28.43it/s, loss=1.83]
SASRec epoch 1/8:  50%|████▉     | 745/1500 [00:26<00:27, 27.63it/s, loss=1.83]
SASRec epoch 1/8:  50%|████▉     | 748/1500 [00:26<00:27, 27.05it/s, loss=1.83]
SASRec epoch 1/8:  50%|█████     | 750/1500 [00:26<00:27, 27.05it/s, loss=1.79]
SASRec epoch 1/8:  50%|█████     | 751/1500 [00:26<00:28, 26.38it/s, loss=1.79]

[SASRec] epoch 1/8 loss=2.2444

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 2/8:   0%|          | 3/1500 [00:00<00:51, 29.28it/s]
SASRec epoch 2/8:   0%|          | 6/1500 [00:00<00:52, 28.27it/s]
SASRec epoch 2/8:   1%|          | 9/1500 [00:00<00:52, 28.65it/s]
SASRec epoch 2/8:   1%|          | 13/1500 [00:00<00:50, 29.61it/s]
SASRec epoch 2/8:   1%|          | 16/1500 [00:00<00:50, 29.65it/s]
SASRec epoch 2/8:   1%|▏         | 19/1500 [00:00<00:50, 29.54it/s]
SASRec epoch 2/8:   1%|▏         | 22/1500 [00:00<00:49, 29.62it/s]
SASRec epoch 2/8:   2%|▏         | 26/1500 [00:00<00:49, 30.03it/s]
SASRec epoch 2/8:   2%|▏         | 29/1500 [00:00<00:51, 28.39it/s]
SASRec epoch 2/8:   2%|▏         | 32/1500 [00:01<00:52, 28.12it/s]
SASRec epoch 2/8:   2%|▏         | 35/1500 [00:01<00:51, 28.18it/s]
SASRec epoch 2/8:   3%|▎         | 38/1500 [00:01<00:53, 27.51it/s]
SASRec epoch 2/8:   3%|▎         | 41/1500 [00:01<00:53, 27.22it/s]
SASRec epoch 2/8:   3%|▎         | 44/1500 [00:01<00:54, 26.63it/s]
SASRec epoch 2/8:   3%|▎         | 47/1500 [00:01<00:55, 26.15it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:01<00:55, 26.35it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:01<00:55, 26.35it/s, loss=1.46]
SASRec epoch 2/8:   4%|▎         | 53/1500 [00:01<00:57, 25.31it/s, loss=1.46]
SASRec epoch 2/8:   4%|▎         | 56/1500 [00:02<00:55, 26.15it/s, loss=1.46]
SASRec epoch 2/8:   4%|▍         | 59/1500 [00:02<00:53, 26.92it/s, loss=1.46]
SASRec epoch 2/8:   4%|▍         | 62/1500 [00:02<00:52, 27.57it/s, loss=1.46]
SASRec epoch 2/8:   4%|▍         | 65/1500 [00:02<00:51, 27.93it/s, loss=1.46]
SASRec epoch 2/8:   5%|▍         | 68/1500 [00:02<00:51, 27.55it/s, loss=1.46]
SASRec epoch 2/8:   5%|▍         | 71/1500 [00:02<00:51, 27.86it/s, loss=1.46]
SASRec epoch 2/8:   5%|▍         | 74/1500 [00:02<00:50, 28.23it/s, loss=1.46]
SASRec epoch 2/8:   5%|▌         | 77/1500 [00:02<00:49, 28.61it/s, loss=1.46]
SASRec epoch 2/8:   5%|▌         | 80/1500 [00:02<00:49, 28.85it/s, loss=1.46]
SASRec epoch 2/8:   6%|▌         | 83/1500 [00:02<00:49, 28.89it/s, loss=1.46]
SASRec epoch 2/8:   6%|▌         | 86/1500 [00:03<00:49, 28.33it/s, loss=1.46]
SASRec epoch 2/8:   6%|▌         | 89/1500 [00:03<00:50, 28.22it/s, loss=1.46]
SASRec epoch 2/8:   6%|▌         | 92/1500 [00:03<00:49, 28.44it/s, loss=1.46]
SASRec epoch 2/8:   6%|▋         | 95/1500 [00:03<00:49, 28.54it/s, loss=1.46]
SASRec epoch 2/8:   7%|▋         | 98/1500 [00:03<00:49, 28.18it/s, loss=1.46]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:03<00:49, 28.18it/s, loss=1.45]
SASRec epoch 2/8:   7%|▋         | 101/1500 [00:03<00:51, 26.96it/s, loss=1.45]
SASRec epoch 2/8:   7%|▋         | 104/1500 [00:03<00:51, 26.87it/s, loss=1.45]
SASRec epoch 2/8:   7%|▋         | 107/1500 [00:03<00:50, 27.41it/s, loss=1.45]
SASRec epoch 2/8:   7%|▋         | 110/1500 [00:03<00:50, 27.55it/s, loss=1.45]
SASRec epoch 2/8:   8%|▊         | 113/1500 [00:04<00:49, 27.77it/s, loss=1.45]
SASRec epoch 2/8:   8%|▊         | 116/1500 [00:04<00:49, 27.76it/s, loss=1.45]
SASRec epoch 2/8:   8%|▊         | 119/1500 [00:04<00:49, 27.98it/s, loss=1.45]
SASRec epoch 2/8:   8%|▊         | 122/1500 [00:04<00:49, 27.96it/s, loss=1.45]
SASRec epoch 2/8:   8%|▊         | 125/1500 [00:04<00:49, 27.95it/s, loss=1.45]
SASRec epoch 2/8:   9%|▊         | 128/1500 [00:04<00:48, 28.25it/s, loss=1.45]
SASRec epoch 2/8:   9%|▊         | 131/1500 [00:04<00:49, 27.89it/s, loss=1.45]
SASRec epoch 2/8:   9%|▉         | 134/1500 [00:04<00:48, 28.34it/s, loss=1.45]
SASRec epoch 2/8:   9%|▉         | 137/1500 [00:04<00:47, 28.72it/s, loss=1.45]
SASRec epoch 2/8:   9%|▉         | 140/1500 [00:05<00:47, 28.85it/s, loss=1.45]
SASRec epoch 2/8:  10%|▉         | 143/1500 [00:05<00:46, 28.92it/s, loss=1.45]
SASRec epoch 2/8:  10%|▉         | 146/1500 [00:05<00:47, 28.58it/s, loss=1.45]
SASRec epoch 2/8:  10%|▉         | 149/1500 [00:05<00:48, 27.59it/s, loss=1.45]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:05<00:48, 27.59it/s, loss=1.46]
SASRec epoch 2/8:  10%|█         | 152/1500 [00:05<00:51, 26.38it/s, loss=1.46]
SASRec epoch 2/8:  10%|█         | 155/1500 [00:05<00:51, 26.23it/s, loss=1.46]
SASRec epoch 2/8:  11%|█         | 158/1500 [00:05<00:53, 25.21it/s, loss=1.46]
SASRec epoch 2/8:  11%|█         | 161/1500 [00:05<00:53, 25.04it/s, loss=1.46]
SASRec epoch 2/8:  11%|█         | 164/1500 [00:05<00:52, 25.50it/s, loss=1.46]
SASRec epoch 2/8:  11%|█         | 167/1500 [00:06<00:51, 25.87it/s, loss=1.46]
SASRec epoch 2/8:  11%|█▏        | 170/1500 [00:06<00:52, 25.55it/s, loss=1.46]
SASRec epoch 2/8:  12%|█▏        | 173/1500 [00:06<00:51, 25.97it/s, loss=1.46]
SASRec epoch 2/8:  12%|█▏        | 176/1500 [00:06<00:51, 25.89it/s, loss=1.46]
SASRec epoch 2/8:  12%|█▏        | 179/1500 [00:06<00:50, 26.37it/s, loss=1.46]
SASRec epoch 2/8:  12%|█▏        | 182/1500 [00:06<00:51, 25.47it/s, loss=1.46]
SASRec epoch 2/8:  12%|█▏        | 185/1500 [00:06<00:49, 26.58it/s, loss=1.46]
SASRec epoch 2/8:  13%|█▎        | 188/1500 [00:06<00:49, 26.45it/s, loss=1.46]
SASRec epoch 2/8:  13%|█▎        | 191/1500 [00:06<00:48, 27.25it/s, loss=1.46]
SASRec epoch 2/8:  13%|█▎        | 195/1500 [00:07<00:45, 28.47it/s, loss=1.46]
SASRec epoch 2/8:  13%|█▎        | 198/1500 [00:07<00:45, 28.67it/s, loss=1.46]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.67it/s, loss=1.43]
SASRec epoch 2/8:  13%|█▎        | 201/1500 [00:07<00:45, 28.39it/s, loss=1.43]
SASRec epoch 2/8:  14%|█▎        | 204/1500 [00:07<00:45, 28.73it/s, loss=1.43]
SASRec epoch 2/8:  14%|█▍        | 208/1500 [00:07<00:44, 29.35it/s, loss=1.43]
SASRec epoch 2/8:  14%|█▍        | 211/1500 [00:07<00:43, 29.50it/s, loss=1.43]
SASRec epoch 2/8:  14%|█▍        | 214/1500 [00:07<00:43, 29.45it/s, loss=1.43]
SASRec epoch 2/8:  14%|█▍        | 217/1500 [00:07<00:43, 29.19it/s, loss=1.43]
SASRec epoch 2/8:  15%|█▍        | 220/1500 [00:07<00:43, 29.19it/s, loss=1.43]
SASRec epoch 2/8:  15%|█▍        | 223/1500 [00:08<00:43, 29.40it/s, loss=1.43]
SASRec epoch 2/8:  15%|█▌        | 227/1500 [00:08<00:42, 29.88it/s, loss=1.43]
SASRec epoch 2/8:  15%|█▌        | 230/1500 [00:08<00:42, 29.59it/s, loss=1.43]
SASRec epoch 2/8:  16%|█▌        | 234/1500 [00:08<00:42, 30.06it/s, loss=1.43]
SASRec epoch 2/8:  16%|█▌        | 238/1500 [00:08<00:41, 30.27it/s, loss=1.43]
SASRec epoch 2/8:  16%|█▌        | 242/1500 [00:08<00:41, 30.41it/s, loss=1.43]
SASRec epoch 2/8:  16%|█▋        | 246/1500 [00:08<00:41, 30.58it/s, loss=1.43]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:08<00:41, 30.13it/s, loss=1.43]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:08<00:41, 30.13it/s, loss=1.42]
SASRec epoch 2/8:  17%|█▋        | 254/1500 [00:09<00:42, 29.65it/s, loss=1.42]
SASRec epoch 2/8:  17%|█▋        | 257/1500 [00:09<00:42, 29.47it/s, loss=1.42]
SASRec epoch 2/8:  17%|█▋        | 261/1500 [00:09<00:41, 29.90it/s, loss=1.42]
SASRec epoch 2/8:  18%|█▊        | 264/1500 [00:09<00:41, 29.87it/s, loss=1.42]
SASRec epoch 2/8:  18%|█▊        | 267/1500 [00:09<00:41, 29.72it/s, loss=1.42]
SASRec epoch 2/8:  18%|█▊        | 271/1500 [00:09<00:40, 30.09it/s, loss=1.42]
SASRec epoch 2/8:  18%|█▊        | 275/1500 [00:09<00:40, 30.46it/s, loss=1.42]
SASRec epoch 2/8:  19%|█▊        | 279/1500 [00:09<00:39, 30.57it/s, loss=1.42]
SASRec epoch 2/8:  19%|█▉        | 283/1500 [00:10<00:40, 30.37it/s, loss=1.42]
SASRec epoch 2/8:  19%|█▉        | 287/1500 [00:10<00:40, 30.21it/s, loss=1.42]
SASRec epoch 2/8:  19%|█▉        | 291/1500 [00:10<00:40, 30.20it/s, loss=1.42]
SASRec epoch 2/8:  20%|█▉        | 295/1500 [00:10<00:39, 30.19it/s, loss=1.42]
SASRec epoch 2/8:  20%|█▉        | 299/1500 [00:10<00:39, 30.32it/s, loss=1.42]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:10<00:39, 30.32it/s, loss=1.42]
SASRec epoch 2/8:  20%|██        | 303/1500 [00:10<00:40, 29.52it/s, loss=1.42]
SASRec epoch 2/8:  20%|██        | 306/1500 [00:10<00:40, 29.54it/s, loss=1.42]
SASRec epoch 2/8:  21%|██        | 309/1500 [00:10<00:40, 29.47it/s, loss=1.42]
SASRec epoch 2/8:  21%|██        | 312/1500 [00:11<00:40, 29.04it/s, loss=1.42]
SASRec epoch 2/8:  21%|██        | 315/1500 [00:11<00:40, 29.21it/s, loss=1.42]
SASRec epoch 2/8:  21%|██        | 318/1500 [00:11<00:40, 29.06it/s, loss=1.42]
SASRec epoch 2/8:  21%|██▏       | 321/1500 [00:11<00:40, 29.17it/s, loss=1.42]
SASRec epoch 2/8:  22%|██▏       | 325/1500 [00:11<00:39, 29.73it/s, loss=1.42]
SASRec epoch 2/8:  22%|██▏       | 328/1500 [00:11<00:39, 29.56it/s, loss=1.42]
SASRec epoch 2/8:  22%|██▏       | 332/1500 [00:11<00:38, 30.06it/s, loss=1.42]
SASRec epoch 2/8:  22%|██▏       | 335/1500 [00:11<00:38, 29.99it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 338/1500 [00:11<00:38, 29.83it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 342/1500 [00:12<00:38, 30.00it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 345/1500 [00:12<00:39, 29.61it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 348/1500 [00:12<00:38, 29.60it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 350/1500 [00:12<00:38, 29.60it/s, loss=1.42]
SASRec epoch 2/8:  23%|██▎       | 351/1500 [00:12<00:40, 28.70it/s, loss=1.42]
SASRec epoch 2/8:  24%|██▎       | 354/1500 [00:12<00:39, 28.95it/s, loss=1.42]
SASRec epoch 2/8:  24%|██▍       | 357/1500 [00:12<00:39, 28.79it/s, loss=1.42]
SASRec epoch 2/8:  24%|██▍       | 361/1500 [00:12<00:38, 29.55it/s, loss=1.42]
SASRec epoch 2/8:  24%|██▍       | 365/1500 [00:12<00:37, 30.01it/s, loss=1.42]
SASRec epoch 2/8:  25%|██▍       | 368/1500 [00:12<00:37, 29.96it/s, loss=1.42]
SASRec epoch 2/8:  25%|██▍       | 371/1500 [00:12<00:37, 29.80it/s, loss=1.42]
SASRec epoch 2/8:  25%|██▍       | 374/1500 [00:13<00:38, 29.47it/s, loss=1.42]
SASRec epoch 2/8:  25%|██▌       | 377/1500 [00:13<00:37, 29.57it/s, loss=1.42]
SASRec epoch 2/8:  25%|██▌       | 380/1500 [00:13<00:37, 29.51it/s, loss=1.42]
SASRec epoch 2/8:  26%|██▌       | 383/1500 [00:13<00:37, 29.58it/s, loss=1.42]
SASRec epoch 2/8:  26%|██▌       | 386/1500 [00:13<00:37, 29.45it/s, loss=1.42]
SASRec epoch 2/8:  26%|██▌       | 389/1500 [00:13<00:37, 29.52it/s, loss=1.42]
SASRec epoch 2/8:  26%|██▌       | 392/1500 [00:13<00:37, 29.58it/s, loss=1.42]
SASRec epoch 2/8:  26%|██▋       | 395/1500 [00:13<00:37, 29.40it/s, loss=1.42]
SASRec epoch 2/8:  27%|██▋       | 398/1500 [00:13<00:37, 29.41it/s, loss=1.42]
SASRec epoch 2/8:  27%|██▋       | 400/1500 [00:13<00:37, 29.41it/s, loss=1.4]
SASRec epoch 2/8:  27%|██▋       | 401/1500 [00:14<00:38, 28.60it/s, loss=1.4]
SASRec epoch 2/8:  27%|██▋       | 404/1500 [00:14<00:38, 28.52it/s, loss=1.4]
SASRec epoch 2/8:  27%|██▋       | 407/1500 [00:14<00:37, 28.87it/s, loss=1.4]
SASRec epoch 2/8:  27%|██▋       | 410/1500 [00:14<00:37, 29.07it/s, loss=1.4]
SASRec epoch 2/8:  28%|██▊       | 413/1500 [00:14<00:37, 29.22it/s, loss=1.4]
SASRec epoch 2/8:  28%|██▊       | 416/1500 [00:14<00:37, 29.29it/s, loss=1.4]
SASRec epoch 2/8:  28%|██▊       | 419/1500 [00:14<00:36, 29.37it/s, loss=1.4]
SASRec epoch 2/8:  28%|██▊       | 423/1500 [00:14<00:36, 29.92it/s, loss=1.4]
SASRec epoch 2/8:  28%|██▊       | 426/1500 [00:14<00:36, 29.81it/s, loss=1.4]
SASRec epoch 2/8:  29%|██▊       | 429/1500 [00:14<00:36, 29.74it/s, loss=1.4]
SASRec epoch 2/8:  29%|██▉       | 432/1500 [00:15<00:35, 29.80it/s, loss=1.4]
SASRec epoch 2/8:  29%|██▉       | 435/1500 [00:15<00:36, 29.20it/s, loss=1.4]
SASRec epoch 2/8:  29%|██▉       | 438/1500 [00:15<00:36, 28.92it/s, loss=1.4]
SASRec epoch 2/8:  29%|██▉       | 441/1500 [00:15<00:36, 28.72it/s, loss=1.4]
SASRec epoch 2/8:  30%|██▉       | 444/1500 [00:15<00:36, 29.03it/s, loss=1.4]
SASRec epoch 2/8:  30%|██▉       | 447/1500 [00:15<00:36, 28.86it/s, loss=1.4]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:15<00:36, 28.86it/s, loss=1.41]
SASRec epoch 2/8:  30%|███       | 451/1500 [00:15<00:36, 29.00it/s, loss=1.41]
SASRec epoch 2/8:  30%|███       | 454/1500 [00:15<00:35, 29.14it/s, loss=1.41]
SASRec epoch 2/8:  30%|███       | 457/1500 [00:15<00:35, 29.17it/s, loss=1.41]
SASRec epoch 2/8:  31%|███       | 461/1500 [00:16<00:34, 29.80it/s, loss=1.41]
SASRec epoch 2/8:  31%|███       | 464/1500 [00:16<00:34, 29.83it/s, loss=1.41]
SASRec epoch 2/8:  31%|███       | 467/1500 [00:16<00:34, 29.60it/s, loss=1.41]
SASRec epoch 2/8:  31%|███▏      | 471/1500 [00:16<00:34, 30.01it/s, loss=1.41]
SASRec epoch 2/8:  32%|███▏      | 474/1500 [00:16<00:34, 29.80it/s, loss=1.41]
SASRec epoch 2/8:  32%|███▏      | 478/1500 [00:16<00:34, 29.78it/s, loss=1.41]
SASRec epoch 2/8:  32%|███▏      | 481/1500 [00:16<00:34, 29.41it/s, loss=1.41]
SASRec epoch 2/8:  32%|███▏      | 484/1500 [00:16<00:35, 28.78it/s, loss=1.41]
SASRec epoch 2/8:  32%|███▏      | 487/1500 [00:16<00:35, 28.90it/s, loss=1.41]
SASRec epoch 2/8:  33%|███▎      | 490/1500 [00:17<00:35, 28.14it/s, loss=1.41]
SASRec epoch 2/8:  33%|███▎      | 493/1500 [00:17<00:36, 27.76it/s, loss=1.41]
SASRec epoch 2/8:  33%|███▎      | 496/1500 [00:17<00:37, 27.02it/s, loss=1.41]
SASRec epoch 2/8:  33%|███▎      | 499/1500 [00:17<00:36, 27.23it/s, loss=1.41]
SASRec epoch 2/8:  33%|███▎      | 500/1500 [00:17<00:36, 27.23it/s, loss=1.39]
SASRec epoch 2/8:  33%|███▎      | 502/1500 [00:17<00:37, 26.75it/s, loss=1.39]
SASRec epoch 2/8:  34%|███▎      | 505/1500 [00:17<00:36, 27.37it/s, loss=1.39]
SASRec epoch 2/8:  34%|███▍      | 508/1500 [00:17<00:35, 27.87it/s, loss=1.39]
SASRec epoch 2/8:  34%|███▍      | 511/1500 [00:17<00:35, 27.98it/s, loss=1.39]
SASRec epoch 2/8:  34%|███▍      | 514/1500 [00:17<00:35, 28.02it/s, loss=1.39]
SASRec epoch 2/8:  34%|███▍      | 517/1500 [00:18<00:34, 28.10it/s, loss=1.39]
SASRec epoch 2/8:  35%|███▍      | 520/1500 [00:18<00:34, 28.03it/s, loss=1.39]
SASRec epoch 2/8:  35%|███▍      | 523/1500 [00:18<00:35, 27.63it/s, loss=1.39]
SASRec epoch 2/8:  35%|███▌      | 526/1500 [00:18<00:35, 27.45it/s, loss=1.39]
SASRec epoch 2/8:  35%|███▌      | 529/1500 [00:18<00:35, 27.62it/s, loss=1.39]
SASRec epoch 2/8:  35%|███▌      | 532/1500 [00:18<00:34, 27.90it/s, loss=1.39]
SASRec epoch 2/8:  36%|███▌      | 535/1500 [00:18<00:34, 28.03it/s, loss=1.39]
SASRec epoch 2/8:  36%|███▌      | 538/1500 [00:18<00:34, 28.24it/s, loss=1.39]
SASRec epoch 2/8:  36%|███▌      | 541/1500 [00:18<00:33, 28.26it/s, loss=1.39]
SASRec epoch 2/8:  36%|███▋      | 544/1500 [00:19<00:33, 28.36it/s, loss=1.39]
SASRec epoch 2/8:  36%|███▋      | 547/1500 [00:19<00:33, 28.09it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 550/1500 [00:19<00:34, 27.28it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 550/1500 [00:19<00:34, 27.28it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 553/1500 [00:19<00:34, 27.36it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 556/1500 [00:19<00:33, 27.90it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 559/1500 [00:19<00:34, 27.24it/s, loss=1.39]
SASRec epoch 2/8:  37%|███▋      | 562/1500 [00:19<00:33, 27.66it/s, loss=1.39]
SASRec epoch 2/8:  38%|███▊      | 565/1500 [00:19<00:33, 28.10it/s, loss=1.39]
SASRec epoch 2/8:  38%|███▊      | 568/1500 [00:19<00:32, 28.45it/s, loss=1.39]
SASRec epoch 2/8:  38%|███▊      | 571/1500 [00:19<00:32, 28.51it/s, loss=1.39]
SASRec epoch 2/8:  38%|███▊      | 574/1500 [00:20<00:32, 28.17it/s, loss=1.39]
SASRec epoch 2/8:  38%|███▊      | 577/1500 [00:20<00:33, 27.62it/s, loss=1.39]
SASRec epoch 2/8:  39%|███▊      | 580/1500 [00:20<00:33, 27.37it/s, loss=1.39]
SASRec epoch 2/8:  39%|███▉      | 583/1500 [00:20<00:33, 27.27it/s, loss=1.39]
SASRec epoch 2/8:  39%|███▉      | 586/1500 [00:20<00:32, 27.77it/s, loss=1.39]
SASRec epoch 2/8:  39%|███▉      | 589/1500 [00:20<00:33, 26.99it/s, loss=1.39]
SASRec epoch 2/8:  39%|███▉      | 592/1500 [00:20<00:34, 26.41it/s, loss=1.39]
SASRec epoch 2/8:  40%|███▉      | 595/1500 [00:20<00:34, 26.35it/s, loss=1.39]
SASRec epoch 2/8:  40%|███▉      | 598/1500 [00:21<00:34, 25.89it/s, loss=1.39]
SASRec epoch 2/8:  40%|████      | 600/1500 [00:21<00:34, 25.89it/s, loss=1.38]
SASRec epoch 2/8:  40%|████      | 601/1500 [00:21<00:35, 25.18it/s, loss=1.38]
SASRec epoch 2/8:  40%|████      | 604/1500 [00:21<00:35, 25.46it/s, loss=1.38]
SASRec epoch 2/8:  40%|████      | 607/1500 [00:21<00:35, 25.01it/s, loss=1.38]
SASRec epoch 2/8:  41%|████      | 610/1500 [00:21<00:35, 24.78it/s, loss=1.38]
SASRec epoch 2/8:  41%|████      | 613/1500 [00:21<00:34, 25.39it/s, loss=1.38]
SASRec epoch 2/8:  41%|████      | 616/1500 [00:21<00:36, 24.52it/s, loss=1.38]
SASRec epoch 2/8:  41%|████▏     | 619/1500 [00:21<00:36, 24.08it/s, loss=1.38]
SASRec epoch 2/8:  41%|████▏     | 622/1500 [00:21<00:34, 25.54it/s, loss=1.38]
SASRec epoch 2/8:  42%|████▏     | 626/1500 [00:22<00:32, 27.23it/s, loss=1.38]
SASRec epoch 2/8:  42%|████▏     | 629/1500 [00:22<00:31, 27.68it/s, loss=1.38]
SASRec epoch 2/8:  42%|████▏     | 632/1500 [00:22<00:30, 28.07it/s, loss=1.38]
SASRec epoch 2/8:  42%|████▏     | 635/1500 [00:22<00:30, 28.25it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 638/1500 [00:22<00:30, 28.46it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 641/1500 [00:22<00:29, 28.70it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 644/1500 [00:22<00:29, 28.89it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 647/1500 [00:22<00:29, 28.65it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 650/1500 [00:22<00:29, 29.02it/s, loss=1.38]
SASRec epoch 2/8:  43%|████▎     | 650/1500 [00:22<00:29, 29.02it/s, loss=1.38]
SASRec epoch 2/8:  44%|████▎     | 653/1500 [00:23<00:29, 28.53it/s, loss=1.38]
SASRec epoch 2/8:  44%|████▍     | 657/1500 [00:23<00:28, 29.34it/s, loss=1.38]
SASRec epoch 2/8:  44%|████▍     | 660/1500 [00:23<00:28, 29.51it/s, loss=1.38]
SASRec epoch 2/8:  44%|████▍     | 663/1500 [00:23<00:28, 29.48it/s, loss=1.38]
SASRec epoch 2/8:  44%|████▍     | 666/1500 [00:23<00:28, 29.26it/s, loss=1.38]
SASRec epoch 2/8:  45%|████▍     | 669/1500 [00:23<00:28, 29.34it/s, loss=1.38]
SASRec epoch 2/8:  45%|████▍     | 672/1500 [00:23<00:28, 29.40it/s, loss=1.38]
SASRec epoch 2/8:  45%|████▌     | 675/1500 [00:23<00:28, 29.22it/s, loss=1.38]
SASRec epoch 2/8:  45%|████▌     | 678/1500 [00:23<00:28, 28.75it/s, loss=1.38]
SASRec epoch 2/8:  45%|████▌     | 682/1500 [00:24<00:27, 29.43it/s, loss=1.38]
SASRec epoch 2/8:  46%|████▌     | 685/1500 [00:24<00:27, 29.55it/s, loss=1.38]
SASRec epoch 2/8:  46%|████▌     | 688/1500 [00:24<00:27, 29.53it/s, loss=1.38]
SASRec epoch 2/8:  46%|████▌     | 691/1500 [00:24<00:27, 29.55it/s, loss=1.38]
SASRec epoch 2/8:  46%|████▋     | 694/1500 [00:24<00:27, 29.19it/s, loss=1.38]
SASRec epoch 2/8:  46%|████▋     | 697/1500 [00:24<00:27, 29.28it/s, loss=1.38]
SASRec epoch 2/8:  47%|████▋     | 700/1500 [00:24<00:27, 29.28it/s, loss=1.38]
SASRec epoch 2/8:  47%|████▋     | 700/1500 [00:24<00:27, 29.28it/s, loss=1.37]
SASRec epoch 2/8:  47%|████▋     | 703/1500 [00:24<00:27, 28.59it/s, loss=1.37]
SASRec epoch 2/8:  47%|████▋     | 706/1500 [00:24<00:27, 28.63it/s, loss=1.37]
SASRec epoch 2/8:  47%|████▋     | 709/1500 [00:24<00:27, 28.77it/s, loss=1.37]
SASRec epoch 2/8:  47%|████▋     | 712/1500 [00:25<00:27, 29.02it/s, loss=1.37]
SASRec epoch 2/8:  48%|████▊     | 715/1500 [00:25<00:26, 29.20it/s, loss=1.37]
SASRec epoch 2/8:  48%|████▊     | 719/1500 [00:25<00:26, 29.77it/s, loss=1.37]
SASRec epoch 2/8:  48%|████▊     | 722/1500 [00:25<00:26, 29.79it/s, loss=1.37]
SASRec epoch 2/8:  48%|████▊     | 725/1500 [00:25<00:25, 29.82it/s, loss=1.37]
SASRec epoch 2/8:  49%|████▊     | 728/1500 [00:25<00:26, 29.59it/s, loss=1.37]
SASRec epoch 2/8:  49%|████▊     | 731/1500 [00:25<00:26, 29.20it/s, loss=1.37]
SASRec epoch 2/8:  49%|████▉     | 734/1500 [00:25<00:26, 29.33it/s, loss=1.37]
SASRec epoch 2/8:  49%|████▉     | 737/1500 [00:25<00:25, 29.45it/s, loss=1.37]
SASRec epoch 2/8:  49%|████▉     | 740/1500 [00:26<00:26, 28.96it/s, loss=1.37]
SASRec epoch 2/8:  50%|████▉     | 744/1500 [00:26<00:25, 29.64it/s, loss=1.37]
SASRec epoch 2/8:  50%|████▉     | 747/1500 [00:26<00:25, 29.54it/s, loss=1.37]
SASRec epoch 2/8:  50%|█████     | 750/1500 [00:26<00:25, 29.48it/s, loss=1.37]

[SASRec] epoch 2/8 loss=1.3687

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 3/8:   0%|          | 3/1500 [00:00<00:56, 26.73it/s]
SASRec epoch 3/8:   0%|          | 6/1500 [00:00<00:56, 26.62it/s]
SASRec epoch 3/8:   1%|          | 9/1500 [00:00<00:56, 26.58it/s]
SASRec epoch 3/8:   1%|          | 12/1500 [00:00<00:55, 26.92it/s]
SASRec epoch 3/8:   1%|          | 15/1500 [00:00<00:55, 26.95it/s]
SASRec epoch 3/8:   1%|          | 18/1500 [00:00<00:54, 27.12it/s]
SASRec epoch 3/8:   1%|▏         | 21/1500 [00:00<00:54, 27.11it/s]
SASRec epoch 3/8:   2%|▏         | 24/1500 [00:00<00:54, 27.27it/s]
SASRec epoch 3/8:   2%|▏         | 27/1500 [00:01<00:55, 26.36it/s]
SASRec epoch 3/8:   2%|▏         | 30/1500 [00:01<00:58, 25.12it/s]
SASRec epoch 3/8:   2%|▏         | 33/1500 [00:01<00:56, 25.75it/s]
SASRec epoch 3/8:   2%|▏         | 36/1500 [00:01<00:54, 26.76it/s]
SASRec epoch 3/8:   3%|▎         | 39/1500 [00:01<00:53, 27.42it/s]
SASRec epoch 3/8:   3%|▎         | 42/1500 [00:01<00:51, 28.06it/s]
SASRec epoch 3/8:   3%|▎         | 46/1500 [00:01<00:50, 29.01it/s]
SASRec epoch 3/8:   3%|▎         | 49/1500 [00:01<00:49, 29.13it/s]
SASRec epoch 3/8:   3%|▎         | 50/1500 [00:01<00:49, 29.13it/s, loss=1.3]
SASRec epoch 3/8:   3%|▎         | 52/1500 [00:01<00:50, 28.66it/s, loss=1.3]
SASRec epoch 3/8:   4%|▎         | 55/1500 [00:02<00:50, 28.89it/s, loss=1.3]
SASRec epoch 3/8:   4%|▍         | 59/1500 [00:02<00:48, 29.56it/s, loss=1.3]
SASRec epoch 3/8:   4%|▍         | 62/1500 [00:02<00:49, 29.14it/s, loss=1.3]
SASRec epoch 3/8:   4%|▍         | 65/1500 [00:02<00:49, 29.25it/s, loss=1.3]
SASRec epoch 3/8:   5%|▍         | 68/1500 [00:02<00:48, 29.36it/s, loss=1.3]
SASRec epoch 3/8:   5%|▍         | 71/1500 [00:02<00:48, 29.32it/s, loss=1.3]
SASRec epoch 3/8:   5%|▍         | 74/1500 [00:02<00:48, 29.34it/s, loss=1.3]
SASRec epoch 3/8:   5%|▌         | 78/1500 [00:02<00:47, 29.95it/s, loss=1.3]
SASRec epoch 3/8:   5%|▌         | 81/1500 [00:02<00:47, 29.67it/s, loss=1.3]
SASRec epoch 3/8:   6%|▌         | 84/1500 [00:02<00:47, 29.75it/s, loss=1.3]
SASRec epoch 3/8:   6%|▌         | 87/1500 [00:03<00:47, 29.60it/s, loss=1.3]
SASRec epoch 3/8:   6%|▌         | 90/1500 [00:03<00:47, 29.58it/s, loss=1.3]
SASRec epoch 3/8:   6%|▌         | 93/1500 [00:03<00:48, 29.13it/s, loss=1.3]
SASRec epoch 3/8:   6%|▋         | 96/1500 [00:03<00:48, 29.07it/s, loss=1.3]
SASRec epoch 3/8:   7%|▋         | 99/1500 [00:03<00:48, 29.09it/s, loss=1.3]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:03<00:48, 29.09it/s, loss=1.29]
SASRec epoch 3/8:   7%|▋         | 102/1500 [00:03<00:49, 28.49it/s, loss=1.29]
SASRec epoch 3/8:   7%|▋         | 105/1500 [00:03<00:48, 28.72it/s, loss=1.29]
SASRec epoch 3/8:   7%|▋         | 108/1500 [00:03<00:48, 28.96it/s, loss=1.29]
SASRec epoch 3/8:   7%|▋         | 111/1500 [00:03<00:47, 29.00it/s, loss=1.29]
SASRec epoch 3/8:   8%|▊         | 114/1500 [00:04<00:47, 29.07it/s, loss=1.29]
SASRec epoch 3/8:   8%|▊         | 117/1500 [00:04<00:47, 29.20it/s, loss=1.29]
SASRec epoch 3/8:   8%|▊         | 120/1500 [00:04<00:46, 29.41it/s, loss=1.29]
SASRec epoch 3/8:   8%|▊         | 123/1500 [00:04<00:48, 28.25it/s, loss=1.29]
SASRec epoch 3/8:   8%|▊         | 126/1500 [00:04<00:48, 28.58it/s, loss=1.29]
SASRec epoch 3/8:   9%|▊         | 129/1500 [00:04<00:47, 28.87it/s, loss=1.29]
SASRec epoch 3/8:   9%|▉         | 132/1500 [00:04<00:47, 28.85it/s, loss=1.29]
SASRec epoch 3/8:   9%|▉         | 135/1500 [00:04<00:47, 29.01it/s, loss=1.29]
SASRec epoch 3/8:   9%|▉         | 138/1500 [00:04<00:46, 29.16it/s, loss=1.29]
SASRec epoch 3/8:   9%|▉         | 141/1500 [00:04<00:46, 29.12it/s, loss=1.29]
SASRec epoch 3/8:  10%|▉         | 144/1500 [00:05<00:47, 28.84it/s, loss=1.29]
SASRec epoch 3/8:  10%|▉         | 147/1500 [00:05<00:46, 29.17it/s, loss=1.29]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:05<00:46, 29.20it/s, loss=1.29]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:05<00:46, 29.20it/s, loss=1.29]
SASRec epoch 3/8:  10%|█         | 153/1500 [00:05<00:49, 27.46it/s, loss=1.29]
SASRec epoch 3/8:  10%|█         | 156/1500 [00:05<00:47, 28.05it/s, loss=1.29]
SASRec epoch 3/8:  11%|█         | 159/1500 [00:05<00:47, 28.08it/s, loss=1.29]
SASRec epoch 3/8:  11%|█         | 162/1500 [00:05<00:47, 28.31it/s, loss=1.29]
SASRec epoch 3/8:  11%|█         | 165/1500 [00:05<00:46, 28.76it/s, loss=1.29]
SASRec epoch 3/8:  11%|█         | 168/1500 [00:05<00:45, 29.12it/s, loss=1.29]
SASRec epoch 3/8:  11%|█▏        | 171/1500 [00:05<00:45, 29.05it/s, loss=1.29]
SASRec epoch 3/8:  12%|█▏        | 174/1500 [00:06<00:45, 29.09it/s, loss=1.29]
SASRec epoch 3/8:  12%|█▏        | 177/1500 [00:06<00:45, 28.98it/s, loss=1.29]
SASRec epoch 3/8:  12%|█▏        | 180/1500 [00:06<00:45, 28.96it/s, loss=1.29]
SASRec epoch 3/8:  12%|█▏        | 183/1500 [00:06<00:45, 28.66it/s, loss=1.29]
SASRec epoch 3/8:  12%|█▏        | 186/1500 [00:06<00:45, 28.86it/s, loss=1.29]
SASRec epoch 3/8:  13%|█▎        | 189/1500 [00:06<00:45, 28.90it/s, loss=1.29]
SASRec epoch 3/8:  13%|█▎        | 192/1500 [00:06<00:45, 28.78it/s, loss=1.29]
SASRec epoch 3/8:  13%|█▎        | 195/1500 [00:06<00:45, 28.84it/s, loss=1.29]
SASRec epoch 3/8:  13%|█▎        | 198/1500 [00:06<00:45, 28.88it/s, loss=1.29]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.88it/s, loss=1.3]
SASRec epoch 3/8:  13%|█▎        | 201/1500 [00:07<00:45, 28.26it/s, loss=1.3]
SASRec epoch 3/8:  14%|█▎        | 204/1500 [00:07<00:45, 28.41it/s, loss=1.3]
SASRec epoch 3/8:  14%|█▍        | 207/1500 [00:07<00:45, 28.61it/s, loss=1.3]
SASRec epoch 3/8:  14%|█▍        | 210/1500 [00:07<00:44, 28.71it/s, loss=1.3]
SASRec epoch 3/8:  14%|█▍        | 213/1500 [00:07<00:45, 28.47it/s, loss=1.3]
SASRec epoch 3/8:  14%|█▍        | 216/1500 [00:07<00:44, 28.55it/s, loss=1.3]
SASRec epoch 3/8:  15%|█▍        | 219/1500 [00:07<00:44, 28.50it/s, loss=1.3]
SASRec epoch 3/8:  15%|█▍        | 222/1500 [00:07<00:44, 28.78it/s, loss=1.3]
SASRec epoch 3/8:  15%|█▌        | 225/1500 [00:07<00:43, 29.08it/s, loss=1.3]
SASRec epoch 3/8:  15%|█▌        | 228/1500 [00:07<00:43, 29.16it/s, loss=1.3]
SASRec epoch 3/8:  15%|█▌        | 231/1500 [00:08<00:43, 29.12it/s, loss=1.3]
SASRec epoch 3/8:  16%|█▌        | 234/1500 [00:08<00:43, 29.23it/s, loss=1.3]
SASRec epoch 3/8:  16%|█▌        | 237/1500 [00:08<00:43, 29.20it/s, loss=1.3]
SASRec epoch 3/8:  16%|█▌        | 240/1500 [00:08<00:43, 29.25it/s, loss=1.3]
SASRec epoch 3/8:  16%|█▌        | 243/1500 [00:08<00:44, 28.46it/s, loss=1.3]
SASRec epoch 3/8:  16%|█▋        | 246/1500 [00:08<00:43, 28.56it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 249/1500 [00:08<00:44, 28.36it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 250/1500 [00:08<00:44, 28.36it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 252/1500 [00:08<00:45, 27.65it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 255/1500 [00:08<00:44, 28.12it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 258/1500 [00:09<00:43, 28.50it/s, loss=1.3]
SASRec epoch 3/8:  17%|█▋        | 261/1500 [00:09<00:43, 28.48it/s, loss=1.3]
SASRec epoch 3/8:  18%|█▊        | 264/1500 [00:09<00:43, 28.71it/s, loss=1.3]
SASRec epoch 3/8:  18%|█▊        | 267/1500 [00:09<00:42, 28.79it/s, loss=1.3]
SASRec epoch 3/8:  18%|█▊        | 270/1500 [00:09<00:42, 29.03it/s, loss=1.3]
SASRec epoch 3/8:  18%|█▊        | 273/1500 [00:09<00:43, 28.26it/s, loss=1.3]
SASRec epoch 3/8:  18%|█▊        | 276/1500 [00:09<00:43, 28.43it/s, loss=1.3]
SASRec epoch 3/8:  19%|█▊        | 279/1500 [00:09<00:42, 28.77it/s, loss=1.3]
SASRec epoch 3/8:  19%|█▉        | 282/1500 [00:09<00:42, 28.96it/s, loss=1.3]
SASRec epoch 3/8:  19%|█▉        | 286/1500 [00:09<00:41, 29.55it/s, loss=1.3]
SASRec epoch 3/8:  19%|█▉        | 289/1500 [00:10<00:40, 29.58it/s, loss=1.3]
SASRec epoch 3/8:  19%|█▉        | 292/1500 [00:10<00:40, 29.57it/s, loss=1.3]
SASRec epoch 3/8:  20%|█▉        | 295/1500 [00:10<00:40, 29.49it/s, loss=1.3]
SASRec epoch 3/8:  20%|█▉        | 298/1500 [00:10<00:40, 29.48it/s, loss=1.3]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:10<00:40, 29.48it/s, loss=1.28]
SASRec epoch 3/8:  20%|██        | 301/1500 [00:10<00:41, 28.79it/s, loss=1.28]
SASRec epoch 3/8:  20%|██        | 304/1500 [00:10<00:42, 28.44it/s, loss=1.28]
SASRec epoch 3/8:  20%|██        | 307/1500 [00:10<00:41, 28.55it/s, loss=1.28]
SASRec epoch 3/8:  21%|██        | 310/1500 [00:10<00:41, 28.39it/s, loss=1.28]
SASRec epoch 3/8:  21%|██        | 313/1500 [00:10<00:41, 28.55it/s, loss=1.28]
SASRec epoch 3/8:  21%|██        | 316/1500 [00:11<00:41, 28.84it/s, loss=1.28]
SASRec epoch 3/8:  21%|██▏       | 319/1500 [00:11<00:40, 28.97it/s, loss=1.28]
SASRec epoch 3/8:  21%|██▏       | 322/1500 [00:11<00:40, 29.25it/s, loss=1.28]
SASRec epoch 3/8:  22%|██▏       | 325/1500 [00:11<00:41, 28.56it/s, loss=1.28]
SASRec epoch 3/8:  22%|██▏       | 328/1500 [00:11<00:43, 26.65it/s, loss=1.28]
SASRec epoch 3/8:  22%|██▏       | 331/1500 [00:11<00:43, 27.04it/s, loss=1.28]
SASRec epoch 3/8:  22%|██▏       | 334/1500 [00:11<00:45, 25.41it/s, loss=1.28]
SASRec epoch 3/8:  22%|██▏       | 337/1500 [00:11<00:46, 25.15it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 340/1500 [00:11<00:45, 25.44it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 343/1500 [00:12<00:44, 25.97it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 346/1500 [00:12<00:43, 26.47it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 349/1500 [00:12<00:43, 26.62it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 350/1500 [00:12<00:43, 26.62it/s, loss=1.28]
SASRec epoch 3/8:  23%|██▎       | 352/1500 [00:12<00:43, 26.54it/s, loss=1.28]
SASRec epoch 3/8:  24%|██▎       | 355/1500 [00:12<00:42, 27.03it/s, loss=1.28]
SASRec epoch 3/8:  24%|██▍       | 358/1500 [00:12<00:42, 27.03it/s, loss=1.28]
SASRec epoch 3/8:  24%|██▍       | 361/1500 [00:12<00:41, 27.37it/s, loss=1.28]
SASRec epoch 3/8:  24%|██▍       | 364/1500 [00:12<00:41, 27.31it/s, loss=1.28]
SASRec epoch 3/8:  24%|██▍       | 367/1500 [00:12<00:41, 27.49it/s, loss=1.28]
SASRec epoch 3/8:  25%|██▍       | 370/1500 [00:13<00:40, 27.98it/s, loss=1.28]
SASRec epoch 3/8:  25%|██▍       | 373/1500 [00:13<00:39, 28.39it/s, loss=1.28]
SASRec epoch 3/8:  25%|██▌       | 376/1500 [00:13<00:39, 28.63it/s, loss=1.28]
SASRec epoch 3/8:  25%|██▌       | 379/1500 [00:13<00:38, 28.80it/s, loss=1.28]
SASRec epoch 3/8:  25%|██▌       | 382/1500 [00:13<00:38, 28.93it/s, loss=1.28]
SASRec epoch 3/8:  26%|██▌       | 385/1500 [00:13<00:39, 28.41it/s, loss=1.28]
SASRec epoch 3/8:  26%|██▌       | 388/1500 [00:13<00:39, 28.28it/s, loss=1.28]
SASRec epoch 3/8:  26%|██▌       | 391/1500 [00:13<00:39, 28.25it/s, loss=1.28]
SASRec epoch 3/8:  26%|██▋       | 394/1500 [00:13<00:38, 28.36it/s, loss=1.28]
SASRec epoch 3/8:  26%|██▋       | 397/1500 [00:14<00:39, 27.61it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:14<00:39, 27.82it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:14<00:39, 27.82it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 403/1500 [00:14<00:39, 28.07it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 406/1500 [00:14<00:38, 28.30it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 409/1500 [00:14<00:38, 28.57it/s, loss=1.28]
SASRec epoch 3/8:  27%|██▋       | 412/1500 [00:14<00:38, 28.29it/s, loss=1.28]
SASRec epoch 3/8:  28%|██▊       | 415/1500 [00:14<00:38, 28.51it/s, loss=1.28]
SASRec epoch 3/8:  28%|██▊       | 418/1500 [00:14<00:38, 28.21it/s, loss=1.28]
SASRec epoch 3/8:  28%|██▊       | 421/1500 [00:14<00:38, 28.12it/s, loss=1.28]
SASRec epoch 3/8:  28%|██▊       | 424/1500 [00:14<00:38, 27.95it/s, loss=1.28]
SASRec epoch 3/8:  28%|██▊       | 427/1500 [00:15<00:38, 28.19it/s, loss=1.28]
SASRec epoch 3/8:  29%|██▊       | 430/1500 [00:15<00:37, 28.35it/s, loss=1.28]
SASRec epoch 3/8:  29%|██▉       | 433/1500 [00:15<00:37, 28.65it/s, loss=1.28]
SASRec epoch 3/8:  29%|██▉       | 436/1500 [00:15<00:36, 28.97it/s, loss=1.28]
SASRec epoch 3/8:  29%|██▉       | 439/1500 [00:15<00:36, 29.02it/s, loss=1.28]
SASRec epoch 3/8:  29%|██▉       | 442/1500 [00:15<00:36, 28.88it/s, loss=1.28]
SASRec epoch 3/8:  30%|██▉       | 445/1500 [00:15<00:37, 28.42it/s, loss=1.28]
SASRec epoch 3/8:  30%|██▉       | 448/1500 [00:15<00:37, 27.89it/s, loss=1.28]
SASRec epoch 3/8:  30%|███       | 450/1500 [00:15<00:37, 27.89it/s, loss=1.27]
SASRec epoch 3/8:  30%|███       | 451/1500 [00:15<00:38, 27.08it/s, loss=1.27]
SASRec epoch 3/8:  30%|███       | 454/1500 [00:16<00:38, 27.02it/s, loss=1.27]
SASRec epoch 3/8:  30%|███       | 457/1500 [00:16<00:38, 27.00it/s, loss=1.27]
SASRec epoch 3/8:  31%|███       | 460/1500 [00:16<00:39, 26.51it/s, loss=1.27]
SASRec epoch 3/8:  31%|███       | 463/1500 [00:16<00:39, 26.59it/s, loss=1.27]
SASRec epoch 3/8:  31%|███       | 466/1500 [00:16<00:40, 25.74it/s, loss=1.27]
SASRec epoch 3/8:  31%|███▏      | 469/1500 [00:16<00:40, 25.72it/s, loss=1.27]
SASRec epoch 3/8:  31%|███▏      | 472/1500 [00:16<00:39, 25.83it/s, loss=1.27]
SASRec epoch 3/8:  32%|███▏      | 475/1500 [00:16<00:41, 24.92it/s, loss=1.27]
SASRec epoch 3/8:  32%|███▏      | 478/1500 [00:16<00:41, 24.77it/s, loss=1.27]
SASRec epoch 3/8:  32%|███▏      | 481/1500 [00:17<00:40, 25.32it/s, loss=1.27]
SASRec epoch 3/8:  32%|███▏      | 484/1500 [00:17<00:39, 25.86it/s, loss=1.27]
SASRec epoch 3/8:  32%|███▏      | 487/1500 [00:17<00:39, 25.51it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 490/1500 [00:17<00:38, 26.46it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 493/1500 [00:17<00:36, 27.27it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 496/1500 [00:17<00:36, 27.83it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 499/1500 [00:17<00:35, 27.94it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 500/1500 [00:17<00:35, 27.94it/s, loss=1.27]
SASRec epoch 3/8:  33%|███▎      | 502/1500 [00:17<00:35, 27.88it/s, loss=1.27]
SASRec epoch 3/8:  34%|███▎      | 505/1500 [00:17<00:35, 28.27it/s, loss=1.27]
SASRec epoch 3/8:  34%|███▍      | 508/1500 [00:18<00:34, 28.38it/s, loss=1.27]
SASRec epoch 3/8:  34%|███▍      | 511/1500 [00:18<00:34, 28.54it/s, loss=1.27]
SASRec epoch 3/8:  34%|███▍      | 514/1500 [00:18<00:34, 28.70it/s, loss=1.27]
SASRec epoch 3/8:  34%|███▍      | 517/1500 [00:18<00:34, 28.28it/s, loss=1.27]
SASRec epoch 3/8:  35%|███▍      | 520/1500 [00:18<00:34, 28.56it/s, loss=1.27]
SASRec epoch 3/8:  35%|███▍      | 523/1500 [00:18<00:33, 28.75it/s, loss=1.27]
SASRec epoch 3/8:  35%|███▌      | 526/1500 [00:18<00:33, 28.99it/s, loss=1.27]
SASRec epoch 3/8:  35%|███▌      | 529/1500 [00:18<00:33, 29.20it/s, loss=1.27]
SASRec epoch 3/8:  35%|███▌      | 532/1500 [00:18<00:33, 29.07it/s, loss=1.27]
SASRec epoch 3/8:  36%|███▌      | 535/1500 [00:18<00:33, 28.82it/s, loss=1.27]
SASRec epoch 3/8:  36%|███▌      | 538/1500 [00:19<00:33, 28.84it/s, loss=1.27]
SASRec epoch 3/8:  36%|███▌      | 541/1500 [00:19<00:33, 28.92it/s, loss=1.27]
SASRec epoch 3/8:  36%|███▋      | 544/1500 [00:19<00:33, 28.89it/s, loss=1.27]
SASRec epoch 3/8:  36%|███▋      | 547/1500 [00:19<00:33, 28.65it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 550/1500 [00:19<00:32, 28.96it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 550/1500 [00:19<00:32, 28.96it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 553/1500 [00:19<00:33, 28.19it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 556/1500 [00:19<00:33, 28.40it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 559/1500 [00:19<00:32, 28.66it/s, loss=1.27]
SASRec epoch 3/8:  37%|███▋      | 562/1500 [00:19<00:32, 28.71it/s, loss=1.27]
SASRec epoch 3/8:  38%|███▊      | 565/1500 [00:20<00:32, 28.80it/s, loss=1.27]
SASRec epoch 3/8:  38%|███▊      | 568/1500 [00:20<00:32, 28.97it/s, loss=1.27]
SASRec epoch 3/8:  38%|███▊      | 571/1500 [00:20<00:32, 29.03it/s, loss=1.27]
SASRec epoch 3/8:  38%|███▊      | 574/1500 [00:20<00:31, 29.19it/s, loss=1.27]
SASRec epoch 3/8:  38%|███▊      | 577/1500 [00:20<00:32, 28.66it/s, loss=1.27]
SASRec epoch 3/8:  39%|███▊      | 580/1500 [00:20<00:32, 28.74it/s, loss=1.27]
SASRec epoch 3/8:  39%|███▉      | 583/1500 [00:20<00:31, 28.88it/s, loss=1.27]
SASRec epoch 3/8:  39%|███▉      | 586/1500 [00:20<00:31, 28.74it/s, loss=1.27]
SASRec epoch 3/8:  39%|███▉      | 589/1500 [00:20<00:31, 28.73it/s, loss=1.27]
SASRec epoch 3/8:  39%|███▉      | 592/1500 [00:20<00:31, 28.91it/s, loss=1.27]
SASRec epoch 3/8:  40%|███▉      | 595/1500 [00:21<00:31, 29.11it/s, loss=1.27]
SASRec epoch 3/8:  40%|███▉      | 598/1500 [00:21<00:30, 29.15it/s, loss=1.27]
SASRec epoch 3/8:  40%|████      | 600/1500 [00:21<00:30, 29.15it/s, loss=1.27]
SASRec epoch 3/8:  40%|████      | 601/1500 [00:21<00:31, 28.55it/s, loss=1.27]
SASRec epoch 3/8:  40%|████      | 604/1500 [00:21<00:30, 28.91it/s, loss=1.27]
SASRec epoch 3/8:  40%|████      | 607/1500 [00:21<00:31, 28.19it/s, loss=1.27]
SASRec epoch 3/8:  41%|████      | 610/1500 [00:21<00:31, 27.92it/s, loss=1.27]
SASRec epoch 3/8:  41%|████      | 613/1500 [00:21<00:31, 27.74it/s, loss=1.27]
SASRec epoch 3/8:  41%|████      | 616/1500 [00:21<00:32, 27.29it/s, loss=1.27]
SASRec epoch 3/8:  41%|████▏     | 619/1500 [00:21<00:32, 27.22it/s, loss=1.27]
SASRec epoch 3/8:  41%|████▏     | 622/1500 [00:22<00:31, 27.58it/s, loss=1.27]
SASRec epoch 3/8:  42%|████▏     | 625/1500 [00:22<00:31, 28.04it/s, loss=1.27]
SASRec epoch 3/8:  42%|████▏     | 628/1500 [00:22<00:30, 28.36it/s, loss=1.27]
SASRec epoch 3/8:  42%|████▏     | 631/1500 [00:22<00:30, 28.73it/s, loss=1.27]
SASRec epoch 3/8:  42%|████▏     | 634/1500 [00:22<00:30, 28.56it/s, loss=1.27]
SASRec epoch 3/8:  42%|████▏     | 637/1500 [00:22<00:30, 28.36it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 640/1500 [00:22<00:30, 28.61it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 643/1500 [00:22<00:29, 28.66it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 646/1500 [00:22<00:29, 28.52it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 649/1500 [00:22<00:29, 28.73it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 650/1500 [00:23<00:29, 28.73it/s, loss=1.27]
SASRec epoch 3/8:  43%|████▎     | 652/1500 [00:23<00:30, 28.24it/s, loss=1.27]
SASRec epoch 3/8:  44%|████▎     | 655/1500 [00:23<00:29, 28.57it/s, loss=1.27]
SASRec epoch 3/8:  44%|████▍     | 658/1500 [00:23<00:29, 28.74it/s, loss=1.27]
SASRec epoch 3/8:  44%|████▍     | 661/1500 [00:23<00:29, 28.89it/s, loss=1.27]
SASRec epoch 3/8:  44%|████▍     | 664/1500 [00:23<00:28, 29.01it/s, loss=1.27]
SASRec epoch 3/8:  44%|████▍     | 667/1500 [00:23<00:29, 28.57it/s, loss=1.27]
SASRec epoch 3/8:  45%|████▍     | 670/1500 [00:23<00:29, 28.60it/s, loss=1.27]
SASRec epoch 3/8:  45%|████▍     | 673/1500 [00:23<00:28, 28.71it/s, loss=1.27]
SASRec epoch 3/8:  45%|████▌     | 676/1500 [00:23<00:28, 29.05it/s, loss=1.27]
SASRec epoch 3/8:  45%|████▌     | 679/1500 [00:24<00:28, 29.05it/s, loss=1.27]
SASRec epoch 3/8:  45%|████▌     | 682/1500 [00:24<00:27, 29.22it/s, loss=1.27]
SASRec epoch 3/8:  46%|████▌     | 685/1500 [00:24<00:27, 29.30it/s, loss=1.27]
SASRec epoch 3/8:  46%|████▌     | 688/1500 [00:24<00:27, 29.20it/s, loss=1.27]
SASRec epoch 3/8:  46%|████▌     | 691/1500 [00:24<00:27, 29.14it/s, loss=1.27]
SASRec epoch 3/8:  46%|████▋     | 694/1500 [00:24<00:27, 29.20it/s, loss=1.27]
SASRec epoch 3/8:  46%|████▋     | 697/1500 [00:24<00:28, 28.57it/s, loss=1.27]
SASRec epoch 3/8:  47%|████▋     | 700/1500 [00:24<00:27, 28.60it/s, loss=1.27]
SASRec epoch 3/8:  47%|████▋     | 700/1500 [00:24<00:27, 28.60it/s, loss=1.25]
SASRec epoch 3/8:  47%|████▋     | 703/1500 [00:24<00:28, 28.14it/s, loss=1.25]
SASRec epoch 3/8:  47%|████▋     | 706/1500 [00:24<00:27, 28.59it/s, loss=1.25]
SASRec epoch 3/8:  47%|████▋     | 709/1500 [00:25<00:27, 28.67it/s, loss=1.25]
SASRec epoch 3/8:  47%|████▋     | 712/1500 [00:25<00:27, 28.93it/s, loss=1.25]
SASRec epoch 3/8:  48%|████▊     | 715/1500 [00:25<00:27, 29.07it/s, loss=1.25]
SASRec epoch 3/8:  48%|████▊     | 719/1500 [00:25<00:26, 29.68it/s, loss=1.25]

[SASRec] epoch 3/8 loss=1.2612

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 4/8:   0%|          | 3/1500 [00:00<00:50, 29.67it/s]
SASRec epoch 4/8:   0%|          | 6/1500 [00:00<00:51, 29.20it/s]
SASRec epoch 4/8:   1%|          | 9/1500 [00:00<00:50, 29.56it/s]
SASRec epoch 4/8:   1%|          | 12/1500 [00:00<00:50, 29.35it/s]
SASRec epoch 4/8:   1%|          | 15/1500 [00:00<00:52, 28.38it/s]
SASRec epoch 4/8:   1%|          | 18/1500 [00:00<00:51, 28.67it/s]
SASRec epoch 4/8:   1%|▏         | 21/1500 [00:00<00:51, 28.83it/s]
SASRec epoch 4/8:   2%|▏         | 24/1500 [00:00<00:51, 28.77it/s]
SASRec epoch 4/8:   2%|▏         | 27/1500 [00:00<00:50, 28.91it/s]
SASRec epoch 4/8:   2%|▏         | 30/1500 [00:01<00:51, 28.79it/s]
SASRec epoch 4/8:   2%|▏         | 33/1500 [00:01<00:50, 28.83it/s]
SASRec epoch 4/8:   2%|▏         | 36/1500 [00:01<00:50, 28.75it/s]
SASRec epoch 4/8:   3%|▎         | 39/1500 [00:01<00:50, 28.84it/s]
SASRec epoch 4/8:   3%|▎         | 42/1500 [00:01<00:50, 28.72it/s]
SASRec epoch 4/8:   3%|▎         | 45/1500 [00:01<00:51, 28.34it/s]
SASRec epoch 4/8:   3%|▎         | 48/1500 [00:01<00:50, 28.63it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:01<00:50, 28.63it/s, loss=1.23]
SASRec epoch 4/8:   3%|▎         | 51/1500 [00:01<00:51, 28.09it/s, loss=1.23]
SASRec epoch 4/8:   4%|▎         | 54/1500 [00:01<00:50, 28.63it/s, loss=1.23]
SASRec epoch 4/8:   4%|▍         | 57/1500 [00:01<00:50, 28.83it/s, loss=1.23]
SASRec epoch 4/8:   4%|▍         | 60/1500 [00:02<00:49, 29.05it/s, loss=1.23]
SASRec epoch 4/8:   4%|▍         | 63/1500 [00:02<00:49, 29.21it/s, loss=1.23]
SASRec epoch 4/8:   4%|▍         | 66/1500 [00:02<00:48, 29.33it/s, loss=1.23]
SASRec epoch 4/8:   5%|▍         | 69/1500 [00:02<00:48, 29.25it/s, loss=1.23]
SASRec epoch 4/8:   5%|▍         | 72/1500 [00:02<00:48, 29.22it/s, loss=1.23]
SASRec epoch 4/8:   5%|▌         | 75/1500 [00:02<00:49, 28.96it/s, loss=1.23]
SASRec epoch 4/8:   5%|▌         | 78/1500 [00:02<00:48, 29.03it/s, loss=1.23]
SASRec epoch 4/8:   5%|▌         | 81/1500 [00:02<00:48, 29.28it/s, loss=1.23]
SASRec epoch 4/8:   6%|▌         | 84/1500 [00:02<00:48, 29.31it/s, loss=1.23]
SASRec epoch 4/8:   6%|▌         | 87/1500 [00:03<00:48, 29.11it/s, loss=1.23]
SASRec epoch 4/8:   6%|▌         | 90/1500 [00:03<00:48, 29.13it/s, loss=1.23]
SASRec epoch 4/8:   6%|▌         | 93/1500 [00:03<00:48, 29.08it/s, loss=1.23]
SASRec epoch 4/8:   6%|▋         | 96/1500 [00:03<00:48, 28.87it/s, loss=1.23]
SASRec epoch 4/8:   7%|▋         | 99/1500 [00:03<00:48, 28.97it/s, loss=1.23]
SASRec epoch 4/8:   7%|▋         | 100/1500 [00:03<00:48, 28.97it/s, loss=1.21]
SASRec epoch 4/8:   7%|▋         | 102/1500 [00:03<00:49, 28.26it/s, loss=1.21]
SASRec epoch 4/8:   7%|▋         | 105/1500 [00:03<00:49, 28.14it/s, loss=1.21]
SASRec epoch 4/8:   7%|▋         | 108/1500 [00:03<00:48, 28.47it/s, loss=1.21]
SASRec epoch 4/8:   7%|▋         | 111/1500 [00:03<00:48, 28.48it/s, loss=1.21]
SASRec epoch 4/8:   8%|▊         | 114/1500 [00:03<00:48, 28.83it/s, loss=1.21]
SASRec epoch 4/8:   8%|▊         | 117/1500 [00:04<00:47, 29.04it/s, loss=1.21]
SASRec epoch 4/8:   8%|▊         | 120/1500 [00:04<00:47, 29.28it/s, loss=1.21]
SASRec epoch 4/8:   8%|▊         | 124/1500 [00:04<00:46, 29.84it/s, loss=1.21]
SASRec epoch 4/8:   8%|▊         | 127/1500 [00:04<00:46, 29.76it/s, loss=1.21]
SASRec epoch 4/8:   9%|▊         | 130/1500 [00:04<00:46, 29.64it/s, loss=1.21]
SASRec epoch 4/8:   9%|▉         | 133/1500 [00:04<00:46, 29.64it/s, loss=1.21]
SASRec epoch 4/8:   9%|▉         | 136/1500 [00:04<00:46, 29.15it/s, loss=1.21]
SASRec epoch 4/8:   9%|▉         | 139/1500 [00:04<00:46, 29.25it/s, loss=1.21]
SASRec epoch 4/8:   9%|▉         | 142/1500 [00:04<00:46, 29.22it/s, loss=1.21]
SASRec epoch 4/8:  10%|▉         | 145/1500 [00:05<00:46, 29.20it/s, loss=1.21]
SASRec epoch 4/8:  10%|▉         | 148/1500 [00:05<00:46, 28.96it/s, loss=1.21]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:05<00:46, 28.96it/s, loss=1.22]
SASRec epoch 4/8:  10%|█         | 151/1500 [00:05<00:47, 28.12it/s, loss=1.22]
SASRec epoch 4/8:  10%|█         | 154/1500 [00:05<00:47, 28.38it/s, loss=1.22]
SASRec epoch 4/8:  10%|█         | 157/1500 [00:05<00:47, 28.54it/s, loss=1.22]
SASRec epoch 4/8:  11%|█         | 160/1500 [00:05<00:46, 28.85it/s, loss=1.22]
SASRec epoch 4/8:  11%|█         | 163/1500 [00:05<00:46, 28.89it/s, loss=1.22]
SASRec epoch 4/8:  11%|█         | 166/1500 [00:05<00:46, 28.68it/s, loss=1.22]
SASRec epoch 4/8:  11%|█▏        | 169/1500 [00:05<00:45, 28.97it/s, loss=1.22]
SASRec epoch 4/8:  11%|█▏        | 172/1500 [00:05<00:45, 29.20it/s, loss=1.22]
SASRec epoch 4/8:  12%|█▏        | 175/1500 [00:06<00:45, 28.99it/s, loss=1.22]
SASRec epoch 4/8:  12%|█▏        | 178/1500 [00:06<00:45, 29.24it/s, loss=1.22]
SASRec epoch 4/8:  12%|█▏        | 181/1500 [00:06<00:45, 29.22it/s, loss=1.22]
SASRec epoch 4/8:  12%|█▏        | 184/1500 [00:06<00:45, 28.84it/s, loss=1.22]
SASRec epoch 4/8:  12%|█▏        | 187/1500 [00:06<00:46, 28.12it/s, loss=1.22]
SASRec epoch 4/8:  13%|█▎        | 190/1500 [00:06<00:47, 27.64it/s, loss=1.22]
SASRec epoch 4/8:  13%|█▎        | 193/1500 [00:06<00:47, 27.31it/s, loss=1.22]
SASRec epoch 4/8:  13%|█▎        | 196/1500 [00:06<00:48, 27.04it/s, loss=1.22]
SASRec epoch 4/8:  13%|█▎        | 199/1500 [00:06<00:47, 27.61it/s, loss=1.22]
SASRec epoch 4/8:  13%|█▎        | 200/1500 [00:06<00:47, 27.61it/s, loss=1.21]
SASRec epoch 4/8:  13%|█▎        | 202/1500 [00:07<00:48, 26.85it/s, loss=1.21]
SASRec epoch 4/8:  14%|█▎        | 205/1500 [00:07<00:47, 27.13it/s, loss=1.21]
SASRec epoch 4/8:  14%|█▍        | 208/1500 [00:07<00:47, 27.40it/s, loss=1.21]
SASRec epoch 4/8:  14%|█▍        | 211/1500 [00:07<00:46, 27.73it/s, loss=1.21]
SASRec epoch 4/8:  14%|█▍        | 214/1500 [00:07<00:45, 28.00it/s, loss=1.21]
SASRec epoch 4/8:  14%|█▍        | 217/1500 [00:07<00:45, 28.16it/s, loss=1.21]
SASRec epoch 4/8:  15%|█▍        | 220/1500 [00:07<00:45, 28.23it/s, loss=1.21]
SASRec epoch 4/8:  15%|█▍        | 223/1500 [00:07<00:45, 28.33it/s, loss=1.21]
SASRec epoch 4/8:  15%|█▌        | 226/1500 [00:07<00:45, 27.85it/s, loss=1.21]
SASRec epoch 4/8:  15%|█▌        | 229/1500 [00:07<00:45, 28.02it/s, loss=1.21]
SASRec epoch 4/8:  15%|█▌        | 232/1500 [00:08<00:45, 28.14it/s, loss=1.21]
SASRec epoch 4/8:  16%|█▌        | 235/1500 [00:08<00:46, 27.20it/s, loss=1.21]
SASRec epoch 4/8:  16%|█▌        | 238/1500 [00:08<00:46, 27.35it/s, loss=1.21]
SASRec epoch 4/8:  16%|█▌        | 241/1500 [00:08<00:46, 26.80it/s, loss=1.21]
SASRec epoch 4/8:  16%|█▋        | 244/1500 [00:08<00:47, 26.68it/s, loss=1.21]
SASRec epoch 4/8:  16%|█▋        | 247/1500 [00:08<00:46, 27.11it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:08<00:45, 27.55it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:08<00:45, 27.55it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 253/1500 [00:08<00:45, 27.58it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 256/1500 [00:08<00:45, 27.54it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 259/1500 [00:09<00:45, 27.47it/s, loss=1.21]
SASRec epoch 4/8:  17%|█▋        | 262/1500 [00:09<00:44, 27.58it/s, loss=1.21]
SASRec epoch 4/8:  18%|█▊        | 265/1500 [00:09<00:44, 27.75it/s, loss=1.21]
SASRec epoch 4/8:  18%|█▊        | 268/1500 [00:09<00:44, 27.95it/s, loss=1.21]
SASRec epoch 4/8:  18%|█▊        | 271/1500 [00:09<00:43, 28.02it/s, loss=1.21]
SASRec epoch 4/8:  18%|█▊        | 274/1500 [00:09<00:43, 28.00it/s, loss=1.21]
SASRec epoch 4/8:  18%|█▊        | 277/1500 [00:09<00:43, 28.05it/s, loss=1.21]
SASRec epoch 4/8:  19%|█▊        | 280/1500 [00:09<00:43, 28.01it/s, loss=1.21]
SASRec epoch 4/8:  19%|█▉        | 283/1500 [00:09<00:43, 27.89it/s, loss=1.21]
SASRec epoch 4/8:  19%|█▉        | 286/1500 [00:10<00:44, 27.00it/s, loss=1.21]
SASRec epoch 4/8:  19%|█▉        | 289/1500 [00:10<00:46, 25.98it/s, loss=1.21]
SASRec epoch 4/8:  19%|█▉        | 292/1500 [00:10<00:45, 26.62it/s, loss=1.21]
SASRec epoch 4/8:  20%|█▉        | 295/1500 [00:10<00:45, 26.64it/s, loss=1.21]
SASRec epoch 4/8:  20%|█▉        | 298/1500 [00:10<00:45, 26.43it/s, loss=1.21]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:10<00:45, 26.43it/s, loss=1.21]
SASRec epoch 4/8:  20%|██        | 301/1500 [00:10<00:47, 25.33it/s, loss=1.21]
SASRec epoch 4/8:  20%|██        | 304/1500 [00:10<00:50, 23.69it/s, loss=1.21]
SASRec epoch 4/8:  20%|██        | 307/1500 [00:10<00:50, 23.56it/s, loss=1.21]
SASRec epoch 4/8:  21%|██        | 310/1500 [00:11<00:48, 24.63it/s, loss=1.21]
SASRec epoch 4/8:  21%|██        | 313/1500 [00:11<00:48, 24.31it/s, loss=1.21]
SASRec epoch 4/8:  21%|██        | 316/1500 [00:11<00:48, 24.47it/s, loss=1.21]
SASRec epoch 4/8:  21%|██▏       | 319/1500 [00:11<00:47, 24.83it/s, loss=1.21]
SASRec epoch 4/8:  21%|██▏       | 322/1500 [00:11<00:48, 24.10it/s, loss=1.21]
SASRec epoch 4/8:  22%|██▏       | 325/1500 [00:11<00:47, 24.60it/s, loss=1.21]
SASRec epoch 4/8:  22%|██▏       | 328/1500 [00:11<00:45, 25.52it/s, loss=1.21]
SASRec epoch 4/8:  22%|██▏       | 331/1500 [00:11<00:45, 25.92it/s, loss=1.21]
SASRec epoch 4/8:  22%|██▏       | 334/1500 [00:11<00:44, 26.23it/s, loss=1.21]
SASRec epoch 4/8:  22%|██▏       | 337/1500 [00:12<00:43, 26.46it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 340/1500 [00:12<00:42, 27.14it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 343/1500 [00:12<00:41, 27.65it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 346/1500 [00:12<00:41, 27.94it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 349/1500 [00:12<00:40, 28.17it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:12<00:40, 28.17it/s, loss=1.21]
SASRec epoch 4/8:  23%|██▎       | 352/1500 [00:12<00:41, 27.62it/s, loss=1.21]
SASRec epoch 4/8:  24%|██▎       | 355/1500 [00:12<00:40, 28.04it/s, loss=1.21]
SASRec epoch 4/8:  24%|██▍       | 358/1500 [00:12<00:40, 28.40it/s, loss=1.21]
SASRec epoch 4/8:  24%|██▍       | 361/1500 [00:12<00:40, 28.30it/s, loss=1.21]
SASRec epoch 4/8:  24%|██▍       | 364/1500 [00:13<00:39, 28.61it/s, loss=1.21]
SASRec epoch 4/8:  24%|██▍       | 367/1500 [00:13<00:39, 28.63it/s, loss=1.21]
SASRec epoch 4/8:  25%|██▍       | 370/1500 [00:13<00:39, 28.82it/s, loss=1.21]
SASRec epoch 4/8:  25%|██▍       | 373/1500 [00:13<00:39, 28.34it/s, loss=1.21]
SASRec epoch 4/8:  25%|██▌       | 376/1500 [00:13<00:39, 28.61it/s, loss=1.21]
SASRec epoch 4/8:  25%|██▌       | 379/1500 [00:13<00:39, 28.35it/s, loss=1.21]
SASRec epoch 4/8:  25%|██▌       | 382/1500 [00:13<00:39, 28.49it/s, loss=1.21]
SASRec epoch 4/8:  26%|██▌       | 385/1500 [00:13<00:38, 28.77it/s, loss=1.21]
SASRec epoch 4/8:  26%|██▌       | 388/1500 [00:13<00:38, 28.93it/s, loss=1.21]
SASRec epoch 4/8:  26%|██▌       | 391/1500 [00:13<00:38, 29.15it/s, loss=1.21]
SASRec epoch 4/8:  26%|██▋       | 394/1500 [00:14<00:37, 29.27it/s, loss=1.21]
SASRec epoch 4/8:  26%|██▋       | 397/1500 [00:14<00:37, 29.32it/s, loss=1.21]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:14<00:37, 29.18it/s, loss=1.21]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:14<00:37, 29.18it/s, loss=1.22]
SASRec epoch 4/8:  27%|██▋       | 403/1500 [00:14<00:38, 28.44it/s, loss=1.22]
SASRec epoch 4/8:  27%|██▋       | 406/1500 [00:14<00:38, 28.50it/s, loss=1.22]
SASRec epoch 4/8:  27%|██▋       | 409/1500 [00:14<00:37, 28.78it/s, loss=1.22]
SASRec epoch 4/8:  27%|██▋       | 412/1500 [00:14<00:37, 28.86it/s, loss=1.22]
SASRec epoch 4/8:  28%|██▊       | 415/1500 [00:14<00:37, 28.98it/s, loss=1.22]
SASRec epoch 4/8:  28%|██▊       | 418/1500 [00:14<00:37, 28.93it/s, loss=1.22]
SASRec epoch 4/8:  28%|██▊       | 421/1500 [00:15<00:37, 29.06it/s, loss=1.22]
SASRec epoch 4/8:  28%|██▊       | 424/1500 [00:15<00:37, 29.07it/s, loss=1.22]
SASRec epoch 4/8:  28%|██▊       | 427/1500 [00:15<00:37, 28.99it/s, loss=1.22]
SASRec epoch 4/8:  29%|██▊       | 430/1500 [00:15<00:36, 29.04it/s, loss=1.22]
SASRec epoch 4/8:  29%|██▉       | 433/1500 [00:15<00:36, 28.87it/s, loss=1.22]
SASRec epoch 4/8:  29%|██▉       | 436/1500 [00:15<00:37, 28.31it/s, loss=1.22]
SASRec epoch 4/8:  29%|██▉       | 439/1500 [00:15<00:37, 28.66it/s, loss=1.22]
SASRec epoch 4/8:  29%|██▉       | 442/1500 [00:15<00:36, 28.79it/s, loss=1.22]
SASRec epoch 4/8:  30%|██▉       | 445/1500 [00:15<00:36, 28.67it/s, loss=1.22]
SASRec epoch 4/8:  30%|██▉       | 448/1500 [00:15<00:36, 28.71it/s, loss=1.22]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:16<00:36, 28.71it/s, loss=1.2]
SASRec epoch 4/8:  30%|███       | 451/1500 [00:16<00:37, 28.07it/s, loss=1.2]
SASRec epoch 4/8:  30%|███       | 454/1500 [00:16<00:36, 28.52it/s, loss=1.2]
SASRec epoch 4/8:  30%|███       | 457/1500 [00:16<00:36, 28.76it/s, loss=1.2]
SASRec epoch 4/8:  31%|███       | 460/1500 [00:16<00:36, 28.61it/s, loss=1.2]
SASRec epoch 4/8:  31%|███       | 463/1500 [00:16<00:36, 28.64it/s, loss=1.2]
SASRec epoch 4/8:  31%|███       | 466/1500 [00:16<00:36, 28.29it/s, loss=1.2]
SASRec epoch 4/8:  31%|███▏      | 469/1500 [00:16<00:36, 28.59it/s, loss=1.2]
SASRec epoch 4/8:  31%|███▏      | 472/1500 [00:16<00:35, 28.75it/s, loss=1.2]
SASRec epoch 4/8:  32%|███▏      | 475/1500 [00:16<00:35, 28.74it/s, loss=1.2]
SASRec epoch 4/8:  32%|███▏      | 478/1500 [00:17<00:35, 28.91it/s, loss=1.2]
SASRec epoch 4/8:  32%|███▏      | 481/1500 [00:17<00:35, 29.10it/s, loss=1.2]
SASRec epoch 4/8:  32%|███▏      | 484/1500 [00:17<00:34, 29.15it/s, loss=1.2]
SASRec epoch 4/8:  32%|███▏      | 487/1500 [00:17<00:34, 29.17it/s, loss=1.2]
SASRec epoch 4/8:  33%|███▎      | 490/1500 [00:17<00:34, 29.22it/s, loss=1.2]
SASRec epoch 4/8:  33%|███▎      | 493/1500 [00:17<00:34, 28.95it/s, loss=1.2]
SASRec epoch 4/8:  33%|███▎      | 496/1500 [00:17<00:35, 28.06it/s, loss=1.2]
SASRec epoch 4/8:  33%|███▎      | 499/1500 [00:17<00:35, 28.44it/s, loss=1.2]
SASRec epoch 4/8:  33%|███▎      | 500/1500 [00:17<00:35, 28.44it/s, loss=1.21]
SASRec epoch 4/8:  33%|███▎      | 502/1500 [00:17<00:35, 27.83it/s, loss=1.21]
SASRec epoch 4/8:  34%|███▎      | 505/1500 [00:17<00:35, 27.83it/s, loss=1.21]
SASRec epoch 4/8:  34%|███▍      | 508/1500 [00:18<00:35, 28.18it/s, loss=1.21]
SASRec epoch 4/8:  34%|███▍      | 511/1500 [00:18<00:34, 28.36it/s, loss=1.21]
SASRec epoch 4/8:  34%|███▍      | 514/1500 [00:18<00:34, 28.53it/s, loss=1.21]
SASRec epoch 4/8:  34%|███▍      | 517/1500 [00:18<00:34, 28.67it/s, loss=1.21]
SASRec epoch 4/8:  35%|███▍      | 520/1500 [00:18<00:34, 28.68it/s, loss=1.21]
SASRec epoch 4/8:  35%|███▍      | 523/1500 [00:18<00:33, 28.88it/s, loss=1.21]
SASRec epoch 4/8:  35%|███▌      | 526/1500 [00:18<00:34, 28.61it/s, loss=1.21]
SASRec epoch 4/8:  35%|███▌      | 529/1500 [00:18<00:33, 28.75it/s, loss=1.21]
SASRec epoch 4/8:  35%|███▌      | 532/1500 [00:18<00:33, 28.89it/s, loss=1.21]
SASRec epoch 4/8:  36%|███▌      | 535/1500 [00:18<00:33, 28.90it/s, loss=1.21]
SASRec epoch 4/8:  36%|███▌      | 538/1500 [00:19<00:33, 28.86it/s, loss=1.21]
SASRec epoch 4/8:  36%|███▌      | 541/1500 [00:19<00:33, 28.98it/s, loss=1.21]
SASRec epoch 4/8:  36%|███▋      | 544/1500 [00:19<00:32, 29.08it/s, loss=1.21]
SASRec epoch 4/8:  36%|███▋      | 547/1500 [00:19<00:32, 28.99it/s, loss=1.21]
SASRec epoch 4/8:  37%|███▋      | 550/1500 [00:19<00:32, 29.01it/s, loss=1.21]
SASRec epoch 4/8:  37%|███▋      | 550/1500 [00:19<00:32, 29.01it/s, loss=1.2]
SASRec epoch 4/8:  37%|███▋      | 553/1500 [00:19<00:33, 28.67it/s, loss=1.2]
SASRec epoch 4/8:  37%|███▋      | 556/1500 [00:19<00:33, 28.44it/s, loss=1.2]
SASRec epoch 4/8:  37%|███▋      | 559/1500 [00:19<00:32, 28.60it/s, loss=1.2]
SASRec epoch 4/8:  37%|███▋      | 562/1500 [00:19<00:32, 28.87it/s, loss=1.2]
SASRec epoch 4/8:  38%|███▊      | 565/1500 [00:20<00:32, 29.03it/s, loss=1.2]
SASRec epoch 4/8:  38%|███▊      | 568/1500 [00:20<00:31, 29.14it/s, loss=1.2]
SASRec epoch 4/8:  38%|███▊      | 571/1500 [00:20<00:31, 29.32it/s, loss=1.2]
SASRec epoch 4/8:  38%|███▊      | 574/1500 [00:20<00:31, 29.26it/s, loss=1.2]
SASRec epoch 4/8:  38%|███▊      | 577/1500 [00:20<00:31, 29.11it/s, loss=1.2]
SASRec epoch 4/8:  39%|███▊      | 580/1500 [00:20<00:31, 28.96it/s, loss=1.2]
SASRec epoch 4/8:  39%|███▉      | 583/1500 [00:20<00:31, 29.09it/s, loss=1.2]
SASRec epoch 4/8:  39%|███▉      | 586/1500 [00:20<00:31, 28.77it/s, loss=1.2]
SASRec epoch 4/8:  39%|███▉      | 589/1500 [00:20<00:31, 28.92it/s, loss=1.2]
SASRec epoch 4/8:  39%|███▉      | 592/1500 [00:20<00:31, 29.17it/s, loss=1.2]
SASRec epoch 4/8:  40%|███▉      | 595/1500 [00:21<00:30, 29.37it/s, loss=1.2]
SASRec epoch 4/8:  40%|███▉      | 598/1500 [00:21<00:30, 29.39it/s, loss=1.2]
SASRec epoch 4/8:  40%|████      | 600/1500 [00:21<00:30, 29.39it/s, loss=1.19]
SASRec epoch 4/8:  40%|████      | 601/1500 [00:21<00:31, 28.50it/s, loss=1.19]
SASRec epoch 4/8:  40%|████      | 604/1500 [00:21<00:31, 28.70it/s, loss=1.19]
SASRec epoch 4/8:  40%|████      | 607/1500 [00:21<00:31, 28.70it/s, loss=1.19]
SASRec epoch 4/8:  41%|████      | 610/1500 [00:21<00:31, 28.70it/s, loss=1.19]
SASRec epoch 4/8:  41%|████      | 613/1500 [00:21<00:30, 28.64it/s, loss=1.19]
SASRec epoch 4/8:  41%|████      | 616/1500 [00:21<00:31, 28.51it/s, loss=1.19]
SASRec epoch 4/8:  41%|████▏     | 619/1500 [00:21<00:30, 28.43it/s, loss=1.19]
SASRec epoch 4/8:  41%|████▏     | 622/1500 [00:22<00:30, 28.61it/s, loss=1.19]
SASRec epoch 4/8:  42%|████▏     | 625/1500 [00:22<00:30, 28.25it/s, loss=1.19]
SASRec epoch 4/8:  42%|████▏     | 628/1500 [00:22<00:31, 27.51it/s, loss=1.19]
SASRec epoch 4/8:  42%|████▏     | 631/1500 [00:22<00:31, 27.42it/s, loss=1.19]
SASRec epoch 4/8:  42%|████▏     | 634/1500 [00:22<00:31, 27.13it/s, loss=1.19]
SASRec epoch 4/8:  42%|████▏     | 637/1500 [00:22<00:33, 26.05it/s, loss=1.19]
SASRec epoch 4/8:  43%|████▎     | 640/1500 [00:22<00:32, 26.09it/s, loss=1.19]
SASRec epoch 4/8:  43%|████▎     | 643/1500 [00:22<00:33, 25.29it/s, loss=1.19]
SASRec epoch 4/8:  43%|████▎     | 646/1500 [00:22<00:33, 25.28it/s, loss=1.19]
SASRec epoch 4/8:  43%|████▎     | 649/1500 [00:23<00:32, 26.09it/s, loss=1.19]
SASRec epoch 4/8:  43%|████▎     | 650/1500 [00:23<00:32, 26.09it/s, loss=1.2]
SASRec epoch 4/8:  43%|████▎     | 652/1500 [00:23<00:32, 26.20it/s, loss=1.2]
SASRec epoch 4/8:  44%|████▎     | 655/1500 [00:23<00:31, 26.73it/s, loss=1.2]
SASRec epoch 4/8:  44%|████▍     | 658/1500 [00:23<00:31, 27.06it/s, loss=1.2]
SASRec epoch 4/8:  44%|████▍     | 661/1500 [00:23<00:30, 27.09it/s, loss=1.2]
SASRec epoch 4/8:  44%|████▍     | 664/1500 [00:23<00:30, 27.28it/s, loss=1.2]
SASRec epoch 4/8:  44%|████▍     | 667/1500 [00:23<00:31, 26.43it/s, loss=1.2]
SASRec epoch 4/8:  45%|████▍     | 670/1500 [00:23<00:30, 27.09it/s, loss=1.2]
SASRec epoch 4/8:  45%|████▍     | 673/1500 [00:23<00:30, 27.45it/s, loss=1.2]
SASRec epoch 4/8:  45%|████▌     | 676/1500 [00:24<00:30, 27.15it/s, loss=1.2]
SASRec epoch 4/8:  45%|████▌     | 679/1500 [00:24<00:29, 27.58it/s, loss=1.2]
SASRec epoch 4/8:  45%|████▌     | 682/1500 [00:24<00:29, 28.05it/s, loss=1.2]
SASRec epoch 4/8:  46%|████▌     | 685/1500 [00:24<00:28, 28.27it/s, loss=1.2]
SASRec epoch 4/8:  46%|████▌     | 688/1500 [00:24<00:28, 28.32it/s, loss=1.2]
SASRec epoch 4/8:  46%|████▌     | 691/1500 [00:24<00:28, 28.57it/s, loss=1.2]
SASRec epoch 4/8:  46%|████▋     | 694/1500 [00:24<00:28, 28.44it/s, loss=1.2]
SASRec epoch 4/8:  46%|████▋     | 697/1500 [00:24<00:28, 27.73it/s, loss=1.2]
SASRec epoch 4/8:  47%|████▋     | 700/1500 [00:24<00:29, 26.98it/s, loss=1.2]
SASRec epoch 4/8:  47%|████▋     | 700/1500 [00:24<00:29, 26.98it/s, loss=1.19]
SASRec epoch 4/8:  47%|████▋     | 703/1500 [00:25<00:29, 27.29it/s, loss=1.19]
SASRec epoch 4/8:  47%|████▋     | 706/1500 [00:25<00:28, 27.46it/s, loss=1.19]
SASRec epoch 4/8:  47%|████▋     | 709/1500 [00:25<00:29, 26.89it/s, loss=1.19]
SASRec epoch 4/8:  47%|████▋     | 712/1500 [00:25<00:28, 27.21it/s, loss=1.19]
SASRec epoch 4/8:  48%|████▊     | 715/1500 [00:25<00:28, 27.44it/s, loss=1.19]

[SASRec] epoch 4/8 loss=1.1935

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 5/8:   0%|          | 3/1500 [00:00<00:51, 29.00it/s]
SASRec epoch 5/8:   0%|          | 6/1500 [00:00<00:51, 28.83it/s]
SASRec epoch 5/8:   1%|          | 9/1500 [00:00<00:51, 28.84it/s]
SASRec epoch 5/8:   1%|          | 12/1500 [00:00<00:50, 29.24it/s]
SASRec epoch 5/8:   1%|          | 15/1500 [00:00<00:51, 29.11it/s]
SASRec epoch 5/8:   1%|          | 18/1500 [00:00<00:52, 28.37it/s]
SASRec epoch 5/8:   1%|▏         | 21/1500 [00:00<00:52, 28.06it/s]
SASRec epoch 5/8:   2%|▏         | 24/1500 [00:00<00:54, 27.18it/s]
SASRec epoch 5/8:   2%|▏         | 27/1500 [00:00<00:54, 26.90it/s]
SASRec epoch 5/8:   2%|▏         | 30/1500 [00:01<00:54, 27.17it/s]
SASRec epoch 5/8:   2%|▏         | 33/1500 [00:01<00:53, 27.41it/s]
SASRec epoch 5/8:   2%|▏         | 36/1500 [00:01<00:53, 27.55it/s]
SASRec epoch 5/8:   3%|▎         | 39/1500 [00:01<00:53, 27.50it/s]
SASRec epoch 5/8:   3%|▎         | 42/1500 [00:01<00:52, 27.62it/s]
SASRec epoch 5/8:   3%|▎         | 45/1500 [00:01<00:52, 27.64it/s]
SASRec epoch 5/8:   3%|▎         | 48/1500 [00:01<00:52, 27.66it/s]
SASRec epoch 5/8:   3%|▎         | 50/1500 [00:01<00:52, 27.66it/s, loss=1.16]
SASRec epoch 5/8:   3%|▎         | 51/1500 [00:01<00:53, 27.25it/s, loss=1.16]
SASRec epoch 5/8:   4%|▎         | 54/1500 [00:01<00:52, 27.44it/s, loss=1.16]
SASRec epoch 5/8:   4%|▍         | 57/1500 [00:02<00:52, 27.54it/s, loss=1.16]
SASRec epoch 5/8:   4%|▍         | 60/1500 [00:02<00:52, 27.63it/s, loss=1.16]
SASRec epoch 5/8:   4%|▍         | 63/1500 [00:02<00:51, 27.68it/s, loss=1.16]
SASRec epoch 5/8:   4%|▍         | 66/1500 [00:02<00:51, 27.73it/s, loss=1.16]
SASRec epoch 5/8:   5%|▍         | 69/1500 [00:02<00:51, 27.59it/s, loss=1.16]
SASRec epoch 5/8:   5%|▍         | 72/1500 [00:02<00:51, 27.96it/s, loss=1.16]
SASRec epoch 5/8:   5%|▌         | 75/1500 [00:02<00:50, 28.45it/s, loss=1.16]
SASRec epoch 5/8:   5%|▌         | 78/1500 [00:02<00:50, 28.05it/s, loss=1.16]
SASRec epoch 5/8:   5%|▌         | 81/1500 [00:02<00:50, 28.13it/s, loss=1.16]
SASRec epoch 5/8:   6%|▌         | 84/1500 [00:03<00:51, 27.62it/s, loss=1.16]
SASRec epoch 5/8:   6%|▌         | 87/1500 [00:03<00:50, 27.86it/s, loss=1.16]
SASRec epoch 5/8:   6%|▌         | 90/1500 [00:03<00:50, 28.07it/s, loss=1.16]
SASRec epoch 5/8:   6%|▌         | 93/1500 [00:03<00:49, 28.29it/s, loss=1.16]
SASRec epoch 5/8:   6%|▋         | 96/1500 [00:03<00:50, 27.78it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 99/1500 [00:03<00:51, 27.15it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:03<00:51, 27.15it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 102/1500 [00:03<00:52, 26.49it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 105/1500 [00:03<00:53, 26.21it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 108/1500 [00:03<00:54, 25.50it/s, loss=1.16]
SASRec epoch 5/8:   7%|▋         | 111/1500 [00:04<00:54, 25.65it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 114/1500 [00:04<00:56, 24.42it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 117/1500 [00:04<00:54, 25.29it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 120/1500 [00:04<00:52, 26.21it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 123/1500 [00:04<00:51, 26.70it/s, loss=1.16]
SASRec epoch 5/8:   8%|▊         | 126/1500 [00:04<00:50, 27.21it/s, loss=1.16]
SASRec epoch 5/8:   9%|▊         | 129/1500 [00:04<00:49, 27.68it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 132/1500 [00:04<00:48, 28.08it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 135/1500 [00:04<00:48, 28.18it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 138/1500 [00:05<00:48, 28.02it/s, loss=1.16]
SASRec epoch 5/8:   9%|▉         | 141/1500 [00:05<00:48, 28.09it/s, loss=1.16]
SASRec epoch 5/8:  10%|▉         | 144/1500 [00:05<00:49, 27.62it/s, loss=1.16]
SASRec epoch 5/8:  10%|▉         | 147/1500 [00:05<00:49, 27.22it/s, loss=1.16]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:05<00:49, 27.17it/s, loss=1.16]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:05<00:49, 27.17it/s, loss=1.17]
SASRec epoch 5/8:  10%|█         | 153/1500 [00:05<00:50, 26.79it/s, loss=1.17]
SASRec epoch 5/8:  10%|█         | 156/1500 [00:05<00:49, 27.10it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 159/1500 [00:05<00:50, 26.72it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 162/1500 [00:05<00:52, 25.65it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 165/1500 [00:06<00:52, 25.23it/s, loss=1.17]
SASRec epoch 5/8:  11%|█         | 168/1500 [00:06<00:54, 24.30it/s, loss=1.17]
SASRec epoch 5/8:  11%|█▏        | 171/1500 [00:06<00:52, 25.18it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 174/1500 [00:06<00:52, 25.41it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 177/1500 [00:06<00:51, 25.87it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 180/1500 [00:06<00:52, 25.25it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 183/1500 [00:06<00:50, 26.32it/s, loss=1.17]
SASRec epoch 5/8:  12%|█▏        | 186/1500 [00:06<00:48, 26.95it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 190/1500 [00:06<00:46, 28.29it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 193/1500 [00:07<00:45, 28.53it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 196/1500 [00:07<00:45, 28.72it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 199/1500 [00:07<00:45, 28.78it/s, loss=1.17]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.78it/s, loss=1.16]
SASRec epoch 5/8:  13%|█▎        | 202/1500 [00:07<00:45, 28.44it/s, loss=1.16]
SASRec epoch 5/8:  14%|█▎        | 205/1500 [00:07<00:45, 28.55it/s, loss=1.16]
SASRec epoch 5/8:  14%|█▍        | 208/1500 [00:07<00:44, 28.86it/s, loss=1.16]
SASRec epoch 5/8:  14%|█▍        | 211/1500 [00:07<00:44, 28.99it/s, loss=1.16]
SASRec epoch 5/8:  14%|█▍        | 214/1500 [00:07<00:44, 29.06it/s, loss=1.16]
SASRec epoch 5/8:  14%|█▍        | 217/1500 [00:07<00:44, 29.03it/s, loss=1.16]
SASRec epoch 5/8:  15%|█▍        | 220/1500 [00:08<00:43, 29.29it/s, loss=1.16]
SASRec epoch 5/8:  15%|█▍        | 223/1500 [00:08<00:43, 29.18it/s, loss=1.16]
SASRec epoch 5/8:  15%|█▌        | 226/1500 [00:08<00:43, 29.18it/s, loss=1.16]
SASRec epoch 5/8:  15%|█▌        | 229/1500 [00:08<00:43, 29.13it/s, loss=1.16]
SASRec epoch 5/8:  15%|█▌        | 232/1500 [00:08<00:43, 29.19it/s, loss=1.16]
SASRec epoch 5/8:  16%|█▌        | 235/1500 [00:08<00:43, 29.40it/s, loss=1.16]
SASRec epoch 5/8:  16%|█▌        | 239/1500 [00:08<00:42, 29.89it/s, loss=1.16]
SASRec epoch 5/8:  16%|█▌        | 242/1500 [00:08<00:42, 29.46it/s, loss=1.16]
SASRec epoch 5/8:  16%|█▋        | 245/1500 [00:08<00:42, 29.59it/s, loss=1.16]
SASRec epoch 5/8:  17%|█▋        | 248/1500 [00:08<00:42, 29.49it/s, loss=1.16]
SASRec epoch 5/8:  17%|█▋        | 250/1500 [00:09<00:42, 29.49it/s, loss=1.15]
SASRec epoch 5/8:  17%|█▋        | 251/1500 [00:09<00:43, 28.53it/s, loss=1.15]
SASRec epoch 5/8:  17%|█▋        | 254/1500 [00:09<00:43, 28.54it/s, loss=1.15]
SASRec epoch 5/8:  17%|█▋        | 257/1500 [00:09<00:43, 28.37it/s, loss=1.15]
SASRec epoch 5/8:  17%|█▋        | 261/1500 [00:09<00:42, 29.23it/s, loss=1.15]
SASRec epoch 5/8:  18%|█▊        | 264/1500 [00:09<00:42, 29.12it/s, loss=1.15]
SASRec epoch 5/8:  18%|█▊        | 267/1500 [00:09<00:42, 29.11it/s, loss=1.15]
SASRec epoch 5/8:  18%|█▊        | 270/1500 [00:09<00:42, 29.13it/s, loss=1.15]
SASRec epoch 5/8:  18%|█▊        | 273/1500 [00:09<00:41, 29.25it/s, loss=1.15]
SASRec epoch 5/8:  18%|█▊        | 276/1500 [00:09<00:41, 29.46it/s, loss=1.15]
SASRec epoch 5/8:  19%|█▊        | 280/1500 [00:10<00:40, 29.94it/s, loss=1.15]
SASRec epoch 5/8:  19%|█▉        | 283/1500 [00:10<00:40, 29.79it/s, loss=1.15]
SASRec epoch 5/8:  19%|█▉        | 287/1500 [00:10<00:40, 30.16it/s, loss=1.15]
SASRec epoch 5/8:  19%|█▉        | 291/1500 [00:10<00:40, 29.87it/s, loss=1.15]
SASRec epoch 5/8:  20%|█▉        | 294/1500 [00:10<00:40, 29.84it/s, loss=1.15]
SASRec epoch 5/8:  20%|█▉        | 297/1500 [00:10<00:40, 29.83it/s, loss=1.15]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:10<00:40, 29.59it/s, loss=1.15]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:10<00:40, 29.59it/s, loss=1.14]
SASRec epoch 5/8:  20%|██        | 303/1500 [00:10<00:41, 28.97it/s, loss=1.14]
SASRec epoch 5/8:  20%|██        | 306/1500 [00:10<00:41, 29.10it/s, loss=1.14]
SASRec epoch 5/8:  21%|██        | 309/1500 [00:11<00:41, 28.78it/s, loss=1.14]
SASRec epoch 5/8:  21%|██        | 312/1500 [00:11<00:41, 28.84it/s, loss=1.14]
SASRec epoch 5/8:  21%|██        | 315/1500 [00:11<00:40, 29.01it/s, loss=1.14]
SASRec epoch 5/8:  21%|██        | 318/1500 [00:11<00:40, 28.96it/s, loss=1.14]
SASRec epoch 5/8:  21%|██▏       | 321/1500 [00:11<00:41, 28.60it/s, loss=1.14]
SASRec epoch 5/8:  22%|██▏       | 324/1500 [00:11<00:40, 28.80it/s, loss=1.14]
SASRec epoch 5/8:  22%|██▏       | 327/1500 [00:11<00:40, 29.02it/s, loss=1.14]
SASRec epoch 5/8:  22%|██▏       | 330/1500 [00:11<00:39, 29.29it/s, loss=1.14]
SASRec epoch 5/8:  22%|██▏       | 333/1500 [00:11<00:39, 29.20it/s, loss=1.14]
SASRec epoch 5/8:  22%|██▏       | 336/1500 [00:11<00:39, 29.17it/s, loss=1.14]
SASRec epoch 5/8:  23%|██▎       | 339/1500 [00:12<00:39, 29.06it/s, loss=1.14]
SASRec epoch 5/8:  23%|██▎       | 342/1500 [00:12<00:39, 29.00it/s, loss=1.14]
SASRec epoch 5/8:  23%|██▎       | 345/1500 [00:12<00:40, 28.79it/s, loss=1.14]
SASRec epoch 5/8:  23%|██▎       | 348/1500 [00:12<00:40, 28.78it/s, loss=1.14]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:12<00:39, 28.78it/s, loss=1.15]
SASRec epoch 5/8:  23%|██▎       | 351/1500 [00:12<00:42, 27.04it/s, loss=1.15]
SASRec epoch 5/8:  24%|██▎       | 354/1500 [00:12<00:41, 27.48it/s, loss=1.15]
SASRec epoch 5/8:  24%|██▍       | 357/1500 [00:12<00:40, 27.97it/s, loss=1.15]
SASRec epoch 5/8:  24%|██▍       | 360/1500 [00:12<00:40, 28.16it/s, loss=1.15]
SASRec epoch 5/8:  24%|██▍       | 363/1500 [00:12<00:40, 28.30it/s, loss=1.15]
SASRec epoch 5/8:  24%|██▍       | 366/1500 [00:13<00:40, 28.33it/s, loss=1.15]
SASRec epoch 5/8:  25%|██▍       | 369/1500 [00:13<00:39, 28.52it/s, loss=1.15]
SASRec epoch 5/8:  25%|██▍       | 372/1500 [00:13<00:39, 28.67it/s, loss=1.15]
SASRec epoch 5/8:  25%|██▌       | 375/1500 [00:13<00:39, 28.63it/s, loss=1.15]
SASRec epoch 5/8:  25%|██▌       | 378/1500 [00:13<00:39, 28.40it/s, loss=1.15]
SASRec epoch 5/8:  25%|██▌       | 381/1500 [00:13<00:39, 28.27it/s, loss=1.15]
SASRec epoch 5/8:  26%|██▌       | 384/1500 [00:13<00:39, 28.56it/s, loss=1.15]
SASRec epoch 5/8:  26%|██▌       | 387/1500 [00:13<00:38, 28.60it/s, loss=1.15]
SASRec epoch 5/8:  26%|██▌       | 390/1500 [00:13<00:38, 28.71it/s, loss=1.15]
SASRec epoch 5/8:  26%|██▌       | 393/1500 [00:14<00:38, 28.96it/s, loss=1.15]
SASRec epoch 5/8:  26%|██▋       | 396/1500 [00:14<00:38, 28.81it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 399/1500 [00:14<00:38, 28.78it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 400/1500 [00:14<00:38, 28.78it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 402/1500 [00:14<00:39, 28.01it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 405/1500 [00:14<00:38, 28.33it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 408/1500 [00:14<00:38, 28.60it/s, loss=1.15]
SASRec epoch 5/8:  27%|██▋       | 411/1500 [00:14<00:39, 27.89it/s, loss=1.15]
SASRec epoch 5/8:  28%|██▊       | 415/1500 [00:14<00:37, 28.90it/s, loss=1.15]
SASRec epoch 5/8:  28%|██▊       | 418/1500 [00:14<00:37, 29.05it/s, loss=1.15]
SASRec epoch 5/8:  28%|██▊       | 421/1500 [00:14<00:36, 29.17it/s, loss=1.15]
SASRec epoch 5/8:  28%|██▊       | 424/1500 [00:15<00:36, 29.15it/s, loss=1.15]
SASRec epoch 5/8:  28%|██▊       | 427/1500 [00:15<00:36, 29.12it/s, loss=1.15]
SASRec epoch 5/8:  29%|██▊       | 430/1500 [00:15<00:36, 28.95it/s, loss=1.15]
SASRec epoch 5/8:  29%|██▉       | 433/1500 [00:15<00:36, 28.85it/s, loss=1.15]
SASRec epoch 5/8:  29%|██▉       | 436/1500 [00:15<00:36, 28.94it/s, loss=1.15]
SASRec epoch 5/8:  29%|██▉       | 439/1500 [00:15<00:37, 28.26it/s, loss=1.15]
SASRec epoch 5/8:  29%|██▉       | 442/1500 [00:15<00:36, 28.68it/s, loss=1.15]
SASRec epoch 5/8:  30%|██▉       | 445/1500 [00:15<00:36, 28.97it/s, loss=1.15]
SASRec epoch 5/8:  30%|██▉       | 448/1500 [00:15<00:36, 28.63it/s, loss=1.15]
SASRec epoch 5/8:  30%|███       | 450/1500 [00:15<00:36, 28.63it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 451/1500 [00:16<00:37, 28.10it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 454/1500 [00:16<00:36, 28.33it/s, loss=1.14]
SASRec epoch 5/8:  30%|███       | 457/1500 [00:16<00:36, 28.55it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 460/1500 [00:16<00:36, 28.74it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 463/1500 [00:16<00:35, 28.90it/s, loss=1.14]
SASRec epoch 5/8:  31%|███       | 466/1500 [00:16<00:35, 28.91it/s, loss=1.14]
SASRec epoch 5/8:  31%|███▏      | 469/1500 [00:16<00:35, 28.72it/s, loss=1.14]
SASRec epoch 5/8:  31%|███▏      | 472/1500 [00:16<00:36, 28.15it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 475/1500 [00:16<00:38, 26.48it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 478/1500 [00:17<00:38, 26.62it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 481/1500 [00:17<00:38, 26.67it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 484/1500 [00:17<00:37, 26.83it/s, loss=1.14]
SASRec epoch 5/8:  32%|███▏      | 487/1500 [00:17<00:37, 27.07it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 490/1500 [00:17<00:37, 27.13it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 493/1500 [00:17<00:37, 26.76it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 496/1500 [00:17<00:39, 25.59it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 499/1500 [00:17<00:39, 25.04it/s, loss=1.14]
SASRec epoch 5/8:  33%|███▎      | 500/1500 [00:17<00:39, 25.04it/s, loss=1.15]
SASRec epoch 5/8:  33%|███▎      | 502/1500 [00:17<00:38, 25.77it/s, loss=1.15]
SASRec epoch 5/8:  34%|███▎      | 505/1500 [00:18<00:37, 26.58it/s, loss=1.15]
SASRec epoch 5/8:  34%|███▍      | 508/1500 [00:18<00:36, 27.14it/s, loss=1.15]
SASRec epoch 5/8:  34%|███▍      | 511/1500 [00:18<00:35, 27.56it/s, loss=1.15]
SASRec epoch 5/8:  34%|███▍      | 514/1500 [00:18<00:35, 27.77it/s, loss=1.15]
SASRec epoch 5/8:  34%|███▍      | 517/1500 [00:18<00:34, 28.12it/s, loss=1.15]
SASRec epoch 5/8:  35%|███▍      | 520/1500 [00:18<00:34, 28.53it/s, loss=1.15]
SASRec epoch 5/8:  35%|███▍      | 523/1500 [00:18<00:33, 28.79it/s, loss=1.15]
SASRec epoch 5/8:  35%|███▌      | 526/1500 [00:18<00:33, 28.96it/s, loss=1.15]
SASRec epoch 5/8:  35%|███▌      | 529/1500 [00:18<00:34, 28.55it/s, loss=1.15]
SASRec epoch 5/8:  35%|███▌      | 532/1500 [00:18<00:34, 28.37it/s, loss=1.15]
SASRec epoch 5/8:  36%|███▌      | 535/1500 [00:19<00:33, 28.52it/s, loss=1.15]
SASRec epoch 5/8:  36%|███▌      | 538/1500 [00:19<00:33, 28.70it/s, loss=1.15]
SASRec epoch 5/8:  36%|███▌      | 541/1500 [00:19<00:33, 28.67it/s, loss=1.15]
SASRec epoch 5/8:  36%|███▋      | 544/1500 [00:19<00:33, 28.31it/s, loss=1.15]
SASRec epoch 5/8:  36%|███▋      | 547/1500 [00:19<00:34, 27.27it/s, loss=1.15]
SASRec epoch 5/8:  37%|███▋      | 550/1500 [00:19<00:34, 27.34it/s, loss=1.15]
SASRec epoch 5/8:  37%|███▋      | 550/1500 [00:19<00:34, 27.34it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 553/1500 [00:19<00:34, 27.49it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 556/1500 [00:19<00:33, 27.89it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 559/1500 [00:19<00:33, 28.07it/s, loss=1.13]
SASRec epoch 5/8:  37%|███▋      | 562/1500 [00:20<00:33, 27.66it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 565/1500 [00:20<00:33, 27.99it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 568/1500 [00:20<00:34, 27.19it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 571/1500 [00:20<00:35, 26.36it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 574/1500 [00:20<00:35, 25.92it/s, loss=1.13]
SASRec epoch 5/8:  38%|███▊      | 577/1500 [00:20<00:35, 26.16it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▊      | 580/1500 [00:20<00:34, 26.62it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 583/1500 [00:20<00:34, 26.97it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 586/1500 [00:20<00:33, 27.44it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 589/1500 [00:21<00:32, 27.87it/s, loss=1.13]
SASRec epoch 5/8:  39%|███▉      | 592/1500 [00:21<00:33, 27.44it/s, loss=1.13]
SASRec epoch 5/8:  40%|███▉      | 595/1500 [00:21<00:33, 27.35it/s, loss=1.13]
SASRec epoch 5/8:  40%|███▉      | 598/1500 [00:21<00:32, 27.44it/s, loss=1.13]
SASRec epoch 5/8:  40%|████      | 600/1500 [00:21<00:32, 27.44it/s, loss=1.15]
SASRec epoch 5/8:  40%|████      | 601/1500 [00:21<00:33, 26.67it/s, loss=1.15]
SASRec epoch 5/8:  40%|████      | 604/1500 [00:21<00:33, 26.74it/s, loss=1.15]
SASRec epoch 5/8:  40%|████      | 607/1500 [00:21<00:33, 26.80it/s, loss=1.15]
SASRec epoch 5/8:  41%|████      | 610/1500 [00:21<00:33, 26.56it/s, loss=1.15]
SASRec epoch 5/8:  41%|████      | 613/1500 [00:21<00:32, 26.90it/s, loss=1.15]
SASRec epoch 5/8:  41%|████      | 616/1500 [00:22<00:32, 26.92it/s, loss=1.15]
SASRec epoch 5/8:  41%|████▏     | 619/1500 [00:22<00:32, 26.70it/s, loss=1.15]
SASRec epoch 5/8:  41%|████▏     | 622/1500 [00:22<00:32, 27.08it/s, loss=1.15]
SASRec epoch 5/8:  42%|████▏     | 625/1500 [00:22<00:32, 26.75it/s, loss=1.15]
SASRec epoch 5/8:  42%|████▏     | 628/1500 [00:22<00:33, 26.31it/s, loss=1.15]
SASRec epoch 5/8:  42%|████▏     | 631/1500 [00:22<00:32, 26.65it/s, loss=1.15]
SASRec epoch 5/8:  42%|████▏     | 634/1500 [00:22<00:32, 26.60it/s, loss=1.15]
SASRec epoch 5/8:  42%|████▏     | 637/1500 [00:22<00:34, 25.37it/s, loss=1.15]
SASRec epoch 5/8:  43%|████▎     | 640/1500 [00:22<00:33, 25.81it/s, loss=1.15]
SASRec epoch 5/8:  43%|████▎     | 643/1500 [00:23<00:31, 26.92it/s, loss=1.15]
SASRec epoch 5/8:  43%|████▎     | 646/1500 [00:23<00:31, 27.50it/s, loss=1.15]
SASRec epoch 5/8:  43%|████▎     | 649/1500 [00:23<00:30, 27.96it/s, loss=1.15]
SASRec epoch 5/8:  43%|████▎     | 650/1500 [00:23<00:30, 27.96it/s, loss=1.13]
SASRec epoch 5/8:  43%|████▎     | 652/1500 [00:23<00:31, 27.09it/s, loss=1.13]
SASRec epoch 5/8:  44%|████▎     | 655/1500 [00:23<00:30, 27.61it/s, loss=1.13]
SASRec epoch 5/8:  44%|████▍     | 658/1500 [00:23<00:30, 27.98it/s, loss=1.13]
SASRec epoch 5/8:  44%|████▍     | 661/1500 [00:23<00:29, 28.43it/s, loss=1.13]
SASRec epoch 5/8:  44%|████▍     | 664/1500 [00:23<00:29, 28.70it/s, loss=1.13]
SASRec epoch 5/8:  44%|████▍     | 667/1500 [00:23<00:28, 28.88it/s, loss=1.13]
SASRec epoch 5/8:  45%|████▍     | 670/1500 [00:24<00:28, 29.06it/s, loss=1.13]
SASRec epoch 5/8:  45%|████▍     | 673/1500 [00:24<00:28, 29.17it/s, loss=1.13]
SASRec epoch 5/8:  45%|████▌     | 676/1500 [00:24<00:28, 29.01it/s, loss=1.13]
SASRec epoch 5/8:  45%|████▌     | 679/1500 [00:24<00:28, 28.89it/s, loss=1.13]
SASRec epoch 5/8:  45%|████▌     | 682/1500 [00:24<00:28, 28.37it/s, loss=1.13]
SASRec epoch 5/8:  46%|████▌     | 685/1500 [00:24<00:28, 28.40it/s, loss=1.13]
SASRec epoch 5/8:  46%|████▌     | 688/1500 [00:24<00:29, 27.96it/s, loss=1.13]
SASRec epoch 5/8:  46%|████▌     | 691/1500 [00:24<00:28, 28.04it/s, loss=1.13]
SASRec epoch 5/8:  46%|████▋     | 694/1500 [00:24<00:28, 28.47it/s, loss=1.13]
SASRec epoch 5/8:  46%|████▋     | 697/1500 [00:24<00:28, 28.68it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 700/1500 [00:25<00:27, 28.89it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 700/1500 [00:25<00:27, 28.89it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 703/1500 [00:25<00:28, 28.24it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 706/1500 [00:25<00:27, 28.43it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 709/1500 [00:25<00:27, 28.60it/s, loss=1.13]
SASRec epoch 5/8:  47%|████▋     | 712/1500 [00:25<00:28, 28.09it/s, loss=1.13]
SASRec epoch 5/8:  48%|████▊     | 715/1500 [00:25<00:27, 28.38it/s, loss=1.13]
SASRec epoch 5/8:  48%|████▊     | 718/1500 [00:25<00:27, 28.63it/s, loss=1.13]

[SASRec] epoch 5/8 loss=1.1326

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 6/8:   0%|          | 3/1500 [00:00<00:56, 26.29it/s]
SASRec epoch 6/8:   0%|          | 6/1500 [00:00<00:56, 26.33it/s]
SASRec epoch 6/8:   1%|          | 9/1500 [00:00<00:57, 25.86it/s]
SASRec epoch 6/8:   1%|          | 12/1500 [00:00<00:57, 25.67it/s]
SASRec epoch 6/8:   1%|          | 15/1500 [00:00<00:57, 25.73it/s]
SASRec epoch 6/8:   1%|          | 18/1500 [00:00<00:59, 24.74it/s]
SASRec epoch 6/8:   1%|▏         | 21/1500 [00:00<01:00, 24.32it/s]
SASRec epoch 6/8:   2%|▏         | 24/1500 [00:00<01:00, 24.45it/s]
SASRec epoch 6/8:   2%|▏         | 27/1500 [00:01<01:01, 24.13it/s]
SASRec epoch 6/8:   2%|▏         | 30/1500 [00:01<01:00, 24.38it/s]
SASRec epoch 6/8:   2%|▏         | 33/1500 [00:01<00:58, 24.90it/s]
SASRec epoch 6/8:   2%|▏         | 36/1500 [00:01<00:58, 25.02it/s]
SASRec epoch 6/8:   3%|▎         | 39/1500 [00:01<00:56, 25.71it/s]
SASRec epoch 6/8:   3%|▎         | 42/1500 [00:01<00:56, 26.03it/s]
SASRec epoch 6/8:   3%|▎         | 45/1500 [00:01<00:55, 26.10it/s]
SASRec epoch 6/8:   3%|▎         | 48/1500 [00:01<00:53, 27.05it/s]
SASRec epoch 6/8:   3%|▎         | 50/1500 [00:01<00:53, 27.05it/s, loss=1.1]
SASRec epoch 6/8:   3%|▎         | 51/1500 [00:01<00:53, 27.05it/s, loss=1.1]
SASRec epoch 6/8:   4%|▎         | 54/1500 [00:02<00:52, 27.66it/s, loss=1.1]
SASRec epoch 6/8:   4%|▍         | 57/1500 [00:02<00:51, 28.22it/s, loss=1.1]
SASRec epoch 6/8:   4%|▍         | 60/1500 [00:02<00:50, 28.44it/s, loss=1.1]
SASRec epoch 6/8:   4%|▍         | 63/1500 [00:02<00:50, 28.59it/s, loss=1.1]
SASRec epoch 6/8:   4%|▍         | 66/1500 [00:02<00:49, 28.78it/s, loss=1.1]
SASRec epoch 6/8:   5%|▍         | 69/1500 [00:02<00:49, 28.89it/s, loss=1.1]
SASRec epoch 6/8:   5%|▍         | 72/1500 [00:02<00:49, 28.68it/s, loss=1.1]
SASRec epoch 6/8:   5%|▌         | 75/1500 [00:02<00:49, 28.87it/s, loss=1.1]
SASRec epoch 6/8:   5%|▌         | 78/1500 [00:02<00:48, 29.04it/s, loss=1.1]
SASRec epoch 6/8:   5%|▌         | 81/1500 [00:03<00:48, 29.05it/s, loss=1.1]
SASRec epoch 6/8:   6%|▌         | 84/1500 [00:03<00:48, 29.03it/s, loss=1.1]
SASRec epoch 6/8:   6%|▌         | 87/1500 [00:03<00:48, 28.99it/s, loss=1.1]
SASRec epoch 6/8:   6%|▌         | 90/1500 [00:03<00:48, 28.95it/s, loss=1.1]
SASRec epoch 6/8:   6%|▌         | 93/1500 [00:03<00:48, 28.99it/s, loss=1.1]
SASRec epoch 6/8:   6%|▋         | 96/1500 [00:03<00:48, 29.07it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 99/1500 [00:03<00:48, 28.67it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:03<00:48, 28.67it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 102/1500 [00:03<00:50, 27.92it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 105/1500 [00:03<00:49, 28.12it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 108/1500 [00:03<00:50, 27.36it/s, loss=1.1]
SASRec epoch 6/8:   7%|▋         | 111/1500 [00:04<00:50, 27.64it/s, loss=1.1]
SASRec epoch 6/8:   8%|▊         | 114/1500 [00:04<00:49, 28.14it/s, loss=1.1]
SASRec epoch 6/8:   8%|▊         | 117/1500 [00:04<00:48, 28.50it/s, loss=1.1]
SASRec epoch 6/8:   8%|▊         | 120/1500 [00:04<00:48, 28.75it/s, loss=1.1]
SASRec epoch 6/8:   8%|▊         | 123/1500 [00:04<00:47, 29.04it/s, loss=1.1]
SASRec epoch 6/8:   8%|▊         | 126/1500 [00:04<00:46, 29.27it/s, loss=1.1]
SASRec epoch 6/8:   9%|▊         | 129/1500 [00:04<00:46, 29.42it/s, loss=1.1]
SASRec epoch 6/8:   9%|▉         | 132/1500 [00:04<00:46, 29.57it/s, loss=1.1]
SASRec epoch 6/8:   9%|▉         | 136/1500 [00:04<00:45, 30.01it/s, loss=1.1]
SASRec epoch 6/8:   9%|▉         | 139/1500 [00:05<00:46, 29.21it/s, loss=1.1]
SASRec epoch 6/8:   9%|▉         | 142/1500 [00:05<00:46, 29.23it/s, loss=1.1]
SASRec epoch 6/8:  10%|▉         | 145/1500 [00:05<00:46, 29.20it/s, loss=1.1]
SASRec epoch 6/8:  10%|▉         | 148/1500 [00:05<00:46, 29.28it/s, loss=1.1]
SASRec epoch 6/8:  10%|█         | 150/1500 [00:05<00:46, 29.28it/s, loss=1.11]
SASRec epoch 6/8:  10%|█         | 151/1500 [00:05<00:47, 28.53it/s, loss=1.11]
SASRec epoch 6/8:  10%|█         | 154/1500 [00:05<00:46, 28.85it/s, loss=1.11]
SASRec epoch 6/8:  10%|█         | 157/1500 [00:05<00:46, 29.06it/s, loss=1.11]
SASRec epoch 6/8:  11%|█         | 160/1500 [00:05<00:45, 29.21it/s, loss=1.11]
SASRec epoch 6/8:  11%|█         | 164/1500 [00:05<00:44, 29.75it/s, loss=1.11]
SASRec epoch 6/8:  11%|█         | 167/1500 [00:05<00:45, 29.42it/s, loss=1.11]
SASRec epoch 6/8:  11%|█▏        | 170/1500 [00:06<00:45, 29.39it/s, loss=1.11]
SASRec epoch 6/8:  12%|█▏        | 173/1500 [00:06<00:44, 29.54it/s, loss=1.11]
SASRec epoch 6/8:  12%|█▏        | 176/1500 [00:06<00:44, 29.44it/s, loss=1.11]
SASRec epoch 6/8:  12%|█▏        | 179/1500 [00:06<00:44, 29.38it/s, loss=1.11]
SASRec epoch 6/8:  12%|█▏        | 182/1500 [00:06<00:44, 29.41it/s, loss=1.11]
SASRec epoch 6/8:  12%|█▏        | 185/1500 [00:06<00:44, 29.27it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 188/1500 [00:06<00:45, 29.06it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 191/1500 [00:06<00:45, 28.87it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 194/1500 [00:06<00:45, 28.92it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 197/1500 [00:07<00:45, 28.78it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.44it/s, loss=1.11]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.44it/s, loss=1.09]
SASRec epoch 6/8:  14%|█▎        | 203/1500 [00:07<00:45, 28.23it/s, loss=1.09]
SASRec epoch 6/8:  14%|█▎        | 206/1500 [00:07<00:45, 28.54it/s, loss=1.09]
SASRec epoch 6/8:  14%|█▍        | 209/1500 [00:07<00:44, 28.73it/s, loss=1.09]
SASRec epoch 6/8:  14%|█▍        | 212/1500 [00:07<00:44, 29.03it/s, loss=1.09]
SASRec epoch 6/8:  14%|█▍        | 215/1500 [00:07<00:44, 28.99it/s, loss=1.09]
SASRec epoch 6/8:  15%|█▍        | 218/1500 [00:07<00:44, 29.04it/s, loss=1.09]
SASRec epoch 6/8:  15%|█▍        | 221/1500 [00:07<00:43, 29.25it/s, loss=1.09]
SASRec epoch 6/8:  15%|█▍        | 224/1500 [00:07<00:43, 29.08it/s, loss=1.09]
SASRec epoch 6/8:  15%|█▌        | 227/1500 [00:08<00:43, 29.15it/s, loss=1.09]
SASRec epoch 6/8:  15%|█▌        | 230/1500 [00:08<00:45, 27.86it/s, loss=1.09]
SASRec epoch 6/8:  16%|█▌        | 233/1500 [00:08<00:45, 27.97it/s, loss=1.09]
SASRec epoch 6/8:  16%|█▌        | 236/1500 [00:08<00:45, 27.98it/s, loss=1.09]
SASRec epoch 6/8:  16%|█▌        | 239/1500 [00:08<00:44, 28.39it/s, loss=1.09]
SASRec epoch 6/8:  16%|█▌        | 242/1500 [00:08<00:43, 28.72it/s, loss=1.09]
SASRec epoch 6/8:  16%|█▋        | 245/1500 [00:08<00:43, 28.85it/s, loss=1.09]
SASRec epoch 6/8:  17%|█▋        | 248/1500 [00:08<00:43, 29.03it/s, loss=1.09]
SASRec epoch 6/8:  17%|█▋        | 250/1500 [00:08<00:43, 29.03it/s, loss=1.1]
SASRec epoch 6/8:  17%|█▋        | 251/1500 [00:08<00:43, 28.52it/s, loss=1.1]
SASRec epoch 6/8:  17%|█▋        | 254/1500 [00:09<00:43, 28.55it/s, loss=1.1]
SASRec epoch 6/8:  17%|█▋        | 257/1500 [00:09<00:43, 28.79it/s, loss=1.1]
SASRec epoch 6/8:  17%|█▋        | 260/1500 [00:09<00:43, 28.29it/s, loss=1.1]
SASRec epoch 6/8:  18%|█▊        | 263/1500 [00:09<00:44, 27.97it/s, loss=1.1]
SASRec epoch 6/8:  18%|█▊        | 266/1500 [00:09<00:43, 28.36it/s, loss=1.1]
SASRec epoch 6/8:  18%|█▊        | 269/1500 [00:09<00:43, 28.47it/s, loss=1.1]
SASRec epoch 6/8:  18%|█▊        | 272/1500 [00:09<00:42, 28.77it/s, loss=1.1]
SASRec epoch 6/8:  18%|█▊        | 275/1500 [00:09<00:42, 28.88it/s, loss=1.1]
SASRec epoch 6/8:  19%|█▊        | 278/1500 [00:09<00:42, 28.97it/s, loss=1.1]
SASRec epoch 6/8:  19%|█▊        | 281/1500 [00:09<00:42, 28.91it/s, loss=1.1]
SASRec epoch 6/8:  19%|█▉        | 284/1500 [00:10<00:42, 28.78it/s, loss=1.1]
SASRec epoch 6/8:  19%|█▉        | 287/1500 [00:10<00:41, 28.99it/s, loss=1.1]
SASRec epoch 6/8:  19%|█▉        | 290/1500 [00:10<00:43, 28.11it/s, loss=1.1]
SASRec epoch 6/8:  20%|█▉        | 293/1500 [00:10<00:42, 28.44it/s, loss=1.1]
SASRec epoch 6/8:  20%|█▉        | 296/1500 [00:10<00:42, 28.51it/s, loss=1.1]
SASRec epoch 6/8:  20%|█▉        | 299/1500 [00:10<00:41, 28.71it/s, loss=1.1]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:10<00:41, 28.71it/s, loss=1.09]
SASRec epoch 6/8:  20%|██        | 302/1500 [00:10<00:42, 27.89it/s, loss=1.09]
SASRec epoch 6/8:  20%|██        | 305/1500 [00:10<00:42, 28.14it/s, loss=1.09]
SASRec epoch 6/8:  21%|██        | 308/1500 [00:10<00:41, 28.51it/s, loss=1.09]
SASRec epoch 6/8:  21%|██        | 311/1500 [00:11<00:41, 28.53it/s, loss=1.09]
SASRec epoch 6/8:  21%|██        | 314/1500 [00:11<00:41, 28.74it/s, loss=1.09]
SASRec epoch 6/8:  21%|██        | 317/1500 [00:11<00:40, 28.89it/s, loss=1.09]
SASRec epoch 6/8:  21%|██▏       | 320/1500 [00:11<00:41, 28.29it/s, loss=1.09]
SASRec epoch 6/8:  22%|██▏       | 323/1500 [00:11<00:41, 28.28it/s, loss=1.09]
SASRec epoch 6/8:  22%|██▏       | 326/1500 [00:11<00:41, 28.33it/s, loss=1.09]
SASRec epoch 6/8:  22%|██▏       | 329/1500 [00:11<00:41, 28.30it/s, loss=1.09]
SASRec epoch 6/8:  22%|██▏       | 332/1500 [00:11<00:41, 28.48it/s, loss=1.09]
SASRec epoch 6/8:  22%|██▏       | 335/1500 [00:11<00:42, 27.67it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 338/1500 [00:11<00:43, 26.58it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 341/1500 [00:12<00:44, 26.27it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 344/1500 [00:12<00:45, 25.52it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 347/1500 [00:12<00:45, 25.31it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:12<00:44, 26.06it/s, loss=1.09]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:12<00:44, 26.06it/s, loss=1.09]
SASRec epoch 6/8:  24%|██▎       | 353/1500 [00:12<00:44, 26.05it/s, loss=1.09]
SASRec epoch 6/8:  24%|██▎       | 356/1500 [00:12<00:43, 26.51it/s, loss=1.09]
SASRec epoch 6/8:  24%|██▍       | 359/1500 [00:12<00:42, 26.85it/s, loss=1.09]
SASRec epoch 6/8:  24%|██▍       | 362/1500 [00:12<00:41, 27.11it/s, loss=1.09]
SASRec epoch 6/8:  24%|██▍       | 365/1500 [00:13<00:41, 27.28it/s, loss=1.09]
SASRec epoch 6/8:  25%|██▍       | 368/1500 [00:13<00:41, 27.55it/s, loss=1.09]
SASRec epoch 6/8:  25%|██▍       | 371/1500 [00:13<00:40, 27.75it/s, loss=1.09]
SASRec epoch 6/8:  25%|██▍       | 374/1500 [00:13<00:40, 27.71it/s, loss=1.09]
SASRec epoch 6/8:  25%|██▌       | 377/1500 [00:13<00:40, 27.67it/s, loss=1.09]
SASRec epoch 6/8:  25%|██▌       | 380/1500 [00:13<00:41, 26.99it/s, loss=1.09]
SASRec epoch 6/8:  26%|██▌       | 383/1500 [00:13<00:40, 27.41it/s, loss=1.09]
SASRec epoch 6/8:  26%|██▌       | 386/1500 [00:13<00:40, 27.76it/s, loss=1.09]
SASRec epoch 6/8:  26%|██▌       | 389/1500 [00:13<00:39, 28.00it/s, loss=1.09]
SASRec epoch 6/8:  26%|██▌       | 392/1500 [00:13<00:39, 27.89it/s, loss=1.09]
SASRec epoch 6/8:  26%|██▋       | 395/1500 [00:14<00:39, 27.89it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 398/1500 [00:14<00:39, 28.18it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 400/1500 [00:14<00:39, 28.18it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 401/1500 [00:14<00:39, 28.11it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 404/1500 [00:14<00:38, 28.45it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 407/1500 [00:14<00:38, 28.60it/s, loss=1.09]
SASRec epoch 6/8:  27%|██▋       | 410/1500 [00:14<00:39, 27.56it/s, loss=1.09]
SASRec epoch 6/8:  28%|██▊       | 413/1500 [00:14<00:39, 27.32it/s, loss=1.09]
SASRec epoch 6/8:  28%|██▊       | 416/1500 [00:14<00:38, 27.84it/s, loss=1.09]
SASRec epoch 6/8:  28%|██▊       | 419/1500 [00:14<00:39, 27.64it/s, loss=1.09]
SASRec epoch 6/8:  28%|██▊       | 422/1500 [00:15<00:39, 27.01it/s, loss=1.09]
SASRec epoch 6/8:  28%|██▊       | 425/1500 [00:15<00:39, 27.48it/s, loss=1.09]
SASRec epoch 6/8:  29%|██▊       | 428/1500 [00:15<00:38, 28.00it/s, loss=1.09]
SASRec epoch 6/8:  29%|██▊       | 431/1500 [00:15<00:37, 28.17it/s, loss=1.09]
SASRec epoch 6/8:  29%|██▉       | 434/1500 [00:15<00:37, 28.32it/s, loss=1.09]
SASRec epoch 6/8:  29%|██▉       | 437/1500 [00:15<00:37, 28.23it/s, loss=1.09]
SASRec epoch 6/8:  29%|██▉       | 440/1500 [00:15<00:37, 28.13it/s, loss=1.09]
SASRec epoch 6/8:  30%|██▉       | 443/1500 [00:15<00:37, 27.88it/s, loss=1.09]
SASRec epoch 6/8:  30%|██▉       | 446/1500 [00:15<00:38, 27.65it/s, loss=1.09]
SASRec epoch 6/8:  30%|██▉       | 449/1500 [00:16<00:37, 27.67it/s, loss=1.09]
SASRec epoch 6/8:  30%|███       | 450/1500 [00:16<00:37, 27.67it/s, loss=1.08]
SASRec epoch 6/8:  30%|███       | 452/1500 [00:16<00:38, 27.07it/s, loss=1.08]
SASRec epoch 6/8:  30%|███       | 455/1500 [00:16<00:38, 27.39it/s, loss=1.08]
SASRec epoch 6/8:  31%|███       | 458/1500 [00:16<00:38, 27.28it/s, loss=1.08]
SASRec epoch 6/8:  31%|███       | 461/1500 [00:16<00:38, 27.12it/s, loss=1.08]
SASRec epoch 6/8:  31%|███       | 464/1500 [00:16<00:38, 27.04it/s, loss=1.08]
SASRec epoch 6/8:  31%|███       | 467/1500 [00:16<00:39, 26.20it/s, loss=1.08]
SASRec epoch 6/8:  31%|███▏      | 470/1500 [00:16<00:39, 26.02it/s, loss=1.08]
SASRec epoch 6/8:  32%|███▏      | 473/1500 [00:16<00:41, 25.01it/s, loss=1.08]
SASRec epoch 6/8:  32%|███▏      | 476/1500 [00:17<00:40, 25.07it/s, loss=1.08]
SASRec epoch 6/8:  32%|███▏      | 479/1500 [00:17<00:41, 24.75it/s, loss=1.08]
SASRec epoch 6/8:  32%|███▏      | 482/1500 [00:17<00:40, 24.94it/s, loss=1.08]
SASRec epoch 6/8:  32%|███▏      | 485/1500 [00:17<00:41, 24.60it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 488/1500 [00:17<00:40, 25.27it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 491/1500 [00:17<00:38, 25.92it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 494/1500 [00:17<00:38, 26.32it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 497/1500 [00:17<00:37, 26.47it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 500/1500 [00:18<00:38, 25.90it/s, loss=1.08]
SASRec epoch 6/8:  33%|███▎      | 500/1500 [00:18<00:38, 25.90it/s, loss=1.1]
SASRec epoch 6/8:  34%|███▎      | 503/1500 [00:18<00:38, 25.60it/s, loss=1.1]
SASRec epoch 6/8:  34%|███▎      | 506/1500 [00:18<00:37, 26.55it/s, loss=1.1]
SASRec epoch 6/8:  34%|███▍      | 509/1500 [00:18<00:36, 27.42it/s, loss=1.1]
SASRec epoch 6/8:  34%|███▍      | 512/1500 [00:18<00:35, 28.09it/s, loss=1.1]
SASRec epoch 6/8:  34%|███▍      | 515/1500 [00:18<00:34, 28.44it/s, loss=1.1]
SASRec epoch 6/8:  35%|███▍      | 518/1500 [00:18<00:34, 28.56it/s, loss=1.1]
SASRec epoch 6/8:  35%|███▍      | 521/1500 [00:18<00:34, 28.78it/s, loss=1.1]
SASRec epoch 6/8:  35%|███▍      | 524/1500 [00:18<00:33, 28.82it/s, loss=1.1]
SASRec epoch 6/8:  35%|███▌      | 527/1500 [00:18<00:33, 28.77it/s, loss=1.1]
SASRec epoch 6/8:  35%|███▌      | 530/1500 [00:19<00:35, 27.55it/s, loss=1.1]
SASRec epoch 6/8:  36%|███▌      | 533/1500 [00:19<00:34, 27.94it/s, loss=1.1]
SASRec epoch 6/8:  36%|███▌      | 536/1500 [00:19<00:34, 28.30it/s, loss=1.1]
SASRec epoch 6/8:  36%|███▌      | 539/1500 [00:19<00:33, 28.68it/s, loss=1.1]
SASRec epoch 6/8:  36%|███▌      | 542/1500 [00:19<00:33, 28.78it/s, loss=1.1]
SASRec epoch 6/8:  36%|███▋      | 545/1500 [00:19<00:33, 28.89it/s, loss=1.1]
SASRec epoch 6/8:  37%|███▋      | 548/1500 [00:19<00:32, 28.85it/s, loss=1.1]
SASRec epoch 6/8:  37%|███▋      | 550/1500 [00:19<00:32, 28.85it/s, loss=1.09]
SASRec epoch 6/8:  37%|███▋      | 551/1500 [00:19<00:33, 28.37it/s, loss=1.09]
SASRec epoch 6/8:  37%|███▋      | 554/1500 [00:19<00:33, 28.47it/s, loss=1.09]
SASRec epoch 6/8:  37%|███▋      | 557/1500 [00:20<00:33, 28.46it/s, loss=1.09]
SASRec epoch 6/8:  37%|███▋      | 560/1500 [00:20<00:34, 27.47it/s, loss=1.09]
SASRec epoch 6/8:  38%|███▊      | 563/1500 [00:20<00:33, 27.93it/s, loss=1.09]
SASRec epoch 6/8:  38%|███▊      | 566/1500 [00:20<00:32, 28.39it/s, loss=1.09]
SASRec epoch 6/8:  38%|███▊      | 569/1500 [00:20<00:32, 28.82it/s, loss=1.09]
SASRec epoch 6/8:  38%|███▊      | 573/1500 [00:20<00:31, 29.48it/s, loss=1.09]
SASRec epoch 6/8:  38%|███▊      | 576/1500 [00:20<00:31, 29.37it/s, loss=1.09]
SASRec epoch 6/8:  39%|███▊      | 579/1500 [00:20<00:31, 29.22it/s, loss=1.09]
SASRec epoch 6/8:  39%|███▉      | 582/1500 [00:20<00:31, 28.98it/s, loss=1.09]
SASRec epoch 6/8:  39%|███▉      | 585/1500 [00:20<00:31, 28.95it/s, loss=1.09]
SASRec epoch 6/8:  39%|███▉      | 588/1500 [00:21<00:31, 28.88it/s, loss=1.09]
SASRec epoch 6/8:  39%|███▉      | 591/1500 [00:21<00:31, 28.41it/s, loss=1.09]
SASRec epoch 6/8:  40%|███▉      | 594/1500 [00:21<00:31, 28.58it/s, loss=1.09]
SASRec epoch 6/8:  40%|███▉      | 597/1500 [00:21<00:31, 28.89it/s, loss=1.09]
SASRec epoch 6/8:  40%|████      | 600/1500 [00:21<00:31, 28.96it/s, loss=1.09]
SASRec epoch 6/8:  40%|████      | 600/1500 [00:21<00:31, 28.96it/s, loss=1.09]
SASRec epoch 6/8:  40%|████      | 603/1500 [00:21<00:31, 28.75it/s, loss=1.09]
SASRec epoch 6/8:  40%|████      | 606/1500 [00:21<00:30, 29.08it/s, loss=1.09]
SASRec epoch 6/8:  41%|████      | 609/1500 [00:21<00:30, 29.19it/s, loss=1.09]
SASRec epoch 6/8:  41%|████      | 612/1500 [00:21<00:30, 29.11it/s, loss=1.09]
SASRec epoch 6/8:  41%|████      | 615/1500 [00:22<00:30, 29.12it/s, loss=1.09]
SASRec epoch 6/8:  41%|████      | 618/1500 [00:22<00:30, 28.80it/s, loss=1.09]
SASRec epoch 6/8:  41%|████▏     | 621/1500 [00:22<00:31, 28.25it/s, loss=1.09]
SASRec epoch 6/8:  42%|████▏     | 624/1500 [00:22<00:30, 28.46it/s, loss=1.09]
SASRec epoch 6/8:  42%|████▏     | 627/1500 [00:22<00:30, 28.67it/s, loss=1.09]
SASRec epoch 6/8:  42%|████▏     | 630/1500 [00:22<00:30, 28.73it/s, loss=1.09]
SASRec epoch 6/8:  42%|████▏     | 633/1500 [00:22<00:30, 28.76it/s, loss=1.09]
SASRec epoch 6/8:  42%|████▏     | 636/1500 [00:22<00:30, 28.73it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 639/1500 [00:22<00:30, 28.60it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 642/1500 [00:22<00:30, 28.56it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 645/1500 [00:23<00:30, 28.43it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 648/1500 [00:23<00:29, 28.51it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 650/1500 [00:23<00:29, 28.51it/s, loss=1.09]
SASRec epoch 6/8:  43%|████▎     | 651/1500 [00:23<00:30, 27.48it/s, loss=1.09]
SASRec epoch 6/8:  44%|████▎     | 654/1500 [00:23<00:30, 27.82it/s, loss=1.09]
SASRec epoch 6/8:  44%|████▍     | 657/1500 [00:23<00:29, 28.13it/s, loss=1.09]
SASRec epoch 6/8:  44%|████▍     | 660/1500 [00:23<00:29, 28.39it/s, loss=1.09]
SASRec epoch 6/8:  44%|████▍     | 663/1500 [00:23<00:29, 28.69it/s, loss=1.09]
SASRec epoch 6/8:  44%|████▍     | 666/1500 [00:23<00:29, 28.64it/s, loss=1.09]
SASRec epoch 6/8:  45%|████▍     | 669/1500 [00:23<00:29, 28.58it/s, loss=1.09]
SASRec epoch 6/8:  45%|████▍     | 672/1500 [00:24<00:28, 28.77it/s, loss=1.09]
SASRec epoch 6/8:  45%|████▌     | 675/1500 [00:24<00:29, 28.22it/s, loss=1.09]
SASRec epoch 6/8:  45%|████▌     | 678/1500 [00:24<00:29, 28.23it/s, loss=1.09]
SASRec epoch 6/8:  45%|████▌     | 681/1500 [00:24<00:29, 27.83it/s, loss=1.09]
SASRec epoch 6/8:  46%|████▌     | 684/1500 [00:24<00:28, 28.25it/s, loss=1.09]
SASRec epoch 6/8:  46%|████▌     | 687/1500 [00:24<00:28, 28.47it/s, loss=1.09]
SASRec epoch 6/8:  46%|████▌     | 690/1500 [00:24<00:28, 28.76it/s, loss=1.09]
SASRec epoch 6/8:  46%|████▌     | 693/1500 [00:24<00:28, 28.73it/s, loss=1.09]
SASRec epoch 6/8:  46%|████▋     | 696/1500 [00:24<00:27, 28.93it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 699/1500 [00:24<00:27, 28.79it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 700/1500 [00:25<00:27, 28.79it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 702/1500 [00:25<00:28, 27.89it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 705/1500 [00:25<00:28, 28.18it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 708/1500 [00:25<00:27, 28.32it/s, loss=1.09]
SASRec epoch 6/8:  47%|████▋     | 711/1500 [00:25<00:28, 27.86it/s, loss=1.09]
SASRec epoch 6/8:  48%|████▊     | 714/1500 [00:25<00:27, 28.36it/s, loss=1.09]
SASRec epoch 6/8:  48%|████▊     | 717/1500 [00:25<00:27, 28.65it/s, loss=1.09]

[SASRec] epoch 6/8 loss=1.0821

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 7/8:   0%|          | 3/1500 [00:00<00:51, 28.95it/s]
SASRec epoch 7/8:   0%|          | 6/1500 [00:00<00:52, 28.50it/s]
SASRec epoch 7/8:   1%|          | 9/1500 [00:00<00:52, 28.14it/s]
SASRec epoch 7/8:   1%|          | 12/1500 [00:00<00:53, 27.89it/s]
SASRec epoch 7/8:   1%|          | 15/1500 [00:00<00:52, 28.42it/s]
SASRec epoch 7/8:   1%|          | 18/1500 [00:00<00:51, 28.56it/s]
SASRec epoch 7/8:   1%|▏         | 21/1500 [00:00<00:53, 27.39it/s]
SASRec epoch 7/8:   2%|▏         | 24/1500 [00:00<00:53, 27.68it/s]
SASRec epoch 7/8:   2%|▏         | 27/1500 [00:00<00:52, 27.91it/s]
SASRec epoch 7/8:   2%|▏         | 30/1500 [00:01<00:52, 27.97it/s]
SASRec epoch 7/8:   2%|▏         | 33/1500 [00:01<00:51, 28.29it/s]
SASRec epoch 7/8:   2%|▏         | 36/1500 [00:01<00:51, 28.18it/s]
SASRec epoch 7/8:   3%|▎         | 39/1500 [00:01<00:51, 28.45it/s]
SASRec epoch 7/8:   3%|▎         | 42/1500 [00:01<00:51, 28.55it/s]
SASRec epoch 7/8:   3%|▎         | 45/1500 [00:01<00:50, 28.65it/s]
SASRec epoch 7/8:   3%|▎         | 48/1500 [00:01<00:50, 28.79it/s]
SASRec epoch 7/8:   3%|▎         | 50/1500 [00:01<00:50, 28.79it/s, loss=1.05]
SASRec epoch 7/8:   3%|▎         | 51/1500 [00:01<00:52, 27.66it/s, loss=1.05]
SASRec epoch 7/8:   4%|▎         | 54/1500 [00:01<00:51, 27.99it/s, loss=1.05]
SASRec epoch 7/8:   4%|▍         | 57/1500 [00:02<00:51, 27.84it/s, loss=1.05]
SASRec epoch 7/8:   4%|▍         | 60/1500 [00:02<00:51, 27.81it/s, loss=1.05]
SASRec epoch 7/8:   4%|▍         | 63/1500 [00:02<00:51, 28.15it/s, loss=1.05]
SASRec epoch 7/8:   4%|▍         | 66/1500 [00:02<00:50, 28.37it/s, loss=1.05]
SASRec epoch 7/8:   5%|▍         | 69/1500 [00:02<00:50, 28.59it/s, loss=1.05]
SASRec epoch 7/8:   5%|▍         | 72/1500 [00:02<00:49, 28.77it/s, loss=1.05]
SASRec epoch 7/8:   5%|▌         | 75/1500 [00:02<00:49, 28.77it/s, loss=1.05]
SASRec epoch 7/8:   5%|▌         | 78/1500 [00:02<00:49, 28.88it/s, loss=1.05]
SASRec epoch 7/8:   5%|▌         | 81/1500 [00:02<00:51, 27.74it/s, loss=1.05]
SASRec epoch 7/8:   6%|▌         | 84/1500 [00:02<00:50, 28.04it/s, loss=1.05]
SASRec epoch 7/8:   6%|▌         | 87/1500 [00:03<00:49, 28.41it/s, loss=1.05]
SASRec epoch 7/8:   6%|▌         | 90/1500 [00:03<00:49, 28.65it/s, loss=1.05]
SASRec epoch 7/8:   6%|▌         | 93/1500 [00:03<00:49, 28.46it/s, loss=1.05]
SASRec epoch 7/8:   6%|▋         | 96/1500 [00:03<00:49, 28.55it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 99/1500 [00:03<00:49, 28.55it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:03<00:49, 28.55it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 102/1500 [00:03<00:49, 27.98it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 105/1500 [00:03<00:49, 28.31it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 108/1500 [00:03<00:49, 28.35it/s, loss=1.05]
SASRec epoch 7/8:   7%|▋         | 111/1500 [00:03<00:50, 27.52it/s, loss=1.05]
SASRec epoch 7/8:   8%|▊         | 114/1500 [00:04<00:49, 27.80it/s, loss=1.05]
SASRec epoch 7/8:   8%|▊         | 117/1500 [00:04<00:49, 28.08it/s, loss=1.05]
SASRec epoch 7/8:   8%|▊         | 120/1500 [00:04<00:49, 28.09it/s, loss=1.05]
SASRec epoch 7/8:   8%|▊         | 123/1500 [00:04<00:48, 28.39it/s, loss=1.05]
SASRec epoch 7/8:   8%|▊         | 126/1500 [00:04<00:48, 28.61it/s, loss=1.05]
SASRec epoch 7/8:   9%|▊         | 129/1500 [00:04<00:47, 28.70it/s, loss=1.05]
SASRec epoch 7/8:   9%|▉         | 132/1500 [00:04<00:47, 28.51it/s, loss=1.05]
SASRec epoch 7/8:   9%|▉         | 135/1500 [00:04<00:47, 28.64it/s, loss=1.05]
SASRec epoch 7/8:   9%|▉         | 138/1500 [00:04<00:47, 28.76it/s, loss=1.05]
SASRec epoch 7/8:   9%|▉         | 141/1500 [00:04<00:48, 28.20it/s, loss=1.05]
SASRec epoch 7/8:  10%|▉         | 144/1500 [00:05<00:48, 27.89it/s, loss=1.05]
SASRec epoch 7/8:  10%|▉         | 147/1500 [00:05<00:48, 28.10it/s, loss=1.05]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:05<00:47, 28.39it/s, loss=1.05]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:05<00:47, 28.39it/s, loss=1.05]
SASRec epoch 7/8:  10%|█         | 153/1500 [00:05<00:47, 28.11it/s, loss=1.05]
SASRec epoch 7/8:  10%|█         | 156/1500 [00:05<00:47, 28.40it/s, loss=1.05]
SASRec epoch 7/8:  11%|█         | 159/1500 [00:05<00:47, 28.33it/s, loss=1.05]
SASRec epoch 7/8:  11%|█         | 162/1500 [00:05<00:46, 28.57it/s, loss=1.05]
SASRec epoch 7/8:  11%|█         | 165/1500 [00:05<00:46, 28.75it/s, loss=1.05]
SASRec epoch 7/8:  11%|█         | 168/1500 [00:05<00:46, 28.36it/s, loss=1.05]
SASRec epoch 7/8:  11%|█▏        | 171/1500 [00:06<00:48, 27.49it/s, loss=1.05]
SASRec epoch 7/8:  12%|█▏        | 174/1500 [00:06<00:47, 27.69it/s, loss=1.05]
SASRec epoch 7/8:  12%|█▏        | 177/1500 [00:06<00:47, 28.04it/s, loss=1.05]
SASRec epoch 7/8:  12%|█▏        | 180/1500 [00:06<00:46, 28.30it/s, loss=1.05]
SASRec epoch 7/8:  12%|█▏        | 183/1500 [00:06<00:46, 28.25it/s, loss=1.05]
SASRec epoch 7/8:  12%|█▏        | 186/1500 [00:06<00:46, 28.45it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 189/1500 [00:06<00:45, 28.54it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 192/1500 [00:06<00:45, 28.48it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 195/1500 [00:06<00:45, 28.78it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 198/1500 [00:06<00:45, 28.78it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 200/1500 [00:07<00:45, 28.78it/s, loss=1.05]
SASRec epoch 7/8:  13%|█▎        | 201/1500 [00:07<00:46, 28.17it/s, loss=1.05]
SASRec epoch 7/8:  14%|█▎        | 204/1500 [00:07<00:45, 28.35it/s, loss=1.05]
SASRec epoch 7/8:  14%|█▍        | 207/1500 [00:07<00:45, 28.58it/s, loss=1.05]
SASRec epoch 7/8:  14%|█▍        | 210/1500 [00:07<00:45, 28.49it/s, loss=1.05]
SASRec epoch 7/8:  14%|█▍        | 213/1500 [00:07<00:46, 27.69it/s, loss=1.05]
SASRec epoch 7/8:  14%|█▍        | 216/1500 [00:07<00:50, 25.36it/s, loss=1.05]
SASRec epoch 7/8:  15%|█▍        | 219/1500 [00:07<00:50, 25.47it/s, loss=1.05]
SASRec epoch 7/8:  15%|█▍        | 222/1500 [00:07<00:49, 25.64it/s, loss=1.05]
SASRec epoch 7/8:  15%|█▌        | 225/1500 [00:08<00:49, 25.55it/s, loss=1.05]
SASRec epoch 7/8:  15%|█▌        | 228/1500 [00:08<00:50, 25.36it/s, loss=1.05]
SASRec epoch 7/8:  15%|█▌        | 231/1500 [00:08<00:49, 25.67it/s, loss=1.05]
SASRec epoch 7/8:  16%|█▌        | 234/1500 [00:08<00:47, 26.55it/s, loss=1.05]
SASRec epoch 7/8:  16%|█▌        | 237/1500 [00:08<00:47, 26.85it/s, loss=1.05]
SASRec epoch 7/8:  16%|█▌        | 240/1500 [00:08<00:46, 27.34it/s, loss=1.05]
SASRec epoch 7/8:  16%|█▌        | 243/1500 [00:08<00:45, 27.75it/s, loss=1.05]
SASRec epoch 7/8:  16%|█▋        | 246/1500 [00:08<00:44, 28.02it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 249/1500 [00:08<00:44, 28.22it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 250/1500 [00:08<00:44, 28.22it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 252/1500 [00:09<00:44, 27.95it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 255/1500 [00:09<00:44, 28.12it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 258/1500 [00:09<00:43, 28.26it/s, loss=1.05]
SASRec epoch 7/8:  17%|█▋        | 261/1500 [00:09<00:44, 27.84it/s, loss=1.05]
SASRec epoch 7/8:  18%|█▊        | 264/1500 [00:09<00:44, 28.00it/s, loss=1.05]
SASRec epoch 7/8:  18%|█▊        | 267/1500 [00:09<00:43, 28.16it/s, loss=1.05]
SASRec epoch 7/8:  18%|█▊        | 270/1500 [00:09<00:43, 28.27it/s, loss=1.05]
SASRec epoch 7/8:  18%|█▊        | 273/1500 [00:09<00:43, 28.14it/s, loss=1.05]
SASRec epoch 7/8:  18%|█▊        | 276/1500 [00:09<00:43, 28.13it/s, loss=1.05]
SASRec epoch 7/8:  19%|█▊        | 279/1500 [00:09<00:44, 27.40it/s, loss=1.05]
SASRec epoch 7/8:  19%|█▉        | 282/1500 [00:10<00:46, 26.07it/s, loss=1.05]
SASRec epoch 7/8:  19%|█▉        | 285/1500 [00:10<00:45, 26.86it/s, loss=1.05]
SASRec epoch 7/8:  19%|█▉        | 288/1500 [00:10<00:45, 26.91it/s, loss=1.05]
SASRec epoch 7/8:  19%|█▉        | 291/1500 [00:10<00:45, 26.30it/s, loss=1.05]
SASRec epoch 7/8:  20%|█▉        | 294/1500 [00:10<00:45, 26.47it/s, loss=1.05]
SASRec epoch 7/8:  20%|█▉        | 297/1500 [00:10<00:44, 27.11it/s, loss=1.05]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:10<00:43, 27.59it/s, loss=1.05]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:10<00:43, 27.59it/s, loss=1.04]
SASRec epoch 7/8:  20%|██        | 303/1500 [00:10<00:43, 27.70it/s, loss=1.04]
SASRec epoch 7/8:  20%|██        | 306/1500 [00:10<00:42, 27.87it/s, loss=1.04]
SASRec epoch 7/8:  21%|██        | 309/1500 [00:11<00:42, 28.09it/s, loss=1.04]
SASRec epoch 7/8:  21%|██        | 312/1500 [00:11<00:42, 28.26it/s, loss=1.04]
SASRec epoch 7/8:  21%|██        | 315/1500 [00:11<00:42, 28.17it/s, loss=1.04]
SASRec epoch 7/8:  21%|██        | 318/1500 [00:11<00:42, 28.06it/s, loss=1.04]
SASRec epoch 7/8:  21%|██▏       | 321/1500 [00:11<00:43, 27.19it/s, loss=1.04]
SASRec epoch 7/8:  22%|██▏       | 324/1500 [00:11<00:44, 26.57it/s, loss=1.04]
SASRec epoch 7/8:  22%|██▏       | 327/1500 [00:11<00:43, 26.89it/s, loss=1.04]
SASRec epoch 7/8:  22%|██▏       | 330/1500 [00:11<00:45, 25.66it/s, loss=1.04]
SASRec epoch 7/8:  22%|██▏       | 333/1500 [00:12<00:47, 24.77it/s, loss=1.04]
SASRec epoch 7/8:  22%|██▏       | 336/1500 [00:12<00:48, 24.18it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 339/1500 [00:12<00:48, 24.08it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 342/1500 [00:12<00:46, 24.70it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 345/1500 [00:12<00:45, 25.32it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 348/1500 [00:12<00:45, 25.51it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:12<00:45, 25.51it/s, loss=1.04]
SASRec epoch 7/8:  23%|██▎       | 351/1500 [00:12<00:45, 24.99it/s, loss=1.04]
SASRec epoch 7/8:  24%|██▎       | 354/1500 [00:12<00:44, 25.47it/s, loss=1.04]
SASRec epoch 7/8:  24%|██▍       | 357/1500 [00:12<00:44, 25.61it/s, loss=1.04]
SASRec epoch 7/8:  24%|██▍       | 360/1500 [00:13<00:44, 25.62it/s, loss=1.04]
SASRec epoch 7/8:  24%|██▍       | 363/1500 [00:13<00:44, 25.30it/s, loss=1.04]
SASRec epoch 7/8:  24%|██▍       | 366/1500 [00:13<00:44, 25.71it/s, loss=1.04]
SASRec epoch 7/8:  25%|██▍       | 369/1500 [00:13<00:44, 25.69it/s, loss=1.04]
SASRec epoch 7/8:  25%|██▍       | 372/1500 [00:13<00:44, 25.49it/s, loss=1.04]
SASRec epoch 7/8:  25%|██▌       | 375/1500 [00:13<00:43, 26.13it/s, loss=1.04]
SASRec epoch 7/8:  25%|██▌       | 378/1500 [00:13<00:44, 25.21it/s, loss=1.04]
SASRec epoch 7/8:  25%|██▌       | 381/1500 [00:13<00:43, 25.99it/s, loss=1.04]
SASRec epoch 7/8:  26%|██▌       | 384/1500 [00:13<00:42, 26.27it/s, loss=1.04]
SASRec epoch 7/8:  26%|██▌       | 387/1500 [00:14<00:41, 26.53it/s, loss=1.04]
SASRec epoch 7/8:  26%|██▌       | 390/1500 [00:14<00:42, 26.34it/s, loss=1.04]
SASRec epoch 7/8:  26%|██▌       | 393/1500 [00:14<00:40, 27.27it/s, loss=1.04]
SASRec epoch 7/8:  26%|██▋       | 396/1500 [00:14<00:40, 27.47it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 399/1500 [00:14<00:39, 27.90it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 400/1500 [00:14<00:39, 27.90it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 402/1500 [00:14<00:40, 27.21it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 405/1500 [00:14<00:39, 27.60it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 408/1500 [00:14<00:40, 26.84it/s, loss=1.04]
SASRec epoch 7/8:  27%|██▋       | 411/1500 [00:14<00:39, 27.31it/s, loss=1.04]
SASRec epoch 7/8:  28%|██▊       | 414/1500 [00:15<00:39, 27.80it/s, loss=1.04]
SASRec epoch 7/8:  28%|██▊       | 417/1500 [00:15<00:38, 28.19it/s, loss=1.04]
SASRec epoch 7/8:  28%|██▊       | 420/1500 [00:15<00:38, 28.41it/s, loss=1.04]
SASRec epoch 7/8:  28%|██▊       | 423/1500 [00:15<00:37, 28.68it/s, loss=1.04]
SASRec epoch 7/8:  28%|██▊       | 426/1500 [00:15<00:37, 28.63it/s, loss=1.04]
SASRec epoch 7/8:  29%|██▊       | 429/1500 [00:15<00:37, 28.72it/s, loss=1.04]
SASRec epoch 7/8:  29%|██▉       | 432/1500 [00:15<00:36, 28.94it/s, loss=1.04]
SASRec epoch 7/8:  29%|██▉       | 435/1500 [00:15<00:36, 28.99it/s, loss=1.04]
SASRec epoch 7/8:  29%|██▉       | 438/1500 [00:15<00:38, 27.80it/s, loss=1.04]
SASRec epoch 7/8:  29%|██▉       | 441/1500 [00:16<00:37, 28.06it/s, loss=1.04]
SASRec epoch 7/8:  30%|██▉       | 444/1500 [00:16<00:37, 28.34it/s, loss=1.04]
SASRec epoch 7/8:  30%|██▉       | 447/1500 [00:16<00:36, 28.56it/s, loss=1.04]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:16<00:37, 28.37it/s, loss=1.04]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:16<00:37, 28.37it/s, loss=1.04]
SASRec epoch 7/8:  30%|███       | 453/1500 [00:16<00:37, 28.11it/s, loss=1.04]
SASRec epoch 7/8:  30%|███       | 456/1500 [00:16<00:36, 28.54it/s, loss=1.04]
SASRec epoch 7/8:  31%|███       | 459/1500 [00:16<00:36, 28.57it/s, loss=1.04]
SASRec epoch 7/8:  31%|███       | 462/1500 [00:16<00:35, 28.86it/s, loss=1.04]
SASRec epoch 7/8:  31%|███       | 465/1500 [00:16<00:35, 28.82it/s, loss=1.04]
SASRec epoch 7/8:  31%|███       | 468/1500 [00:16<00:36, 28.18it/s, loss=1.04]
SASRec epoch 7/8:  31%|███▏      | 471/1500 [00:17<00:36, 28.12it/s, loss=1.04]
SASRec epoch 7/8:  32%|███▏      | 474/1500 [00:17<00:36, 28.35it/s, loss=1.04]
SASRec epoch 7/8:  32%|███▏      | 477/1500 [00:17<00:36, 28.34it/s, loss=1.04]
SASRec epoch 7/8:  32%|███▏      | 480/1500 [00:17<00:35, 28.48it/s, loss=1.04]
SASRec epoch 7/8:  32%|███▏      | 483/1500 [00:17<00:35, 28.67it/s, loss=1.04]
SASRec epoch 7/8:  32%|███▏      | 486/1500 [00:17<00:35, 28.74it/s, loss=1.04]
SASRec epoch 7/8:  33%|███▎      | 489/1500 [00:17<00:34, 28.92it/s, loss=1.04]
SASRec epoch 7/8:  33%|███▎      | 492/1500 [00:17<00:34, 28.83it/s, loss=1.04]
SASRec epoch 7/8:  33%|███▎      | 495/1500 [00:17<00:35, 28.52it/s, loss=1.04]
SASRec epoch 7/8:  33%|███▎      | 498/1500 [00:18<00:35, 28.16it/s, loss=1.04]
SASRec epoch 7/8:  33%|███▎      | 500/1500 [00:18<00:35, 28.16it/s, loss=1.03]
SASRec epoch 7/8:  33%|███▎      | 501/1500 [00:18<00:35, 27.82it/s, loss=1.03]
SASRec epoch 7/8:  34%|███▎      | 504/1500 [00:18<00:35, 27.98it/s, loss=1.03]
SASRec epoch 7/8:  34%|███▍      | 507/1500 [00:18<00:35, 28.28it/s, loss=1.03]
SASRec epoch 7/8:  34%|███▍      | 510/1500 [00:18<00:34, 28.31it/s, loss=1.03]
SASRec epoch 7/8:  34%|███▍      | 513/1500 [00:18<00:34, 28.68it/s, loss=1.03]
SASRec epoch 7/8:  34%|███▍      | 516/1500 [00:18<00:34, 28.90it/s, loss=1.03]
SASRec epoch 7/8:  35%|███▍      | 519/1500 [00:18<00:33, 29.03it/s, loss=1.03]
SASRec epoch 7/8:  35%|███▍      | 522/1500 [00:18<00:33, 29.06it/s, loss=1.03]
SASRec epoch 7/8:  35%|███▌      | 525/1500 [00:18<00:33, 28.98it/s, loss=1.03]
SASRec epoch 7/8:  35%|███▌      | 528/1500 [00:19<00:33, 28.61it/s, loss=1.03]
SASRec epoch 7/8:  35%|███▌      | 531/1500 [00:19<00:33, 28.76it/s, loss=1.03]
SASRec epoch 7/8:  36%|███▌      | 534/1500 [00:19<00:33, 28.71it/s, loss=1.03]
SASRec epoch 7/8:  36%|███▌      | 537/1500 [00:19<00:33, 28.65it/s, loss=1.03]
SASRec epoch 7/8:  36%|███▌      | 540/1500 [00:19<00:33, 28.89it/s, loss=1.03]
SASRec epoch 7/8:  36%|███▌      | 543/1500 [00:19<00:33, 28.96it/s, loss=1.03]
SASRec epoch 7/8:  36%|███▋      | 546/1500 [00:19<00:33, 28.89it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 549/1500 [00:19<00:32, 29.04it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 550/1500 [00:19<00:32, 29.04it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 552/1500 [00:19<00:33, 28.06it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 555/1500 [00:20<00:33, 28.59it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 558/1500 [00:20<00:33, 28.47it/s, loss=1.03]
SASRec epoch 7/8:  37%|███▋      | 561/1500 [00:20<00:32, 28.63it/s, loss=1.03]
SASRec epoch 7/8:  38%|███▊      | 564/1500 [00:20<00:32, 29.00it/s, loss=1.03]
SASRec epoch 7/8:  38%|███▊      | 567/1500 [00:20<00:32, 29.03it/s, loss=1.03]
SASRec epoch 7/8:  38%|███▊      | 570/1500 [00:20<00:31, 29.07it/s, loss=1.03]
SASRec epoch 7/8:  38%|███▊      | 573/1500 [00:20<00:31, 29.05it/s, loss=1.03]
SASRec epoch 7/8:  38%|███▊      | 576/1500 [00:20<00:31, 29.20it/s, loss=1.03]
SASRec epoch 7/8:  39%|███▊      | 579/1500 [00:20<00:31, 29.23it/s, loss=1.03]
SASRec epoch 7/8:  39%|███▉      | 582/1500 [00:20<00:31, 29.25it/s, loss=1.03]
SASRec epoch 7/8:  39%|███▉      | 585/1500 [00:21<00:31, 29.23it/s, loss=1.03]
SASRec epoch 7/8:  39%|███▉      | 588/1500 [00:21<00:31, 28.66it/s, loss=1.03]
SASRec epoch 7/8:  39%|███▉      | 591/1500 [00:21<00:31, 28.70it/s, loss=1.03]
SASRec epoch 7/8:  40%|███▉      | 594/1500 [00:21<00:31, 28.76it/s, loss=1.03]
SASRec epoch 7/8:  40%|███▉      | 597/1500 [00:21<00:31, 28.73it/s, loss=1.03]
SASRec epoch 7/8:  40%|████      | 600/1500 [00:21<00:31, 29.01it/s, loss=1.03]
SASRec epoch 7/8:  40%|████      | 600/1500 [00:21<00:31, 29.01it/s, loss=1.03]
SASRec epoch 7/8:  40%|████      | 603/1500 [00:21<00:31, 28.66it/s, loss=1.03]
SASRec epoch 7/8:  40%|████      | 606/1500 [00:21<00:30, 28.91it/s, loss=1.03]
SASRec epoch 7/8:  41%|████      | 609/1500 [00:21<00:30, 29.00it/s, loss=1.03]
SASRec epoch 7/8:  41%|████      | 612/1500 [00:21<00:30, 28.79it/s, loss=1.03]
SASRec epoch 7/8:  41%|████      | 616/1500 [00:22<00:29, 29.52it/s, loss=1.03]
SASRec epoch 7/8:  41%|████▏     | 619/1500 [00:22<00:30, 28.82it/s, loss=1.03]
SASRec epoch 7/8:  41%|████▏     | 622/1500 [00:22<00:30, 29.02it/s, loss=1.03]
SASRec epoch 7/8:  42%|████▏     | 625/1500 [00:22<00:30, 28.88it/s, loss=1.03]
SASRec epoch 7/8:  42%|████▏     | 629/1500 [00:22<00:29, 29.54it/s, loss=1.03]
SASRec epoch 7/8:  42%|████▏     | 632/1500 [00:22<00:29, 29.47it/s, loss=1.03]
SASRec epoch 7/8:  42%|████▏     | 635/1500 [00:22<00:29, 29.55it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 638/1500 [00:22<00:29, 29.43it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 641/1500 [00:22<00:29, 29.54it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 644/1500 [00:23<00:28, 29.52it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 647/1500 [00:23<00:28, 29.61it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 650/1500 [00:23<00:29, 29.02it/s, loss=1.03]
SASRec epoch 7/8:  43%|████▎     | 650/1500 [00:23<00:29, 29.02it/s, loss=1.03]
SASRec epoch 7/8:  44%|████▎     | 653/1500 [00:23<00:29, 28.40it/s, loss=1.03]
SASRec epoch 7/8:  44%|████▎     | 656/1500 [00:23<00:29, 28.86it/s, loss=1.03]
SASRec epoch 7/8:  44%|████▍     | 659/1500 [00:23<00:29, 28.96it/s, loss=1.03]
SASRec epoch 7/8:  44%|████▍     | 662/1500 [00:23<00:29, 28.85it/s, loss=1.03]
SASRec epoch 7/8:  44%|████▍     | 665/1500 [00:23<00:28, 28.95it/s, loss=1.03]
SASRec epoch 7/8:  45%|████▍     | 668/1500 [00:23<00:28, 28.83it/s, loss=1.03]
SASRec epoch 7/8:  45%|████▍     | 671/1500 [00:24<00:28, 28.62it/s, loss=1.03]
SASRec epoch 7/8:  45%|████▍     | 674/1500 [00:24<00:28, 28.71it/s, loss=1.03]
SASRec epoch 7/8:  45%|████▌     | 677/1500 [00:24<00:29, 28.31it/s, loss=1.03]
SASRec epoch 7/8:  45%|████▌     | 680/1500 [00:24<00:30, 26.90it/s, loss=1.03]
SASRec epoch 7/8:  46%|████▌     | 683/1500 [00:24<00:31, 25.93it/s, loss=1.03]
SASRec epoch 7/8:  46%|████▌     | 686/1500 [00:24<00:32, 25.08it/s, loss=1.03]
SASRec epoch 7/8:  46%|████▌     | 689/1500 [00:24<00:32, 24.61it/s, loss=1.03]
SASRec epoch 7/8:  46%|████▌     | 692/1500 [00:24<00:32, 25.22it/s, loss=1.03]
SASRec epoch 7/8:  46%|████▋     | 695/1500 [00:24<00:31, 25.74it/s, loss=1.03]
SASRec epoch 7/8:  47%|████▋     | 698/1500 [00:25<00:30, 26.36it/s, loss=1.03]
SASRec epoch 7/8:  47%|████▋     | 700/1500 [00:25<00:30, 26.36it/s, loss=1.02]
SASRec epoch 7/8:  47%|████▋     | 701/1500 [00:25<00:30, 26.33it/s, loss=1.02]
SASRec epoch 7/8:  47%|████▋     | 704/1500 [00:25<00:29, 26.93it/s, loss=1.02]
SASRec epoch 7/8:  47%|████▋     | 707/1500 [00:25<00:29, 27.20it/s, loss=1.02]
SASRec epoch 7/8:  47%|████▋     | 710/1500 [00:25<00:28, 27.31it/s, loss=1.02]
SASRec epoch 7/8:  48%|████▊     | 713/1500 [00:25<00:28, 27.78it/s, loss=1.02]

[SASRec] epoch 7/8 loss=1.0245

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 8/8:   0%|          | 3/1500 [00:00<00:52, 28.65it/s]
SASRec epoch 8/8:   0%|          | 6/1500 [00:00<00:52, 28.30it/s]
SASRec epoch 8/8:   1%|          | 9/1500 [00:00<00:52, 28.42it/s]
SASRec epoch 8/8:   1%|          | 12/1500 [00:00<00:52, 28.45it/s]
SASRec epoch 8/8:   1%|          | 15/1500 [00:00<00:51, 28.88it/s]
SASRec epoch 8/8:   1%|          | 18/1500 [00:00<00:51, 28.77it/s]
SASRec epoch 8/8:   1%|▏         | 21/1500 [00:00<00:51, 28.62it/s]
SASRec epoch 8/8:   2%|▏         | 24/1500 [00:00<00:51, 28.61it/s]
SASRec epoch 8/8:   2%|▏         | 27/1500 [00:00<00:52, 28.30it/s]
SASRec epoch 8/8:   2%|▏         | 30/1500 [00:01<00:51, 28.64it/s]
SASRec epoch 8/8:   2%|▏         | 33/1500 [00:01<00:50, 28.85it/s]
SASRec epoch 8/8:   2%|▏         | 36/1500 [00:01<00:50, 28.79it/s]
SASRec epoch 8/8:   3%|▎         | 39/1500 [00:01<00:50, 28.98it/s]
SASRec epoch 8/8:   3%|▎         | 42/1500 [00:01<00:51, 28.54it/s]
SASRec epoch 8/8:   3%|▎         | 45/1500 [00:01<00:51, 28.45it/s]
SASRec epoch 8/8:   3%|▎         | 48/1500 [00:01<00:50, 28.78it/s]
SASRec epoch 8/8:   3%|▎         | 50/1500 [00:01<00:50, 28.78it/s, loss=0.993]
SASRec epoch 8/8:   3%|▎         | 51/1500 [00:01<00:51, 28.12it/s, loss=0.993]
SASRec epoch 8/8:   4%|▎         | 54/1500 [00:01<00:51, 28.30it/s, loss=0.993]
SASRec epoch 8/8:   4%|▍         | 57/1500 [00:01<00:50, 28.60it/s, loss=0.993]
SASRec epoch 8/8:   4%|▍         | 60/1500 [00:02<00:50, 28.50it/s, loss=0.993]
SASRec epoch 8/8:   4%|▍         | 63/1500 [00:02<00:49, 28.86it/s, loss=0.993]
SASRec epoch 8/8:   4%|▍         | 66/1500 [00:02<00:49, 29.12it/s, loss=0.993]
SASRec epoch 8/8:   5%|▍         | 69/1500 [00:02<00:49, 29.05it/s, loss=0.993]
SASRec epoch 8/8:   5%|▍         | 72/1500 [00:02<00:49, 28.76it/s, loss=0.993]
SASRec epoch 8/8:   5%|▌         | 75/1500 [00:02<00:49, 28.99it/s, loss=0.993]
SASRec epoch 8/8:   5%|▌         | 78/1500 [00:02<00:48, 29.11it/s, loss=0.993]
SASRec epoch 8/8:   5%|▌         | 81/1500 [00:02<00:48, 29.35it/s, loss=0.993]
SASRec epoch 8/8:   6%|▌         | 84/1500 [00:02<00:49, 28.60it/s, loss=0.993]
SASRec epoch 8/8:   6%|▌         | 87/1500 [00:03<00:49, 28.26it/s, loss=0.993]
SASRec epoch 8/8:   6%|▌         | 90/1500 [00:03<00:50, 27.82it/s, loss=0.993]
SASRec epoch 8/8:   6%|▌         | 93/1500 [00:03<00:50, 27.94it/s, loss=0.993]
SASRec epoch 8/8:   6%|▋         | 96/1500 [00:03<00:50, 28.04it/s, loss=0.993]
SASRec epoch 8/8:   7%|▋         | 99/1500 [00:03<00:53, 26.35it/s, loss=0.993]
SASRec epoch 8/8:   7%|▋         | 100/1500 [00:03<00:53, 26.35it/s, loss=0.999]
SASRec epoch 8/8:   7%|▋         | 102/1500 [00:03<00:54, 25.56it/s, loss=0.999]
SASRec epoch 8/8:   7%|▋         | 105/1500 [00:03<00:54, 25.66it/s, loss=0.999]
SASRec epoch 8/8:   7%|▋         | 108/1500 [00:03<00:52, 26.67it/s, loss=0.999]
SASRec epoch 8/8:   7%|▋         | 111/1500 [00:03<00:50, 27.36it/s, loss=0.999]
SASRec epoch 8/8:   8%|▊         | 114/1500 [00:04<00:49, 27.80it/s, loss=0.999]
SASRec epoch 8/8:   8%|▊         | 117/1500 [00:04<00:49, 28.19it/s, loss=0.999]
SASRec epoch 8/8:   8%|▊         | 120/1500 [00:04<00:48, 28.37it/s, loss=0.999]
SASRec epoch 8/8:   8%|▊         | 123/1500 [00:04<00:48, 28.60it/s, loss=0.999]
SASRec epoch 8/8:   8%|▊         | 126/1500 [00:04<00:47, 28.69it/s, loss=0.999]
SASRec epoch 8/8:   9%|▊         | 129/1500 [00:04<00:47, 28.67it/s, loss=0.999]
SASRec epoch 8/8:   9%|▉         | 132/1500 [00:04<00:49, 27.77it/s, loss=0.999]
SASRec epoch 8/8:   9%|▉         | 135/1500 [00:04<00:49, 27.84it/s, loss=0.999]
SASRec epoch 8/8:   9%|▉         | 138/1500 [00:04<00:48, 28.32it/s, loss=0.999]
SASRec epoch 8/8:   9%|▉         | 141/1500 [00:04<00:47, 28.45it/s, loss=0.999]
SASRec epoch 8/8:  10%|▉         | 144/1500 [00:05<00:47, 28.70it/s, loss=0.999]
SASRec epoch 8/8:  10%|▉         | 147/1500 [00:05<00:46, 28.97it/s, loss=0.999]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:05<00:46, 28.78it/s, loss=0.999]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:05<00:46, 28.78it/s, loss=1]
SASRec epoch 8/8:  10%|█         | 153/1500 [00:05<00:46, 28.92it/s, loss=1]
SASRec epoch 8/8:  10%|█         | 156/1500 [00:05<00:46, 28.95it/s, loss=1]
SASRec epoch 8/8:  11%|█         | 159/1500 [00:05<00:46, 29.13it/s, loss=1]
SASRec epoch 8/8:  11%|█         | 162/1500 [00:05<00:46, 28.89it/s, loss=1]
SASRec epoch 8/8:  11%|█         | 165/1500 [00:05<00:46, 28.42it/s, loss=1]
SASRec epoch 8/8:  11%|█         | 168/1500 [00:05<00:48, 27.74it/s, loss=1]
SASRec epoch 8/8:  11%|█▏        | 171/1500 [00:06<00:47, 27.84it/s, loss=1]
SASRec epoch 8/8:  12%|█▏        | 174/1500 [00:06<00:50, 26.33it/s, loss=1]
SASRec epoch 8/8:  12%|█▏        | 177/1500 [00:06<00:51, 25.83it/s, loss=1]
SASRec epoch 8/8:  12%|█▏        | 180/1500 [00:06<00:50, 25.90it/s, loss=1]
SASRec epoch 8/8:  12%|█▏        | 183/1500 [00:06<00:52, 25.15it/s, loss=1]
SASRec epoch 8/8:  12%|█▏        | 186/1500 [00:06<00:54, 24.19it/s, loss=1]
SASRec epoch 8/8:  13%|█▎        | 189/1500 [00:06<00:54, 23.96it/s, loss=1]
SASRec epoch 8/8:  13%|█▎        | 192/1500 [00:06<00:56, 23.06it/s, loss=1]
SASRec epoch 8/8:  13%|█▎        | 195/1500 [00:07<00:57, 22.65it/s, loss=1]
SASRec epoch 8/8:  13%|█▎        | 198/1500 [00:07<00:56, 23.13it/s, loss=1]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:07<00:56, 23.13it/s, loss=0.99]
SASRec epoch 8/8:  13%|█▎        | 201/1500 [00:07<00:53, 24.08it/s, loss=0.99]
SASRec epoch 8/8:  14%|█▎        | 204/1500 [00:07<00:51, 25.28it/s, loss=0.99]
SASRec epoch 8/8:  14%|█▍        | 207/1500 [00:07<00:50, 25.48it/s, loss=0.99]
SASRec epoch 8/8:  14%|█▍        | 210/1500 [00:07<00:51, 25.14it/s, loss=0.99]
SASRec epoch 8/8:  14%|█▍        | 213/1500 [00:07<00:51, 25.22it/s, loss=0.99]
SASRec epoch 8/8:  14%|█▍        | 216/1500 [00:07<00:50, 25.44it/s, loss=0.99]
SASRec epoch 8/8:  15%|█▍        | 219/1500 [00:08<00:50, 25.60it/s, loss=0.99]
SASRec epoch 8/8:  15%|█▍        | 222/1500 [00:08<00:49, 25.80it/s, loss=0.99]
SASRec epoch 8/8:  15%|█▌        | 225/1500 [00:08<00:49, 25.72it/s, loss=0.99]
SASRec epoch 8/8:  15%|█▌        | 228/1500 [00:08<00:49, 25.70it/s, loss=0.99]
SASRec epoch 8/8:  15%|█▌        | 231/1500 [00:08<00:48, 26.06it/s, loss=0.99]
SASRec epoch 8/8:  16%|█▌        | 234/1500 [00:08<00:47, 26.56it/s, loss=0.99]
SASRec epoch 8/8:  16%|█▌        | 237/1500 [00:08<00:49, 25.29it/s, loss=0.99]
SASRec epoch 8/8:  16%|█▌        | 240/1500 [00:08<00:49, 25.66it/s, loss=0.99]
SASRec epoch 8/8:  16%|█▌        | 243/1500 [00:08<00:48, 25.99it/s, loss=0.99]
SASRec epoch 8/8:  16%|█▋        | 246/1500 [00:09<00:47, 26.45it/s, loss=0.99]
SASRec epoch 8/8:  17%|█▋        | 249/1500 [00:09<00:47, 26.57it/s, loss=0.99]
SASRec epoch 8/8:  17%|█▋        | 250/1500 [00:09<00:47, 26.57it/s, loss=0.987]
SASRec epoch 8/8:  17%|█▋        | 252/1500 [00:09<00:49, 25.39it/s, loss=0.987]
SASRec epoch 8/8:  17%|█▋        | 255/1500 [00:09<00:49, 24.98it/s, loss=0.987]
SASRec epoch 8/8:  17%|█▋        | 258/1500 [00:09<00:47, 25.89it/s, loss=0.987]
SASRec epoch 8/8:  17%|█▋        | 261/1500 [00:09<00:46, 26.82it/s, loss=0.987]
SASRec epoch 8/8:  18%|█▊        | 264/1500 [00:09<00:45, 26.98it/s, loss=0.987]
SASRec epoch 8/8:  18%|█▊        | 267/1500 [00:09<00:44, 27.64it/s, loss=0.987]
SASRec epoch 8/8:  18%|█▊        | 270/1500 [00:09<00:43, 28.03it/s, loss=0.987]
SASRec epoch 8/8:  18%|█▊        | 273/1500 [00:10<00:43, 28.34it/s, loss=0.987]
SASRec epoch 8/8:  18%|█▊        | 276/1500 [00:10<00:42, 28.61it/s, loss=0.987]
SASRec epoch 8/8:  19%|█▊        | 279/1500 [00:10<00:43, 28.39it/s, loss=0.987]
SASRec epoch 8/8:  19%|█▉        | 282/1500 [00:10<00:42, 28.41it/s, loss=0.987]
SASRec epoch 8/8:  19%|█▉        | 285/1500 [00:10<00:42, 28.64it/s, loss=0.987]
SASRec epoch 8/8:  19%|█▉        | 288/1500 [00:10<00:42, 28.78it/s, loss=0.987]
SASRec epoch 8/8:  19%|█▉        | 291/1500 [00:10<00:42, 28.67it/s, loss=0.987]
SASRec epoch 8/8:  20%|█▉        | 294/1500 [00:10<00:42, 28.62it/s, loss=0.987]
SASRec epoch 8/8:  20%|█▉        | 297/1500 [00:10<00:42, 28.60it/s, loss=0.987]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:10<00:42, 28.55it/s, loss=0.987]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:10<00:42, 28.55it/s, loss=0.985]
SASRec epoch 8/8:  20%|██        | 303/1500 [00:11<00:42, 27.86it/s, loss=0.985]
SASRec epoch 8/8:  20%|██        | 306/1500 [00:11<00:42, 28.06it/s, loss=0.985]
SASRec epoch 8/8:  21%|██        | 309/1500 [00:11<00:43, 27.57it/s, loss=0.985]
SASRec epoch 8/8:  21%|██        | 312/1500 [00:11<00:42, 27.83it/s, loss=0.985]
SASRec epoch 8/8:  21%|██        | 315/1500 [00:11<00:42, 28.18it/s, loss=0.985]
SASRec epoch 8/8:  21%|██        | 318/1500 [00:11<00:41, 28.27it/s, loss=0.985]
SASRec epoch 8/8:  21%|██▏       | 321/1500 [00:11<00:41, 28.49it/s, loss=0.985]
SASRec epoch 8/8:  22%|██▏       | 324/1500 [00:11<00:41, 28.49it/s, loss=0.985]
SASRec epoch 8/8:  22%|██▏       | 327/1500 [00:11<00:40, 28.63it/s, loss=0.985]
SASRec epoch 8/8:  22%|██▏       | 330/1500 [00:12<00:40, 28.66it/s, loss=0.985]
SASRec epoch 8/8:  22%|██▏       | 333/1500 [00:12<00:40, 28.67it/s, loss=0.985]
SASRec epoch 8/8:  22%|██▏       | 336/1500 [00:12<00:40, 28.75it/s, loss=0.985]
SASRec epoch 8/8:  23%|██▎       | 339/1500 [00:12<00:41, 28.00it/s, loss=0.985]
SASRec epoch 8/8:  23%|██▎       | 342/1500 [00:12<00:40, 28.34it/s, loss=0.985]
SASRec epoch 8/8:  23%|██▎       | 345/1500 [00:12<00:41, 27.87it/s, loss=0.985]
SASRec epoch 8/8:  23%|██▎       | 348/1500 [00:12<00:41, 27.97it/s, loss=0.985]
SASRec epoch 8/8:  23%|██▎       | 350/1500 [00:12<00:41, 27.97it/s, loss=0.989]
SASRec epoch 8/8:  23%|██▎       | 351/1500 [00:12<00:41, 27.55it/s, loss=0.989]
SASRec epoch 8/8:  24%|██▎       | 354/1500 [00:12<00:41, 27.83it/s, loss=0.989]
SASRec epoch 8/8:  24%|██▍       | 357/1500 [00:13<00:40, 28.01it/s, loss=0.989]
SASRec epoch 8/8:  24%|██▍       | 360/1500 [00:13<00:40, 28.27it/s, loss=0.989]
SASRec epoch 8/8:  24%|██▍       | 363/1500 [00:13<00:39, 28.59it/s, loss=0.989]
SASRec epoch 8/8:  24%|██▍       | 366/1500 [00:13<00:39, 28.82it/s, loss=0.989]
SASRec epoch 8/8:  25%|██▍       | 369/1500 [00:13<00:39, 28.68it/s, loss=0.989]
SASRec epoch 8/8:  25%|██▍       | 372/1500 [00:13<00:39, 28.88it/s, loss=0.989]
SASRec epoch 8/8:  25%|██▌       | 375/1500 [00:13<00:40, 27.79it/s, loss=0.989]
SASRec epoch 8/8:  25%|██▌       | 378/1500 [00:13<00:39, 28.10it/s, loss=0.989]
SASRec epoch 8/8:  25%|██▌       | 381/1500 [00:13<00:39, 28.39it/s, loss=0.989]
SASRec epoch 8/8:  26%|██▌       | 384/1500 [00:13<00:39, 28.43it/s, loss=0.989]
SASRec epoch 8/8:  26%|██▌       | 387/1500 [00:14<00:38, 28.72it/s, loss=0.989]
SASRec epoch 8/8:  26%|██▌       | 390/1500 [00:14<00:38, 28.87it/s, loss=0.989]
SASRec epoch 8/8:  26%|██▌       | 393/1500 [00:14<00:38, 28.97it/s, loss=0.989]
SASRec epoch 8/8:  26%|██▋       | 396/1500 [00:14<00:38, 28.98it/s, loss=0.989]
SASRec epoch 8/8:  27%|██▋       | 399/1500 [00:14<00:38, 28.58it/s, loss=0.989]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:14<00:38, 28.58it/s, loss=0.97]
SASRec epoch 8/8:  27%|██▋       | 402/1500 [00:14<00:39, 28.01it/s, loss=0.97]
SASRec epoch 8/8:  27%|██▋       | 405/1500 [00:14<00:38, 28.49it/s, loss=0.97]
SASRec epoch 8/8:  27%|██▋       | 408/1500 [00:14<00:38, 28.74it/s, loss=0.97]
SASRec epoch 8/8:  27%|██▋       | 411/1500 [00:14<00:37, 29.09it/s, loss=0.97]
SASRec epoch 8/8:  28%|██▊       | 414/1500 [00:14<00:36, 29.36it/s, loss=0.97]
SASRec epoch 8/8:  28%|██▊       | 417/1500 [00:15<00:37, 29.24it/s, loss=0.97]
SASRec epoch 8/8:  28%|██▊       | 420/1500 [00:15<00:37, 29.18it/s, loss=0.97]
SASRec epoch 8/8:  28%|██▊       | 423/1500 [00:15<00:36, 29.26it/s, loss=0.97]
SASRec epoch 8/8:  28%|██▊       | 426/1500 [00:15<00:36, 29.37it/s, loss=0.97]
SASRec epoch 8/8:  29%|██▊       | 429/1500 [00:15<00:36, 29.01it/s, loss=0.97]
SASRec epoch 8/8:  29%|██▉       | 432/1500 [00:15<00:36, 29.21it/s, loss=0.97]
SASRec epoch 8/8:  29%|██▉       | 435/1500 [00:15<00:36, 29.25it/s, loss=0.97]
SASRec epoch 8/8:  29%|██▉       | 438/1500 [00:15<00:36, 29.35it/s, loss=0.97]
SASRec epoch 8/8:  29%|██▉       | 442/1500 [00:15<00:35, 29.85it/s, loss=0.97]
SASRec epoch 8/8:  30%|██▉       | 445/1500 [00:16<00:35, 29.69it/s, loss=0.97]
SASRec epoch 8/8:  30%|██▉       | 448/1500 [00:16<00:35, 29.45it/s, loss=0.97]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:16<00:35, 29.45it/s, loss=0.975]
SASRec epoch 8/8:  30%|███       | 451/1500 [00:16<00:36, 28.70it/s, loss=0.975]
SASRec epoch 8/8:  30%|███       | 454/1500 [00:16<00:36, 28.54it/s, loss=0.975]
SASRec epoch 8/8:  30%|███       | 457/1500 [00:16<00:36, 28.66it/s, loss=0.975]
SASRec epoch 8/8:  31%|███       | 460/1500 [00:16<00:36, 28.60it/s, loss=0.975]
SASRec epoch 8/8:  31%|███       | 463/1500 [00:16<00:35, 29.00it/s, loss=0.975]
SASRec epoch 8/8:  31%|███       | 466/1500 [00:16<00:35, 28.96it/s, loss=0.975]
SASRec epoch 8/8:  31%|███▏      | 469/1500 [00:16<00:35, 28.84it/s, loss=0.975]
SASRec epoch 8/8:  31%|███▏      | 472/1500 [00:16<00:35, 29.11it/s, loss=0.975]
SASRec epoch 8/8:  32%|███▏      | 475/1500 [00:17<00:35, 29.22it/s, loss=0.975]
SASRec epoch 8/8:  32%|███▏      | 478/1500 [00:17<00:34, 29.25it/s, loss=0.975]
SASRec epoch 8/8:  32%|███▏      | 481/1500 [00:17<00:34, 29.27it/s, loss=0.975]
SASRec epoch 8/8:  32%|███▏      | 484/1500 [00:17<00:34, 29.14it/s, loss=0.975]
SASRec epoch 8/8:  32%|███▏      | 487/1500 [00:17<00:34, 29.26it/s, loss=0.975]
SASRec epoch 8/8:  33%|███▎      | 490/1500 [00:17<00:34, 29.23it/s, loss=0.975]
SASRec epoch 8/8:  33%|███▎      | 493/1500 [00:17<00:34, 29.45it/s, loss=0.975]
SASRec epoch 8/8:  33%|███▎      | 496/1500 [00:17<00:33, 29.59it/s, loss=0.975]
SASRec epoch 8/8:  33%|███▎      | 499/1500 [00:17<00:33, 29.57it/s, loss=0.975]
SASRec epoch 8/8:  33%|███▎      | 500/1500 [00:17<00:33, 29.57it/s, loss=0.98]
SASRec epoch 8/8:  33%|███▎      | 502/1500 [00:18<00:35, 28.46it/s, loss=0.98]
SASRec epoch 8/8:  34%|███▎      | 505/1500 [00:18<00:35, 28.37it/s, loss=0.98]
SASRec epoch 8/8:  34%|███▍      | 508/1500 [00:18<00:34, 28.61it/s, loss=0.98]
SASRec epoch 8/8:  34%|███▍      | 511/1500 [00:18<00:34, 28.56it/s, loss=0.98]
SASRec epoch 8/8:  34%|███▍      | 514/1500 [00:18<00:34, 28.60it/s, loss=0.98]
SASRec epoch 8/8:  34%|███▍      | 517/1500 [00:18<00:34, 28.88it/s, loss=0.98]
SASRec epoch 8/8:  35%|███▍      | 520/1500 [00:18<00:34, 28.41it/s, loss=0.98]
SASRec epoch 8/8:  35%|███▍      | 523/1500 [00:18<00:34, 28.71it/s, loss=0.98]
SASRec epoch 8/8:  35%|███▌      | 526/1500 [00:18<00:33, 28.85it/s, loss=0.98]
SASRec epoch 8/8:  35%|███▌      | 529/1500 [00:18<00:33, 28.91it/s, loss=0.98]
SASRec epoch 8/8:  35%|███▌      | 532/1500 [00:19<00:33, 29.12it/s, loss=0.98]
SASRec epoch 8/8:  36%|███▌      | 535/1500 [00:19<00:33, 29.01it/s, loss=0.98]
SASRec epoch 8/8:  36%|███▌      | 538/1500 [00:19<00:33, 29.09it/s, loss=0.98]
SASRec epoch 8/8:  36%|███▌      | 541/1500 [00:19<00:33, 29.02it/s, loss=0.98]
SASRec epoch 8/8:  36%|███▋      | 544/1500 [00:19<00:34, 27.99it/s, loss=0.98]
SASRec epoch 8/8:  36%|███▋      | 547/1500 [00:19<00:35, 26.93it/s, loss=0.98]
SASRec epoch 8/8:  37%|███▋      | 550/1500 [00:19<00:37, 25.37it/s, loss=0.98]
SASRec epoch 8/8:  37%|███▋      | 550/1500 [00:19<00:37, 25.37it/s, loss=0.977]
SASRec epoch 8/8:  37%|███▋      | 553/1500 [00:19<00:37, 25.54it/s, loss=0.977]
SASRec epoch 8/8:  37%|███▋      | 556/1500 [00:19<00:36, 25.65it/s, loss=0.977]
SASRec epoch 8/8:  37%|███▋      | 559/1500 [00:20<00:35, 26.17it/s, loss=0.977]
SASRec epoch 8/8:  37%|███▋      | 562/1500 [00:20<00:35, 26.64it/s, loss=0.977]
SASRec epoch 8/8:  38%|███▊      | 565/1500 [00:20<00:34, 27.04it/s, loss=0.977]
SASRec epoch 8/8:  38%|███▊      | 568/1500 [00:20<00:34, 27.03it/s, loss=0.977]
SASRec epoch 8/8:  38%|███▊      | 571/1500 [00:20<00:33, 27.35it/s, loss=0.977]
SASRec epoch 8/8:  38%|███▊      | 574/1500 [00:20<00:33, 27.63it/s, loss=0.977]
SASRec epoch 8/8:  38%|███▊      | 577/1500 [00:20<00:33, 27.64it/s, loss=0.977]
SASRec epoch 8/8:  39%|███▊      | 580/1500 [00:20<00:34, 27.04it/s, loss=0.977]
SASRec epoch 8/8:  39%|███▉      | 583/1500 [00:20<00:33, 27.42it/s, loss=0.977]
SASRec epoch 8/8:  39%|███▉      | 586/1500 [00:21<00:32, 27.74it/s, loss=0.977]
SASRec epoch 8/8:  39%|███▉      | 589/1500 [00:21<00:32, 27.90it/s, loss=0.977]
SASRec epoch 8/8:  39%|███▉      | 592/1500 [00:21<00:32, 28.00it/s, loss=0.977]
SASRec epoch 8/8:  40%|███▉      | 595/1500 [00:21<00:32, 27.83it/s, loss=0.977]
SASRec epoch 8/8:  40%|███▉      | 598/1500 [00:21<00:32, 28.16it/s, loss=0.977]
SASRec epoch 8/8:  40%|████      | 600/1500 [00:21<00:31, 28.16it/s, loss=0.96]
SASRec epoch 8/8:  40%|████      | 601/1500 [00:21<00:31, 28.35it/s, loss=0.96]
SASRec epoch 8/8:  40%|████      | 604/1500 [00:21<00:31, 28.71it/s, loss=0.96]
SASRec epoch 8/8:  40%|████      | 607/1500 [00:21<00:31, 28.76it/s, loss=0.96]
SASRec epoch 8/8:  41%|████      | 610/1500 [00:21<00:31, 28.22it/s, loss=0.96]
SASRec epoch 8/8:  41%|████      | 613/1500 [00:22<00:32, 27.61it/s, loss=0.96]
SASRec epoch 8/8:  41%|████      | 616/1500 [00:22<00:31, 27.67it/s, loss=0.96]
SASRec epoch 8/8:  41%|████▏     | 619/1500 [00:22<00:31, 27.87it/s, loss=0.96]
SASRec epoch 8/8:  41%|████▏     | 622/1500 [00:22<00:31, 28.06it/s, loss=0.96]
SASRec epoch 8/8:  42%|████▏     | 625/1500 [00:22<00:31, 27.89it/s, loss=0.96]
SASRec epoch 8/8:  42%|████▏     | 628/1500 [00:22<00:31, 27.86it/s, loss=0.96]
SASRec epoch 8/8:  42%|████▏     | 631/1500 [00:22<00:33, 25.71it/s, loss=0.96]
SASRec epoch 8/8:  42%|████▏     | 634/1500 [00:22<00:35, 24.62it/s, loss=0.96]
SASRec epoch 8/8:  42%|████▏     | 637/1500 [00:22<00:35, 24.30it/s, loss=0.96]
SASRec epoch 8/8:  43%|████▎     | 640/1500 [00:23<00:36, 23.59it/s, loss=0.96]
SASRec epoch 8/8:  43%|████▎     | 643/1500 [00:23<00:36, 23.27it/s, loss=0.96]
SASRec epoch 8/8:  43%|████▎     | 646/1500 [00:23<00:37, 22.81it/s, loss=0.96]
SASRec epoch 8/8:  43%|████▎     | 649/1500 [00:23<00:36, 23.19it/s, loss=0.96]
SASRec epoch 8/8:  43%|████▎     | 650/1500 [00:23<00:36, 23.19it/s, loss=0.958]
SASRec epoch 8/8:  43%|████▎     | 652/1500 [00:23<00:35, 24.12it/s, loss=0.958]
SASRec epoch 8/8:  44%|████▎     | 655/1500 [00:23<00:33, 25.24it/s, loss=0.958]
SASRec epoch 8/8:  44%|████▍     | 658/1500 [00:23<00:32, 25.96it/s, loss=0.958]
SASRec epoch 8/8:  44%|████▍     | 661/1500 [00:23<00:31, 26.53it/s, loss=0.958]
SASRec epoch 8/8:  44%|████▍     | 664/1500 [00:24<00:31, 26.97it/s, loss=0.958]
SASRec epoch 8/8:  44%|████▍     | 667/1500 [00:24<00:30, 27.12it/s, loss=0.958]
SASRec epoch 8/8:  45%|████▍     | 670/1500 [00:24<00:31, 26.46it/s, loss=0.958]
SASRec epoch 8/8:  45%|████▍     | 673/1500 [00:24<00:31, 26.47it/s, loss=0.958]
SASRec epoch 8/8:  45%|████▌     | 676/1500 [00:24<00:31, 26.51it/s, loss=0.958]
SASRec epoch 8/8:  45%|████▌     | 679/1500 [00:24<00:31, 26.05it/s, loss=0.958]
SASRec epoch 8/8:  45%|████▌     | 682/1500 [00:24<00:31, 26.10it/s, loss=0.958]
SASRec epoch 8/8:  46%|████▌     | 685/1500 [00:24<00:31, 26.17it/s, loss=0.958]
SASRec epoch 8/8:  46%|████▌     | 688/1500 [00:24<00:30, 26.28it/s, loss=0.958]
SASRec epoch 8/8:  46%|████▌     | 691/1500 [00:25<00:30, 26.69it/s, loss=0.958]
SASRec epoch 8/8:  46%|████▋     | 694/1500 [00:25<00:30, 26.44it/s, loss=0.958]
SASRec epoch 8/8:  46%|████▋     | 697/1500 [00:25<00:31, 25.48it/s, loss=0.958]
SASRec epoch 8/8:  47%|████▋     | 700/1500 [00:25<00:31, 25.55it/s, loss=0.958]
SASRec epoch 8/8:  47%|████▋     | 700/1500 [00:25<00:31, 25.55it/s, loss=0.974]
SASRec epoch 8/8:  47%|████▋     | 703/1500 [00:25<00:32, 24.38it/s, loss=0.974]
SASRec epoch 8/8:  47%|████▋     | 706/1500 [00:25<00:31, 25.26it/s, loss=0.974]
SASRec epoch 8/8:  47%|████▋     | 709/1500 [00:25<00:30, 26.16it/s, loss=0.974]

[SASRec] epoch 8/8 loss=0.9621

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0031 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0056 | NDCG@100: 0.0012 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095

SASRec hyperparam search:  75%|███████▌  | 3/4 [18:04<06:21, 381.09s/it]/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(

[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0012 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0013 | NDCG@20: 0.0004 | MAP@20: 0.0002
K=50 | Recall@50: 0.0033 | NDCG@50: 0.0008 | MAP@50: 0.0002
K=100 | Recall@100: 0.0061 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target score: split=ALL K=50 Recall=0.003094

=== TRY: {'max_len': 100, 'hidden': 128, 'n_heads': 4, 'dropout': 0.3, 'lr': 0.0005} ===

SASRec epoch 1/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 1/8:   0%|          | 2/1500 [00:00<02:13, 11.22it/s]
SASRec epoch 1/8:   0%|          | 4/1500 [00:00<02:03, 12.07it/s]
SASRec epoch 1/8:   0%|          | 6/1500 [00:00<01:48, 13.72it/s]
SASRec epoch 1/8:   1%|          | 8/1500 [00:00<01:40, 14.81it/s]
SASRec epoch 1/8:   1%|          | 10/1500 [00:00<01:36, 15.51it/s]
SASRec epoch 1/8:   1%|          | 12/1500 [00:00<01:33, 15.97it/s]
SASRec epoch 1/8:   1%|          | 14/1500 [00:00<01:31, 16.23it/s]
SASRec epoch 1/8:   1%|          | 16/1500 [00:01<01:30, 16.42it/s]
SASRec epoch 1/8:   1%|          | 18/1500 [00:01<01:29, 16.63it/s]
SASRec epoch 1/8:   1%|▏         | 20/1500 [00:01<01:28, 16.65it/s]
SASRec epoch 1/8:   1%|▏         | 22/1500 [00:01<01:30, 16.35it/s]
SASRec epoch 1/8:   2%|▏         | 24/1500 [00:01<01:28, 16.60it/s]
SASRec epoch 1/8:   2%|▏         | 26/1500 [00:01<01:28, 16.65it/s]
SASRec epoch 1/8:   2%|▏         | 28/1500 [00:01<01:28, 16.69it/s]
SASRec epoch 1/8:   2%|▏         | 30/1500 [00:01<01:28, 16.62it/s]
SASRec epoch 1/8:   2%|▏         | 32/1500 [00:02<01:28, 16.64it/s]
SASRec epoch 1/8:   2%|▏         | 34/1500 [00:02<01:28, 16.65it/s]
SASRec epoch 1/8:   2%|▏         | 36/1500 [00:02<01:28, 16.62it/s]
SASRec epoch 1/8:   3%|▎         | 38/1500 [00:02<01:28, 16.48it/s]
SASRec epoch 1/8:   3%|▎         | 40/1500 [00:02<01:27, 16.63it/s]
SASRec epoch 1/8:   3%|▎         | 42/1500 [00:02<01:27, 16.70it/s]
SASRec epoch 1/8:   3%|▎         | 44/1500 [00:02<01:26, 16.75it/s]
SASRec epoch 1/8:   3%|▎         | 46/1500 [00:02<01:26, 16.77it/s]
SASRec epoch 1/8:   3%|▎         | 48/1500 [00:02<01:26, 16.74it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:03<01:26, 16.82it/s]
SASRec epoch 1/8:   3%|▎         | 50/1500 [00:03<01:26, 16.82it/s, loss=11.2]
SASRec epoch 1/8:   3%|▎         | 52/1500 [00:03<01:27, 16.59it/s, loss=11.2]
SASRec epoch 1/8:   4%|▎         | 54/1500 [00:03<01:26, 16.71it/s, loss=11.2]
SASRec epoch 1/8:   4%|▎         | 56/1500 [00:03<01:26, 16.63it/s, loss=11.2]
SASRec epoch 1/8:   4%|▍         | 58/1500 [00:03<01:26, 16.74it/s, loss=11.2]
SASRec epoch 1/8:   4%|▍         | 60/1500 [00:03<01:25, 16.77it/s, loss=11.2]
SASRec epoch 1/8:   4%|▍         | 62/1500 [00:03<01:25, 16.74it/s, loss=11.2]
SASRec epoch 1/8:   4%|▍         | 64/1500 [00:03<01:25, 16.70it/s, loss=11.2]
SASRec epoch 1/8:   4%|▍         | 66/1500 [00:04<01:25, 16.81it/s, loss=11.2]
SASRec epoch 1/8:   5%|▍         | 68/1500 [00:04<01:25, 16.83it/s, loss=11.2]
SASRec epoch 1/8:   5%|▍         | 70/1500 [00:04<01:25, 16.73it/s, loss=11.2]
SASRec epoch 1/8:   5%|▍         | 72/1500 [00:04<01:25, 16.77it/s, loss=11.2]
SASRec epoch 1/8:   5%|▍         | 74/1500 [00:04<01:25, 16.67it/s, loss=11.2]
SASRec epoch 1/8:   5%|▌         | 76/1500 [00:04<01:25, 16.61it/s, loss=11.2]
SASRec epoch 1/8:   5%|▌         | 78/1500 [00:04<01:25, 16.70it/s, loss=11.2]
SASRec epoch 1/8:   5%|▌         | 80/1500 [00:04<01:24, 16.76it/s, loss=11.2]
SASRec epoch 1/8:   5%|▌         | 82/1500 [00:04<01:24, 16.85it/s, loss=11.2]
SASRec epoch 1/8:   6%|▌         | 84/1500 [00:05<01:25, 16.52it/s, loss=11.2]
SASRec epoch 1/8:   6%|▌         | 86/1500 [00:05<01:25, 16.57it/s, loss=11.2]
SASRec epoch 1/8:   6%|▌         | 88/1500 [00:05<01:25, 16.60it/s, loss=11.2]
SASRec epoch 1/8:   6%|▌         | 90/1500 [00:05<01:24, 16.65it/s, loss=11.2]
SASRec epoch 1/8:   6%|▌         | 92/1500 [00:05<01:24, 16.57it/s, loss=11.2]
SASRec epoch 1/8:   6%|▋         | 94/1500 [00:05<01:24, 16.68it/s, loss=11.2]
SASRec epoch 1/8:   6%|▋         | 96/1500 [00:05<01:23, 16.75it/s, loss=11.2]
SASRec epoch 1/8:   7%|▋         | 98/1500 [00:05<01:23, 16.76it/s, loss=11.2]
SASRec epoch 1/8:   7%|▋         | 100/1500 [00:06<01:23, 16.80it/s, loss=11.2]
SASRec epoch 1/8:   7%|▋         | 100/1500 [00:06<01:23, 16.80it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 102/1500 [00:06<01:24, 16.55it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 104/1500 [00:06<01:23, 16.69it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 106/1500 [00:06<01:23, 16.77it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 108/1500 [00:06<01:23, 16.59it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 110/1500 [00:06<01:24, 16.48it/s, loss=9.92]
SASRec epoch 1/8:   7%|▋         | 112/1500 [00:06<01:26, 16.04it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 114/1500 [00:06<01:27, 15.84it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 116/1500 [00:07<01:26, 15.94it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 118/1500 [00:07<01:25, 16.07it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 120/1500 [00:07<01:24, 16.25it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 122/1500 [00:07<01:24, 16.26it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 124/1500 [00:07<01:24, 16.27it/s, loss=9.92]
SASRec epoch 1/8:   8%|▊         | 126/1500 [00:07<01:24, 16.17it/s, loss=9.92]
SASRec epoch 1/8:   9%|▊         | 128/1500 [00:07<01:27, 15.67it/s, loss=9.92]
SASRec epoch 1/8:   9%|▊         | 130/1500 [00:07<01:28, 15.52it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 132/1500 [00:08<01:29, 15.26it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 134/1500 [00:08<01:27, 15.56it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 136/1500 [00:08<01:26, 15.72it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 138/1500 [00:08<01:25, 15.91it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 140/1500 [00:08<01:24, 16.00it/s, loss=9.92]
SASRec epoch 1/8:   9%|▉         | 142/1500 [00:08<01:24, 16.12it/s, loss=9.92]
SASRec epoch 1/8:  10%|▉         | 144/1500 [00:08<01:25, 15.95it/s, loss=9.92]
SASRec epoch 1/8:  10%|▉         | 146/1500 [00:08<01:23, 16.13it/s, loss=9.92]
SASRec epoch 1/8:  10%|▉         | 148/1500 [00:09<01:23, 16.26it/s, loss=9.92]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:09<01:24, 16.05it/s, loss=9.92]
SASRec epoch 1/8:  10%|█         | 150/1500 [00:09<01:24, 16.05it/s, loss=9.09]
SASRec epoch 1/8:  10%|█         | 152/1500 [00:09<01:24, 16.01it/s, loss=9.09]
SASRec epoch 1/8:  10%|█         | 154/1500 [00:09<01:23, 16.17it/s, loss=9.09]
SASRec epoch 1/8:  10%|█         | 156/1500 [00:09<01:22, 16.25it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 158/1500 [00:09<01:22, 16.35it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 160/1500 [00:09<01:21, 16.42it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 162/1500 [00:09<01:23, 16.11it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 164/1500 [00:10<01:22, 16.21it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 166/1500 [00:10<01:22, 16.20it/s, loss=9.09]
SASRec epoch 1/8:  11%|█         | 168/1500 [00:10<01:22, 16.23it/s, loss=9.09]
SASRec epoch 1/8:  11%|█▏        | 170/1500 [00:10<01:21, 16.34it/s, loss=9.09]
SASRec epoch 1/8:  11%|█▏        | 172/1500 [00:10<01:20, 16.43it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 174/1500 [00:10<01:20, 16.48it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 176/1500 [00:10<01:20, 16.54it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 178/1500 [00:10<01:19, 16.56it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 180/1500 [00:11<01:19, 16.61it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 182/1500 [00:11<01:20, 16.37it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 184/1500 [00:11<01:21, 16.20it/s, loss=9.09]
SASRec epoch 1/8:  12%|█▏        | 186/1500 [00:11<01:21, 16.16it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 188/1500 [00:11<01:21, 16.09it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 190/1500 [00:11<01:21, 16.05it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 192/1500 [00:11<01:22, 15.94it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 194/1500 [00:11<01:21, 15.96it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 196/1500 [00:12<01:24, 15.42it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 198/1500 [00:12<01:25, 15.27it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:12<01:26, 14.99it/s, loss=9.09]
SASRec epoch 1/8:  13%|█▎        | 200/1500 [00:12<01:26, 14.99it/s, loss=8.36]
SASRec epoch 1/8:  13%|█▎        | 202/1500 [00:12<01:27, 14.80it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▎        | 204/1500 [00:12<01:25, 15.07it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▎        | 206/1500 [00:12<01:26, 14.91it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▍        | 208/1500 [00:12<01:25, 15.19it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▍        | 210/1500 [00:12<01:24, 15.19it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▍        | 212/1500 [00:13<01:22, 15.61it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▍        | 214/1500 [00:13<01:22, 15.64it/s, loss=8.36]
SASRec epoch 1/8:  14%|█▍        | 216/1500 [00:13<01:20, 15.96it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▍        | 218/1500 [00:13<01:19, 16.17it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▍        | 220/1500 [00:13<01:19, 16.08it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▍        | 222/1500 [00:13<01:19, 16.09it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▍        | 224/1500 [00:13<01:18, 16.35it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▌        | 226/1500 [00:13<01:17, 16.42it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▌        | 228/1500 [00:14<01:17, 16.49it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▌        | 230/1500 [00:14<01:17, 16.40it/s, loss=8.36]
SASRec epoch 1/8:  15%|█▌        | 232/1500 [00:14<01:19, 15.99it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▌        | 234/1500 [00:14<01:18, 16.17it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▌        | 236/1500 [00:14<01:17, 16.28it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▌        | 238/1500 [00:14<01:16, 16.42it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▌        | 240/1500 [00:14<01:16, 16.46it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▌        | 242/1500 [00:14<01:15, 16.58it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▋        | 244/1500 [00:15<01:15, 16.71it/s, loss=8.36]
SASRec epoch 1/8:  16%|█▋        | 246/1500 [00:15<01:15, 16.56it/s, loss=8.36]
SASRec epoch 1/8:  17%|█▋        | 248/1500 [00:15<01:15, 16.63it/s, loss=8.36]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.58it/s, loss=8.36]
SASRec epoch 1/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.58it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 252/1500 [00:15<01:16, 16.32it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 254/1500 [00:15<01:16, 16.35it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 256/1500 [00:15<01:15, 16.49it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 258/1500 [00:15<01:14, 16.57it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 260/1500 [00:16<01:14, 16.64it/s, loss=7.62]
SASRec epoch 1/8:  17%|█▋        | 262/1500 [00:16<01:14, 16.67it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 264/1500 [00:16<01:14, 16.63it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 266/1500 [00:16<01:14, 16.63it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 268/1500 [00:16<01:14, 16.64it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 270/1500 [00:16<01:13, 16.65it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 272/1500 [00:16<01:14, 16.58it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 274/1500 [00:16<01:13, 16.62it/s, loss=7.62]
SASRec epoch 1/8:  18%|█▊        | 276/1500 [00:16<01:13, 16.70it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▊        | 278/1500 [00:17<01:13, 16.62it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▊        | 280/1500 [00:17<01:13, 16.65it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 282/1500 [00:17<01:13, 16.58it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 284/1500 [00:17<01:13, 16.49it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 286/1500 [00:17<01:13, 16.60it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 288/1500 [00:17<01:13, 16.60it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 290/1500 [00:17<01:13, 16.56it/s, loss=7.62]
SASRec epoch 1/8:  19%|█▉        | 292/1500 [00:17<01:12, 16.62it/s, loss=7.62]
SASRec epoch 1/8:  20%|█▉        | 294/1500 [00:18<01:12, 16.65it/s, loss=7.62]
SASRec epoch 1/8:  20%|█▉        | 296/1500 [00:18<01:12, 16.61it/s, loss=7.62]
SASRec epoch 1/8:  20%|█▉        | 298/1500 [00:18<01:12, 16.62it/s, loss=7.62]
SASRec epoch 1/8:  20%|██        | 300/1500 [00:18<01:12, 16.55it/s, loss=7.62]
SASRec epoch 1/8:  20%|██        | 300/1500 [00:18<01:12, 16.55it/s, loss=7.07]
SASRec epoch 1/8:  20%|██        | 302/1500 [00:18<01:15, 15.82it/s, loss=7.07]
SASRec epoch 1/8:  20%|██        | 304/1500 [00:18<01:14, 16.01it/s, loss=7.07]
SASRec epoch 1/8:  20%|██        | 306/1500 [00:18<01:14, 16.05it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 308/1500 [00:18<01:13, 16.29it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 310/1500 [00:19<01:12, 16.44it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 312/1500 [00:19<01:12, 16.39it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 314/1500 [00:19<01:12, 16.47it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 316/1500 [00:19<01:11, 16.46it/s, loss=7.07]
SASRec epoch 1/8:  21%|██        | 318/1500 [00:19<01:11, 16.48it/s, loss=7.07]
SASRec epoch 1/8:  21%|██▏       | 320/1500 [00:19<01:11, 16.43it/s, loss=7.07]
SASRec epoch 1/8:  21%|██▏       | 322/1500 [00:19<01:11, 16.48it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 324/1500 [00:19<01:10, 16.56it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 326/1500 [00:20<01:10, 16.59it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 328/1500 [00:20<01:10, 16.52it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 330/1500 [00:20<01:10, 16.50it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 332/1500 [00:20<01:10, 16.53it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 334/1500 [00:20<01:10, 16.64it/s, loss=7.07]
SASRec epoch 1/8:  22%|██▏       | 336/1500 [00:20<01:10, 16.60it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 338/1500 [00:20<01:09, 16.66it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 340/1500 [00:20<01:09, 16.72it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 342/1500 [00:20<01:09, 16.65it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 344/1500 [00:21<01:09, 16.60it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 346/1500 [00:21<01:09, 16.49it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 348/1500 [00:21<01:09, 16.54it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.54it/s, loss=7.07]
SASRec epoch 1/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.54it/s, loss=6.29]
SASRec epoch 1/8:  23%|██▎       | 352/1500 [00:21<01:10, 16.24it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▎       | 354/1500 [00:21<01:11, 15.96it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▎       | 356/1500 [00:21<01:10, 16.12it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▍       | 358/1500 [00:21<01:09, 16.34it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▍       | 360/1500 [00:22<01:09, 16.36it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▍       | 362/1500 [00:22<01:09, 16.40it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▍       | 364/1500 [00:22<01:09, 16.28it/s, loss=6.29]
SASRec epoch 1/8:  24%|██▍       | 366/1500 [00:22<01:08, 16.44it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▍       | 368/1500 [00:22<01:08, 16.47it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▍       | 370/1500 [00:22<01:08, 16.57it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▍       | 372/1500 [00:22<01:09, 16.14it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▍       | 374/1500 [00:22<01:10, 16.00it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▌       | 376/1500 [00:23<01:11, 15.75it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▌       | 378/1500 [00:23<01:11, 15.73it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▌       | 380/1500 [00:23<01:11, 15.75it/s, loss=6.29]
SASRec epoch 1/8:  25%|██▌       | 382/1500 [00:23<01:11, 15.61it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▌       | 384/1500 [00:23<01:11, 15.55it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▌       | 386/1500 [00:23<01:11, 15.52it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▌       | 388/1500 [00:23<01:12, 15.30it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▌       | 390/1500 [00:23<01:11, 15.50it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▌       | 392/1500 [00:24<01:10, 15.64it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▋       | 394/1500 [00:24<01:10, 15.76it/s, loss=6.29]
SASRec epoch 1/8:  26%|██▋       | 396/1500 [00:24<01:10, 15.72it/s, loss=6.29]
SASRec epoch 1/8:  27%|██▋       | 398/1500 [00:24<01:09, 15.85it/s, loss=6.29]
SASRec epoch 1/8:  27%|██▋       | 400/1500 [00:24<01:09, 15.84it/s, loss=6.29]
SASRec epoch 1/8:  27%|██▋       | 400/1500 [00:24<01:09, 15.84it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 402/1500 [00:24<01:09, 15.77it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 404/1500 [00:24<01:08, 15.94it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 406/1500 [00:25<01:09, 15.65it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 408/1500 [00:25<01:10, 15.44it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 410/1500 [00:25<01:11, 15.22it/s, loss=5.88]
SASRec epoch 1/8:  27%|██▋       | 412/1500 [00:25<01:11, 15.28it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 414/1500 [00:25<01:11, 15.25it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 416/1500 [00:25<01:11, 15.14it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 418/1500 [00:25<01:11, 15.12it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 420/1500 [00:25<01:11, 15.10it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 422/1500 [00:26<01:11, 15.02it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 424/1500 [00:26<01:11, 15.06it/s, loss=5.88]
SASRec epoch 1/8:  28%|██▊       | 426/1500 [00:26<01:10, 15.24it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▊       | 428/1500 [00:26<01:11, 15.06it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▊       | 430/1500 [00:26<01:09, 15.29it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 432/1500 [00:26<01:08, 15.54it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 434/1500 [00:26<01:07, 15.74it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 436/1500 [00:26<01:07, 15.84it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 438/1500 [00:27<01:07, 15.83it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 440/1500 [00:27<01:07, 15.67it/s, loss=5.88]
SASRec epoch 1/8:  29%|██▉       | 442/1500 [00:27<01:07, 15.67it/s, loss=5.88]
SASRec epoch 1/8:  30%|██▉       | 444/1500 [00:27<01:07, 15.71it/s, loss=5.88]
SASRec epoch 1/8:  30%|██▉       | 446/1500 [00:27<01:08, 15.48it/s, loss=5.88]
SASRec epoch 1/8:  30%|██▉       | 448/1500 [00:27<01:08, 15.26it/s, loss=5.88]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:27<01:08, 15.29it/s, loss=5.88]
SASRec epoch 1/8:  30%|███       | 450/1500 [00:27<01:08, 15.29it/s, loss=5.44]
SASRec epoch 1/8:  30%|███       | 452/1500 [00:28<01:09, 14.98it/s, loss=5.44]
SASRec epoch 1/8:  30%|███       | 454/1500 [00:28<01:10, 14.90it/s, loss=5.44]
SASRec epoch 1/8:  30%|███       | 456/1500 [00:28<01:09, 15.06it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 458/1500 [00:28<01:08, 15.31it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 460/1500 [00:28<01:07, 15.37it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 462/1500 [00:28<01:08, 15.21it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 464/1500 [00:28<01:07, 15.38it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 466/1500 [00:28<01:06, 15.61it/s, loss=5.44]
SASRec epoch 1/8:  31%|███       | 468/1500 [00:29<01:05, 15.85it/s, loss=5.44]
SASRec epoch 1/8:  31%|███▏      | 470/1500 [00:29<01:04, 16.04it/s, loss=5.44]
SASRec epoch 1/8:  31%|███▏      | 472/1500 [00:29<01:03, 16.12it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 474/1500 [00:29<01:04, 15.97it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 476/1500 [00:29<01:03, 16.12it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 478/1500 [00:29<01:02, 16.26it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 480/1500 [00:29<01:02, 16.39it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 482/1500 [00:29<01:01, 16.42it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 484/1500 [00:30<01:01, 16.46it/s, loss=5.44]
SASRec epoch 1/8:  32%|███▏      | 486/1500 [00:30<01:01, 16.54it/s, loss=5.44]
SASRec epoch 1/8:  33%|███▎      | 488/1500 [00:30<01:00, 16.63it/s, loss=5.44]

[SASRec] epoch 1/8 loss=4.7715

SASRec epoch 2/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 2/8:   0%|          | 2/1500 [00:00<01:28, 16.84it/s]
SASRec epoch 2/8:   0%|          | 4/1500 [00:00<01:30, 16.48it/s]
SASRec epoch 2/8:   0%|          | 6/1500 [00:00<01:31, 16.30it/s]
SASRec epoch 2/8:   1%|          | 8/1500 [00:00<01:32, 16.07it/s]
SASRec epoch 2/8:   1%|          | 10/1500 [00:00<01:32, 16.05it/s]
SASRec epoch 2/8:   1%|          | 12/1500 [00:00<01:32, 16.07it/s]
SASRec epoch 2/8:   1%|          | 14/1500 [00:00<01:31, 16.22it/s]
SASRec epoch 2/8:   1%|          | 16/1500 [00:00<01:32, 16.06it/s]
SASRec epoch 2/8:   1%|          | 18/1500 [00:01<01:31, 16.16it/s]
SASRec epoch 2/8:   1%|▏         | 20/1500 [00:01<01:31, 16.22it/s]
SASRec epoch 2/8:   1%|▏         | 22/1500 [00:01<01:31, 16.15it/s]
SASRec epoch 2/8:   2%|▏         | 24/1500 [00:01<01:31, 16.07it/s]
SASRec epoch 2/8:   2%|▏         | 26/1500 [00:01<01:32, 15.95it/s]
SASRec epoch 2/8:   2%|▏         | 28/1500 [00:01<01:31, 16.15it/s]
SASRec epoch 2/8:   2%|▏         | 30/1500 [00:01<01:30, 16.17it/s]
SASRec epoch 2/8:   2%|▏         | 32/1500 [00:01<01:30, 16.19it/s]
SASRec epoch 2/8:   2%|▏         | 34/1500 [00:02<01:30, 16.20it/s]
SASRec epoch 2/8:   2%|▏         | 36/1500 [00:02<01:30, 16.14it/s]
SASRec epoch 2/8:   3%|▎         | 38/1500 [00:02<01:30, 16.15it/s]
SASRec epoch 2/8:   3%|▎         | 40/1500 [00:02<01:30, 16.11it/s]
SASRec epoch 2/8:   3%|▎         | 42/1500 [00:02<01:30, 16.14it/s]
SASRec epoch 2/8:   3%|▎         | 44/1500 [00:02<01:30, 16.12it/s]
SASRec epoch 2/8:   3%|▎         | 46/1500 [00:02<01:30, 16.03it/s]
SASRec epoch 2/8:   3%|▎         | 48/1500 [00:02<01:30, 16.07it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:03<01:30, 16.07it/s]
SASRec epoch 2/8:   3%|▎         | 50/1500 [00:03<01:30, 16.07it/s, loss=2.49]
SASRec epoch 2/8:   3%|▎         | 52/1500 [00:03<01:32, 15.66it/s, loss=2.49]
SASRec epoch 2/8:   4%|▎         | 54/1500 [00:03<01:33, 15.48it/s, loss=2.49]
SASRec epoch 2/8:   4%|▎         | 56/1500 [00:03<01:32, 15.69it/s, loss=2.49]
SASRec epoch 2/8:   4%|▍         | 58/1500 [00:03<01:31, 15.84it/s, loss=2.49]
SASRec epoch 2/8:   4%|▍         | 60/1500 [00:03<01:30, 15.99it/s, loss=2.49]
SASRec epoch 2/8:   4%|▍         | 62/1500 [00:03<01:29, 16.07it/s, loss=2.49]
SASRec epoch 2/8:   4%|▍         | 64/1500 [00:03<01:28, 16.19it/s, loss=2.49]
SASRec epoch 2/8:   4%|▍         | 66/1500 [00:04<01:28, 16.22it/s, loss=2.49]
SASRec epoch 2/8:   5%|▍         | 68/1500 [00:04<01:27, 16.30it/s, loss=2.49]
SASRec epoch 2/8:   5%|▍         | 70/1500 [00:04<01:27, 16.36it/s, loss=2.49]
SASRec epoch 2/8:   5%|▍         | 72/1500 [00:04<01:26, 16.43it/s, loss=2.49]
SASRec epoch 2/8:   5%|▍         | 74/1500 [00:04<01:26, 16.50it/s, loss=2.49]
SASRec epoch 2/8:   5%|▌         | 76/1500 [00:04<01:26, 16.47it/s, loss=2.49]
SASRec epoch 2/8:   5%|▌         | 78/1500 [00:04<01:26, 16.44it/s, loss=2.49]
SASRec epoch 2/8:   5%|▌         | 80/1500 [00:04<01:26, 16.43it/s, loss=2.49]
SASRec epoch 2/8:   5%|▌         | 82/1500 [00:05<01:25, 16.49it/s, loss=2.49]
SASRec epoch 2/8:   6%|▌         | 84/1500 [00:05<01:26, 16.42it/s, loss=2.49]
SASRec epoch 2/8:   6%|▌         | 86/1500 [00:05<01:26, 16.35it/s, loss=2.49]
SASRec epoch 2/8:   6%|▌         | 88/1500 [00:05<01:27, 16.10it/s, loss=2.49]
SASRec epoch 2/8:   6%|▌         | 90/1500 [00:05<01:27, 16.05it/s, loss=2.49]
SASRec epoch 2/8:   6%|▌         | 92/1500 [00:05<01:27, 16.11it/s, loss=2.49]
SASRec epoch 2/8:   6%|▋         | 94/1500 [00:05<01:27, 16.15it/s, loss=2.49]
SASRec epoch 2/8:   6%|▋         | 96/1500 [00:05<01:26, 16.23it/s, loss=2.49]
SASRec epoch 2/8:   7%|▋         | 98/1500 [00:06<01:26, 16.21it/s, loss=2.49]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:06<01:26, 16.27it/s, loss=2.49]
SASRec epoch 2/8:   7%|▋         | 100/1500 [00:06<01:26, 16.27it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 102/1500 [00:06<01:26, 16.21it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 104/1500 [00:06<01:25, 16.37it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 106/1500 [00:06<01:25, 16.28it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 108/1500 [00:06<01:25, 16.31it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 110/1500 [00:06<01:25, 16.32it/s, loss=2.44]
SASRec epoch 2/8:   7%|▋         | 112/1500 [00:06<01:24, 16.38it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 114/1500 [00:07<01:24, 16.46it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 116/1500 [00:07<01:23, 16.48it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 118/1500 [00:07<01:24, 16.43it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 120/1500 [00:07<01:24, 16.43it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 122/1500 [00:07<01:24, 16.37it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 124/1500 [00:07<01:24, 16.30it/s, loss=2.44]
SASRec epoch 2/8:   8%|▊         | 126/1500 [00:07<01:23, 16.36it/s, loss=2.44]
SASRec epoch 2/8:   9%|▊         | 128/1500 [00:07<01:24, 16.26it/s, loss=2.44]
SASRec epoch 2/8:   9%|▊         | 130/1500 [00:08<01:24, 16.26it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 132/1500 [00:08<01:24, 16.28it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 134/1500 [00:08<01:23, 16.30it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 136/1500 [00:08<01:23, 16.31it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 138/1500 [00:08<01:23, 16.33it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 140/1500 [00:08<01:24, 16.17it/s, loss=2.44]
SASRec epoch 2/8:   9%|▉         | 142/1500 [00:08<01:23, 16.35it/s, loss=2.44]
SASRec epoch 2/8:  10%|▉         | 144/1500 [00:08<01:23, 16.23it/s, loss=2.44]
SASRec epoch 2/8:  10%|▉         | 146/1500 [00:09<01:23, 16.24it/s, loss=2.44]
SASRec epoch 2/8:  10%|▉         | 148/1500 [00:09<01:23, 16.23it/s, loss=2.44]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:09<01:23, 16.26it/s, loss=2.44]
SASRec epoch 2/8:  10%|█         | 150/1500 [00:09<01:23, 16.26it/s, loss=2.44]
SASRec epoch 2/8:  10%|█         | 152/1500 [00:09<01:24, 15.96it/s, loss=2.44]
SASRec epoch 2/8:  10%|█         | 154/1500 [00:09<01:23, 16.10it/s, loss=2.44]
SASRec epoch 2/8:  10%|█         | 156/1500 [00:09<01:23, 16.12it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 158/1500 [00:09<01:22, 16.31it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 160/1500 [00:09<01:22, 16.25it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 162/1500 [00:09<01:21, 16.32it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 164/1500 [00:10<01:21, 16.36it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 166/1500 [00:10<01:21, 16.40it/s, loss=2.44]
SASRec epoch 2/8:  11%|█         | 168/1500 [00:10<01:21, 16.39it/s, loss=2.44]
SASRec epoch 2/8:  11%|█▏        | 170/1500 [00:10<01:20, 16.43it/s, loss=2.44]
SASRec epoch 2/8:  11%|█▏        | 172/1500 [00:10<01:21, 16.33it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 174/1500 [00:10<01:22, 16.11it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 176/1500 [00:10<01:23, 15.80it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 178/1500 [00:10<01:22, 16.01it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 180/1500 [00:11<01:22, 16.04it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 182/1500 [00:11<01:21, 16.14it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 184/1500 [00:11<01:21, 16.16it/s, loss=2.44]
SASRec epoch 2/8:  12%|█▏        | 186/1500 [00:11<01:21, 16.20it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 188/1500 [00:11<01:20, 16.26it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 190/1500 [00:11<01:22, 15.89it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 192/1500 [00:11<01:23, 15.70it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 194/1500 [00:11<01:22, 15.77it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 196/1500 [00:12<01:24, 15.42it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 198/1500 [00:12<01:25, 15.17it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:12<01:24, 15.40it/s, loss=2.44]
SASRec epoch 2/8:  13%|█▎        | 200/1500 [00:12<01:24, 15.40it/s, loss=2.35]
SASRec epoch 2/8:  13%|█▎        | 202/1500 [00:12<01:23, 15.48it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▎        | 204/1500 [00:12<01:22, 15.63it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▎        | 206/1500 [00:12<01:22, 15.77it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▍        | 208/1500 [00:12<01:21, 15.82it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▍        | 210/1500 [00:13<01:20, 15.98it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▍        | 212/1500 [00:13<01:21, 15.87it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▍        | 214/1500 [00:13<01:21, 15.83it/s, loss=2.35]
SASRec epoch 2/8:  14%|█▍        | 216/1500 [00:13<01:20, 15.91it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▍        | 218/1500 [00:13<01:20, 16.01it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▍        | 220/1500 [00:13<01:19, 16.06it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▍        | 222/1500 [00:13<01:19, 16.06it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▍        | 224/1500 [00:13<01:20, 15.88it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▌        | 226/1500 [00:14<01:20, 15.84it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▌        | 228/1500 [00:14<01:20, 15.86it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▌        | 230/1500 [00:14<01:19, 15.93it/s, loss=2.35]
SASRec epoch 2/8:  15%|█▌        | 232/1500 [00:14<01:19, 15.97it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▌        | 234/1500 [00:14<01:19, 15.85it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▌        | 236/1500 [00:14<01:19, 15.81it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▌        | 238/1500 [00:14<01:19, 15.82it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▌        | 240/1500 [00:14<01:20, 15.61it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▌        | 242/1500 [00:15<01:21, 15.46it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▋        | 244/1500 [00:15<01:20, 15.56it/s, loss=2.35]
SASRec epoch 2/8:  16%|█▋        | 246/1500 [00:15<01:20, 15.67it/s, loss=2.35]
SASRec epoch 2/8:  17%|█▋        | 248/1500 [00:15<01:19, 15.77it/s, loss=2.35]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:15<01:18, 15.89it/s, loss=2.35]
SASRec epoch 2/8:  17%|█▋        | 250/1500 [00:15<01:18, 15.89it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 252/1500 [00:15<01:19, 15.73it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 254/1500 [00:15<01:18, 15.79it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 256/1500 [00:15<01:18, 15.87it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 258/1500 [00:16<01:17, 16.00it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 260/1500 [00:16<01:18, 15.88it/s, loss=2.32]
SASRec epoch 2/8:  17%|█▋        | 262/1500 [00:16<01:17, 15.90it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 264/1500 [00:16<01:17, 16.02it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 266/1500 [00:16<01:16, 16.20it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 268/1500 [00:16<01:15, 16.30it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.23it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 272/1500 [00:16<01:16, 15.97it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 274/1500 [00:17<01:16, 16.12it/s, loss=2.32]
SASRec epoch 2/8:  18%|█▊        | 276/1500 [00:17<01:15, 16.12it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▊        | 278/1500 [00:17<01:16, 16.00it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▊        | 280/1500 [00:17<01:16, 15.88it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 282/1500 [00:17<01:16, 15.89it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 284/1500 [00:17<01:16, 15.82it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 286/1500 [00:17<01:17, 15.69it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 288/1500 [00:17<01:18, 15.42it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 290/1500 [00:18<01:20, 15.05it/s, loss=2.32]
SASRec epoch 2/8:  19%|█▉        | 292/1500 [00:18<01:18, 15.41it/s, loss=2.32]
SASRec epoch 2/8:  20%|█▉        | 294/1500 [00:18<01:16, 15.67it/s, loss=2.32]
SASRec epoch 2/8:  20%|█▉        | 296/1500 [00:18<01:16, 15.71it/s, loss=2.32]
SASRec epoch 2/8:  20%|█▉        | 298/1500 [00:18<01:16, 15.79it/s, loss=2.32]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:18<01:15, 15.88it/s, loss=2.32]
SASRec epoch 2/8:  20%|██        | 300/1500 [00:18<01:15, 15.88it/s, loss=2.3]
SASRec epoch 2/8:  20%|██        | 302/1500 [00:18<01:15, 15.81it/s, loss=2.3]
SASRec epoch 2/8:  20%|██        | 304/1500 [00:18<01:14, 15.99it/s, loss=2.3]
SASRec epoch 2/8:  20%|██        | 306/1500 [00:19<01:14, 16.09it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 308/1500 [00:19<01:13, 16.26it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 310/1500 [00:19<01:12, 16.33it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 312/1500 [00:19<01:13, 16.18it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 314/1500 [00:19<01:12, 16.31it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 316/1500 [00:19<01:12, 16.36it/s, loss=2.3]
SASRec epoch 2/8:  21%|██        | 318/1500 [00:19<01:12, 16.35it/s, loss=2.3]
SASRec epoch 2/8:  21%|██▏       | 320/1500 [00:19<01:12, 16.32it/s, loss=2.3]
SASRec epoch 2/8:  21%|██▏       | 322/1500 [00:20<01:12, 16.26it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 324/1500 [00:20<01:12, 16.27it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 326/1500 [00:20<01:12, 16.30it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 328/1500 [00:20<01:12, 16.26it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 330/1500 [00:20<01:12, 16.24it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 332/1500 [00:20<01:11, 16.30it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 334/1500 [00:20<01:11, 16.27it/s, loss=2.3]
SASRec epoch 2/8:  22%|██▏       | 336/1500 [00:20<01:11, 16.30it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 338/1500 [00:21<01:11, 16.30it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 340/1500 [00:21<01:10, 16.39it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 342/1500 [00:21<01:10, 16.37it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 344/1500 [00:21<01:10, 16.48it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 346/1500 [00:21<01:10, 16.43it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 348/1500 [00:21<01:10, 16.39it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.28it/s, loss=2.3]
SASRec epoch 2/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.28it/s, loss=2.26]
SASRec epoch 2/8:  23%|██▎       | 352/1500 [00:21<01:12, 15.92it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▎       | 354/1500 [00:22<01:11, 16.01it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▎       | 356/1500 [00:22<01:10, 16.18it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▍       | 358/1500 [00:22<01:09, 16.32it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▍       | 360/1500 [00:22<01:10, 16.23it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▍       | 362/1500 [00:22<01:09, 16.33it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▍       | 364/1500 [00:22<01:09, 16.28it/s, loss=2.26]
SASRec epoch 2/8:  24%|██▍       | 366/1500 [00:22<01:09, 16.34it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▍       | 368/1500 [00:22<01:09, 16.27it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▍       | 370/1500 [00:22<01:09, 16.26it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▍       | 372/1500 [00:23<01:09, 16.17it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.23it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.09it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▌       | 378/1500 [00:23<01:09, 16.20it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▌       | 380/1500 [00:23<01:08, 16.25it/s, loss=2.26]
SASRec epoch 2/8:  25%|██▌       | 382/1500 [00:23<01:09, 16.19it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▌       | 384/1500 [00:23<01:08, 16.26it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▌       | 386/1500 [00:23<01:08, 16.34it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▌       | 388/1500 [00:24<01:07, 16.38it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▌       | 390/1500 [00:24<01:08, 16.29it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▌       | 392/1500 [00:24<01:07, 16.30it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▋       | 394/1500 [00:24<01:08, 16.22it/s, loss=2.26]
SASRec epoch 2/8:  26%|██▋       | 396/1500 [00:24<01:07, 16.38it/s, loss=2.26]
SASRec epoch 2/8:  27%|██▋       | 398/1500 [00:24<01:07, 16.32it/s, loss=2.26]
SASRec epoch 2/8:  27%|██▋       | 400/1500 [00:24<01:08, 16.02it/s, loss=2.26]
SASRec epoch 2/8:  27%|██▋       | 400/1500 [00:24<01:08, 16.02it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 402/1500 [00:24<01:09, 15.87it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 404/1500 [00:25<01:08, 15.94it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 406/1500 [00:25<01:08, 16.02it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 408/1500 [00:25<01:08, 16.04it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 410/1500 [00:25<01:07, 16.16it/s, loss=2.21]
SASRec epoch 2/8:  27%|██▋       | 412/1500 [00:25<01:07, 16.01it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 414/1500 [00:25<01:07, 16.10it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 416/1500 [00:25<01:07, 16.02it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 418/1500 [00:25<01:07, 16.11it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 420/1500 [00:26<01:06, 16.13it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 422/1500 [00:26<01:06, 16.26it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 424/1500 [00:26<01:06, 16.29it/s, loss=2.21]
SASRec epoch 2/8:  28%|██▊       | 426/1500 [00:26<01:05, 16.35it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▊       | 428/1500 [00:26<01:05, 16.35it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▊       | 430/1500 [00:26<01:05, 16.35it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 432/1500 [00:26<01:05, 16.30it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 434/1500 [00:26<01:07, 15.77it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 436/1500 [00:27<01:06, 15.92it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 438/1500 [00:27<01:06, 16.01it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 440/1500 [00:27<01:05, 16.15it/s, loss=2.21]
SASRec epoch 2/8:  29%|██▉       | 442/1500 [00:27<01:05, 16.28it/s, loss=2.21]
SASRec epoch 2/8:  30%|██▉       | 444/1500 [00:27<01:04, 16.29it/s, loss=2.21]
SASRec epoch 2/8:  30%|██▉       | 446/1500 [00:27<01:04, 16.38it/s, loss=2.21]
SASRec epoch 2/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.27it/s, loss=2.21]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:27<01:04, 16.22it/s, loss=2.21]
SASRec epoch 2/8:  30%|███       | 450/1500 [00:27<01:04, 16.22it/s, loss=2.18]
SASRec epoch 2/8:  30%|███       | 452/1500 [00:28<01:05, 16.10it/s, loss=2.18]
SASRec epoch 2/8:  30%|███       | 454/1500 [00:28<01:05, 16.07it/s, loss=2.18]
SASRec epoch 2/8:  30%|███       | 456/1500 [00:28<01:04, 16.08it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 458/1500 [00:28<01:04, 16.10it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 460/1500 [00:28<01:04, 16.09it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 462/1500 [00:28<01:04, 16.12it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 464/1500 [00:28<01:04, 16.08it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 466/1500 [00:28<01:04, 16.14it/s, loss=2.18]
SASRec epoch 2/8:  31%|███       | 468/1500 [00:29<01:03, 16.15it/s, loss=2.18]
SASRec epoch 2/8:  31%|███▏      | 470/1500 [00:29<01:04, 16.04it/s, loss=2.18]
SASRec epoch 2/8:  31%|███▏      | 472/1500 [00:29<01:03, 16.13it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 474/1500 [00:29<01:03, 16.21it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 476/1500 [00:29<01:02, 16.32it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 478/1500 [00:29<01:02, 16.41it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 480/1500 [00:29<01:02, 16.43it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 482/1500 [00:29<01:02, 16.31it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 484/1500 [00:30<01:01, 16.43it/s, loss=2.18]
SASRec epoch 2/8:  32%|███▏      | 486/1500 [00:30<01:01, 16.47it/s, loss=2.18]
SASRec epoch 2/8:  33%|███▎      | 488/1500 [00:30<01:02, 16.22it/s, loss=2.18]

[SASRec] epoch 2/8 loss=2.0484

SASRec epoch 3/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 3/8:   0%|          | 2/1500 [00:00<01:31, 16.40it/s]
SASRec epoch 3/8:   0%|          | 4/1500 [00:00<01:31, 16.30it/s]
SASRec epoch 3/8:   0%|          | 6/1500 [00:00<01:31, 16.36it/s]
SASRec epoch 3/8:   1%|          | 8/1500 [00:00<01:30, 16.42it/s]
SASRec epoch 3/8:   1%|          | 10/1500 [00:00<01:30, 16.46it/s]
SASRec epoch 3/8:   1%|          | 12/1500 [00:00<01:30, 16.39it/s]
SASRec epoch 3/8:   1%|          | 14/1500 [00:00<01:31, 16.30it/s]
SASRec epoch 3/8:   1%|          | 16/1500 [00:00<01:33, 15.89it/s]
SASRec epoch 3/8:   1%|          | 18/1500 [00:01<01:34, 15.65it/s]
SASRec epoch 3/8:   1%|▏         | 20/1500 [00:01<01:34, 15.64it/s]
SASRec epoch 3/8:   1%|▏         | 22/1500 [00:01<01:35, 15.49it/s]
SASRec epoch 3/8:   2%|▏         | 24/1500 [00:01<01:34, 15.60it/s]
SASRec epoch 3/8:   2%|▏         | 26/1500 [00:01<01:33, 15.76it/s]
SASRec epoch 3/8:   2%|▏         | 28/1500 [00:01<01:31, 16.01it/s]
SASRec epoch 3/8:   2%|▏         | 30/1500 [00:01<01:31, 16.15it/s]
SASRec epoch 3/8:   2%|▏         | 32/1500 [00:01<01:30, 16.27it/s]
SASRec epoch 3/8:   2%|▏         | 34/1500 [00:02<01:31, 15.99it/s]
SASRec epoch 3/8:   2%|▏         | 36/1500 [00:02<01:32, 15.88it/s]
SASRec epoch 3/8:   3%|▎         | 38/1500 [00:02<01:33, 15.60it/s]
SASRec epoch 3/8:   3%|▎         | 40/1500 [00:02<01:34, 15.51it/s]
SASRec epoch 3/8:   3%|▎         | 42/1500 [00:02<01:33, 15.58it/s]
SASRec epoch 3/8:   3%|▎         | 44/1500 [00:02<01:34, 15.49it/s]
SASRec epoch 3/8:   3%|▎         | 46/1500 [00:02<01:35, 15.22it/s]
SASRec epoch 3/8:   3%|▎         | 48/1500 [00:03<01:36, 15.12it/s]
SASRec epoch 3/8:   3%|▎         | 50/1500 [00:03<01:36, 15.08it/s]
SASRec epoch 3/8:   3%|▎         | 50/1500 [00:03<01:36, 15.08it/s, loss=1.73]
SASRec epoch 3/8:   3%|▎         | 52/1500 [00:03<01:37, 14.91it/s, loss=1.73]
SASRec epoch 3/8:   4%|▎         | 54/1500 [00:03<01:36, 15.03it/s, loss=1.73]
SASRec epoch 3/8:   4%|▎         | 56/1500 [00:03<01:35, 15.15it/s, loss=1.73]
SASRec epoch 3/8:   4%|▍         | 58/1500 [00:03<01:35, 15.17it/s, loss=1.73]
SASRec epoch 3/8:   4%|▍         | 60/1500 [00:03<01:34, 15.28it/s, loss=1.73]
SASRec epoch 3/8:   4%|▍         | 62/1500 [00:03<01:32, 15.50it/s, loss=1.73]
SASRec epoch 3/8:   4%|▍         | 64/1500 [00:04<01:31, 15.71it/s, loss=1.73]
SASRec epoch 3/8:   4%|▍         | 66/1500 [00:04<01:30, 15.85it/s, loss=1.73]
SASRec epoch 3/8:   5%|▍         | 68/1500 [00:04<01:30, 15.82it/s, loss=1.73]
SASRec epoch 3/8:   5%|▍         | 70/1500 [00:04<01:29, 15.95it/s, loss=1.73]
SASRec epoch 3/8:   5%|▍         | 72/1500 [00:04<01:28, 16.17it/s, loss=1.73]
SASRec epoch 3/8:   5%|▍         | 74/1500 [00:04<01:27, 16.27it/s, loss=1.73]
SASRec epoch 3/8:   5%|▌         | 76/1500 [00:04<01:27, 16.27it/s, loss=1.73]
SASRec epoch 3/8:   5%|▌         | 78/1500 [00:04<01:26, 16.40it/s, loss=1.73]
SASRec epoch 3/8:   5%|▌         | 80/1500 [00:05<01:26, 16.41it/s, loss=1.73]
SASRec epoch 3/8:   5%|▌         | 82/1500 [00:05<01:26, 16.44it/s, loss=1.73]
SASRec epoch 3/8:   6%|▌         | 84/1500 [00:05<01:25, 16.47it/s, loss=1.73]
SASRec epoch 3/8:   6%|▌         | 86/1500 [00:05<01:25, 16.52it/s, loss=1.73]
SASRec epoch 3/8:   6%|▌         | 88/1500 [00:05<01:25, 16.52it/s, loss=1.73]
SASRec epoch 3/8:   6%|▌         | 90/1500 [00:05<01:24, 16.59it/s, loss=1.73]
SASRec epoch 3/8:   6%|▌         | 92/1500 [00:05<01:24, 16.63it/s, loss=1.73]
SASRec epoch 3/8:   6%|▋         | 94/1500 [00:05<01:24, 16.59it/s, loss=1.73]
SASRec epoch 3/8:   6%|▋         | 96/1500 [00:06<01:25, 16.40it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 98/1500 [00:06<01:26, 16.28it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:06<01:26, 16.25it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 100/1500 [00:06<01:26, 16.25it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 102/1500 [00:06<01:26, 16.23it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 104/1500 [00:06<01:27, 15.99it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 106/1500 [00:06<01:27, 15.91it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 108/1500 [00:06<01:27, 15.84it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 110/1500 [00:06<01:28, 15.72it/s, loss=1.73]
SASRec epoch 3/8:   7%|▋         | 112/1500 [00:07<01:27, 15.79it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 114/1500 [00:07<01:27, 15.76it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 116/1500 [00:07<01:30, 15.34it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 118/1500 [00:07<01:29, 15.48it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 120/1500 [00:07<01:28, 15.66it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 122/1500 [00:07<01:27, 15.68it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 124/1500 [00:07<01:28, 15.59it/s, loss=1.73]
SASRec epoch 3/8:   8%|▊         | 126/1500 [00:07<01:27, 15.74it/s, loss=1.73]
SASRec epoch 3/8:   9%|▊         | 128/1500 [00:08<01:26, 15.90it/s, loss=1.73]
SASRec epoch 3/8:   9%|▊         | 130/1500 [00:08<01:25, 16.01it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 132/1500 [00:08<01:25, 15.95it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 134/1500 [00:08<01:25, 15.93it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 136/1500 [00:08<01:25, 15.96it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 138/1500 [00:08<01:24, 16.11it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 140/1500 [00:08<01:25, 15.96it/s, loss=1.73]
SASRec epoch 3/8:   9%|▉         | 142/1500 [00:08<01:24, 16.07it/s, loss=1.73]
SASRec epoch 3/8:  10%|▉         | 144/1500 [00:09<01:23, 16.21it/s, loss=1.73]
SASRec epoch 3/8:  10%|▉         | 146/1500 [00:09<01:23, 16.24it/s, loss=1.73]
SASRec epoch 3/8:  10%|▉         | 148/1500 [00:09<01:23, 16.26it/s, loss=1.73]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:09<01:23, 16.22it/s, loss=1.73]
SASRec epoch 3/8:  10%|█         | 150/1500 [00:09<01:23, 16.22it/s, loss=1.72]
SASRec epoch 3/8:  10%|█         | 152/1500 [00:09<01:24, 15.96it/s, loss=1.72]
SASRec epoch 3/8:  10%|█         | 154/1500 [00:09<01:24, 16.01it/s, loss=1.72]
SASRec epoch 3/8:  10%|█         | 156/1500 [00:09<01:23, 16.14it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 158/1500 [00:09<01:23, 16.17it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 160/1500 [00:10<01:22, 16.21it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 162/1500 [00:10<01:22, 16.20it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 164/1500 [00:10<01:22, 16.16it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 166/1500 [00:10<01:22, 16.18it/s, loss=1.72]
SASRec epoch 3/8:  11%|█         | 168/1500 [00:10<01:21, 16.27it/s, loss=1.72]
SASRec epoch 3/8:  11%|█▏        | 170/1500 [00:10<01:21, 16.25it/s, loss=1.72]
SASRec epoch 3/8:  11%|█▏        | 172/1500 [00:10<01:21, 16.25it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 174/1500 [00:10<01:22, 16.14it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 176/1500 [00:11<01:21, 16.20it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 178/1500 [00:11<01:21, 16.15it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 180/1500 [00:11<01:21, 16.20it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 182/1500 [00:11<01:21, 16.20it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 184/1500 [00:11<01:22, 15.97it/s, loss=1.72]
SASRec epoch 3/8:  12%|█▏        | 186/1500 [00:11<01:21, 16.04it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 188/1500 [00:11<01:21, 16.13it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 190/1500 [00:11<01:20, 16.25it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 192/1500 [00:12<01:20, 16.26it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 194/1500 [00:12<01:20, 16.29it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 196/1500 [00:12<01:20, 16.30it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 198/1500 [00:12<01:19, 16.37it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.32it/s, loss=1.72]
SASRec epoch 3/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.32it/s, loss=1.71]
SASRec epoch 3/8:  13%|█▎        | 202/1500 [00:12<01:21, 15.98it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▎        | 204/1500 [00:12<01:20, 16.11it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▎        | 206/1500 [00:12<01:20, 16.15it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▍        | 208/1500 [00:13<01:20, 16.02it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▍        | 210/1500 [00:13<01:20, 16.08it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▍        | 212/1500 [00:13<01:20, 15.91it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▍        | 214/1500 [00:13<01:20, 16.02it/s, loss=1.71]
SASRec epoch 3/8:  14%|█▍        | 216/1500 [00:13<01:20, 16.02it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▍        | 218/1500 [00:13<01:19, 16.04it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▍        | 220/1500 [00:13<01:19, 16.08it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▍        | 222/1500 [00:13<01:19, 16.16it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▍        | 224/1500 [00:14<01:19, 16.05it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▌        | 226/1500 [00:14<01:18, 16.19it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▌        | 228/1500 [00:14<01:18, 16.22it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▌        | 230/1500 [00:14<01:18, 16.22it/s, loss=1.71]
SASRec epoch 3/8:  15%|█▌        | 232/1500 [00:14<01:17, 16.31it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▌        | 234/1500 [00:14<01:17, 16.34it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▌        | 236/1500 [00:14<01:17, 16.27it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▌        | 238/1500 [00:14<01:17, 16.35it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▌        | 240/1500 [00:14<01:17, 16.33it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▌        | 242/1500 [00:15<01:17, 16.24it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▋        | 244/1500 [00:15<01:17, 16.12it/s, loss=1.71]
SASRec epoch 3/8:  16%|█▋        | 246/1500 [00:15<01:17, 16.20it/s, loss=1.71]
SASRec epoch 3/8:  17%|█▋        | 248/1500 [00:15<01:16, 16.31it/s, loss=1.71]
SASRec epoch 3/8:  17%|█▋        | 250/1500 [00:15<01:16, 16.35it/s, loss=1.71]
SASRec epoch 3/8:  17%|█▋        | 250/1500 [00:15<01:16, 16.35it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 252/1500 [00:15<01:18, 15.99it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 254/1500 [00:15<01:17, 16.14it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 256/1500 [00:15<01:17, 16.11it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 258/1500 [00:16<01:16, 16.24it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 260/1500 [00:16<01:17, 16.05it/s, loss=1.69]
SASRec epoch 3/8:  17%|█▋        | 262/1500 [00:16<01:16, 16.09it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 264/1500 [00:16<01:16, 16.15it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 266/1500 [00:16<01:16, 16.10it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 268/1500 [00:16<01:16, 16.12it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.21it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 272/1500 [00:16<01:15, 16.26it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 274/1500 [00:17<01:15, 16.32it/s, loss=1.69]
SASRec epoch 3/8:  18%|█▊        | 276/1500 [00:17<01:16, 16.10it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▊        | 278/1500 [00:17<01:15, 16.14it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▊        | 280/1500 [00:17<01:16, 15.90it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 282/1500 [00:17<01:17, 15.64it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 284/1500 [00:17<01:17, 15.62it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 286/1500 [00:17<01:16, 15.77it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 288/1500 [00:17<01:16, 15.88it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 290/1500 [00:18<01:17, 15.67it/s, loss=1.69]
SASRec epoch 3/8:  19%|█▉        | 292/1500 [00:18<01:16, 15.73it/s, loss=1.69]
SASRec epoch 3/8:  20%|█▉        | 294/1500 [00:18<01:16, 15.71it/s, loss=1.69]
SASRec epoch 3/8:  20%|█▉        | 296/1500 [00:18<01:16, 15.77it/s, loss=1.69]
SASRec epoch 3/8:  20%|█▉        | 298/1500 [00:18<01:15, 15.91it/s, loss=1.69]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:18<01:14, 16.02it/s, loss=1.69]
SASRec epoch 3/8:  20%|██        | 300/1500 [00:18<01:14, 16.02it/s, loss=1.71]
SASRec epoch 3/8:  20%|██        | 302/1500 [00:18<01:14, 15.98it/s, loss=1.71]
SASRec epoch 3/8:  20%|██        | 304/1500 [00:18<01:14, 15.95it/s, loss=1.71]
SASRec epoch 3/8:  20%|██        | 306/1500 [00:19<01:14, 15.99it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 308/1500 [00:19<01:14, 16.00it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 310/1500 [00:19<01:13, 16.10it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 312/1500 [00:19<01:14, 15.95it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 314/1500 [00:19<01:15, 15.71it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 316/1500 [00:19<01:16, 15.46it/s, loss=1.71]
SASRec epoch 3/8:  21%|██        | 318/1500 [00:19<01:17, 15.28it/s, loss=1.71]
SASRec epoch 3/8:  21%|██▏       | 320/1500 [00:20<01:17, 15.23it/s, loss=1.71]
SASRec epoch 3/8:  21%|██▏       | 322/1500 [00:20<01:18, 15.10it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 324/1500 [00:20<01:17, 15.12it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 326/1500 [00:20<01:17, 15.14it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 328/1500 [00:20<01:16, 15.39it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 330/1500 [00:20<01:16, 15.23it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 332/1500 [00:20<01:14, 15.60it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 334/1500 [00:20<01:16, 15.28it/s, loss=1.71]
SASRec epoch 3/8:  22%|██▏       | 336/1500 [00:21<01:16, 15.26it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 338/1500 [00:21<01:14, 15.53it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 340/1500 [00:21<01:15, 15.31it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 342/1500 [00:21<01:15, 15.29it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 344/1500 [00:21<01:14, 15.44it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 346/1500 [00:21<01:13, 15.66it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 348/1500 [00:21<01:13, 15.70it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 350/1500 [00:21<01:11, 15.97it/s, loss=1.71]
SASRec epoch 3/8:  23%|██▎       | 350/1500 [00:21<01:11, 15.97it/s, loss=1.69]
SASRec epoch 3/8:  23%|██▎       | 352/1500 [00:22<01:11, 16.14it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▎       | 354/1500 [00:22<01:10, 16.28it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▎       | 356/1500 [00:22<01:09, 16.38it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▍       | 358/1500 [00:22<01:09, 16.37it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▍       | 360/1500 [00:22<01:09, 16.29it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▍       | 362/1500 [00:22<01:09, 16.36it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▍       | 364/1500 [00:22<01:09, 16.34it/s, loss=1.69]
SASRec epoch 3/8:  24%|██▍       | 366/1500 [00:22<01:10, 16.13it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▍       | 368/1500 [00:23<01:10, 16.16it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▍       | 370/1500 [00:23<01:09, 16.21it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▍       | 372/1500 [00:23<01:09, 16.14it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.13it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.17it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▌       | 378/1500 [00:23<01:09, 16.23it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▌       | 380/1500 [00:23<01:09, 16.15it/s, loss=1.69]
SASRec epoch 3/8:  25%|██▌       | 382/1500 [00:23<01:09, 16.13it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▌       | 384/1500 [00:24<01:10, 15.92it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▌       | 386/1500 [00:24<01:09, 16.12it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▌       | 388/1500 [00:24<01:08, 16.15it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▌       | 390/1500 [00:24<01:08, 16.27it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▌       | 392/1500 [00:24<01:07, 16.37it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▋       | 394/1500 [00:24<01:07, 16.38it/s, loss=1.69]
SASRec epoch 3/8:  26%|██▋       | 396/1500 [00:24<01:07, 16.46it/s, loss=1.69]
SASRec epoch 3/8:  27%|██▋       | 398/1500 [00:24<01:06, 16.48it/s, loss=1.69]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:25<01:06, 16.53it/s, loss=1.69]
SASRec epoch 3/8:  27%|██▋       | 400/1500 [00:25<01:06, 16.53it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 402/1500 [00:25<01:09, 15.90it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 404/1500 [00:25<01:09, 15.87it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 406/1500 [00:25<01:09, 15.75it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 408/1500 [00:25<01:08, 15.93it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 410/1500 [00:25<01:07, 16.04it/s, loss=1.67]
SASRec epoch 3/8:  27%|██▋       | 412/1500 [00:25<01:07, 16.07it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 414/1500 [00:25<01:07, 16.20it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 416/1500 [00:26<01:06, 16.26it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 418/1500 [00:26<01:06, 16.22it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 420/1500 [00:26<01:07, 15.89it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 422/1500 [00:26<01:07, 16.03it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 424/1500 [00:26<01:06, 16.13it/s, loss=1.67]
SASRec epoch 3/8:  28%|██▊       | 426/1500 [00:26<01:06, 16.12it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▊       | 428/1500 [00:26<01:06, 16.05it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▊       | 430/1500 [00:26<01:06, 16.13it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 432/1500 [00:27<01:06, 16.13it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 434/1500 [00:27<01:06, 16.07it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 436/1500 [00:27<01:06, 16.10it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 438/1500 [00:27<01:05, 16.13it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 440/1500 [00:27<01:05, 16.10it/s, loss=1.67]
SASRec epoch 3/8:  29%|██▉       | 442/1500 [00:27<01:05, 16.23it/s, loss=1.67]
SASRec epoch 3/8:  30%|██▉       | 444/1500 [00:27<01:05, 16.24it/s, loss=1.67]
SASRec epoch 3/8:  30%|██▉       | 446/1500 [00:27<01:05, 16.19it/s, loss=1.67]
SASRec epoch 3/8:  30%|██▉       | 448/1500 [00:28<01:04, 16.28it/s, loss=1.67]
SASRec epoch 3/8:  30%|███       | 450/1500 [00:28<01:04, 16.31it/s, loss=1.67]
SASRec epoch 3/8:  30%|███       | 450/1500 [00:28<01:04, 16.31it/s, loss=1.65]
SASRec epoch 3/8:  30%|███       | 452/1500 [00:28<01:05, 16.08it/s, loss=1.65]
SASRec epoch 3/8:  30%|███       | 454/1500 [00:28<01:06, 15.83it/s, loss=1.65]
SASRec epoch 3/8:  30%|███       | 456/1500 [00:28<01:05, 15.96it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 458/1500 [00:28<01:04, 16.04it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 460/1500 [00:28<01:04, 16.13it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 462/1500 [00:28<01:04, 16.17it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 464/1500 [00:29<01:03, 16.21it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 466/1500 [00:29<01:03, 16.20it/s, loss=1.65]
SASRec epoch 3/8:  31%|███       | 468/1500 [00:29<01:03, 16.26it/s, loss=1.65]
SASRec epoch 3/8:  31%|███▏      | 470/1500 [00:29<01:03, 16.24it/s, loss=1.65]
SASRec epoch 3/8:  31%|███▏      | 472/1500 [00:29<01:03, 16.23it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 474/1500 [00:29<01:03, 16.25it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 476/1500 [00:29<01:03, 16.23it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 478/1500 [00:29<01:03, 16.13it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 480/1500 [00:29<01:02, 16.24it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 482/1500 [00:30<01:02, 16.26it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 484/1500 [00:30<01:02, 16.30it/s, loss=1.65]
SASRec epoch 3/8:  32%|███▏      | 486/1500 [00:30<01:02, 16.34it/s, loss=1.65]
SASRec epoch 3/8:  33%|███▎      | 488/1500 [00:30<01:02, 16.18it/s, loss=1.65]

[SASRec] epoch 3/8 loss=1.6106

SASRec epoch 4/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 4/8:   0%|          | 2/1500 [00:00<01:31, 16.39it/s]
SASRec epoch 4/8:   0%|          | 4/1500 [00:00<01:32, 16.14it/s]
SASRec epoch 4/8:   0%|          | 6/1500 [00:00<01:33, 16.06it/s]
SASRec epoch 4/8:   1%|          | 8/1500 [00:00<01:31, 16.28it/s]
SASRec epoch 4/8:   1%|          | 10/1500 [00:00<01:31, 16.36it/s]
SASRec epoch 4/8:   1%|          | 12/1500 [00:00<01:30, 16.43it/s]
SASRec epoch 4/8:   1%|          | 14/1500 [00:00<01:30, 16.48it/s]
SASRec epoch 4/8:   1%|          | 16/1500 [00:00<01:30, 16.46it/s]
SASRec epoch 4/8:   1%|          | 18/1500 [00:01<01:31, 16.27it/s]
SASRec epoch 4/8:   1%|▏         | 20/1500 [00:01<01:30, 16.27it/s]
SASRec epoch 4/8:   1%|▏         | 22/1500 [00:01<01:30, 16.29it/s]
SASRec epoch 4/8:   2%|▏         | 24/1500 [00:01<01:30, 16.27it/s]
SASRec epoch 4/8:   2%|▏         | 26/1500 [00:01<01:30, 16.31it/s]
SASRec epoch 4/8:   2%|▏         | 28/1500 [00:01<01:30, 16.30it/s]
SASRec epoch 4/8:   2%|▏         | 30/1500 [00:01<01:30, 16.31it/s]
SASRec epoch 4/8:   2%|▏         | 32/1500 [00:01<01:30, 16.29it/s]
SASRec epoch 4/8:   2%|▏         | 34/1500 [00:02<01:30, 16.24it/s]
SASRec epoch 4/8:   2%|▏         | 36/1500 [00:02<01:29, 16.28it/s]
SASRec epoch 4/8:   3%|▎         | 38/1500 [00:02<01:29, 16.31it/s]
SASRec epoch 4/8:   3%|▎         | 40/1500 [00:02<01:30, 16.19it/s]
SASRec epoch 4/8:   3%|▎         | 42/1500 [00:02<01:29, 16.24it/s]
SASRec epoch 4/8:   3%|▎         | 44/1500 [00:02<01:29, 16.27it/s]
SASRec epoch 4/8:   3%|▎         | 46/1500 [00:02<01:28, 16.34it/s]
SASRec epoch 4/8:   3%|▎         | 48/1500 [00:02<01:28, 16.43it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:03<01:28, 16.40it/s]
SASRec epoch 4/8:   3%|▎         | 50/1500 [00:03<01:28, 16.40it/s, loss=1.5]
SASRec epoch 4/8:   3%|▎         | 52/1500 [00:03<01:29, 16.18it/s, loss=1.5]
SASRec epoch 4/8:   4%|▎         | 54/1500 [00:03<01:28, 16.31it/s, loss=1.5]
SASRec epoch 4/8:   4%|▎         | 56/1500 [00:03<01:27, 16.43it/s, loss=1.5]
SASRec epoch 4/8:   4%|▍         | 58/1500 [00:03<01:27, 16.43it/s, loss=1.5]
SASRec epoch 4/8:   4%|▍         | 60/1500 [00:03<01:27, 16.41it/s, loss=1.5]
SASRec epoch 4/8:   4%|▍         | 62/1500 [00:03<01:27, 16.42it/s, loss=1.5]
SASRec epoch 4/8:   4%|▍         | 64/1500 [00:03<01:27, 16.40it/s, loss=1.5]
SASRec epoch 4/8:   4%|▍         | 66/1500 [00:04<01:27, 16.40it/s, loss=1.5]
SASRec epoch 4/8:   5%|▍         | 68/1500 [00:04<01:28, 16.18it/s, loss=1.5]
SASRec epoch 4/8:   5%|▍         | 70/1500 [00:04<01:28, 16.25it/s, loss=1.5]
SASRec epoch 4/8:   5%|▍         | 72/1500 [00:04<01:27, 16.34it/s, loss=1.5]
SASRec epoch 4/8:   5%|▍         | 74/1500 [00:04<01:26, 16.42it/s, loss=1.5]
SASRec epoch 4/8:   5%|▌         | 76/1500 [00:04<01:26, 16.46it/s, loss=1.5]
SASRec epoch 4/8:   5%|▌         | 78/1500 [00:04<01:26, 16.47it/s, loss=1.5]
SASRec epoch 4/8:   5%|▌         | 80/1500 [00:04<01:27, 16.19it/s, loss=1.5]
SASRec epoch 4/8:   5%|▌         | 82/1500 [00:05<01:26, 16.30it/s, loss=1.5]
SASRec epoch 4/8:   6%|▌         | 84/1500 [00:05<01:26, 16.38it/s, loss=1.5]
SASRec epoch 4/8:   6%|▌         | 86/1500 [00:05<01:26, 16.36it/s, loss=1.5]
SASRec epoch 4/8:   6%|▌         | 88/1500 [00:05<01:26, 16.38it/s, loss=1.5]
SASRec epoch 4/8:   6%|▌         | 90/1500 [00:05<01:26, 16.33it/s, loss=1.5]
SASRec epoch 4/8:   6%|▌         | 92/1500 [00:05<01:25, 16.46it/s, loss=1.5]
SASRec epoch 4/8:   6%|▋         | 94/1500 [00:05<01:26, 16.34it/s, loss=1.5]
SASRec epoch 4/8:   6%|▋         | 96/1500 [00:05<01:26, 16.29it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 98/1500 [00:06<01:25, 16.31it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 100/1500 [00:06<01:25, 16.37it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 100/1500 [00:06<01:25, 16.37it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 102/1500 [00:06<01:26, 16.22it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 104/1500 [00:06<01:26, 16.13it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 106/1500 [00:06<01:25, 16.28it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 108/1500 [00:06<01:25, 16.29it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 110/1500 [00:06<01:25, 16.21it/s, loss=1.5]
SASRec epoch 4/8:   7%|▋         | 112/1500 [00:06<01:25, 16.27it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 114/1500 [00:06<01:24, 16.31it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 116/1500 [00:07<01:25, 16.20it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 118/1500 [00:07<01:24, 16.27it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 120/1500 [00:07<01:26, 15.93it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 122/1500 [00:07<01:27, 15.79it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 124/1500 [00:07<01:25, 16.02it/s, loss=1.5]
SASRec epoch 4/8:   8%|▊         | 126/1500 [00:07<01:26, 15.96it/s, loss=1.5]
SASRec epoch 4/8:   9%|▊         | 128/1500 [00:07<01:26, 15.86it/s, loss=1.5]
SASRec epoch 4/8:   9%|▊         | 130/1500 [00:07<01:25, 16.08it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 132/1500 [00:08<01:24, 16.11it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 134/1500 [00:08<01:24, 16.16it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 136/1500 [00:08<01:24, 16.17it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 138/1500 [00:08<01:24, 16.11it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 140/1500 [00:08<01:24, 16.07it/s, loss=1.5]
SASRec epoch 4/8:   9%|▉         | 142/1500 [00:08<01:25, 15.82it/s, loss=1.5]
SASRec epoch 4/8:  10%|▉         | 144/1500 [00:08<01:27, 15.50it/s, loss=1.5]
SASRec epoch 4/8:  10%|▉         | 146/1500 [00:09<01:27, 15.46it/s, loss=1.5]
SASRec epoch 4/8:  10%|▉         | 148/1500 [00:09<01:26, 15.67it/s, loss=1.5]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:09<01:28, 15.26it/s, loss=1.5]
SASRec epoch 4/8:  10%|█         | 150/1500 [00:09<01:28, 15.26it/s, loss=1.48]
SASRec epoch 4/8:  10%|█         | 152/1500 [00:09<01:30, 14.82it/s, loss=1.48]
SASRec epoch 4/8:  10%|█         | 154/1500 [00:09<01:29, 14.99it/s, loss=1.48]
SASRec epoch 4/8:  10%|█         | 156/1500 [00:09<01:30, 14.90it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 158/1500 [00:09<01:30, 14.89it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 160/1500 [00:09<01:29, 15.02it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 162/1500 [00:10<01:28, 15.14it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 164/1500 [00:10<01:29, 14.99it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 166/1500 [00:10<01:27, 15.16it/s, loss=1.48]
SASRec epoch 4/8:  11%|█         | 168/1500 [00:10<01:28, 15.10it/s, loss=1.48]
SASRec epoch 4/8:  11%|█▏        | 170/1500 [00:10<01:27, 15.15it/s, loss=1.48]
SASRec epoch 4/8:  11%|█▏        | 172/1500 [00:10<01:27, 15.23it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 174/1500 [00:10<01:25, 15.53it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 176/1500 [00:10<01:26, 15.37it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 178/1500 [00:11<01:25, 15.43it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 180/1500 [00:11<01:25, 15.44it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 182/1500 [00:11<01:25, 15.49it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 184/1500 [00:11<01:26, 15.17it/s, loss=1.48]
SASRec epoch 4/8:  12%|█▏        | 186/1500 [00:11<01:25, 15.34it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 188/1500 [00:11<01:24, 15.54it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 190/1500 [00:11<01:24, 15.47it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 192/1500 [00:12<01:24, 15.50it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 194/1500 [00:12<01:23, 15.72it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 196/1500 [00:12<01:22, 15.80it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 198/1500 [00:12<01:22, 15.79it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 200/1500 [00:12<01:22, 15.80it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 200/1500 [00:12<01:22, 15.80it/s, loss=1.48]
SASRec epoch 4/8:  13%|█▎        | 202/1500 [00:12<01:22, 15.77it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▎        | 204/1500 [00:12<01:21, 15.81it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▎        | 206/1500 [00:12<01:22, 15.69it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▍        | 208/1500 [00:13<01:22, 15.61it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▍        | 210/1500 [00:13<01:22, 15.63it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▍        | 212/1500 [00:13<01:22, 15.67it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▍        | 214/1500 [00:13<01:22, 15.59it/s, loss=1.48]
SASRec epoch 4/8:  14%|█▍        | 216/1500 [00:13<01:21, 15.68it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▍        | 218/1500 [00:13<01:20, 15.95it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▍        | 220/1500 [00:13<01:19, 16.11it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▍        | 222/1500 [00:13<01:19, 16.05it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▍        | 224/1500 [00:14<01:18, 16.21it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▌        | 226/1500 [00:14<01:18, 16.18it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▌        | 228/1500 [00:14<01:18, 16.19it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▌        | 230/1500 [00:14<01:18, 16.22it/s, loss=1.48]
SASRec epoch 4/8:  15%|█▌        | 232/1500 [00:14<01:17, 16.34it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▌        | 234/1500 [00:14<01:17, 16.40it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▌        | 236/1500 [00:14<01:16, 16.42it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▌        | 238/1500 [00:14<01:16, 16.49it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▌        | 240/1500 [00:15<01:16, 16.38it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▌        | 242/1500 [00:15<01:16, 16.44it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▋        | 244/1500 [00:15<01:16, 16.42it/s, loss=1.48]
SASRec epoch 4/8:  16%|█▋        | 246/1500 [00:15<01:15, 16.52it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 248/1500 [00:15<01:16, 16.42it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.45it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.45it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 252/1500 [00:15<01:16, 16.33it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 254/1500 [00:15<01:16, 16.39it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 256/1500 [00:15<01:16, 16.36it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 258/1500 [00:16<01:16, 16.19it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 260/1500 [00:16<01:16, 16.23it/s, loss=1.48]
SASRec epoch 4/8:  17%|█▋        | 262/1500 [00:16<01:16, 16.29it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 264/1500 [00:16<01:16, 16.21it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 266/1500 [00:16<01:15, 16.25it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 268/1500 [00:16<01:15, 16.26it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.32it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 272/1500 [00:16<01:15, 16.22it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 274/1500 [00:17<01:16, 16.12it/s, loss=1.48]
SASRec epoch 4/8:  18%|█▊        | 276/1500 [00:17<01:16, 16.06it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▊        | 278/1500 [00:17<01:15, 16.14it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▊        | 280/1500 [00:17<01:15, 16.16it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 282/1500 [00:17<01:14, 16.28it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 284/1500 [00:17<01:14, 16.31it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 286/1500 [00:17<01:14, 16.21it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 288/1500 [00:17<01:14, 16.32it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 290/1500 [00:18<01:13, 16.41it/s, loss=1.48]
SASRec epoch 4/8:  19%|█▉        | 292/1500 [00:18<01:13, 16.37it/s, loss=1.48]
SASRec epoch 4/8:  20%|█▉        | 294/1500 [00:18<01:13, 16.38it/s, loss=1.48]
SASRec epoch 4/8:  20%|█▉        | 296/1500 [00:18<01:13, 16.38it/s, loss=1.48]
SASRec epoch 4/8:  20%|█▉        | 298/1500 [00:18<01:13, 16.40it/s, loss=1.48]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:18<01:13, 16.38it/s, loss=1.48]
SASRec epoch 4/8:  20%|██        | 300/1500 [00:18<01:13, 16.38it/s, loss=1.47]
SASRec epoch 4/8:  20%|██        | 302/1500 [00:18<01:15, 15.97it/s, loss=1.47]
SASRec epoch 4/8:  20%|██        | 304/1500 [00:18<01:14, 16.05it/s, loss=1.47]
SASRec epoch 4/8:  20%|██        | 306/1500 [00:19<01:13, 16.21it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 308/1500 [00:19<01:13, 16.32it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 310/1500 [00:19<01:14, 16.03it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 312/1500 [00:19<01:13, 16.14it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 314/1500 [00:19<01:13, 16.18it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 316/1500 [00:19<01:12, 16.31it/s, loss=1.47]
SASRec epoch 4/8:  21%|██        | 318/1500 [00:19<01:12, 16.30it/s, loss=1.47]
SASRec epoch 4/8:  21%|██▏       | 320/1500 [00:19<01:11, 16.40it/s, loss=1.47]
SASRec epoch 4/8:  21%|██▏       | 322/1500 [00:20<01:12, 16.34it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 324/1500 [00:20<01:11, 16.39it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 326/1500 [00:20<01:11, 16.34it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 328/1500 [00:20<01:11, 16.39it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 330/1500 [00:20<01:11, 16.29it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 332/1500 [00:20<01:11, 16.24it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 334/1500 [00:20<01:11, 16.26it/s, loss=1.47]
SASRec epoch 4/8:  22%|██▏       | 336/1500 [00:20<01:11, 16.32it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 338/1500 [00:21<01:11, 16.24it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 340/1500 [00:21<01:11, 16.22it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 342/1500 [00:21<01:10, 16.37it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 344/1500 [00:21<01:11, 16.28it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 346/1500 [00:21<01:10, 16.32it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 348/1500 [00:21<01:10, 16.38it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.45it/s, loss=1.47]
SASRec epoch 4/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.45it/s, loss=1.45]
SASRec epoch 4/8:  23%|██▎       | 352/1500 [00:21<01:11, 16.09it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▎       | 354/1500 [00:22<01:11, 16.00it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▎       | 356/1500 [00:22<01:11, 15.99it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▍       | 358/1500 [00:22<01:10, 16.12it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▍       | 360/1500 [00:22<01:11, 16.02it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▍       | 362/1500 [00:22<01:11, 15.93it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▍       | 364/1500 [00:22<01:10, 16.08it/s, loss=1.45]
SASRec epoch 4/8:  24%|██▍       | 366/1500 [00:22<01:10, 16.06it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▍       | 368/1500 [00:22<01:10, 16.13it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▍       | 370/1500 [00:23<01:09, 16.20it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▍       | 372/1500 [00:23<01:09, 16.17it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.19it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.16it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▌       | 378/1500 [00:23<01:10, 15.92it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▌       | 380/1500 [00:23<01:10, 15.78it/s, loss=1.45]
SASRec epoch 4/8:  25%|██▌       | 382/1500 [00:23<01:11, 15.57it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▌       | 384/1500 [00:23<01:11, 15.68it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▌       | 386/1500 [00:24<01:11, 15.57it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▌       | 388/1500 [00:24<01:12, 15.38it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▌       | 390/1500 [00:24<01:12, 15.28it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▌       | 392/1500 [00:24<01:11, 15.44it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▋       | 394/1500 [00:24<01:12, 15.24it/s, loss=1.45]
SASRec epoch 4/8:  26%|██▋       | 396/1500 [00:24<01:13, 15.11it/s, loss=1.45]
SASRec epoch 4/8:  27%|██▋       | 398/1500 [00:24<01:13, 14.95it/s, loss=1.45]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:24<01:11, 15.30it/s, loss=1.45]
SASRec epoch 4/8:  27%|██▋       | 400/1500 [00:24<01:11, 15.30it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 402/1500 [00:25<01:10, 15.56it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 404/1500 [00:25<01:09, 15.88it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 406/1500 [00:25<01:07, 16.10it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 408/1500 [00:25<01:07, 16.12it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 410/1500 [00:25<01:09, 15.73it/s, loss=1.46]
SASRec epoch 4/8:  27%|██▋       | 412/1500 [00:25<01:09, 15.57it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 414/1500 [00:25<01:09, 15.69it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 416/1500 [00:25<01:09, 15.67it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 418/1500 [00:26<01:08, 15.72it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 420/1500 [00:26<01:08, 15.71it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 422/1500 [00:26<01:08, 15.84it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 424/1500 [00:26<01:07, 15.86it/s, loss=1.46]
SASRec epoch 4/8:  28%|██▊       | 426/1500 [00:26<01:06, 16.06it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▊       | 428/1500 [00:26<01:05, 16.27it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▊       | 430/1500 [00:26<01:06, 16.13it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 432/1500 [00:26<01:08, 15.63it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 434/1500 [00:27<01:08, 15.49it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 436/1500 [00:27<01:08, 15.64it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 438/1500 [00:27<01:07, 15.76it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 440/1500 [00:27<01:06, 16.03it/s, loss=1.46]
SASRec epoch 4/8:  29%|██▉       | 442/1500 [00:27<01:05, 16.15it/s, loss=1.46]
SASRec epoch 4/8:  30%|██▉       | 444/1500 [00:27<01:04, 16.35it/s, loss=1.46]
SASRec epoch 4/8:  30%|██▉       | 446/1500 [00:27<01:04, 16.39it/s, loss=1.46]
SASRec epoch 4/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.30it/s, loss=1.46]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:28<01:04, 16.18it/s, loss=1.46]
SASRec epoch 4/8:  30%|███       | 450/1500 [00:28<01:04, 16.18it/s, loss=1.44]
SASRec epoch 4/8:  30%|███       | 452/1500 [00:28<01:05, 15.93it/s, loss=1.44]
SASRec epoch 4/8:  30%|███       | 454/1500 [00:28<01:05, 15.93it/s, loss=1.44]
SASRec epoch 4/8:  30%|███       | 456/1500 [00:28<01:05, 15.97it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 458/1500 [00:28<01:04, 16.18it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 460/1500 [00:28<01:03, 16.29it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 462/1500 [00:28<01:03, 16.22it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 464/1500 [00:28<01:04, 16.12it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 466/1500 [00:29<01:04, 16.07it/s, loss=1.44]
SASRec epoch 4/8:  31%|███       | 468/1500 [00:29<01:03, 16.13it/s, loss=1.44]
SASRec epoch 4/8:  31%|███▏      | 470/1500 [00:29<01:03, 16.19it/s, loss=1.44]
SASRec epoch 4/8:  31%|███▏      | 472/1500 [00:29<01:04, 15.95it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 474/1500 [00:29<01:04, 15.89it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 476/1500 [00:29<01:04, 15.97it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 478/1500 [00:29<01:03, 16.19it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 480/1500 [00:29<01:02, 16.36it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 482/1500 [00:30<01:01, 16.49it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 484/1500 [00:30<01:01, 16.46it/s, loss=1.44]
SASRec epoch 4/8:  32%|███▏      | 486/1500 [00:30<01:01, 16.44it/s, loss=1.44]
SASRec epoch 4/8:  33%|███▎      | 488/1500 [00:30<01:01, 16.42it/s, loss=1.44]
SASRec epoch 4/8:  33%|███▎      | 490/1500 [00:30<01:02, 16.29it/s, loss=1.44]

[SASRec] epoch 4/8 loss=1.4271

SASRec epoch 5/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 5/8:   0%|          | 2/1500 [00:00<01:33, 16.05it/s]
SASRec epoch 5/8:   0%|          | 4/1500 [00:00<01:32, 16.16it/s]
SASRec epoch 5/8:   0%|          | 6/1500 [00:00<01:32, 16.18it/s]
SASRec epoch 5/8:   1%|          | 8/1500 [00:00<01:32, 16.19it/s]
SASRec epoch 5/8:   1%|          | 10/1500 [00:00<01:31, 16.23it/s]
SASRec epoch 5/8:   1%|          | 12/1500 [00:00<01:31, 16.30it/s]
SASRec epoch 5/8:   1%|          | 14/1500 [00:00<01:31, 16.24it/s]
SASRec epoch 5/8:   1%|          | 16/1500 [00:00<01:31, 16.23it/s]
SASRec epoch 5/8:   1%|          | 18/1500 [00:01<01:32, 16.00it/s]
SASRec epoch 5/8:   1%|▏         | 20/1500 [00:01<01:32, 16.01it/s]
SASRec epoch 5/8:   1%|▏         | 22/1500 [00:01<01:32, 15.96it/s]
SASRec epoch 5/8:   2%|▏         | 24/1500 [00:01<01:33, 15.86it/s]
SASRec epoch 5/8:   2%|▏         | 26/1500 [00:01<01:33, 15.81it/s]
SASRec epoch 5/8:   2%|▏         | 28/1500 [00:01<01:34, 15.59it/s]
SASRec epoch 5/8:   2%|▏         | 30/1500 [00:01<01:34, 15.62it/s]
SASRec epoch 5/8:   2%|▏         | 32/1500 [00:02<01:33, 15.74it/s]
SASRec epoch 5/8:   2%|▏         | 34/1500 [00:02<01:32, 15.82it/s]
SASRec epoch 5/8:   2%|▏         | 36/1500 [00:02<01:32, 15.91it/s]
SASRec epoch 5/8:   3%|▎         | 38/1500 [00:02<01:33, 15.71it/s]
SASRec epoch 5/8:   3%|▎         | 40/1500 [00:02<01:32, 15.77it/s]
SASRec epoch 5/8:   3%|▎         | 42/1500 [00:02<01:31, 15.98it/s]
SASRec epoch 5/8:   3%|▎         | 44/1500 [00:02<01:30, 16.16it/s]
SASRec epoch 5/8:   3%|▎         | 46/1500 [00:02<01:29, 16.33it/s]
SASRec epoch 5/8:   3%|▎         | 48/1500 [00:02<01:28, 16.46it/s]
SASRec epoch 5/8:   3%|▎         | 50/1500 [00:03<01:28, 16.46it/s]
SASRec epoch 5/8:   3%|▎         | 50/1500 [00:03<01:28, 16.46it/s, loss=1.38]
SASRec epoch 5/8:   3%|▎         | 52/1500 [00:03<01:28, 16.44it/s, loss=1.38]
SASRec epoch 5/8:   4%|▎         | 54/1500 [00:03<01:27, 16.50it/s, loss=1.38]
SASRec epoch 5/8:   4%|▎         | 56/1500 [00:03<01:27, 16.56it/s, loss=1.38]
SASRec epoch 5/8:   4%|▍         | 58/1500 [00:03<01:27, 16.57it/s, loss=1.38]
SASRec epoch 5/8:   4%|▍         | 60/1500 [00:03<01:26, 16.61it/s, loss=1.38]
SASRec epoch 5/8:   4%|▍         | 62/1500 [00:03<01:26, 16.58it/s, loss=1.38]
SASRec epoch 5/8:   4%|▍         | 64/1500 [00:03<01:26, 16.60it/s, loss=1.38]
SASRec epoch 5/8:   4%|▍         | 66/1500 [00:04<01:26, 16.61it/s, loss=1.38]
SASRec epoch 5/8:   5%|▍         | 68/1500 [00:04<01:26, 16.47it/s, loss=1.38]
SASRec epoch 5/8:   5%|▍         | 70/1500 [00:04<01:27, 16.43it/s, loss=1.38]
SASRec epoch 5/8:   5%|▍         | 72/1500 [00:04<01:27, 16.38it/s, loss=1.38]
SASRec epoch 5/8:   5%|▍         | 74/1500 [00:04<01:27, 16.23it/s, loss=1.38]
SASRec epoch 5/8:   5%|▌         | 76/1500 [00:04<01:28, 16.11it/s, loss=1.38]
SASRec epoch 5/8:   5%|▌         | 78/1500 [00:04<01:28, 16.12it/s, loss=1.38]
SASRec epoch 5/8:   5%|▌         | 80/1500 [00:04<01:28, 16.13it/s, loss=1.38]
SASRec epoch 5/8:   5%|▌         | 82/1500 [00:05<01:27, 16.15it/s, loss=1.38]
SASRec epoch 5/8:   6%|▌         | 84/1500 [00:05<01:27, 16.10it/s, loss=1.38]
SASRec epoch 5/8:   6%|▌         | 86/1500 [00:05<01:27, 16.14it/s, loss=1.38]
SASRec epoch 5/8:   6%|▌         | 88/1500 [00:05<01:27, 16.14it/s, loss=1.38]
SASRec epoch 5/8:   6%|▌         | 90/1500 [00:05<01:27, 16.15it/s, loss=1.38]
SASRec epoch 5/8:   6%|▌         | 92/1500 [00:05<01:27, 16.10it/s, loss=1.38]
SASRec epoch 5/8:   6%|▋         | 94/1500 [00:05<01:27, 16.12it/s, loss=1.38]
SASRec epoch 5/8:   6%|▋         | 96/1500 [00:05<01:26, 16.15it/s, loss=1.38]
SASRec epoch 5/8:   7%|▋         | 98/1500 [00:06<01:26, 16.20it/s, loss=1.38]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:06<01:26, 16.24it/s, loss=1.38]
SASRec epoch 5/8:   7%|▋         | 100/1500 [00:06<01:26, 16.24it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 102/1500 [00:06<01:27, 15.97it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 104/1500 [00:06<01:27, 16.03it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 106/1500 [00:06<01:26, 16.13it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 108/1500 [00:06<01:26, 16.16it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 110/1500 [00:06<01:26, 16.05it/s, loss=1.35]
SASRec epoch 5/8:   7%|▋         | 112/1500 [00:06<01:26, 16.09it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 114/1500 [00:07<01:25, 16.19it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 116/1500 [00:07<01:25, 16.27it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 118/1500 [00:07<01:24, 16.38it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 120/1500 [00:07<01:23, 16.49it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 122/1500 [00:07<01:24, 16.36it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 124/1500 [00:07<01:24, 16.34it/s, loss=1.35]
SASRec epoch 5/8:   8%|▊         | 126/1500 [00:07<01:24, 16.32it/s, loss=1.35]
SASRec epoch 5/8:   9%|▊         | 128/1500 [00:07<01:23, 16.40it/s, loss=1.35]
SASRec epoch 5/8:   9%|▊         | 130/1500 [00:08<01:23, 16.42it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 132/1500 [00:08<01:23, 16.43it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 134/1500 [00:08<01:23, 16.45it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 136/1500 [00:08<01:22, 16.52it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 138/1500 [00:08<01:22, 16.48it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 140/1500 [00:08<01:22, 16.46it/s, loss=1.35]
SASRec epoch 5/8:   9%|▉         | 142/1500 [00:08<01:22, 16.47it/s, loss=1.35]
SASRec epoch 5/8:  10%|▉         | 144/1500 [00:08<01:21, 16.55it/s, loss=1.35]
SASRec epoch 5/8:  10%|▉         | 146/1500 [00:08<01:21, 16.55it/s, loss=1.35]
SASRec epoch 5/8:  10%|▉         | 148/1500 [00:09<01:21, 16.56it/s, loss=1.35]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:09<01:21, 16.51it/s, loss=1.35]
SASRec epoch 5/8:  10%|█         | 150/1500 [00:09<01:21, 16.51it/s, loss=1.37]
SASRec epoch 5/8:  10%|█         | 152/1500 [00:09<01:22, 16.40it/s, loss=1.37]
SASRec epoch 5/8:  10%|█         | 154/1500 [00:09<01:21, 16.50it/s, loss=1.37]
SASRec epoch 5/8:  10%|█         | 156/1500 [00:09<01:21, 16.40it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 158/1500 [00:09<01:21, 16.40it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 160/1500 [00:09<01:22, 16.26it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 162/1500 [00:09<01:22, 16.29it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 164/1500 [00:10<01:22, 16.25it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 166/1500 [00:10<01:21, 16.34it/s, loss=1.37]
SASRec epoch 5/8:  11%|█         | 168/1500 [00:10<01:21, 16.26it/s, loss=1.37]
SASRec epoch 5/8:  11%|█▏        | 170/1500 [00:10<01:22, 16.17it/s, loss=1.37]
SASRec epoch 5/8:  11%|█▏        | 172/1500 [00:10<01:21, 16.22it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 174/1500 [00:10<01:22, 16.12it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 176/1500 [00:10<01:22, 16.12it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 178/1500 [00:10<01:22, 16.02it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 180/1500 [00:11<01:21, 16.14it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 182/1500 [00:11<01:22, 16.07it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 184/1500 [00:11<01:21, 16.11it/s, loss=1.37]
SASRec epoch 5/8:  12%|█▏        | 186/1500 [00:11<01:21, 16.14it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 188/1500 [00:11<01:21, 16.18it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 190/1500 [00:11<01:20, 16.24it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 192/1500 [00:11<01:20, 16.29it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 194/1500 [00:11<01:20, 16.26it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 196/1500 [00:12<01:20, 16.26it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 198/1500 [00:12<01:19, 16.32it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.38it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.38it/s, loss=1.37]
SASRec epoch 5/8:  13%|█▎        | 202/1500 [00:12<01:20, 16.21it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▎        | 204/1500 [00:12<01:19, 16.21it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▎        | 206/1500 [00:12<01:20, 16.12it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▍        | 208/1500 [00:12<01:20, 16.15it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▍        | 210/1500 [00:12<01:19, 16.16it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▍        | 212/1500 [00:13<01:20, 16.02it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▍        | 214/1500 [00:13<01:20, 16.00it/s, loss=1.37]
SASRec epoch 5/8:  14%|█▍        | 216/1500 [00:13<01:21, 15.72it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▍        | 218/1500 [00:13<01:23, 15.40it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▍        | 220/1500 [00:13<01:24, 15.20it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▍        | 222/1500 [00:13<01:23, 15.23it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▍        | 224/1500 [00:13<01:22, 15.48it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▌        | 226/1500 [00:13<01:22, 15.39it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▌        | 228/1500 [00:14<01:21, 15.55it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▌        | 230/1500 [00:14<01:22, 15.46it/s, loss=1.37]
SASRec epoch 5/8:  15%|█▌        | 232/1500 [00:14<01:21, 15.52it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▌        | 234/1500 [00:14<01:22, 15.40it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▌        | 236/1500 [00:14<01:23, 15.13it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▌        | 238/1500 [00:14<01:22, 15.26it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▌        | 240/1500 [00:14<01:22, 15.36it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▌        | 242/1500 [00:15<01:20, 15.64it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▋        | 244/1500 [00:15<01:20, 15.52it/s, loss=1.37]
SASRec epoch 5/8:  16%|█▋        | 246/1500 [00:15<01:20, 15.58it/s, loss=1.37]
SASRec epoch 5/8:  17%|█▋        | 248/1500 [00:15<01:20, 15.62it/s, loss=1.37]
SASRec epoch 5/8:  17%|█▋        | 250/1500 [00:15<01:18, 15.91it/s, loss=1.37]
SASRec epoch 5/8:  17%|█▋        | 250/1500 [00:15<01:18, 15.91it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 252/1500 [00:15<01:17, 16.09it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 254/1500 [00:15<01:16, 16.26it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 256/1500 [00:15<01:16, 16.28it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 258/1500 [00:16<01:16, 16.20it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 260/1500 [00:16<01:16, 16.22it/s, loss=1.35]
SASRec epoch 5/8:  17%|█▋        | 262/1500 [00:16<01:16, 16.26it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 264/1500 [00:16<01:15, 16.45it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 266/1500 [00:16<01:16, 16.07it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 268/1500 [00:16<01:15, 16.24it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.39it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 272/1500 [00:16<01:14, 16.51it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 274/1500 [00:16<01:13, 16.62it/s, loss=1.35]
SASRec epoch 5/8:  18%|█▊        | 276/1500 [00:17<01:13, 16.69it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▊        | 278/1500 [00:17<01:13, 16.69it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▊        | 280/1500 [00:17<01:14, 16.49it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 282/1500 [00:17<01:15, 16.23it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 284/1500 [00:17<01:16, 15.95it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 286/1500 [00:17<01:17, 15.67it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 288/1500 [00:17<01:17, 15.62it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 290/1500 [00:17<01:17, 15.71it/s, loss=1.35]
SASRec epoch 5/8:  19%|█▉        | 292/1500 [00:18<01:17, 15.59it/s, loss=1.35]
SASRec epoch 5/8:  20%|█▉        | 294/1500 [00:18<01:16, 15.73it/s, loss=1.35]
SASRec epoch 5/8:  20%|█▉        | 296/1500 [00:18<01:16, 15.79it/s, loss=1.35]
SASRec epoch 5/8:  20%|█▉        | 298/1500 [00:18<01:15, 15.85it/s, loss=1.35]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:18<01:15, 15.87it/s, loss=1.35]
SASRec epoch 5/8:  20%|██        | 300/1500 [00:18<01:15, 15.87it/s, loss=1.35]
SASRec epoch 5/8:  20%|██        | 302/1500 [00:18<01:16, 15.57it/s, loss=1.35]
SASRec epoch 5/8:  20%|██        | 304/1500 [00:18<01:15, 15.79it/s, loss=1.35]
SASRec epoch 5/8:  20%|██        | 306/1500 [00:19<01:14, 16.06it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 308/1500 [00:19<01:13, 16.23it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 310/1500 [00:19<01:12, 16.35it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 312/1500 [00:19<01:12, 16.43it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 314/1500 [00:19<01:12, 16.46it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 316/1500 [00:19<01:11, 16.52it/s, loss=1.35]
SASRec epoch 5/8:  21%|██        | 318/1500 [00:19<01:11, 16.58it/s, loss=1.35]
SASRec epoch 5/8:  21%|██▏       | 320/1500 [00:19<01:12, 16.32it/s, loss=1.35]
SASRec epoch 5/8:  21%|██▏       | 322/1500 [00:19<01:12, 16.28it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 324/1500 [00:20<01:12, 16.28it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 326/1500 [00:20<01:12, 16.25it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 328/1500 [00:20<01:11, 16.28it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 330/1500 [00:20<01:11, 16.29it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 332/1500 [00:20<01:11, 16.29it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 334/1500 [00:20<01:11, 16.31it/s, loss=1.35]
SASRec epoch 5/8:  22%|██▏       | 336/1500 [00:20<01:11, 16.30it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 338/1500 [00:20<01:11, 16.20it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 340/1500 [00:21<01:11, 16.30it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 342/1500 [00:21<01:10, 16.38it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 344/1500 [00:21<01:10, 16.45it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 346/1500 [00:21<01:10, 16.45it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 348/1500 [00:21<01:09, 16.46it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.46it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 350/1500 [00:21<01:09, 16.46it/s, loss=1.35]
SASRec epoch 5/8:  23%|██▎       | 352/1500 [00:21<01:09, 16.42it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▎       | 354/1500 [00:21<01:09, 16.47it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▎       | 356/1500 [00:22<01:10, 16.13it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▍       | 358/1500 [00:22<01:11, 16.06it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▍       | 360/1500 [00:22<01:10, 16.20it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▍       | 362/1500 [00:22<01:10, 16.25it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▍       | 364/1500 [00:22<01:09, 16.30it/s, loss=1.35]
SASRec epoch 5/8:  24%|██▍       | 366/1500 [00:22<01:09, 16.32it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▍       | 368/1500 [00:22<01:09, 16.36it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▍       | 370/1500 [00:22<01:09, 16.37it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▍       | 372/1500 [00:23<01:09, 16.29it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.30it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.27it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▌       | 378/1500 [00:23<01:08, 16.36it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▌       | 380/1500 [00:23<01:08, 16.42it/s, loss=1.35]
SASRec epoch 5/8:  25%|██▌       | 382/1500 [00:23<01:07, 16.51it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▌       | 384/1500 [00:23<01:07, 16.53it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▌       | 386/1500 [00:23<01:07, 16.59it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▌       | 388/1500 [00:24<01:07, 16.55it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▌       | 390/1500 [00:24<01:07, 16.48it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▌       | 392/1500 [00:24<01:07, 16.46it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▋       | 394/1500 [00:24<01:07, 16.35it/s, loss=1.35]
SASRec epoch 5/8:  26%|██▋       | 396/1500 [00:24<01:07, 16.40it/s, loss=1.35]
SASRec epoch 5/8:  27%|██▋       | 398/1500 [00:24<01:06, 16.48it/s, loss=1.35]
SASRec epoch 5/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.48it/s, loss=1.35]
SASRec epoch 5/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.48it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 402/1500 [00:24<01:07, 16.16it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 404/1500 [00:24<01:07, 16.16it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 406/1500 [00:25<01:07, 16.15it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 408/1500 [00:25<01:08, 15.97it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 410/1500 [00:25<01:07, 16.11it/s, loss=1.34]
SASRec epoch 5/8:  27%|██▋       | 412/1500 [00:25<01:07, 16.11it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 414/1500 [00:25<01:07, 16.16it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 416/1500 [00:25<01:06, 16.19it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 418/1500 [00:25<01:06, 16.26it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 420/1500 [00:25<01:06, 16.28it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 422/1500 [00:26<01:06, 16.20it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 424/1500 [00:26<01:05, 16.33it/s, loss=1.34]
SASRec epoch 5/8:  28%|██▊       | 426/1500 [00:26<01:06, 16.16it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▊       | 428/1500 [00:26<01:05, 16.27it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▊       | 430/1500 [00:26<01:05, 16.25it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 432/1500 [00:26<01:05, 16.31it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 434/1500 [00:26<01:05, 16.26it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 436/1500 [00:26<01:05, 16.30it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 438/1500 [00:27<01:05, 16.33it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 440/1500 [00:27<01:05, 16.12it/s, loss=1.34]
SASRec epoch 5/8:  29%|██▉       | 442/1500 [00:27<01:06, 15.89it/s, loss=1.34]
SASRec epoch 5/8:  30%|██▉       | 444/1500 [00:27<01:05, 16.09it/s, loss=1.34]
SASRec epoch 5/8:  30%|██▉       | 446/1500 [00:27<01:05, 16.16it/s, loss=1.34]
SASRec epoch 5/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.19it/s, loss=1.34]
SASRec epoch 5/8:  30%|███       | 450/1500 [00:27<01:05, 16.12it/s, loss=1.34]
SASRec epoch 5/8:  30%|███       | 450/1500 [00:27<01:05, 16.12it/s, loss=1.33]
SASRec epoch 5/8:  30%|███       | 452/1500 [00:27<01:04, 16.13it/s, loss=1.33]
SASRec epoch 5/8:  30%|███       | 454/1500 [00:28<01:04, 16.15it/s, loss=1.33]
SASRec epoch 5/8:  30%|███       | 456/1500 [00:28<01:04, 16.28it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 458/1500 [00:28<01:03, 16.37it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 460/1500 [00:28<01:03, 16.42it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 462/1500 [00:28<01:03, 16.46it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 464/1500 [00:28<01:03, 16.37it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 466/1500 [00:28<01:03, 16.36it/s, loss=1.33]
SASRec epoch 5/8:  31%|███       | 468/1500 [00:28<01:03, 16.25it/s, loss=1.33]
SASRec epoch 5/8:  31%|███▏      | 470/1500 [00:29<01:04, 16.06it/s, loss=1.33]
SASRec epoch 5/8:  31%|███▏      | 472/1500 [00:29<01:04, 15.91it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 474/1500 [00:29<01:04, 15.87it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 476/1500 [00:29<01:05, 15.62it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 478/1500 [00:29<01:05, 15.51it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 480/1500 [00:29<01:07, 15.21it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 482/1500 [00:29<01:08, 14.82it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 484/1500 [00:29<01:07, 14.99it/s, loss=1.33]
SASRec epoch 5/8:  32%|███▏      | 486/1500 [00:30<01:07, 14.98it/s, loss=1.33]
SASRec epoch 5/8:  33%|███▎      | 488/1500 [00:30<01:07, 15.08it/s, loss=1.33]

[SASRec] epoch 5/8 loss=1.3170

SASRec epoch 6/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 6/8:   0%|          | 2/1500 [00:00<01:35, 15.72it/s]
SASRec epoch 6/8:   0%|          | 4/1500 [00:00<01:34, 15.90it/s]
SASRec epoch 6/8:   0%|          | 6/1500 [00:00<01:32, 16.18it/s]
SASRec epoch 6/8:   1%|          | 8/1500 [00:00<01:31, 16.32it/s]
SASRec epoch 6/8:   1%|          | 10/1500 [00:00<01:30, 16.42it/s]
SASRec epoch 6/8:   1%|          | 12/1500 [00:00<01:30, 16.49it/s]
SASRec epoch 6/8:   1%|          | 14/1500 [00:00<01:30, 16.48it/s]
SASRec epoch 6/8:   1%|          | 16/1500 [00:00<01:30, 16.40it/s]
SASRec epoch 6/8:   1%|          | 18/1500 [00:01<01:30, 16.30it/s]
SASRec epoch 6/8:   1%|▏         | 20/1500 [00:01<01:31, 16.23it/s]
SASRec epoch 6/8:   1%|▏         | 22/1500 [00:01<01:30, 16.39it/s]
SASRec epoch 6/8:   2%|▏         | 24/1500 [00:01<01:30, 16.30it/s]
SASRec epoch 6/8:   2%|▏         | 26/1500 [00:01<01:30, 16.32it/s]
SASRec epoch 6/8:   2%|▏         | 28/1500 [00:01<01:29, 16.37it/s]
SASRec epoch 6/8:   2%|▏         | 30/1500 [00:01<01:29, 16.47it/s]
SASRec epoch 6/8:   2%|▏         | 32/1500 [00:01<01:28, 16.53it/s]
SASRec epoch 6/8:   2%|▏         | 34/1500 [00:02<01:29, 16.47it/s]
SASRec epoch 6/8:   2%|▏         | 36/1500 [00:02<01:28, 16.50it/s]
SASRec epoch 6/8:   3%|▎         | 38/1500 [00:02<01:28, 16.58it/s]
SASRec epoch 6/8:   3%|▎         | 40/1500 [00:02<01:27, 16.61it/s]
SASRec epoch 6/8:   3%|▎         | 42/1500 [00:02<01:28, 16.51it/s]
SASRec epoch 6/8:   3%|▎         | 44/1500 [00:02<01:29, 16.21it/s]
SASRec epoch 6/8:   3%|▎         | 46/1500 [00:02<01:29, 16.25it/s]
SASRec epoch 6/8:   3%|▎         | 48/1500 [00:02<01:29, 16.21it/s]
SASRec epoch 6/8:   3%|▎         | 50/1500 [00:03<01:28, 16.34it/s]
SASRec epoch 6/8:   3%|▎         | 50/1500 [00:03<01:28, 16.34it/s, loss=1.27]
SASRec epoch 6/8:   3%|▎         | 52/1500 [00:03<01:28, 16.28it/s, loss=1.27]
SASRec epoch 6/8:   4%|▎         | 54/1500 [00:03<01:29, 16.07it/s, loss=1.27]
SASRec epoch 6/8:   4%|▎         | 56/1500 [00:03<01:29, 16.16it/s, loss=1.27]
SASRec epoch 6/8:   4%|▍         | 58/1500 [00:03<01:28, 16.22it/s, loss=1.27]
SASRec epoch 6/8:   4%|▍         | 60/1500 [00:03<01:28, 16.27it/s, loss=1.27]
SASRec epoch 6/8:   4%|▍         | 62/1500 [00:03<01:31, 15.64it/s, loss=1.27]
SASRec epoch 6/8:   4%|▍         | 64/1500 [00:03<01:33, 15.38it/s, loss=1.27]
SASRec epoch 6/8:   4%|▍         | 66/1500 [00:04<01:32, 15.57it/s, loss=1.27]
SASRec epoch 6/8:   5%|▍         | 68/1500 [00:04<01:30, 15.75it/s, loss=1.27]
SASRec epoch 6/8:   5%|▍         | 70/1500 [00:04<01:30, 15.87it/s, loss=1.27]
SASRec epoch 6/8:   5%|▍         | 72/1500 [00:04<01:29, 15.89it/s, loss=1.27]
SASRec epoch 6/8:   5%|▍         | 74/1500 [00:04<01:29, 15.97it/s, loss=1.27]
SASRec epoch 6/8:   5%|▌         | 76/1500 [00:04<01:28, 16.17it/s, loss=1.27]
SASRec epoch 6/8:   5%|▌         | 78/1500 [00:04<01:26, 16.37it/s, loss=1.27]
SASRec epoch 6/8:   5%|▌         | 80/1500 [00:04<01:26, 16.48it/s, loss=1.27]
SASRec epoch 6/8:   5%|▌         | 82/1500 [00:05<01:26, 16.43it/s, loss=1.27]
SASRec epoch 6/8:   6%|▌         | 84/1500 [00:05<01:26, 16.35it/s, loss=1.27]
SASRec epoch 6/8:   6%|▌         | 86/1500 [00:05<01:27, 16.08it/s, loss=1.27]
SASRec epoch 6/8:   6%|▌         | 88/1500 [00:05<01:29, 15.86it/s, loss=1.27]
SASRec epoch 6/8:   6%|▌         | 90/1500 [00:05<01:29, 15.73it/s, loss=1.27]
SASRec epoch 6/8:   6%|▌         | 92/1500 [00:05<01:29, 15.73it/s, loss=1.27]
SASRec epoch 6/8:   6%|▋         | 94/1500 [00:05<01:29, 15.65it/s, loss=1.27]
SASRec epoch 6/8:   6%|▋         | 96/1500 [00:05<01:28, 15.87it/s, loss=1.27]
SASRec epoch 6/8:   7%|▋         | 98/1500 [00:06<01:26, 16.16it/s, loss=1.27]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:06<01:25, 16.31it/s, loss=1.27]
SASRec epoch 6/8:   7%|▋         | 100/1500 [00:06<01:25, 16.31it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 102/1500 [00:06<01:25, 16.31it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 104/1500 [00:06<01:25, 16.40it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 106/1500 [00:06<01:24, 16.46it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 108/1500 [00:06<01:25, 16.38it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 110/1500 [00:06<01:24, 16.43it/s, loss=1.26]
SASRec epoch 6/8:   7%|▋         | 112/1500 [00:06<01:24, 16.49it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 114/1500 [00:07<01:24, 16.43it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 116/1500 [00:07<01:23, 16.52it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 118/1500 [00:07<01:23, 16.56it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 120/1500 [00:07<01:23, 16.60it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 122/1500 [00:07<01:22, 16.63it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 124/1500 [00:07<01:22, 16.61it/s, loss=1.26]
SASRec epoch 6/8:   8%|▊         | 126/1500 [00:07<01:22, 16.59it/s, loss=1.26]
SASRec epoch 6/8:   9%|▊         | 128/1500 [00:07<01:22, 16.58it/s, loss=1.26]
SASRec epoch 6/8:   9%|▊         | 130/1500 [00:08<01:24, 16.30it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 132/1500 [00:08<01:23, 16.43it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 134/1500 [00:08<01:22, 16.51it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 136/1500 [00:08<01:22, 16.58it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 138/1500 [00:08<01:23, 16.39it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 140/1500 [00:08<01:23, 16.27it/s, loss=1.26]
SASRec epoch 6/8:   9%|▉         | 142/1500 [00:08<01:24, 16.13it/s, loss=1.26]
SASRec epoch 6/8:  10%|▉         | 144/1500 [00:08<01:23, 16.23it/s, loss=1.26]
SASRec epoch 6/8:  10%|▉         | 146/1500 [00:08<01:24, 16.06it/s, loss=1.26]
SASRec epoch 6/8:  10%|▉         | 148/1500 [00:09<01:23, 16.14it/s, loss=1.26]
SASRec epoch 6/8:  10%|█         | 150/1500 [00:09<01:23, 16.15it/s, loss=1.26]
SASRec epoch 6/8:  10%|█         | 150/1500 [00:09<01:23, 16.15it/s, loss=1.27]
SASRec epoch 6/8:  10%|█         | 152/1500 [00:09<01:23, 16.07it/s, loss=1.27]
SASRec epoch 6/8:  10%|█         | 154/1500 [00:09<01:24, 15.93it/s, loss=1.27]
SASRec epoch 6/8:  10%|█         | 156/1500 [00:09<01:23, 16.09it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 158/1500 [00:09<01:22, 16.22it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 160/1500 [00:09<01:21, 16.39it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 162/1500 [00:09<01:21, 16.44it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 164/1500 [00:10<01:22, 16.17it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 166/1500 [00:10<01:22, 16.15it/s, loss=1.27]
SASRec epoch 6/8:  11%|█         | 168/1500 [00:10<01:22, 16.18it/s, loss=1.27]
SASRec epoch 6/8:  11%|█▏        | 170/1500 [00:10<01:21, 16.32it/s, loss=1.27]
SASRec epoch 6/8:  11%|█▏        | 172/1500 [00:10<01:21, 16.37it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 174/1500 [00:10<01:20, 16.47it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 176/1500 [00:10<01:19, 16.57it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 178/1500 [00:10<01:19, 16.57it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 180/1500 [00:11<01:19, 16.55it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 182/1500 [00:11<01:19, 16.53it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 184/1500 [00:11<01:19, 16.47it/s, loss=1.27]
SASRec epoch 6/8:  12%|█▏        | 186/1500 [00:11<01:19, 16.51it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 188/1500 [00:11<01:19, 16.55it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 190/1500 [00:11<01:19, 16.58it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 192/1500 [00:11<01:19, 16.51it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 194/1500 [00:11<01:19, 16.42it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 196/1500 [00:12<01:19, 16.39it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 198/1500 [00:12<01:19, 16.36it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:12<01:20, 16.18it/s, loss=1.27]
SASRec epoch 6/8:  13%|█▎        | 200/1500 [00:12<01:20, 16.18it/s, loss=1.26]
SASRec epoch 6/8:  13%|█▎        | 202/1500 [00:12<01:21, 16.01it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▎        | 204/1500 [00:12<01:20, 16.07it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▎        | 206/1500 [00:12<01:20, 16.07it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▍        | 208/1500 [00:12<01:20, 16.11it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▍        | 210/1500 [00:12<01:19, 16.15it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▍        | 212/1500 [00:13<01:19, 16.16it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▍        | 214/1500 [00:13<01:19, 16.21it/s, loss=1.26]
SASRec epoch 6/8:  14%|█▍        | 216/1500 [00:13<01:18, 16.26it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▍        | 218/1500 [00:13<01:19, 16.18it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▍        | 220/1500 [00:13<01:18, 16.22it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▍        | 222/1500 [00:13<01:18, 16.26it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▍        | 224/1500 [00:13<01:18, 16.29it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▌        | 226/1500 [00:13<01:18, 16.27it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▌        | 228/1500 [00:14<01:17, 16.34it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▌        | 230/1500 [00:14<01:17, 16.49it/s, loss=1.26]
SASRec epoch 6/8:  15%|█▌        | 232/1500 [00:14<01:17, 16.45it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▌        | 234/1500 [00:14<01:16, 16.51it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▌        | 236/1500 [00:14<01:16, 16.49it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▌        | 238/1500 [00:14<01:16, 16.52it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▌        | 240/1500 [00:14<01:16, 16.49it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▌        | 242/1500 [00:14<01:16, 16.43it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▋        | 244/1500 [00:14<01:16, 16.46it/s, loss=1.26]
SASRec epoch 6/8:  16%|█▋        | 246/1500 [00:15<01:16, 16.46it/s, loss=1.26]
SASRec epoch 6/8:  17%|█▋        | 248/1500 [00:15<01:15, 16.49it/s, loss=1.26]
SASRec epoch 6/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.47it/s, loss=1.26]
SASRec epoch 6/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.47it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 252/1500 [00:15<01:17, 16.03it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 254/1500 [00:15<01:17, 16.01it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 256/1500 [00:15<01:17, 16.03it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 258/1500 [00:15<01:16, 16.18it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 260/1500 [00:15<01:16, 16.16it/s, loss=1.27]
SASRec epoch 6/8:  17%|█▋        | 262/1500 [00:16<01:16, 16.24it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 264/1500 [00:16<01:15, 16.35it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 266/1500 [00:16<01:14, 16.46it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 268/1500 [00:16<01:14, 16.50it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.34it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 272/1500 [00:16<01:14, 16.47it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 274/1500 [00:16<01:14, 16.55it/s, loss=1.27]
SASRec epoch 6/8:  18%|█▊        | 276/1500 [00:16<01:14, 16.53it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▊        | 278/1500 [00:17<01:13, 16.54it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▊        | 280/1500 [00:17<01:13, 16.55it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 282/1500 [00:17<01:14, 16.45it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 284/1500 [00:17<01:13, 16.51it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 286/1500 [00:17<01:13, 16.51it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 288/1500 [00:17<01:14, 16.19it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 290/1500 [00:17<01:14, 16.34it/s, loss=1.27]
SASRec epoch 6/8:  19%|█▉        | 292/1500 [00:17<01:13, 16.49it/s, loss=1.27]
SASRec epoch 6/8:  20%|█▉        | 294/1500 [00:18<01:13, 16.45it/s, loss=1.27]
SASRec epoch 6/8:  20%|█▉        | 296/1500 [00:18<01:13, 16.48it/s, loss=1.27]
SASRec epoch 6/8:  20%|█▉        | 298/1500 [00:18<01:12, 16.52it/s, loss=1.27]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:18<01:12, 16.52it/s, loss=1.27]
SASRec epoch 6/8:  20%|██        | 300/1500 [00:18<01:12, 16.52it/s, loss=1.25]
SASRec epoch 6/8:  20%|██        | 302/1500 [00:18<01:15, 15.97it/s, loss=1.25]
SASRec epoch 6/8:  20%|██        | 304/1500 [00:18<01:14, 15.99it/s, loss=1.25]
SASRec epoch 6/8:  20%|██        | 306/1500 [00:18<01:14, 15.93it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 308/1500 [00:18<01:14, 16.09it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 310/1500 [00:19<01:13, 16.13it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 312/1500 [00:19<01:13, 16.16it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 314/1500 [00:19<01:13, 16.14it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 316/1500 [00:19<01:13, 16.18it/s, loss=1.25]
SASRec epoch 6/8:  21%|██        | 318/1500 [00:19<01:12, 16.22it/s, loss=1.25]
SASRec epoch 6/8:  21%|██▏       | 320/1500 [00:19<01:14, 15.78it/s, loss=1.25]
SASRec epoch 6/8:  21%|██▏       | 322/1500 [00:19<01:15, 15.54it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 324/1500 [00:19<01:16, 15.35it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 326/1500 [00:20<01:16, 15.35it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 328/1500 [00:20<01:17, 15.15it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 330/1500 [00:20<01:15, 15.44it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 332/1500 [00:20<01:14, 15.68it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 334/1500 [00:20<01:13, 15.82it/s, loss=1.25]
SASRec epoch 6/8:  22%|██▏       | 336/1500 [00:20<01:13, 15.83it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 338/1500 [00:20<01:12, 16.02it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 340/1500 [00:20<01:12, 16.04it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 342/1500 [00:21<01:12, 15.89it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 344/1500 [00:21<01:12, 15.90it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 346/1500 [00:21<01:12, 15.95it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 348/1500 [00:21<01:11, 16.09it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.22it/s, loss=1.25]
SASRec epoch 6/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.22it/s, loss=1.24]
SASRec epoch 6/8:  23%|██▎       | 352/1500 [00:21<01:10, 16.18it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▎       | 354/1500 [00:21<01:10, 16.23it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▎       | 356/1500 [00:21<01:10, 16.26it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▍       | 358/1500 [00:22<01:10, 16.11it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▍       | 360/1500 [00:22<01:11, 15.97it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▍       | 362/1500 [00:22<01:12, 15.79it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▍       | 364/1500 [00:22<01:11, 15.92it/s, loss=1.24]
SASRec epoch 6/8:  24%|██▍       | 366/1500 [00:22<01:11, 15.77it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▍       | 368/1500 [00:22<01:12, 15.65it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▍       | 370/1500 [00:22<01:12, 15.63it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▍       | 372/1500 [00:22<01:12, 15.53it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▍       | 374/1500 [00:23<01:13, 15.36it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▌       | 376/1500 [00:23<01:13, 15.22it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▌       | 378/1500 [00:23<01:14, 15.10it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▌       | 380/1500 [00:23<01:13, 15.18it/s, loss=1.24]
SASRec epoch 6/8:  25%|██▌       | 382/1500 [00:23<01:12, 15.45it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▌       | 384/1500 [00:23<01:10, 15.80it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▌       | 386/1500 [00:23<01:09, 16.07it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▌       | 388/1500 [00:23<01:08, 16.28it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▌       | 390/1500 [00:24<01:08, 16.27it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▌       | 392/1500 [00:24<01:08, 16.11it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▋       | 394/1500 [00:24<01:08, 16.11it/s, loss=1.24]
SASRec epoch 6/8:  26%|██▋       | 396/1500 [00:24<01:08, 16.20it/s, loss=1.24]
SASRec epoch 6/8:  27%|██▋       | 398/1500 [00:24<01:07, 16.27it/s, loss=1.24]
SASRec epoch 6/8:  27%|██▋       | 400/1500 [00:24<01:08, 16.10it/s, loss=1.24]
SASRec epoch 6/8:  27%|██▋       | 400/1500 [00:24<01:08, 16.10it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 402/1500 [00:24<01:09, 15.76it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 404/1500 [00:24<01:09, 15.75it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 406/1500 [00:25<01:11, 15.36it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 408/1500 [00:25<01:12, 15.15it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 410/1500 [00:25<01:11, 15.30it/s, loss=1.25]
SASRec epoch 6/8:  27%|██▋       | 412/1500 [00:25<01:09, 15.59it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 414/1500 [00:25<01:08, 15.78it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 416/1500 [00:25<01:08, 15.93it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 418/1500 [00:25<01:07, 16.06it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 420/1500 [00:25<01:06, 16.15it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 422/1500 [00:26<01:06, 16.21it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 424/1500 [00:26<01:06, 16.20it/s, loss=1.25]
SASRec epoch 6/8:  28%|██▊       | 426/1500 [00:26<01:06, 16.20it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▊       | 428/1500 [00:26<01:06, 16.18it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▊       | 430/1500 [00:26<01:06, 16.20it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 432/1500 [00:26<01:05, 16.24it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 434/1500 [00:26<01:05, 16.27it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 436/1500 [00:26<01:05, 16.26it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 438/1500 [00:27<01:05, 16.26it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 440/1500 [00:27<01:05, 16.26it/s, loss=1.25]
SASRec epoch 6/8:  29%|██▉       | 442/1500 [00:27<01:04, 16.31it/s, loss=1.25]
SASRec epoch 6/8:  30%|██▉       | 444/1500 [00:27<01:04, 16.27it/s, loss=1.25]
SASRec epoch 6/8:  30%|██▉       | 446/1500 [00:27<01:05, 16.19it/s, loss=1.25]
SASRec epoch 6/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.19it/s, loss=1.25]
SASRec epoch 6/8:  30%|███       | 450/1500 [00:27<01:04, 16.19it/s, loss=1.25]
SASRec epoch 6/8:  30%|███       | 450/1500 [00:27<01:04, 16.19it/s, loss=1.23]
SASRec epoch 6/8:  30%|███       | 452/1500 [00:27<01:05, 15.91it/s, loss=1.23]
SASRec epoch 6/8:  30%|███       | 454/1500 [00:28<01:05, 15.94it/s, loss=1.23]
SASRec epoch 6/8:  30%|███       | 456/1500 [00:28<01:05, 15.99it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 458/1500 [00:28<01:05, 15.99it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 460/1500 [00:28<01:04, 16.09it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 462/1500 [00:28<01:04, 16.19it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 464/1500 [00:28<01:03, 16.34it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 466/1500 [00:28<01:03, 16.38it/s, loss=1.23]
SASRec epoch 6/8:  31%|███       | 468/1500 [00:28<01:03, 16.36it/s, loss=1.23]
SASRec epoch 6/8:  31%|███▏      | 470/1500 [00:29<01:02, 16.48it/s, loss=1.23]
SASRec epoch 6/8:  31%|███▏      | 472/1500 [00:29<01:02, 16.48it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 474/1500 [00:29<01:02, 16.49it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 476/1500 [00:29<01:01, 16.60it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 478/1500 [00:29<01:01, 16.58it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 480/1500 [00:29<01:01, 16.47it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 482/1500 [00:29<01:01, 16.47it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 484/1500 [00:29<01:01, 16.51it/s, loss=1.23]
SASRec epoch 6/8:  32%|███▏      | 486/1500 [00:30<01:01, 16.54it/s, loss=1.23]
SASRec epoch 6/8:  33%|███▎      | 488/1500 [00:30<01:01, 16.56it/s, loss=1.23]

[SASRec] epoch 6/8 loss=1.2269

SASRec epoch 7/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 7/8:   0%|          | 2/1500 [00:00<01:30, 16.49it/s]
SASRec epoch 7/8:   0%|          | 4/1500 [00:00<01:32, 16.12it/s]
SASRec epoch 7/8:   0%|          | 6/1500 [00:00<01:32, 16.19it/s]
SASRec epoch 7/8:   1%|          | 8/1500 [00:00<01:31, 16.35it/s]
SASRec epoch 7/8:   1%|          | 10/1500 [00:00<01:30, 16.46it/s]
SASRec epoch 7/8:   1%|          | 12/1500 [00:00<01:29, 16.54it/s]
SASRec epoch 7/8:   1%|          | 14/1500 [00:00<01:29, 16.56it/s]
SASRec epoch 7/8:   1%|          | 16/1500 [00:00<01:29, 16.62it/s]
SASRec epoch 7/8:   1%|          | 18/1500 [00:01<01:29, 16.65it/s]
SASRec epoch 7/8:   1%|▏         | 20/1500 [00:01<01:29, 16.61it/s]
SASRec epoch 7/8:   1%|▏         | 22/1500 [00:01<01:29, 16.56it/s]
SASRec epoch 7/8:   2%|▏         | 24/1500 [00:01<01:29, 16.49it/s]
SASRec epoch 7/8:   2%|▏         | 26/1500 [00:01<01:29, 16.44it/s]
SASRec epoch 7/8:   2%|▏         | 28/1500 [00:01<01:29, 16.47it/s]
SASRec epoch 7/8:   2%|▏         | 30/1500 [00:01<01:29, 16.45it/s]
SASRec epoch 7/8:   2%|▏         | 32/1500 [00:01<01:29, 16.47it/s]
SASRec epoch 7/8:   2%|▏         | 34/1500 [00:02<01:29, 16.45it/s]
SASRec epoch 7/8:   2%|▏         | 36/1500 [00:02<01:28, 16.45it/s]
SASRec epoch 7/8:   3%|▎         | 38/1500 [00:02<01:28, 16.43it/s]
SASRec epoch 7/8:   3%|▎         | 40/1500 [00:02<01:29, 16.36it/s]
SASRec epoch 7/8:   3%|▎         | 42/1500 [00:02<01:29, 16.35it/s]
SASRec epoch 7/8:   3%|▎         | 44/1500 [00:02<01:29, 16.31it/s]
SASRec epoch 7/8:   3%|▎         | 46/1500 [00:02<01:29, 16.27it/s]
SASRec epoch 7/8:   3%|▎         | 48/1500 [00:02<01:29, 16.26it/s]
SASRec epoch 7/8:   3%|▎         | 50/1500 [00:03<01:29, 16.27it/s]
SASRec epoch 7/8:   3%|▎         | 50/1500 [00:03<01:29, 16.27it/s, loss=1.19]
SASRec epoch 7/8:   3%|▎         | 52/1500 [00:03<01:30, 16.04it/s, loss=1.19]
SASRec epoch 7/8:   4%|▎         | 54/1500 [00:03<01:30, 15.93it/s, loss=1.19]
SASRec epoch 7/8:   4%|▎         | 56/1500 [00:03<01:30, 16.03it/s, loss=1.19]
SASRec epoch 7/8:   4%|▍         | 58/1500 [00:03<01:30, 15.99it/s, loss=1.19]
SASRec epoch 7/8:   4%|▍         | 60/1500 [00:03<01:29, 16.14it/s, loss=1.19]
SASRec epoch 7/8:   4%|▍         | 62/1500 [00:03<01:29, 16.15it/s, loss=1.19]
SASRec epoch 7/8:   4%|▍         | 64/1500 [00:03<01:28, 16.20it/s, loss=1.19]
SASRec epoch 7/8:   4%|▍         | 66/1500 [00:04<01:28, 16.24it/s, loss=1.19]
SASRec epoch 7/8:   5%|▍         | 68/1500 [00:04<01:27, 16.29it/s, loss=1.19]
SASRec epoch 7/8:   5%|▍         | 70/1500 [00:04<01:27, 16.36it/s, loss=1.19]
SASRec epoch 7/8:   5%|▍         | 72/1500 [00:04<01:27, 16.36it/s, loss=1.19]
SASRec epoch 7/8:   5%|▍         | 74/1500 [00:04<01:27, 16.28it/s, loss=1.19]
SASRec epoch 7/8:   5%|▌         | 76/1500 [00:04<01:27, 16.32it/s, loss=1.19]
SASRec epoch 7/8:   5%|▌         | 78/1500 [00:04<01:27, 16.33it/s, loss=1.19]
SASRec epoch 7/8:   5%|▌         | 80/1500 [00:04<01:26, 16.40it/s, loss=1.19]
SASRec epoch 7/8:   5%|▌         | 82/1500 [00:05<01:26, 16.36it/s, loss=1.19]
SASRec epoch 7/8:   6%|▌         | 84/1500 [00:05<01:26, 16.39it/s, loss=1.19]
SASRec epoch 7/8:   6%|▌         | 86/1500 [00:05<01:26, 16.33it/s, loss=1.19]
SASRec epoch 7/8:   6%|▌         | 88/1500 [00:05<01:26, 16.32it/s, loss=1.19]
SASRec epoch 7/8:   6%|▌         | 90/1500 [00:05<01:26, 16.33it/s, loss=1.19]
SASRec epoch 7/8:   6%|▌         | 92/1500 [00:05<01:27, 16.18it/s, loss=1.19]
SASRec epoch 7/8:   6%|▋         | 94/1500 [00:05<01:26, 16.25it/s, loss=1.19]
SASRec epoch 7/8:   6%|▋         | 96/1500 [00:05<01:26, 16.32it/s, loss=1.19]
SASRec epoch 7/8:   7%|▋         | 98/1500 [00:05<01:25, 16.37it/s, loss=1.19]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:06<01:25, 16.45it/s, loss=1.19]
SASRec epoch 7/8:   7%|▋         | 100/1500 [00:06<01:25, 16.45it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 102/1500 [00:06<01:25, 16.27it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 104/1500 [00:06<01:24, 16.46it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 106/1500 [00:06<01:24, 16.55it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 108/1500 [00:06<01:24, 16.50it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 110/1500 [00:06<01:25, 16.18it/s, loss=1.18]
SASRec epoch 7/8:   7%|▋         | 112/1500 [00:06<01:25, 16.24it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 114/1500 [00:06<01:25, 16.29it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 116/1500 [00:07<01:25, 16.27it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 118/1500 [00:07<01:25, 16.21it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 120/1500 [00:07<01:26, 15.92it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 122/1500 [00:07<01:27, 15.77it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 124/1500 [00:07<01:27, 15.78it/s, loss=1.18]
SASRec epoch 7/8:   8%|▊         | 126/1500 [00:07<01:27, 15.70it/s, loss=1.18]
SASRec epoch 7/8:   9%|▊         | 128/1500 [00:07<01:27, 15.62it/s, loss=1.18]
SASRec epoch 7/8:   9%|▊         | 130/1500 [00:08<01:27, 15.65it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 132/1500 [00:08<01:28, 15.52it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 134/1500 [00:08<01:29, 15.21it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 136/1500 [00:08<01:29, 15.32it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 138/1500 [00:08<01:29, 15.18it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 140/1500 [00:08<01:29, 15.24it/s, loss=1.18]
SASRec epoch 7/8:   9%|▉         | 142/1500 [00:08<01:28, 15.27it/s, loss=1.18]
SASRec epoch 7/8:  10%|▉         | 144/1500 [00:08<01:29, 15.20it/s, loss=1.18]
SASRec epoch 7/8:  10%|▉         | 146/1500 [00:09<01:28, 15.29it/s, loss=1.18]
SASRec epoch 7/8:  10%|▉         | 148/1500 [00:09<01:27, 15.44it/s, loss=1.18]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:09<01:26, 15.60it/s, loss=1.18]
SASRec epoch 7/8:  10%|█         | 150/1500 [00:09<01:26, 15.60it/s, loss=1.18]
SASRec epoch 7/8:  10%|█         | 152/1500 [00:09<01:26, 15.52it/s, loss=1.18]
SASRec epoch 7/8:  10%|█         | 154/1500 [00:09<01:26, 15.59it/s, loss=1.18]
SASRec epoch 7/8:  10%|█         | 156/1500 [00:09<01:25, 15.74it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 158/1500 [00:09<01:24, 15.87it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 160/1500 [00:09<01:23, 16.00it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 162/1500 [00:10<01:23, 15.98it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 164/1500 [00:10<01:22, 16.11it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 166/1500 [00:10<01:24, 15.87it/s, loss=1.18]
SASRec epoch 7/8:  11%|█         | 168/1500 [00:10<01:25, 15.58it/s, loss=1.18]
SASRec epoch 7/8:  11%|█▏        | 170/1500 [00:10<01:25, 15.63it/s, loss=1.18]
SASRec epoch 7/8:  11%|█▏        | 172/1500 [00:10<01:23, 15.96it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 174/1500 [00:10<01:21, 16.22it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 176/1500 [00:10<01:20, 16.40it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 178/1500 [00:11<01:20, 16.50it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 180/1500 [00:11<01:20, 16.46it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 182/1500 [00:11<01:22, 15.98it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 184/1500 [00:11<01:23, 15.79it/s, loss=1.18]
SASRec epoch 7/8:  12%|█▏        | 186/1500 [00:11<01:23, 15.76it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 188/1500 [00:11<01:22, 15.89it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 190/1500 [00:11<01:22, 15.93it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 192/1500 [00:11<01:21, 16.04it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 194/1500 [00:12<01:21, 16.12it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 196/1500 [00:12<01:20, 16.15it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 198/1500 [00:12<01:22, 15.85it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 200/1500 [00:12<01:22, 15.83it/s, loss=1.18]
SASRec epoch 7/8:  13%|█▎        | 200/1500 [00:12<01:22, 15.83it/s, loss=1.17]
SASRec epoch 7/8:  13%|█▎        | 202/1500 [00:12<01:23, 15.60it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▎        | 204/1500 [00:12<01:22, 15.62it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▎        | 206/1500 [00:12<01:22, 15.71it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▍        | 208/1500 [00:12<01:21, 15.78it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▍        | 210/1500 [00:13<01:20, 15.95it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▍        | 212/1500 [00:13<01:19, 16.15it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▍        | 214/1500 [00:13<01:18, 16.34it/s, loss=1.17]
SASRec epoch 7/8:  14%|█▍        | 216/1500 [00:13<01:18, 16.42it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▍        | 218/1500 [00:13<01:17, 16.49it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▍        | 220/1500 [00:13<01:17, 16.57it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▍        | 222/1500 [00:13<01:16, 16.62it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▍        | 224/1500 [00:13<01:16, 16.60it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▌        | 226/1500 [00:14<01:16, 16.59it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▌        | 228/1500 [00:14<01:16, 16.53it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▌        | 230/1500 [00:14<01:16, 16.57it/s, loss=1.17]
SASRec epoch 7/8:  15%|█▌        | 232/1500 [00:14<01:16, 16.58it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▌        | 234/1500 [00:14<01:16, 16.55it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▌        | 236/1500 [00:14<01:16, 16.56it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▌        | 238/1500 [00:14<01:16, 16.56it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▌        | 240/1500 [00:14<01:15, 16.62it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▌        | 242/1500 [00:14<01:15, 16.70it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▋        | 244/1500 [00:15<01:15, 16.73it/s, loss=1.17]
SASRec epoch 7/8:  16%|█▋        | 246/1500 [00:15<01:14, 16.75it/s, loss=1.17]
SASRec epoch 7/8:  17%|█▋        | 248/1500 [00:15<01:14, 16.71it/s, loss=1.17]
SASRec epoch 7/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.63it/s, loss=1.17]
SASRec epoch 7/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.63it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 252/1500 [00:15<01:16, 16.36it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 254/1500 [00:15<01:15, 16.48it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 256/1500 [00:15<01:15, 16.41it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 258/1500 [00:15<01:15, 16.45it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 260/1500 [00:16<01:15, 16.36it/s, loss=1.19]
SASRec epoch 7/8:  17%|█▋        | 262/1500 [00:16<01:15, 16.30it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 264/1500 [00:16<01:15, 16.37it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 266/1500 [00:16<01:15, 16.37it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 268/1500 [00:16<01:15, 16.38it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 270/1500 [00:16<01:15, 16.23it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 272/1500 [00:16<01:15, 16.26it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 274/1500 [00:16<01:15, 16.33it/s, loss=1.19]
SASRec epoch 7/8:  18%|█▊        | 276/1500 [00:17<01:14, 16.35it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▊        | 278/1500 [00:17<01:15, 16.24it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▊        | 280/1500 [00:17<01:15, 16.27it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 282/1500 [00:17<01:14, 16.27it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 284/1500 [00:17<01:14, 16.36it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 286/1500 [00:17<01:15, 16.18it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 288/1500 [00:17<01:14, 16.34it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 290/1500 [00:17<01:13, 16.42it/s, loss=1.19]
SASRec epoch 7/8:  19%|█▉        | 292/1500 [00:18<01:13, 16.45it/s, loss=1.19]
SASRec epoch 7/8:  20%|█▉        | 294/1500 [00:18<01:12, 16.55it/s, loss=1.19]
SASRec epoch 7/8:  20%|█▉        | 296/1500 [00:18<01:13, 16.46it/s, loss=1.19]
SASRec epoch 7/8:  20%|█▉        | 298/1500 [00:18<01:12, 16.48it/s, loss=1.19]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:18<01:12, 16.44it/s, loss=1.19]
SASRec epoch 7/8:  20%|██        | 300/1500 [00:18<01:12, 16.44it/s, loss=1.17]
SASRec epoch 7/8:  20%|██        | 302/1500 [00:18<01:13, 16.32it/s, loss=1.17]
SASRec epoch 7/8:  20%|██        | 304/1500 [00:18<01:12, 16.49it/s, loss=1.17]
SASRec epoch 7/8:  20%|██        | 306/1500 [00:18<01:11, 16.60it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 308/1500 [00:19<01:11, 16.62it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 310/1500 [00:19<01:11, 16.61it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 312/1500 [00:19<01:11, 16.53it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 314/1500 [00:19<01:11, 16.54it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 316/1500 [00:19<01:12, 16.40it/s, loss=1.17]
SASRec epoch 7/8:  21%|██        | 318/1500 [00:19<01:12, 16.38it/s, loss=1.17]
SASRec epoch 7/8:  21%|██▏       | 320/1500 [00:19<01:11, 16.43it/s, loss=1.17]
SASRec epoch 7/8:  21%|██▏       | 322/1500 [00:19<01:12, 16.29it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 324/1500 [00:19<01:12, 16.33it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 326/1500 [00:20<01:11, 16.34it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 328/1500 [00:20<01:11, 16.32it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 330/1500 [00:20<01:11, 16.33it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 332/1500 [00:20<01:11, 16.35it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 334/1500 [00:20<01:11, 16.39it/s, loss=1.17]
SASRec epoch 7/8:  22%|██▏       | 336/1500 [00:20<01:10, 16.46it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 338/1500 [00:20<01:10, 16.45it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 340/1500 [00:20<01:10, 16.47it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 342/1500 [00:21<01:10, 16.41it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 344/1500 [00:21<01:10, 16.37it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 346/1500 [00:21<01:10, 16.28it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 348/1500 [00:21<01:10, 16.25it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.28it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 350/1500 [00:21<01:10, 16.28it/s, loss=1.17]
SASRec epoch 7/8:  23%|██▎       | 352/1500 [00:21<01:11, 16.12it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▎       | 354/1500 [00:21<01:10, 16.23it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▎       | 356/1500 [00:21<01:11, 16.02it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▍       | 358/1500 [00:22<01:11, 16.04it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▍       | 360/1500 [00:22<01:10, 16.21it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▍       | 362/1500 [00:22<01:09, 16.34it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▍       | 364/1500 [00:22<01:09, 16.41it/s, loss=1.17]
SASRec epoch 7/8:  24%|██▍       | 366/1500 [00:22<01:08, 16.46it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▍       | 368/1500 [00:22<01:08, 16.45it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▍       | 370/1500 [00:22<01:08, 16.52it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▍       | 372/1500 [00:22<01:08, 16.49it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.32it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.19it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▌       | 378/1500 [00:23<01:09, 16.04it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▌       | 380/1500 [00:23<01:09, 16.05it/s, loss=1.17]
SASRec epoch 7/8:  25%|██▌       | 382/1500 [00:23<01:08, 16.23it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▌       | 384/1500 [00:23<01:09, 16.13it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▌       | 386/1500 [00:23<01:08, 16.28it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▌       | 388/1500 [00:23<01:08, 16.29it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▌       | 390/1500 [00:24<01:07, 16.42it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▌       | 392/1500 [00:24<01:07, 16.36it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▋       | 394/1500 [00:24<01:08, 16.20it/s, loss=1.17]
SASRec epoch 7/8:  26%|██▋       | 396/1500 [00:24<01:07, 16.34it/s, loss=1.17]
SASRec epoch 7/8:  27%|██▋       | 398/1500 [00:24<01:07, 16.43it/s, loss=1.17]
SASRec epoch 7/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.55it/s, loss=1.17]
SASRec epoch 7/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.55it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 402/1500 [00:24<01:07, 16.26it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 404/1500 [00:24<01:06, 16.38it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 406/1500 [00:25<01:06, 16.47it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 408/1500 [00:25<01:06, 16.50it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 410/1500 [00:25<01:07, 16.25it/s, loss=1.16]
SASRec epoch 7/8:  27%|██▋       | 412/1500 [00:25<01:06, 16.37it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 414/1500 [00:25<01:05, 16.49it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 416/1500 [00:25<01:06, 16.35it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 418/1500 [00:25<01:07, 16.13it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 420/1500 [00:25<01:07, 16.05it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 422/1500 [00:26<01:06, 16.10it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 424/1500 [00:26<01:06, 16.14it/s, loss=1.16]
SASRec epoch 7/8:  28%|██▊       | 426/1500 [00:26<01:07, 15.91it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▊       | 428/1500 [00:26<01:07, 15.78it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▊       | 430/1500 [00:26<01:07, 15.78it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 432/1500 [00:26<01:06, 16.05it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 434/1500 [00:26<01:05, 16.25it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 436/1500 [00:26<01:05, 16.35it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 438/1500 [00:26<01:04, 16.44it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 440/1500 [00:27<01:04, 16.48it/s, loss=1.16]
SASRec epoch 7/8:  29%|██▉       | 442/1500 [00:27<01:04, 16.48it/s, loss=1.16]
SASRec epoch 7/8:  30%|██▉       | 444/1500 [00:27<01:04, 16.47it/s, loss=1.16]
SASRec epoch 7/8:  30%|██▉       | 446/1500 [00:27<01:04, 16.27it/s, loss=1.16]
SASRec epoch 7/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.21it/s, loss=1.16]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:27<01:04, 16.39it/s, loss=1.16]
SASRec epoch 7/8:  30%|███       | 450/1500 [00:27<01:04, 16.39it/s, loss=1.16]
SASRec epoch 7/8:  30%|███       | 452/1500 [00:27<01:03, 16.46it/s, loss=1.16]
SASRec epoch 7/8:  30%|███       | 454/1500 [00:27<01:03, 16.57it/s, loss=1.16]
SASRec epoch 7/8:  30%|███       | 456/1500 [00:28<01:02, 16.63it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 458/1500 [00:28<01:03, 16.53it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 460/1500 [00:28<01:03, 16.41it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 462/1500 [00:28<01:03, 16.45it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 464/1500 [00:28<01:03, 16.39it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 466/1500 [00:28<01:05, 15.79it/s, loss=1.16]
SASRec epoch 7/8:  31%|███       | 468/1500 [00:28<01:06, 15.61it/s, loss=1.16]
SASRec epoch 7/8:  31%|███▏      | 470/1500 [00:28<01:06, 15.54it/s, loss=1.16]
SASRec epoch 7/8:  31%|███▏      | 472/1500 [00:29<01:06, 15.42it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 474/1500 [00:29<01:06, 15.51it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 476/1500 [00:29<01:05, 15.61it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 478/1500 [00:29<01:05, 15.66it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 480/1500 [00:29<01:05, 15.55it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 482/1500 [00:29<01:06, 15.37it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 484/1500 [00:29<01:07, 15.13it/s, loss=1.16]
SASRec epoch 7/8:  32%|███▏      | 486/1500 [00:30<01:06, 15.27it/s, loss=1.16]
SASRec epoch 7/8:  33%|███▎      | 488/1500 [00:30<01:05, 15.47it/s, loss=1.16]

[SASRec] epoch 7/8 loss=1.1523

SASRec epoch 8/8:   0%|          | 0/1500 [00:00<?, ?it/s]
SASRec epoch 8/8:   0%|          | 2/1500 [00:00<01:32, 16.26it/s]
SASRec epoch 8/8:   0%|          | 4/1500 [00:00<01:34, 15.85it/s]
SASRec epoch 8/8:   0%|          | 6/1500 [00:00<01:34, 15.89it/s]
SASRec epoch 8/8:   1%|          | 8/1500 [00:00<01:34, 15.72it/s]
SASRec epoch 8/8:   1%|          | 10/1500 [00:00<01:35, 15.66it/s]
SASRec epoch 8/8:   1%|          | 12/1500 [00:00<01:34, 15.78it/s]
SASRec epoch 8/8:   1%|          | 14/1500 [00:00<01:32, 16.02it/s]
SASRec epoch 8/8:   1%|          | 16/1500 [00:01<01:32, 16.10it/s]
SASRec epoch 8/8:   1%|          | 18/1500 [00:01<01:31, 16.17it/s]
SASRec epoch 8/8:   1%|▏         | 20/1500 [00:01<01:30, 16.29it/s]
SASRec epoch 8/8:   1%|▏         | 22/1500 [00:01<01:30, 16.26it/s]
SASRec epoch 8/8:   2%|▏         | 24/1500 [00:01<01:30, 16.32it/s]
SASRec epoch 8/8:   2%|▏         | 26/1500 [00:01<01:30, 16.33it/s]
SASRec epoch 8/8:   2%|▏         | 28/1500 [00:01<01:29, 16.36it/s]
SASRec epoch 8/8:   2%|▏         | 30/1500 [00:01<01:29, 16.38it/s]
SASRec epoch 8/8:   2%|▏         | 32/1500 [00:01<01:29, 16.41it/s]
SASRec epoch 8/8:   2%|▏         | 34/1500 [00:02<01:29, 16.43it/s]
SASRec epoch 8/8:   2%|▏         | 36/1500 [00:02<01:28, 16.45it/s]
SASRec epoch 8/8:   3%|▎         | 38/1500 [00:02<01:28, 16.46it/s]
SASRec epoch 8/8:   3%|▎         | 40/1500 [00:02<01:28, 16.43it/s]
SASRec epoch 8/8:   3%|▎         | 42/1500 [00:02<01:28, 16.41it/s]
SASRec epoch 8/8:   3%|▎         | 44/1500 [00:02<01:28, 16.53it/s]
SASRec epoch 8/8:   3%|▎         | 46/1500 [00:02<01:27, 16.58it/s]
SASRec epoch 8/8:   3%|▎         | 48/1500 [00:02<01:27, 16.56it/s]
SASRec epoch 8/8:   3%|▎         | 50/1500 [00:03<01:27, 16.53it/s]
SASRec epoch 8/8:   3%|▎         | 50/1500 [00:03<01:27, 16.53it/s, loss=1.12]
SASRec epoch 8/8:   3%|▎         | 52/1500 [00:03<01:28, 16.30it/s, loss=1.12]
SASRec epoch 8/8:   4%|▎         | 54/1500 [00:03<01:28, 16.38it/s, loss=1.12]
SASRec epoch 8/8:   4%|▎         | 56/1500 [00:03<01:27, 16.41it/s, loss=1.12]
SASRec epoch 8/8:   4%|▍         | 58/1500 [00:03<01:29, 16.19it/s, loss=1.12]
SASRec epoch 8/8:   4%|▍         | 60/1500 [00:03<01:28, 16.32it/s, loss=1.12]
SASRec epoch 8/8:   4%|▍         | 62/1500 [00:03<01:27, 16.38it/s, loss=1.12]
SASRec epoch 8/8:   4%|▍         | 64/1500 [00:03<01:27, 16.43it/s, loss=1.12]
SASRec epoch 8/8:   4%|▍         | 66/1500 [00:04<01:27, 16.47it/s, loss=1.12]
SASRec epoch 8/8:   5%|▍         | 68/1500 [00:04<01:26, 16.51it/s, loss=1.12]
SASRec epoch 8/8:   5%|▍         | 70/1500 [00:04<01:26, 16.53it/s, loss=1.12]
SASRec epoch 8/8:   5%|▍         | 72/1500 [00:04<01:26, 16.55it/s, loss=1.12]
SASRec epoch 8/8:   5%|▍         | 74/1500 [00:04<01:26, 16.51it/s, loss=1.12]
SASRec epoch 8/8:   5%|▌         | 76/1500 [00:04<01:26, 16.55it/s, loss=1.12]
SASRec epoch 8/8:   5%|▌         | 78/1500 [00:04<01:26, 16.50it/s, loss=1.12]
SASRec epoch 8/8:   5%|▌         | 80/1500 [00:04<01:25, 16.53it/s, loss=1.12]
SASRec epoch 8/8:   5%|▌         | 82/1500 [00:05<01:25, 16.53it/s, loss=1.12]
SASRec epoch 8/8:   6%|▌         | 84/1500 [00:05<01:25, 16.56it/s, loss=1.12]
SASRec epoch 8/8:   6%|▌         | 86/1500 [00:05<01:25, 16.52it/s, loss=1.12]
SASRec epoch 8/8:   6%|▌         | 88/1500 [00:05<01:25, 16.51it/s, loss=1.12]
SASRec epoch 8/8:   6%|▌         | 90/1500 [00:05<01:25, 16.51it/s, loss=1.12]
SASRec epoch 8/8:   6%|▌         | 92/1500 [00:05<01:25, 16.46it/s, loss=1.12]
SASRec epoch 8/8:   6%|▋         | 94/1500 [00:05<01:26, 16.28it/s, loss=1.12]
SASRec epoch 8/8:   6%|▋         | 96/1500 [00:05<01:26, 16.25it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 98/1500 [00:05<01:26, 16.27it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 100/1500 [00:06<01:25, 16.30it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 100/1500 [00:06<01:25, 16.30it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 102/1500 [00:06<01:26, 16.16it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 104/1500 [00:06<01:26, 16.21it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 106/1500 [00:06<01:25, 16.22it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 108/1500 [00:06<01:25, 16.22it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 110/1500 [00:06<01:25, 16.24it/s, loss=1.12]
SASRec epoch 8/8:   7%|▋         | 112/1500 [00:06<01:25, 16.19it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 114/1500 [00:06<01:25, 16.22it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 116/1500 [00:07<01:25, 16.26it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 118/1500 [00:07<01:24, 16.39it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 120/1500 [00:07<01:23, 16.46it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 122/1500 [00:07<01:23, 16.50it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 124/1500 [00:07<01:23, 16.38it/s, loss=1.12]
SASRec epoch 8/8:   8%|▊         | 126/1500 [00:07<01:23, 16.40it/s, loss=1.12]
SASRec epoch 8/8:   9%|▊         | 128/1500 [00:07<01:23, 16.45it/s, loss=1.12]
SASRec epoch 8/8:   9%|▊         | 130/1500 [00:07<01:24, 16.16it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 132/1500 [00:08<01:24, 16.21it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 134/1500 [00:08<01:24, 16.15it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 136/1500 [00:08<01:24, 16.18it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 138/1500 [00:08<01:23, 16.25it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 140/1500 [00:08<01:23, 16.20it/s, loss=1.12]
SASRec epoch 8/8:   9%|▉         | 142/1500 [00:08<01:23, 16.30it/s, loss=1.12]
SASRec epoch 8/8:  10%|▉         | 144/1500 [00:08<01:23, 16.30it/s, loss=1.12]
SASRec epoch 8/8:  10%|▉         | 146/1500 [00:08<01:22, 16.35it/s, loss=1.12]
SASRec epoch 8/8:  10%|▉         | 148/1500 [00:09<01:23, 16.24it/s, loss=1.12]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:09<01:23, 16.19it/s, loss=1.12]
SASRec epoch 8/8:  10%|█         | 150/1500 [00:09<01:23, 16.19it/s, loss=1.13]
SASRec epoch 8/8:  10%|█         | 152/1500 [00:09<01:24, 16.00it/s, loss=1.13]
SASRec epoch 8/8:  10%|█         | 154/1500 [00:09<01:23, 16.04it/s, loss=1.13]
SASRec epoch 8/8:  10%|█         | 156/1500 [00:09<01:23, 16.08it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 158/1500 [00:09<01:22, 16.18it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 160/1500 [00:09<01:22, 16.25it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 162/1500 [00:09<01:22, 16.29it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 164/1500 [00:10<01:22, 16.29it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 166/1500 [00:10<01:22, 16.21it/s, loss=1.13]
SASRec epoch 8/8:  11%|█         | 168/1500 [00:10<01:21, 16.31it/s, loss=1.13]
SASRec epoch 8/8:  11%|█▏        | 170/1500 [00:10<01:21, 16.34it/s, loss=1.13]
SASRec epoch 8/8:  11%|█▏        | 172/1500 [00:10<01:21, 16.36it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 174/1500 [00:10<01:20, 16.40it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 176/1500 [00:10<01:21, 16.34it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 178/1500 [00:10<01:21, 16.25it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 180/1500 [00:11<01:22, 16.02it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 182/1500 [00:11<01:23, 15.72it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 184/1500 [00:11<01:25, 15.47it/s, loss=1.13]
SASRec epoch 8/8:  12%|█▏        | 186/1500 [00:11<01:24, 15.59it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 188/1500 [00:11<01:23, 15.77it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 190/1500 [00:11<01:21, 16.01it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 192/1500 [00:11<01:20, 16.17it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 194/1500 [00:11<01:20, 16.31it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 196/1500 [00:12<01:19, 16.42it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 198/1500 [00:12<01:19, 16.45it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.45it/s, loss=1.13]
SASRec epoch 8/8:  13%|█▎        | 200/1500 [00:12<01:19, 16.45it/s, loss=1.12]
SASRec epoch 8/8:  13%|█▎        | 202/1500 [00:12<01:20, 16.09it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▎        | 204/1500 [00:12<01:19, 16.27it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▎        | 206/1500 [00:12<01:18, 16.40it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▍        | 208/1500 [00:12<01:18, 16.49it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▍        | 210/1500 [00:12<01:18, 16.44it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▍        | 212/1500 [00:13<01:17, 16.52it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▍        | 214/1500 [00:13<01:18, 16.45it/s, loss=1.12]
SASRec epoch 8/8:  14%|█▍        | 216/1500 [00:13<01:18, 16.44it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▍        | 218/1500 [00:13<01:18, 16.33it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▍        | 220/1500 [00:13<01:19, 16.03it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▍        | 222/1500 [00:13<01:19, 16.02it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▍        | 224/1500 [00:13<01:19, 16.02it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▌        | 226/1500 [00:13<01:18, 16.15it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▌        | 228/1500 [00:14<01:18, 16.11it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▌        | 230/1500 [00:14<01:18, 16.12it/s, loss=1.12]
SASRec epoch 8/8:  15%|█▌        | 232/1500 [00:14<01:19, 16.03it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▌        | 234/1500 [00:14<01:18, 16.16it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▌        | 236/1500 [00:14<01:17, 16.25it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▌        | 238/1500 [00:14<01:18, 16.15it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▌        | 240/1500 [00:14<01:18, 16.08it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▌        | 242/1500 [00:14<01:17, 16.26it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▋        | 244/1500 [00:14<01:16, 16.35it/s, loss=1.12]
SASRec epoch 8/8:  16%|█▋        | 246/1500 [00:15<01:16, 16.37it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 248/1500 [00:15<01:16, 16.43it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.49it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 250/1500 [00:15<01:15, 16.49it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 252/1500 [00:15<01:16, 16.29it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 254/1500 [00:15<01:18, 15.82it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 256/1500 [00:15<01:19, 15.68it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 258/1500 [00:15<01:20, 15.51it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 260/1500 [00:16<01:19, 15.52it/s, loss=1.12]
SASRec epoch 8/8:  17%|█▋        | 262/1500 [00:16<01:18, 15.77it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 264/1500 [00:16<01:17, 15.85it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 266/1500 [00:16<01:19, 15.49it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 268/1500 [00:16<01:19, 15.41it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 270/1500 [00:16<01:20, 15.26it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 272/1500 [00:16<01:20, 15.34it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 274/1500 [00:16<01:18, 15.53it/s, loss=1.12]
SASRec epoch 8/8:  18%|█▊        | 276/1500 [00:17<01:18, 15.58it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▊        | 278/1500 [00:17<01:16, 15.88it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▊        | 280/1500 [00:17<01:16, 16.01it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 282/1500 [00:17<01:15, 16.16it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 284/1500 [00:17<01:15, 16.20it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 286/1500 [00:17<01:14, 16.21it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 288/1500 [00:17<01:14, 16.19it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 290/1500 [00:17<01:15, 16.12it/s, loss=1.12]
SASRec epoch 8/8:  19%|█▉        | 292/1500 [00:18<01:14, 16.15it/s, loss=1.12]
SASRec epoch 8/8:  20%|█▉        | 294/1500 [00:18<01:14, 16.21it/s, loss=1.12]
SASRec epoch 8/8:  20%|█▉        | 296/1500 [00:18<01:13, 16.30it/s, loss=1.12]
SASRec epoch 8/8:  20%|█▉        | 298/1500 [00:18<01:13, 16.37it/s, loss=1.12]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:18<01:13, 16.42it/s, loss=1.12]
SASRec epoch 8/8:  20%|██        | 300/1500 [00:18<01:13, 16.42it/s, loss=1.11]
SASRec epoch 8/8:  20%|██        | 302/1500 [00:18<01:13, 16.34it/s, loss=1.11]
SASRec epoch 8/8:  20%|██        | 304/1500 [00:18<01:13, 16.33it/s, loss=1.11]
SASRec epoch 8/8:  20%|██        | 306/1500 [00:18<01:12, 16.41it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 308/1500 [00:19<01:13, 16.16it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 310/1500 [00:19<01:13, 16.13it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 312/1500 [00:19<01:13, 16.25it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 314/1500 [00:19<01:12, 16.32it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 316/1500 [00:19<01:12, 16.40it/s, loss=1.11]
SASRec epoch 8/8:  21%|██        | 318/1500 [00:19<01:11, 16.43it/s, loss=1.11]
SASRec epoch 8/8:  21%|██▏       | 320/1500 [00:19<01:11, 16.46it/s, loss=1.11]
SASRec epoch 8/8:  21%|██▏       | 322/1500 [00:19<01:11, 16.49it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 324/1500 [00:19<01:11, 16.45it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 326/1500 [00:20<01:11, 16.47it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 328/1500 [00:20<01:12, 16.21it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 330/1500 [00:20<01:11, 16.34it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 332/1500 [00:20<01:11, 16.41it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 334/1500 [00:20<01:10, 16.46it/s, loss=1.11]
SASRec epoch 8/8:  22%|██▏       | 336/1500 [00:20<01:10, 16.49it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 338/1500 [00:20<01:10, 16.52it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 340/1500 [00:20<01:10, 16.48it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 342/1500 [00:21<01:10, 16.45it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 344/1500 [00:21<01:10, 16.37it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 346/1500 [00:21<01:11, 16.24it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 348/1500 [00:21<01:11, 16.16it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 350/1500 [00:21<01:11, 16.13it/s, loss=1.11]
SASRec epoch 8/8:  23%|██▎       | 350/1500 [00:21<01:11, 16.13it/s, loss=1.13]
SASRec epoch 8/8:  23%|██▎       | 352/1500 [00:21<01:12, 15.88it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▎       | 354/1500 [00:21<01:11, 15.95it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▎       | 356/1500 [00:21<01:11, 15.95it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▍       | 358/1500 [00:22<01:11, 15.99it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▍       | 360/1500 [00:22<01:11, 15.97it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▍       | 362/1500 [00:22<01:11, 16.02it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▍       | 364/1500 [00:22<01:10, 16.07it/s, loss=1.13]
SASRec epoch 8/8:  24%|██▍       | 366/1500 [00:22<01:10, 16.14it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▍       | 368/1500 [00:22<01:10, 16.15it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▍       | 370/1500 [00:22<01:10, 16.12it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▍       | 372/1500 [00:22<01:09, 16.12it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▍       | 374/1500 [00:23<01:09, 16.11it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▌       | 376/1500 [00:23<01:09, 16.21it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▌       | 378/1500 [00:23<01:09, 16.20it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▌       | 380/1500 [00:23<01:09, 16.20it/s, loss=1.13]
SASRec epoch 8/8:  25%|██▌       | 382/1500 [00:23<01:08, 16.33it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▌       | 384/1500 [00:23<01:08, 16.40it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▌       | 386/1500 [00:23<01:08, 16.34it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▌       | 388/1500 [00:23<01:07, 16.35it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▌       | 390/1500 [00:24<01:07, 16.41it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▌       | 392/1500 [00:24<01:07, 16.40it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▋       | 394/1500 [00:24<01:07, 16.32it/s, loss=1.13]
SASRec epoch 8/8:  26%|██▋       | 396/1500 [00:24<01:07, 16.31it/s, loss=1.13]
SASRec epoch 8/8:  27%|██▋       | 398/1500 [00:24<01:07, 16.41it/s, loss=1.13]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.45it/s, loss=1.13]
SASRec epoch 8/8:  27%|██▋       | 400/1500 [00:24<01:06, 16.45it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 402/1500 [00:24<01:06, 16.41it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 404/1500 [00:24<01:06, 16.56it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 406/1500 [00:25<01:05, 16.60it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 408/1500 [00:25<01:05, 16.58it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 410/1500 [00:25<01:06, 16.50it/s, loss=1.11]
SASRec epoch 8/8:  27%|██▋       | 412/1500 [00:25<01:06, 16.39it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 414/1500 [00:25<01:06, 16.38it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 416/1500 [00:25<01:06, 16.40it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 418/1500 [00:25<01:05, 16.46it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 420/1500 [00:25<01:05, 16.46it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 422/1500 [00:25<01:05, 16.52it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 424/1500 [00:26<01:05, 16.55it/s, loss=1.11]
SASRec epoch 8/8:  28%|██▊       | 426/1500 [00:26<01:05, 16.36it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▊       | 428/1500 [00:26<01:06, 16.17it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▊       | 430/1500 [00:26<01:05, 16.28it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 432/1500 [00:26<01:05, 16.26it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 434/1500 [00:26<01:06, 16.15it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 436/1500 [00:26<01:05, 16.18it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 438/1500 [00:26<01:05, 16.20it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 440/1500 [00:27<01:05, 16.10it/s, loss=1.11]
SASRec epoch 8/8:  29%|██▉       | 442/1500 [00:27<01:07, 15.76it/s, loss=1.11]
SASRec epoch 8/8:  30%|██▉       | 444/1500 [00:27<01:06, 15.87it/s, loss=1.11]
SASRec epoch 8/8:  30%|██▉       | 446/1500 [00:27<01:05, 16.03it/s, loss=1.11]
SASRec epoch 8/8:  30%|██▉       | 448/1500 [00:27<01:04, 16.24it/s, loss=1.11]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:27<01:05, 16.09it/s, loss=1.11]
SASRec epoch 8/8:  30%|███       | 450/1500 [00:27<01:05, 16.09it/s, loss=1.11]
SASRec epoch 8/8:  30%|███       | 452/1500 [00:27<01:06, 15.88it/s, loss=1.11]
SASRec epoch 8/8:  30%|███       | 454/1500 [00:27<01:04, 16.13it/s, loss=1.11]
SASRec epoch 8/8:  30%|███       | 456/1500 [00:28<01:04, 16.28it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 458/1500 [00:28<01:03, 16.44it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 460/1500 [00:28<01:02, 16.52it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 462/1500 [00:28<01:02, 16.53it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 464/1500 [00:28<01:02, 16.57it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 466/1500 [00:28<01:02, 16.62it/s, loss=1.11]
SASRec epoch 8/8:  31%|███       | 468/1500 [00:28<01:02, 16.52it/s, loss=1.11]
SASRec epoch 8/8:  31%|███▏      | 470/1500 [00:28<01:02, 16.41it/s, loss=1.11]
SASRec epoch 8/8:  31%|███▏      | 472/1500 [00:29<01:02, 16.48it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 474/1500 [00:29<01:01, 16.58it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 476/1500 [00:29<01:01, 16.62it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 478/1500 [00:29<01:01, 16.56it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 480/1500 [00:29<01:01, 16.64it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 482/1500 [00:29<01:01, 16.59it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 484/1500 [00:29<01:02, 16.38it/s, loss=1.11]
SASRec epoch 8/8:  32%|███▏      | 486/1500 [00:29<01:02, 16.23it/s, loss=1.11]
SASRec epoch 8/8:  33%|███▎      | 488/1500 [00:30<01:02, 16.16it/s, loss=1.11]

[SASRec] epoch 8/8 loss=1.0973

[SASRec(VAL)/ALL] n=31679
[SASRec(VAL)/ALL] short rec lists: 0/31679 (0.000)

=== SASRec(VAL)/ALL ===
K= 5 | Recall@5: 0.0002 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0011 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0032 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0057 | NDCG@100: 0.0012 | MAP@100: 0.0003

[SASRec(VAL)/WARM] n=25095

SASRec hyperparam search: 100%|██████████| 4/4 [30:38<00:00, 459.51s/it]

[SASRec(VAL)/WARM] short rec lists: 0/25095 (0.000)

=== SASRec(VAL)/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0013 | NDCG@10: 0.0004 | MAP@10: 0.0002
K=20 | Recall@20: 0.0014 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0034 | NDCG@50: 0.0008 | MAP@50: 0.0003
K=100 | Recall@100: 0.0062 | NDCG@100: 0.0013 | MAP@100: 0.0003

[SASRec(VAL)/COLD] n=1187
[SASRec(VAL)/COLD] short rec lists: 0/1187 (0.000)

=== SASRec(VAL)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0008 | NDCG@10: 0.0003 | MAP@10: 0.0001
K=20 | Recall@20: 0.0017 | NDCG@20: 0.0005 | MAP@20: 0.0002
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0034 | NDCG@100: 0.0007 | MAP@100: 0.0002
VAL target score: split=ALL K=50 Recall=0.003157

BEST: {'max_len': 50, 'hidden': 64, 'n_heads': 2, 'dropout': 0.2, 'lr': 0.001} score= 0.0035038984816439913

In [ ]:
best_cfg = best["cfg"]

sas_model_test, sas_rec_test = fit_sasrec(
    test_pack, test_seqs, test_item_side,
    max_len=best_cfg["max_len"],
    hidden=best_cfg["hidden"],
    n_layers=2,
    n_heads=best_cfg["n_heads"],
    dropout=best_cfg["dropout"],
    lr=best_cfg["lr"],
    weight_decay=1e-4,
    batch_size=256,
    steps_per_epoch=2500,   # можно больше для качества
    epochs=15,              # можно больше для качества
    maxK_cache=max(KS),
)

outs_sas = evaluate_pack_subsets(test_pack, sas_rec_test, "SASRec", ks=KS)
outs_sas

## Matrix TF-IDF

In [ ]:
import numpy as np
from scipy.sparse import diags
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize

def train_cb_tfidf(pack, item_docs, vec_params):
    """
    pack: val_pack или test_pack (из build_split_objects)
    item_docs: list[str] длины pack["n_items"] в порядке item index i=0..n_items-1
    vec_params: параметры TfidfVectorizer
    """
    vec = TfidfVectorizer(**vec_params)
    X_items = vec.fit_transform(item_docs).astype(np.float32)  # (n_items, n_terms)


    R = pack["R"].astype(np.float32)  # (n_users, n_items)
    prof = R @ X_items  # (n_users, n_terms)

    cnt = np.asarray(R.getnnz(axis=1)).astype(np.float32)
    cnt[cnt == 0] = 1.0
    prof = diags(1.0 / cnt) @ prof
    prof = normalize(prof, norm="l2", axis=1)

    model = {"vec": vec, "X_items": normalize(X_items, norm="l2", axis=1), "prof": prof}
    return model

import numpy as np

def make_recommender(pack, model, filter_seen=True, maxK=50):
    X_items = model["X_items"]   # sparse (n_items, n_terms), L2-норм
    prof = model["prof"]         # sparse (n_users, n_terms), L2-норм

    user_train_items = pack["user_train_items"]
    cache = {}  # cache[u] = np.int32[top-maxK]  (НЕ scores!)

    def recommend_fn(u: int, K: int):
        u = int(u)
        K = int(K)
        if K <= 0:
            return np.array([], dtype=np.int32)


        if u not in cache:
            # scores длины n_items создаётся временно и НЕ сохраняется
            scores = (prof[u] @ X_items.T).toarray().ravel()

            if filter_seen:
                seen = user_train_items.get(u, None)
                if seen:
                    scores[list(seen)] = -np.inf

            kk = min(int(maxK), scores.shape[0])
            idx = np.argpartition(-scores, kk - 1)[:kk]
            idx = idx[np.argsort(-scores[idx])]
            cache[u] = idx.astype(np.int32)

        idx = cache[u]
        return idx[: min(K, idx.size)]

    return recommend_fn

## Models functions

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
from scipy.sparse import identity, hstack
KS = (5, 10, 20, 50, 100)

def evaluate_pack_subsets(pack, recommend_fn, name, ks=KS):
    ef = pack["eval_f"]
    outs = {}

    def run(mask, split):
        u = ef.loc[mask, "u"].values
        i = ef.loc[mask, "i"].values
        print(f"\n[{name}/{split}] n={len(u)}")
        out = evaluate_next_item(u, i, recommend_fn, ks=ks, name=f"{name}/{split}")
        print_metrics(f"{name}/{split}", out, ks=ks)
        return out

    outs["ALL"]  = run(np.ones(len(ef), dtype=bool), "ALL")
    outs["WARM"] = run(ef["is_warm_item_eligible"].values, "WARM")
    outs["COLD"] = run(ef["is_cold_item"].values, "COLD")
    return outs

# ---------- baselines ----------
def make_pop_recommender(pack):
    train_f = pack["train_f"]
    user_train_items = pack["user_train_items"]
    item_pop = train_f.groupby("i")["u"].nunique().sort_values(ascending=False)
    pop_ranked_items = item_pop.index.values.astype(np.int32)
    def recommend(u, K):
        seen = user_train_items.get(int(u), set())
        recs = []
        for it in pop_ranked_items:
            if int(it) not in seen:
                recs.append(int(it))
                if len(recs) == K:
                    break
        return np.asarray(recs, dtype=np.int32)
    return recommend

def make_random_recommender(pack, seed=SEED):
    rng = np.random.default_rng(seed)
    user_train_items = pack["user_train_items"]
    all_items = pack["all_items"]
    n_items = pack["n_items"]
    def recommend(u, K):
        seen = user_train_items.get(int(u), set())
        if len(seen) >= n_items:
            return np.array([], dtype=np.int32)
        candidates = np.setdiff1d(all_items, np.fromiter(seen, dtype=np.int32), assume_unique=False)
        if candidates.size <= K:
            return candidates.astype(np.int32)
        idx = rng.choice(candidates.size, size=K, replace=False)
        return candidates[idx].astype(np.int32)
    return recommend

# ---------- CF models (fit -> recommend_fn) ----------
from implicit.nearest_neighbours import CosineRecommender, tfidf_weight, bm25_weight
from implicit.bpr import BayesianPersonalizedRanking
from implicit.als import AlternatingLeastSquares
from lightfm import LightFM

def fit_itemknn(pack, weighting="bm25", K_sim=100, bm25_K1=1.2, bm25_B=0.75):
    R = pack["R"].tocsr()
    if weighting == "raw":
        Rw = R
    elif weighting == "tfidf":
        Rw = tfidf_weight(R).tocsr()
    elif weighting == "bm25":
        Rw = bm25_weight(R, K1=bm25_K1, B=bm25_B).tocsr()
    else:
        raise ValueError("weighting must be raw/tfidf/bm25")

    model = CosineRecommender(K=K_sim)
    model.fit(Rw.tocsr())

    def recommend(u, K):
        items, _ = model.recommend(userid=int(u), user_items=Rw[int(u)], N=int(K), filter_already_liked_items=True)
        return np.asarray(items, dtype=np.int32)

    return recommend

def fit_bpr(pack, factors=64, learning_rate=0.05, regularization=0.002, iterations=200):
    R = pack["R"].tocsr()
    model = BayesianPersonalizedRanking(
        factors=int(factors),
        learning_rate=float(learning_rate),
        regularization=float(regularization),
        iterations=int(iterations),
        random_state=SEED
    )
    model.fit(R)

    def recommend(u, K):
        items, _ = model.recommend(userid=int(u), user_items=R[int(u)], N=int(K), filter_already_liked_items=True)
        return np.asarray(items, dtype=np.int32)

    return recommend

def fit_als(pack, factors=128, regularization=0.01, iterations=40, alpha=40.0):
    R = pack["R"].tocsr().astype(np.float32)
    R_conf = (R * float(alpha)).tocsr()
    model = AlternatingLeastSquares(
        factors=int(factors),
        regularization=float(regularization),
        iterations=int(iterations),
        random_state=SEED
    )
    model.fit(R_conf)

    def recommend(u, K):
        items, _ = model.recommend(userid=int(u), user_items=R[int(u)], N=int(K), filter_already_liked_items=True)
        return np.asarray(items, dtype=np.int32)

    return recommend

def fit_lightfm_cf(pack, no_components=128, loss="warp", learning_rate=0.05,
                   item_alpha=1e-6, user_alpha=1e-6, epochs=30, num_threads=8):
    R = pack["R"].tocoo()
    model = LightFM(
        no_components=int(no_components),
        loss=loss,
        learning_rate=float(learning_rate),
        item_alpha=float(item_alpha),
        user_alpha=float(user_alpha),
        random_state=SEED
    )
    model.fit(R, epochs=int(epochs), num_threads=int(num_threads), verbose=False)

    user_train_items = pack["user_train_items"]
    all_items = pack["all_items"]
    n_items = pack["n_items"]

    def recommend(u, K):
        seen = user_train_items.get(int(u), set())
        if len(seen) >= n_items:
            return np.array([], dtype=np.int32)
        candidates = np.setdiff1d(all_items, np.fromiter(seen, dtype=np.int32), assume_unique=False)
        if candidates.size == 0:
            return np.array([], dtype=np.int32)
        scores = model.predict(int(u), candidates, num_threads=int(num_threads))
        kk = min(int(K), scores.size)
        topk = np.argpartition(-scores, kk-1)[:kk]
        ranked = candidates[topk][np.argsort(-scores[topk])]
        return ranked.astype(np.int32)

    return recommend

## CB; Hybrid; Fusion

In [ ]:
# ---------- CB TF-IDF (metadata + optional train-only review text) ----------
# берём сохранённые best_cb_vec_params; если не сохранил, используй дефолт
cb_vec_params = globals().get("best_cb_vec_params", {
    "lowercase": True, "stop_words": "english", "norm": "l2", "sublinear_tf": True,
    "ngram_range": (1, 1), "max_df": 1.0, "max_features": 300000, "min_df": 5
})

# IMPORTANT for cold-start:
# categories/attrs tokens can be sparse; too aggressive min_df may wipe most features.
# For cold-start evaluation (where review text is empty for cold items), use softer min_df.
cb_vec_params_cold = dict(cb_vec_params)
cb_vec_params_cold["min_df"] = min(int(cb_vec_params.get("min_df", 5)), 2)

cb_model = train_cb_tfidf(test_pack, item_docs_test, cb_vec_params_cold)
cb_rec = make_recommender(test_pack, cb_model, filter_seen=True)


# ---------- Hybrid LightFM (content features) ----------
# Key fix: item_features must cover ALL items (incl. cold) and should not be dominated by per-item identity.
# We keep identity features but down-weight them; TF-IDF features carry generalizable signal.

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
from scipy.sparse import identity, hstack
from lightfm import LightFM


def fit_lightfm_hybrid(pack, item_docs, vec_params, no_components=64, loss="warp",
                       learning_rate=0.05, item_alpha=1e-6, user_alpha=1e-6,
                       epochs=30, num_threads=8, identity_weight=0.05):
    vec = TfidfVectorizer(**vec_params)
    X = vec.fit_transform(item_docs).astype(np.float32)
    X = normalize(X, norm="l2", axis=1)

    # identity features help warm items but can hurt cold start if they dominate.
    # down-weight identity part so content features are the main signal.
    if identity_weight is not None and float(identity_weight) > 0:
        I = identity(pack["n_items"], format="csr", dtype=np.float32) * float(identity_weight)
        item_features = hstack([I, X], format="csr")
    else:
        item_features = X.tocsr()

    user_features = identity(pack["n_users"], format="csr", dtype=np.float32)

    R = pack["R"].tocoo()
    model = LightFM(
        no_components=int(no_components),
        loss=loss,
        learning_rate=float(learning_rate),
        item_alpha=float(item_alpha),
        user_alpha=float(user_alpha),
        random_state=SEED
    )
    model.fit(R, user_features=user_features, item_features=item_features,
              epochs=int(epochs), num_threads=int(num_threads), verbose=False)

    user_train_items = pack["user_train_items"]
    all_items = pack["all_items"]
    n_items = pack["n_items"]

    def recommend(u, K):
        seen = user_train_items.get(int(u), set())
        if len(seen) >= n_items:
            return np.array([], dtype=np.int32)
        candidates = np.setdiff1d(all_items, np.fromiter(seen, dtype=np.int32), assume_unique=False)
        if candidates.size == 0:
            return np.array([], dtype=np.int32)
        scores = model.predict(int(u), candidates,
                               user_features=user_features, item_features=item_features,
                               num_threads=int(num_threads))
        kk = min(int(K), scores.size)
        topk = np.argpartition(-scores, kk-1)[:kk]
        ranked = candidates[topk][np.argsort(-scores[topk])]
        return ranked.astype(np.int32)

    parts = {
        "model": model,
        "vec": vec,
        "user_features": user_features,
        "item_features": item_features,
        "recommend": recommend,
    }
    return parts


cb_vec_params_l = globals().get("best_cb_vec_params", {
    "lowercase": True, "stop_words": "english", "norm": "l2", "sublinear_tf": True,
    "ngram_range": (1, 2), "max_df": 1.0, "max_features": 200_000, "min_df": 2
})
cb_vec_params_lfm = dict(cb_vec_params_l)
hyb_parts = fit_lightfm_hybrid(
    test_pack, item_docs_test, cb_vec_params_lfm,
    no_components=64, loss="warp", learning_rate=0.05,
    item_alpha=1e-6, user_alpha=1e-6, epochs=40, num_threads=8,
    identity_weight=0.05
)

hyb_rec = hyb_parts["recommend"]


# ---------- Score-fusion Hybrid (LightFM-hybrid score + CB score) ----------
# This tends to improve cold-start robustness, because CB contributes direct content matching.


def make_score_fusion_recommender(pack, hyb_parts, cb_model, alpha=0.6, num_threads=8, filter_seen=True):
    model = hyb_parts["model"]
    user_features = hyb_parts["user_features"]
    item_features = hyb_parts["item_features"]

    prof = cb_model["prof"]
    X_items = cb_model["X_items"]

    user_train_items = pack["user_train_items"]
    all_items = pack["all_items"]
    n_items = pack["n_items"]

    def _z(x):
        x = x.astype(np.float32)
        m = float(x.mean())
        s = float(x.std())
        return (x - m) / (s + 1e-8)

    def recommend(u, K):
        u = int(u)
        K = int(K)
        if K <= 0:
            return np.array([], dtype=np.int32)

        seen = user_train_items.get(u, set())
        if filter_seen and len(seen) >= n_items:
            return np.array([], dtype=np.int32)

        if filter_seen and seen:
            candidates = np.setdiff1d(all_items, np.fromiter(seen, dtype=np.int32), assume_unique=False)
        else:
            candidates = all_items

        if candidates.size == 0:
            return np.array([], dtype=np.int32)

        # LightFM-hybrid scores
        s_lfm = model.predict(u, candidates,
                              user_features=user_features, item_features=item_features,
                              num_threads=int(num_threads)).astype(np.float32)

        # CB cosine scores (profile vs item vectors) computed only on candidates
        s_cb = (prof[u] @ X_items[candidates].T).toarray().ravel().astype(np.float32)

        # Normalize and fuse
        s = float(alpha) * _z(s_lfm) + (1.0 - float(alpha)) * _z(s_cb)

        kk = min(K, s.size)
        topk = np.argpartition(-s, kk-1)[:kk]
        ranked = candidates[topk][np.argsort(-s[topk])]
        return ranked.astype(np.int32)

    return recommend

hyb_fused_rec = make_score_fusion_recommender(test_pack, hyb_parts, cb_model, alpha=0.6, num_threads=8)

## Fit

In [ ]:
# ======== RUN EVAL (FAST) ========
recommenders = {}
outs = {}
aux = {}
masks = _get_masks(test_pack)

# (опционально) быстрый режим: оценивать на подвыборке строк eval
SAMPLE_N = None   # например 5000 для быстрого прогона; None = полный

# Baselines
recommenders["Popularity"] = make_pop_recommender(test_pack)
recommenders["Random"]     = make_random_recommender(test_pack)

# ItemKNN
w, K_sim, K1, B = best_itemknn_params
knn_rec = fit_itemknn(
    test_pack,
    weighting=w,
    K_sim=int(K_sim),
    bm25_K1=(float(K1) if K1 else 1.2),
    bm25_B=(float(B) if B else 0.75)
)
recommenders["ItemKNN"] = knn_rec

# BPR
f, lr, reg, it = best_bpr_params
bpr_rec = fit_bpr(
    test_pack,
    factors=int(f),
    learning_rate=float(lr),
    regularization=float(reg),
    iterations=int(it)
)
recommenders["BPR"] = bpr_rec

# ALS
f, reg, it, a = best_als_params
als_rec = fit_als(
    test_pack,
    factors=int(f),
    regularization=float(reg),
    iterations=int(it),
    alpha=float(a)
)
recommenders["ALS"] = als_rec

# LightFM CF
loss, c, lr, ia, ua, ep = best_lfm_cf_params
lfm_cf_rec = fit_lightfm_cf(
    test_pack,
    no_components=int(c),
    loss=loss,
    learning_rate=float(lr),
    item_alpha=float(ia),
    user_alpha=float(ua),
    epochs=int(ep),
    num_threads=8
)
recommenders["LightFM(CF)"] = lfm_cf_rec

# CB / Hybrid / Fusion (предполагаем, что вы их уже обучили выше и переменные существуют)
recommenders["CB(TFIDF)"]        = cb_rec
recommenders["LightFM(Hybrid)"]  = hyb_rec
recommenders["Hybrid(Fusion)"]   = hyb_fused_rec

# ======== FAST EVAL: accuracy + aux in ONE PASS ========
for model, rec_fn in recommenders.items():
    outs[model] = {}
    aux[model] = {}
    for split, mask in masks.items():
        out_split, aux_split = evaluate_with_aux(
            test_pack, rec_fn, mask, ks=KS, sample_n=SAMPLE_N, seed=42
        )
        outs[model][split] = out_split
        aux[model][split]  = aux_split

/usr/local/lib/python3.12/dist-packages/implicit/utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0030736923217773438 seconds
  warnings.warn(

  0%|          | 0/19942 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 2 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/40 [00:00<?, ?it/s]

In [ ]:
# ======== SUMMARY TABLE (WITH COVERAGE/NOVELTY/COLD*) ========
pd.set_option('display.max_rows', 200)

def to_rows(split, model, out, aux_for_model_split):
    cov = aux_for_model_split["Coverage"]
    nov = aux_for_model_split["Novelty"]
    csh = aux_for_model_split["ColdShare"]
    ccv = aux_for_model_split["ColdCoverage"]

    return [{
        "split": split,
        "model": model,
        "K": int(k),
        "Recall": float(r),
        "NDCG": float(n),
        "MAP": float(m),
        "Coverage": float(cov[k]),
        "Novelty": float(nov[k]),
        "ColdShare": float(csh[k]),
        "ColdCoverage": float(ccv[k]),
    } for k, (r, n, m) in out.items()]

rows = []
for model, d in outs.items():
    for split in ["ALL", "WARM", "COLD"]:
        rows += to_rows(split, model, d[split], aux[model][split])

res_cs = (
    pd.DataFrame(rows)
      .sort_values(["split", "K", "Recall"], ascending=[True, True, False])
      .reset_index(drop=True)
)

res_cs

,split,model,K,Recall,NDCG,MAP,Coverage,Novelty,ColdShare,ColdCoverage
0,ALL,ALS,5,0.019437,0.011879,0.009427,0.169391,11.534911,0.000000,0.000000
1,ALL,LightFM(CF),5,0.014869,0.009062,0.007183,0.015094,10.014725,0.000000,0.000000
2,ALL,BPR,5,0.010648,0.006446,0.005084,0.263213,12.967369,0.000000,0.000000
3,ALL,LightFM(Hybrid),5,0.006300,0.003955,0.003192,0.537108,12.292205,0.000397,0.034664
4,ALL,Popularity,5,0.005954,0.003768,0.003064,0.000552,9.108951,0.000000,0.000000
5,ALL,Hybrid(Fusion),5,0.005450,0.003461,0.002816,0.579731,12.772761,0.000756,0.070378
6,ALL,ItemKNN,5,0.003560,0.002280,0.001859,0.566794,15.011279,0.000000,0.000000
7,ALL,CB(TFIDF),5,0.002142,0.001437,0.001208,0.550547,13.630944,0.001815,0.177521
8,ALL,Random,5,0.000221,0.000117,0.000085,0.999549,15.545868,0.048009,1.000000
9,ALL,ALS,10,0.034369,0.016650,0.011361,0.220590,11.712346,0.000000,0.000000
10,ALL,LightFM(CF),10,0.026430,0.012781,0.008707,0.023217,10.236734,0.000000,0.000000
11,ALL,BPR,10,0.018775,0.009051,0.006146,0.327700,13.077820,0.000000,0.000000
12,ALL,LightFM(Hybrid),10,0.012223,0.005865,0.003976,0.654348,12.422916,0.000510,0.069328
13,ALL,Popularity,10,0.011498,0.005582,0.003825,0.000903,9.295942,0.000000,0.000000
14,ALL,Hybrid(Fusion),10,0.009703,0.004809,0.003357,0.684234,12.837634,0.001046,0.163866
15,ALL,ItemKNN,10,0.007686,0.003597,0.002393,0.650135,15.002063,0.000000,0.000000
16,ALL,CB(TFIDF),10,0.004127,0.002080,0.001473,0.674506,13.668038,0.002230,0.335084
17,ALL,Random,10,0.000504,0.000207,0.000121,1.000000,15.543905,0.047628,1.000000
18,ALL,ALS,20,0.057176,0.022368,0.012906,0.282018,11.912021,0.000000,0.000000
19,ALL,LightFM(CF),20,0.043536,0.017068,0.009864,0.037459,10.487517,0.000000,0.000000
20,ALL,BPR,20,0.032479,0.012506,0.007090,0.396400,13.208584,0.000000,0.000000
21,ALL,LightFM(Hybrid),20,0.020539,0.007950,0.004540,0.744409,12.560511,0.000655,0.127101
22,ALL,Popularity,20,0.018996,0.007463,0.004333,0.001655,9.524995,0.000000,0.000000
23,ALL,Hybrid(Fusion),20,0.016854,0.006602,0.003841,0.777655,12.909449,0.001216,0.265756
24,ALL,ItemKNN,20,0.016192,0.005696,0.002942,0.688848,14.888933,0.000000,0.000000
25,ALL,CB(TFIDF),20,0.006710,0.002734,0.001654,0.783974,13.706862,0.002438,0.500000
26,ALL,Random,20,0.000819,0.000285,0.000141,1.000000,15.542381,0.047680,1.000000
27,ALL,ALS,50,0.106445,0.032072,0.014435,0.395547,12.204591,0.000000,0.000000
28,ALL,LightFM(CF),50,0.081307,0.024491,0.011027,0.068699,10.857467,0.000000,0.000000
29,ALL,BPR,50,0.062059,0.018307,0.007992,0.510430,13.413607,0.000000,0.000000
30,ALL,ItemKNN,50,0.047222,0.011762,0.003876,0.716077,14.537719,0.000000,0.000000
31,ALL,LightFM(Hybrid),50,0.042181,0.012200,0.005204,0.838582,12.761764,0.000941,0.255252
32,ALL,Popularity,50,0.035849,0.010770,0.004849,0.003510,9.938428,0.000000,0.000000
33,ALL,Hybrid(Fusion),50,0.035188,0.010195,0.004399,0.878347,13.014888,0.001417,0.482143
34,ALL,CB(TFIDF),50,0.014207,0.004204,0.001882,0.896149,13.756838,0.002741,0.723739
35,ALL,Random,50,0.001859,0.000488,0.000172,1.000000,15.542773,0.047709,1.000000
36,ALL,ALS,100,0.158896,0.040543,0.015170,0.515294,12.447638,0.000000,0.000000
37,ALL,LightFM(CF),100,0.124748,0.031495,0.011631,0.108866,11.178912,0.000000,0.000000
38,ALL,BPR,100,0.098822,0.024244,0.008507,0.598786,13.594808,0.000000,0.000000
39,ALL,LightFM(Hybrid),100,0.067761,0.016327,0.005561,0.893240,12.922174,0.001212,0.382353
40,ALL,ItemKNN,100,0.064768,0.014639,0.004139,0.716127,14.379587,0.000000,0.000000
41,ALL,Hybrid(Fusion),100,0.057365,0.013770,0.004708,0.931551,13.102346,0.001649,0.658613
42,ALL,Popularity,100,0.056137,0.014045,0.005133,0.006770,10.272141,0.000000,0.000000
43,ALL,CB(TFIDF),100,0.014207,0.004204,0.001882,0.896149,13.756838,0.002741,0.723739
44,ALL,Random,100,0.004095,0.000847,0.000203,1.000000,15.543704,0.047718,1.000000
45,COLD,Popularity,5,0.000000,0.000000,0.000000,0.000351,9.107894,0.000000,0.000000
46,COLD,Random,5,0.000000,0.000000,0.000000,0.248471,15.515859,0.046573,0.238445
47,COLD,ItemKNN,5,0.000000,0.000000,0.000000,0.172851,15.141962,0.000000,0.000000
48,COLD,BPR,5,0.000000,0.000000,0.000000,0.106659,13.227051,0.000000,0.000000
49,COLD,ALS,5,0.000000,0.000000,0.000000,0.079631,11.724836,0.000000,0.000000
50,COLD,LightFM(CF),5,0.000000,0.000000,0.000000,0.008926,10.164493,0.000000,0.000000
51,COLD,CB(TFIDF),5,0.000000,0.000000,0.000000,0.129425,13.920625,0.003163,0.017857
52,COLD,LightFM(Hybrid),5,0.000000,0.000000,0.000000,0.147628,12.670480,0.000527,0.002101
53,COLD,Hybrid(Fusion),5,0.000000,0.000000,0.000000,0.165129,13.176638,0.001054,0.005252
54,COLD,CB(TFIDF),10,0.000879,0.000313,0.000146,0.206850,13.945934,0.003954,0.046218
55,COLD,Popularity,10,0.000000,0.000000,0.000000,0.000752,9.294555,0.000000,0.000000
56,COLD,Random,10,0.000000,0.000000,0.000000,0.431200,15.540289,0.046749,0.411765
57,COLD,ItemKNN,10,0.000000,0.000000,0.000000,0.281216,15.114948,0.000000,0.000000
58,COLD,BPR,10,0.000000,0.000000,0.000000,0.164076,13.329533,0.000000,0.000000
59,COLD,ALS,10,0.000000,0.000000,0.000000,0.119095,11.891947,0.000000,0.000000
60,COLD,LightFM(CF),10,0.000000,0.000000,0.000000,0.014241,10.395734,0.000000,0.000000
61,COLD,LightFM(Hybrid),10,0.000000,0.000000,0.000000,0.241149,12.789497,0.000615,0.006303
62,COLD,Hybrid(Fusion),10,0.000000,0.000000,0.000000,0.254538,13.220358,0.001406,0.013655
63,COLD,CB(TFIDF),20,0.002636,0.000751,0.000264,0.308595,13.974488,0.003998,0.088235
64,COLD,Popularity,20,0.000000,0.000000,0.000000,0.001404,9.522530,0.000000,0.000000
65,COLD,Random,20,0.000000,0.000000,0.000000,0.677415,15.544480,0.046705,0.652311
66,COLD,ItemKNN,20,0.000000,0.000000,0.000000,0.418363,15.008799,0.000000,0.000000
67,COLD,BPR,20,0.000000,0.000000,0.000000,0.237840,13.449409,0.000000,0.000000
68,COLD,ALS,20,0.000000,0.000000,0.000000,0.173152,12.074574,0.000000,0.000000
69,COLD,LightFM(CF),20,0.000000,0.000000,0.000000,0.023669,10.633771,0.000000,0.000000
70,COLD,LightFM(Hybrid),20,0.000000,0.000000,0.000000,0.366362,12.923469,0.000747,0.016807
71,COLD,Hybrid(Fusion),20,0.000000,0.000000,0.000000,0.369923,13.284111,0.001845,0.036765
72,COLD,CB(TFIDF),50,0.005272,0.001301,0.000363,0.478688,14.013143,0.004956,0.209034
73,COLD,Hybrid(Fusion),50,0.003515,0.000684,0.000104,0.548440,13.368571,0.002496,0.119748
74,COLD,Random,50,0.002636,0.000537,0.000092,0.940477,15.549293,0.047522,0.944328
75,COLD,LightFM(Hybrid),50,0.000879,0.000156,0.000018,0.566192,13.109987,0.001107,0.049370
76,COLD,Popularity,50,0.000000,0.000000,0.000000,0.003159,9.936346,0.000000,0.000000
77,COLD,ItemKNN,50,0.000000,0.000000,0.000000,0.573313,14.705560,0.000000,0.000000
78,COLD,BPR,50,0.000000,0.000000,0.000000,0.360044,13.636981,0.000000,0.000000
79,COLD,ALS,50,0.000000,0.000000,0.000000,0.273042,12.364829,0.000000,0.000000
80,COLD,LightFM(CF),50,0.000000,0.000000,0.000000,0.045883,10.987483,0.000000,0.000000
81,COLD,Hybrid(Fusion),100,0.006151,0.001119,0.000145,0.683984,13.443913,0.002847,0.213235
82,COLD,CB(TFIDF),100,0.005272,0.001301,0.000363,0.478688,14.013143,0.004956,0.209034
83,COLD,Random,100,0.004394,0.000817,0.000115,0.996339,15.551627,0.047909,0.995798
84,COLD,LightFM(Hybrid),100,0.003515,0.000576,0.000053,0.704894,13.254026,0.001670,0.111345
85,COLD,Popularity,100,0.000000,0.000000,0.000000,0.006118,10.270121,0.000000,0.000000
86,COLD,ItemKNN,100,0.000000,0.000000,0.000000,0.620700,14.570750,0.000000,0.000000
87,COLD,BPR,100,0.000000,0.000000,0.000000,0.466854,13.801733,0.000000,0.000000
88,COLD,ALS,100,0.000000,0.000000,0.000000,0.382359,12.601169,0.000000,0.000000
89,COLD,LightFM(CF),100,0.000000,0.000000,0.000000,0.076973,11.298235,0.000000,0.000000
90,WARM,ALS,5,0.025027,0.015296,0.012138,0.160465,11.485539,0.000000,0.000000
91,WARM,LightFM(CF),5,0.019146,0.011669,0.009249,0.014693,9.966822,0.000000,0.000000
92,WARM,BPR,5,0.013710,0.008300,0.006547,0.252733,12.908101,0.000000,0.000000
93,WARM,LightFM(Hybrid),5,0.008072,0.005076,0.004100,0.492980,12.196041,0.000316,0.023109
94,WARM,Popularity,5,0.007666,0.004852,0.003945,0.000552,9.109328,0.000000,0.000000
95,WARM,Hybrid(Fusion),5,0.006936,0.004390,0.003565,0.525775,12.674838,0.000641,0.050420
96,WARM,ItemKNN,5,0.004584,0.002936,0.002394,0.550145,14.981350,0.000000,0.000000
97,WARM,CB(TFIDF),5,0.002677,0.001769,0.001474,0.485458,13.559139,0.001444,0.122899
98,WARM,Random,5,0.000122,0.000081,0.000068,0.998295,15.530098,0.047678,0.997899
99,WARM,ALS,10,0.044254,0.021439,0.014629,0.209608,11.665341,0.000000,0.000000
100,WARM,LightFM(CF),10,0.034032,0.016457,0.011211,0.022214,10.189284,0.000000,0.000000
101,WARM,BPR,10,0.024176,0.011654,0.007914,0.316367,13.019426,0.000000,0.000000
102,WARM,LightFM(Hybrid),10,0.015657,0.007522,0.005106,0.614632,12.327831,0.000458,0.053571
103,WARM,Popularity,10,0.014806,0.007188,0.004925,0.000903,9.296397,0.000000,0.000000
104,WARM,Hybrid(Fusion),10,0.012372,0.006114,0.004257,0.635393,12.740710,0.000848,0.121849
105,WARM,ItemKNN,10,0.009897,0.004632,0.003081,0.639655,14.974108,0.000000,0.000000
106,WARM,CB(TFIDF),10,0.005152,0.002570,0.001804,0.610821,13.599806,0.001764,0.250000
107,WARM,Random,10,0.000446,0.000189,0.000114,1.000000,15.540660,0.047824,1.000000
108,WARM,ALS,20,0.073622,0.028801,0.016618,0.272891,11.866514,0.000000,0.000000
109,WARM,LightFM(CF),20,0.056058,0.021978,0.012701,0.036406,10.443302,0.000000,0.000000
110,WARM,BPR,20,0.041820,0.016103,0.009129,0.385819,13.152637,0.000000,0.000000
111,WARM,LightFM(Hybrid),20,0.026285,0.010185,0.005825,0.714472,12.468364,0.000572,0.103992
112,WARM,Popularity,20,0.024459,0.009609,0.005580,0.001655,9.525673,0.000000,0.000000
113,WARM,Hybrid(Fusion),20,0.021539,0.008411,0.004877,0.735583,12.815546,0.000980,0.210084
114,WARM,ItemKNN,20,0.020849,0.007334,0.003789,0.682279,14.858591,0.000000,0.000000
115,WARM,CB(TFIDF),20,0.008315,0.003372,0.002025,0.728112,13.641228,0.001917,0.390756
116,WARM,Random,20,0.000771,0.000271,0.000136,1.000000,15.542221,0.047874,1.000000
117,WARM,ALS,50,0.137062,0.041297,0.018587,0.382058,12.160705,0.000000,0.000000
118,WARM,LightFM(CF),50,0.104693,0.031536,0.014198,0.066493,10.817594,0.000000,0.000000
119,WARM,BPR,50,0.079909,0.023572,0.010291,0.498746,13.361944,0.000000,0.000000
120,WARM,ItemKNN,50,0.060804,0.015145,0.004991,0.715826,14.493842,0.000000,0.000000
121,WARM,LightFM(Hybrid),50,0.053787,0.015587,0.006669,0.821181,12.675506,0.000819,0.221639
122,WARM,Popularity,50,0.046161,0.013868,0.006244,0.003510,9.938966,0.000000,0.000000
123,WARM,Hybrid(Fusion),50,0.044376,0.012887,0.005573,0.847307,12.926564,0.001149,0.398109
124,WARM,CB(TFIDF),50,0.017199,0.005110,0.002295,0.853826,13.695052,0.002190,0.616597
125,WARM,Random,50,0.001947,0.000502,0.000172,1.000000,15.543011,0.047683,1.000000
126,WARM,ALS,100,0.204600,0.052204,0.019533,0.499950,12.406252,0.000000,0.000000
127,WARM,LightFM(CF),100,0.160630,0.040554,0.014976,0.105707,11.142908,0.000000,0.000000
128,WARM,BPR,100,0.127246,0.031217,0.010954,0.588858,13.547518,0.000000,0.000000
129,WARM,LightFM(Hybrid),100,0.086034,0.020790,0.007119,0.881657,12.840801,0.001036,0.352941
130,WARM,ItemKNN,100,0.083398,0.018850,0.005329,0.716127,14.329206,0.000000,0.000000
131,WARM,Popularity,100,0.072283,0.018084,0.006610,0.006770,10.272657,0.000000,0.000000
132,WARM,Hybrid(Fusion),100,0.072162,0.017365,0.005959,0.909638,13.018719,0.001335,0.561975
133,WARM,CB(TFIDF),100,0.017199,0.005110,0.002295,0.853826,13.695052,0.002190,0.616597
134,WARM,Random,100,0.004827,0.000965,0.000212,1.000000,15.543024,0.047730,1.000000

In [ ]:
# split	model	K	Recall	NDCG	MAP	Coverage	Novelty	ColdShare	ColdCoverage
# 0	ALL	ALS+CB+CatBoost	5	0.034283	0.022583	0.018756	0.564854	12.271246	0.000680	0.164807
# 1	ALL	ALS+CB+CatBoost	10	0.054061	0.028954	0.021370	0.637941	12.129508	0.000637	0.266094
# 2	ALL	ALS+CB+CatBoost	20	0.082056	0.036002	0.023289	0.723954	12.161037	0.000654	0.416309
# 3	ALL	ALS+CB+CatBoost	50	0.138831	0.047219	0.025071	0.809277	12.293179	0.000522	0.569099
# 4	ALL	ALS+CB+CatBoost	100	0.194721	0.056270	0.025864	0.874951	12.485408	0.000540	0.739914
# 5	COLD	ALS+CB+CatBoost	5	0.000000	0.000000	0.000000	0.111173	12.550417	0.001289	0.008584
# 6	COLD	ALS+CB+CatBoost	10	0.000000	0.000000	0.000000	0.146405	12.380398	0.001418	0.018026
# 7	COLD	ALS+CB+CatBoost	20	0.000644	0.000165	0.000046	0.194102	12.390392	0.001546	0.039485
# 8	COLD	ALS+CB+CatBoost	50	0.000644	0.000165	0.000046	0.273586	12.512285	0.001018	0.060944
# 9	COLD	ALS+CB+CatBoost	100	0.000644	0.000165	0.000046	0.357269	12.696622	0.001121	0.126180
# 10	WARM	ALS+CB+CatBoost	5	0.038532	0.025383	0.021081	0.536544	12.235942	0.000569	0.131330
# 11	WARM	ALS+CB+CatBoost	10	0.060761	0.032542	0.024019	0.606318	12.097766	0.000561	0.224893
# 12	WARM	ALS+CB+CatBoost	20	0.092210	0.040460	0.026175	0.688689	12.131628	0.000585	0.357940
# 13	WARM	ALS+CB+CatBoost	50	0.156007	0.053064	0.028177	0.777883	12.265773	0.000480	0.515880
# 14	WARM	ALS+CB+CatBoost	100	0.218824	0.063237	0.029068	0.852382	12.459460	0.000488	0.696996

In [ ]:
=== SASRec/COLD ===
K= 5 | Recall@5: 0.0009 | NDCG@5: 0.0009 | MAP@5: 0.0009
K=10 | Recall@10: 0.0009 | NDCG@10: 0.0009 | MAP@10: 0.0009
K=20 | Recall@20: 0.0009 | NDCG@20: 0.0009 | MAP@20: 0.0009
K=50 | Recall@50: 0.0009 | NDCG@50: 0.0009 | MAP@50: 0.0009
K=100 | Recall@100: 0.0044 | NDCG@100: 0.0014 | MAP@100: 0.0009

In [ ]:
# # ======== RUN EVAL (TEST_CS) ========
# recommenders = {}
# outs = {}
# aux = {}
# masks = _get_masks(test_pack)


# # Baselines
# recommenders["Popularity"] = make_pop_recommender(test_pack)
# outs["Popularity"] = evaluate_pack_subsets(test_pack, recommenders["Popularity"], "Popularity")

# recommenders["Random"] = make_random_recommender(test_pack)
# outs["Random"] = evaluate_pack_subsets(test_pack, recommenders["Random"], "Random")

# # ItemKNN best params
# w, K_sim, K1, B = best_itemknn_params
# knn_rec = fit_itemknn(test_pack, weighting=w, K_sim=K_sim, bm25_K1=(K1 if K1 else 1.2), bm25_B=(B if B else 0.75))
# recommenders["ItemKNN"] = knn_rec
# outs["ItemKNN"] = evaluate_pack_subsets(test_pack, knn_rec, "ItemKNN")

# # BPR best
# f, lr, reg, it = best_bpr_params
# bpr_rec = fit_bpr(test_pack, factors=f, learning_rate=lr, regularization=reg, iterations=it)
# recommenders["BPR"] = bpr_rec
# outs["BPR"] = evaluate_pack_subsets(test_pack, bpr_rec, "BPR")

# # ALS best
# f, reg, it, a = best_als_params
# als_rec = fit_als(test_pack, factors=f, regularization=reg, iterations=it, alpha=a)
# recommenders["ALS"] = als_rec
# outs["ALS"] = evaluate_pack_subsets(test_pack, als_rec, "ALS")

# # LightFM CF best
# loss, c, lr, ia, ua, ep = best_lfm_cf_params
# lfm_cf_rec = fit_lightfm_cf(
#     test_pack, no_components=c, loss=loss, learning_rate=lr,
#     item_alpha=ia, user_alpha=ua, epochs=ep, num_threads=8
# )
# recommenders["LightFM(CF)"] = lfm_cf_rec
# outs["LightFM(CF)"] = evaluate_pack_subsets(test_pack, lfm_cf_rec, "LightFM(CF)")

# # CB + Hybrid (у вас они уже обучены выше и лежат в cb_rec / hyb_rec / hyb_fused_rec)
# recommenders["CB(TFIDF)"] = cb_rec
# outs["CB(TFIDF)"] = evaluate_pack_subsets(test_pack, cb_rec, "CB(TFIDF)")

# recommenders["LightFM(Hybrid)"] = hyb_rec
# outs["LightFM(Hybrid)"] = evaluate_pack_subsets(test_pack, hyb_rec, "LightFM(Hybrid)")

# recommenders["Hybrid(Fusion)"] = hyb_fused_rec
# outs["Hybrid(Fusion)"] = evaluate_pack_subsets(test_pack, hyb_fused_rec, "Hybrid(Fusion)")

# # ======== AUX METRICS (Coverage / Novelty / ColdShare / ColdCoverage) ========
# aux = {}  # aux[model][split] -> dict with metric dicts by K

# for model, rec_fn in recommenders.items():
#     aux[model] = {}
#     for split, mask in masks.items():
#         aux[model][split] = {
#             "Coverage":     catalog_coverage_at_k(test_pack, rec_fn, mask, ks=KS),
#             "Novelty":      novelty_at_k(test_pack, rec_fn, mask, ks=KS),
#             "ColdShare":    cold_share_at_k(test_pack, rec_fn, mask, ks=KS),
#             "ColdCoverage": cold_coverage_at_k(test_pack, rec_fn, mask, ks=KS),
#         }

## Metrics

In [ ]:
# ======== SUMMARY TABLE ========
pd.set_option('display.max_rows', 200)
import pandas as pd

def to_rows(split, model, out, aux_for_model_split):
    cov = aux_for_model_split["Coverage"]
    nov = aux_for_model_split["Novelty"]
    csh = aux_for_model_split["ColdShare"]
    ccv = aux_for_model_split["ColdCoverage"]

    return [{
        "split": split,
        "model": model,
        "K": int(k),
        "Recall": float(r),
        "NDCG": float(n),
        "MAP": float(m),
        "Coverage": float(cov[k]),
        "Novelty": float(nov[k]),
        "ColdShare": float(csh[k]),
        "ColdCoverage": float(ccv[k]),
    } for k, (r, n, m) in out.items()]

rows = []
for model, d in outs.items():
    for split in ["ALL", "WARM", "COLD"]:
        rows += to_rows(split, model, d[split], aux[model][split])

res_cs = (
    pd.DataFrame(rows)
      .sort_values(["split", "K", "Recall"], ascending=[True, True, False])
      .reset_index(drop=True)
)

res_cs

,split,model,K,Recall,NDCG,MAP,Coverage,Novelty,ColdShare,ColdCoverage
0,ALL,ALS,5,0.019437,0.011879,0.009427,0.169391,11.534911,0.000000,0.000000
1,ALL,LightFM(CF),5,0.014869,0.009062,0.007183,0.015094,10.014725,0.000000,0.000000
2,ALL,BPR,5,0.010648,0.006446,0.005084,0.263213,12.967369,0.000000,0.000000
3,ALL,LightFM(Hybrid),5,0.006300,0.003955,0.003192,0.537108,12.292205,0.000397,0.034664
4,ALL,Popularity,5,0.005954,0.003768,0.003064,0.000552,9.108951,0.000000,0.000000
5,ALL,Hybrid(Fusion),5,0.005450,0.003461,0.002816,0.579731,12.772761,0.000756,0.070378
6,ALL,ItemKNN,5,0.003560,0.002280,0.001859,0.566794,15.011279,0.000000,0.000000
7,ALL,CB(TFIDF),5,0.002142,0.001437,0.001208,0.550547,13.630944,0.001815,0.177521
8,ALL,Random,5,0.000221,0.000117,0.000085,0.999549,15.545868,0.048009,1.000000
9,ALL,ALS,10,0.034369,0.016650,0.011361,0.220590,11.712346,0.000000,0.000000
10,ALL,LightFM(CF),10,0.026430,0.012781,0.008707,0.023217,10.236734,0.000000,0.000000
11,ALL,BPR,10,0.018775,0.009051,0.006146,0.327700,13.077820,0.000000,0.000000
12,ALL,LightFM(Hybrid),10,0.012223,0.005865,0.003976,0.654348,12.422916,0.000510,0.069328
13,ALL,Popularity,10,0.011498,0.005582,0.003825,0.000903,9.295942,0.000000,0.000000
14,ALL,Hybrid(Fusion),10,0.009703,0.004809,0.003357,0.684234,12.837634,0.001046,0.163866
15,ALL,ItemKNN,10,0.007686,0.003597,0.002393,0.650135,15.002063,0.000000,0.000000
16,ALL,CB(TFIDF),10,0.004127,0.002080,0.001473,0.674506,13.668038,0.002230,0.335084
17,ALL,Random,10,0.000504,0.000207,0.000121,1.000000,15.543905,0.047628,1.000000
18,ALL,ALS,20,0.057176,0.022368,0.012906,0.282018,11.912021,0.000000,0.000000
19,ALL,LightFM(CF),20,0.043536,0.017068,0.009864,0.037459,10.487517,0.000000,0.000000
20,ALL,BPR,20,0.032479,0.012506,0.007090,0.396400,13.208584,0.000000,0.000000
21,ALL,LightFM(Hybrid),20,0.020539,0.007950,0.004540,0.744409,12.560511,0.000655,0.127101
22,ALL,Popularity,20,0.018996,0.007463,0.004333,0.001655,9.524995,0.000000,0.000000
23,ALL,Hybrid(Fusion),20,0.016854,0.006602,0.003841,0.777655,12.909449,0.001216,0.265756
24,ALL,ItemKNN,20,0.016192,0.005696,0.002942,0.688848,14.888933,0.000000,0.000000
25,ALL,CB(TFIDF),20,0.006710,0.002734,0.001654,0.783974,13.706862,0.002438,0.500000
26,ALL,Random,20,0.000819,0.000285,0.000141,1.000000,15.542381,0.047680,1.000000
27,ALL,ALS,50,0.106445,0.032072,0.014435,0.395547,12.204591,0.000000,0.000000
28,ALL,LightFM(CF),50,0.081307,0.024491,0.011027,0.068699,10.857467,0.000000,0.000000
29,ALL,BPR,50,0.062059,0.018307,0.007992,0.510430,13.413607,0.000000,0.000000
30,ALL,ItemKNN,50,0.047222,0.011762,0.003876,0.716077,14.537719,0.000000,0.000000
31,ALL,LightFM(Hybrid),50,0.042181,0.012200,0.005204,0.838582,12.761764,0.000941,0.255252
32,ALL,Popularity,50,0.035849,0.010770,0.004849,0.003510,9.938428,0.000000,0.000000
33,ALL,Hybrid(Fusion),50,0.035188,0.010195,0.004399,0.878347,13.014888,0.001417,0.482143
34,ALL,CB(TFIDF),50,0.014207,0.004204,0.001882,0.896149,13.756838,0.002741,0.723739
35,ALL,Random,50,0.001859,0.000488,0.000172,1.000000,15.542773,0.047709,1.000000
36,ALL,ALS,100,0.158896,0.040543,0.015170,0.515294,12.447638,0.000000,0.000000
37,ALL,LightFM(CF),100,0.124748,0.031495,0.011631,0.108866,11.178912,0.000000,0.000000
38,ALL,BPR,100,0.098822,0.024244,0.008507,0.598786,13.594808,0.000000,0.000000
39,ALL,LightFM(Hybrid),100,0.067761,0.016327,0.005561,0.893240,12.922174,0.001212,0.382353
40,ALL,ItemKNN,100,0.064768,0.014639,0.004139,0.716127,14.379587,0.000000,0.000000
41,ALL,Hybrid(Fusion),100,0.057365,0.013770,0.004708,0.931551,13.102346,0.001649,0.658613
42,ALL,Popularity,100,0.056137,0.014045,0.005133,0.006770,10.272141,0.000000,0.000000
43,ALL,CB(TFIDF),100,0.014207,0.004204,0.001882,0.896149,13.756838,0.002741,0.723739
44,ALL,Random,100,0.004095,0.000847,0.000203,1.000000,15.543704,0.047718,1.000000
45,COLD,Popularity,5,0.000000,0.000000,0.000000,0.000351,9.107894,0.000000,0.000000
46,COLD,Random,5,0.000000,0.000000,0.000000,0.248471,15.515859,0.046573,0.238445
47,COLD,ItemKNN,5,0.000000,0.000000,0.000000,0.172851,15.141962,0.000000,0.000000
48,COLD,BPR,5,0.000000,0.000000,0.000000,0.106659,13.227051,0.000000,0.000000
49,COLD,ALS,5,0.000000,0.000000,0.000000,0.079631,11.724836,0.000000,0.000000
50,COLD,LightFM(CF),5,0.000000,0.000000,0.000000,0.008926,10.164493,0.000000,0.000000
51,COLD,CB(TFIDF),5,0.000000,0.000000,0.000000,0.129425,13.920625,0.003163,0.017857
52,COLD,LightFM(Hybrid),5,0.000000,0.000000,0.000000,0.147628,12.670480,0.000527,0.002101
53,COLD,Hybrid(Fusion),5,0.000000,0.000000,0.000000,0.165129,13.176638,0.001054,0.005252
54,COLD,CB(TFIDF),10,0.000879,0.000313,0.000146,0.206850,13.945934,0.003954,0.046218
55,COLD,Popularity,10,0.000000,0.000000,0.000000,0.000752,9.294555,0.000000,0.000000
56,COLD,Random,10,0.000000,0.000000,0.000000,0.431200,15.540289,0.046749,0.411765
57,COLD,ItemKNN,10,0.000000,0.000000,0.000000,0.281216,15.114948,0.000000,0.000000
58,COLD,BPR,10,0.000000,0.000000,0.000000,0.164076,13.329533,0.000000,0.000000
59,COLD,ALS,10,0.000000,0.000000,0.000000,0.119095,11.891947,0.000000,0.000000
60,COLD,LightFM(CF),10,0.000000,0.000000,0.000000,0.014241,10.395734,0.000000,0.000000
61,COLD,LightFM(Hybrid),10,0.000000,0.000000,0.000000,0.241149,12.789497,0.000615,0.006303
62,COLD,Hybrid(Fusion),10,0.000000,0.000000,0.000000,0.254538,13.220358,0.001406,0.013655
63,COLD,CB(TFIDF),20,0.002636,0.000751,0.000264,0.308595,13.974488,0.003998,0.088235
64,COLD,Popularity,20,0.000000,0.000000,0.000000,0.001404,9.522530,0.000000,0.000000
65,COLD,Random,20,0.000000,0.000000,0.000000,0.677415,15.544480,0.046705,0.652311
66,COLD,ItemKNN,20,0.000000,0.000000,0.000000,0.418363,15.008799,0.000000,0.000000
67,COLD,BPR,20,0.000000,0.000000,0.000000,0.237840,13.449409,0.000000,0.000000
68,COLD,ALS,20,0.000000,0.000000,0.000000,0.173152,12.074574,0.000000,0.000000
69,COLD,LightFM(CF),20,0.000000,0.000000,0.000000,0.023669,10.633771,0.000000,0.000000
70,COLD,LightFM(Hybrid),20,0.000000,0.000000,0.000000,0.366362,12.923469,0.000747,0.016807
71,COLD,Hybrid(Fusion),20,0.000000,0.000000,0.000000,0.369923,13.284111,0.001845,0.036765
72,COLD,CB(TFIDF),50,0.005272,0.001301,0.000363,0.478688,14.013143,0.004956,0.209034
73,COLD,Hybrid(Fusion),50,0.003515,0.000684,0.000104,0.548440,13.368571,0.002496,0.119748
74,COLD,Random,50,0.002636,0.000537,0.000092,0.940477,15.549293,0.047522,0.944328
75,COLD,LightFM(Hybrid),50,0.000879,0.000156,0.000018,0.566192,13.109987,0.001107,0.049370
76,COLD,Popularity,50,0.000000,0.000000,0.000000,0.003159,9.936346,0.000000,0.000000
77,COLD,ItemKNN,50,0.000000,0.000000,0.000000,0.573313,14.705560,0.000000,0.000000
78,COLD,BPR,50,0.000000,0.000000,0.000000,0.360044,13.636981,0.000000,0.000000
79,COLD,ALS,50,0.000000,0.000000,0.000000,0.273042,12.364829,0.000000,0.000000
80,COLD,LightFM(CF),50,0.000000,0.000000,0.000000,0.045883,10.987483,0.000000,0.000000
81,COLD,Hybrid(Fusion),100,0.006151,0.001119,0.000145,0.683984,13.443913,0.002847,0.213235
82,COLD,CB(TFIDF),100,0.005272,0.001301,0.000363,0.478688,14.013143,0.004956,0.209034
83,COLD,Random,100,0.004394,0.000817,0.000115,0.996339,15.551627,0.047909,0.995798
84,COLD,LightFM(Hybrid),100,0.003515,0.000576,0.000053,0.704894,13.254026,0.001670,0.111345
85,COLD,Popularity,100,0.000000,0.000000,0.000000,0.006118,10.270121,0.000000,0.000000
86,COLD,ItemKNN,100,0.000000,0.000000,0.000000,0.620700,14.570750,0.000000,0.000000
87,COLD,BPR,100,0.000000,0.000000,0.000000,0.466854,13.801733,0.000000,0.000000
88,COLD,ALS,100,0.000000,0.000000,0.000000,0.382359,12.601169,0.000000,0.000000
89,COLD,LightFM(CF),100,0.000000,0.000000,0.000000,0.076973,11.298235,0.000000,0.000000
90,WARM,ALS,5,0.025027,0.015296,0.012138,0.160465,11.485539,0.000000,0.000000
91,WARM,LightFM(CF),5,0.019146,0.011669,0.009249,0.014693,9.966822,0.000000,0.000000
92,WARM,BPR,5,0.013710,0.008300,0.006547,0.252733,12.908101,0.000000,0.000000
93,WARM,LightFM(Hybrid),5,0.008072,0.005076,0.004100,0.492980,12.196041,0.000316,0.023109
94,WARM,Popularity,5,0.007666,0.004852,0.003945,0.000552,9.109328,0.000000,0.000000
95,WARM,Hybrid(Fusion),5,0.006936,0.004390,0.003565,0.525775,12.674838,0.000641,0.050420
96,WARM,ItemKNN,5,0.004584,0.002936,0.002394,0.550145,14.981350,0.000000,0.000000
97,WARM,CB(TFIDF),5,0.002677,0.001769,0.001474,0.485458,13.559139,0.001444,0.122899
98,WARM,Random,5,0.000122,0.000081,0.000068,0.998295,15.530098,0.047678,0.997899
99,WARM,ALS,10,0.044254,0.021439,0.014629,0.209608,11.665341,0.000000,0.000000
100,WARM,LightFM(CF),10,0.034032,0.016457,0.011211,0.022214,10.189284,0.000000,0.000000
101,WARM,BPR,10,0.024176,0.011654,0.007914,0.316367,13.019426,0.000000,0.000000
102,WARM,LightFM(Hybrid),10,0.015657,0.007522,0.005106,0.614632,12.327831,0.000458,0.053571
103,WARM,Popularity,10,0.014806,0.007188,0.004925,0.000903,9.296397,0.000000,0.000000
104,WARM,Hybrid(Fusion),10,0.012372,0.006114,0.004257,0.635393,12.740710,0.000848,0.121849
105,WARM,ItemKNN,10,0.009897,0.004632,0.003081,0.639655,14.974108,0.000000,0.000000
106,WARM,CB(TFIDF),10,0.005152,0.002570,0.001804,0.610821,13.599806,0.001764,0.250000
107,WARM,Random,10,0.000446,0.000189,0.000114,1.000000,15.540660,0.047824,1.000000
108,WARM,ALS,20,0.073622,0.028801,0.016618,0.272891,11.866514,0.000000,0.000000
109,WARM,LightFM(CF),20,0.056058,0.021978,0.012701,0.036406,10.443302,0.000000,0.000000
110,WARM,BPR,20,0.041820,0.016103,0.009129,0.385819,13.152637,0.000000,0.000000
111,WARM,LightFM(Hybrid),20,0.026285,0.010185,0.005825,0.714472,12.468364,0.000572,0.103992
112,WARM,Popularity,20,0.024459,0.009609,0.005580,0.001655,9.525673,0.000000,0.000000
113,WARM,Hybrid(Fusion),20,0.021539,0.008411,0.004877,0.735583,12.815546,0.000980,0.210084
114,WARM,ItemKNN,20,0.020849,0.007334,0.003789,0.682279,14.858591,0.000000,0.000000
115,WARM,CB(TFIDF),20,0.008315,0.003372,0.002025,0.728112,13.641228,0.001917,0.390756
116,WARM,Random,20,0.000771,0.000271,0.000136,1.000000,15.542221,0.047874,1.000000
117,WARM,ALS,50,0.137062,0.041297,0.018587,0.382058,12.160705,0.000000,0.000000
118,WARM,LightFM(CF),50,0.104693,0.031536,0.014198,0.066493,10.817594,0.000000,0.000000
119,WARM,BPR,50,0.079909,0.023572,0.010291,0.498746,13.361944,0.000000,0.000000
120,WARM,ItemKNN,50,0.060804,0.015145,0.004991,0.715826,14.493842,0.000000,0.000000
121,WARM,LightFM(Hybrid),50,0.053787,0.015587,0.006669,0.821181,12.675506,0.000819,0.221639
122,WARM,Popularity,50,0.046161,0.013868,0.006244,0.003510,9.938966,0.000000,0.000000
123,WARM,Hybrid(Fusion),50,0.044376,0.012887,0.005573,0.847307,12.926564,0.001149,0.398109
124,WARM,CB(TFIDF),50,0.017199,0.005110,0.002295,0.853826,13.695052,0.002190,0.616597
125,WARM,Random,50,0.001947,0.000502,0.000172,1.000000,15.543011,0.047683,1.000000
126,WARM,ALS,100,0.204600,0.052204,0.019533,0.499950,12.406252,0.000000,0.000000
127,WARM,LightFM(CF),100,0.160630,0.040554,0.014976,0.105707,11.142908,0.000000,0.000000
128,WARM,BPR,100,0.127246,0.031217,0.010954,0.588858,13.547518,0.000000,0.000000
129,WARM,LightFM(Hybrid),100,0.086034,0.020790,0.007119,0.881657,12.840801,0.001036,0.352941
130,WARM,ItemKNN,100,0.083398,0.018850,0.005329,0.716127,14.329206,0.000000,0.000000
131,WARM,Popularity,100,0.072283,0.018084,0.006610,0.006770,10.272657,0.000000,0.000000
132,WARM,Hybrid(Fusion),100,0.072162,0.017365,0.005959,0.909638,13.018719,0.001335,0.561975
133,WARM,CB(TFIDF),100,0.017199,0.005110,0.002295,0.853826,13.695052,0.002190,0.616597
134,WARM,Random,100,0.004827,0.000965,0.000212,1.000000,15.543024,0.047730,1.000000

In [ ]:
#

# 2 stage rank

In [ ]:
import numpy as np
import pandas as pd

SEED = 42
rng = np.random.default_rng(SEED)

# Candidate sizes
M_ALS = 500
M_CB  = 1200

# Neg sampling per query (for ranker training)
N_NEG = 50

# Сколько warm-queries брать для обучения ранкера (cold берём все)
N_WARM_QUERIES = 15000

# Размер SVD-эмбеддинга item-фич (CB item features -> dense dims for CatBoost)
SVD_DIM = 32

# Какая метрика на VAL является целевой при подборе (обычно COLD Recall@50/100)
TARGET_K = 50
TARGET_SPLIT = "COLD"  # "COLD" / "ALL" / "WARM"

# Сколько запросов использовать для быстрой оценки в тюнинге (ускорение)
EVAL_SAMPLE_N = 20000  # None = полный прогон (медленно)

In [ ]:
from implicit.als import AlternatingLeastSquares

def fit_als_model(pack, factors, regularization, iterations, alpha, seed=42):
    R = pack["R"].tocsr().astype(np.float32)
    R_conf = (R * float(alpha)).tocsr()

    als = AlternatingLeastSquares(
        factors=int(factors),
        regularization=float(regularization),
        iterations=int(iterations),
        random_state=int(seed),
    )
    als.fit(R_conf)
    return als, R

def als_topM(als, R, u, M):
    items, scores = als.recommend(
        userid=int(u),
        user_items=R[int(u)],
        N=int(M),
        filter_already_liked_items=True,
        recalculate_user=False,
    )
    return np.asarray(items, dtype=np.int32), np.asarray(scores, dtype=np.float64)

def als_score_items(als, u, items):
    uf = als.user_factors[int(u)]      # (f,)
    itf = als.item_factors[items]      # (n,f)
    return (itf @ uf).astype(np.float64)

# VAL / TEST ALS
f, reg, it, a = best_als_params
als_val,  R_val  = fit_als_model(val_pack,  f, reg, it, a, seed=SEED)
als_test, R_test = fit_als_model(test_pack, f, reg, it, a, seed=SEED)

  0%|          | 0/40 [00:00<?, ?it/s]

  0%|          | 0/40 [00:00<?, ?it/s]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from scipy import sparse

def _l2_normalize_rows(X):
    norms = np.sqrt(X.multiply(X).sum(axis=1)).A1
    norms[norms == 0] = 1.0
    inv = 1.0 / norms
    return sparse.diags(inv).dot(X)

def build_cb_and_svd(pack, item_docs, vec_params, svd_dim=32, seed=42):
    vec = TfidfVectorizer(**vec_params)
    X_items = vec.fit_transform(item_docs).tocsr()
    X_items = _l2_normalize_rows(X_items)

    # user профили как в CB: U = R * X_items
    R = pack["R"].tocsr().astype(np.float32)
    U = (R @ X_items).tocsr()
    U = _l2_normalize_rows(U)

    # SVD по item-матрице (dense item embeddings)
    svd = TruncatedSVD(n_components=int(svd_dim), random_state=int(seed))
    item_emb = svd.fit_transform(X_items).astype(np.float32)  # (n_items, d)


    user_emb = svd.transform(U).astype(np.float32)           # (n_users, d)

    return vec, X_items, U, svd, item_emb, user_emb

def cb_score_items(U, X_items, u, items):
    v = U[int(u)]
    Xsub = X_items[items]
    return (v @ Xsub.T).toarray().ravel().astype(np.float64)

def cb_topM(U, X_items, u, M):
    v = U[int(u)]
    scores = (v @ X_items.T).toarray().ravel()
    if M >= scores.size:
        idx = np.argsort(-scores)
    else:
        idx_part = np.argpartition(-scores, M)[:M]
        idx = idx_part[np.argsort(-scores[idx_part])]
    return idx.astype(np.int32), scores[idx].astype(np.float64)


vec_params = dict(best_cb_vec_params)
vec_params["min_df"] = 2  # или 1

# VAL artifacts
vec_val, X_items_val, U_val, svd_val, item_emb_val, user_emb_val = build_cb_and_svd(
    val_pack, item_docs_val, vec_params, svd_dim=SVD_DIM, seed=SEED
)

# TEST artifacts
vec_test, X_items_test, U_test, svd_test, item_emb_test, user_emb_test = build_cb_and_svd(
    test_pack, item_docs_test, vec_params, svd_dim=SVD_DIM, seed=SEED
)

In [ ]:
from catboost import CatBoostRanker, Pool

def build_ranker_dataset(
    pack, als, R, X_items, U,
    item_emb, user_emb,
    M_als=500, M_cb=1200, n_neg=50,
    n_warm_queries=15000,
    seed=42
):
    ef = pack["eval_f"].reset_index(drop=True)
    rng = np.random.default_rng(seed)

    cold_idx = ef.index[ef["is_cold_item"] == 1].to_numpy()
    warm_idx = ef.index[ef["is_cold_item"] == 0].to_numpy()
    if warm_idx.size > n_warm_queries:
        warm_idx = rng.choice(warm_idx, size=int(n_warm_queries), replace=False)

    use_idx = np.concatenate([cold_idx, warm_idx])
    rng.shuffle(use_idx)

    is_cold_by_i = pack["is_cold_by_i"].astype(bool)
    pop = np.asarray(pack["R"].sum(axis=0)).ravel().astype(np.float64)
    log_pop = np.log1p(pop).astype(np.float32)

    X_rows, y_rows, gid_rows, w_rows = [], [], [], []

    for q, j in enumerate(use_idx):
        u = int(ef.loc[j, "u"])
        true_i = int(ef.loc[j, "i"])
        is_cold_query = int(ef.loc[j, "is_cold_item"]) == 1

        a_items, _ = als_topM(als, R, u, M_als)
        c_items, _ = cb_topM(U, X_items, u, M_cb)

        cand = np.unique(np.concatenate([a_items, c_items, np.array([true_i], dtype=np.int32)]))

        a_rank = {int(i): r for r, i in enumerate(a_items.tolist())}
        c_rank = {int(i): r for r, i in enumerate(c_items.tolist())}

        neg_pool = cand[cand != true_i]
        if neg_pool.size == 0:
            continue
        if neg_pool.size > n_neg:
            neg = rng.choice(neg_pool, size=int(n_neg), replace=False)
        else:
            neg = neg_pool

        items = np.concatenate([np.array([true_i], dtype=np.int32), neg])

        # Base scores
        als_s = als_score_items(als, u, items).astype(np.float32)
        cb_s  = cb_score_items(U, X_items, u, items).astype(np.float32)

        # Ranks
        als_r = np.array([a_rank.get(int(i), 10**6) for i in items], dtype=np.float32)
        cb_r  = np.array([c_rank.get(int(i), 10**6) for i in items], dtype=np.float32)

        # Item stats
        cold_item = is_cold_by_i[items].astype(np.float32)
        lp = log_pop[items].astype(np.float32)

        # CB item features (dense SVD embedding)
        it_emb = item_emb[items]                 # (n, d)
        u_emb  = np.repeat(user_emb[u][None, :], repeats=items.size, axis=0)  # (n, d)


        feats = np.concatenate(
            [
                als_s[:, None],
                cb_s[:, None],
                als_r[:, None],
                cb_r[:, None],
                cold_item[:, None],
                lp[:, None],
                it_emb,
                u_emb,
            ],
            axis=1
        ).astype(np.float32)

        labels = np.zeros(items.size, dtype=np.float32)
        labels[0] = 1.0

        X_rows.append(feats)
        y_rows.append(labels)
        gid_rows.append(np.full(items.size, q, dtype=np.int32))


        w = 3.0 if is_cold_query else 1.0
        w_rows.append(np.full(items.size, w, dtype=np.float32))

    X = np.vstack(X_rows)
    y = np.concatenate(y_rows)
    gid = np.concatenate(gid_rows)
    w = np.concatenate(w_rows)
    return X, y, gid, w

X_all, y_all, gid_all, w_all = build_ranker_dataset(
    val_pack, als_val, R_val, X_items_val, U_val,
    item_emb_val, user_emb_val,
    M_als=M_ALS, M_cb=M_CB, n_neg=N_NEG,
    n_warm_queries=N_WARM_QUERIES,
    seed=SEED
)


n_groups = int(gid_all.max() + 1)
perm = rng.permutation(n_groups)
cut = int(0.8 * n_groups)
train_groups = set(perm[:cut].tolist())

train_mask = np.array([g in train_groups for g in gid_all], dtype=bool)

X_tr, y_tr, gid_tr, w_tr = X_all[train_mask], y_all[train_mask], gid_all[train_mask], w_all[train_mask]
X_va, y_va, gid_va, w_va = X_all[~train_mask], y_all[~train_mask], gid_all[~train_mask], w_all[~train_mask]

train_pool = Pool(X_tr, y_tr, group_id=gid_tr, weight=w_tr)
valid_pool = Pool(X_va, y_va, group_id=gid_va, weight=w_va)

print("Ranker train pairs:", X_tr.shape, "valid pairs:", X_va.shape)

Ranker train pairs: (660399, 70) valid pairs: (165138, 70)

In [ ]:
def make_catboost_rerank_recommender(
    pack, als, R, X_items, U,
    item_emb, user_emb,
    ranker,
    M_als=500, M_cb=1200
):
    is_cold_by_i = pack["is_cold_by_i"].astype(bool)
    pop = np.asarray(pack["R"].sum(axis=0)).ravel().astype(np.float64)
    log_pop = np.log1p(pop).astype(np.float32)

    def rec(u, K):
        a_items, _ = als_topM(als, R, u, M_als)
        c_items, _ = cb_topM(U, X_items, u, M_cb)
        cand = np.unique(np.concatenate([a_items, c_items]))
        if cand.size == 0:
            return np.array([], dtype=np.int32), np.array([], dtype=np.float64)

        a_rank = {int(i): r for r, i in enumerate(a_items.tolist())}
        c_rank = {int(i): r for r, i in enumerate(c_items.tolist())}

        als_s = als_score_items(als, u, cand).astype(np.float32)
        cb_s  = cb_score_items(U, X_items, u, cand).astype(np.float32)

        als_r = np.array([a_rank.get(int(i), 10**6) for i in cand], dtype=np.float32)
        cb_r  = np.array([c_rank.get(int(i), 10**6) for i in cand], dtype=np.float32)

        cold_item = is_cold_by_i[cand].astype(np.float32)
        lp = log_pop[cand].astype(np.float32)

        it_emb = item_emb[cand]
        u_emb  = np.repeat(user_emb[int(u)][None, :], repeats=cand.size, axis=0)

        feats = np.concatenate(
            [
                als_s[:, None],
                cb_s[:, None],
                als_r[:, None],
                cb_r[:, None],
                cold_item[:, None],
                lp[:, None],
                it_emb,
                u_emb,
            ],
            axis=1
        ).astype(np.float32)

        scores = ranker.predict(feats).astype(np.float64)
        order = np.argsort(-scores)
        top = cand[order[:K]]
        return top.astype(np.int32), scores[order[:K]]

    return rec

def score_on_val(pack, rec_fn, split, target_k, ks, sample_n=None):
    masks = _get_masks(pack)
    mask = masks[split]
    out, aux = evaluate_with_aux(pack, rec_fn, mask, ks=ks, sample_n=sample_n, seed=SEED)
    r = out[target_k][0]
    return float(r), out, aux

# небольшой grid (расширяйте при необходимости)
grid = []
for depth in [6, 8]:
    for lr in [0.05, 0.08]:
        for l2 in [3.0, 8.0]:
            for iters in [1200]:
                grid.append({"depth": depth, "learning_rate": lr, "l2_leaf_reg": l2, "iterations": iters})

results = []
best = {"score": -1, "params": None, "model": None, "best_iteration": None}

for params in grid:
    ranker = CatBoostRanker(
        loss_function="YetiRank",
        iterations=int(params["iterations"]),
        depth=int(params["depth"]),
        learning_rate=float(params["learning_rate"]),
        l2_leaf_reg=float(params["l2_leaf_reg"]),
        random_seed=SEED,
        verbose=False,
        # ранняя остановка по валид-пулу
        od_type="Iter",
        od_wait=80
    )
    ranker.fit(train_pool, eval_set=valid_pool, use_best_model=True)

    rec_val = make_catboost_rerank_recommender(
        val_pack, als_val, R_val, X_items_val, U_val,
        item_emb_val, user_emb_val,
        ranker, M_als=M_ALS, M_cb=M_CB
    )

    score, _, _ = score_on_val(val_pack, rec_val, TARGET_SPLIT, TARGET_K, ks=KS, sample_n=EVAL_SAMPLE_N)

    row = dict(params)
    row["target_split"] = TARGET_SPLIT
    row["target_k"] = TARGET_K
    row["Recall_target"] = score
    row["best_iteration"] = int(ranker.get_best_iteration() or params["iterations"])
    results.append(row)

    if score > best["score"]:
        best["score"] = score
        best["params"] = params
        best["model"] = ranker
        best["best_iteration"] = row["best_iteration"]

pd.DataFrame(results).sort_values("Recall_target", ascending=False).reset_index(drop=True).head(10), best

Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.
Pairwise losses don't support object weights.

(   depth  learning_rate  l2_leaf_reg  iterations target_split  target_k  \
 0      6           0.05          3.0        1200         COLD        50
 1      6           0.05          8.0        1200         COLD        50
 2      6           0.08          3.0        1200         COLD        50
 3      6           0.08          8.0        1200         COLD        50
 4      8           0.05          3.0        1200         COLD        50
 5      8           0.05          8.0        1200         COLD        50
 6      8           0.08          3.0        1200         COLD        50
 7      8           0.08          8.0        1200         COLD        50

    Recall_target  best_iteration
 0            0.0             742
 1            0.0             663
 2            0.0             489
 3            0.0             645
 4            0.0             613
 5            0.0             555
 6            0.0             505
 7            0.0             645  ,
 {'score': 0.0,
  'params': {'depth': 6,
   'learning_rate': 0.05,
   'l2_leaf_reg': 3.0,
   'iterations': 1200},
  'model': <catboost.core.CatBoostRanker at 0x7c56de1d81a0>,
  'best_iteration': 742})

In [ ]:
best_params = best["params"]
best_iters  = int(best["best_iteration"])

full_pool = Pool(X_all, y_all, group_id=gid_all, weight=w_all)

ranker_final = CatBoostRanker(
    loss_function="YetiRank",
    iterations=best_iters,
    depth=int(best_params["depth"]),
    learning_rate=float(best_params["learning_rate"]),
    l2_leaf_reg=float(best_params["l2_leaf_reg"]),
    random_seed=SEED,
    verbose=200
)
ranker_final.fit(full_pool)

rec_val_final = make_catboost_rerank_recommender(
    val_pack, als_val, R_val, X_items_val, U_val,
    item_emb_val, user_emb_val,
    ranker_final, M_als=M_ALS, M_cb=M_CB
)

# Единый протокол метрик (ALL/WARM/COLD) на VAL
masks_val = _get_masks(val_pack)
rows = []
for split, mask in masks_val.items():
    out, aux = evaluate_with_aux(val_pack, rec_val_final, mask, ks=KS, sample_n=None, seed=SEED)
    for k, (r, n, m) in out.items():
        rows.append({
            "split": split, "model": "ALS+CB+CatBoost", "K": int(k),
            "Recall": float(r), "NDCG": float(n), "MAP": float(m),
            "Coverage": float(aux["Coverage"][k]),
            "Novelty": float(aux["Novelty"][k]),
            "ColdShare": float(aux["ColdShare"][k]),
            "ColdCoverage": float(aux["ColdCoverage"][k]),
        })

pd.DataFrame(rows).sort_values(["split","K"]).reset_index(drop=True)

Pairwise losses don't support object weights.

0:	total: 2.65s	remaining: 32m 47s
200:	total: 5m 18s	remaining: 14m 17s
400:	total: 10m 26s	remaining: 8m 52s
600:	total: 15m 31s	remaining: 3m 38s
741:	total: 19m 3s	remaining: 0us

,split,model,K,Recall,NDCG,MAP,Coverage,Novelty,ColdShare,ColdCoverage
0,ALL,ALS+CB+CatBoost,5,0.034029,0.022109,0.018210,0.603570,12.141833,0.000000,0.000000
1,ALL,ALS+CB+CatBoost,10,0.054263,0.028629,0.020887,0.638849,12.013959,0.000000,0.000000
2,ALL,ALS+CB+CatBoost,20,0.084567,0.036274,0.022976,0.660432,12.016079,0.000000,0.000000
3,ALL,ALS+CB+CatBoost,50,0.144765,0.048176,0.024870,0.680362,12.174454,0.000004,0.005550
4,ALL,ALS+CB+CatBoost,100,0.205373,0.057990,0.025729,0.725233,12.361688,0.000058,0.126735
5,COLD,ALS+CB+CatBoost,5,0.000000,0.000000,0.000000,0.152518,12.442360,0.000000,0.000000
6,COLD,ALS+CB+CatBoost,10,0.000000,0.000000,0.000000,0.210338,12.304353,0.000000,0.000000
7,COLD,ALS+CB+CatBoost,20,0.000000,0.000000,0.000000,0.269864,12.286590,0.000000,0.000000
8,COLD,ALS+CB+CatBoost,50,0.000000,0.000000,0.000000,0.371383,12.414376,0.000000,0.000000
9,COLD,ALS+CB+CatBoost,100,0.000000,0.000000,0.000000,0.475673,12.580316,0.000084,0.009251
10,WARM,ALS+CB+CatBoost,5,0.042957,0.027910,0.022987,0.564135,12.066985,0.000000,0.000000
11,WARM,ALS+CB+CatBoost,10,0.068500,0.036141,0.026367,0.602611,11.945804,0.000000,0.000000
12,WARM,ALS+CB+CatBoost,20,0.106754,0.045791,0.029004,0.630003,11.953067,0.000000,0.000000
13,WARM,ALS+CB+CatBoost,50,0.182746,0.060816,0.031394,0.659845,12.118250,0.000004,0.004625
14,WARM,ALS+CB+CatBoost,100,0.259175,0.073192,0.032478,0.705569,12.310397,0.000050,0.098057

In [ ]:
rec_test_final = make_catboost_rerank_recommender(
    test_pack, als_test, R_test, X_items_test, U_test,
    item_emb_test, user_emb_test,
    ranker_final, M_als=M_ALS, M_cb=M_CB
)

masks_test = _get_masks(test_pack)
rows = []
for split, mask in masks_test.items():
    out, aux = evaluate_with_aux(test_pack, rec_test_final, mask, ks=KS, sample_n=None, seed=SEED)
    for k, (r, n, m) in out.items():
        rows.append({
            "split": split, "model": "ALS+CB+CatBoost", "K": int(k),
            "Recall": float(r), "NDCG": float(n), "MAP": float(m),
            "Coverage": float(aux["Coverage"][k]),
            "Novelty": float(aux["Novelty"][k]),
            "ColdShare": float(aux["ColdShare"][k]),
            "ColdCoverage": float(aux["ColdCoverage"][k]),
        })

pd.DataFrame(rows).sort_values(["split","K"]).reset_index(drop=True)

In [ ]:
1==1

True

In [ ]:
pd.set_option('display.max_rows', 200)
pd.DataFrame(rows).sort_values(["split","K"]).reset_index(drop=True)

,split,model,K,Recall,NDCG,MAP,Coverage,Novelty,ColdShare,ColdCoverage
0,ALL,ALS+CB+CatBoost,5,0.027816,0.017642,0.014319,0.583041,12.231438,0.000000,0.000000
1,ALL,ALS+CB+CatBoost,10,0.045237,0.023248,0.016617,0.624912,12.091363,0.000000,0.000000
2,ALL,ALS+CB+CatBoost,20,0.071888,0.029921,0.018414,0.655150,12.070344,0.000000,0.000000
3,ALL,ALS+CB+CatBoost,50,0.129410,0.041266,0.020207,0.681075,12.203599,0.000000,0.000000
4,ALL,ALS+CB+CatBoost,100,0.188949,0.050896,0.021048,0.706499,12.380161,0.000008,0.026261
5,COLD,ALS+CB+CatBoost,5,0.000000,0.000000,0.000000,0.142212,12.515335,0.000000,0.000000
6,COLD,ALS+CB+CatBoost,10,0.000000,0.000000,0.000000,0.195116,12.334543,0.000000,0.000000
7,COLD,ALS+CB+CatBoost,20,0.000000,0.000000,0.000000,0.251529,12.288222,0.000000,0.000000
8,COLD,ALS+CB+CatBoost,50,0.000000,0.000000,0.000000,0.345652,12.395486,0.000000,0.000000
9,COLD,ALS+CB+CatBoost,100,0.000879,0.000134,0.000009,0.437318,12.559697,0.000026,0.003151
10,WARM,ALS+CB+CatBoost,5,0.035817,0.022717,0.018437,0.539765,12.160323,0.000000,0.000000
11,WARM,ALS+CB+CatBoost,10,0.058248,0.029935,0.021396,0.582590,12.028384,0.000000,0.000000
12,WARM,ALS+CB+CatBoost,20,0.092565,0.038527,0.023711,0.616337,12.012059,0.000000,0.000000
13,WARM,ALS+CB+CatBoost,50,0.166633,0.053136,0.026020,0.650988,12.150541,0.000000,0.000000
14,WARM,ALS+CB+CatBoost,100,0.243216,0.065523,0.027100,0.680574,12.331444,0.000007,0.016807

In [ ]:
1==1

True

Ниже — подробное пояснение того, что именно делают ячейки, которые я прислал, зачем каждая нужна, что на каких данных обучается, и какие сигналы (фичи) реально используются. Буду идти строго по порядку ячеек.

Общая идея: ALS + CB кандидаты → CatBoost ранжирует
Зачем вообще второй этап (CatBoost)

ALS/CF отлично ранжирует warm объекты (которые встречались в train), но не умеет cold.

CB (TF-IDF по категориям/атрибутам) умеет выдавать cold кандидатов, но ранжирует “следующий конкретный бизнес” слабее CF.

Мы делаем двухстадийную схему:

Candidate generation: берём небольшой список кандидатов от ALS и от CB и объединяем.

Reranking: учим CatBoost выбирать правильный следующий item среди кандидатов, используя сигналы ALS/CB + контентные item-фичи (как в CB).

Это позволяет:

не скорить весь каталог (30k items) для каждого пользователя,

и не терять cold items (они приходят через CB).

Что такое val_pack и test_pack в этой схеме

val_pack — ваш внутренний “validation pack”:

val_pack["R"] построена по истории (примерно до
𝑛
−
2
n−2),

val_pack["eval_f"] содержит цели (предсказать
𝑛
−
1
n−1).

На нём: подбираем гиперпараметры.

test_pack — финальный “test pack”:

test_pack["R"] построена по истории (примерно до
𝑛
−
1
n−1),

test_pack["eval_f"] содержит цели (предсказать
𝑛
n).

На нём: только финальная оценка.

Ячейка 0 — Конфиг
M_ALS = 500
M_CB  = 1200
N_NEG = 50
N_WARM_QUERIES = 15000
SVD_DIM = 32
TARGET_K = 50
TARGET_SPLIT = "COLD"
EVAL_SAMPLE_N = 20000

Что это означает

M_ALS — сколько кандидатов берём у ALS на 1-й стадии.

M_CB — сколько кандидатов берём у CB.

CB нужен для cold → обычно M_CB берут больше.

N_NEG — сколько негативов на один запрос для обучения ранкера.

Для каждого (u, true_item) берём 1 positive и 50 negatives.

N_WARM_QUERIES — сколько warm-запросов взять для обучения ранкера (cold берём все).

Потому что warm eval у вас очень большой, а cold маленький, и датасет для ранкера нельзя делать на всех 60k+ warm запросах, иначе будет долго.

SVD_DIM — размер плотного эмбеддинга item-фич (из TF-IDF) для CatBoost.

Это способ дать ранкеру контентную информацию без огромного количества sparse признаков.

TARGET_SPLIT / TARGET_K — на чём тюним гиперпараметры ранкера:

например, максимизируем COLD Recall@50 на VAL.

EVAL_SAMPLE_N — ускорение при тюнинге: оценивать не на всех eval, а на сэмпле (например 20k). Для финальных таблиц ставят None.

Ячейка 1 — ALS модель “объектом”

Здесь мы обучаем ALS как объект implicit, чтобы:

получать ALS_topM(u) — список кандидатов и их als-score,

получать als_score(u, item) для любого кандидата.

Функции:

fit_als_model(pack, ...) — учит ALS на pack["R"].

als_topM(als, R, u, M) — выдаёт top-M кандидатов.

als_score_items(als, u, items) — быстро считает score для конкретных items.

Почему это нужно

CatBoost на втором этапе должен иметь фичу “насколько ALS верит в item”, поэтому нам нужен именно score для произвольного item, а не только готовый топ-K.

Ячейка 2 — CB “как в CB” + SVD

Тут мы строим ровно то, что вы используете в контентной модели:

TfidfVectorizer обучается на item_docs

item_docs у вас уже сформированы так, что:

для cold items используются только категории/атрибуты (без review text),

для warm может быть больше (если у вас так сделано).

строится X_items — sparse TF-IDF матрица items (n_items × vocab)

строится U = R @ X_items — профили пользователей (n_users × vocab), как в CB

Затем добавляется:
4) TruncatedSVD над X_items → получаем item_emb (n_items × d)
5) user_emb = svd.transform(U) → получаем user_emb (n_users × d)

Почему нужен SVD

CatBoost не любит огромные sparse TF-IDF признаки (можно, но это тяжело и часто медленно).
SVD даёт компактную “семантическую” проекцию TF-IDF в 32 числа на item, которые:

сохраняют контентный сигнал,

дешёвые для ранкера,

одинаково доступны и для warm, и для cold.

Что значит “как в CB фичи items”

Это именно контент, который вы используете в CB:

категории/атрибуты/мета токены (и возможно текст там, где разрешено),

только мы даём его ранкеру не напрямую TF-IDF, а через item_emb.

Ячейка 3 — Построение обучающего датасета для CatBoost Ranker (на VAL)

Это ключевая ячейка.

Что такое “query” для ранкера

Один eval-случай (строка val_pack["eval_f"]) — это query:

пользователь u

правильный следующий item true_i

Как строится один query

Генерируем кандидатов:

a_items = ALS_topM(u, M_ALS)

c_items = CB_topM(u, M_CB)

cand = union(a_items, c_items) ∪ {true_i} (важно: гарантируем наличие positive)

Выбираем обучающие пары:

1 positive: true_i

N_NEG negatives: случайные items из cand \ {true_i}

Считаем фичи для каждого (u, item) из этой мини-выборки.

Какие фичи идут в CatBoost

На каждый кандидат item:

Скоринговые:

als_score(u,item) — от ALS факторизации

cb_score(u,item) — косинус/скалярное произведение профиля пользователя и item TF-IDF

Ранговые:

als_rank — позиция item в ALS_topM (если item не в ALS_topM → 1e6)

cb_rank — позиция item в CB_topM

Cold/популярность:

is_cold_item — бинарный флаг по pack["is_cold_by_i"]

log_pop — log1p(popularity_in_train) из R (часто помогает как калибровка)

Контентные (как в CB):

item_emb[item] — SVD эмбеддинг item

user_emb[u] — SVD эмбеддинг пользователя

Итого это компактный numeric feature vector.

Почему мы берём все cold queries + часть warm

Потому что:

cold queries мало (1552–1821), их важно учесть все,

warm queries очень много, их можно сэмплировать, чтобы не убить время/память,

ранкер при этом видит и warm, и cold режимы.

Почему split делается “по group_id”

Чтобы избежать утечки:

нельзя, чтобы один и тот же query (u, true_i) попал частично в train и valid.

поэтому делим данные по id запроса (group_id), а не по строкам.

Ячейка 4 — Тюнинг гиперпараметров CatBoost на VAL

Здесь мы делаем маленький grid по:

depth

learning_rate

l2_leaf_reg

Для каждого набора:

обучаем CatBoostRanker на train_pool, early stopping на valid_pool

строим recommend_fn, который:

берёт кандидатов union(ALS_topM, CB_topM)

считает фичи для всех кандидатов

делает ranker.predict(feats) и выбирает top-K

оцениваем через ваш же evaluate_with_aux:

берём маску COLD (или что вы выбрали)

считаем Recall@TARGET_K (например 50)

выбираем лучший набор параметров.

Почему есть EVAL_SAMPLE_N: чтобы тюнинг не шёл часами.

Ячейка 5 — Финальная модель ранкера на VAL (полная оценка)

После выбора гиперпараметров:

переобучаем ранкер на всём X_all (train+valid) — это стандартная практика

оцениваем по единому протоколу метрик:

ALL / WARM / COLD

Recall/NDCG/MAP + ваши Coverage/Novelty/ColdShare/ColdCoverage

Эта таблица — ваш результат “на VAL”.

Ячейка 6 — Финальная оценка на TEST (единый протокол)

Здесь:

ALS, CB, SVD для TEST уже построены на test_pack

ranker не переобучаем (иначе будет утечка)

делаем rerank кандидатов и считаем метрики на test_pack["eval_f"] так же, как раньше

Что именно “обучается”, а что “подбирается”
Обучается (fit)

ALS на pack["R"] (отдельно для val_pack и test_pack)

TF-IDF + SVD на item_docs_pack (отдельно для val_pack и test_pack)

CatBoostRanker только на VAL (на выборке query→candidates)

Подбирается (tuning)

гиперпараметры CatBoost (depth/lr/l2) — только по VAL метрике (например COLD Recall@50)

(опционально отдельно) min_df и SVD_DIM — тоже только по VAL

Тестируется

всё оценивается финально на TEST тем же протоколом метрик.

Что это даёт вам относительно вашего текущего результата

CF-модели: хороши на WARM, нули на COLD — как у вас.

CB: даёт non-zero на COLD, но слабый Recall.

CatBoost должен научиться:

где ALS-score релевантен (warm),

где надо опираться на CB/контент (cold),

калибровать всё через популярность и ранги,
и в идеале поднять COLD Recall без сильного провала WARM.

Если вы хотите, я могу адаптировать описание под ваш фактический набор столбцов/объектов в pack (например точные названия eval_f колонок, если у вас не u/i/is_cold_item), но логика останется той же.

Ниже — ответы по пунктам, с привязкой к тому, что было в присланных ячейках (ALS кандидаты + CB кандидаты → CatBoost rerank + единый eval).

1) Может ли генератор кандидатов не дать релевантный объект? Что если его нет среди кандидатов

Да, это ключевая проблема двухстадийных схем: если истинный следующий item
𝑖
\*
i
\*
 не попал в кандидаты, то второй этап (CatBoost) физически не может его “придумать”, потому что он ранжирует только предоставленный список.

Что происходит в обучении

В обучающем датасете я специально делал:

cand = union(ALS_topM, CB_topM) ∪ {true_i}

То есть в обучении мы насильно добавляем true_i в кандидаты, чтобы:

всегда был positive,

CatBoost мог учиться различать “true vs negatives”.

Что происходит на инференсе (VAL/TEST eval)

В инференсе мы обычно делаем просто:

cand = union(ALS_topM, CB_topM)
и не добавляем true_i (мы же его не знаем).

Если true_i не попал в union, то:

для этого запроса вклад в Recall@K будет 0 при любом ранкере,

итоговый Recall ограничен сверху candidate-recall:

𝑅
𝑒
𝑐
𝑎
𝑙
𝑙
@
𝐾
≤
𝑃
(
𝑖
\*
∈
𝐶
𝑎
𝑛
𝑑
(
𝑢
)
)
Recall@K≤P(i
\*
∈Cand(u))
Что с этим делать (практически)

Измерить candidate-recall на VAL: доля запросов, где true_i входит в union кандидатов.
Если он низкий на COLD — увеличивайте M_CB (обычно это основной рычаг).

Делайте асимметрию M: M_CB >> M_ALS, потому что cold в основном приходит через CB.

Если всё равно плохо, добавляют fallback:

“квота q cold из CB в top-K” (гарантирует ColdShare, но может портить WARM),

или отдельный “CB-only” режим для cold-queries (если вы умеете заранее определить cold-query, что у вас есть через метки).

2) Зачем тут SVD: объяснение на примере
Проблема без SVD

TF-IDF по категориям/атрибутам — это очень разреженный вектор:

размерность = размер словаря (тысячи/десятки тысяч токенов),

подавать это напрямую в CatBoost как признаки — возможно, но:

тяжело по памяти/скорости,

высокий риск переобучения,

плохо переносится на слабые/редкие токены.

Что даёт SVD

SVD (TruncatedSVD) делает низкоразмерные плотные эмбеддинги:

item_emb[i] ∈ R^d, где d=32 (например),

эти 32 числа — “темы/латентные факторы контента”.

CatBoost получает вместо огромного sparse TF-IDF:

компактные числовые признаки, которые легче учить.

Мини-пример (интуитивно)

Представьте токены:

item A: cat_sushi, cat_japanese, attr_price=medium

item B: cat_sushi, cat_japanese, attr_price=cheap

item C: cat_auto, cat_repair, attr_parking=true

TF-IDF будет иметь разные координаты по каждому токену.
SVD “сожмёт” эти координаты так, что:

A и B окажутся близко в embedding-пространстве (похожая “тема”: японская еда),

C будет далеко (другая тема: авто-сервис).

Для cold items это важно: даже если токены редкие/шумные, SVD часто позволяет извлечь общий смысл (“кластер”) и облегчает ранкеру работу.

3) Всё ли будет работать, и почему может быть долго (без зацикливания)
Зацикливания (бесконечных циклов) в присланном коде нет

Всё там — конечные циклы:

по запросам (eval rows / subset),

по кандидатам (≤ M_ALS + M_CB),

по grid гиперпараметров.

То есть “залипнуть” в бесконечность не должно.

Главный риск — время, не “циклы”

Самое дорогое место в присланном варианте — функция cb_topM, если она реализована как:

для каждого пользователя считать scores = U[u] @ X_items.T по всем 30k items.

Это операция порядка
𝑂
(
𝑛
_
𝑖
𝑡
𝑒
𝑚
𝑠
)
O(n_items) на один запрос.
Если вы прогоняете:

тюнинг ранкера + оценку на 20k eval запросов,

и внутри каждого запроса ещё делаете cb_topM,
то это может стать часами.

Как сделать, чтобы работало быстрее и предсказуемо

Рекомендации (в порядке эффективности):

В тюнинге ставьте EVAL_SAMPLE_N = 5000–10000, а не 20000.

Снизить объём обучающего датасета ранкера:

N_WARM_QUERIES = 5000–10000

N_NEG = 20–30 (часто достаточно)

Снизить кандидаты:

M_ALS=300–500

M_CB=600–1000 (а потом поднять только если candidate-recall низкий)

В идеале: не вычислять cb_topM через полный перебор items при каждом вызове.
Если у вас в ноутбуке уже есть быстрый cb_rec(u, M) (который вы использовали в eval), лучше использовать его для кандидатов, а cb_score_items(...) — только для скоринга этих кандидатов.

Мини-проверки “что всё корректно” (логические)

Перед долгими прогонами стоит проверить:

совпадает ли нумерация items: кандидаты от ALS и от CB должны быть в одном item-space 0..n_items-1 для данного pack.

item_docs_val длиной ровно val_pack["n_items"] (аналогично test).

pack["eval_f"] содержит колонки u, i, is_cold_item, is_warm_item_eligible (у вас они есть).

pack["is_cold_by_i"] есть и длиной n_items.

Если всё это соответствует вашему пайплайну — логически код состыкуется.

4) Что тюним, что берём уже найденным, и на каких выборках
Что берём “как есть” из вашего пайплайна

ALS hyperparams: best_als_params
Они уже должны быть подобраны на VAL_CS (на задаче “предсказать n−1”).

TF-IDF параметры: best_cb_vec_params
Аналогично — из предыдущего тюнинга (тоже на VAL).

Опционально вы отдельно тюните min_df=1/2 на VAL — это остаётся внешним выбором, но всё равно на VAL, не на TEST.

Что тюним в новых ячейках

CatBoost Ranker hyperparams (на VAL):

depth, learning_rate, l2_leaf_reg, iterations (через early stopping фактически подбирается best_iteration).

Также, по-хорошему, кандидаты и негативы — это тоже гиперпараметры:

M_ALS, M_CB, N_NEG
Но обычно их фиксируют “разумными” и не делают большой grid.

На каких выборках это делается (строго)

Обучение ранкера и подбор гиперпараметров — только на VAL_CS:

ALS/CB артефакты строятся на val_pack["R"]

training pairs строятся из val_pack["eval_f"]

внутренний split делается по group_id (по запросам) внутри VAL (80/20)

Финальная оценка — на TEST_CS:

ALS/CB артефакты пересчитываются на test_pack["R"] (это корректно, так и должно быть)

CatBoost не переобучается на TEST

метрики считаются на test_pack["eval_f"] тем же протоколом ALL/WARM/COLD.

Итоговая схема в одном абзаце

Старые гиперпараметры (ALS, TF-IDF) вы уже нашли на VAL.

Новые гиперпараметры (CatBoost) вы подбираете на VAL (query-split).

Затем фиксируете всё найденное, пересчитываете CF/CB артефакты на TEST и делаете финальный eval на TEST тем же протоколом.

Если вы хотите, я могу дать ещё одну маленькую ячейку “candidate recall диагностика” (на VAL для COLD/WARM), чтобы вы заранее понимали, что ваш потолок по Recall не ограничен кандидаторами. Это обычно спасает часы вычислений.

In [ ]:
# # ======== RUN EVAL (TEST_CS) ========
# outs = {}
# recommenders = {}
# outs = {}
# masks = _get_masks(test_pack)

# outs["Popularity"] = evaluate_pack_subsets(test_pack, make_pop_recommender(test_pack), "Popularity")
# outs["Random"]     = evaluate_pack_subsets(test_pack, make_random_recommender(test_pack), "Random")

# # ItemKNN best params
# w, K_sim, K1, B = best_itemknn_params
# knn_rec = fit_itemknn(test_pack, weighting=w, K_sim=K_sim, bm25_K1=(K1 if K1 else 1.2), bm25_B=(B if B else 0.75))
# outs["ItemKNN"] = evaluate_pack_subsets(test_pack, knn_rec, "ItemKNN")

# # BPR best
# f, lr, reg, it = best_bpr_params
# bpr_rec = fit_bpr(test_pack, factors=f, learning_rate=lr, regularization=reg, iterations=it)
# outs["BPR"] = evaluate_pack_subsets(test_pack, bpr_rec, "BPR")

# # ALS best
# f, reg, it, a = best_als_params
# als_rec = fit_als(test_pack, factors=f, regularization=reg, iterations=it, alpha=a)
# outs["ALS"] = evaluate_pack_subsets(test_pack, als_rec, "ALS")

# # LightFM CF best
# loss, c, lr, ia, ua, ep = best_lfm_cf_params
# lfm_cf_rec = fit_lightfm_cf(test_pack, no_components=c, loss=loss, learning_rate=lr,
#                             item_alpha=ia, user_alpha=ua, epochs=ep, num_threads=8)
# outs["LightFM(CF)"] = evaluate_pack_subsets(test_pack, lfm_cf_rec, "LightFM(CF)")

# # CB + Hybrid (fixed)
# outs["CB(TFIDF)"] = evaluate_pack_subsets(test_pack, cb_rec, "CB(TFIDF)")
# outs["LightFM(Hybrid)"] = evaluate_pack_subsets(test_pack, hyb_rec, "LightFM(Hybrid)")
# outs["Hybrid(Fusion)"] = evaluate_pack_subsets(test_pack, hyb_fused_rec, "Hybrid(Fusion)")

# # ======== SUMMARY TABLE ========
# import pandas as pd

# def to_rows(split, model, out):
#     return [{"split": split, "model": model, "K": int(k), "Recall": float(r), "NDCG": float(n), "MAP": float(m)}
#             for k,(r,n,m) in out.items()]

# rows = []
# for model, d in outs.items():
#     for split in ["ALL","WARM","COLD"]:
#         rows += to_rows(split, model, d[split])

# res_cs = pd.DataFrame(rows).sort_values(["split","K","Recall"], ascending=[True, True, False]).reset_index(drop=True)
# res_cs

[Popularity/ALL] n=69977
[Popularity/ALL] short rec lists: 0/69977 (0.000)

=== Popularity/ALL ===
K= 5 | Recall@5: 0.0076 | NDCG@5: 0.0049 | MAP@5: 0.0040
K=10 | Recall@10: 0.0127 | NDCG@10: 0.0065 | MAP@10: 0.0047
K=20 | Recall@20: 0.0222 | NDCG@20: 0.0089 | MAP@20: 0.0054
K=50 | Recall@50: 0.0406 | NDCG@50: 0.0126 | MAP@50: 0.0059
K=100 | Recall@100: 0.0634 | NDCG@100: 0.0162 | MAP@100: 0.0062

[Popularity/WARM] n=62260
[Popularity/WARM] short rec lists: 0/62260 (0.000)

=== Popularity/WARM ===
K= 5 | Recall@5: 0.0085 | NDCG@5: 0.0055 | MAP@5: 0.0045
K=10 | Recall@10: 0.0143 | NDCG@10: 0.0074 | MAP@10: 0.0053
K=20 | Recall@20: 0.0250 | NDCG@20: 0.0100 | MAP@20: 0.0060
K=50 | Recall@50: 0.0456 | NDCG@50: 0.0141 | MAP@50: 0.0067
K=100 | Recall@100: 0.0713 | NDCG@100: 0.0183 | MAP@100: 0.0070

[Popularity/COLD] n=1552
[Popularity/COLD] short rec lists: 0/1552 (0.000)

=== Popularity/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0000 | NDCG@50: 0.0000 | MAP@50: 0.0000
K=100 | Recall@100: 0.0000 | NDCG@100: 0.0000 | MAP@100: 0.0000

[Random/ALL] n=69977
[Random/ALL] short rec lists: 0/69977 (0.000)

=== Random/ALL ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0003 | NDCG@10: 0.0001 | MAP@10: 0.0001
K=20 | Recall@20: 0.0007 | NDCG@20: 0.0002 | MAP@20: 0.0001
K=50 | Recall@50: 0.0017 | NDCG@50: 0.0004 | MAP@50: 0.0001
K=100 | Recall@100: 0.0029 | NDCG@100: 0.0006 | MAP@100: 0.0002

[Random/WARM] n=62260
[Random/WARM] short rec lists: 0/62260 (0.000)

=== Random/WARM ===
K= 5 | Recall@5: 0.0003 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0004 | NDCG@10: 0.0002 | MAP@10: 0.0001
K=20 | Recall@20: 0.0007 | NDCG@20: 0.0003 | MAP@20: 0.0001
K=50 | Recall@50: 0.0019 | NDCG@50: 0.0005 | MAP@50: 0.0002
K=100 | Recall@100: 0.0035 | NDCG@100: 0.0007 | MAP@100: 0.0002

[Random/COLD] n=1552
[Random/COLD] short rec lists: 0/1552 (0.000)

=== Random/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0013 | NDCG@50: 0.0003 | MAP@50: 0.0000
K=100 | Recall@100: 0.0032 | NDCG@100: 0.0006 | MAP@100: 0.0001

/usr/local/lib/python3.12/dist-packages/implicit/utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.003700733184814453 seconds
  warnings.warn(

  0%|          | 0/69977 [00:00<?, ?it/s]

[ItemKNN/ALL] n=69977
[ItemKNN/ALL] short rec lists: 61542/69977 (0.879)

=== ItemKNN/ALL ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0020 | NDCG@10: 0.0006 | MAP@10: 0.0002
K=20 | Recall@20: 0.0118 | NDCG@20: 0.0029 | MAP@20: 0.0008
K=50 | Recall@50: 0.0224 | NDCG@50: 0.0049 | MAP@50: 0.0011
K=100 | Recall@100: 0.0274 | NDCG@100: 0.0057 | MAP@100: 0.0011

[ItemKNN/WARM] n=62260
[ItemKNN/WARM] short rec lists: 54755/62260 (0.879)

=== ItemKNN/WARM ===
K= 5 | Recall@5: 0.0001 | NDCG@5: 0.0001 | MAP@5: 0.0001
K=10 | Recall@10: 0.0022 | NDCG@10: 0.0007 | MAP@10: 0.0003
K=20 | Recall@20: 0.0132 | NDCG@20: 0.0032 | MAP@20: 0.0008
K=50 | Recall@50: 0.0250 | NDCG@50: 0.0055 | MAP@50: 0.0012
K=100 | Recall@100: 0.0307 | NDCG@100: 0.0064 | MAP@100: 0.0013

[ItemKNN/COLD] n=1552
[ItemKNN/COLD] short rec lists: 1361/1552 (0.877)

=== ItemKNN/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0000 | NDCG@50: 0.0000 | MAP@50: 0.0000
K=100 | Recall@100: 0.0000 | NDCG@100: 0.0000 | MAP@100: 0.0000

  0%|          | 0/200 [00:00<?, ?it/s]

[BPR/ALL] n=69977
[BPR/ALL] short rec lists: 0/69977 (0.000)

=== BPR/ALL ===
K= 5 | Recall@5: 0.0088 | NDCG@5: 0.0055 | MAP@5: 0.0044
K=10 | Recall@10: 0.0161 | NDCG@10: 0.0078 | MAP@10: 0.0053
K=20 | Recall@20: 0.0275 | NDCG@20: 0.0106 | MAP@20: 0.0061
K=50 | Recall@50: 0.0535 | NDCG@50: 0.0157 | MAP@50: 0.0069
K=100 | Recall@100: 0.0855 | NDCG@100: 0.0209 | MAP@100: 0.0073

[BPR/WARM] n=62260
[BPR/WARM] short rec lists: 0/62260 (0.000)

=== BPR/WARM ===
K= 5 | Recall@5: 0.0099 | NDCG@5: 0.0061 | MAP@5: 0.0049
K=10 | Recall@10: 0.0181 | NDCG@10: 0.0087 | MAP@10: 0.0060
K=20 | Recall@20: 0.0309 | NDCG@20: 0.0119 | MAP@20: 0.0068
K=50 | Recall@50: 0.0601 | NDCG@50: 0.0177 | MAP@50: 0.0077
K=100 | Recall@100: 0.0961 | NDCG@100: 0.0235 | MAP@100: 0.0082

[BPR/COLD] n=1552
[BPR/COLD] short rec lists: 0/1552 (0.000)

=== BPR/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0000 | NDCG@50: 0.0000 | MAP@50: 0.0000
K=100 | Recall@100: 0.0000 | NDCG@100: 0.0000 | MAP@100: 0.0000

/usr/local/lib/python3.12/dist-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 2 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

  0%|          | 0/40 [00:00<?, ?it/s]

[ALS/ALL] n=69977
[ALS/ALL] short rec lists: 0/69977 (0.000)

=== ALS/ALL ===
K= 5 | Recall@5: 0.0245 | NDCG@5: 0.0154 | MAP@5: 0.0124
K=10 | Recall@10: 0.0404 | NDCG@10: 0.0205 | MAP@10: 0.0145
K=20 | Recall@20: 0.0662 | NDCG@20: 0.0270 | MAP@20: 0.0163
K=50 | Recall@50: 0.1161 | NDCG@50: 0.0368 | MAP@50: 0.0178
K=100 | Recall@100: 0.1675 | NDCG@100: 0.0452 | MAP@100: 0.0186

[ALS/WARM] n=62260
[ALS/WARM] short rec lists: 0/62260 (0.000)

=== ALS/WARM ===
K= 5 | Recall@5: 0.0275 | NDCG@5: 0.0173 | MAP@5: 0.0140
K=10 | Recall@10: 0.0454 | NDCG@10: 0.0231 | MAP@10: 0.0163
K=20 | Recall@20: 0.0744 | NDCG@20: 0.0304 | MAP@20: 0.0183
K=50 | Recall@50: 0.1305 | NDCG@50: 0.0414 | MAP@50: 0.0201
K=100 | Recall@100: 0.1883 | NDCG@100: 0.0508 | MAP@100: 0.0209

[ALS/COLD] n=1552
[ALS/COLD] short rec lists: 0/1552 (0.000)

=== ALS/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0000 | NDCG@50: 0.0000 | MAP@50: 0.0000
K=100 | Recall@100: 0.0000 | NDCG@100: 0.0000 | MAP@100: 0.0000

[LightFM(CF)/ALL] n=69977
[LightFM(CF)/ALL] short rec lists: 0/69977 (0.000)

=== LightFM(CF)/ALL ===
K= 5 | Recall@5: 0.0216 | NDCG@5: 0.0134 | MAP@5: 0.0107
K=10 | Recall@10: 0.0362 | NDCG@10: 0.0181 | MAP@10: 0.0126
K=20 | Recall@20: 0.0583 | NDCG@20: 0.0236 | MAP@20: 0.0141
K=50 | Recall@50: 0.1034 | NDCG@50: 0.0325 | MAP@50: 0.0155
K=100 | Recall@100: 0.1574 | NDCG@100: 0.0412 | MAP@100: 0.0163

[LightFM(CF)/WARM] n=62260
[LightFM(CF)/WARM] short rec lists: 0/62260 (0.000)

=== LightFM(CF)/WARM ===
K= 5 | Recall@5: 0.0243 | NDCG@5: 0.0151 | MAP@5: 0.0121
K=10 | Recall@10: 0.0407 | NDCG@10: 0.0203 | MAP@10: 0.0142
K=20 | Recall@20: 0.0656 | NDCG@20: 0.0266 | MAP@20: 0.0159
K=50 | Recall@50: 0.1162 | NDCG@50: 0.0365 | MAP@50: 0.0175
K=100 | Recall@100: 0.1769 | NDCG@100: 0.0463 | MAP@100: 0.0183

[LightFM(CF)/COLD] n=1552
[LightFM(CF)/COLD] short rec lists: 0/1552 (0.000)

=== LightFM(CF)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0000 | NDCG@50: 0.0000 | MAP@50: 0.0000
K=100 | Recall@100: 0.0000 | NDCG@100: 0.0000 | MAP@100: 0.0000

[CB(TFIDF)/ALL] n=69977
[CB(TFIDF)/ALL] short rec lists: 69977/69977 (1.000)

=== CB(TFIDF)/ALL ===
K= 5 | Recall@5: 0.0024 | NDCG@5: 0.0016 | MAP@5: 0.0014
K=10 | Recall@10: 0.0043 | NDCG@10: 0.0022 | MAP@10: 0.0016
K=20 | Recall@20: 0.0073 | NDCG@20: 0.0030 | MAP@20: 0.0018
K=50 | Recall@50: 0.0146 | NDCG@50: 0.0044 | MAP@50: 0.0020
K=100 | Recall@100: 0.0146 | NDCG@100: 0.0044 | MAP@100: 0.0020

[CB(TFIDF)/WARM] n=62260
[CB(TFIDF)/WARM] short rec lists: 62260/62260 (1.000)

=== CB(TFIDF)/WARM ===
K= 5 | Recall@5: 0.0026 | NDCG@5: 0.0018 | MAP@5: 0.0015
K=10 | Recall@10: 0.0047 | NDCG@10: 0.0024 | MAP@10: 0.0018
K=20 | Recall@20: 0.0078 | NDCG@20: 0.0032 | MAP@20: 0.0020
K=50 | Recall@50: 0.0156 | NDCG@50: 0.0048 | MAP@50: 0.0022
K=100 | Recall@100: 0.0156 | NDCG@100: 0.0048 | MAP@100: 0.0022

[CB(TFIDF)/COLD] n=1552
[CB(TFIDF)/COLD] short rec lists: 1552/1552 (1.000)

=== CB(TFIDF)/COLD ===
K= 5 | Recall@5: 0.0006 | NDCG@5: 0.0006 | MAP@5: 0.0006
K=10 | Recall@10: 0.0006 | NDCG@10: 0.0006 | MAP@10: 0.0006
K=20 | Recall@20: 0.0032 | NDCG@20: 0.0013 | MAP@20: 0.0008
K=50 | Recall@50: 0.0064 | NDCG@50: 0.0019 | MAP@50: 0.0009
K=100 | Recall@100: 0.0064 | NDCG@100: 0.0019 | MAP@100: 0.0009

[LightFM(Hybrid)/ALL] n=69977
[LightFM(Hybrid)/ALL] short rec lists: 0/69977 (0.000)

=== LightFM(Hybrid)/ALL ===
K= 5 | Recall@5: 0.0069 | NDCG@5: 0.0043 | MAP@5: 0.0034
K=10 | Recall@10: 0.0118 | NDCG@10: 0.0058 | MAP@10: 0.0040
K=20 | Recall@20: 0.0202 | NDCG@20: 0.0080 | MAP@20: 0.0046
K=50 | Recall@50: 0.0396 | NDCG@50: 0.0118 | MAP@50: 0.0052
K=100 | Recall@100: 0.0639 | NDCG@100: 0.0157 | MAP@100: 0.0056

[LightFM(Hybrid)/WARM] n=62260
[LightFM(Hybrid)/WARM] short rec lists: 0/62260 (0.000)

=== LightFM(Hybrid)/WARM ===
K= 5 | Recall@5: 0.0077 | NDCG@5: 0.0048 | MAP@5: 0.0038
K=10 | Recall@10: 0.0132 | NDCG@10: 0.0065 | MAP@10: 0.0045
K=20 | Recall@20: 0.0226 | NDCG@20: 0.0089 | MAP@20: 0.0052
K=50 | Recall@50: 0.0441 | NDCG@50: 0.0131 | MAP@50: 0.0058
K=100 | Recall@100: 0.0711 | NDCG@100: 0.0175 | MAP@100: 0.0062

[LightFM(Hybrid)/COLD] n=1552
[LightFM(Hybrid)/COLD] short rec lists: 0/1552 (0.000)

=== LightFM(Hybrid)/COLD ===
K= 5 | Recall@5: 0.0000 | NDCG@5: 0.0000 | MAP@5: 0.0000
K=10 | Recall@10: 0.0000 | NDCG@10: 0.0000 | MAP@10: 0.0000
K=20 | Recall@20: 0.0000 | NDCG@20: 0.0000 | MAP@20: 0.0000
K=50 | Recall@50: 0.0013 | NDCG@50: 0.0002 | MAP@50: 0.0000
K=100 | Recall@100: 0.0058 | NDCG@100: 0.0010 | MAP@100: 0.0001

[Hybrid(Fusion)/ALL] n=69977
[Hybrid(Fusion)/ALL] short rec lists: 0/69977 (0.000)

=== Hybrid(Fusion)/ALL ===
K= 5 | Recall@5: 0.0056 | NDCG@5: 0.0033 | MAP@5: 0.0026
K=10 | Recall@10: 0.0098 | NDCG@10: 0.0047 | MAP@10: 0.0032
K=20 | Recall@20: 0.0164 | NDCG@20: 0.0063 | MAP@20: 0.0036
K=50 | Recall@50: 0.0323 | NDCG@50: 0.0095 | MAP@50: 0.0041
K=100 | Recall@100: 0.0531 | NDCG@100: 0.0128 | MAP@100: 0.0044

[Hybrid(Fusion)/WARM] n=62260
[Hybrid(Fusion)/WARM] short rec lists: 0/62260 (0.000)

=== Hybrid(Fusion)/WARM ===
K= 5 | Recall@5: 0.0062 | NDCG@5: 0.0037 | MAP@5: 0.0029
K=10 | Recall@10: 0.0108 | NDCG@10: 0.0052 | MAP@10: 0.0035
K=20 | Recall@20: 0.0181 | NDCG@20: 0.0070 | MAP@20: 0.0040
K=50 | Recall@50: 0.0357 | NDCG@50: 0.0105 | MAP@50: 0.0045
K=100 | Recall@100: 0.0587 | NDCG@100: 0.0142 | MAP@100: 0.0049

[Hybrid(Fusion)/COLD] n=1552
[Hybrid(Fusion)/COLD] short rec lists: 0/1552 (0.000)

=== Hybrid(Fusion)/COLD ===
K= 5 | Recall@5: 0.0006 | NDCG@5: 0.0003 | MAP@5: 0.0002
K=10 | Recall@10: 0.0006 | NDCG@10: 0.0003 | MAP@10: 0.0002
K=20 | Recall@20: 0.0013 | NDCG@20: 0.0004 | MAP@20: 0.0002
K=50 | Recall@50: 0.0058 | NDCG@50: 0.0013 | MAP@50: 0.0003
K=100 | Recall@100: 0.0084 | NDCG@100: 0.0017 | MAP@100: 0.0004

    split            model    K    Recall      NDCG       MAP
0     ALL              ALS    5  0.024451  0.015383  0.012422
1     ALL      LightFM(CF)    5  0.021593  0.013397  0.010727
2     ALL              BPR    5  0.008831  0.005455  0.004358
3     ALL       Popularity    5  0.007602  0.004899  0.004032
4     ALL  LightFM(Hybrid)    5  0.006931  0.004280  0.003414
..    ...              ...  ...       ...       ...       ...
130  WARM  LightFM(Hybrid)  100  0.071121  0.017489  0.006213
131  WARM   Hybrid(Fusion)  100  0.058721  0.014173  0.004851
132  WARM          ItemKNN  100  0.030710  0.006425  0.001265
133  WARM        CB(TFIDF)  100  0.015628  0.004757  0.002222
134  WARM           Random  100  0.003469  0.000743  0.000194

[135 rows x 6 columns]

In [ ]:
pd.set_option('display.max_rows', 200)

In [ ]:
res_cs

    split            model    K    Recall      NDCG       MAP
0     ALL              ALS    5  0.024451  0.015383  0.012422
1     ALL      LightFM(CF)    5  0.021593  0.013397  0.010727
2     ALL              BPR    5  0.008831  0.005455  0.004358
3     ALL       Popularity    5  0.007602  0.004899  0.004032
4     ALL  LightFM(Hybrid)    5  0.006931  0.004280  0.003414
5     ALL   Hybrid(Fusion)    5  0.005588  0.003342  0.002614
6     ALL        CB(TFIDF)    5  0.002401  0.001624  0.001368
7     ALL           Random    5  0.000129  0.000072  0.000054
8     ALL          ItemKNN    5  0.000100  0.000066  0.000055
9     ALL              ALS   10  0.040413  0.020528  0.014536
10    ALL      LightFM(CF)   10  0.036226  0.018090  0.012641
11    ALL              BPR   10  0.016077  0.007776  0.005304
12    ALL       Popularity   10  0.012733  0.006542  0.004702
13    ALL  LightFM(Hybrid)   10  0.011818  0.005837  0.004042
14    ALL   Hybrid(Fusion)   10  0.009789  0.004684  0.003159
15    ALL        CB(TFIDF)   10  0.004287  0.002226  0.001612
16    ALL          ItemKNN   10  0.002001  0.000618  0.000247
17    ALL           Random   10  0.000272  0.000119  0.000074
18    ALL              ALS   20  0.066179  0.027010  0.016298
19    ALL      LightFM(CF)   20  0.058348  0.023646  0.014147
20    ALL              BPR   20  0.027466  0.010630  0.006074
21    ALL       Popularity   20  0.022222  0.008930  0.005351
22    ALL  LightFM(Hybrid)   20  0.020250  0.007956  0.004618
23    ALL   Hybrid(Fusion)   20  0.016434  0.006341  0.003601
24    ALL          ItemKNN   20  0.011761  0.002868  0.000756
25    ALL        CB(TFIDF)   20  0.007288  0.002987  0.001822
26    ALL           Random   20  0.000672  0.000222  0.000103
27    ALL              ALS   50  0.116124  0.036849  0.017849
28    ALL      LightFM(CF)   50  0.103420  0.032511  0.015538
29    ALL              BPR   50  0.053475  0.015747  0.006878
30    ALL       Popularity   50  0.040613  0.012568  0.005931
31    ALL  LightFM(Hybrid)   50  0.039627  0.011762  0.005213
32    ALL   Hybrid(Fusion)   50  0.032339  0.009451  0.004082
33    ALL          ItemKNN   50  0.022364  0.004919  0.001062
34    ALL        CB(TFIDF)   50  0.014576  0.004411  0.002042
35    ALL           Random   50  0.001715  0.000427  0.000136
36    ALL              ALS  100  0.167526  0.045165  0.018575
37    ALL      LightFM(CF)  100  0.157352  0.041222  0.016295
38    ALL              BPR  100  0.085500  0.020915  0.007325
39    ALL  LightFM(Hybrid)  100  0.063935  0.015694  0.005556
40    ALL       Popularity  100  0.063407  0.016248  0.006250
41    ALL   Hybrid(Fusion)  100  0.053146  0.012817  0.004376
42    ALL          ItemKNN  100  0.027409  0.005740  0.001135
43    ALL        CB(TFIDF)  100  0.014576  0.004411  0.002042
44    ALL           Random  100  0.002944  0.000626  0.000153
45   COLD        CB(TFIDF)    5  0.000644  0.000644  0.000644
46   COLD   Hybrid(Fusion)    5  0.000644  0.000277  0.000161
47   COLD       Popularity    5  0.000000  0.000000  0.000000
48   COLD           Random    5  0.000000  0.000000  0.000000
49   COLD          ItemKNN    5  0.000000  0.000000  0.000000
50   COLD              BPR    5  0.000000  0.000000  0.000000
51   COLD              ALS    5  0.000000  0.000000  0.000000
52   COLD      LightFM(CF)    5  0.000000  0.000000  0.000000
53   COLD  LightFM(Hybrid)    5  0.000000  0.000000  0.000000
54   COLD        CB(TFIDF)   10  0.000644  0.000644  0.000644
55   COLD   Hybrid(Fusion)   10  0.000644  0.000277  0.000161
56   COLD       Popularity   10  0.000000  0.000000  0.000000
57   COLD           Random   10  0.000000  0.000000  0.000000
58   COLD          ItemKNN   10  0.000000  0.000000  0.000000
59   COLD              BPR   10  0.000000  0.000000  0.000000
60   COLD              ALS   10  0.000000  0.000000  0.000000
61   COLD      LightFM(CF)   10  0.000000  0.000000  0.000000
62   COLD  LightFM(Hybrid)   10  0.000000  0.000000  0.000000
63   COLD        CB(TFIDF)   20  0.003222  0.001288  0.000817
64   COLD   Hybrid(Fusion)   20  0.001289  0.000442  0.000207
65   COLD       Popularity   20  0.000000  0.000000  0.000000
66   COLD           Random   20  0.000000  0.000000  0.000000
67   COLD          ItemKNN   20  0.000000  0.000000  0.000000
68   COLD              BPR   20  0.000000  0.000000  0.000000
69   COLD              ALS   20  0.000000  0.000000  0.000000
70   COLD      LightFM(CF)   20  0.000000  0.000000  0.000000
71   COLD  LightFM(Hybrid)   20  0.000000  0.000000  0.000000
72   COLD        CB(TFIDF)   50  0.006443  0.001924  0.000917
73   COLD   Hybrid(Fusion)   50  0.005799  0.001301  0.000330
74   COLD           Random   50  0.001289  0.000256  0.000041
75   COLD  LightFM(Hybrid)   50  0.001289  0.000248  0.000036
76   COLD       Popularity   50  0.000000  0.000000  0.000000
77   COLD          ItemKNN   50  0.000000  0.000000  0.000000
78   COLD              BPR   50  0.000000  0.000000  0.000000
79   COLD              ALS   50  0.000000  0.000000  0.000000
80   COLD      LightFM(CF)   50  0.000000  0.000000  0.000000
81   COLD   Hybrid(Fusion)  100  0.008376  0.001717  0.000366
82   COLD        CB(TFIDF)  100  0.006443  0.001924  0.000917
83   COLD  LightFM(Hybrid)  100  0.005799  0.000967  0.000096
84   COLD           Random  100  0.003222  0.000567  0.000067
85   COLD       Popularity  100  0.000000  0.000000  0.000000
86   COLD          ItemKNN  100  0.000000  0.000000  0.000000
87   COLD              BPR  100  0.000000  0.000000  0.000000
88   COLD              ALS  100  0.000000  0.000000  0.000000
89   COLD      LightFM(CF)  100  0.000000  0.000000  0.000000
90   WARM              ALS    5  0.027482  0.017289  0.013962
91   WARM      LightFM(CF)    5  0.024269  0.015057  0.012057
92   WARM              BPR    5  0.009926  0.006131  0.004899
93   WARM       Popularity    5  0.008545  0.005506  0.004532
94   WARM  LightFM(Hybrid)    5  0.007742  0.004791  0.003826
95   WARM   Hybrid(Fusion)    5  0.006168  0.003705  0.002907
96   WARM        CB(TFIDF)    5  0.002618  0.001780  0.001503
97   WARM           Random    5  0.000257  0.000137  0.000099
98   WARM          ItemKNN    5  0.000096  0.000064  0.000054
99   WARM              ALS   10  0.045422  0.023073  0.016338
100  WARM      LightFM(CF)   10  0.040716  0.020332  0.014207
101  WARM              BPR   10  0.018069  0.008739  0.005961
102  WARM       Popularity   10  0.014311  0.007353  0.005284
103  WARM  LightFM(Hybrid)   10  0.013187  0.006525  0.004526
104  WARM   Hybrid(Fusion)   10  0.010777  0.005178  0.003505
105  WARM        CB(TFIDF)   10  0.004658  0.002430  0.001766
106  WARM          ItemKNN   10  0.002233  0.000684  0.000270
107  WARM           Random   10  0.000369  0.000173  0.000114
108  WARM              ALS   20  0.074382  0.030358  0.018319
109  WARM      LightFM(CF)   20  0.065580  0.026577  0.015900
110  WARM              BPR   20  0.030871  0.011948  0.006827
111  WARM       Popularity   20  0.024976  0.010036  0.006014
112  WARM  LightFM(Hybrid)   20  0.022615  0.008895  0.005169
113  WARM   Hybrid(Fusion)   20  0.018134  0.007011  0.003993
114  WARM          ItemKNN   20  0.013203  0.003214  0.000841
115  WARM        CB(TFIDF)   20  0.007790  0.003223  0.001985
116  WARM           Random   20  0.000723  0.000262  0.000138
117  WARM              ALS   50  0.130517  0.041416  0.020061
118  WARM      LightFM(CF)   50  0.116238  0.036541  0.017464
119  WARM              BPR   50  0.060103  0.017699  0.007730
120  WARM       Popularity   50  0.045647  0.014126  0.006666
121  WARM  LightFM(Hybrid)   50  0.044121  0.013122  0.005832
122  WARM   Hybrid(Fusion)   50  0.035737  0.010454  0.004526
123  WARM          ItemKNN   50  0.025040  0.005503  0.001183
124  WARM        CB(TFIDF)   50  0.015628  0.004757  0.002222
125  WARM           Random   50  0.001879  0.000488  0.000172
126  WARM              ALS  100  0.188291  0.050763  0.020877
127  WARM      LightFM(CF)  100  0.176855  0.046332  0.018314
128  WARM              BPR  100  0.096097  0.023507  0.008233
129  WARM       Popularity  100  0.071266  0.018262  0.007025
130  WARM  LightFM(Hybrid)  100  0.071121  0.017489  0.006213
131  WARM   Hybrid(Fusion)  100  0.058721  0.014173  0.004851
132  WARM          ItemKNN  100  0.030710  0.006425  0.001265
133  WARM        CB(TFIDF)  100  0.015628  0.004757  0.002222
134  WARM           Random  100  0.003469  0.000743  0.000194

## Duplicate evaluation cell (disabled)
The evaluation logic is implemented in the previous cell.